### ISSUE TITLE
Skipping frames for Vier.be

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#1089]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/1089) by Siemon Geeroms (Bitbucket: [siemonG](https://bitbucket.org/siemonG), ).**

----------------------------------------

First of all thanks for the add-on! 

Almost everthing is working as desired but I have a minor issue playing streams from Vier,  every once in a while a few frames are skipped. I first tought this was an issue with buffering on my raspberry but I also have this issue on my laptop. The strange part is that it always occurrs on the exact same time position, for example  series "de dag" aflv 3 at 38:24.

Thanks in advanced

Siemon

**Comment by dagwieers** [comment]
cc @abanink @peno64 @Arathonk @michaelarnauts @amelsfort

**Comment by dagwieers** [comment]
With the release of a new season of Callboys, we are again affected by this issue.
And we need to switch back to OMXPlayer to make it somewhat workable.
However enabling OMXPlayer causes issues with **inputstream.adaptive** playback.

**Comment by Stavr0sStuff** [comment]
I can second this. Callboys S02E01 on Vier frequently stalls and goes back X seconds/minutes in time. This issue thread is rather long and contains lots of references to concepts I don't know (e.g. I don't understand what "However enabling OMXPlayer causes issues with inputstream.adaptive playback." means), so forgive me if the answer is somewhere in here, but: is there a workaround for this problem on OSMC+ retrospect?

**Comment by basrieter** [comment]
There was a fix here: https://github.com/xbmc/xbmc/issues/16003

But it was not further implemented. I commented on that issue. I suggest more people do so, as I can't fix this from a Retrospect perspective. The vier.be streams are just crappy (from a demux point of view) and Kodi has issues reading.

**Comment by XwhitewidowX** [comment]
Also have this problem with ‘de slimste mens’ on my Nvidia Shield TV.

**Comment by dagwieers** [comment]
I am not sure if the streams are crap, at least the player they use (and ffmpeg) doesn't fall over like Kodi does. So I would rather blame the Kodi player for not being able to handle these streams.

**Comment by TomHillaert** [comment]
So what's the status of this issue ? Still having vier streams skipping frames or hanging, sometimes sound continues and video comes back after some seconds... And sometimes it just hangs completely

**Comment by basrieter** [comment]
It has to do with the Kodi player. I personally don't experience this. Perhaps somebody can try a Kodi Matrix build?

**Comment by Stavr0sStuff** [comment]
Once i switched the video player in kodi settings to the OMX one (or the
other one, i don't remember) i didn't experience the issue again. No
further tweaks/patches required.

**Comment by basrieter** [comment]
Great and good to hear.

**Comment by dagwieers** [comment]
@Stavr0sStuff Beware that the OMXPlayer only works on RPi3 and older, so is not a solution for any other architecture. Also, in the upcoming Matrix they have removed OMXPlayer even for RPI3 and older. So we need a proper fix in inputstream.adaptive and/or Kodi.

This is also the main reason why **[plugin.video.viervijfzes](https://github.com/add-ons/plugin.video.viervijfzes)** has not been released to the public yet.
