### ISSUE TITLE
problems stievie

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#1133]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/1133) by xiaomimibox (Bitbucket: [xiaominmibox](https://bitbucket.org/xiaominmibox), ).**

----------------------------------------

these problems started yesterday, the day before everything worked great

* Live streams of channels on Stievie stopped working
* lower resolution 
* clicking some shows in the timeline closes kodi completely (on android tv)

**Comment by dagwieers** [comment]
I don't have any problems with Stievie, it has been working perfectly. Maybe this one can be closed?
