### ISSUE TITLE
Feature request: Configure swedish channels for paying user

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#1165]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/1165) by Anton Berggren (Bitbucket: [orfeous1](https://bitbucket.org/orfeous1), GitHub: [orfeous1](https://github.com/orfeous1)).**

----------------------------------------

It would be nice to configure like [dplay.se](http://dplay.se) or [tv4.se](http://tv4.se) and put my username and password so i can view content that only shows for paying users. For now there are only 7 channels to put username and passord on. And its not swedish channels.

**Comment by mcrypt** [comment]
What is the status on this? The national football league in Sweden has just started back up, and it is exclusively broadcast on the dplay streaming platform here in Sweden. There is massive problems with streaming the actual games.. Everyone is up in arms about it.. People are fed up, Journalists call it the biggest fiasco ever. How cool wouldn't it be if we could get this working flawlessly on kodi using the retrospect plugin? lol. From what i've read about it, i think it's mostly a problem with the apps they use on various hardware, samsung-tv related mostly.

**Comment by basrieter** [comment]
Dplay.se already has the option to configure a username and password.

**Comment by mcrypt** [comment]
oh i see, excellent.. i will upgrade, thank you!

**Comment by basrieter** [comment]
Please install it via the Kodi repository if you run Leia or Matrix.
