### ISSUE TITLE
News programs on SVT play end with a freeze and annoying sound

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#1168]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/1168) by Snah (Bitbucket: [Snaah](https://bitbucket.org/Snaah), GitHub: [Snaah](https://github.com/Snaah)).**

----------------------------------------

When the news programs Aktuellt and Rapport end Retrospect freezes and an annoying sound is played. Possibly because of local news and culture news being broadcast as a separate streams after the national news. Tested on Windows 10, Android and Android TV with same result. Attaching a screen recording too.

Edit: Bitbucket doesn’t like my video file. Try [https://myfile.is/HbBey9ten4/retro\_error\_mp4](https://myfile.is/HbBey9ten4/retro_error_mp4)

**Comment by Snaah** [comment]
@basrieter I just tried the SVT add-on in the Kodi repository and there it works just like it should. No annoying sound in the end.

**Comment by basrieter** [comment]
Try disabling the InputStream Adaptive for SVT and test that.

**Comment by Snaah** [comment]
Without using InputStream Adaptive I get picture, but no sound.

**Comment by basrieter** [comment]
Try the SVT Patched version in #1217

**Comment by Snaah** [comment]
Workin like it should now! Great work, Bas!
