### ISSUE TITLE
Add support for TVL (Flanders/Regional)

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#1200]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/1200) by Dag Wieers (Bitbucket: [dagwieers](https://bitbucket.org/dagwieers), GitHub: [dagwieers](https://github.com/dagwieers)).**

----------------------------------------

It would be nice to see TVL \([https://www.tvl.be/](https://www.tvl.be)\) support.

This is the Limburg regional TV station.

It also has a live stream at: [https://player-api.new.livestream.com/accounts/27755193/events/8452383/live.m3u8](https://player-api.new.livestream.com/accounts/27755193/events/8452383/live.m3u8)

**Comment by dagwieers** [comment]
I started [plugin.video.regiotv](https://github.com/dagwieers/plugin.video.regiotv) that includes the TVL live stream among many other Flemish regional stations.

**Comment by peno64** [comment]
Je kan dit reeds bekijken via https://github.com/Opvolger/plugin.video.hanssettings

**Comment by basrieter** [comment]
Then no need to add it in Retrospect
