### ISSUE TITLE
Add support for TVOost (Flanders/Regional)

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#1201]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/1201) by Dag Wieers (Bitbucket: [dagwieers](https://bitbucket.org/dagwieers), GitHub: [dagwieers](https://github.com/dagwieers)).**

----------------------------------------

It would be nice to see TVOost \([https://www.tvoost.be/](https://www.tvoost.be)\) support in Retrospect.

This is the regional TV station for Oost-Vlaanderen.

It also has a live stream at: [https://www.tvoost.be/live](https://www.tvoost.be/live)

**Comment by dagwieers** [comment]
I started [plugin.video.regiotv](https://github.com/dagwieers/plugin.video.regiotv) that includes the TV Oost live stream among many other Flemish regional stations.

**Comment by peno64** [comment]
You can already watch this via https://github.com/Opvolger/plugin.video.hanssettings

**Comment by basrieter** [comment]
Then no need to add it in Retrospect
