### ISSUE TITLE
Add support for BVN (Flanders/Netherlands)

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#1203]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/1203) by Dag Wieers (Bitbucket: [dagwieers](https://bitbucket.org/dagwieers), GitHub: [dagwieers](https://github.com/dagwieers)).**

----------------------------------------

It would be very interesting to see BVN \([https://www.bvn.tv](https://www.bvn.tv)\) support in Retrospect.

BVN has a lot of quality content and is quite popular with expats.

It has both VOD content and a live stream at: [https://npobvn-prd.cdn.eurovisioncdn.net/live/npo/u/npo/drm/dash\_cenc/bvn/0/0/0/bvn.isml/stream.mpd](https://npobvn-prd.cdn.eurovisioncdn.net/live/npo/u/npo/drm/dash_cenc/bvn/0/0/0/bvn.isml/stream.mpd)

**Comment by michaelarnauts** [comment]
For the live stream:

1. scrape https://www.bvn.tv/bvnlive/
2. find the iframe tag to get the jwt: https://start-player.npo.nl/embed/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJza2lwQ2F0YWxvZyI6MCwidXNlRW5jcnlwdGlvbiI6ImRybSIsImF1dG9wbGF5IjoiMSIsImhhc0FkQ29uc2VudCI6IjEiLCJzdGVyU2l0ZUlkIjoiYnZuIiwic3RlcklkZW50aWZpZXIiOiJidm4tZGVza3RvcCIsInN0ZXJSZWZlcnJhbFVybCI6Imh0dHBzOlwvXC93d3cuYnZuLnR2XC9idm5saXZlIiwic2hhcmUiOiIwIiwic21hcnR0YWciOnsic2l0ZUlkIjoiMjYifSwiaWF0IjoxNTY3OTc1NjgwLCJuYmYiOjE1Njc5NzU2ODAsImV4cCI6MTU2ODAwNDQ4MCwiY29uc3VtZXJJZCI6IjQ0ZDVmY2UzLWU2M2EtNDc4ZS04YTVjLTNhOGQ0YTJmYjNiNCIsIm1lZGlhSWQiOiJMSV9CVk5fNDU4OTEwNyIsImlzUGxheWxpc3QiOmZhbHNlLCJyZWZlcnJlclVybCI6bnVsbCwibm9BZHMiOjAsInJlY29tbWVuZGF0aW9ucyI6MSwiaXNzIjoiZXlKcGRpSTZJa1JTYmxKNGJIQkdVamh6WEM5Q2NYcFdRM0pGUkUxQlBUMGlMQ0oyWVd4MVpTSTZJbUo2YTI1TmFWUkRlVTFtVGtaSFNXdzBTRFJrV2tsRVZtcE1WekZaT1haMmRGaHdlVlpTYjFkclMybG5UbXRMUXpSNVducDBSblJWVmt3MWFWSm5RbklpTENKdFlXTWlPaUl4TWpWbFlUWm1PV0prWlRVd1pUWXpZVFkxWldVeU56TXpNbVU0Tmpaa1pHVXpOV1ZsTURNeVlqTTJNREF4TUdRNU1tRXlOVGswWXpnM01tWTFZalUzSW4wPSJ9.NBp9kj7i1Y-Po82QiYe3uD6kgs6FpN6FcHpntI7gbjc

3. use the jwt to construct the url to fetch https://start-player.npo.nl/video/LI_BVN_4589107/streams?profile=dash-widevine&quality=npo&tokenId=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJza2lwQ2F0YWxvZyI6MCwidXNlRW5jcnlwdGlvbiI6ImRybSIsImF1dG9wbGF5IjoiMSIsImhhc0FkQ29uc2VudCI6IjEiLCJzdGVyU2l0ZUlkIjoiYnZuIiwic3RlcklkZW50aWZpZXIiOiJidm4tZGVza3RvcCIsInN0ZXJSZWZlcnJhbFVybCI6Imh0dHBzOlwvXC93d3cuYnZuLnR2XC9idm5saXZlIiwic2hhcmUiOiIwIiwic21hcnR0YWciOnsic2l0ZUlkIjoiMjYifSwiaWF0IjoxNTY3OTc1NjgwLCJuYmYiOjE1Njc5NzU2ODAsImV4cCI6MTU2ODAwNDQ4MCwiY29uc3VtZXJJZCI6IjQ0ZDVmY2UzLWU2M2EtNDc4ZS04YTVjLTNhOGQ0YTJmYjNiNCIsIm1lZGlhSWQiOiJMSV9CVk5fNDU4OTEwNyIsImlzUGxheWxpc3QiOmZhbHNlLCJyZWZlcnJlclVybCI6bnVsbCwibm9BZHMiOjAsInJlY29tbWVuZGF0aW9ucyI6MSwiaXNzIjoiZXlKcGRpSTZJa1JTYmxKNGJIQkdVamh6WEM5Q2NYcFdRM0pGUkUxQlBUMGlMQ0oyWVd4MVpTSTZJbUo2YTI1TmFWUkRlVTFtVGtaSFNXdzBTRFJrV2tsRVZtcE1WekZaT1haMmRGaHdlVlpTYjFkclMybG5UbXRMUXpSNVducDBSblJWVmt3MWFWSm5RbklpTENKdFlXTWlPaUl4TWpWbFlUWm1PV0prWlRVd1pUWXpZVFkxWldVeU56TXpNbVU0Tmpaa1pHVXpOV1ZsTURNeVlqTTJNREF4TUdRNU1tRXlOVGswWXpnM01tWTFZalUzSW4wPSJ9.NBp9kj7i1Y-Po82QiYe3uD6kgs6FpN6FcHpntI7gbjc&streamType=livetv&mobile=0&ios=0&isChromecast=0

This will return this:
```
{
   "stream":{
      "src":"https:\/\/npobvn-prd.cdn.eurovisioncdn.net\/live\/npo\/u\/npo\/drm\/dash_cenc\/bvn\/0\/0\/0\/bvn.isml\/stream.mpd",
      "type":"application\/dash+xml",
      "keySystemOptions":[
         {
            "name":"com.widevine.alpha",
            "options":{
               "licenseUrl":"https:\/\/npo-drm-gateway.samgcloud.nepworldwide.nl\/authentication",
               "httpRequestHeaders":{
                  "x-custom-data":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJucG8iLCJpYXQiOjE1Njc5NzU3MjEsImRybV90eXBlIjoid2lkZXZpbmUiLCJsaWNlbnNlX3Byb2ZpbGUiOiJ3ZWIiLCJjbGllbnRfaXAiOiI3OC4xMTAuMTk2LjEzIn0.UhjQRjahL5VY_baEiWfCO6myKZnJzFVO2EQEybMS4VE"
               }
            }
         }
      ]
   },
   "catchupAvailable":false,
   "selectedQuality":"npo",
   "debug":{
      "skipCatalog":false,
      "skipAds":false,
      "selectedQuality":"npo",
      "profile":"dash-widevine",
      "stream":"https:\/\/npobvn-prd.cdn.eurovisioncdn.net\/live\/npo\/u\/npo\/drm\/dash_cenc\/bvn\/0\/0\/0\/bvn.isml\/stream.mpd",
      "streamType":"dash_cenc"
   }
}
```

Start the stream and pass the widevine attributes

**Comment by peno64** [comment]
Je kan dit reeds bekijken via https://github.com/Opvolger/plugin.video.hanssettings

**Comment by basrieter** [comment]
Then no need to add it in Retrospect

**Comment by dagwieers** [comment]
@peno64 De stream uit de Hanssettings add-on lijkt eerder illegaal. En er is ook geen VOD support voor BVN in Hanssettings.
