### ISSUE TITLE
Add duration and "Watchable until" to Viafree channels

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#1205]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/1205) by Snah (Bitbucket: [Snaah](https://bitbucket.org/Snaah), GitHub: [Snaah](https://github.com/Snaah)).**

----------------------------------------

Days left are under label **u'time\_left'**, sometimes followed by **u'days**. If it’s set to 0, it means it will expire by the end of the day.

Duration is in seconds under label **u'duration'**.

**Comment by basrieter** [comment]
There are actually multiple data entries that could indicate this value:

![image](https://user-images.githubusercontent.com/1310443/67131131-cbd3f480-f203-11e9-9810-2445ea1e920b.png)

![image](https://user-images.githubusercontent.com/1310443/67131149-da221080-f203-11e9-82a8-903badf9882e.png)

![image](https://user-images.githubusercontent.com/1310443/67131142-d55d5c80-f203-11e9-8dfa-9dafebdcb852.png)

The later actually are more days then the previous two dates. So which one to use? I would prefer one of the first two.

**Comment by basrieter** [comment]
@Snaah @sopor Any suggestions?

**Comment by Snaah** [comment]
The labels I provided are from a Retrospect trace log. Is yours from the API? The latter seems to be for premium users, i.e. premium users have more days to watch the show. Correct? (It is this way on for instance TV4 Play.)

For all channels, the data I'm interested in is: duration, time aired and "watchable until". Seems all is there!
