### ISSUE TITLE
Retrospect documentation is really confusing

### ISSUE THREAD

**Issue by peno64** [retrospect-addon/plugin.video.retrospect#1208]
In the start page (https://github.com/retrospect-addon/plugin.video.retrospect) it is stated:

Installing and updating Retrospect under Kodi Leia and up
If you are using Kodi Leia then the installation is straight forward: you can install Retrospect and the dependencies from the Kodi repository. You will find Retrospect in the repository under the Video Add-ons. Updating Retrospect will then automatically be done using the Kodi repository.

Installing Retrospect
There are a couple of ways to install and/or update Retrospect using this GIT repository:

1 - Installing and updating Retrospect the 'Easy way'
.
.
.

! Be advised !
Retrospect will NOT auto-update. So new version need to be installed manually.

This is really confusing...

The first way of installing should be from the kodi repo and it should say that it will then update automatically.

And the other ways should be 2., 3. and only there it should say that it will not update automatically.

If you look at the old bitbucket download page, you see that still alot of users install retrospect manually from there (419 5.0.2 downloads) and not via the kodi repo. I think this is because they don't understand enough that retrospect is now again in a repo and doesn't have to be installed manually anymore.

**Comment by dagwieers** [comment]
I agree, I would keep it simple in the entry page, and forward to the Wiki for specific advanced scenarios. In most cases users don't need anything other than installing the addon from Kodi.

If your main document has 95% covered for edge scenarios, the documentation is broken :-)

Cfr. https://github.com/pietje666/plugin.video.vrt.nu/blob/master/README.md

**Comment by basrieter** [comment]
Ok, I can see your problem. Let me rewrite it to have 2 options: either from the repo for Leia and up, or from zip with Krypton. I will remove the GIT stuff. Thanks for your feedback.

**Comment by peno64** [comment]
Very good. 

Retrospect without Leia has also less and less of a point I think because it needs widevine for alot of channels to decode which is only available on Leia...

**Comment by dagwieers** [comment]
> Retrospect without Leia has also less and less of a point I think because it needs widevine for alot of channels to decode which is only available on Leia...

I don't agree there. But I think we should be looking for adding Retrospect also to Krypton (and see if we can bend the policy on that for add-ons that have a long legacy).

**Comment by basrieter** [comment]
Please review the PR an preview the documentation here: https://github.com/retrospect-addon/plugin.video.retrospect/tree/feature-documentation

**Comment by dagwieers** [comment]
You can just write #1209 in the text.

**Comment by Snaah** [comment]
I've actually been thinking about this for a long time. Good point, @peno64 !

@basrieter I can look through the new text the coming days and comment on the PR.

@peno64 On a sidenote I can not grasp why Retrospect would have a lesser value because it needs Widevine. Welcome to development, welcome to the future, friends! ;) Why the heck someone stays on older versions of Kodi for no real reason beats me.

**Comment by basrieter** [comment]
Great! Please put your comments in the PR, so I can update that one.

**Comment by peno64** [comment]
@Snaah I think you misunderstand me. I am already on kodi 18 since its beta versions. I don't say that retrospecr has a lesser value because it needs widevine. I say because it needs widevine for much of its channels to be able to work and because winevine only works on the latest kodi version there is no much point in supporting retrospect on lower kodi versions. And i also understand why it needs widevine to be able to do its thing that it does.

**Comment by Snaah** [comment]
@peno64 You're absolutely right - I misunderstood you completely (Dag's comment). Sorry, I was tired.

@basrieter I will. I haven't gotten acquainted with Github yet. Is it possible to edit a PR locally, then push it from Sourcetree as an edit of the PR?

**Comment by basrieter** [comment]
@Snaah you can comment on different lines in the PR by poging to #1209 and then `Files changed` and you can click between the line numbers and the +/- to add comments. Of just comment at the first line to have a generic comment on the file.

**Comment by basrieter** [comment]
Anyone looked at this? Is it clearer now @peno64

**Comment by Snaah** [comment]
I've begun but will need some more time.

**Comment by basrieter** [comment]
@Snaah  keep in mind that it needs to stay short and simple.

**Comment by Snaah** [comment]
@basrieter I find Github a bit of a hassle to use for this kind of editing, but I'm going to start commenting right now in #1209.
