### ISSUE TITLE
VRT.NU VOD titles are playing in double speed.

### ISSUE THREAD

**Issue by GunterO** [retrospect-addon/plugin.video.retrospect#1210]
### Describe the bug
When playing an episode / program of VRT.NU (e.g. "National"/"VRT.NU"/"Titles with"H" / "Het Journaal" / <Any episode>) the playback speeds seems to be double.
When downgrading to an order version (v4.x), there is no problem.
However,live TV is ok.

## Expected Behavior
Normal playback speed.

## Actual Behavior
Double playback speed.

### To Reproduce
Play any episode of 
"National" / "VRT.NU" / "Titles with"H" / "Het Journaal" / <Any episode>

### Your Environment
CoreELEC 9.0.3

Used versions:
- Kodi version: v18.3
- Retrospect version: 5.0.3

**Comment by basrieter** [comment]
Were is your retrospect log?

**Comment by GunterO** [comment]
[11_Addons.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/3545158/11_Addons.log)

**Comment by GunterO** [comment]
I added retrospect.log, but the contents seems to be similar to the addons.log I uploaded before.
I hope this helps.

**Comment by basrieter** [comment]
It's not a **debug** log. On the wiki you can find information on how to generate a debug log: https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Logging

**Comment by GunterO** [comment]
Oops, sorry. I hope this one is ok.
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/3545298/retrospect.log)

**Comment by basrieter** [comment]
Can you try to disable using InputStream Adaptive from the Retrospect add-on settings? 

![image](https://user-images.githubusercontent.com/1310443/63758982-fddc7080-c8bc-11e9-80e8-13d03c296262.png)

Then try playing it again. If that works, I know where to look.

**Comment by GunterO** [comment]
Yep, disabling that option fixed it!

**Comment by basrieter** [comment]
Ok, what I will do is 2 things: 

1. allow you to configure the InputStream Adaptive for VRT.nu independent from the Retrospect add-on settings
1. see why this happens in the InputStream Adaptive add-on. Could you also provde a debug Kodi.log (so enable debug logging in Kodi, play it again the the InputStream Adaptive add-on enabled in Retrospect) and attach the log here. Hopefully @peak3d can figure out why it plays too fast.

**Comment by basrieter** [comment]
Could you try this patch: 
[retrospect-patch-20190827.122826.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3545618/retrospect-patch-20190827.122826.zip)

It should allow you to enable the InputStream Adaptive in Retrospect globally but disable it for VRT.nu for the `Channel Options` in the context menu when VRT.nu is highlighted:

![image](https://user-images.githubusercontent.com/1310443/63764253-b5c24b80-c8c6-11e9-8472-7d820cdb8155.png) ![image](https://user-images.githubusercontent.com/1310443/63764273-bf4bb380-c8c6-11e9-8bee-fcfb3edcdb3e.png)

![image](https://user-images.githubusercontent.com/1310443/63764239-a9d68980-c8c6-11e9-8972-e909b35593da.png)

**Comment by GunterO** [comment]
1. The patch is working. I (re)enabled the InputStream Adaptive in the global settings and disabled it in VRT NU channel options.
2. Enabled it again to generate the 01_KODI.log debug for you.
[01_KODI.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3545846/01_KODI.zip)

**Comment by peno64** [comment]
I just tried this with v 5.0.3 from the kodi repo on libreelec 9.1.002 with kodi 18.3 in RPI3 and the inputstream adaptive setting enabled (and widevine installed) and playing 'het journaal' is working without a problem. Normal playback...

**Comment by basrieter** [comment]
Ok, so it is likely already fixed but just not yet available in that LibreElec build. Saves me from harnessing peak3d

**Comment by peno64** [comment]
I guess you mean coreelec instead of libreelec. Is there a versionnumber that can be checked/compared from something?

**Comment by basrieter** [comment]
Indeed, CoreElec
