### ISSUE TITLE
npo live stream not playing

### ISSUE THREAD

**Issue by deboshond** [retrospect-addon/plugin.video.retrospect#1211]
### Describe the bug
Here is a clear and concise description of what the problem is:
When I select Live TV NPO 1, it does not play. 
A blue "kodi" circle appears for a few seconds, then it flashes back to Retrospect, again the kodi circle and then I am back in retro spect.

Retrospect was working until two weeks ago, it suddenly stopped working for NPO.
It is possible to play other channels, for instance veronica, sbs etc.
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/3552174/retrospect.log)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Channel should play and it was playing before.

## Possible Fix
na

### To Reproduce
1. select live tv 
2. npo 1
3. play....

### Debuglog
addon/plugin.video.retrospect/wiki/Logging -->
The **debug** retrospect.log can be found here:
https://paste.kodi.tv/onehoxomib

### Screenshots 
Here are some links or screenshots to help explain the problem:
na

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
na

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi : libreelec
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: leia 18.1 (libreelec 9.01)
- Retrospect version: 5.0.3

**Comment by basrieter** [comment]
This is most likely a LibreElec issue and combination with WideVine libraries. Do you have the option to upgrade to a more recent LibreElec version (or CoreElec)?

**Comment by peno64** [comment]
I am also on raspberry pi but with the latest libreelec (9.1.002), latest kodi (18.3) and npo1 live plays without a problem. It is only a week or 2 I changed from kodi 18.2 to 18.3 and only then an update of inputstream adaptive was available and I also reinstalled widevine at that moment to have the latest version.

**Comment by deboshond** [comment]
Thx, I will upgrade and let you know.



Verzonden vanaf mijn Samsung Galaxy-smartphone.


-------- Oorspronkelijk bericht --------
Van: Bas Rieter <notifications@github.com>
Datum: 28-08-19 20:08 (GMT+01:00)
Aan: "retrospect-addon/plugin.video.retrospect" <plugin.video.retrospect@noreply.github.com>
Cc: deboshond <bas@greydanus.net>, Author <author@noreply.github.com>
Onderwerp: Re: [retrospect-addon/plugin.video.retrospect] npo live stream not playing (#1211)


This is most likely a LibreElec issue and combination with WideVine libraries. Do you have the option to upgrade to a more recent LibreElec version (or CoreElec)?

**Comment by buddygurt** [comment]
I have exactly the same problem as mentioned above. NPOstart doesn't play anymore (in a similar fashion as deboshond reported). For me it all started when Widevine prompted for an update and I pressed OK (oh how I regret that now...). Tried several things but nothing solved it. Updated to LibreElec 9.1.002 with Kodi 18.3, reinstalled Retrospect 5.0.4 from the repo a couple of times. Updated InputstreamAdaptive to version 2.3.22.2. Still no playback.

Any ideas how to fix this?

**Comment by buddygurt** [comment]
Wha! Found this post, which (eventually) solved the problem:
https://github.com/Opvolger/plugin.video.uzg/issues/28
Had to explicitly remove Retrospect, UZG and InputstreamHelper, and then reinstall. Then had to reinstall Widevine CDM (by clicking an arbitrary video) and reboot about three times, but in the end everything worked again. Took some time and effort, but I'm a happy user again.

**Comment by basrieter** [comment]
Good to hear that! The 0.4.1 of the InputStream Helper will solve these issues.

**Comment by peno64** [comment]
You can already download/install 0.4.1 of InputSream Helper from https://github.com/emilsvennesson/script.module.inputstreamhelper/releases

**Comment by basrieter** [comment]
No need! It is already merged: https://github.com/xbmc/repo-scripts/pull/1141

**Comment by deboshond** [comment]
> You can already download/install 0.4.1 of InputSream Helper from https://github.com/emilsvennesson/script.module.inputstreamhelper/releases

Yes, this did the trick. I updated to 0.4.1 for the inputstream helper, after that I got a popup for widevine. Updated widevine and everything working fine again.

**Comment by basrieter** [comment]
Great to hear that!

**Comment by Arathonk** [comment]
Just a note, I have the same problems,
I'm on Inputstream helper 0.4.1, and everytime I get the pop up saying I have to update Widevine CDM, but when I do that after downloading it just doesn't go any further when extracting.

**Comment by basrieter** [comment]
> Just a note, I have the same problems,
> I'm on Inputstream helper 0.4.1, and everytime I get the pop up saying I have to update Widevine CDM, but when I do that after downloading it just doesn't go any further when extracting.

Please report this in their repo: https://github.com/emilsvennesson/script.module.inputstreamhelper/
