### ISSUE TITLE
VRT NU toont niet alle episodes/seizoenen van Thuis

### ISSUE THREAD

**Issue by peno64** [retrospect-addon/plugin.video.retrospect#1218]
Ga naar VRT NU, 'T', Thuis. Enkel de episodes gestart van 2/9 worden getoond terwijl er veel meer zijn (extra seizoenen). Dit wordt ook aangetoond door de VRT NU addon van dag wieers. Zie de printscreens
![screenshot028](https://user-images.githubusercontent.com/32430988/64200900-b7bf7800-ce8d-11e9-83a6-9772724764ea.png)
![screenshot029](https://user-images.githubusercontent.com/32430988/64200916-bc842c00-ce8d-11e9-9881-b6bdb0eb0ba6.png)

**Comment by basrieter** [comment]
@peno64 zou je aan de bug format willen houden? En op zijn minste een debug retrospect.log kunnen toevoegen?

**Comment by basrieter** [comment]
Zou je de bestaande bestanden van Retrospect kunnen overschrijven met de bestanden in deze zip? Dan Kodi herstarten en kijken of het dan werkt?

[retrospect-patch-20190903.213706.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3571147/retrospect-patch-20190903.213706.zip)

**Comment by peno64** [comment]
Ziet er goed uit!
