### ISSUE TITLE
RTBF Auvio (with user login)

### ISSUE THREAD

**Issue by stebadev** [retrospect-addon/plugin.video.retrospect#1219]
## Channel Request
RTBF Auvio (with user login)
https://www.rtbf.be/auvio/

**Comment by basrieter** [comment]
Please don't ignore the template that was provide to request a new channel. It contains essential information:

https://github.com/retrospect-addon/plugin.video.retrospect/blob/master/.github/ISSUE_TEMPLATE/channel_request.md

So please update your request.
