### ISSUE TITLE
SVT Öppet arkiv: Add duration, mark as geoblocked and fix end date

### ISSUE THREAD

**Issue by Snaah** [retrospect-addon/plugin.video.retrospect#1220]
### Is your feature request related to a problem? Please describe

1. Duration can be added to SVT Öppet arkiv. It is under the same label as for SVT Play, in seconds. (Watchable until is not the same, though. There are programs on Öppet arkiv that has a last day to watch too, but the info does not coincide with SVT Play. I haven't found where it is.)

2. All programs of Öppet arkiv are geoblocked and should be marked as such. You must have a Swedish IP to watch them.

3. SVT Play also lists some of Öppet arkivs programs. Since SVT Play's programs have a correct "watchable until", wrong dates are shown in Retrospect for Öppet arkivs programs listed under SVT Play. All are given the end date 2199-01-01 00:00. An easy solution is just to show nothing for those.

Examples to see the 2199-01...:
https://www.oppetarkiv.se/video/1182223/abba-dabba-dooo
https://www.svtplay.se/abba-dabba-dooo

https://www.oppetarkiv.se/video/4998658/cornelis-dokumentaren
https://www.svtplay.se/cornelis-dokumentaren

### Describe the solution you'd like

Duration and all programs marked as geoblocked for Öppet arkiv. "Watchable until" for Öppet arkiv programs on SVT Play nullified.

**Comment by basrieter** [comment]
Ok, 

1. is not possible as only the details of a video show the duration. See https://www.oppetarkiv.se/etikett/titel/Absolut_samtal/ for example. 

2. is simple and can be done. 
3. actually shows these dates in the data from their API: 

![image](https://user-images.githubusercontent.com/1310443/64540069-e02cf380-d31f-11e9-8719-ad454b949e3c.png)

I could just ignore them?

**Comment by Snaah** [comment]
Okay on 1 and 2. For 3, yes, just ignore the date if it's 2199-01-01. (It will show 2199-01-01 even if the episode has a set end date: https://www.oppetarkiv.se/video/1256676/aspiranterna-avsnitt-3-av-8).
