### ISSUE TITLE
Can we have country labels for PRs/issues

### ISSUE THREAD

**Issue by dagwieers** [retrospect-addon/plugin.video.retrospect#1221]
### Describe the solution you'd like
Is it possible to add labels for the different countries?

I bet most users are interested to:
- General Retrospect issues/features
- Issues and feature requests for channels they (can) watch

So ideally I would like to see labels like: `global`, `belgium`, `netherlands`, `sweden`, `finland`, `uk`, etc. Preferably all in the same colour (which is a common practice to have mutual exclusive labels have the same colour).

**Comment by basrieter** [comment]
I added the major ones and will more when needed. A "global" issue is a global issue and will not get a country related tag.
