### ISSUE TITLE
VTM.be does not parse (certain) folders (for ex. episodes of Gina & Chantal)

### ISSUE THREAD

**Issue by bertdebondt** [retrospect-addon/plugin.video.retrospect#1222]
### Describe the bug
Here is a clear and concise description of what the problem is:

Episodes are not listed anymore under certain folders. For ex. "Gina & Chantal"

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It should show the available episodes

## Actual Behavior

Error message : "Error retrieving the list of items"

### To Reproduce

Just try to open map Gina & Chantal on VTM.be channel

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/xaqijijoxo

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Same program (Gina & chantal) is available through Stevie Channel, but there only last episode 3 (last) can be seen not episode 1 or 2.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.0 ALPHA 1
- Retrospect version: Latest 5.04

**Comment by basrieter** [comment]
Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi:  

[retrospect-patch-20190911.221507.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3602548/retrospect-patch-20190911.221507.zip)

**Comment by peno64** [comment]
I can confirm that this patch works. Before the patch I had this same error and after installing the patch and restarting the pi it works fine.

**Comment by basrieter** [comment]
Great! Will push the changes  and include it in the next version.

**Comment by peno64** [comment]
There is a VTM GO addon under development. It is almost finished. They are waiting on the release of a change in another addon to release it.
https://github.com/michaelarnauts/plugin.video.vtm.go
