### ISSUE TITLE
Retrospect crash on startup - Kodi on Xbox One

### ISSUE THREAD

**Issue by TimoVerbrugghe** [retrospect-addon/plugin.video.retrospect#1225]
### Describe the bug
Here is a clear and concise description of what the problem is:

Right after installing Retrospect from the Kodi Add-On repository and launching it for the first time, it immediately crashes and I get a kodi notification that I should check the log for details.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expected behaviour is that Retrospect launches normally.

## Actual Behavior

Retrospect crashes immediately on launch.

## Possible Fix

After looking in the log file which I put in debug mode, available here: http://paste.kodi.tv/gowajitoxe (lines 760 - 850 are retrospect being launched), It seems that the crash happens when retrospect tries to write out its own log file. Don't know exactly how addons are restricted in the xbox one version, but could it be that you're restricted in writing files?

### To Reproduce

1. Install the latest version of Kodi on Xbox One through the Store
2. Download the Retrospect addon from the Kodi Repository.
3. Try to launch Retrospect

### Debuglog

The **debug** retrospect.log can be found here:
--> NOT AVAILABLE since it's not created on startup.

Debug kodi.log available here: http://paste.kodi.tv/gowajitoxe

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [x] Windows UWP -> **XBOX One**

Used versions:
- Kodi version: 18.3
- Retrospect version: 5.0.5

**Comment by basrieter** [comment]
Your complete logfile is filled with access denied errors. Are you sure it is just Retrospect that is causing errors?

**Comment by TimoVerbrugghe** [comment]
Hi Bas!

My log file has indeed quite a lot of NFS3ERR_ACCES, however it seems that these lines are pretty harmless and is an issue that will be resolved in v19 of Kodi: https://github.com/xbmc/xbmc/issues/15194

Also, the access errors only have to do with the NFS share, while I think this issue is more related to writing log files to internal storage, so I think it's unrelated...

**Comment by basrieter** [comment]
Can you explain your setup a bit? Most importantly where your profile files are locayed?

**Comment by basrieter** [comment]
And could you provide me with a full debug kodi.log? One that also shows the paths at the top?

**Comment by TimoVerbrugghe** [comment]
Sorry for being bit later with this. Full debug kodi.log is available here: http://paste.kodi.tv/raw/uzeyanomay

So my setup is an XBOX One X, running Kodi 18.3 Git:20190619-89472b7d69, compiled 2019-06-27 (lastest version available in the windows store on Xbox).

**Comment by basrieter** [comment]
I tried running it on Windows using the UWP version of Kodi. That works just fine. So it is weird. 

Are you able replace single files on your Xbox? So that I can send you some debug files?

**Comment by TimoVerbrugghe** [comment]
Let's see which files you want me to replace and where, because I have noticed that I can't move/copy any file that I want, like f.e. the kodi.log in userdata folder file, using the built-in file manager in kodi.

But I can definitely try ;), you can send them over.

**Comment by envackervirvel** [comment]
Hello. Any news on this issue? I tried to run Retrospect on Xbox One but with the same result as Timo. But since Xbox is such a closed platform it seems hard to do anything outside what Microsoft wants. :-(

**Comment by o0donder0o** [comment]
+1 Don't see any reason to get another media center since i already have an XB0. Restrospect seems the perfect solution to stream dutch replay TV shows since apps on XB0 for these services are not available and Chromecasting lacks quality and sometimes delays sound.

I'm happy to help out if tests need to be done or logs need to be provided.

**Comment by basrieter** [comment]
Can you guys try this one.

- Enable debug logging in Kodi
- Then install it from ZIP via Kodi. 
- Restart Kodi and open Retrospect again. I think it will still fail, but it will give me more insight. 
- Then provide me with the Kodi logfile in pastebin.

[plugin.video.retrospect-5.0.8.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3774761/plugin.video.retrospect-5.0.8.zip)

**Comment by o0donder0o** [comment]
Will do, gonna try it out later this weekend.

**Comment by basrieter** [comment]
> Will do, gonna try it out later this weekend.

No hurries. I am kinda busy at the moment so I don't have too time either.

**Comment by envackervirvel** [comment]
Hi. 
Trying to do stuff with Xbox is terrible :-) It such a closed platform.. but I think I managed to get a kodi.log file at last by taking a photo on my screen and then using an online tool to convert the pic to text.. maybe there is another way but I can’t find it.

I put the log on Pastebin and I hope it tells at least something. 
https://pastebin.com/Qs1Qzhxy
Thanks!

**Comment by basrieter** [comment]
I need more of that log. I added some logging that should be higher up. There is an add-on in the repository that allows you to upload the kodi.log to pastebin. You can use that one.

**Comment by envackervirvel** [comment]
Ok! I installed the log file uploader add-on and got this URL:
https://paste.kodi.tv/hojuneyoce
Hope it helps.

**Comment by o0donder0o** [comment]
Let me know if you need my log as well.

**Comment by basrieter** [comment]
No, I am still clueless. I need to check what is going on. Seems like the files are read-only some how.

**Comment by basrieter** [comment]
Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi.

[retrospect-patch-20191029.002147.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3781021/retrospect-patch-20191029.002147.zip)

See if it will start then. I suspect it to fail again, but at least generate a retrospect.log.

**Comment by envackervirvel** [comment]
Hi!
I updated Retrospect but it didn't start. Log file can be found at: https://paste.kodi.tv/pukuwahufe

**Comment by basrieter** [comment]
Well, you did not update it correctly. You should not have "Installed from zip" but manually override the files. Please reinstall Retrospect from the Kodi repo and manually replace the logger.py from the zipfile.

**Comment by envackervirvel** [comment]
Ok.. Not sure how to proceed because the Kodi file manager in Xbox will not let me do any file replacements at all I'm afraid + it doesn't show the whole file system. And I can't ftp, scp or anything else either. :-(
Frustrating.

**Comment by basrieter** [comment]
Can you do an install from zip? Because then download the main 5.0.8 release from GitHub (https://github.com/retrospect-addon/plugin.video.retrospect/releases) and then replace the logger.py in that zip and install that zip via the normal Kodi procedure.

**Comment by envackervirvel** [comment]
Yes, installation from zip is basically the only procedure that works on Xbox Kodi as far as I can see. I will try that tomorrow morning and get back with a kodi log.

**Comment by basrieter** [comment]
Great. It will still crash! But if it does generate a retrospect.log we are a bit further. So if there is a retrospect.log generated, please upload that via the Retrospect settings (enable the Retrospect debug logging and then you get an option to upload it).

**Comment by envackervirvel** [comment]
Good morning.
I re-installed Retrospect using a zip with the two new files and get this Kodi log: https://paste.kodi.tv/gunadagoye

I do get a retrospect.log but I'm not able to send it via Retrospect and I'm not allowed to just copy/paste it from the profile directory...

**Comment by bcnx** [comment]
> Good morning.
> I re-installed Retrospect using a zip with the two new files and get this Kodi log: https://paste.kodi.tv/gunadagoye
> 
> I do get a retrospect.log but I'm not able to send it via Retrospect and I'm not allowed to just copy/paste it from the profile directory...

Hi,

how did you upload the zip? Did you use a USB memory stick?
 
Cheers,

BC

**Comment by basrieter** [comment]
You can give https://github.com/retrospect-addon/plugin.video.retrospect/archive/feature-xbmcvfs.zip a try in Kodi Leia for Xbox One. You need to "install it from zip". You can put the zip on a network file system and link that to your Kodi sources (from the Kodi File Manager).

**Comment by basrieter** [comment]
Also to @TimoVerbrugghe could you give this one a try? I don't think it will work 100% yet, but I want to double check that the solution works.

**Comment by bcnx** [comment]
Hi,

so I put the zip file on my NFS share, added a folder for that in Filemanager, installed the ZIP file in Addons and did an update immediately there after, but:
- I still cannot enter passwords in Channel Settings
- stil do not have VTM Go in the channel list

I will try to send debug files now,

BC

**Comment by bcnx** [comment]
Retrospect logfile sending does not work, Kodi does:

https://paste.kodi.tv/vijisijuqi

thanks,

BC

**Comment by bcnx** [comment]
I tried another VTM Go Addon and it complains about Kodi from the Windows store not supporting Wedevine. Does that mean that Kodi on the Xbox is a lost cause for Addons like Retrospect?

cheers.

BC

**Comment by basrieter** [comment]
> Hi,
> 
> so I put the zip file on my NFS share, added a folder for that in Filemanager, installed the ZIP file in Addons and did an update immediately there after, but:
> 
> * I still cannot enter passwords in Channel Settings
> * stil do not have VTM Go in the channel list
> 
> I will try to send debug files now,
> 
> BC

You did not put the correct .zip file on the share,  I can see that from the Kodi log. Please use this logfile: https://github.com/retrospect-addon/plugin.video.retrospect/archive/feature-xbmcvfs.zip and give it another try.

Regarding VTM: that change is not yet in this zip file. It first needs to run on Xbox One. However, if Widevine is not supported on Xbox, then you can forget about online streams, als 95% of te streams are in Widevine nowadays.

**Comment by bcnx** [comment]
huh? I used the link : https://github.com/retrospect-addon/plugin.video.retrospect/archive/feature-xbmcvfs.zip , it's the same as yours.

another issue: will the absence Widevine on Xbox not render all ours efforts useless? if we can't use Widevine, we probably cannot use a lot of streaming Addons on Xbox.

**Comment by bcnx** [comment]
Wait, I did an update, might this have overwritten the zip version?

**Comment by basrieter** [comment]
If you updated Kodi to "Kodi Matrix" they yes! The zips only work for Kodi Leia, not Matrix.

**Comment by bcnx** [comment]
No, I updated in the Addon page

**Comment by basrieter** [comment]
Then it will have overwritten it.

**Comment by bcnx** [comment]
OK, will try again. But what about Widevine? Do we need this? If so, whatever we are doing now is pointless.

**Comment by bcnx** [comment]
same problem, https://paste.kodi.tv/onoxucenas

**Comment by basrieter** [comment]
Indeed, same error, eventhough I used the Kodi API. So I can't help that at the moment. Need to ask around in the Kodi team.

But without Widevine you can't play a lot. So I would suggest you trying your rPi3 or buy a rPi4.

**Comment by bcnx** [comment]
Hey Bas, yes today I made the decision to leave the Xbox platform: there is no file access, there is no possibility for remote access (SSH or VNC) and no means to schedule things. I'm an open source fan and Xbox is not that. I use it fir what it is intended: gaming. 
I plan to buy an Odroid N2+ which is a lot more powerful than the RPi 4 but delivery times are a bit crazy.
