### ISSUE TITLE
UR Play broken

### ISSUE THREAD

**Issue by Snaah** [retrospect-addon/plugin.video.retrospect#1226]
### Describe the bug
Here is a clear and concise description of what the problem is:

1. UR Play is not working. No programs can be listed, no categories shown etc.

2. The search function seems to be semi-working. I will describe an error I've known for some time that I haven't reported. It is still there.

Searching for "90" gives the result it should give, among them the documentary "90+ och världsmästare". But clicking it shows the listing for ["you may also like" from URPlay's website](https://urplay.se/program/208354-90-plus-och-varldsmastare) (bottom of the page). "90+ och världsmästare" is not shown. The programs shown are not playable.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

UR Play working.
## Actual Behavior

UR Play not working.
### To Reproduce

1. Start UR Play.
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/3654624/retrospect.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.4
- Retrospect version: 5.05

**Comment by basrieter** [comment]
They moved to an API. Let me have a look at that.

**Comment by basrieter** [comment]
The main listing should work now. Will look into the rest tomorrow.

Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi.

[retrospect-patch-20190925.235754.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3654959/retrospect-patch-20190925.235754.zip)

**Comment by Snaah** [comment]
Working! Thanks, Bas.

**Comment by basrieter** [comment]
Working categories:

[retrospect-patch-20190926.231715.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3659950/retrospect-patch-20190926.231715.zip)

**Comment by Snaah** [comment]
Working here! (The listings. "90 plus och världsmästare" still gives wrong hits. Most shared, Latest, Last Chance are not working.)

**Comment by basrieter** [comment]
All should be working again. Only thing I need to fix is the folders (like seasons) within a show. 

[retrospect-patch-20190930.211112.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3672848/retrospect-patch-20190930.211112.zip)

**Comment by Snaah** [comment]
All working now. Thanks!

**Comment by basrieter** [comment]
And the Season Folders should be working now. 

[retrospect-patch-20191002.002508.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3678707/retrospect-patch-20191002.002508.zip)

**Comment by Snaah** [comment]
Working great !

**Comment by basrieter** [comment]
I am pushing 5.0.6 to the Kodi repo. So it will be officially release soon.

**Comment by bubbleboyy** [comment]
Categories not working "Retrospect error. Error retrieving the list of items"
