### ISSUE TITLE
Latest Retrospect update not available trough Kodi repo. 

### ISSUE THREAD

**Issue by Arathonk** [retrospect-addon/plugin.video.retrospect#1227]
I'm running Retrospect 5.0.5 on Kodi 18.3(rasppi,osmc),
When starting Retrospect I get a notification saying there's an update avaiable(5.0.6) but that update isn't in the Kodi repo. 

I'm not updating by downloading the file on Github, because you wrote not to do that when on Leia. 

Could you look into it?

**Comment by basrieter** [comment]
All repro changes need to propagate to all Kodibmirrors. That takes some time. The notification is triggered by the release on Github. 

You try to force Kodi to search for updates?

**Comment by basrieter** [comment]
See also #1224

**Comment by Arathonk** [comment]
I have forced searched but nothing.
Do you propose to wait or update with the zip?

**Comment by basrieter** [comment]
Wait. I just checked my LibreElec install and after I restarted it and did a search for updates it did find it. 

If you install from zip you will nolonger get any automatic updates.

**Comment by Arathonk** [comment]
So I'll wait for it! I just checked and nothing yet.
Thanks for the info.

**Comment by basrieter** [comment]
If you go to:

* Install from repository
* Video Add-ons

Do you see Retrospect there? What versions are available?

**Comment by Arathonk** [comment]
Yes it's there, only 5.0.5

**Comment by basrieter** [comment]
Then I have no clue. Updating is completely done by Kodi, so Retrospect has no hand in that. Perhaps OSMC uses it's own listing of add-ons that takes a bit longer to update. I don't know.
