### ISSUE TITLE
Sweden: Viafree's MTV and National Geographic channels can be added

### ISSUE THREAD

**Issue by Snaah** [retrospect-addon/plugin.video.retrospect#1229]
### What Channel would you like to add and why?

Viafree's MTV and National Geographic
### Provide some details for the channel
- Name of the channels in English: MTV and National Geographic
- Name of the channels in native language: MTV and National Geographic
- Websites for the channels: https://www.viafree.se/kanal/mtv and https://www.viafree.se/kanal/national-geographic
- If available link to the Android app for the VOD content of channel:
- Link to the logo of the channel
 
### Check which features should be implementend
- [ ] Video on-demand content
- [ ] TV live streams
- [ ] Use your account for the VOD services from Retrospect
- [ ] Access the premium content if you are eligible

**Comment by Snaah** [comment]
Forgot: Actually there's also the channel Comedy Central, but it only has 2 shows. Overkill to add it as a separate channel.

**Comment by basrieter** [comment]
Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi.

[retrospect-patch-20191007.220452.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3699244/retrospect-patch-20191007.220452.zip)

**Comment by Snaah** [comment]
Working! Nice, Bas. Good placement of the channels in the sorting too. For the descriptions:
"Sändningar från MTV (Viafree.se)."
"Sändningar från National Geographic (Viafree.se)."

**Comment by basrieter** [comment]
Ok, let me change that (copy pasted it from the Norwegian descriptions :) ).
