### ISSUE TITLE
Sweden: Add exclusive content and categories to Viafree and Dplay

### ISSUE THREAD

**Issue by Snaah** [retrospect-addon/plugin.video.retrospect#1230]
### Is your feature request related to a problem? Please describe

Viafree and Dplay have exclusive content and categories, which are not in Retrospect.
### Describe the solution you'd like

As both channels have exclusive content, it would be great to have a special folder to list those shows in each channel. ".: Viafree/Dplay exklusivt :." - ".: Viafree/Dplay exclusive :." The URLs are:
Dplay: https://www.dplay.se/kanaler/dplay
Viafree: https://www.viafree.se/viafree-exklusivt

It would also be great to have categories:
Dplay: https://www.dplay.se/kategorier
Viafree: Can't find a direct URL. They are shown here, at top under "Kategorier":
https://www.viafree.se/program/

**Comment by basrieter** [comment]
Please create individual enhancement requests for this: One Viafree and one Dplay. These are two completely different channels.

**Comment by Snaah** [comment]
Sure, but does it matter? Just a formality.
