### ISSUE TITLE
Sweden: Add exclusive content and categories to Dplay

### ISSUE THREAD

**Issue by Snaah** [retrospect-addon/plugin.video.retrospect#1232]
### Is your feature request related to a problem? Please describe

Dplay has exclusive content and categories, which are not in Retrospect.

### Describe the solution you'd like

As Dplay has exclusive content, it would be great to have a special folder to list those shows in the channel. ".: Dplay exklusivt :." - ".: Dplay exclusive :." The URL is:
https://www.dplay.se/kanaler/dplay

It would also be great to have categories: 
Dplay: https://www.dplay.se/kategorier

**Comment by basrieter** [comment]
Isn't this data already available via the normal Dplay.se channel?

**Comment by Snaah** [comment]
The exclusive content: Yes, that's why it just needs to be sorted into a folder.
The categories are not.
(This goes for Viafree too.)
