### ISSUE TITLE
No program listings anymore for NPOstart 

### ISSUE THREAD

**Issue by ErikBrown2** [retrospect-addon/plugin.video.retrospect#1233]
### Describe the bug
Here is a clear and concise description of what the problem is:

NPOstart does not show any programs anymore

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

See a list of programs

## Actual Behavior

For instance when I go to NPO start - recent - yesterday and press enter, I get the following error message: Retrospect error. Error retrieving the list of items.

## Possible Fix

You know best

### To Reproduce

1. Start NPOstart and try to get any program listing. For instance, recent - yesterday
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/uboyuvozow

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:
- Retrospect version:
LibreElec 9.1.501

**Comment by basrieter** [comment]
Apart. Ik ga er naar kijken.

**Comment by basrieter** [comment]
Gefixed, met samen met @Opvolger

[retrospect-patch-20191009.205819.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3708998/retrospect-patch-20191009.205819.zip)

**Comment by ErikBrown2** [comment]
Wow Bas, dat was snel. Het werkt inderdaad. Heel erg bedankt!

**Comment by Phyxion** [comment]
Viel mij ook al op, een aantal series werkten nog wel. Fijn dat er al een fix is @basrieter! Versie bump @ Kodi repo? 😊

**Comment by basrieter** [comment]
Onderweg: https://github.com/xbmc/repo-plugins/pull/2557

**Comment by Diggler74** [comment]
dank
