### ISSUE TITLE
Rtlxl speelt te snel via coreelec 9.2

### ISSUE THREAD

**Issue by kengithub9** [retrospect-addon/plugin.video.retrospect#1234]
Rtlxl speelt alles te snel af. vanalles geprobeerd, inputstream uit of aan maakt niets uit.
Ik draai op mijn eminent 7680 Coreelec 9.2 met de laatste retrospect.5.06 en inputstream 2.4.2.1.
Er was eerder een bugreport hiervan maar echt een oplossing kon ik niet vinden.
Het gekke is dat ik de gewone kodi 19 beta op windows10 wel normaal kan kijken naar rtlxl.
Kan iemand tips of oplossingen geven voor mijn probleem.

**Comment by Ctheman** [comment]
Bij Retrospect "Configureren", deselect "Gebruik de Inputstream Adaptive add-on wanneer mogelijk"

**Comment by kengithub9** [comment]
Als ik deselect gebruik dan krijg ik alleen het laatste stuk van het programma. Dus vanaf het laatste reclameblok.

**Comment by Ctheman** [comment]
Installeer de nieuwste Widevine via Retrospect dan zou ie moeten werken.

**Comment by kengithub9** [comment]
Is middels gelukt om het werkend te krijgen met een nieuwere versie van Widevine.

**Comment by Ctheman** [comment]
👍

**Comment by kengithub9** [comment]
Helaas te vroeg gejuicht. Ook na update Widewine spelen veel afleveringen te snel af. Ik heb in de retrospect de optie uitgezet en in rtlxl op aan dan gaat het soms goed en heel vaak fout. Als ik in rtlxl het uit zet dan krijg ik alleen het laatste stuk te zien en op optie retrospect in het hetzelfde als optie aan ook als ik de optie in settings van retrospect zelf aan heb staan is het niet goed. 
mijn inputstream is 2.4.21 en inputhelper 0.42, widewine 1503. Ik heb Coreelec 9.2.

Hopelijk weet iemand toch nog een werkende oplossing.

**Comment by basrieter** [comment]
Zou hier een issue voor kunnen aanmaken in https://github.com/peak3d/inputstream.adaptive/issues en hem dan even hier linken? Dan zal ik samen met Peak3d kijken of we wat verder kunnen komen.

**Comment by kengithub9** [comment]
Ik zal er melding van maken bij Peak3d zodat er een oplossing komt want ik weet natuurlijk niet of er nog meer mensen zijn die dit probleem hebben. Voor nu alvast bedankt.

**Comment by kengithub9** [comment]
Ik heb inmiddels melding gemaakt van deze bug bij Peak3d nu dus afwachten op hen voor een oplossing

**Comment by Ctheman** [comment]
Hoe is het hier nu mee, ik heb geconstateerd dat als je "Recent" gebruikt hij het laatste stukje afspeelt, maar als je gewoon via "A-Z" doet hij vanaf het begin afspeelt (idd alleen bij RTL)

**Comment by basrieter** [comment]
Je zult de InputStream Adaptive moeten gebruiken om dat probleem te voorkomen @ctheman. Maar dan speelt het weer te snel kennelijk. 

Ik hoop dat we binnenkort een nieuwe InputStream Adaptive komt. Maar laat vooral even een (Engelstalige) berichtje achter in https://github.com/peak3d/inputstream.adaptive/issues/335

**Comment by Ctheman** [comment]
@basrieter , heb de Inputstream Adaptive gebruiken indien mogelijk uit staan, en speel de programma's  af via "A-Z". Daar valt prima mee te leven ;)

**Comment by kengithub9** [comment]
Helaas werkt het nog steeds niet goed bij RTLxl.
Helaas krijg ik de nieuwe Inputstream 2.4..3. niet op mijn Eminent LibreElec 18.4 geïnstalleerd. Ik krijg telkens een foutmelding bij het installeren vanaf usbstick.

**Comment by basrieter** [comment]
Dat is vervelend. Bij Kodi 18.6 krijg je automatisch de nieuwe inputStream Adaptive add-on. Hebben ze die al? Anders een LibreElec  proberen?

**Comment by Ctheman** [comment]
Probeer deze inputstream eens, werkt bij mij prima !

https://relkai.coreelec.org/addons/9.2/Amlogic/arm/inputstream.adaptive/inputstream.adaptive-2.3.22.2.zip

**Comment by kengithub9** [comment]
Helaas werkt dat niet. Het komt denk ik door mijn Eminent LibreElec 18.4(9.0) dat de inputstream niet te installeren is. Ik kan hem niet zelf bijwerken met LibreElec(9.2)

**Comment by Ctheman** [comment]
Dan ga je toch terug naar CoreElec, sowieso een beter alternatief voor AMLogic devices

**Comment by kengithub9** [comment]
Eindelijk heb ik Retrospect weer kunnen testen op het afspelen van RTLXL.
Doordat nu CoreELEC 9.2.2. Kodi18.6 uit is gekomen. LibreElec niet actief bijgewerkt door Eminent dus moest ik CoreElec installeren. 

Retrospect 5.21. Inputstream 2.4.4..1 inputhelper 0.4.4.

Helaas lukt het niet om de video's correct af te spelen. 
Via de instelling van Retro zelf inputstream aan werkt niet en ook uit niet. Ook via menu recent of A t'/m z lijst werkt het niet. 
Ook heb ik zelf bij RTLxl de instelling van retrospect verzet naar enabled of disabled maar dat helpt niet. Telkens loopt het beeld en geluid te snel. Bij disabled krijg ik alleen het laatste stuk van de aflevering.
Bij Kijk of NPO start werkt alles gewoon goed met inputstream aan in het menu van retrospect.

Wie kan dit oplossen?

**Comment by basrieter** [comment]
Toch mooi dat je dit in 3 verschillende plaatsen cross-post. Niet zo netjes. Heb je een DEBUG retrospect.log? Graag volledig posten op paste.kodi.tv of via de ingebouwde functionaliteit van Retrospect.

**Comment by Ctheman** [comment]
Zet de inputstream gebruiken indien mogelijk op "uit" en gebruik de door mij eerder genoemde inputstream van reilkai. Daarna inputstream auto update uitzetten.

**Comment by kengithub9** [comment]
Ik heb inmiddels een DEBUG via de ingebouwde functie van Retrospect verstuurd.
En sorry dat ik het op drie plaatsen heb geplaatst. 

@Ctheman die versie werkte toen wel maar alleen voor RTLxl en een paar andere addons werken toen niet meer dus een oude versie blijven gebruiken is voor mij geen optie.

**Comment by basrieter** [comment]
> Ik heb inmiddels een DEBUG via de ingebouwde functie van Retrospect verstuurd.
> En sorry dat ik het op drie plaatsen heb geplaatst. Ik heb ze inmiddels verwijderd.
> 
> @Ctheman die versie werkte toen wel maar alleen voor RTLxl en een paar andere addons werken toen niet meer dus een oude versie blijven gebruiken is voor mij geen optie.

Je zult dan wel zelf nog even de link hier moeten posten. Na het uploaden wordt deze weergegeven. Het komt niet automatisch hier terecht.

**Comment by kengithub9** [comment]
Hierbij de link: https://paste.kodi.tv/ovuyuwufec

**Comment by Ctheman** [comment]
> die versie werkte toen wel maar alleen voor RTLxl en een paar andere addons werken toen niet meer dus een oude versie blijven gebruiken is voor mij geen optie.

Hier loopt Coreelec 9.2.2 met inputstream adaptive 2.3.22.2 prima, de streams van RTL, SBS en NPO doen het prima, zowel bij "Recent" als "A-Z"

Alle andere add-ons (Youtube, The Crew, Shadow) werken goed.

**Comment by basrieter** [comment]
> Hierbij de link: https://paste.kodi.tv/ovuyuwufec

Je log bevat enkel het posten van de log. Graag nog een keer afspelen en dan uploaden

**Comment by kengithub9** [comment]
Hierbij hopelijk de juiste log: https://paste.kodi.tv/axoqurujan

**Comment by basrieter** [comment]
Thanks, zie er niks raars is. Dus dan kan ik jammer genoeg niet echt verder helpen? Is er al een Matrix build voor CoreElec/LibreElec? Wellicht kan je die eens proberen.

**Comment by kengithub9** [comment]
Jammer dat er niks mis is want nu blijft het probleem. Een Matrix build is er nog niet. Misschien even die andere optie proberen.

**Comment by thomazz-nl** [comment]
Hi Bas Rieter, bij deze ook een bijdrage van een andere gebruiker. Ik ervaar dezelfde issues als kengithub9. Hieronder twee verschillende logs, één van Kodi op Windows (geen problemen met afspelen van RTL XL) en één van Kodi op OSMC (Vero4k device). Laatstgenoemde heeft de sync issues met afspelen.
[retrospect_windows.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4808172/retrospect_windows.log)
[retrospect_vero4k.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4808173/retrospect_vero4k.log)

Een bijdrage met de logfiles van Kodi en video voorbeeld zijn in het issue bij [inputstream.adaptive](https://github.com/peak3d/inputstream.adaptive/issues/335#issuecomment-647011292) te vinden.

Hopelijk weet iemand de vinger op de zere plek te leggen met deze aanvullende info.

**Comment by basrieter** [comment]
Ik ga deze sluiten. Als je het probleem nog steeds hebt, dan hoor ik het graag.
