### ISSUE TITLE
three errors

### ISSUE THREAD

**Issue by Diggler74** [retrospect-addon/plugin.video.retrospect#1236]
### Describe the bug

three errors occur: 

- 'recent'  and open any day: error
- open tv shows (full list): error
- after opening tv shows (A-Z) and open any tv show: error

## Expected Behavior

To work just fine

## Actual Behavior

shows nothing besides error message

## Possible Fix

You know best

### Your Environment
Used Operating system:

 - [x] AndroidTV
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.4
- Retrospect version: latest (official Kodi Repo)

**Comment by Diggler74** [comment]
thanks. Should have mentioned channel NPO. 

i did read #1233 issue before posting. This issue #1233 says "NPOstart does not show any programs anymore"

which is not the same issue as i posted.

**Comment by basrieter** [comment]
Exactly the same issue. An update will be there as soon as the Kodi repo's sync
