### ISSUE TITLE
UR Play broken again

### ISSUE THREAD

**Issue by bubbleboyy** [retrospect-addon/plugin.video.retrospect#1237]
Categories not working "Retrospect error. Error retrieving the list of items" #1226

**Comment by basrieter** [comment]
Please try to stick to the bug template! That template also asked for a DEBUG retrospect.log that contains the issue. Could you provide one?

**Comment by Snaah** [comment]
Here's a log. 
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/3719653/retrospect.log)

Discovered now there are radio shows in the listings. Don't know if that is something you want to do something about. Played https://urplay.se/program/210286-mifforadio-kanslor

**Comment by basrieter** [comment]
How do I navigate there?

**Comment by Snaah** [comment]
I found the category now: https://urplay.se/bladdra/radio. If you care to put energy to it, this could be the first time there's a root folder for ".: Radio :." in a Swedish channel.

The show I played in Retrospect (Känslor) is under ".: Sista chansen :.". Retrospect plays it just fine and displays the picture, but it gives an error about it not being able to play it. 

The label for radio is **u'format': u'audio'**, for video **u'format': u'video'**.

**Comment by bubbleboyy** [comment]
Sorry, Im new to github. Do you want my retrospect.log or can you use snaahs?

**Comment by basrieter** [comment]
You can enable debug logging in Retrospect, generate the error again and then use the build-in functionality to upload the log. Then post the link here.

**Comment by bubbleboyy** [comment]
The log: https://paste.kodi.tv/iqakaqoyep

**Comment by basrieter** [comment]
Ok, so your problem is not Retrospect at all, but you get a `504 Gateway Time-out` error. That means that there is a server/network element that did not respond in time. 

I tested myself, but UR Play seems to be just fine (except for the Radio streams perhaps). It could be related to your internet connection. Could you check that? Perhaps restart your (wifi)router/modem.

**Comment by bubbleboyy** [comment]
here is a new log: http://paste.kodi.tv/ikilewemek
The 504 Gateway Time-out error is gone now. Maybe there was a server hiccup on their side.

**Comment by bubbleboyy** [comment]
Here is the kodi log: https://paste.kodi.tv/aluhuxepoq

**Comment by basrieter** [comment]
Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi.

[retrospect-patch-20191013.204848.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3722142/retrospect-patch-20191013.204848.zip)

**Comment by bubbleboyy** [comment]
Categories working now. Thank you!

**Comment by Snaah** [comment]
Can confirm categories are working. Thank's Bas!

Lyssna: Great to have. As you indicated, some of the streams don't seem to work. No biggie for me, but can provide a debug log coming days.

**Comment by basrieter** [comment]
@Snaah do you have an example of a stream that does not work?

**Comment by Snaah** [comment]
@basrieter I can't find any streams not working now. Must have been something at my end. Will report back if I find any. Issue can be closed.

**Comment by bubbleboyy** [comment]
Categories not working again.
Retrospect: https://paste.kodi.tv/vikuluxoho
Kodi: https://paste.kodi.tv/jodopirode

**Comment by basrieter** [comment]
Nope it is not. The fixed version I posted here still works like a charm. The logs you post are not for the version I added here. Sorry.
