### ISSUE TITLE
TV4 play Sweden has moved its API?

### ISSUE THREAD

**Issue by tintin42** [retrospect-addon/plugin.video.retrospect#1240]
### Describe the bug
It seems like the API for TV4 Sweden has moved. in the retrospect log the plugin tries to pull e.g. categories from http://webapi.tv4play.se/play/categories.json which as of today is an empty file.

Tried to pull the file from another IP location as well, but with the same results. 

## Expected Behavior
Beeing able to browse and view TV4 Sweden

## Actual Behavior
Error "Error retreiving list of items" for all items items under TV4. The channel works from their web page.

## Possible Fix
Tried to find the api from a debugger but didn't really know where to look for the api calls.

### To Reproduce
1. Fresh install of OSMC, installed retrospect and widewine.
2. Try to use TV4 sweden

### Debuglog
The **debug** retrospect.log can be found here:
http://paste.kodi.tv/ujucaxeqov

### Your Environment
Used Operating system:
 - [ ] Raspberry-Pi

Used versions:
- Kodi version: 18.3
- Retrospect version: 5.0.7

**Comment by basrieter** [comment]
Is it just the Categories?

**Comment by JohanG72** [comment]
Same for me on kodi 18.4. Retrospect 5.0.7. Elementary OS Loki. Does not play anything on tv4play. Displays error "could not get programlist" no matter what I choose. Other channels work..

**Comment by basrieter** [comment]
Ok, so I need to look into this. But I am rather busy at the moment, it might take some time.

**Comment by JohanG72** [comment]
Tnx for doing such great work :-)

**Comment by peakdeveploer** [comment]
> Ok, so I need to look into this. But I am rather busy at the moment, it might take some time.

According to my quick analysis *could* the fix be as simple as
http://webapi.tv4play.se/play/categories.json
->
http://api.tv4play.se/play/categories.json

**Comment by basrieter** [comment]
Let me check that!

**Comment by basrieter** [comment]
Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi.

[retrospect-patch-20191015.234422.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3731585/retrospect-patch-20191015.234422.zip)

Let me know if this works.

**Comment by dobbelina** [comment]
> 
> 
> Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi.
> 
> [retrospect-patch-20191015.234422.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3731585/retrospect-patch-20191015.234422.zip)
> 
> Let me know if this works.

Thanks basrieter, fix works. 👍

**Comment by JohanG72** [comment]
Works great. Tnx 🙏

**Comment by basrieter** [comment]
I will push a new release somewhere this week.

**Comment by Klench** [comment]
Thank you @basrieter! Sorry for a noobish question but where should the file be put, more specifically?

**Comment by basrieter** [comment]
Weird, it should be there? In the retrospect.log and kodi.log the paths are written. Check there.

**Comment by bubbleboyy** [comment]
> Thank you @basrieter! Sorry for a noobish question but where should the file be put, more specifically?

You can unzip retrospect-patch-20191015.234422.zip and then move the plugin.video.retrospect folder to plugin.video.retrospect-5.0.7.zip.

**Comment by Klench** [comment]
> Weird, it should be there? In the retrospect.log and kodi.log the paths are written. Check there.

Apparently I was running Retrospect 4.0.7 so everything worked properly after I installed 5.0.7 instead. Thank you!

**Comment by basrieter** [comment]
Great! I will create an official update soon. Keep in mind @Klench  that from now on you should install via the Kodi repository.

**Comment by basrieter** [comment]
Reopening this to prevent useless duplicate bugs for users that don't search.

**Comment by Espancor** [comment]
I tried to replace it as you said (manually) but I didin´t make it. 
In swedish: Är det någon som har lyckats?

**Comment by basrieter** [comment]
How did you try that? You need to manually (via a file explorer) overwrite your original files with the ones in the zip, then restart Kodi.

**Comment by Klench** [comment]
> I tried to replace it as you said (manually) but I didin´t make it.
> In swedish: Är det någon som har lyckats?

I used a SCP command (SSH) to replace `chn_tv4se.py` in `~/.kodi/addons/plugin.video.retrospect/channels/channel.se/tv4se/`. 

Make sure to run Retrospect 5.0.7 and then restart Kodi.

In swedish: Det gick perfekt när jag såg till att köra rätt version av Retrospect.

**Comment by basrieter** [comment]
I also did a PR for an official update: https://github.com/xbmc/repo-plugins/pull/2568

**Comment by Espancor** [comment]
I did it in my pc and then I put it in a pendrive and after that on my Android Tv. I´m sorry if I don´t understand you guys. 
I´m not very good using SCP @Klench  
I can wait untill everything is fix it! Thank you @basrieter  and I love your work here with this addon, I have been using it a few years

**Comment by Snaah** [comment]
@Espancor No need to use anything other than "standard". What to do:

PC:
Download the patch and extract it (and replace files) to **%userprofile%\AppData\Roaming\Kodi\addons\** (assuming you have installed Kodi to the default path).

Android TV:
If you already have the zip on your TV, extract/copy the files (and replace) to **Android\data\ org.xbmc.kodi\files\.kodi\addons\**. The directory **.kodi** is hidden, so you must activate showing of hidden files and directories in your filebrowser app. I use the excellent [X-plore File Manager](https://play.google.com/store/apps/details?id=com.lonelycatgames.Xplore&hl=en_US). It can handle zips.

You can also use TeamViewer from your PC to control your Android TV and transfer the files to the right directory. It is perhaps the easiest way. I use it myself.

If it won't work, I can guide you in Swedish. :)

**Comment by basrieter** [comment]
I expect and official update today.

**Comment by Espancor** [comment]
@Snaah Tror att jag kommer att vänta på uppgraderingen, men det var snällt av dig.
Men du kanske vet hur man kan komma undan geo blockeringen?

**Comment by basrieter** [comment]
Please don't discuss circumventing GEO restrictions here. It is against the policy of the broadcasters.

**Comment by Espancor** [comment]
@basrieter Oh! I´m sorry so much! It was my fault!

**Comment by basrieter** [comment]
Update 5.0.8 rolling out.

**Comment by kaisto** [comment]
Realt nice Bas!! You are excellent
