### ISSUE TITLE
Swedish TV4 can´t play anything

### ISSUE THREAD

**Issue by Espancor** [retrospect-addon/plugin.video.retrospect#1241]
Hi! Anyone having problems to play Swedish Tv4?
I have update my kodi with the latest version and I using kodi on my Android Tv.

**Comment by basrieter** [comment]
So three things:

1. Please stick to the format for a but. We added a template there to get valuable feedback
1. You did not attach a debug retrospect.log, so we can't even see what is going on in you machine.
1. You need to search: #1240 or https://github.com/retrospect-addon/plugin.video.retrospect/labels/tobereleased

**Comment by Espancor** [comment]
Oops!! Sorry for that! It was my first question here, noob!! 🙏

Den tors 17 okt. 2019 20:37Bas Rieter <notifications@github.com> skrev:

**Comment by basrieter** [comment]
NP. Working on a release via the Kodi repo
