### ISSUE TITLE
Swedish TV4 cannot list programmes

### ISSUE THREAD

**Issue by ChrisIse** [retrospect-addon/plugin.video.retrospect#1242]
### Describe the bug
Here is a clear and concise description of what the problem is:

On Swedish TV4 it is not possible to list programmes and therefore not possible to watch them.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Clicking on Retrospect -> TV4 Play -> Most Viewed Episodes should list them

## Actual Behavior

No list, Just message "Error retrieving the list of items"

### Debuglog

The **debug** retrospect.log can be found here:
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/3742611/retrospect.log)
[kodi.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/3742612/kodi.log)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.2
- Retrospect version: 5.0.7

**Comment by basrieter** [comment]
Please search open and closed issues: #1240 #1241

**Comment by ChrisIse** [comment]
Sorry, can't believe I missed that. Thanks.

Chris

Den fre 18 okt. 2019 kl 09:07 skrev Bas Rieter <notifications@github.com>:
