### ISSUE TITLE
UR Play broken

### ISSUE THREAD

**Issue by bubbleboyy** [retrospect-addon/plugin.video.retrospect#1244]
### Describe the bug
Here is a clear and concise description of what the problem is:

Categories not working.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The list of items should appear
## Actual Behavior

No categories. Only Retrospect error. Error retrieving the list of items
## Possible Fix

Worked with the latest patch, but a few days later it was broken again.

### To Reproduce

1. Open UR Play
2. Categories
3.

### Debuglog

The **debug** retrospect.log can be found here:
retrospect: https://paste.kodi.tv/vikuluxoho
Kodi: https://paste.kodi.tv/jodopirode

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.4
- Retrospect version: 5.0.7

**Comment by bubbleboyy** [comment]
They seems to break the categories all the time.

**Comment by basrieter** [comment]
Please search: #1237

**Comment by bubbleboyy** [comment]
Its a new problem...
