### ISSUE TITLE
"No episodes found"

### ISSUE THREAD

**Issue by kennypenny666** [retrospect-addon/plugin.video.retrospect#1246]
Bij "opsporing verzocht" onder NPO favorieten.
Fix graag,danku.

**Comment by basrieter** [comment]
Houd je aub aan de template die er voor een bug. Daarin staat namelijk dat ik een debug retrospect.log logfile nodig heb en een overzicht van hoe het probleem is te reproduceren. Dus met een enkel zin ga je er niet komen.

Graag even deze bug editen in het juiste formaat.

**Comment by kennypenny666** [comment]
> 
> 
> Houd je aub aan de template die er voor een bug is. Daarin staat namelijk o.a. dat een debug retrospect.log logfile nodig is en een overzicht van hoe het probleem is te reproduceren. Dus met een enkel zin ga je er niet komen.
> 
> Graag even deze bug editen in het juiste formaat.

" Something went really wrong, and we can’t process that file." staat er hier wanneer ik de log probeer te uploaden

**Comment by kennypenny666** [comment]
hier dan via pastebin 

https://pastebin.com/qkBNBw6p

**Comment by basrieter** [comment]
Thanks, maar je beschrijft nog steeds niet wat je nu precies doet? Wat bedoel je met _NPO favorieten_?

**Comment by basrieter** [comment]
Er was er gewoon geen geschikbaar. Vandaag is er 1 bijgekomen. Zie ook https://www.npostart.nl/opsporing-verzocht/AT_2046088/episode

**Comment by kennypenny666** [comment]
Wat bedoel ik nou met favorieten?
De favorieten die onder mijn NPO PROFIEL staan! Ik heb je toch de log gestuurd.
Ik heb dat programma er in staan en daar krijg ik NO EPISODES.
Dus mijn vraag is of je dat kan fixen ajb.

**Comment by kennypenny666** [comment]
Er staat nu 1 episo, maar alle beschikbare episodes horen daar te staan! net als alle andere episodes onder de favoriete shows in mijn profiel!
Dus er klopt iets niet bij Opsporing verzocht.
