### ISSUE TITLE
Er staat maar 1 aflevering bij "opsporing verzocht"onder favoriete SHOWS onder mijn NPO PROFIEL

### ISSUE THREAD

**Issue by kennypenny666** [retrospect-addon/plugin.video.retrospect#1247]
Waar slaat het nu op dat je dat bug topic sluit??Er is toch niks opgelost nu?
Ik leg je toch uit wat ik bedoel met favorieten? Ik heb je notabene mijn log gestuurd!
https://github.com/retrospect-addon/plugin.video.retrospect/issues/1246

**Comment by basrieter** [comment]
> Waar slaat het nu op dat je dat bug topic sluit??Er is toch niks opgelost nu?
> Ik leg je toch uit wat ik bedoel met favorieten? Ik heb je notabene mijn log gestuurd!
> #1246
Ietwat respect voor iemand die in zijn vrije tijd open source software maakt mag wel. 

Ik heb gekeken naar je log en er waren op dat moment gewoon niet meer afleveringen beschikbaar. Nu is er 1 en dat is ook exact wat er op npo.nl staat. Meer kan ik er dan ook niet tevoorschijn toveren.

**Comment by kennypenny666** [comment]
Ja je hebt gelijk dat er maar 1 aflevering staat van Opsporing Verzocht ook op NPO zelf. Ik vind dat wel raar. Waarom is dat denk je?
Bij andere shows zijn er tientallen afleveringen beschikbaar!

**Comment by basrieter** [comment]
Geen idee. Wat ik wel merk is dat NPO steeds meer content als premium gaat aanbieden. En die krijg je dan nu niet te zien. Maar meer dan dit kan ik er dus ook niet aan doen. Sorry.

**Comment by kennypenny666** [comment]
Maar ik heb een HD abbo bij NPO en nog staat er maar 1 aflevering.

**Comment by basrieter** [comment]
Dan weet ik het ook niet zo. Je zou het wellicht bij NPO kunnen navragen, maar ik zou daar geen Kodi bij noemen (houden ze niet echt van) en enkel vragen waarom het niet op de site staat.

**Comment by kennypenny666** [comment]
Ja ik heb het ook gevraagd net inderdaad. Of ik antwoord krijg is vraag 2,want daar zijn ze niet zo goed in daar.
En nee natuurlijk noem ik Kodi of jouw app niet, dat heeft er ook niks mee te maken.

**Comment by basrieter** [comment]
Ik ben benieuwd wat ze zeggen.

**Comment by kennypenny666** [comment]
Ik laat het je weten.

**Comment by kennypenny666** [comment]
Hier het antwoord van NPO:

"Dit komt omdat Opsporing Verzocht maar een week is terug te kijken. Op vrijdagavond wordt de uitzending offline gehaald. Indien een verdachte, gezocht in een van onze afleveringen, gevonden wordt, zijn wij verplicht om de uitzending direct offline te halen."

Nou wat een onzin zeg. Dus wanneer die verdachte opgepakt word en moet boeten,dan moeten wij dus ook boeten door het niet meer kunnen bekijken van afleveringen.
Maar goed,er is nu tenminste duidelijkheid hierover.

**Comment by basrieter** [comment]
Ok, in ieder geval wel een antwoord. Ik ga het sluiten hier dan.
