### ISSUE TITLE
Favorites conversion when a channel is updated

### ISSUE THREAD

**Issue by Snaah** [retrospect-addon/plugin.video.retrospect#1249]
### Is your feature request related to a problem? Please describe

Sometimes when channels are updated the favorites for that channel are broken. The user then has to update the favorites manually, one by one. Would be great if Retrospect would convert the favorites.

### Describe the solution you'd like

Retrospect automatically converts the favorites list so that it works with the updated channel.

**Comment by basrieter** [comment]
I understand the issue, but that is really not possible. If urls change, I really can't create a mapping for all shows. I just can't. I could remove those that are broken, but then you would not know which ones you had. 

So this is just a thing I can't fix. If a website changes pages, Chrome/Firefox also won't update their bookmarks automatically. Same story.

**Comment by Snaah** [comment]
Ok. So when channels are changed it's never about just the domain or directory path of the URL or such, but the entire URL?

**Comment by basrieter** [comment]
It can be anything that can cause a channel update. But only those changes that include an domain/url update will break the favorites as a favorite items had a specific URL that is then outdated.

**Comment by Snaah** [comment]
Got an idea. You said you could remove those that are broken. As you say it's better to keep the. But could they be marked somehow too? Like with a red medium "dot"?

**Comment by basrieter** [comment]
In theory, yes, but I can't detect which ones are broken. The fact that they are broken is because the URL no longer exists or no longer contains videos. 

There is no way to detect that beforehand.

**Comment by Snaah** [comment]
Ok. I guess having Retrospect check what it can and can't reach would be too much work?

**Comment by basrieter** [comment]
Well, imagine somebody having 100+ favourites. If opening those would require all 100 favourites to be validated by opening an url, it would take a long time.

**Comment by Snaah** [comment]
You're right and I don't want to "demand" something which requires a lot of work. If that function could only be activated manually then? Like "Check validity of favorites".

**Comment by basrieter** [comment]
If I take this to a broader aspect: would it make sense to give broken items a "red" color? So you know it will either not list any videos (in case of a folder) or not play (in case of a video). That would work for all things (including favourites).

**Comment by Snaah** [comment]
Yes, I believe red is the color to use. It says "error".

**Comment by basrieter** [comment]
I do need to check if this all is feasible, and it won't be before somewhere end of next week.

**Comment by Snaah** [comment]
Take all the time you need! Good luck with the certificate. 🙂
