### ISSUE TITLE
NPOstart 8 uur journaal is missing from the recent program list since last Monday

### ISSUE THREAD

**Issue by ErikBrown2** [retrospect-addon/plugin.video.retrospect#1251]
### Describe the bug
Here is a clear and concise description of what the problem is:
This is only a minor issue but since last Monday the 'Recent' program listing does not show anymore the 8 uur journaal. The 8 uur journaal is shown in the full program listing TV Shows (A-Z) and also in the recent days before last Monday. I am not sure where you get the list from but when I check the NPO start site and look for yesterdays programs, then the 8 uur journaal does show up.

EDIT. It appears that the NOS journaal episode of 20:00 hours is incorrectly listed at 21:00 hours in the Recent program list. Also all other NOS journaal episodes throughout the day shown in the TV Shows (Full list) program list used to have the time added to the entry. This time has now disappeared so it is not possible to determine which episode was transmitted at what time. In the TV Shows (A-Z) program list the NOS Journaal is completely missing although I am not sure if it was shown there before.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Start Retrospect, then select NPO Start, Recent, Yesterday, browse to 20:00 and see the NOS journaal listed
EDIT. Also show the time for the NOS journaal entries in the TV Shows (Full list) as part of the program name in order to be able to identify the original transmission time of the episode.

## Actual Behavior

The NOS journaal is not shown at 20:00 hours. Other programs are shown but not the NOS journaal 
EDIT. The 20:00 hours NOS journaal appears to be shown in the Recent list at 21:00 hours. The NOS journaal entries throughout the day in the TV Shows (Full list) do not show the time of the episode anymore as part of the program name.

## Possible Fix

You know best

### To Reproduce

1. Start Retrospect, then select NPO Start, Recent, Yesterday, browse to 20:00. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here: https://paste.kodi.tv/obuneweyuv

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: LibreELEC (Leia) 9.2 Beta 2
- Retrospect version:

**Comment by basrieter** [comment]
There was a Daylight saving issue (Zomertijd/wintertijd). It is fixed and will be in the next release.

**Comment by basrieter** [comment]
See: https://github.com/retrospect-addon/plugin.video.retrospect/commit/c133db9dd7a3460ef89292c3c5de3988c0bb34f4
