### ISSUE TITLE
NPO Start NOS Journaal heeft geen tijdsaanduiding meer

### ISSUE THREAD

**Issue by ErikBrown2** [retrospect-addon/plugin.video.retrospect#1253]
### Describe the bug
Here is a clear and concise description of what the problem is:

Het NPO Start NOS Journaal had voorheen de uitzendingstijd als onderdeel van de episode naam. Iets in de geest van NOS Journaal 20:00 . Maar nu is het alleen nog maar NOS Journaal. Dus het is erg lastig om uit te vinden welke episode op welke tijd was uitgezonden.
## Expected Behavior
Here is a clear and concise description of what was expected to happen:

 In de lijsten TV Shows(Full list)  en TV Shows (A-Z) en dan NOS Journaal hadden voorheen alle uitzendingen van het journaal  de naam NOS Journaal 20:00 of zo. Dus de tijd van uitzending was deel van de episode naam.
## Actual Behavior

In de lijst TV Shows(Full list) - NOS Journaal hebben alle uitzendingen van het journaal de naam NOS Journaal. Er is geen onderscheid meer op uitzendingstijd.
## Possible Fix

Voeg de tijd toe aan de naam NOS Journaal zoals NOS Journaal 20:00
### To Reproduce

1. Start NPO Start
2. Ga naar TV Shows (full list) of ga naar TV Shows (A-Z) en dan naar N
3. Ga naar NOS Journaal
4. Alle uitzendingen hebben de naam NOS Journaal
### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/atabahupor

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: LibreELEC (Leia) 9.2 Beta 2
- Retrospect version: 5..1.0

**Comment by basrieter** [comment]
Ik ga er naar kijken, daar had ik iets voor ingebouwd, maar dat werkt wellicht niet meer. Ik gok als gevolg van de wintertijd...

**Comment by basrieter** [comment]
Zou je deze via de "install from zip" feature kunnen installeren?  Volgens mij moet het zo weer werken. Ik heb ook nog wat gefixed met de zomer/wintertijd dus nu zou het allemaal weer OK moeten zijn. 

[plugin.video.retrospect-5.1.0-NPO-Journaal.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3828451/plugin.video.retrospect-5.1.0-NPO-Journaal.zip)

**Comment by ErikBrown2** [comment]
Hallo Bas,

Werkt als een trein! Heel mooi. Hartelijk bedankt!

**Comment by basrieter** [comment]
Mooi zo! Dan ga ik het in de volgende release stoppen.
