### ISSUE TITLE
SVT Error retriving the list of items 

### ISSUE THREAD

**Issue by Egon666** [retrospect-addon/plugin.video.retrospect#1254]
### Describe the bug
Here is a clear and concise description of what the problem is:

After yesterdays update to 5.1.0 SVT stopped listing episodes under the series name folder and throw "Error retriving the list of items" instead. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [x] iOS
 - [x] Linux
 - [x] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [x] Windows UWP

Used versions:
- Kodi version: Leia 18.4
- Retrospect version:5.1.0

**Comment by basrieter** [comment]
Please fill the complete template and provide me with a log file.

**Comment by hakgle47** [comment]
For me Retrospect 5.1.0 worked perfect for a few days. Yesterday afternoon SVT Play stopped working. Other swedish channels, for example UR Play, works.

I providing my logfile. 
[kodi.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/3823682/kodi.log)

**Comment by SteX68** [comment]
Can confirm that it do not work, maybe they changed the program list location on SVT?

**Comment by Egon666** [comment]
I am not close to my kodi machine this weekend. @basrieter do You have enough information with the provided log to move forward?

**Comment by basrieter** [comment]
Yes, their API changed. Need to fix it big time but don't have the time the coming days

**Comment by SteX68** [comment]
Thank you @basrieter for letting us know what the problem is, take your time and good to know you'll fix it after some days :) have a great weekend.

**Comment by basrieter** [comment]
Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi.

This will make the basic stuff work again.

[retrospect-patch-20191115.225320.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3853322/retrospect-patch-20191115.225320.zip)

**Comment by hakgle47** [comment]
I tried the new version (5.1.1) and it works perfectly for me.

@basrieter  - Thank you very much!

**Comment by basrieter** [comment]
With the provided patch I assume?

**Comment by Egon666** [comment]
Works fine for me with the patch, thank you!

Den lör 16 nov. 2019 12:58Bas Rieter <notifications@github.com> skrev:

**Comment by hakgle47** [comment]
Yes, I installed the patch. After that the version number increaset to 5.1.1.

**Comment by Snaah** [comment]
@basrieter Titles A-Z shows and playing episodes works. But all root selections besides .: TV-kanaler :.` are gone. .: Genrer/Taggar :., .: Senaste :., .: Sök :. and so on does not show. @hakgle47 @Egon666 @SteX68 Please confirm it is like this at your place too.

**Comment by hakgle47** [comment]
@Snaah, I agree. Root-selections and other features titles A - Z doesn´t work. I assumed that this was a quick fix just to get basic funtion up an running.

I guess SVT made a major change on their site and Basrieter need a while longer to fix all functions.

**Comment by Sopor** [comment]
@Snaah If you read in the patch you will see
`# TODO: Not working         # Genres/tags (using JSON)`

**Comment by basrieter** [comment]
Isn't that exactly what I said: the basic stuff is working...the rest will come later

**Comment by Snaah** [comment]
Ok, didn't see that. Good work!

**Comment by SteX68** [comment]
Thank you very much @basrieter ,work perfectly :)

**Comment by basrieter** [comment]
New patch files. You can replace the original ones (don't install from zip)

[retrospect-patch-20191117.172933.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3855808/retrospect-patch-20191117.172933.zip)

**Comment by basrieter** [comment]
New patch files. You can replace the original ones (don't install from zip)

[retrospect-patch-20191117.172934.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3855914/retrospect-patch-20191117.172934.zip)

**Comment by Sopor** [comment]
It seems to work but genre and search are still missing

**Comment by basrieter** [comment]
Patience......

**Comment by basrieter** [comment]
I added the "Genres":

[retrospect-patch-20191122.005112.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3877275/retrospect-patch-20191122.005112.zip)

**Comment by basrieter** [comment]
I think I have them all now. Please verify by MANUALLY replace the existing files with the one inside zip file.

[retrospect-patch-20191123.213759.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3882891/retrospect-patch-20191123.213759.zip)

**Comment by SteX68** [comment]
Looks as it should at my end (confirmed) ,but would like one more to confirm it if I missed something.
Thank you.

**Comment by basrieter** [comment]
Genre and Tags are now the same. Even in their site. You go to the Genre page and click on _more_ .

I am in doubt whether or not to not have the first main listing in a separate folder.

**Comment by Snaah** [comment]
Great work, Bas! Search works too.

**Genre/tags**: This is a huge drawback, because the "main" genres are very useful. By "main" genres I mean the categories shown on top of this page: https://www.svtplay.se/program. So they make no distinction in the api anymore? Idiotic. 

If this is to be like this, change "Genrer/Taggar" to "Genrer" **OR** to "Genrer/taggar". The language police have eyes everywhere. ;)

**Main listing in separate folder**: Please do NOT do this. It is not good like it is on TV4 now and makes no sense, as you use Retrospect to look at (TV-)programs. If many want this, make it an option?

**Comment by basrieter** [comment]
@Snaah I can almost always fix stuff that SVT break. Here are your categories back:

[retrospect-patch-20191124.225719.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3884186/retrospect-patch-20191124.225719.zip)

And I lowered the "T" of Tags/Taggar.

**Comment by Snaah** [comment]
Working. Fabulous, Bas!
