### ISSUE TITLE
No subtitle on tv4 play. 

### ISSUE THREAD

**Issue by mangebest** [retrospect-addon/plugin.video.retrospect#1255]
The subtitle on tv4 play was working for a while.
But since the latest update it is gone again.
Best regards 
Magnus
Kodi Leia and latest retrospect

**Comment by basrieter** [comment]
Attach a DEBUG retrospect.log. But first make sure that you have the InputStream Adaptive add-on enabled in the Retrospect settings.

Also: it could the there are 2 subtitles (one that only translates the non-Swedish texts) so you need to switch to the correct one.

**Comment by basrieter** [comment]
And just to clarify: I can't preselect the right one.

**Comment by maxruben** [comment]
I have the same problem. Sometimes I can get a subtitle by changing to another subtitle than default and sometimes by browsing for subtitles and selecting the current show (it is already marked with green text in the browse list) and sometimes I can not get it to work. I haven't found a way that always works.  Whenever I have selected another subtitle than the default it always jumps back to the default (as I can see when I go into the subtitle menu again). Perhaps it is this that is the problem.

Kodi Leia and the latest retrospect with InputStream Adaptive enabled.
/Ruben

**Comment by basrieter** [comment]
Again, that is Kodi not Retrospect. I could double check but not without a debug retrospect.log

**Comment by maxruben** [comment]
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/3828279/retrospect.log)
Here is the logfile.
After some more testing it seems like it always works if the first subtitle is not the Swedish [Default] and I then select that. If the first subtitle says it is the default Swedish it doesn't work and I can't seem to select the second (external unknown) or get it to work again. But if I then stop the show and start it again (resume is ok) sometimes (but not always) the subtitle order has switched so that the first is not the Swedish and I can then switch to the Swedish subtitle and it works.

/Ruben

**Comment by basrieter** [comment]
So the playback and subtitles are done 100% by the InputStream Adaptive add-on:
```
20191110 10:30:16 - [INFO    ] - mediaitem.py         - 414  - Creating playlist items for Bitrate: 4000 kbps
20191110 10:30:16 - [INFO    ] - mediaitem.py         - 414  - | MediaItem: Ernst i Toscana del 3 [Type=video, Complete=True, IsLive=False, Date=2015-05-04 20:00, Geo/DRM=True/False]
20191110 10:30:16 - [INFO    ] - mediaitem.py         - 414  - | MediaPart: Ernst i Toscana del 3 [HttpHeaders={}]
20191110 10:30:16 - [INFO    ] - mediaitem.py         - 414  - |  + MediaStream: https://lbs-usp-dash-vod.cmore.se/vod/5e85c/10toyou23jc(3148573_ISMUSP).ism/10toyou23jc(3148573_ISMUSP).mpd [bitrate=0]
20191110 10:30:16 - [INFO    ] - mediaitem.py         - 414  - |     + Property: inputstreamaddon=inputstream.adaptive
20191110 10:30:16 - [INFO    ] - mediaitem.py         - 414  - |     + Property: inputstream.adaptive.manifest_type=mpd
20191110 10:30:16 - [INFO    ] - mediaitem.py         - 414  - +     + Property: inputstream.adaptive.license_type=com.widevine.alpha
20191110 10:30:16 - [INFO    ] - mediaitem.py         - 427  - Selected Stream:  MediaStream: https://lbs-usp-dash-vod.cmore.se/vod/5e85c/10toyou23jc(3148573_ISMUSP).ism/10toyou23jc(3148573_ISMUSP).mpd [bitrate=0]
20191110 10:30:16 - [INFO    ] - mediaitem.py         - 427  - |     + Property: inputstreamaddon=inputstream.adaptive
20191110 10:30:16 - [INFO    ] - mediaitem.py         - 427  - |     + Property: inputstream.adaptive.manifest_type=mpd
20191110 10:30:16 - [INFO    ] - mediaitem.py         - 427  - +     + Property: inputstream.adaptive.license_type=com.widevine.alpha
```
I have no control over that. So I would suggest you submit a bug report here: https://github.com/peak3d/inputstream.adaptive/issues

Please keep in mind that you will need to provide all information possible and make sure you create logfiles with a stream that is not a premium or geo-locked stream. Peak3d needs to check the stream and that cannot be done with those streams.

**Comment by maxruben** [comment]
Ok.
Thanks a lot for your quick and excellent support.

/Ruben

**Comment by basrieter** [comment]
This, by the way is the result of TV4 starting to use DRM. See #1250

**Comment by mangebest** [comment]
Hello 
sorry to bother.
In SVTplay i get ”error retrieving the list of items” on every show i try.
i have included a log-file.
I hope i did that correctly.

best regards 
Magnus

**Comment by basrieter** [comment]
@mangebest Please try to search issues before hijacking this one: #1254

**Comment by Leatherface75** [comment]
> This, by the way is the result of TV4 starting to use DRM. See #1250

Isn't it possible to use Widevine for that? It works for CMore so should work for TV4 too.

https://github.com/emilsvennesson/kodi-cmore

**Comment by basrieter** [comment]
@Leatherface75 Yes, that is what I did now and apparently the subs in the Widevine streams suck.

**Comment by Leatherface75** [comment]
Aah ok i saw that now.

**Comment by Leatherface75** [comment]
Seems some subtitles works and some not.
Same programs with Cmore addon shows subtitles without problems.

**Comment by basrieter** [comment]
> Seems some subtitles works and some not.
> Same programs with Cmore addon shows subtitles without problems.

Because they are Cmore streams, not stream hosted on the TV4 platform (even though they are from the same broadcaster)

**Comment by Leatherface75** [comment]
What i mean is that the problem is not Widevine because that addon also uses Widevine.

**Comment by basrieter** [comment]
I did mention that the it are the streams that have the crappy subs. And the InputStream Adaptive add-on just selects those that are there.
