### ISSUE TITLE
SBS stops playing/freezing/no sound

### ISSUE THREAD

**Issue by CMTriX** [retrospect-addon/plugin.video.retrospect#1256]
### Describe the bug
Here is a clear and concise description of what the problem is:

SBS6 stopt met afspelen. Het beeld bevriest, of komt terug in het overzicht. Ook stopt het geluid soms vlak voordat het er uit klapt. Dit gebeurt op de dag dat de uitzending geweest is.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1.  SBS programma's opvragen en afspelen. BV MR. Frank Visser
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/3827123/retrospect.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: latest
- Retrospect version: latest

**Comment by basrieter** [comment]
Playback is done using the Inputstream Adaptive add-on. So I don't have any influence over it. Check your kodi.log and see what it says. 

Alternatively you could try lowering the bitrate for this specific channel.

**Comment by CMTriX** [comment]
Ik ging snel, maar volgens mij kwam er een paar dagen geleden een update voor Inputstream over het scherm. En gisteren werkte sbs6 weer! frapant!

**Comment by basrieter** [comment]
Super!
