### ISSUE TITLE
Gele a bij titels

### ISSUE THREAD

**Issue by CMTriX** [retrospect-addon/plugin.video.retrospect#1257]
### Describe the bug
Here is a clear and concise description of what the problem is:

Ik zie vaak bij items een GELE a. Is dat een foutje of wil dat iets aanduiden?

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

![Knipsel](https://user-images.githubusercontent.com/48124325/68526748-5a0d3900-02df-11ea-8cf7-31506a918dc4.PNG)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:
- Retrospect version:

**Comment by basrieter** [comment]
Dat is een betaalde of een DRM item. In de settings van Retrospect staat dat aangegeven en in de Description van het item.

**Comment by ErikBrown2** [comment]
Hallo Bas, Ik heb hetzelfde op NPO Start. Veel meer programma's dan voorheen hebben zo'n gele "a". En voor de meeste is het een vals alarm. Als ik op op zo'n item met een gele "a" klik, dan zie ik eerst een pop-up met de tekst " Retrospect - Paid video, The selected item is not free and might not play on Kodi." Als ik dan op OK klik, dan speelt het toch af. Het lijkt er op dat het een bug is. Zie hieronder als een voorbeeld een deel van de programma lijst. Een debug log is https://paste.kodi.tv/olipujafek


<a href="https://imgur.com/fkoUK6M"><img src="https://i.imgur.com/fkoUK6M.png" title="source: imgur.com" /></a>

**Comment by basrieter** [comment]
Die info komt uit de NPO Start gegevens. Ik zal eens kijken hoe dat bij deze zit.

**Comment by basrieter** [comment]
Zoals ik al zei: 
![image](https://user-images.githubusercontent.com/1310443/69478402-3de6bd00-0df2-11ea-8b69-2f74ac1c7943.png)

Voor bijv. _Klokhuis - E-Sports_ staat er aangegeven dat hij niet meer `available` is. Zo ook met andere:

![image](https://user-images.githubusercontent.com/1310443/69478435-8aca9380-0df2-11ea-87c9-dc5ca0840c2f.png)

Ook _Pingu_ van vadnaag.

**Comment by basrieter** [comment]
[retrospect-patch-20191123.134157.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3882437/retrospect-patch-20191123.134157.zip)

Ik negeer nu de afleveringen waarbij de start en eind `availability` gelijk zijn. Volgens mij al beter nu.

**Comment by CMTriX** [comment]
> Hallo Bas, Ik heb hetzelfde op NPO Start. Veel meer programma's dan voorheen hebben zo'n gele "a". En voor de meeste is het een vals alarm. Als ik op op zo'n item met een gele "a" klik, dan zie ik eerst een pop-up met de tekst " Retrospect - Paid video, The selected item is not free and might not play on Kodi." Als ik dan op OK klik, dan speelt het toch af. Het lijkt er op dat het een bug is. Zie hieronder als een voorbeeld een deel van de programma lijst. Een debug log is https://paste.kodi.tv/olipujafek
> 
> [![](https://camo.githubusercontent.com/e529e8a9b17caa3d2c76e972443162dc97b10b1d/68747470733a2f2f692e696d6775722e636f6d2f666b6f554b364d2e706e67)](https://imgur.com/fkoUK6M)

Wow! Welke skin gebruik je voor KODI?

**Comment by basrieter** [comment]
Dat is gewoon Confluence volgens mij.

**Comment by ErikBrown2** [comment]
Het is nu inderdaad een stuk beter. Bedankt voor de fix Bas.

<a href="https://imgur.com/w5YlHDx"><img src="https://i.imgur.com/w5YlHDx.png" title="source: imgur.com" /></a>

**Comment by ErikBrown2** [comment]
> Dat is gewoon Confluence volgens mij.

Inderdaad

**Comment by basrieter** [comment]
Mooi zo. Ga ik dat in de volgende versie zetten.
