### ISSUE TITLE
Sbs6 & kijk.nl episodes freeze and stop playing

### ISSUE THREAD

**Issue by martijnabel** [retrospect-addon/plugin.video.retrospect#1258]
When using Retrospect on my Nuc with Libreelec and Kodi Leia, SBS6 and kijk.nl freezes the image and eventually stops playing.
Sound keeps playing when image freezes.
Using retrospect 5.1.0 on Leia 18.4 installed from the official Kodi repository.
I have reinstalled the addon, restarted the nuc nothing helps.
As far as i can see nothing strange in the log files

**Comment by basrieter** [comment]
Please enable debug logging in both Retrospect and Kodi. Try playing again and then attach both kodi.log and retrospect.log here (don't copy paste)

**Comment by basrieter** [comment]
Closing it. If this specific issue is still there feel free to re-open it.
