### ISSUE TITLE
Could you add nuvideo.nl?

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#126]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/126) by Anonymous.**

----------------------------------------

link http://www.nuvideo.nl/  
  
----  
Original item http://code.google.com/p/xot-uzg/issues/detail?id=126

**Comment by dagwieers** [comment]
Should this not be labeled "channel"?

**Comment by Snaah** [comment]
Nuvideo.nl does not seem to exist anymore. Close issue?
