### ISSUE TITLE
NPO Start Plus episodes don't play anymore

### ISSUE THREAD

**Issue by remcox** [retrospect-addon/plugin.video.retrospect#1260]
### Describe the bug
Since a few days, NPO Start Plus episodes (i.e. paid episodes) don't play anymore. This worked perfectly fine until a few days ago.

## Expected Behavior
NPO Start Plus items play normally.

## Actual Behavior
The user interface states "Dit programma is niet (meer) beschikbaar (15)". The logging states: process_video_item returned an MediaItem that had MediaItem.complete = False:

If a certain show has some paid and some non-paid episodes (e.g. First Dates), the paid episodes don't play while the non-paid episodes play fine.

### To Reproduce
1. Try to play any paid episode from NPO Start Plus (i.e. an episode that has an 'a' next to it).

### Debuglog
The **debug** retrospect.log can be found here: https://pastebin.com/cmhrjTjR

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:
 - Linux

Used versions:
- Kodi version: 18.1rc1
- Retrospect version: 5.1.0

**Comment by basrieter** [comment]
I don't have a NPO Plus account, so this is hard to verify for me. If you want you can share your account details with me via email: retrospect {@} rieter [dot] net. That allows me to check this.

**Comment by basrieter** [comment]
Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi and try again. Post a new debug retrospect.log on pastebin.com

[retrospect-patch-20191113.214120.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3843412/retrospect-patch-20191113.214120.zip)

**Comment by remcox** [comment]
Actually, I just shutdown Kodi, removed the Retrospect cache and cookiejar.dat, started Kodi, re-entered the NPO Start Plus credentials and it worked again. The warning in the logging about complete = False does not appear anymore, and instead it states: MediaItem: (...) [Type=video, Complete=True (...)

So that is even without your (kindly provided) patch.

Not sure why this made it work again, because I had not changed anything to the configuration of the machine for the last months, and I have been successfully using Retrospect (including the paid episodes) on a daily basis in this time frame...

**Comment by basrieter** [comment]
It's an issue with the login with NPO. So it would have been nice to have a new log so I can fix the issue? But with you cookiejar being cleaned, that will not be possible anymore. Any way to get them back?

**Comment by remcox** [comment]
I'm afraid I cannot recover the old cookiejar.dat. I cleaned it after I noticed that everything was working correctly on an other machine, so I figured the cache and/or cookies might have got corrupted for some reason.

For now it works correctly again. When the problem occurs again I will apply the patch and post the new logging.

**Comment by basrieter** [comment]
Ok!
