### ISSUE TITLE
Keep viewed history after add-on update

### ISSUE THREAD

**Issue by ErikBrown2** [retrospect-addon/plugin.video.retrospect#1261]
### Is your feature request related to a problem? Please describe

In my opinion the viewed program history (the tick mark or arrow after the program name in the program list) is really useful. It shows you in a simple but helpful way which episodes of a program series you already have watched. But after updating the Retrospect add-on, this history appears to have been deleted. Would it not be possible to maintain the history also after Retrospect add-on updates?
### Describe the solution you'd like

It would be very nice if the watched marks (the tick mark or arrow after the program name) would still be there after a Retrospect add-on update. I realize that you need a mechanism to ensure that the history list does not get too large. But maybe this can be done based on a check of the size of the history list at start up of the add-on?
### Describe alternatives you've considered

The alternative is to remember mentally what you have already watched but for me that is not always so easy.

**Comment by basrieter** [comment]
This is not just related to updates of the addon. The fact is that the url of each items contains information that changes over time. I know that some channels updates thumbnails after about 24 hours and that causes the url within Kodi to change. Currently I can't really fix that, without severely impacting the performance of the add-on. I tried that, see #724

**Comment by Phyxion** [comment]
Ik plaats het hier ook maar even bij, het valt mij op dat dit de laatste paar weken zeer vaak voorkomt bij NPO Start. Ik dacht eerst dat het kwam door de Retrospect updates want het viel wel vaak samen met een update daarvan. Vooral bij series met veel (dagelijkse) afleveringen is het niet ideaal omdat je dan snel het overzicht kwijt bent. Kan voor de NPO Start afleveringen niet gewoon het media id gebruikt worden (bijvoorbeeld KN_1662276)? Volgens mij blijft die altijd hetzelfde voor een aflevering.

**Comment by basrieter** [comment]
Ik de urls die Retrospect gebruikt zit veel meer info die nodig is. Ik ben wel met wat bezig, wat dit zou fixen, maar dat gaat nog even duren.

**Comment by basrieter** [comment]
Ok, ik heb wat geprobeerd. Zou je deze eens kunnen installeren: https://github.com/retrospect-addon/plugin.video.retrospect/archive/feature-pickle-store.zip (via Install from zip)

Wat hier anders is, is dat ik de GUID's van de items gebruikt in de URL en de data lokaal bewaar. Daar zitten wat haken en ogen aan:

- ik kan bijv. niet meer goed uit de logs halen welk item er precies een fout geeft omdat ik enkel een GUID zie en de rest staat lokaal.
- er worden files naar disk geschreven en dat is (zeker op een Raspberry Pi) heel erg traag.

Maar probleer eens of het werkt. Het zou backwards compatible moeten zijn met de reeds bestaande favourites in zowel Kodi als Retrospect. Als er iets niet werkt, dan hoor ik het graag. 

Nogmaals:  **dit is echt een heel simple en eerste poging het kan zomaar helemaal niet werken**

**Comment by Phyxion** [comment]
Ik heb het even op de RPi geprobeerd en na paar keer rebooten bleef de lijst goed. Ik gebruik alleen Kodi's bladwijzers, die werkten allemaal nog. Qua vertraging, wanneer zou je dit moeten merken? Ik kan niet zeggen dat ik met openen / sluiten van een video enig verschil heb gemerkt.

**Comment by basrieter** [comment]
Ok, dat is goed nieuws. Er gaat wel een probleem ontstaan voor de Kodi bladwijzers:

de bestandjes die ik opsla, worden na 30 dagen verwijderd. Als je dus een Kodi bladwijzer aanmaakt, dan zal de url die je opslaat nu gaan wijzen naar data uit het bestandje. Als dat bestandje dus weg is na 30 dagen, dan werkt je bladwijzer niet meer. Weet niet of ik dat eenvoudig kan fixen. Maar ik ga kijken.

**Comment by basrieter** [comment]
Meer info vind je hier: https://github.com/retrospect-addon/plugin.video.retrospect/pull/1339

**Comment by Phyxion** [comment]
Verwijderd Kodi die zelf automatisch na 30 dagen?

**Comment by basrieter** [comment]
> Verwijderd Kodi die zelf automatisch na 30 dagen?

Nee, die verwijdert Retrospect omdat je anders heel veel storage kwijt bent aan data die je nooit meer gebruikt.

**Comment by Phyxion** [comment]
Kunnen ze voor bookmarks dan niet bewaard worden? Ik weet niet wat voor mogelijkheden Kodi zelf heeft met betrekking tot het opvragen daarvan, maar in favourites.xml staan gebookmarkte series hier met pickle (en 'zenders' zonder) erin ieder geval. Bedankt voor de extra info in ieder geval 👍

**Comment by basrieter** [comment]
Ik mag niet zomaar favourites.xml uitlezen en aangezien het bookmarken helemaal buiten de add-ons om gaat weet ik niet eens wanneer dat gebeurd.

**Comment by Phyxion** [comment]
> Ik mag niet zomaar favourites.xml uitlezen

Is daar een speciale reden voor dan? Ik zie op GitHub namelijk meerdere addons die dat bestand wel gewoon lezen (via special://profile/favourites.xml). Dit bestand wordt ook keurig direct bijgewerkt als er een bookmark wordt toegevoegd/verwijderd. Zolang je alleen leest kan er ook weinig bijzonders gebeuren lijkt mij. Alhoewel mijn kennis van Kodi ook wel zo'n beetje ophoudt bij het afspelen ervan 😊

**Comment by basrieter** [comment]
Het problem met de favorieten is opgelost door de jsonRPC te gebruiken om favourites op te vragen en zo de files niet te purgen. 

Een nieuwe versie kan je via https://github.com/retrospect-addon/plugin.video.retrospect/archive/feature-pickle-store.zip downloaden en installeren via "Install from zip"

**Comment by Phyxion** [comment]
OK, mooi 👍🏻 Ik heb het nu alleen even op mijn eigen PC getest en heb Kodi meerdere keren herstart, elke keer ging het prima en werden de afleveringen keurig onthouden (van diverse programma's).

**Comment by basrieter** [comment]
I also fixed the debug logging issue where data was missing. Could you install it again and see if it is working correctly.

**Comment by Phyxion** [comment]
Ik heb diverse programma's weer geprobeerd en ook bekeken of de vorige afleveringen nog gemarkeerd waren als gezien en dat is zo, dus volgens mij werkt het prima 🙂
