### ISSUE TITLE
Retrospect episodes freezing

### ISSUE THREAD

**Issue by Arathonk** [retrospect-addon/plugin.video.retrospect#1262]
### Describe the bug
Here is a clear and concise description of what the problem is:
Retrospect episodes freezing, having to manually stop and start episode again, happens over and over, 
Sometimes up to 20 times per 50 minute episode, also happens in live streams(NPO 1&2&3). Happens in every category. Tested in episodes from SBS6, NPO 1 and more. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Play normally

## Actual Behavior
Constantly freezing

## Possible Fix
No idea. 

### To Reproduce
Play any live stream or episode. 

### Debuglog
The **debug** retrospect.log can be found here:
https://paste.kodi.tv/exajehifax

### Screenshots 
-

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
-

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.4
- Retrospect version: 5.1.1

**Comment by Arathonk** [comment]
#1258 might be the same issue?

**Comment by basrieter** [comment]
the streams play using the InputStream Adaptive add-on.  You can  try lowering the bitrate for NPO?

**Comment by Arathonk** [comment]
It's not just NPO, how can I low it? In Inputstream settings from your addon there's min and max bandwidth, but there's no values there?

**Comment by basrieter** [comment]
You can limit it from the Retrospect add-on settings. First line:

![image](https://user-images.githubusercontent.com/1310443/69000733-aacef400-08d4-11ea-9c54-befb7af62352.png)

**Comment by Arathonk** [comment]
It was on 4000, changed it to 2500, that's for all streams right? Not only NPO? I'll test and let you know.

**Comment by basrieter** [comment]
That is for all channels indeed. That still does not work. List all channel (but really all) channels that have this issue for you.

**Comment by Arathonk** [comment]
Didn't work no, still freezes. I can't possibly try all channels..

**Comment by Arathonk** [comment]
Before yesterday, so before the last update of Retrospect/Inputstream there where no issues at all.

**Comment by basrieter** [comment]
There was an update or the InputStream Adaptive add-on that could be related. Last update did not change anything in channels at all. It just restructured some stuff internal.

**Comment by basrieter** [comment]
Buy yes, please try the RTL channel.

**Comment by Arathonk** [comment]
I just tried RTL, SBS and NPO again, and they all have this problem..

**Comment by basrieter** [comment]
So this has absolutely nothing to do with Retrospect as all of these channels have not been updated for a while. 

Enable debug logging in Kodi, play one and wait until it stops. Then upload the kodi.log to https://paste.kodi.tv/

**Comment by skycamel** [comment]
I think indeed that this is some other issue than Retrospect because I have similar problem since a few days with other addons (Yelo, VTM Go, ...)
I also don't feel it would be the Inputstream adaptive update as myself I had to stay on the modified version to be able to use VTM Go and yet I also experience the same issues.

**Comment by basrieter** [comment]
Ok, then I will close this one.
