### ISSUE TITLE
NOS.nl fail without error in UI

### ISSUE THREAD

**Issue by ltGuillaume** [retrospect-addon/plugin.video.retrospect#1263]
### Describe the bug
There are currently no clips in the NOS.nl channel that can be played. I have tested Retrospect 5.1.1 on Kodi 18.5 on Win10 and 18.4 on a Raspberry Pi 2 (LibreELEC). I have updated Widevine via the Inputstream Helper.

### To Reproduce

1. Open the channel NOS.nl
2. Choose any clip
3. Watch it fail

### Debuglog

The **debug** retrospect.log can be found here:
[retrospect.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/3882527/retrospect.txt)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi 2 (LibreELEC)
 - [x] Windows 10 x64
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.5/18.4
- Retrospect version: 5.1.1

**Comment by basrieter** [comment]
Ik zal eens kijken.

**Comment by basrieter** [comment]
Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi.

[retrospect-patch-20191123.160138.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3882586/retrospect-patch-20191123.160138.zip)

**Comment by ltGuillaume** [comment]
Wow, that was fast! Confirmed working! Thank you! 😎

**Comment by basrieter** [comment]
Great. Let me close this issue with the correct commit.
