### ISSUE TITLE
Unable to resolve dependencies on Kodi 18.4

### ISSUE THREAD

**Issue by dromer** [retrospect-addon/plugin.video.retrospect#1264]
### Describe the bug
Trying to install the plugin (5.1.1) from the kodi repositories.

```inputstream.adaptive```
Not available

```script.module.win_inet_pton```
Not available

## Expected Behavior
Resolve needed dependencies.

### To Reproduce
Install the plugin from the repo.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.4
- Retrospect version: 5.1.1

**Comment by basrieter** [comment]
This issue is related to Kodi, not Retrospect. `inputstream.adaptive` should be there and if it is missing, it is because of your platform/cpu combi. The other one is also specific to your platform.

**Comment by dromer** [comment]
So Retrospect does not run on Linux?

**Comment by basrieter** [comment]
Yes, it most certainly does. I am saying that there is something not right with your Kodi repositories. But you did not really include any logging what so ever, and did not even mention on what platform you are trying to install (OpenElec, LibreElec, Ubuntu.....), so it's hard to say. 

Post a full kodi.log on https://paste.kodi.tv/

**Comment by dromer** [comment]
Ok sorry. This is on Debian Buster using deb-multimedia repositories (where I believe this package is from).

log: https://paste.kodi.tv/otemotivoy.kodi

**Comment by basrieter** [comment]
Dit you compile it yourself?

**Comment by dromer** [comment]
No, as I said in the previous post I installed it from deb-multimedia repositories.

I know it's not the most recent version of Kodi 18, but I believe such dependencies should be able to be installed no?

**Comment by basrieter** [comment]
You might need to install the binary add-on manually (see https://kodi.tv/article/kodi-v18-binary-add-ons-repository)
