### ISSUE TITLE
Sweden: SVT channels do not work

### ISSUE THREAD

**Issue by Snaah** [retrospect-addon/plugin.video.retrospect#1266]
### Describe the bug
Here is a clear and concise description of what the problem is:

SVT channels aren't playable in Retrospect.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

SVT channels should work.

## Actual Behavior

SVT channels do not work.

### To Reproduce

1. Try starting any SVT channel. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/3935424/retrospect.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.5
- Retrospect version: 5.1.2

**Comment by basrieter** [comment]
Playable? So the listings do work? And you are trying it from inside Sweden?

**Comment by Snaah** [comment]
The listings work, but I cannot view the channels. Yes, from inside Sweden.

**Comment by basrieter** [comment]
You have to be a bit more clear. Are you referring to the live streams? Please give an example.

**Comment by Snaah** [comment]
Yes, the live streams - ".:TV-kanaler/channels:.". None works.

**Comment by basrieter** [comment]
Apparently I did not uncomment a line after the last revamp of their API. Please manually extract the files from the zip and overwrite the original files:

[retrospect-patch-20191208.204845.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3937078/retrospect-patch-20191208.204845.zip)

**Comment by Snaah** [comment]
Working! Thanks a lot.

**Comment by Eeemil** [comment]
I might add that I've not been able to list the program "Rapport" for a couple of months. I can view the most recent under "Recent" but if I search for the program under "Titles with R" and select "Rapport" I get a new menu, "2019" or "Klipp", the category "Klipp" works, but "2019" yields "Error retrieving the list of items".

(I'm using OSMC 2019-11-1, Retrospect Swedish Channels v 5.0.0.0, Retrospect 5.1.2)

**Comment by basrieter** [comment]
You need to create a new issue for that @Eeemil and include a logfile.

**Comment by basrieter** [comment]
Needs to go into the repo

**Comment by Snaah** [comment]
@Eeemil For me Rapport works just like it should (Windows 10, Kodi 18.5). Have you tried the patch above?
