### ISSUE TITLE
No TV-programs for swedish channel UR Play

### ISSUE THREAD

**Issue by hakgle47** [retrospect-addon/plugin.video.retrospect#1267]
### Describe the bug
Here is a clear and concise description of what the problem is:

When I browse to a folder with TV-shows, UR Play finds the folder but the folder does not contain any TV-programs.

Example:
Browse for ”Kalla krigets försvunna bomber” (”The lost bombs of the cold war”) in Retrospect UR Play. No TV-programs are listed. If I look directly at [urplay.se](https://urplay.se/serie/209558-kalla-krigets-forsvunna-bomber) there are two programs in that series.

Another example is the ”60-talets USA” (”The sixties”). UR Play in Retrospect finds the folder but there are no programs in the folder.

I am providing a screenshot, Kodi and Retrospect logs.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

TV-programs in the folder should be listed.

## Actual Behavior

TV-programs are not listed in their folder.

## Possible Fix

I guess that urplay.se changed their API again.

### To Reproduce

1. Browse for a TV-show folder in Retrospect Urplay, no programs will show up.

### Debuglog

The **debug** retrospect.log can be found here:

[kodi.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/3969420/kodi.log)

[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/3969422/retrospect.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

![Urplay_fel](https://user-images.githubusercontent.com/57522709/70930044-9e090180-2034-11ea-8428-025bfd0fbf96.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.5.
- Retrospect version: 5.1.2.

**Comment by basrieter** [comment]
Thanks for reporting this. Let me look into it.

**Comment by basrieter** [comment]
Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi.

[retrospect-patch-20191218.003757.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3975922/retrospect-patch-20191218.003757.zip)

**Comment by hakgle47** [comment]
I installed the file as you instructed and tested. It works without any problem as far as I can tell.

Thank you very much!

**Comment by basrieter** [comment]
Great. I will try to release a new official version somewhere this week.
