### ISSUE TITLE
More view-options

### ISSUE THREAD

**Issue by user00099** [retrospect-addon/plugin.video.retrospect#1268]
### Is your feature request related to a problem? Please describe

I'm using the Kodi-skin Estuary which have 9 view-options (List, Poster, IconWall, Shift, InfoWall, WideList, Wall, Banner, FanArt), but in the Retrospect-addon I only can see WideList, InfoWall and Wall.
### Describe the solution you'd like

If its possible and not to much work, it would be nice with some more view-options, especially FanArt-view (View 502)

**Comment by basrieter** [comment]
Please use this zip and **manually** replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi and see if this is better:

[retrospect-patch-20191227.194703.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4006034/retrospect-patch-20191227.194703.zip)

**Comment by Snaah** [comment]
Gives error and Retrospect doesn't start:

> 20191229 01:07:40 - [DEBUG   ] - envcontroller.py     - 111  - + G:\#Skräp\Kodi2\portable_data\addons\plugin.video.retrospect\resources\media\retrospect03.jpg
> 20191229 01:07:40 - [DEBUG   ] - xbmcwrapper.py       - 195  - Showing notification: Retrospect - Startar Retrospect.
> 20191229 01:07:40 - [CRITICAL] - addon.py             - 72   - Error running plugin
> 20191229 01:07:40 - [CRITICAL] - addon.py             - 72   - | Traceback (most recent call last):
> 20191229 01:07:40 - [CRITICAL] - addon.py             - 72   - |   File "G:\#Skr䰜Kodi2\portable_data\addons\plugin.video.retrospect\resources\lib\addon.py", line 62, in run_addon
> 20191229 01:07:40 - [CRITICAL] - addon.py             - 72   - |     plugin.Plugin(sys.argv[0], sys.argv[2], sys.argv[1])
> 20191229 01:07:40 - [CRITICAL] - addon.py             - 72   - |   File "G:\#Skr䰜Kodi2\portable_data\addons\plugin.video.retrospect\resources\lib\plugin.py", line 82, in __init__
> 20191229 01:07:40 - [CRITICAL] - addon.py             - 72   - |     from resources.lib.updater import Updater
> 20191229 01:07:40 - [CRITICAL] - addon.py             - 72   - + ImportError: No module named updater
> 20191229 01:07:40 - [INFO    ] - addon.py             - 73   - Retrospect :: Flushing and closing logfile.
>

**Comment by basrieter** [comment]
Crap, let me fix that.

**Comment by basrieter** [comment]
Please try this one.

[retrospect-patch-20191229.111329.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4007958/retrospect-patch-20191229.111329.zip)

**Comment by Snaah** [comment]
Working! Nice enhancement, very good suggestion @user00099 

Noticed two things:

1. SVT Play fanart looks strange:
![image](https://user-images.githubusercontent.com/1334819/71555652-48febf80-2a26-11ea-9493-d55dec8f15b2.png)
---
2. While we're at the viewing options, is it possible to make the picture+text of the _WideList_ option start at the same level as the _List_ option, i.e. higher up on the page? This would remove the wait for the scrolling of text. 

_WideList:_
![image](https://user-images.githubusercontent.com/1334819/71555573-ca098700-2a25-11ea-9d04-e57e110c58eb.png)

_WideList:_
 ![image](https://user-images.githubusercontent.com/1334819/71555534-641cff80-2a25-11ea-9c66-b8eda4278946.png)

As always, great work, @basrieter !

**Comment by basrieter** [comment]
So the Fanart of SVT is that actual image: 

https://cdn.rieter.net/resource.images.retrospect/resources/channel.se.svt/svtfanart.jpg

The other 2 suggestions are skin things, over which I have no control I think.

**Comment by user00099** [comment]
First, thanks for a great work with the Retrospect-addon.

Now also I have tested the patch with the FanArt-view and it works for me as well.
But is it possible to get the FanArt-pictures from each Play-channels website instead of the ones from the Retrospect-addon resources?
I have tested the SVT Play-channel in both Retrospect-addon and the SVT Play-addon from Kodis official repository, both with the FanArt-view, and it looks a little bit different from each other.
Here is some screenshots of both Retrospect-addon and the SVT Play-addon.

SVT Play-channel in Retrospect
![Retrospect01](https://user-images.githubusercontent.com/59258626/71558885-2b4a4e00-2a58-11ea-9a10-777fab7ad87a.png)

SVT Play-channel in SVT Play-addon
![SvtPlayAddon01](https://user-images.githubusercontent.com/59258626/71558912-6f3d5300-2a58-11ea-9852-38b8d2f822f0.png)

SVT Play-channel in Retrospect
![Retrospect02](https://user-images.githubusercontent.com/59258626/71558918-82e8b980-2a58-11ea-96f0-e015333aef3f.png)

SVT Play-channel in SVT Play-addon
![SvtPlayAddon02](https://user-images.githubusercontent.com/59258626/71558931-9562f300-2a58-11ea-8b15-ac397e92bef7.png)

So if its possible and not to much work, it would be great if its possible to get the FanArt-pictures from each Play-channels website instead.

Thanks in advance.

**Comment by user00099** [comment]
Dplay-channel in Retrospect
![Retrospect03](https://user-images.githubusercontent.com/59258626/71559008-6c8f2d80-2a59-11ea-94ca-6294e8e4dc85.png)

![Retrospect04](https://user-images.githubusercontent.com/59258626/71559014-744ed200-2a59-11ea-9202-d410ce5d012c.png)

![Retrospect05](https://user-images.githubusercontent.com/59258626/71559017-7dd83a00-2a59-11ea-9704-69904f64b523.png)

TV4 Play-channel in Retrospect
![Retrospect06](https://user-images.githubusercontent.com/59258626/71559027-99434500-2a59-11ea-8e0d-54b7a98eb5e4.png)

![Retrospect07](https://user-images.githubusercontent.com/59258626/71559030-9ea08f80-2a59-11ea-8db0-353ce39f1eb0.png)

![Retrospect08](https://user-images.githubusercontent.com/59258626/71559035-a5c79d80-2a59-11ea-91c1-57385e9fece6.png)

**Comment by basrieter** [comment]
Well, it depends on what I code as to be "fanart". I don't set fanart for all shows. Let me check that too.

**Comment by user00099** [comment]
ok, thanks

**Comment by basrieter** [comment]
So SVT I can fix, but not all the things I have listed provide all image data: 

[retrospect-patch-20191229.220651.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4008567/retrospect-patch-20191229.220651.zip)

**Comment by basrieter** [comment]
Dplay and TV4 fixed

[retrospect-patch-20191229.221631.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4008574/retrospect-patch-20191229.221631.zip)

**Comment by basrieter** [comment]
While looking at #1271 I found that allowing more views by setting the content type to "TV Shows" breaks the season/episode information in Kodi, as a TV Show does not have a specific season or episode. So the main question here is:  Why and where do you want these views? Because I will have to revert it at least for the normal listings. I can keep this change for the channel overview.

**Comment by user00099** [comment]
Ok, didnt know that - not good if it breaks the season/episode information.
Hmm... - I like the FanArt-view but if it breaks the season/episode information maybe its better to keep using either List or WideList-view.
Maybe i'll go back to List or WideList instead, so maybe its unnecessarily for you to keep laying down works on it.

**Comment by basrieter** [comment]
I asked around in the Kodi team Slack, but the view types from specific content types are determined by the skin. 

So you could ask the skin author to add more view types for the "episodes" content type.

**Comment by Snaah** [comment]
Bummer. The episode/show information is more important.
