### ISSUE TITLE
Sweden: TV4 Play - "available until/expires at"

### ISSUE THREAD

**Issue by user00099** [retrospect-addon/plugin.video.retrospect#1269]
### Is your feature request related to a problem? Please describe

Missing service: available until//expires at
### Describe the solution you'd like

If its possible and not to much work, it would be nice with "available until//expires at" of the TV-shows in TV4 Play. For example in this series "Hidden" on the TV4 Play website (https://www.tv4play.se/program/hidden) it says "Available: 30+ days".

**Comment by basrieter** [comment]
"Hidden" has an expire date of 2021-11-14T23:59:59+01:00 which makes not real sense. Is there a show that actually has an expire date less then 30 days?

**Comment by Snaah** [comment]
I looked into this again and found the labels:

`daysLeftInService:` shows the real amount of days left.
`humandaysLeftInService:` shows "30+ dagar till" if daysLeftInService is 30 or more, the real amount of days if it's less than 30.

**Comment by basrieter** [comment]
What do you mean with 'Label'? I get data from these urls: https://api.tv4play.se/play/video_assets?platform=tablet&per_page=25&is_live=false&type=episode&page=1&node_nids=hidden&start=0 and they don't show any of those. Only the actual expire date.

So the question remains: what shows actually have an expire date?

**Comment by Snaah** [comment]
I used Inspect page/Network in Chrome. Then the API doesn't have that information.

Here's a show with 23 days left: https://www.tv4play.se/program/solsidan

**Comment by user00099** [comment]
First, thanks for a great work with the Retrospect-addon.

Then some answers for your questions:
As @Snaah already said, most series have an expire date more than 30 days and says "Available: 30+ days".
But there are a few series and movies that have an expire date less than 30 days and are counting down to 0 before they are being removed from the website. Here is some examples:
Solsidan as @Snaah already said, (https://www.tv4play.se/program/solsidan)
Safe House (https://www.tv4play.se/program/safe-house)
Some movies:
A Bigger Splash (https://www.tv4play.se/program/a-bigger-splash)
Rallybrudar (https://www.tv4play.se/program/rallybrudar)

**Comment by basrieter** [comment]
Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi.

[retrospect-patch-20191229.231137.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4008634/retrospect-patch-20191229.231137.zip)
