### ISSUE TITLE
MTG channels - enhance look and feel

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1272]
### Is your feature request related to a problem? Please describe

No problem, just some small enhancements for a great product.

### Describe the solution you'd like

Some minor enhancement are requested and I will provide code for the requested changes below that I use on my own system.

- Display program name with Title - SeasonEpisode 
- Display Fanart in video_item
- Display Fanart to episode_item
- Add expire date to description
- Add "set_info_label" to show duration

[mtgchannels-CodeForChange.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/4010385/mtgchannels-CodeForChange.txt)

**Comment by basrieter** [comment]
Thanks again for these changes. I added all of them, but took a slightly different approach for the artwork:
[chn_viafree.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4011449/chn_viafree.zip)

**Comment by matsarv** [comment]
Everything works OK.

I found one thing that catch my eyes.

![Image 5](https://user-images.githubusercontent.com/46671821/71615198-492ac680-2bb0-11ea-9427-4b07bae245a7.png)

A missing hyphen and upper case in Season and Episode to lower.

My opinion is to use upper case in Season and Episode. If you decide to go all in for upper case, please change this also in MTG and SE channels as this looks better.

Have a really good Happy New Year!

**Comment by basrieter** [comment]
The missing hyphens is because that is how it is in the JSON data:

![image](https://user-images.githubusercontent.com/1310443/71626180-2dddac80-2bec-11ea-8cab-f36ffa80bfcf.png)

**Comment by Snaah** [comment]
@basrieter When this is released, you can also close #1205.

**Comment by matsarv** [comment]
OK, ready for release then.

**Comment by matsarv** [comment]
Since it's not release I will add this. Hope it's OK.
Above i mentioned the Season and Episode, missing hyphen, large S and E.

I did a small change and that fixed everything.
```
remark row 495
            # webisode = result_set.get("webisode", False)

replace row 498
from:
            if episode > 0 and not webisode:
to:
            if episode > 0:
```
I don't understand what the webiscode is used for.

Before change:
![viafreeepisode1](https://user-images.githubusercontent.com/46671821/71771644-e97d4400-2f3e-11ea-9dbe-7272ae220fa8.png)

After change:
![viafreeepisode2](https://user-images.githubusercontent.com/46671821/71771646-ee41f800-2f3e-11ea-8eed-f565c03a5cc9.png)

**Comment by Snaah** [comment]
@matsarv If you have the time you could take a look at #1231 (and possibly #1232 too). Would be great!

**Comment by basrieter** [comment]
The `webisode` is used in some cases. Don' t 

> @matsarv If you have the time you could take a look at #1231 (and possibly #1232 too). Would be great!

This request makes little sense as it involves much more than just small changes. Just be patient until they are done.

**Comment by matsarv** [comment]
@Snaah Would be nice to have genres not only for SVT. Sorry, this goes over my head and as @basrieter said "involves much more than just small changes".

**Comment by Snaah** [comment]
So the info is not available in the API?
