### ISSUE TITLE
SE SVT channels - enhance look and feel

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1273]
### Is your feature request related to a problem? Please describe

One small problem, se below.
### Describe the solution you'd like

Some enhancement are requested for change, code added.

- Change name in .: Categories :. Film
- Add fanart and description to folders in Genrer

[svtchannel-CodeForChanges.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/4013910/svtchannel-CodeForChanges.txt)

**Comment by basrieter** [comment]
The first change I could do. Same with the description. However, I am a bit lost with the fanart part:

> -------------
> Add fanart and description to folders in Genrer
> -------------
> 
> replace row 312: item.description = result_set.get('description')
> to:
>         item.description = result_set.get('longDescription')
> 
>         image_info = result_set.get("image")
>         if image_info:
>             item.thumb = self.__get_thumb(image_info, width=720)
>             item.fanart = self.__get_thumb(image_info)
>         image_info = result_set.get("image")
>         if image_info:
>             item.thumb = self.__get_thumb(image_info)

Could you explain a bit more, seems like there is some duplicate code here? Perhaps tell me where I can see the result of this change?

**Comment by matsarv** [comment]
> The first change I could do. Same with the description. However, I am a bit lost with the fanart part:
> 
> 
> Add fanart and description to folders in Genrer
> replace row 312: item.description = result_set.get('description')
> to:
> item.description = result_set.get('longDescription')
>     image_info = result_set.get("image")
>     if image_info:
>         item.thumb = self.__get_thumb(image_info, width=720)
>         item.fanart = self.__get_thumb(image_info)
>     image_info = result_set.get("image")
>     if image_info:
>         item.thumb = self.__get_thumb(image_info)
> 
> 
> Could you explain a bit more, seems like there is some duplicate code here? Perhaps tell me where I can see the result of this change?

An example:
under Genre / Action & äventyr (old code)
![svtgenrenofanart](https://user-images.githubusercontent.com/46671821/71646438-fa347c80-2ce8-11ea-854b-7340a5e82800.png)
under Genre / Action & äventyr (new code)
![svtgenrefanart](https://user-images.githubusercontent.com/46671821/71646440-08829880-2ce9-11ea-9814-212f1503a0c0.png)
Image, fanart and description added when it's a folder.

**Comment by matsarv** [comment]
There were som new items under the Category, here is the new list.
[category.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/4014589/category.txt)

**Comment by basrieter** [comment]
Thanks! I was confused by the duplicate code! Please try this:

[chn_svt.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4014591/chn_svt.zip)

**Comment by basrieter** [comment]
I also added the new categories, but that is not in the zip yet

**Comment by matsarv** [comment]
OK, the image, fanart and descrition was is there
As you see in the pictures, there is a problem with the sorting order when it first sort folders and then single program. I use to miss programs due to this, forget that programs is shown after folders.

**Comment by basrieter** [comment]
You can enable the mixing of videos/folder in the Retrospect settings:

![image](https://user-images.githubusercontent.com/1310443/71646939-e2f88d80-2cee-11ea-8eef-cd204f4af1ca.png)

**Comment by matsarv** [comment]
OK, I have totally missed that one. Good work!

**Comment by Snaah** [comment]
That option doesn't solve the "problem" though, as the A-Ö folders all begin with "Titlar med...".

**Comment by basrieter** [comment]
Disable the grouping of folders!

**Comment by Snaah** [comment]
I know. My comment was to @matsarv .

Disabling the grouping makes a very long list that is hard to handle. Would placing the shows without folder in a special folder be doable?

**Comment by matsarv** [comment]
> I know. My comment was to @matsarv .
> Disabling the grouping makes a very long list that is hard to handle. Would placing the shows without folder in a special folder be doable?

@Snaah With the mix it's OK, no special folder is neded, only that the program list ends up in a Program A-Ö folder eventually.

**Comment by matsarv** [comment]
Found another missing set_date for enhancement:

- Add valid from date to episodes.
- Remove sub_heading for episodes.

When using sub_heading the episode name will be changed next two days after relese, so it was marked unwatched. With this change there will be release date and duration for the episode.

[svtchannelsetdate-CodeForChanges.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/4016517/svtchannelsetdate-CodeForChanges.txt)

**Comment by basrieter** [comment]
I added the date, but not the subheading. I really can't help it that they change the subheading. But leaving it out can cause episodes to be indistinguishable from each other. Where is this causing you issues?

**Comment by matsarv** [comment]
![sub_heading](https://user-images.githubusercontent.com/46671821/71684164-fd854200-2d94-11ea-9a68-de1a85309060.png)
28. will have 1 jan 2020 tomorrow
29. will have Igår 16:16 tomorrow
29. will have 2 jan 2020 day after tomorrow

This may be possible:
[get_program.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/4016910/get_program.txt)
Just a thought from my side

**Comment by basrieter** [comment]
You need to gell me how to get there, so I can check myself.

**Comment by basrieter** [comment]
And I need to see more than just this example. If it is not generic, it is a no-go. I don't like doing these specific changes. If it is in the API that the show has a title and a subtitle, then that is how it is. Interpreting "positionInSeason" might work for this specific items, but might fail for many others.

**Comment by matsarv** [comment]
In program list, goto: 
/ Backstage / Säsong 2 / 
/ Belinder auktioner /
/ Min fantastiska vännina /
Check today and tomorrow.
Maybe it's to risky to add.....

**Comment by basrieter** [comment]
I removed the SubHeading (as most of the info is available now anyways) and I try to parse the season info and set it in the appropriate Kodi InfoLabels:

[chn_svt.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4017557/chn_svt.zip)

**Comment by matsarv** [comment]
Not any good.
All the "extra_items" is not working anymore.
(PS. No needed to add "sub_heading" to "longDescription" as you say above info is available)

**Comment by basrieter** [comment]
Please be more specific. What folders don't work anymore?

**Comment by basrieter** [comment]
Right, found it. However, this is also caused by the change:
![image](https://user-images.githubusercontent.com/1310443/71723993-ef83ff80-2e2e-11ea-9d96-e79eb7302bc2.png)

**Comment by basrieter** [comment]
So if I remove the subheading this happens: 

![image](https://user-images.githubusercontent.com/1310443/71724221-c9ab2a80-2e2f-11ea-9beb-ca02c3dfc136.png)

Instead of: 

![image](https://user-images.githubusercontent.com/1310443/71724207-c021c280-2e2f-11ea-83ed-9f6ae140ba9f.png)

As you can see, some of the items actually loose information.

**Comment by basrieter** [comment]
Ok, please try this:

[chn_svt.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4019245/chn_svt.zip)

I basically ignore subheadings if:

- they end with " min" or " tim"
- contain "Ikvall"
- contain "Idag"

Except for these special folders as they need this data to distinguish or give more information: 

- Last Chance
- Recent
- Most Viewed
- Search

**Comment by matsarv** [comment]
It's hard to know all the impact. Looks promising.
Everything seems to work OK after plenty of testing.

I did find some small adding during testing that could be added:

- Fanart in Category
- Filter out Igår
- Fix item.name if a Season

[svtepisode-CodeForChanges.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/4020131/svtepisode-CodeForChanges.txt)

**Comment by Snaah** [comment]
@matsarv Ok. For me that list becomes too hard to overlook. Instead I mostly use the search function. Great work you both are doing!

**Comment by basrieter** [comment]
Thanks @matsarv. Do you have some examples for the '_Fix item.name if a Season_'?

**Comment by matsarv** [comment]
Here is two examples:

Before:

Andra åket
![aa1](https://user-images.githubusercontent.com/46671821/71770383-2ab82880-2f2c-11ea-8f60-8a88d943be18.png)
Shetland
![sh1](https://user-images.githubusercontent.com/46671821/71770384-2d1a8280-2f2c-11ea-875c-a60784622cbc.png)

After:

Andra åket
![aa2](https://user-images.githubusercontent.com/46671821/71770386-3146a000-2f2c-11ea-806b-8751abd1edea.png)
Shetland
![sh2](https://user-images.githubusercontent.com/46671821/71770387-33106380-2f2c-11ea-9322-7c175fd33760.png)

The sorting gets correct and as for Shetland, i has no Season (only one season=single), but now ju see it from Season 5.

It would be nice to have the program name also, as in the other channels.

**Comment by basrieter** [comment]
Program name is difficult as it can be multiple levels up (with seasons and so). But here are the other changes:

[chn_svt.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4022375/chn_svt.zip)

**Comment by matsarv** [comment]
Don't create .pyo
Errorlog: [retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4022410/retrospect.log)

**Comment by matsarv** [comment]
I did some testing and everything works OK

Is it possible to get the program title?

**Comment by matsarv** [comment]
Sorry, missed your comment on Program name above

**Comment by matsarv** [comment]
Sorry, I did a code compare and found one thing you did not add from my test code.
When session info, I used the "nameRaw" instead. The episode number is allready there.

```
add after row 540: item.set_season_info(episode_info[1], episode_info[4])
                item.name = result_set.get("nameRaw")
```
Andra åket

Before:
![andraaket](https://user-images.githubusercontent.com/46671821/71772627-1edd5e00-2f4e-11ea-93f4-7c1857d8d260.png)

After:
![andraaket2](https://user-images.githubusercontent.com/46671821/71772654-de321480-2f4e-11ea-8256-9fab49e48a76.png)

Sorry, but this must be the last for this time

**Comment by basrieter** [comment]
Nope, I can't use the "_nameRaw_" as it is empty very often. But please tell me where this is, so I can check and see what is going on?

**Comment by matsarv** [comment]
If you meen the code:

```
after row 540: item.set_season_info(episode_info[1], episode_info[4])
add:
                item.name = result_set.get("nameRaw")
```

If you mean the programs:

Andra åket / Season 2
Annedroider
Backstage
Bamse
Banerang
Belinders auktioner
Branden

….and is goes on.

One more, we added check for "tim" and "min" and now I just seen that program "Bon" even had "sek" as last word.

```
after row 436: or "Igår" in sub_heading
add:
                    or sub_heading.endswith(" sek")
```

**Comment by basrieter** [comment]
> If you mean the programs:
> 
> Andra åket / Season 2
> Annedroider
> Backstage
> Bamse
> Banerang
> Belinders auktioner
> Branden
> 
So that is what I meant. But take Trex: it has an empty `nameRaw` and so this is the result:

![image](https://user-images.githubusercontent.com/1310443/71773149-e6db1880-2f57-11ea-944b-dc2b0e836406.png)

But I was able to fix that too:

[chn_svt.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4022747/chn_svt.zip)

But to be honest, further than this I don't what to go. If we get more specific we might end up hard coding stuff for specific shows.

**Comment by matsarv** [comment]
I agree with you. I'll check the new file tomorrow.

**Comment by matsarv** [comment]
It's looking very good now. Everything is OK.

**Comment by basrieter** [comment]
https://github.com/xbmc/repo-plugins/pull/2671

**Comment by matsarv** [comment]
Thanks for the info. Did a refresh on the plugin page, and it got installed.
