### ISSUE TITLE
NRK shows no content in certain folders

### ISSUE THREAD

**Issue by rytmisk** [retrospect-addon/plugin.video.retrospect#1274]
### Describe the bug
Here is a clear and concise description of what the problem is:
Some folders in the NRK plugin shows no content such as "popular". Or the one show I was trying to watch now "Mesternes mester" (under "Categories/Underholdning/M/Mesternes mester/Sesong 11
I think NRK might have changed something in their geolocation also because in the other NRK plugin these folders show up, but does not play - while the direct streams work (I'm behind a Norwegian VPN)
Thanks again for all your work!! 
All the best!
Ketil

**Comment by basrieter** [comment]
Could you please post a debug retrospect.log. You can use the built-in functionality from Retrospect to do that. Just enable debug logging in Retrospect, reproduce the issue and upload the log. Post the link here.

**Comment by rytmisk** [comment]
[Here](https://paste.kodi.tv/yujififozo) is the log for the no content in "popular"

**Comment by rytmisk** [comment]
I changed some things in the geo location settings so now the content of the "mesternes mester" folder shows. But it will not play on the libreelec build even if it plays on my ubuntu computer with the same VPN. Strange! 
Log for this [here](https://paste.kodi.tv/imumuqiqos)

**Comment by basrieter** [comment]
What is your LibreElec and Kodi version?  I guess the decryption on your LibreElec is not working.

**Comment by rytmisk** [comment]
LibreElec 9.0.2 and Kodi 18.2 should be the greatest newest and stablest :-)
Any tips?
Ketil

**Comment by basrieter** [comment]
Could you post a kodi.log?

**Comment by rytmisk** [comment]
Sure
[Here](http://ix.io/27QM)
Thanks so much!!
Ketil

**Comment by basrieter** [comment]
That zip does not contain any playback of Retrospect!

But there is something wrong with your DNS/Name resolving. The whole log contains these errors:

`CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)`

**Comment by rytmisk** [comment]
Hm. I guess it is time for a full reset of the box anyway. I'll reinstall it and if the issue remains I will get back to you. Thank so much you for your efforts!!! You're a hero!
Ketil

**Comment by basrieter** [comment]
Closing it for now then.

**Comment by rytmisk** [comment]
Hi again. 
Just for your info: Now I have reinstalled and it works as expected - except that the folder "popular" on the front page is still empty. 
Sorry for troubling and thank you for all the help!!
Ketil

**Comment by basrieter** [comment]
Yes, the "popular" items seems to have been removed from the site. Did they put it somewhere else?

**Comment by rytmisk** [comment]
It is gone on the webpage and in the app. The heading "Våre mest sette serier" means our most seen series. And the heading "Populære dokumentarserier" means "our most popular documentaries"
However the Kodi addon named NRK in the official Kodi repo still has a working "Mest sett" which means "most seen". I do not know where they draw that from.
All the best
Ketil

**Comment by basrieter** [comment]
Found the issue: the url changed.

**Comment by basrieter** [comment]
Please use this zip and manually replace the Retrospect files with the newer versions inside the zip (no install from zip). Finally restart Kodi.

[retrospect-patch-20200207.235240.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4173219/retrospect-patch-20200207.235240.zip)

**Comment by rytmisk** [comment]
Thanks!
Hoewever it did not work - probably I did something wrong. I updated Retro and exited. Extracted and overwrote the content into home/.kodi/addons/net.rieterxot.channels.no and tried to open the "popular" and still got a "Error retrieving the list of items".
Log is [here](https://paste.kodi.tv/ipupamugax)
Thanks again for all your work!!
Ketil

**Comment by basrieter** [comment]
That is the wrong path. You need to be in plugin.video.retrospect/channels

**Comment by rytmisk** [comment]
I am so clueless! Thank you for your patience! Now it works perfectly!!!
Ketil
