### ISSUE TITLE
vrt nu doesn't work anymore

### ISSUE THREAD

**Issue by peno64** [retrospect-addon/plugin.video.retrospect#1276]
### Describe the bug
Here is a clear and concise description of what the problem is:

When going into vrt nu, I only see Categorieeb, Cannes and Live Streams and when I go into Categorien it is all empty. So nothing can be viewed anymore.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Al least I should see categories and in the past there was also an ABC index I think but even that it totally gone.

### To Reproduce

1. go to vrt nu
2. go into categorien. It's empty

### Debuglog

The **debug** retrospect.log can be found here:

https://paste.kodi.tv/aquqabebej.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi 3
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.5
- Retrospect version: 5.1.4

**Comment by peno64** [comment]
btw, the addon vrt.nu does still work so it is not a problem on the site

**Comment by peno64** [comment]
This is the retrospect.log file: https://paste.kodi.tv/pixujuwixe.kodi

**Comment by basrieter** [comment]
This is not a DEBUG retrospect log.

**Comment by basrieter** [comment]
Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi.

[retrospect-patch-20200114.232441.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4061884/retrospect-patch-20200114.232441.zip)

**Comment by peno64** [comment]
Yes that solves the problem. Both categories and the ABC index are back again and working.

Thank you

**Comment by basrieter** [comment]
Great. I will push an update somewhere this week.

**Comment by jellegrammens** [comment]
Thanks for the quick fix :D
