### ISSUE TITLE
SE SBS channels - enhance look and feel 

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1277]
### Is your feature request related to a problem? Please describe

No problem, just some small enhancements for a great product.

### Describe the solution you'd like

Some minor enhancement are requested and I will provide test-code for the requested changes below that I use on my own system.

- Add fanart to item in Search and Latest

[testcode2-chn_sbs.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/4069911/testcode2-chn_sbs.txt)

**Comment by basrieter** [comment]
I took a slightly different approach as the initial fanart/thumb setting was done somewhere else, but was over overwritten in the `create_video_item` method. See if this works for you?

[retrospect-patch-20200118.140757.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4080714/retrospect-patch-20200118.140757.zip)

**Comment by matsarv** [comment]
If you add it in the "def __get_video_streams...." then you will add the thumb image as fanart to all item streams. 

Before any fix, in the root folder of Kanal 5, all the program will have a fanart and that is used on the items streams in the folder as fanart. That's OK. But if you search for something, the single item stream in the search result will have the "Kanal 5" channel fanart and the program folders will have correct fanart on the item stream in the folder.

Example:

I search for SOS Gute and the result is (with my test code):

![Image1](https://user-images.githubusercontent.com/46671821/72665614-77aafd00-3a0a-11ea-8a32-03b1d9381933.png)

Step into SOS Gute and the correct fanart on item streams will be used (with my test code):

![Image2](https://user-images.githubusercontent.com/46671821/72665636-b3de5d80-3a0a-11ea-89c5-6ee7d642f902.png)

The single item stream in the search result will have the item thumb as fanart (with my test code):

![Image3](https://user-images.githubusercontent.com/46671821/72665837-84c8eb80-3a0c-11ea-85da-92c7b16e6969.png)


Added your patched file:

The single item stream in the search result will have the item thumb as fanart as above picture but all the item streams in program folders will also have the item thumb as fanart and not the program folder fanart. Below is the program folder of SOS Gute both from main program list and in the search result.

![Image4](https://user-images.githubusercontent.com/46671821/72665897-2e0fe180-3a0d-11ea-8058-5b633464166d.png)

I hope you get it.

**Comment by basrieter** [comment]
I see. Let me have a look at it. But that won't be today.

**Comment by basrieter** [comment]
Please try this one.

[retrospect-patch-20200118.230924.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4081861/retrospect-patch-20200118.230924.zip)

**Comment by matsarv** [comment]
Now it's working OK. Ready for release.

**Comment by basrieter** [comment]
Great!
