### ISSUE TITLE
Nick channels has stopped streaming

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1279]
### Describe the bug
Here is a clear and concise description of what the problem is:

Both Swedish Nick Jr. and Nickelodeon will not start playing the stream.
I enabled the Netherland channels and they didn't work either.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Stream the selected program.
### To Reproduce

1. Start Nickelodeon or Nick Jr.
2. Select program folder
3. Start program

### Debuglog

The **debug** retrospect.log can be found here:

Here is the part where the stream try to start:
```
20200120 09:26:00 - [INFO    ] - mediaitem.py         - 427  - Selected Stream:  MediaStream: rtmp://cp5290......mp4 [bitrate=3043]
20200120 09:26:00 - [DEBUG   ] - plugin.py            - 498  - Continuing playback in plugin.py
20200120 09:26:00 - [DEBUG   ] - plugin.py            - 929  - Current playlist size and position: 1 @ 0
20200120 09:26:00 - [DEBUG   ] - plugin.py            - 938  - Adding Main PlayList item
20200120 09:26:00 - [DEBUG   ] - xbmcwrapper.py       - 385  - Waiting for Player status '1'
20200120 09:26:00 - [DEBUG   ] - xbmcwrapper.py       - 390  - player.isPlaying is '0', preferred value is 1 and stream: 'rtmp://cp5290......mp4'
20200120 09:26:00 - [DEBUG   ] - xbmcwrapper.py       - 411  - player.isPlaying is 0, waiting a cycle
20200120 09:26:01 - [DEBUG   ] - xbmcwrapper.py       - 411  - player.isPlaying is 0, waiting a cycle
20200120 09:26:02 - [DEBUG   ] - xbmcwrapper.py       - 411  - player.isPlaying is 0, waiting a cycle
20200120 09:26:03 - [DEBUG   ] - xbmcwrapper.py       - 411  - player.isPlaying is 0, waiting a cycle
20200120 09:26:04 - [DEBUG   ] - xbmcwrapper.py       - 411  - player.isPlaying is 0, waiting a cycle
20200120 09:26:05 - [DEBUG   ] - xbmcwrapper.py       - 411  - player.isPlaying is 0, waiting a cycle
20200120 09:26:06 - [DEBUG   ] - xbmcwrapper.py       - 411  - player.isPlaying is 0, waiting a cycle
20200120 09:26:07 - [DEBUG   ] - xbmcwrapper.py       - 411  - player.isPlaying is 0, waiting a cycle
20200120 09:26:08 - [DEBUG   ] - xbmcwrapper.py       - 411  - player.isPlaying is 0, waiting a cycle
20200120 09:26:09 - [DEBUG   ] - xbmcwrapper.py       - 411  - player.isPlaying is 0, waiting a cycle
20200120 09:26:10 - [DEBUG   ] - kodisettings.py      - 70   - Removed Kodi settings-store
20200120 09:26:10 - [DEBUG   ] - localsettings.py     - 84   - Removed Local settings-store
20200120 09:26:10 - [INFO    ] - addon.py             - 67   - Retrospect :: Flushing and closing logfile.
```
You can get a full log from the Netherland channels, they didn't work either.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ X] Raspberry-Pi
 - [ X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.5
- Retrospect version: 5.1.4

**Comment by basrieter** [comment]
Please attach the full debug retrospect.log, don't copy paste parts.

**Comment by matsarv** [comment]
Sorry, here it comes
[retrospect.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4087521/retrospect.zip)

**Comment by basrieter** [comment]
Try this please:

[chn_nickjr.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4087623/chn_nickjr.zip)

**Comment by matsarv** [comment]
Now it's working OK. Ready for release.

**Comment by basrieter** [comment]
This fixes Nickelodeon

[chn_nickelodeon.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4087726/chn_nickelodeon.zip)

**Comment by matsarv** [comment]
This last file is for Netherlands and Norway. 
They don't work for me but that could perhaps be a regional thing.

[retrospect-no.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4087770/retrospect-no.zip)
[retrospect-nl.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4087772/retrospect-nl.zip)

**Comment by basrieter** [comment]
It's regional.

**Comment by matsarv** [comment]
OK. Great work.
