### ISSUE TITLE
SE TV4 channels - enhance look and feel

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1280]
### Is your feature request related to a problem? Please describe

No problem, just some small enhancements for a great product.

### Describe the solution you'd like

Some minor enhancement are requested and I will provide test-code for the requested changes below that I use on my own system.

- Add missing thumb and fanart in folders 
- Add start time to Live Broadcast item name

[testcode-chn_tv4se.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/4087648/testcode-chn_tv4se.txt)

### Additional context

Before:
![chn_tv4se_before](https://user-images.githubusercontent.com/46671821/72754089-2dbb4600-3bc7-11ea-8477-748ea8620296.jpg)
After:
![chn_tv4se_after](https://user-images.githubusercontent.com/46671821/72754093-31e76380-3bc7-11ea-95ce-d9e6085da89a.jpg)

**Comment by basrieter** [comment]
I don't like `item.fanart = result_set.get("program_image")` as it just replaces the fanart with the thumb of the video. Those are two different things.

**Comment by basrieter** [comment]
So this contains all changes except the one I mentioned before.

[retrospect-patch-20200120.222552.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4087907/retrospect-patch-20200120.222552.zip)

**Comment by matsarv** [comment]
All program items that are not in a program folder will not have any fanart except the default TV Logo. See the picture "Before" above. My guess was that there is no self.parentItem.fanart for the single items so I used the program_image as fanart to get rid of the TV logo to get a better look.
I prefer the thumb before the TV logo, but you decide.

The patch file it's working OK. Ready for release.

**Comment by basrieter** [comment]
Ok, I understand that, but that change did that for all items. But I did a small extra check, so it should work now:

[retrospect-patch-20200120.225451.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4088044/retrospect-patch-20200120.225451.zip)

**Comment by matsarv** [comment]
It look good but there is one place that it miss to add the thumb.
If you search for something no thumb is shown on the first page but if I go to second page there the single item have the thumb as fanart.

**Comment by matsarv** [comment]
Just for test, I did a remark on your added code on row 537-541
And the added on row 536: item.fanart = result_set.get("program_image")

Now the single item har the correct fanart from the parent folder.
It's also correct fanart under Categories and TV Shows folders and items.

Now is the thumb not used as fanart nowhere.

![Image1](https://user-images.githubusercontent.com/46671821/72762515-281e2a00-3be0-11ea-8b19-fa1526d64f10.png)

**Comment by basrieter** [comment]
I see now. Try this version then :) 

[retrospect-patch-20200121.000250.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4088335/retrospect-patch-20200121.000250.zip)

**Comment by matsarv** [comment]
Now it's working OK. Ready for release.
