### ISSUE TITLE
vrt nu doesn't work anymore (again)

### ISSUE THREAD

**Issue by peno64** [retrospect-addon/plugin.video.retrospect#1281]
### Describe the bug
Here is a clear and concise description of what the problem is:
When going into vrt nu, I only see Categorieen, Channels and Live Streams and when I go into Categorien. No abc index. When I go into Categorien, Niews en actua, , Het journaal, there I only have a folder Seizoen 2019 and the latest journal broadcasted while there should be alot from today and previous days. When I go into Seizoen 2019, it is completely empty

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
There should be more journals and in the past there was also an ABC index I think but even that it totally gone.

### To Reproduce

1.  Go to vrt nu
2. There is no ABC index
3. Go into Categorieen
4. Go into Nieuws en actua
5. Go into Het journaal

### Debuglog

The **debug** retrospect.log can be found here:

https://paste.kodi.tv/olodadowih.kodi

The kodi log can be found here:

https://paste.kodi.tv/agaqidomuy.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

A simular problem was there also last week and you solved it then with an updated chn_vrtnu.py
Before I installed the new retrospect version today, I tested it with this version and it also didn't work anymore. Then I installed the latest retrospect from today or yesterday and the problem is still there. So vrt.nu must have changed again something on their site.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi 4
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.5
- Retrospect version: 5.1.5

**Comment by peno64** [comment]
Oh I forgot to mention again that the addon vrt.nu does still give all the journals so it is not an issue on the vrt website

**Comment by basrieter** [comment]
Yes, they changed again........Try this:

[retrospect-patch-20200123.001616.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4100518/retrospect-patch-20200123.001616.zip)

**Comment by peno64** [comment]
Well, the ABC index is again there with  this update, but in "Het journaal" I still miss all the journals except the last one on air.

**Comment by basrieter** [comment]
I see. Try this:

[retrospect-patch-20200123.202941.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4105049/retrospect-patch-20200123.202941.zip)

**Comment by peno64** [comment]
Yes, works fine now.

Thank you

**Comment by peno64** [comment]
New release update is working great. Thank you

**Comment by basrieter** [comment]
NP. Hope they don't keep changing them.
