### ISSUE TITLE
Install widevine fails because menu_install_widevine.py is in the wrong location

### ISSUE THREAD

**Issue by SpectralDuck** [retrospect-addon/plugin.video.retrospect#1282]
Trying to install widevine through the menus fails without any message
* Go to addons > retrospect > add-on settings > General
* Click Install Widevine using 'InputStream Helper'  add-on
  * Nothing happens

The logs contain the following message:
> ERROR: CScriptInvocationManager::ExecuteAsync - Not executing non-existing script special://home/addons/plugin.video.retrospect/resources/menus/menu_install_widevine.py

There is a file named _menu_install_widevine.py_ at _special://home/addons/plugin.video.retrospect/menu_install_widevine.py_
Creating the folder _menus_ and copying _menu_install_widevine.py_ there fixes the issue.

I assume the script should be moved, or the path called from the menu should be changed.

Windows 10
Kodi 18.5 Git:20191116-37f51f6e63
Retrospect 5.1.6

**Comment by basrieter** [comment]
There is no need to do this manually anymore. It will be done automatically whenever it is needed. I will see what is wrong here.

**Comment by SpectralDuck** [comment]
Wow, great turn around time on the fix!

**Comment by basrieter** [comment]
If you want, you can download the `master` branch as zip and install from zip to get the fix.
