### ISSUE TITLE
SVTPlay.se - Not all programs have subtitles

### ISSUE THREAD

**Issue by Sopor** [retrospect-addon/plugin.video.retrospect#1283]
### Describe the bug
Here is a clear and concise description of what the problem is:

It seems that SVT has change the subtitles from `websrt` to `webvtt` on all new programs.
## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It should show subtitles because they work in the web browser.

## Actual Behavior

No subtitles.

### To Reproduce

1. Watch `Uti bôgda`.
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
https://pastebin.com/4KbVfrPp

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.5
- Retrospect version: 5.1.6

**Comment by basrieter** [comment]
Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi.

[retrospect-patch-20200210.235507.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4183439/retrospect-patch-20200210.235507.zip)

**Comment by Sopor** [comment]
Working.
