### ISSUE TITLE
SVTPlay.se - Vargblod has no items

### ISSUE THREAD

**Issue by Sopor** [retrospect-addon/plugin.video.retrospect#1284]
### Describe the bug
Here is a clear and concise description of what the problem is:

When trying to open Vargblod/Säsong 1 or 2 it will only show `No episodes found for the selected item`

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It should show the episodes

## Actual Behavior

`No episodes found for the selected item`

### To Reproduce

1. https://www.svtplay.se/vargblod
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
https://pastebin.com/h4TEzTuf

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.5
- Retrospect version: 5.1.6

**Comment by basrieter** [comment]
Please use the chn_svt from this zip and see if the issue is resolved (subs still need work, see #1283)

[retrospect-patch-20200205.110349.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4158746/retrospect-patch-20200205.110349.zip)

**Comment by Sopor** [comment]
Yes, this seems to work.
