### ISSUE TITLE
MTG Viafree channel - enhance look and feel

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1285]
### Is your feature request related to a problem? Please describe

No problem, just some small enhancements for a great product.

### Describe the solution you'd like

A minor enhancement are requested and I will provide test-code for the requested changes below that I use on my own system.

### Describe alternatives you've considered

- Add missing fanart on page menu item

```
add after 442:	item.type = "page"

        item.thumb = self.parentItem.thumb
        item.fanart = self.parentItem.fanart
```

### Additional context

Before:
![chn_viafree_before](https://user-images.githubusercontent.com/46671821/74046034-16a19400-49ce-11ea-9eb7-ed9cd7648be0.jpg)

After:
![chn_viafree_after](https://user-images.githubusercontent.com/46671821/74046054-1d300b80-49ce-11ea-9ce0-1aaf2f569593.jpg)

**Comment by basrieter** [comment]
Thanks (again). Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi.

[retrospect-patch-20200207.214318.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4172875/retrospect-patch-20200207.214318.zip)

Let me know the result.

**Comment by matsarv** [comment]
It's working OK. Ready for release.
