### ISSUE TITLE
SE UR Play channel - enhance look and feel

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1286]
### Is your feature request related to a problem? Please describe

No problem, just some small enhancements for a great product.

### Describe the solution you'd like

Some minor enhancement are requested and I will provide test-code for the requested changes below that I use on my own system.

- Add expire date to description where exist
- Add episode before title where exist (Kategorier / Dokumentär / Historiska val)

[testcode-chn_urplay.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/4172096/testcode-chn_urplay.txt)

### Additional context

Episode before:
![chn_urplay-episode-before](https://user-images.githubusercontent.com/46671821/74049666-e7425580-49d4-11ea-997b-0b4e87953565.png)

Episode after:
![chn_urplay-episode-after](https://user-images.githubusercontent.com/46671821/74049684-f0cbbd80-49d4-11ea-8ccc-d4b073d06e70.png)

**Comment by basrieter** [comment]
Is it me, or did UR Play just completely break now?

**Comment by matsarv** [comment]
It seems to be problem with browsing folders. 
If you do a search for "Amerikas urfolk" you get one folder (not working) and the two stream (working) and they should appear in the folder.
![Image 1](https://user-images.githubusercontent.com/46671821/74192112-2979ca00-4c55-11ea-8abd-8ceb13564ab1.png)

**Comment by basrieter** [comment]
Ok, but browsing does not work at all. Seems like a much bigger issue!

**Comment by matsarv** [comment]
You are right. I get Plugin::Error Processing FolderList in the log.
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4183185/retrospect.log)

**Comment by basrieter** [comment]
Please try this. UR Play should work again. I think I also included your suggestions.

[plugin.video.retrospect-5.1.6.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4194877/plugin.video.retrospect-5.1.6.zip)

**Comment by matsarv** [comment]
Greate work, now the browsing works again.

EndTime seems to have the startTime (should be 2022-06-30 below)

Duration is not correct, remove * 60 (should be 22:12 below)
row 329: item.set_info_label("duration", int(duration) * 60)
to: item.set_info_label("duration", int(duration))

![Image 1](https://user-images.githubusercontent.com/46671821/74378871-00893e80-4de7-11ea-84c9-92dad8de0bbb.png)


If the fanart is missing for a single stream, I would like to see the item.thumb as fanart.
It looks better then to have the channel logo as fanart, please.
![Image 2](https://user-images.githubusercontent.com/46671821/74379371-fb78bf00-4de7-11ea-96a3-9d56913e3fc2.png)

**Comment by basrieter** [comment]
> EndTime seems to have the startTime (should be 2022-06-30 below)
Well spot!

> Duration is not correct, remove * 60 (should be 22:12 below)
> row 329: item.set_info_label("duration", int(duration) * 60)
> to: item.set_info_label("duration", int(duration))
Check! Again, well spotted.

> If the fanart is missing for a single stream, I would like to see the item.thumb as fanart.
> It looks better then to have the channel logo as fanart, please.
How did you navigate here? So I can see where I need to fix it.

**Comment by matsarv** [comment]
Navigate: Kategorier (Categories) / Dokumentär / Historiska val

EndTime is fixed by changing:

row 345:                     start_date, date_format="%Y-%m-%dT%H:%M:%SZ", time_zone="UTC")
to:                     end_date, date_format="%Y-%m-%dT%H:%M:%SZ", time_zone="UTC")

**Comment by basrieter** [comment]
Ok, thanks. Will push a new version to Kodi.
