### ISSUE TITLE
SE Öppet arkiv channel - enhance look and feel

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1287]
### Is your feature request related to a problem? Please describe

No problem, just some small enhancements for a great product.

### Describe alternatives you've considered

Some minor enhancement are requested and I will provide test-code for the requested changes below that I use on my own system.

Below need new parsing data.

** 1. Add thumb and fanart to Genre folders (regex)**
---
1-level - image on page as thumb and fanart (https://www.oppetarkiv.se/genrer)
![1-level](https://user-images.githubusercontent.com/46671821/74050657-cbd84a00-49d6-11ea-9cb4-5186dead50f6.png)

2-level - image on page as thumb and fanart is parentItem.fanart (https://www.oppetarkiv.se/etikett/genre/Barn-1/?sort=alfabetisk)
![2-level](https://user-images.githubusercontent.com/46671821/74050671-d09cfe00-49d6-11ea-8c79-5809cc34c96e.png)

3-level - thumb (working today) and fanart is parentItem.fanart (https://www.oppetarkiv.se/video/8243043/agaton-sax)
![3-level](https://user-images.githubusercontent.com/46671821/74050681-d4c91b80-49d6-11ea-8525-99624a93bd3f.png)

** 2. Add duration (regex)**
---
![oppetarkiv-set_duration](https://user-images.githubusercontent.com/46671821/74050824-0f32b880-49d7-11ea-8ddf-d61734754952.png)

**3. Add thumb as fanart to Program list item (stream)** 
---
if above 3-level works check if parentItem.fanart exist, if not use item.thumb
(like you did in #1280)

Below just add thumb as fanart to both Program and Genre (just my code today)
```
add after ~238:  item.thumb = thumb_url
        item.fanart = item.thumb
```

I hope above is clear enough to understand.

**Comment by basrieter** [comment]
So, 1 and 2 are a no go, all that information comes from this page: https://www.oppetarkiv.se/kategori/titel. I just filter the items that belong to a genre. The thing is, that both the genres (in the filter) and the programs on the page don't have images. So I can'f add them. 

And 3 would basically set all fanart to the corresponding video item thumbs. If any fanart should be set, it should be the one from the parent item, but that one does not have any.

**Comment by matsarv** [comment]
Above 1 and 2 is all in Genre on the web.

![genre](https://user-images.githubusercontent.com/46671821/74195160-efabc200-4c5a-11ea-9025-28f88de49fdf.png)


For Genre (**1), the first level is,
on the Öppet arkiv site https://www.oppetarkiv.se/genrer

![ur-genre](https://user-images.githubusercontent.com/46671821/74193861-701cf380-4c58-11ea-97b0-463bbbb034ef.png)

and in Retropect, name and url is parsed so I guess that the image is also possible to parse or not?

![kodi-genre](https://user-images.githubusercontent.com/46671821/74193902-81fe9680-4c58-11ea-87cf-f20fe9b3d1ff.png)

The same goes for the next level,
on Öppet arkiv https://www.oppetarkiv.se/etikett/genre/Barn-1/?sort=alfabetisk

![ur-barn](https://user-images.githubusercontent.com/46671821/74195519-ac9e1e80-4c5b-11ea-96d6-b9cf5d7dc55a.png)

In Retrospect:
![kodi-barn](https://user-images.githubusercontent.com/46671821/74195537-b58ef000-4c5b-11ea-9086-af68729a00b2.png)


Maybe I see it the wrong way and it will not be possible.

I know that the program list displayed when open Öppet arkiv comes from https://www.oppetarkiv.se/kategori/titel and the item (stream) don't have any fanart so I guess the thumb is better that the TV logo.

**Comment by basrieter** [comment]
You are seeing it the wrong way indeed: I don't use those URL's at all. Only the main one and filter that one: 

![image](https://user-images.githubusercontent.com/1310443/74197594-115b7800-4c60-11ea-8e24-7500d3de7768.png)

**Comment by matsarv** [comment]
I see, if you go this way for Genre there are no thumb and fanart for the folders 

I think you should have gone by Genre on homepage for Genre but that is a bigger change now.
You can drop this request and close it.

**Comment by basrieter** [comment]
Perhaps, but the more different pages I use, the more code I need and the larger the risk is that stuff breaks.
