### ISSUE TITLE
VIDEOS AMT  - enhance look and feel

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1288]
### Is your feature request related to a problem? Please describe

No problem, just some small enhancements for a great product.

### Describe the solution you'd like

Some minor enhancement are requested and I will provide test-code for the requested changes below that I use on my own system.

- Add Studio, Genre, Directors and Actors to description
- Add duration (runtime)

[testcode-chn_amt.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/4172901/testcode-chn_amt.txt)

### Additional context

![folders](https://user-images.githubusercontent.com/46671821/74065031-42d00b80-49f4-11ea-8f06-a5d06d63c9b7.png)

**Comment by basrieter** [comment]
Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi.

[retrospect-patch-20200211.201046.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4187757/retrospect-patch-20200211.201046.zip)

**Comment by matsarv** [comment]
Only the info label for "genre" is displayed.

![amt1](https://user-images.githubusercontent.com/46671821/74270900-445b4580-4d0c-11ea-9ef2-c7a19cecca18.png)

**Comment by basrieter** [comment]
If you go into the details of the folder it will show the others to:

![image](https://user-images.githubusercontent.com/1310443/74271603-77520900-4d0d-11ea-8caa-e2f8ee1ab9ac.png)

**Comment by matsarv** [comment]
Hmmm, it seems to depend on which skin is used. I use the default skin Estuary and I can't find any detail page in there.

**Comment by basrieter** [comment]
Use the "i" key (apparently it is not in the context menu, I will add it)

**Comment by basrieter** [comment]
[retrospect-patch-20200211.210213.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4188015/retrospect-patch-20200211.210213.zip)

**Comment by matsarv** [comment]
Now I can see all the info.

Please add below to the swedish language file.

msgctxt "#30014"
msgid "Show info"
msgstr "Visa info"

**Comment by basrieter** [comment]
Thanks! Just added that.
