### ISSUE TITLE
SVTPlay.se - Live TV object has no attribute 'items'

### ISSUE THREAD

**Issue by Sopor** [retrospect-addon/plugin.video.retrospect#1289]
### Describe the bug
Here is a clear and concise description of what the problem is:

Live TV won't show any channels. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

View Live TV

## Actual Behavior

`Error retrieving list of items`

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
https://pastebin.com/a0FLH61V

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.5
- Retrospect version: 5.1.6

**Comment by basrieter** [comment]
Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi.

[retrospect-patch-20200210.234733.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4183416/retrospect-patch-20200210.234733.zip)

**Comment by Sopor** [comment]
I get the same message, but no channels are streaming anything. I believe it should still show a message, right?

**Comment by basrieter** [comment]
At this moment only channels with streams show.

But I could have a look at that. But check if it works tomorrow when there are streams.

**Comment by Sopor** [comment]
The first program will start at 05:15.

**Comment by Sopor** [comment]
Hmm, only SVT1 and SVT2 are working. `SVT Barn` will not work.

**Comment by basrieter** [comment]
I need logs, always logs. So please try the playback again and post links to the Retrospect debug logs.

**Comment by basrieter** [comment]
Fixed that I think.

[retrospect-patch-20200211.195548.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4187638/retrospect-patch-20200211.195548.zip)

**Comment by Sopor** [comment]
Yes, you're right. It's fixed :)
