### ISSUE TITLE
HTML opmaak filteren uit de text item.description AT5

### ISSUE THREAD

**Issue by didamsko** [retrospect-addon/plugin.video.retrospect#1292]
Gebruik momenteel Retrospect 5.1.6 in laatste versie van OSMC op de Vero 4K + maar dit speelt eigenlijk al vanaf het begin dat ik Retrospect ben gaan uitproberen. 

De text item.description van de AT5 uitzendingen komt in beeld met de HTML opmaak er nog in:

--------------------------------------------------------------------------------
```
<p>Dit is het ... </p>
<ul>
<li>Item over ...</li>
<li>Volgende item ...</li>
...
</ul>
```
--------------------------------------------------------------------------------

![IMG_7984](https://user-images.githubusercontent.com/60958082/74311370-9e412700-4d6f-11ea-9e53-9f132db3e91a.jpg)

Kan je die HTML opmaak er svp uitfilteren? Misschien dan gelijk uit alle item.description text halen en niet alleen uit die van AT5?

Bij voorbaat dank!

**Comment by basrieter** [comment]
Dat is inderdaad niet handig. Gelukkig hebben we standaard code om dat op te schonen. Zou je de bestaande bestanden van Retrospect kunnen overschrijven met de bestanden in deze zip (dus niet "install from zip")? Dan Kodi herstarten en kijken of het dan werkt?

[retrospect-patch-20200212.090445.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4190563/retrospect-patch-20200212.090445.zip)

**Comment by didamsko** [comment]
Bedankt! De HtmlHelper werkt prima:

![IMG_8006](https://user-images.githubusercontent.com/60958082/74316715-5a075400-4d7a-11ea-8772-6a22b2e33509.jpg)

Ziet er toch wat netter uit zo :)

Wat mij betreft kan thread dan gesloten worden als opgelost. Fijne dag!

**Comment by didamsko** [comment]
PS, ook die andere weergave (onderste deel van eerste afbeelding) klopt nu.
