### ISSUE TITLE
NPO Start: recent items give "Fout bij het ophalen van de items" or are empty

### ISSUE THREAD

**Issue by mvmsoft** [retrospect-addon/plugin.video.retrospect#1295]
### Describe the bug
Here is a clear and concise description of what the problem is:

All 'recent' items (today, yesterday, friday etc) are empty lists or give "Fout bij het ophalen van de items"
## Expected Behavior

A list of programs in NPO of the respected day.

## Actual Behavior

Fout bij  het ophalen van de items, bij elk onderdeel van de 'Recent' folder
## Possible Fix

Retrospect glitch? In 5.1.6 this worked as expected, but in 5.1.7 it's a problem
### To Reproduce

1. In Retrospect, goto NPO Start, then "Recent", then "Vandaag" (or any other choice)

### Debuglog

The **debug** retrospect.log can be found here:
The log is called befowamego

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.5
- Retrospect version: 5.1.7

**Comment by basrieter** [comment]
I see, I think I broke that yesterday.

**Comment by mvmsoft** [comment]
With more and more code to maintain, these kind of errors will occur more frequently. What you could try to do about it: get a 'acceptance´  team in between yourself (the development team) and the users (us)

**Comment by basrieter** [comment]
This was just a coincidence because NPO has some weird API output. But yes, I might need to look into this more.

**Comment by basrieter** [comment]
Please try this version. You can use the "Install from zip" option.

[plugin.video.retrospect-5.1.7-1295.1.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4200661/plugin.video.retrospect-5.1.7-1295.1.zip)

**Comment by mvmsoft** [comment]
You're fast. And thanks a LOT, checked some days in Recent, and all of them seem to work as usual. Regarding the 'acceptance' team, you could consider a few people that each have another part of retrospect to watch. It's surely a bit complicated, because we're dealing with a moving target, which is quite big. I myself am interested in NPO Start and (f.i.) ONS. But not so in Veronica or RTL. Anyway, thanks again. Great!
