### ISSUE TITLE
Keyframes Missing during watching

### ISSUE THREAD

**Issue by YMaas** [retrospect-addon/plugin.video.retrospect#1297]
### Describe the bug
Here is a clear and concise description of what the problem is:

Hello i am using retrospect with great pleasure on my galaxy a40 but i am experiencing strange video playback since updating my phone. I now get the images you see attached from kodi 18.5 and retrospect  5.1.8 but also on older versions. Other device de video looks ok but not on my phone. Any suggestions would be nice
## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

Normal view by Kijk.nl app it doesn't show the video in the picture but is there and ok![Screenshot_20200217-211142_KIJK](https://user-images.githubusercontent.com/61164604/74684305-df03ca80-51cb-11ea-92c2-b30adca6f6e4.jpg)
Current view from kodi
![Screenshot_20200217-211257_Kodi](https://user-images.githubusercontent.com/61164604/74684408-170b0d80-51cc-11ea-913b-da4b5e017302.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.5
- Retrospect version:5.1.8

**Comment by basrieter** [comment]
If it the playback starts and certainly if it al works on other devices than Retrospect is doing what is should do. It will most likely be a Kodi videoplayer thing then. And as you provide no logs what so ever, I can't really say anything about that. So for now, I will close this issue.
