### ISSUE TITLE
failed to install retrospect on xbox one 

### ISSUE THREAD

**Issue by mikafo** [retrospect-addon/plugin.video.retrospect#1298]
##Bug report
### Describe the bug
On Kodi 18.5 on Xbox One I try to install retrospect add-on . After I pressed to install from the add-on repo. I get an error at the bottom of the screen. The dependency of
inputstream.adaptive version 2.0.19. Then the retrospective installation fails. Hence it does not appear on video add-ons. Inputstream.adaptive  add-on is also not listen on kodi repo on xbox.

## Expected Behavior
successful installation retrospect.

## Actual Behavior
unsuccessful installation retrospect. 

### To Reproduce
try to install the addon on kodi xbox

### Your Environment
Used Operating system:
[x ] Xbox

Used versions:
- Kodi version: 18.5
- Retrospect version: 5.1.8

**Comment by basrieter** [comment]
The add-on is a dependency and if it does not exist, it won't work. Ask in the Kodi forums why the InputStream Adaptive is not available for Xbox. 

Read this one: https://forum.kodi.tv/showthread.php?tid=349961
