### ISSUE TITLE
Vault PIN at every log on

### ISSUE THREAD

**Issue by hubdeb07** [retrospect-addon/plugin.video.retrospect#1299]
Hello,
The last two days I am prompted to enter the retrospect vault pin at every start of a paid program on NPO Start. Once the pin is entered, a pop-up message saying "Could not log on to the selected channel" appears. After clicking OK the program plays just fine.
In the past I was never asked for this PIN and the vault worked silently in the background.

I purged retrospect and reinstalled but with the same result.

What could be causing this?
Thank you

The **debug** retrospect.log can be found here: https://paste.kodi.tv/vorabowajo.kodi

**Comment by basrieter** [comment]
Could you please try to set a password for the NPO channel. I think it is empty at the moment. 

The fact it works is because the cookie is still valid but the extension fails so Retrospect thinks the login failed.

**Comment by hubdeb07** [comment]
Het kan ook in het Nederlands zie ik,

Ik heb er nader naar gekeken en ik heb iets te snel gedacht dat het om de premium items gaat maar  ik zie eigenlijk ook precies dezelfde symptomen als bij deze issues:

Net als issue “Retrospect PIN (???) #1194” werd ik ineens verrast met de PIN invoeren bij ieder programma. Ik neem tenminste aan dat dat niet de bedoeling kan zijn...en ik het bestaan van die vault PIN ook alweer lang vergeten was.

En net als issue “NPO start PLus items are not working.. #1291” krijg ik bij de premium items het bericht "dit programma is niet (meer) beschikbaar. (15)” en er speelt dan niks,

In dit log zijn als retrospect opstart de  username en password gewoon ingevuld,
Eerst ga ik naar recent > nos journaal (daar zou je normaal toch niet voor in hoeven te loggen?) en moet ik de pin invoeren gevolgd door Could not log on for: NPO Start. Daarna speelt het normaal.

Ik ga naar Hele lijst > grenslanders (want ik weet dat dat een premium item is en ik heb gecheckt of het in npostart.nl wel aanwezig is ) de lijst verschijnt keurig met kleine a-tjes dus helemaal goed. Ik selecteer er één > PIN > Could not log on for: NPO Start. >  dit programma is niet (meer) beschikbaar. (15)

Vanaf hier heb ik de  username en password gewist in de settings en nogmaals  Hele lijst > grenslanders,
(nu uiteraard geen PIN gevraagd) >  dit programma is niet (meer) beschikbaar. (15)

Tenslotte dus zonder  abonnement weer naar hetzelfde NOS journaal en dat speelt dan gewoon zoals je zou verwachten,

Ik wordt van het log niet veel wijzer, wel héél véél cookies maar ik weet niet wat wel en niet normaal gedrag is.

De andere issues blijken vanzelf opgelost te zijn maar hier is het na meerdere herinstallaties nog steeds hetzelfde. Ik zet nu het abonnement maar uit, dan kunnen we tenminste gewoon kijken want dat gaat verder prima..!
Bedankt.

logfile : https://paste.kodi.tv/ayaxoricis.kodi

**Comment by basrieter** [comment]
Apart. Zou je het volgende eens kunnen doen nog:

- Download de hele Retrospect repo even als zip vanaf hier: https://github.com/retrospect-addon/plugin.video.retrospect/archive/master.zip
- Installeer deze binnen Kodi
- Binnen de add-on settings van Kodi even TRACE logging aanzetten
- Stel je username voor NPO nog een keer in
- Stel je wachtwoord voor NPO nog een keer in
- Navigeer naar een premium video
- Probeer deze af te spelen
- Navigeer naar een non-paid item
- Probeer deze af te spelen

Daarna de log op paste.kodi.tv zetten en hier linken.

**Comment by hubdeb07** [comment]
Precies gedaan zoals gevraagd, met hetzelfde resultaat als hierboven.

logfile: https://paste.kodi.tv/ulutivovij

**Comment by mvmsoft** [comment]
Geen idee of het er iets mee te maken heeft, maar mijn rasp met een wat ouder 16GB kaartje gaf tot gisteren allerlei hickups in Retrospect: haperende uitzendingen. Bv die leuke serie Grenslanders stokte bijna elke 5 minuten, en moest dan weer op gang geholpen worden. Mijn micro-SD kaartje van 32GB weer ingericht, en nu kon ik zonder haperingen kijken. Dus misschien is het alleen een wat brak kaartje bij hubdeb07. Vroegah had je harde schijven en chkdsk, maar wat heb je voor sd-kaartjes? NB misschien gaat het daar niet om, maar opslag kan stuk.

**Comment by hubdeb07** [comment]
Nee hoor, Kodi draait hier op een laptop met een echte harde schijf.
In ieder geval kreeg je íets te zien, ook al haperde het, hier is het gewoon niet beschikbaar...

**Comment by basrieter** [comment]
Je login gaat gewoon fout zoals ik het zie. Ik heb het idee dat je een verkeerd WW gebruikt, maar NPO geeft dat niet terug. Weet je echt 100% zeker dat  je username/ww combinatie klopt? Ik kan met mijn account namelijk gewoon inloggen.

**Comment by hubdeb07** [comment]
Bingo, dat was het dus gewoon!
Toen ik het wachtwoord opnieuw moest invoeren heb ik het ww dat we ergens opgeschreven hadden ingevuld. En daar zat een fout in!  Dus ik heb inderdaad elke keer, in de overtuiging dat het goed was, het ww met een fout ingevuld.
Mijn excuses voor het lastig vallen, want nu werkt alles weer zoals vroeger.
Hartelijk dank!

**Comment by basrieter** [comment]
Fijn om te horen. Veel plezier ermee.

**Comment by mvmsoft** [comment]
Ik zei: NB misschien gaat het daar niet om, maar opslag kan stuk. Denk toch dat daar bij mij de crux zit, want ook dat tweede 32GB kaartje deed al snel moeilijk. Beide zijn flink in gebruik geweest, en nu heb ik het kaartje van de rasp beneden (weinig gebruikt) in de rasp boven (veel gebruikt) gestopt, en hij deed het meteen, vond zelfs de DAC zonder tussenkomst. Nu alle afleveringen van Grenslanders gezien, zonder enige hapering. Ga nu maar eens wat voorzichtiger om met dat spul, niet zomaar de stroom eraf, maar eerst netjes afsluiten. Beetje off-topic, vrees ik (al moest ik mijn ww voor NPO Start eerst weer goed invoeren).
