### ISSUE TITLE
Norway: Remove Dplay.no channels that are premium

### ISSUE THREAD

**Issue by Snaah** [retrospect-addon/plugin.video.retrospect#1300]
### Is your feature request related to a problem? Please describe

Didn't know where to put this, so I put it here.

These Dplay.no channels can be removed because they are all premium: Animal Planet, Discovery, Investigation Discovery and TLC. Can be verified here: https://www.dplay.no/kanaler

**Comment by basrieter** [comment]
Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1300.zip from zip and see if that fixes the problem.

**Comment by Snaah** [comment]
Fixed!
