### ISSUE TITLE
A better view of air date, available until date, season/episode, and length

### ISSUE THREAD

**Issue by Snaah** [retrospect-addon/plugin.video.retrospect#1301]
### Is your feature request related to a problem? Please describe

I found this solution in the plugin [YLE Areena/Arenan](https://github.com/hirsivaja/plugin.video.areena):
![image](https://user-images.githubusercontent.com/1334819/75197895-38817180-5757-11ea-874d-a76ce351a62e.png)

I think it is more easy to view the information for the date when a show was aired, what date it expires, the season and episode, and length of episode this way. Wouldn't it be great in Retrospect?

**Comment by basrieter** [comment]
Did you try how this looked in other skins? Confluence for instance?

**Comment by Snaah** [comment]
Confluence:
![image](https://user-images.githubusercontent.com/1334819/75291784-cf633200-581a-11ea-87f0-ce270d1d8fda.png)

**Comment by basrieter** [comment]
That does not look so nice. 

Besides that: season, duration and date are all standard Kodi fields. Fields that can be shown in different Kodi views. 

The expire date, perhaps premium or geo restrictions might be. But it should work on all skins.

**Comment by Snaah** [comment]
The reason it doesn't look good in Confluence I assume is because of the bold font used for the program title. No need to use that, this could be implemented to suit both Estuary and Confluence.

But are you saying the field/position for season/episode, air date and duration are fixed for an add-on to adhere to Kodi rules? Like these positions:
![image](https://user-images.githubusercontent.com/1334819/75297701-75696900-5828-11ea-8bb6-34e350dbda1d.png)

And it makes you not want to tinker with them?

**Comment by basrieter** [comment]
It is because it is not a multiline aware skin.

And no, the season, duration and date can be viewed in other Kodi views and are shown in Info panel not in the title (like your screenshot). 

If it is shown in the title it is because that is how it is called online.

From an add-on perspective I don't know (and don't want to know) what skin is being used. So there will not be a skin dependent solution.

**Comment by Snaah** [comment]
I understand a skin dependent solution wouldn't be good. "how it is called online"=how Yle sends the info or how the plugin collects the data?

Another idea to make the view a little better within present Retrospect then: What do you think about having the watchable until date at the top of the info text, instead of at the bottom? I many times feel it's a hassle to have to wait until the text scrolls down.

**Comment by basrieter** [comment]
I moved some stuff around and now display more at the top of the description. You can test it by downloading https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1301.zip and install it in Kodi via the _Install from zip_ option.

**Comment by Snaah** [comment]
You're quick as always! :)

I found the expires info and the geoblocked on TV4 shows. Actually, I prefer the geoblock info at the bottom as the ring after the title listing shows if a program is geoblocked (which is great BTW). That way there won't be a line break for the time ("23:59:59"). Won't the yellow colour be confusing to have on the expires info too? I'm thinking this placement, but white as the other text. What do you think?

(Really what would be great is to have the "infobox" with the icon start more towards the top of the screen, but I know that is skin related. We talked about it before.)

**Comment by basrieter** [comment]
Ok, thanks for the feedback. I did not get a line break before the time, but that is a skin thing.

I will see what options there are for arrangements of the text. I prefer all meta info to be all at the same place. 

Can you provide me a screenshot of how it looks now with you? With the time on a new line?

**Comment by matsarv** [comment]
I installed this and had a looked at this change, and I like it. 

I use the standard skin Estuary and get:
![expire-at-top_before](https://user-images.githubusercontent.com/46671821/75576683-b350d200-5a60-11ea-80cd-3fd8062f79e1.png)

I did a small change that i think looks a bit cleaner:
![expire-at-top_after](https://user-images.githubusercontent.com/46671821/75576770-d9767200-5a60-11ea-9f2d-5a1e2c9ea222.png)

Just my opinion.

**Comment by Snaah** [comment]
Here's how it looks at my place:
![image](https://user-images.githubusercontent.com/1334819/75578285-76361100-5a5b-11ea-847c-cef6e3ad0fce.png)

I'm running 1080p.

If all meta info should be in one place, I like @matsarv's positioning, but "Ses till:" is not correct Swedish. "Kan ses till:" works until we find something better. (Transifex makes language changes MUCH easier! Good decision, @basrieter.)

Another thought would be to get rid of the time ("23:59:59"). Instead we could have "Kan ses t.o.m.:" The abbreviation "t.o.m." means to and including [date].

**Comment by matsarv** [comment]
Please, leave the time visible. Programs will expire on varying times.
![expire-at-top_after3](https://user-images.githubusercontent.com/46671821/75593360-603d4600-5a85-11ea-8c59-89b3a2ea011b.png)

![expire-at-top_after4](https://user-images.githubusercontent.com/46671821/75593366-64696380-5a85-11ea-964f-2fbc07cb8450.png)

**Comment by basrieter** [comment]
Ok, thanks all for the feedback: I moved some stuff around and add the line breaks instead of pipes (|). See here: https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1301.zip

**Comment by Snaah** [comment]
@matsarv True. I hadn't noticed there were programs with expiry time not being 23:59:59. But then remove the seconds, at least? No need for them.

@basrieter The new formatting is much better!

**Comment by basrieter** [comment]
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1301.zip again. I removed the seconds.

**Comment by Snaah** [comment]
Looking good here! It will also be implemented for other channels, like SVT, right?

**Comment by basrieter** [comment]
Yes, will try to do that.

**Comment by basrieter** [comment]
I updated SVT, UR Play and ViaFree now. It think that were all of them. Please these these channels a bit more thoroughly: https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1301.zip

**Comment by Snaah** [comment]
Looking good to me. Well done!
