### ISSUE TITLE
request moviemeter.nl for trailers

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#131]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/131) by Anonymous.**

----------------------------------------

on a specific move there is 99 percent of the time  a trailer  
there  is also information about:score/votes,trailer,genre/director/Cast  
and storyline.Don't know what of this is possible to put in xot uzg.  
  
this url of the site i like especially.  
http://www.moviemeter.nl/list/top_recent/  
http://www.moviemeter.nl/film/cinema/  
http://www.moviemeter.nl/film/search/  
  
----  
Original item http://code.google.com/p/xot-uzg/issues/detail?id=131

**Comment by dagwieers** [comment]
Should this not be labeled "channel"?
