### ISSUE TITLE
Stievie.be / Q2.be and VTM.be are no longer working

### ISSUE THREAD

**Issue by ericbreynaert** [retrospect-addon/plugin.video.retrospect#1310]
Kodi leia latests version

alles werkte een paar dagen geleden nog. Nu DRM protection op alle stevie streams. 

logfile posted: ahubitagaf

Graag advies hoe dit op te lossen

**Comment by basrieter** [comment]
Kan je dat iets meer toelichten? Krijg je een melding over DRM?

**Comment by ericbreynaert** [comment]
Beste bas,

Ja inderdaad een melding dat drm protected streams Kodi Leia vereisen, en widevine en inputstream Adaptive.

Met een ok knop erop.

Maar ik heb al die dingen denk ik.

Grt

E

Sent from my Android phone using TouchDown (www.symantec.com)

-----Original Message-----

**Comment by basrieter** [comment]
Ik zie geen widevine. Die kun je vanuit de Retrospect add-on settings installeren met de inputStream Adaptive helper add-on

**Comment by ericbreynaert** [comment]
Heb ik al meermaals gedaan. Krijg altijd een bevestiging dat het ook zou zijn. Hoe installeer ik die widevine anders manueel?

Grt

Eric

Sent from my Android phone using TouchDown (www.symantec.com)

-----Original Message-----

**Comment by basrieter** [comment]
![image](https://user-images.githubusercontent.com/1310443/75614775-870a8380-5b3c-11ea-88b6-e7560dd41653.png)
Het is over met Stievie. Ik ga hem eruit halen.

**Comment by ericbreynaert** [comment]
Da's het probleem! Bedankt. Kan je misschien de VTM go integreren?

Die andere versie werkt niet zo vlot.

Sent from my Android phone using TouchDown (www.symantec.com)

-----Original Message-----

**Comment by basrieter** [comment]
Ik ga eens kijken.

**Comment by basrieter** [comment]
Hier kan je een test versie vinden van de huidige VTM.be: https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1310.zip

Deze kan je via "Install from zip" installeren. Enkel de live kanalen zitten nu nog in VTM.be. Ik kan deze van NL echter niet testen. Zou jij dat kunnen doen?

**Comment by ericbreynaert** [comment]
Ik heb die geprobeerd, maar begint altijd maar ergens op het einde te spelen.

Probleem met de reclame blokken. Er staat iets van in de issues.

Grt

E

Sent from my Android phone using TouchDown (www.symantec.com)

-----Original Message-----

**Comment by ericbreynaert** [comment]
Sorry, verkeerd gekeken. Ik dacht dat het die andere was. Ik probeer morgen ochtend.

Ik laat iets weten

Sent from my Android phone using TouchDown (www.symantec.com)

-----Original Message-----

**Comment by ericbreynaert** [comment]
Hallo, net getest.

Error: the selected item doesn't have a stream associated with it.


Logfile: judisutire

Sent from my Android phone using TouchDown (www.symantec.com)

-----Original Message-----

**Comment by basrieter** [comment]
Probeer je dat vanuit België?

**Comment by ericbreynaert** [comment]
Yup, vanuit vlaanderen

Grt

e

**Comment by basrieter** [comment]
Dan gaat ie er gewoon helemaal uit denk ik.

**Comment by basrieter** [comment]
Ik heb ze verwijderd: https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1310.zip

Enkel VTM.be staat er nog, want die werkt af en toe voor oude items.

**Comment by peno64** [comment]
Er bestaat een addon voor vtm go: https://github.com/michaelarnauts/plugin.video.vtm.go
Binnenkort komt die ook in de officiele kodi repo maar ondertussen kan je hem al installeren vanuit https://github.com/michaelarnauts/plugin.video.vtm.go/releases
Merk op dat je de laatste versie van inputstream.adaptive moet hebben opdat deze addon zou werken want vtm go gebruikt een feature die maar in die laatste versie van inputstream.adaptive wordt ondersteund en deze is nog maar een paar dagen uit.

**Comment by basrieter** [comment]
Ik ga waarschijnlijk gebruikers naar jullie add-on verwijzen vanuit Retrospect

**Comment by basrieter** [comment]
I referenced Stieve.be to the new upcoming VTM Go add-on: https://github.com/xbmc/repo-plugins/pull/2730

Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1310.zip and let me know if the link is shown. 

* If you have not installed https://github.com/michaelarnauts/plugin.video.vtm.go/releases it should show it as "missing" 
* other wise it will allow you to redirect to the VTM Go add-on.

![image](https://user-images.githubusercontent.com/1310443/75718494-56a91d80-5cd3-11ea-8b15-949b6b885560.png)

**Comment by dagwieers** [comment]
Stievie FREE is voorbij (vervangen door VTM GO) maar Stievie PREMIUM blijft nog verder bestaan.

**Comment by basrieter** [comment]
@dagwieers Als iemand me een account kan geven om het te testen dan kan ik er wellicht wat in laten zitten, maar voor nu is het helemaal dood.

**Comment by basrieter** [comment]
Thanks @dagwieers for helping on the premium live channels. https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1310.zip now contains Stievie with just live channels if you have a premium Stievie account.

**Comment by basrieter** [comment]
Any that can verify this works?

**Comment by galsom** [comment]
We have been a paying subscriber for Stievie now for several years and the mentioned change to VTM GO at the moment is only for the free Stievie accounts, not the paying subscribers.

Is it possible to make the already aired shows again accessible when the add-on settings contains a username and password or some other way of differentiating a paying subscriber?

**Comment by basrieter** [comment]
The aired shows were no longer available for Stievie as far as I could see.

**Comment by galsom** [comment]
<img width="1519" alt="stievie" src="https://user-images.githubusercontent.com/48659253/76260237-a64d9300-6257-11ea-87d0-2a4cb2fecf5c.png">

This is what we currently see in the browser view, showing all the aired shows and we are able to select e.g. earlier ones from today.

Is the code that you use working with this data?
