### ISSUE TITLE
MTG Viafree channel - enhance look and feel

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1311]
### Is your feature request related to a problem? Please describe

No problem, just some small enhancements for a great product.

### Describe the solution you'd like

Some minor enhancement are requested, test-code for the requested changes below that I use on my own system.

Add thumb and fanart when searching for something, Today, only thumb on item (stream)
(search for "American")

```
Add after row 769 (5.18): item.thumb = self.__get_thumb_image(result_set["image"])

        thumb_data = result_set['_links'].get('image', None)
        if thumb_data is not None:
            item.thumb = self.__get_thumb_image(thumb_data['href'])
            item.fanart = self.__get_thumb_image(thumb_data['href'], True)
```

Before:
![before](https://user-images.githubusercontent.com/46671821/75608382-2a3ca800-5aff-11ea-95b6-bf394bdc43e7.png)

After:
![after](https://user-images.githubusercontent.com/46671821/75608384-3163b600-5aff-11ea-9124-25b651074d22.png)

**Comment by basrieter** [comment]
I can't find this show (American Heist). Where is it?

**Comment by matsarv** [comment]
The show (American Heist) is not there anymore.

Goto Viafree (Sverige) press .: Search :. and type: american 
The two shows don't have any thumb and fanart for the folder.

Before:
![before2](https://user-images.githubusercontent.com/46671821/76058069-af9adf00-5f7b-11ea-9134-107c28f64b5c.png)


After:
![after2](https://user-images.githubusercontent.com/46671821/76058081-b45f9300-5f7b-11ea-9d8e-a3f7e8d49f2c.png)


The above code is added 
after row 755 (latest): item.thumb = self.__get_thumb_image(result_set["image"])

I hope this help you.

**Comment by matsarv** [comment]
The changes look good. Ready for release.
