### ISSUE TITLE
SE TV4 channel - enhance look and feel

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1313]
### Is your feature request related to a problem? Please describe

No problem, just some small enhancements for a great product.

### Describe the solution you'd like

Some minor enhancement are requested. Test-code for the requested changes below that I use on my own system.

 - Increase maxPageSize (other channels have 100)
```
replace row 87 (5.18): self.maxPageSize = 25
        self.maxPageSize = 100
```
- Add fanart to single item 
   (search for "Agatha" goto "I huvudet på Agatha Christie"
```
add after row 535 (5.18): item.thumb = thumb_url

        if self.parentItem.fanart.startswith("resource") and item.thumb.startswith("http"):
            item.fanart = item.thumb
```

Before:
![before](https://user-images.githubusercontent.com/46671821/75608577-024e4400-5b01-11ea-83ff-3549dc892071.png)

After:
![after](https://user-images.githubusercontent.com/46671821/75608578-05e1cb00-5b01-11ea-8fe9-1f7947aebe3b.png)

**Comment by matsarv** [comment]
A better way to add fanart to single item.

In mediaitem.py
```
add after row 413: if self.fanart and not AddonSettings.hide_fanart():

            if self.fanart.startswith("special") and self.thumb.startswith("http"):
                self.fanart = self.thumb
```
This will show correct thumb when fanart is missing for present and future implementations.
With above it's no need to implement issue #1314 and #1315

**Comment by basrieter** [comment]
I don't like the generic approach as it will be for all channels. And to be honest: I don't really like this for all channels.

**Comment by basrieter** [comment]
Please use https://github.com/retrospect-addon/plugin.video.retrospect/pull/1321 and the related branch to test and provide feedback.

**Comment by matsarv** [comment]
Everything works and looking really good. Ready for release.

**Comment by basrieter** [comment]
So I was thinking about your generic suggestion. I didn't like the location where you do propose this.

But, what I can do is make a setting: "Use thumbnail images if fanart is missing" and then put the generic code it the right place and use this setting.

**Comment by matsarv** [comment]
This would be a great soluton.

**Comment by basrieter** [comment]
Please test this PR: https://github.com/retrospect-addon/plugin.video.retrospect/pull/1322

**Comment by matsarv** [comment]
Everything works with the new setting (Show thumbnail as fanart if no fanart is available) and looking really good. Ready for release.
