### ISSUE TITLE
SE Öppet arkiv channel - enhance look and feel

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1314]
### Is your feature request related to a problem? Please describe

No problem, just some small enhancements for a great product.

### Describe the solution you'd like

Some minor enhancement are requested. Test-code for the requested changes below that I use on my own system.

- Add thumb as fanart to both Program and Genre item
Program and Genre is missing fanart and then it's good enough to use the thumb as fanart.

```
add after ~238:  item.thumb = thumb_url

        if self.parentItem.fanart.startswith("resource") and item.thumb.startswith("http"):
            item.fanart = item.thumb
```

Before:
![before](https://user-images.githubusercontent.com/46671821/75608721-7ccb9380-5b02-11ea-824c-57f02e98a127.png)

After:
![after](https://user-images.githubusercontent.com/46671821/75608720-7a693980-5b02-11ea-80a0-f08f0a9e48f4.png)

**Comment by basrieter** [comment]
Please check the linked PR and Branch so see if it all works as expected.

**Comment by matsarv** [comment]
Everything works and looking really good. Ready for release.

**Comment by matsarv** [comment]
Everything works with the new setting (Show thumbnail as fanart if no fanart is available) and looking really good. Ready for release.
