### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1316]
### Is your feature request related to a problem? Please describe

Capital letter in centence word.

### Describe the solution you'd like

I'm guessing that there should not be a capital letter in centence word, see picture below.
I suggest to change A to a, "Titlar med andra tecken"

### Additional context

![viafree-grouping-names](https://user-images.githubusercontent.com/46671821/75609015-59561800-5b05-11ea-82a9-492c323198a6.png)

**Comment by basrieter** [comment]
I will fix that. For future translations I would like to invite you to join the translation team. That way you can propose new translations: https://www.transifex.com/retrospect/public/

**Comment by basrieter** [comment]
Fixed with 0b516b462c00391c7d672f1899688d21909f03bd
