### ISSUE TITLE
Sweden, TV4: Add ".:[menu item]:."

### ISSUE THREAD

**Issue by Snaah** [retrospect-addon/plugin.video.retrospect#1317]
### Is your feature request related to a problem? Please describe

It would be nice to add ".:[menu item]:." to make the "meta entries" just like for all other channels. For example for Search and TV-programs. Consistency is a virtue. :)

**Comment by basrieter** [comment]
Nope. The only reason that the others have `.: :.` is to distinquish them from normal folders belonging to a TV Show. For TV4 these folders are not mixed. So no need. I am changing SVT similar.
