### ISSUE TITLE
Sort "single episodes" into an own folder

### ISSUE THREAD

**Issue by Snaah** [retrospect-addon/plugin.video.retrospect#1326]
### Is your feature request related to a problem? Please describe

In some channels there are episodes, for example movies, that don't have a parent folder. They are shown at the end of the main A-Z listing. Would be great if those could be sorted in an own folder.

### Describe the solution you'd like

Have a special folder for the "single items" without a folder.

**Comment by basrieter** [comment]
Please try this version: https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1326.zip (use Install from zip)

The separate clips can now be found a folder in the main listing.

**Comment by matsarv** [comment]
Just tested and I do not like this new approach for SVT Play.

I really want to see things to look nice and have a structure that is straight forward so it's easy to find the programs you are looking for.

It now stated to be so hard to find what you want to look at and have to wander around before you find what you looking for. 

Back in December 2019, SVT Play was acting the same as all the other Swedish channels in Retrospect and was mirroring the website. 

If I would like to look for a program today I will go to the web and press Program. There I will find all the program that SVT Play will offer to me in separate folder. When pressing a program folder it which could contain single, episode or season program and you get a description and a nice thumb and fanart on what you are looking for..

When the change was made to remove the folder for single program the description and thumb and fanart was lost and you will not get any information about the program. I didn't like this change.

Now with this latest change you have to go to different places (folders when the program list be put into a folder) to look for a specific program. This doesn't feel natural.

I really would like to get back the old layout as in December 2019 and have a Retrospect setting for choosing the old like the other channels and this new approach.

Just my opinion
Regards Mats

**Comment by basrieter** [comment]
Ok, let's pause it here. 

**I do not deliberately move anything**. SVT changed their API completely (See #1254). This caused "single" video items, that would usually **not** be showing at all or would be in a folder with a single video item, to appear in the main listing. I did not choose that, SVT did. They removed all thumb data from their main list (_just like the website_). So Retrospect is still in line with the website. 

So please don't accuse **me** of messing things up for users of Retrospect. See me as the messenger, not the cause of this restructuring at SVT. 

Besides that: If it was up to me, I would convert all TV channels to the format of TV4 and NPO. So that it is generic within Retrospect. 

So @snaah and @matsarv discuss this with each other and let me know the result. Until that time, things stay as they currently are. All time spent on these lines of code seem to be a waste at the moment.

**Comment by matsarv** [comment]
I'm so sorry Bas, I didn't mean to accuse you. I really like the things you are doing with Retrospect. It's fantastic work and I know you spend allot of time on this.  Please don't let my above comment stop you in any way as I don't see all that happens in the background from the source. 

Please,  put this item to "waiting for user" again and continue all the great work you are doing for us with Retrospect.

**Comment by basrieter** [comment]
> I'm so sorry Bas, I didn't mean to accuse you. I really like the things you are doing with Retrospect. It's fantastic work and I know you spend allot of time on this. Please don't let my above comment stop you in any way as I don't see all that happens in the background from the source.
> 
> Please, put this item to "waiting for user" again and continue all the great work you are doing for us with Retrospect.

No worries, let's say that out Corona "stay-at-home" is starting to affect my mood. But I do think that would be interested in the discussion between you and @snaah as you both have different  opinions.

**Comment by basrieter** [comment]
So I did a compromise: https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1326.zip

Via the SVT channel settings you can now select to see either a "Clips" and "TV shows" folder (so both) or include them in the main listing (as it was)

**Comment by matsarv** [comment]
Greate work. Here are my thoughts.

I think you should only show the "extra_items" and "category_items" and "genre_tags" (with removed dots) in the root of SVT Play.

Default setting: "Show programs and clips in separate folders" is off.

All folders and streams (single program) is placed in the new "TV Shows" folder and possible to to use the setting "Advanced / Mix folders and streams while sorting" for sorting

![off](https://user-images.githubusercontent.com/46671821/77737710-cf6b7300-700e-11ea-9634-a355ba3e76dd.jpg)

This will be the same as today except now all programs is placed in a subfolder and the sorting dots can be removed form folders in root folder (as you have planned to do).
This is very good, now it's possible to goto any folder under SVT Play without have the full list of all programs.


--------
Setting: "Show programs and clips in separate folders" is on.

All program folders is placed in the new "TV Shows" folder and single program (single stream) is placed in a new "Clips" folder.

As requested above, when using "General / Group list if it exceeds # folders" it should be shown at the end of the main A-Z listing sorted in an own folder.

I think this new "Clips" folder should have a separate language translation as the (msgctxt "#30548", msgid "Clips") is used when a program have trailer(s) and the setting says someting like "Channel Setting / Show folders and single stream in separate folders"


@Snaah, please comment @basrieter changes and these proposed changes

**Comment by basrieter** [comment]
I could live with that. You @Snaah

**Comment by basrieter** [comment]
@sopor what is your view on this?

**Comment by basrieter** [comment]
@matsarv please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1326.zip again. I perhaps need to look at the labels, for from a functional perspective, is this what you mean?

**Comment by matsarv** [comment]
Really nice work, right on spot.

Settings: "Show programs and clips in separate folders" is off.

Now folders and single item is in "TV Shows" and the speed to go between folders in SVT Play is fantastic.

Checked two settings:

- Working:  "Advanced / Mix folders and streams while sorting"
- Not working: "General / Group list if exceeds # folder", only single stream is showing up in the "TV Shows" folder.

**Comment by matsarv** [comment]
I did some more testing and found that "Live TV" is not working again. It's the same in released version 5.2.0. See [retrospect-latest.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4397654/retrospect-latest.log)

**Comment by basrieter** [comment]
> Really nice work, right on spot.
> 
> Settings: "Show programs and clips in separate folders" is off.
> 
> Now folders and single item is in "TV Shows" and the speed to go between folders in SVT Play is fantastic.
> 
> Checked two settings:
> 
> * Working:  "Advanced / Mix folders and streams while sorting"
> * Not working: "General / Group list if exceeds # folder", only single stream is showing up in the "TV Shows" folder.

* Not working: "General / Group list if exceeds # folder", only single stream is showing up in the "TV Shows" folder.

Don't know what you mean with that? Did you refresh the list after the changes?

-

**Comment by matsarv** [comment]
Settings: "Show programs and clips in separate folders" is off.
I'm change "General / Group list if exceeds # folder" to 10.
Checking "Genre / Drama" and both Tiles with... folders and single stream is shown.
![genre](https://user-images.githubusercontent.com/46671821/77831540-0dac8380-7130-11ea-86ba-1c4d39f4b5f7.png)
Checking "TV Shows" and only single stream is shown.
![tvshows](https://user-images.githubusercontent.com/46671821/77831566-3a609b00-7130-11ea-81e0-7fdd8ecc1c17.png)
I also tested Refresh List on "TV Shows" folder, still only single stream is shown.

**Comment by basrieter** [comment]
Ok, I fixed the live stuff: SVT moved to GraphQL there. 

I only split clips/tv shows in the main listing, not other folders. Can you check now. I could not really reproduce your issue, but for me it seems to work. If it does not for you, please post some more details: your info was super, it only lacked what you expected to see (you said what was wrong).

**Comment by matsarv** [comment]
Greate. Live TV is working again.

OK. I reverted back to 5.2.0 and set the group list to 10
Then it will show both Titles with.... and single stream (in the SVT Play folder). 
![titles529](https://user-images.githubusercontent.com/46671821/77832308-62063200-7135-11ea-8190-15fffc119157.png)
My guess is it should be the same when moved the "program folders and single stream" into the new "TV Shows" folder and using the Group list. I hope this will help you.

**Comment by basrieter** [comment]
If I set the group list limit to 10, and disable the new "Show programs and clips in separate folders" it does exactly what is should do for me. This is what I see under `TV Shows` then:

![image](https://user-images.githubusercontent.com/1310443/77833364-0d66b500-713d-11ea-873d-bcb3a2399cf9.png)

Of course it starts at `Titles with '0-9'`

After `z` the clips are being listed. That is how I would expect it.

**Comment by matsarv** [comment]
I manage to get them to show by  set the "Mix folders and streams while sorting" to off.
Now it shows both Titles with.... and single stream. 
![titles2](https://user-images.githubusercontent.com/46671821/77833748-eb226680-713f-11ea-9fcb-8ba476052b6b.png)
In 5.2.0 it worked to have "Mix folders and streams while sorting" to ON but now it must be switched OFF to get the same result.

**Comment by basrieter** [comment]
Ok, found it. It's the sorting in Kodi that messes that up! The main SVT list is sorted by Date by default ( I really have no clue why), while the others are sorted by name. Apparently the mixing only happens if sorting by name in Kodi. So it's a Kodi thing, not Retrospect. 

If you sort by Date, you get the list you expect. If sorting by name, the `Titles with ''` end up in the list under T.

**Comment by matsarv** [comment]
OK,  checked and all works greate.

**Comment by basrieter** [comment]
Please try this one: https://github.com/retrospect-addon/plugin.video.retrospect/archive/fd538378dbeef7edf27b853517ba21bb99b31471.zip

I made sure that even if sorting by Name: when these 'grouped' items are there, they appear at the top (if sorted from a->z)

**Comment by matsarv** [comment]
Perfect, now is the sorting correct even with the Swedish special characters.

**Comment by basrieter** [comment]
Great! I will make this the final solution. Thanks for your help!

**Comment by Snaah** [comment]
Sorry for the late reply. Been busy getting my butt back to Sweden from Spain. Horrible situation!

I appreciate both of your efforts. Great work!

My view:

First: Consistency is preferable, i.e. separate options for one channel is not good. It is confusing.

1. I think there should be separate options to have "Clips" or TV-shows as separate folders. One option for what is now called "Clips" and one for "TV shows".

2. I  think the "Clips" folder should be under TV-shows, simply because they are TV-shows.

3. I want these options to be for all Swedish channels (or all channels no matter what country?). I personally don't like to have a separate folder for "TV-shows" in TV4 for instance. 

4. Thus, I also want the ".:[menu item:." (Search, Recent, Most viewed, etc.) to be kept or another way to have an order where the "meta" menu items are at the top of the listing. 

5. I also agree "Clips" is not a good name because it is already used for short videos of news, trailers and such. As I want that folder in the regular A-Ö listings, I suggest "Single episodes"/"Enskilda avsnitt". This folder should be placed at the top as a ".:[menu item]:.".

6. It would also be great to have https://github.com/retrospect-addon/plugin.video.retrospect/issues/909 fixed while we're at it. I'm thinking it partly is about same things.

@basrieter I saw that you closed the issue while I was writing. Sorry again for commenting late.

**Comment by basrieter** [comment]
@Snaah that has probably been a nightmare to do at this point! Hopefully you are almost home. 

Let me respond to your input:

1. The options stays as it is. I have been planning to restructure SVT (and other similar channels with long mainlisting) into a more nested option. So the only _option_ there is now is to further split the 'Single episodes' into a folder. 
1. There are only 'Single episodes', no clips, that was just a temporary naming. Nothing changed for clips in the other listings
1. There won't be such option for all channels. SVT is an exception, because I did want to combine my preference with those of @matsarv 
1. There will not be a `.: title :.` option all _meta_ stuff. The `.: :.` was introduced to distinguish between shows and _special_ folders. In the new SVT listing, this distinction is no longer needed. Hence, no `.: :.`.
1. Yes, I will use your suggestion here for the naming. Sounds good.
1. #909 is a different item and much more complicated. It's for later.

**Comment by Snaah** [comment]
Healthy and in Sweden! Surprisingly, the Swedish Ministry for Foreign Affairs "organized" the trip (we had to pay muchos dineros, but that's irrelevant in these circumstances).

Ah, now I see that what you've made is exactly my suggestion. I thought the option would also put "TV Shows" under the initial listing. I didn't check enough. What confused me was the name of the option, "Split TV shows and single episodes in separate folders". I suggest changing it to "Show single episodes in a separate folder"/ "Visa enskilda avsnitt i en separat mapp".

Now that I know what the option does, let me comment.

1. I understand you want to have a root listing without the A-Ö listing of programs. The reason for this is that it takes time for Retrospect to show the list on some devices, right? I and probably more people can live with that. The change now adds one more unnecessary click. With the "meta items" on top it's optimal.

Separate options for each channel would probably be the best then, as some channels like TV12 don't have many programs.

2. I wasn't clear enough: I meant only the "Single episodes" folder. I want that in the A-Ö listings instead of the root. They are TV shows too. The folder would end up on top, as "Single" and "Enskilda" is before T. 

3. Ok, but I think it eventually would be really good for user control and Retrospect to be customizable.

4. Yes, I know the purpose with ".:[menu item]:.". Commented thinking the long listing with the "meta items" and the A-Ö together was still there. 

5. Ok!

6. I know, was just trying to trick you into doing that as well. :)

**Comment by basrieter** [comment]
Good to hear you got home safely. 

It is almost impossible to make this behavior generic for all channels, as each and every channel needs its own implementation. If I would make it a generic item, then all channels should be able to implement this, and that is difficult to do.

**Comment by matsarv** [comment]
@Snaah, glad to see you home safely.

Now that I've been reading you thoughts above, i understand better what you requested.

I've been thinking about how to make it easier for the end user as sometimes I often miss good settings myself.

This is what I've come to realize after using the new functions this morning, on how to achive a more simple way.

-------------
Setting 1 one and Setting 2 are working today in 5.2.1.
-------------
Setting 1:

"Group list if it exceeds # folders" is off
"Mix folders and streams while sorting" is off

Folder "TV Shows" displays:

Program folders first
Single episodes last

![Setting1](https://user-images.githubusercontent.com/46671821/77903357-03e76500-7283-11ea-9b1a-5f38218ba929.png)


Setting 2:

"Group list if it exceeds # folders" is off
"Mix folders and streams while sorting" is on

Folder "TV Shows" displays:

Mix program folder and single episode

![Setting2](https://user-images.githubusercontent.com/46671821/77903367-08138280-7283-11ea-8443-a817819253fe.png)


-------------
Below is a new thought for how use the grouping feature.
-------------
Setting 3:

"Group list if it exceeds # folders" is on
"Mix folders and streams while sorting" is off

Folder "TV Shows" displays:

Single episodes folder first
Titles with ... folders last

![Setting3](https://user-images.githubusercontent.com/46671821/77903397-16619e80-7283-11ea-863b-126d41aad5be.png)


Setting 4:

"Group list if it exceeds # folders" is on
"Mix folders and streams while sorting" is on

Folder "TV Shows" displays:

Titles with ... in the list
Single episodes in respectively Titles folders sorted
(No Single episodes folder)

![Setting4](https://user-images.githubusercontent.com/46671821/77903407-1a8dbc00-7283-11ea-859e-89e2c68e7395.png)
![Setting5](https://user-images.githubusercontent.com/46671821/77903413-1e214300-7283-11ea-9536-58226680abd4.png)


To do as above you do not need to have a channel setting for SVT Play.
No need to have the Single episodes folder in the SVT Play root as the Single episodes are also TV Shows.

Maybe I've missed someting but this could be a way forward.
Just a thought from me.

**Comment by Snaah** [comment]
Thanks to both of you.

@basrieter Ok, then go for individual settings trying to be as consistent as possible. As I keep repeating, consistency is good for the end user. We are used to Retrospect and know how it works. An idea in general: If there's any chance/time coming months, why not let someone who's never used it try? That's a good way to get input on improvements, including language.

@matsarv I don't like the new TV-shows folder. I liked the old listings better. They are easy and spot on when starting SVT. I feel the extra click to get to the listings is unnecessary and I like having ".:Kanaler:." at the top. That's why I want it to be optional to have the A-Ö listings in the root listing.

I understand what you are saying with "setting 3" and "setting 4". I think I suggested "setting 4" before and it's not possible to accomplish in an easy way. What do you say, @basrieter ? "Setting 3" places the "Single episodes" folder where I want it!

**Comment by Snaah** [comment]
@basrieter I suggest changing "Mix folders and streams while sorting" to "Mix folders and single episodes while sorting"/"Blanda mappar och enskilda avsnitt vid sorteringen".

**Comment by basrieter** [comment]
> @basrieter I suggest changing "Mix folders and streams while sorting" to "Mix folders and single episodes while sorting"/"Blanda mappar och enskilda avsnitt vid sorteringen".

These are two completely different thing. This setting only changes the Kodi sorting behaviour to mix videos and folder when sorting by name. This setting as nothing to do with these whole issue.

**Comment by basrieter** [comment]
So, I would rather add an option: `Flat/deep channel listings` and with `deep` it would stay the same as it is now. `flat` would result in a flat listing, as with as much as possible in main listing.

But I would then like to see it combined in a single setting with the `max group #` but I don't really see how that would come out. Suggestions?

**Comment by matsarv** [comment]
I hope I see what you mean "Flat channel listings"
I have tried to visualize how I see it, how it working now and how it could work with flat listing.

As default I have set the "Channel Settings" have "Split TV shows and single episodes in separate folders" to off.

Now SVT Play have the same layout as TV4 Play. All TV program is shown in the folder "TV shows" (is the generic setting for all TV channel in the future).

![1](https://user-images.githubusercontent.com/46671821/78019988-e7b1f980-7350-11ea-8537-28f1c876b131.png)

In "TV shows" Program folders and the stream (single episode without a folder) is displayed (for SVT PLay) - (as today)

![2](https://user-images.githubusercontent.com/46671821/78020005-ed0f4400-7350-11ea-9d81-bfb953203683.png)

Advanced setting like "Mix folders and stream while sorting" should still should work. - (as today)

![3](https://user-images.githubusercontent.com/46671821/78020032-f9939c80-7350-11ea-8e99-539396f07360.png)

If using "Group list if it exceeds # folders" show the folders "Title with .." list. (as today)

The streams (program without a folder) should be put into a folder "Single episodes" in folder "TV Shows" if single episode are present. -- (New change)

![4](https://user-images.githubusercontent.com/46671821/78020041-fdbfba00-7350-11ea-87a2-ab72a763ae28.png)

----------
The new flat channel listings is to have all the standard folders and "Single episodes" and "Titel with .." to showing up in the SVT Play folder.

![5](https://user-images.githubusercontent.com/46671821/78020052-02846e00-7351-11ea-962b-2e07853c96b8.png)

The above is achived if there was a setting "Flat channel listings (override Group list above)". -- (New change)

![6](https://user-images.githubusercontent.com/46671821/78020070-0912e580-7351-11ea-9375-37232a522a09.png)

I think this is something that could be used in many channels. This is how it could be looking in TV4 Play.

![7](https://user-images.githubusercontent.com/46671821/78021078-dc5fcd80-7352-11ea-90d5-f7afb55e388d.png)

-------------
I think, now the "Channel Settings" have "Split TV shows and single episodes in separate folders" for SVT Play will not be nedded anymore.

Above I have trying to visualize how it perhaps would work, if possible.

**Comment by Snaah** [comment]
> > @basrieter I suggest changing "Mix folders and streams while sorting" to "Mix folders and single episodes while sorting"/"Blanda mappar och enskilda avsnitt vid sorteringen".
> 
> These are two completely different thing. This setting only changes the Kodi sorting behaviour to mix videos and folder when sorting by name. This setting has nothing to do with this issue at all.

- "Streams" are the same as single episodes, right? I think it is good to use the same word for the same thing. Otherwise it's confusing.

- Having both "Mix folder..." and "Group list if exceeds..." enabled doesn't sort the single episodes into the A-Ö folders. They are only mixed if "Group list if it exceeds..." is disabled. Would it be possible to get the single episodes sorted in to the A-Ö folder?

- What you say about flat/deep is what I've been saying all along (remember the discussion for TV4): A setting for if the user wants the A-Ö listings in the root or under a separate TV shows folder. I don't understand why this should be connected to the setting for "Group list if it exceeds...". 

@matsarv What you suggest at the end is how SVT (and TV4) used to look before these changes took place. My suggestion is along these lines. The single episodes folder should be at the top of the A-Ö listing, no matter if the A-Ö listings are under a separate TV shows folder or not. I wan't the "Group list..." enabled, but still no extra TV shows folder.

This is how I want it optimally in the root:
Live TV
Search
Categories
[other "meta items"]
Single episodes folder
A-Z listings

OR

As above, but with single episodes sorted into the A-Ö listings.

If the user chooses to have a separate TV shows folder:

TV-kanaler
TV-program/Single episodes first then the A-Z listings
Search
Categories
[other "meta items"]

So, two settings:
1. Show listings in separate TV shows folder
2. Show single episodes in separate folder 

Sorry if this is getting hard to overlook. Hope you get the picture.

**Comment by basrieter** [comment]
@matsarv You almost have it. But the `Group list if exceeds` I will remove I think. I would make it so:

### Flat list

- .: Categories :.
- .: Currently Playing :.
- ..
- ..
- .: Search :. 
- Show A
- Show B 
- Single A
- Single B

### Flat grouped list
- .: Categories :.
- .: Currently Playing :.
- ..
- ..
- .: Search :. 
- Titles with 'A'
  - Show A
- Titles with 'B'
  - Show B
- .....
- Titles with 'Z'
- Single A
- Single B

### Deep list

- Categories
- Currently Playing
- ..
- ..
- Search
- TV Shows 
  - Show A
  - Show B
- Singles
  - Single A
  - Single B

### Deep grouped list

- Categories
- Currently Playing
- ..
- ..
- Search
- TV Shows 
  - Titles with 'A'
    - Show A
  - Titles with 'B'
    - Show B
  - Titles with 'Z'
- Singles
  - Single A
  - Single B

The lists take the setting `Group list if exceeds` and switches the mode from `deep` -> `deep grouped` or `flat` -> `flat grouped`

**Comment by matsarv** [comment]
OK, but I really would like to have one change above!
The "Deep list" shoud be acting as it doing is today, all the Show and Single is placed under TV Shows.

**Deep list**

Categories
Currently Playing
..
..
Search
TV Shows
- Show A
- Show B
- Single A
- Single B

**If mixed is used in General setting:**

**Deep list**

Categories
Currently Playing
..
..
Search
TV Shows
- Show Aa
- Single Aab
- Show Ab
- Single Aba
- Single Abb
- Show Ba
- Single Ba

**Comment by basrieter** [comment]
The mix setting has nothing to do with my code. It is 100% Kodi, so don't take it into account here. The only difference your are pointing out here is that you want the singles to be mixed with the TV shows again.

But that is specific for SVT and not any other channel. And that is the discussion we already had before. That would be a third view option: `flat`, `deep`, `compact`?

**Comment by matsarv** [comment]
What I'm trying to get is to have the list under TV Shows just as it is on www.svtplay.se under Program.
This is a complete list of program with all the singles and TV shows mixed in an alfabetic order. I don't see them as singles and TV show only as TV program.

If this is not possible, thats ok. I will live with that.

**Comment by basrieter** [comment]
> What I'm trying to get is to have the list under TV Shows just as it is on [www.svtplay.se](http://www.svtplay.se) under Program.
> This is a complete list of program with all the singles and TV shows mixed in an alfabetic order. I don't see them as singles and TV show only as TV program. I have this configuration in 5.2.1 today.
> 
> If this is not possible, thats ok. I will live with that.

So that would be the `compact` option where the mainlist is as _compact_ as possible

**Comment by matsarv** [comment]
> > What I'm trying to get is to have the list under TV Shows just as it is on [www.svtplay.se](http://www.svtplay.se) under Program.
> > This is a complete list of program with all the singles and TV shows mixed in an alfabetic order. I don't see them as singles and TV show only as TV program. I have this configuration in 5.2.1 today.
> > If this is not possible, thats ok. I will live with that.
> 
> So that would be the `compact` option where the mainlist is as _compact_ as possible

Yes, please. I would like to see this compact mode added to Cannel Setting for SVTPlay.

**Comment by Snaah** [comment]
First, please don't name this flat/deep/compact in Retrospect because it will be confusing. There's no need to either, as the settings titles are self-explanatory (see suggestion below). Using both "single episodes" and "streams" for the same thing will be confusing as well.

I agree with @matsarv (the last case). I would also like a listing with single episodes mixed with "show folders" in alphabetical order.

So, if we are talking the same lingo there should be two new options, and they will together with "Mix..." cause different listing results. Words in italic are what I suggest to change to.
1. _Show_ listings of TV shows in separate folder ("split" is ambiguous)
2. _Show_ single episodes in separate folder ("split" is ambiguous)
3. Mix folders and _single_episodes_ while sorting ("single episodes" is better) 

Swedish:
1. Visa listningar av TV-program i en separat mapp
2. Visa enskilda avsnitt i en separat mapp
3. Blanda mappar och enskilda avsnitt i listningar

When option 2 is enabled it will automatically override option 3. You can't mix folders and single episodes if the single episodes are in a separate folder.

Apart from this I'd like to have the root listing begin with
TV-kanaler
TV-program
Enskilda avsnitt
Sök

I like to be able to customize Retrospect.

**Comment by matsarv** [comment]
I really do like the way @basrieter presented on how it could be implemented.


This is how I image how  it could be seen in the settings.

- General settings (general = could be used in all channels like Dutch, Swedish a.s.o.)
![new1](https://user-images.githubusercontent.com/46671821/78242727-d6005b80-74e2-11ea-85a4-91b7a50f47f8.png)

- Channel Settings (SVT Play)
![new2](https://user-images.githubusercontent.com/46671821/78242751-df89c380-74e2-11ea-8cd9-241870074bc5.png)

- For showing the order of root folders, it should use the Kodi default built in sort and order.
![new3](https://user-images.githubusercontent.com/46671821/78242846-08aa5400-74e3-11ea-9e13-45062c6a7e7b.png)

**Comment by Snaah** [comment]
@matsarv I like this. Picture number two; with your "opposite" option single episodes will be shown in a folder by default. That is a good thing!

The default Kodi sorting order makes the sorting bad, it won't be in an intuitive order. The ".:[menu item]:." or another solution would be good. In the [Yle Areena plugin](https://github.com/hirsivaja/plugin.video.areena) they've solved it, overriding Kodi's sorting options:
![image](https://user-images.githubusercontent.com/1334819/78303866-d712a680-753d-11ea-9fa6-223ba5b380bb.png)

**Comment by basrieter** [comment]
Ok, so let me clarify some things:

1. Stop thinking that _mix folders and streams_ is something magically that I control: I don't. It's Kodi that mixes video items and folder items if, and only if, the list is sorted by _name_. It will not distinguish between video/stream/single, just _is it a folder_ or _can I play it_. So keep it out of this discussion regarding listing and grouping. So let's not call it _Mix folders and single episodes while sorting_ as it just wrong. 
1. So settings like 'Show TV shows and singles in the same folder" make no sense, as it has nothing to do with _singles_.
1. I don't control the sorting in lists: yes, the first time you ever open it I tell Kodi there is a default sort option. But after that, if you change it, Kodi will keep that user option for ever, and I cannot do anything about that.
1. I will be converting all channels to not show a full TV list in their root listing. As a gesture to older users, I am willing to make an option that will still show the full list as the root, but that setting will default to the _shorter list with a 'TV show' folder_ for one simple reason: it's faster on older/less powerful devices. So I want to keep the _root_ folder as small and fast as possible.
1. Only a few channels have a mixed list of _TV shows_ and _singles_ in their primary list of shows. Only for those lists, and NO other lists inside that channel, I could provide a _channel option_ to put those videos, that happen to represent a _single_ item, in a separate folder. 
   * That folder will always be in the root of the channel, nowhere else. Because otherwise there will be no end to where it should be and each channel needs to have a separate implementation for it.  
 
This might all seem harsh, but from the discussion above, I see that some ideas are based on false assumptions, which result in unrealistic ideas. So basically reading this back: it is the way it is currently in 5.2.1, with the only addition that you can show primary listing in the root of a channel.

**Comment by Snaah** [comment]
You don't seem harsh at all @basrieter Good you explain.

1. Yes, ok, but aren't the streams actually single episodes in Retrospect? Are there any occurrences where this does not apply? If not, then what are streams?

Do I understand you correctly: It is not possible to sort single episodes (streams?) alphabetically into "Titles by..." folders? If both "Mix..." and "Group..." are enabled, the single episodes will always be at the bottom of the listings?

2. ? Present option's title is "Split TV shows and single episodes into separate folders". The option @matsarv suggested is just the opposite of that, i.e. to have them show in separate folders is default (not enabled).  

3. ? You mean until the user changes the sorting order, right? Default will still be an option.

4. Great!´Thank you for this!

5. Here I disagree. I see the end being at either under TV-shows (always at the top) or an option to have them in the root or under TV-shows. But I am not the programmer. :)

No matter the outcome, I think  "Show"/"Visa" is better than "Split"/"Lägg" in the title of the option.
