### ISSUE TITLE
Swedish TV3, something has broken since last update.

### ISSUE THREAD

**Issue by orfeous1** [retrospect-addon/plugin.video.retrospect#1329]
Not able to watch new episodes for "Svenska Truckers" and "Frusna Vägar" on TV3play.
Stopped working after i updated Retrospect to 5.1.9.
I can play older episodes though without any problems.

Attaching logs.
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4313939/retrospect.log)
[kodi.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4313941/kodi.log)

**Comment by jpablo1980** [comment]
Ja precis. Det går inte att se dem senaste program från TV3. Alla dem som sänt i mars går inte att se men från februari och bakåt går fint

**Comment by basrieter** [comment]
Is it just that one? Or more shows?

**Comment by orfeous1** [comment]
There are more shows/programs that doesnt work.
"Norrmalmspolisen" for one more example.
"Lyxfällan" one more..

Trying to play latest episodes with fail and after i play the previous one and thats working also all others before that.

The episodes does play on the website

Attatching logs.

[kodi.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4315192/kodi.log)
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4315196/retrospect.log)

**Comment by basrieter** [comment]
I need a non-geo restricted (without the yellow circle) one, or a HAR capture from chrome: https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting

In the latter case, enable the logging as described, navigate to viafree and play the video on the website. Mail the result (don't post here as it might have sensitive info) to retrospect [at] rieter [dot] net.

**Comment by orfeous1** [comment]
Mailed you the recording!
/Anton

**Comment by basrieter** [comment]
Thanks, I think I can work with that. Just need to figure out some stuff. And I am currently a bit occupied with the stuff happening in The Netherlands and so.

**Comment by orfeous1** [comment]
Thank you!
Please notify me when you looked in to it and made up a "fix"
/Anton

**Comment by basrieter** [comment]
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1329.zip and install it using the "Install from zip" option. Should fix it. Although I can't really test is as it is Geo blocked.

**Comment by orfeous1** [comment]
Yes, it seems to work for me on TV3. Thank you!
Tried both Svenska Truckers and Frusna Vägar.
Also works with subtitles.

**Comment by basrieter** [comment]
Great!

**Comment by orfeous1** [comment]
Had to modify the addon.xml though to get it to work with Python 3.
<import addon="xbmc.python" version="3.0.0" />

**Comment by jpablo1980** [comment]
> Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1329.zip and install it using the "Install from zip" option. Should fix it. Although I can't really test is as it is Geo blocked.

I cannot download it

**Comment by basrieter** [comment]
Correct! It was merged with master. You can download that one now.

**Comment by jpablo1980** [comment]
R
Thanks

Den tis 17 mars 2020 11:37Bas Rieter <notifications@github.com> skrev:
