### ISSUE TITLE
Kodi team seems to broke something, addons not compatible

### ISSUE THREAD

**Issue by orfeous1** [retrospect-addon/plugin.video.retrospect#1330]
Latest Kodi 20200309 does not work with a lot of addons. Including Retrospect.
The last working Kodi version that works with Retrospect and others is 20200226.

Attatching logs.
[kodi.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4312175/kodi.log)

**Comment by basrieter** [comment]
True, we introduced a pure Python 3 API for add-ons in recent nightly builds. All add-ons need to resubmit their Python 3 version. 

I am waiting for a single dependency and them Retrospect will be there.

**Comment by orfeous1** [comment]
There is a temporary fix!
Look here.

https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/286#issuecomment-597059996

**Comment by Essam311** [comment]
@orfeous1 This fix is for you as a user, does not work for the developers of the add-ons, because they must wait until the developers of inputstreamhelper replace `"xbmc.python" version="2.25.0"` with `xbmc.python" version="3.0.0` and submit inputstreamhelper to Kodi Matrix repo so they can do the same for their add-ons too.

**Comment by orfeous1** [comment]
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4313377/retrospect.log)

Trying to run Kodi and modified Retrospect with no success.
Attached logfile from retrospect.

**Comment by Essam311** [comment]
@orfeous1 Did you deleted Kodi folder or just kept the old one?

**Comment by orfeous1** [comment]
Uninstalled and deleted the whole Kodi-folder. Started from scratch.
Looks like i need to install all the dependencies manually because Kodi repros have the non python 3 versions. Ive downloaded the newer ones manually and extracted them into correct folder.
All of them shows that they are installed but i still got that error message and the same info in the logfile for retrospect.

**Comment by Essam311** [comment]
Install this one manually.
https://mirrors.kodi.tv/addons/matrix/script.module.requests/script.module.requests-2.22.0.1.zip

**Comment by Essam311** [comment]
Does the videos of Apple move trailers working for you?

**Comment by orfeous1** [comment]
Allready installed that http request thing without problem.
How do i try the Apple movie trailers?

In my kodi.log it looks like there is something wrong with datapath or something.
Tried to install Youtube-addon.

2020-03-10 17:51:06.790 T:13116   ERROR: Requested path https://mirrors.kodi.tv/addons/matrix/plugin.video.youtube/plugin.video.youtube-6.6.0.1.zip not found in known repository directories
2020-03-10 17:51:06.790 T:13116   ERROR: CAddonInstallJob[plugin.video.youtube]: failed to resolve addon install source path
2020-03-10 17:51:06.823 T:10380   DEBUG: CGUIMediaWindow::GetDirectory (addons://repository.xbmc.org/xbmc.addon.video)
2020-03-10 17:51:06.823 T:10380   DEBUG:   ParentPath = [addons://repository.xbmc.org/xbmc.addon.video]

**Comment by Essam311** [comment]
@orfeous1 You do not extract the files, you need to install them from "Add-ons" then "Download" then "Install from zip file".

**Comment by orfeous1** [comment]
Sorry, im an idiot.. i didnt use Kodi to install the scripts. I extracted the folder manually :)
Now retrospect starts :)

**Comment by Essam311** [comment]
In "Video" in the main list of "retrospect" then "Apple movie trailers" and try to play any video.

**Comment by orfeous1** [comment]
There are no Apple movie trailers

**Comment by Essam311** [comment]
In my country (Egypt) I get this, I can only test the free videos, but this is not important as long as the add-on is working for you.

![1](https://user-images.githubusercontent.com/59211054/76341356-98eee200-6305-11ea-9173-799d38b1e5ac.png)

![2](https://user-images.githubusercontent.com/59211054/76341374-9f7d5980-6305-11ea-91c2-499c3618943d.png)

![3](https://user-images.githubusercontent.com/59211054/76341383-a60bd100-6305-11ea-8f76-cc1190618ac8.png)

**Comment by basrieter** [comment]
Can somebody give a bit more details on the Apple movie issue? Is it also broken within Retrospect in Leia?

**Comment by Essam311** [comment]
@basrieter This is in Kodi 19 Matrix latest build, it working for me.

**Comment by orfeous1** [comment]
I will try, didnt know that it existed.
I disabled every channel except the Swedish one.

**Comment by orfeous1** [comment]
Tried now, seems to work great except that on some trailers it seems to buffer a loooooot.
Starts playing for 2sec then stops and i see a circle in the middle counting numbers like 1...........................................................................................2.........................................................................................................................3

Really slowly.

**Comment by basrieter** [comment]
Please don't do odd workarounds for Matrix. Be a bit more patient until all add-ons migrate
