### ISSUE TITLE
kan omroep Gelderland niet ontvangen

### ISSUE THREAD

**Issue by HendrikMartinus** [retrospect-addon/plugin.video.retrospect#1331]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [x] Windows UWP

Used versions:
- Kodi version:
- Retrospect version:

**Comment by HendrikMartinus** [comment]
Iedere keer is er een probleem om regionaal omroep Gelderland te ontvangen. Omroep Gelderland zegt dat het bij de provider ligt en de provider zegt dat het in retrospect ligt. Maar al met al kom ik geen millimeter verder. Hoe moet ik nu hier mee aan?

**Comment by HendrikMartinus** [comment]
Iedere keer is er een probleem om regionaal omroep Gelderland te ontvangen. Omroep Gelderland zegt dat het bij de 'provider' ligt en de provider zegt dat het in 'retrospect' ligt. Maar al met al kom ik geen milimeter verder. Hoe moet ik nu hier mee aan?

**Comment by basrieter** [comment]
Wat is nu precies het probleem? Zou je eens rustig uitleggen wat er niet werkt? 

Laat ik ook melden dat Omroep Gelderland geen enkel weet en relatie heeft met Retrospect

**Comment by basrieter** [comment]
Je kunt deze zipfile downloaden en installeren via de "Install from zip" optie in Kodi: https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1331.zip

Laat even weten of dat werkt.

**Comment by basrieter** [comment]
En? Werkt het?

**Comment by HendrikMartinus** [comment]
Misschien is dit overbodig, maar ik wil toch nog even zeggen dat met de nieuwe Add-on zipfile voor Retrospect, Omroep Gelderland prima is te ontvangen, daar ben ik erg blij mee, het is zelfs beter dan vroeger (minder bufferen).
Hartelijk dank

**Comment by HendrikMartinus** [comment]
sorry een foutje ik bedoelde dat ik nog een keer wilde zeggen dat omroep Gelderland weer prima is te ontvangen.
Met vriendelijke groet,
Henk ten Haaken

**Comment by basrieter** [comment]
Graag gedaan! Ik zal dit weekend een nieuwe release proberen te maken
