### ISSUE TITLE
Dplay Cannot Start Playback

### ISSUE THREAD

**Issue by Sigge84** [retrospect-addon/plugin.video.retrospect#1336]
I’ve installed retrospect with latest version 5.1.9 on my Raspberry PI 3

The software installed on the raspberry is LibreELEC 9.2.1. Kodi version is 18.6 leia

When I want to play some videos  in DPLAY (se) I get the following error: Cannot Start Playback.

`2020-03-13 23:04:56.866 T:1588810624   ERROR: Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.retrospect/resources/lib/plugin.py", line 467, in play_video_item
                                                media_item = self.channelObject.process_video_item(media_item)
                                              File "/storage/.kodi/addons/plugin.video.retrospect/resources/lib/chn_class.py", line 414, in process_video_item
                                                return data_parser.Updater(item)
                                              File "/storage/.kodi/addons/plugin.video.retrospect/channels/channel.se/sbs/chn_sbs.py", line 572, in update_video_item
                                                m3u8url = video_info["streaming"]["hls"]["url"]
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
2020-03-13 23:04:56.869 T:1937355328   ERROR: Playlist Player: skipping unplayable item: 0, path `
[kodi.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4331947/kodi.log)
`

**Comment by basrieter** [comment]
No issue here?

**Comment by Sigge84** [comment]
no seem like  u need to regist and pay for the serie i tried with. Before it was free this serie, but it should be written an "o" or "a" when payment is needed. It was not.
When I tried to watch the serie in Dplay they was asking for logon so thats how I find it out.

**Comment by basrieter** [comment]
Ok, what series and episode? So I can check and perhaps add the a or o?

**Comment by Sigge84** [comment]
Dplay
Ex on the beach s07e2-*

/Sigge

14 mars 2020 kl. 00:53 skrev Bas Rieter <notifications@github.com>:

﻿

Ok, what series and episode? So I can check and perhaps add the a or o?

**Comment by basrieter** [comment]
![image](https://user-images.githubusercontent.com/1310443/76681059-ea8dba00-65ee-11ea-92d4-691d195cfd57.png)

According to the API it is both free and premium?

**Comment by Sigge84** [comment]
https://www.dplay.se/program/eotb

I Try to the homepage it says you need to login and cost But you have some different prenumeration.
What I can see it’s boot free.

/Sigge

14 mars 2020 kl. 12:26 skrev Bas Rieter <notifications@github.com>:

﻿

[image]<https://user-images.githubusercontent.com/1310443/76681059-ea8dba00-65ee-11ea-92d4-691d195cfd57.png>

According to the API it is both free and premium?

**Comment by Sigge84** [comment]
You need standard prenumeration “underhållning” and its cost 79kr/month
Premium cost 349kr/month

[cid:248B4C6C-51B8-4822-AAC1-0607950347E3]

/Sigge

14 mars 2020 kl. 12:26 skrev Bas Rieter <notifications@github.com>:

﻿

[image]<https://user-images.githubusercontent.com/1310443/76681059-ea8dba00-65ee-11ea-92d4-691d195cfd57.png>

According to the API it is both free and premium?

**Comment by Snaah** [comment]
From DPlay's webpage it seems the first episode of the season is free, the rest not.

**Comment by Sigge84** [comment]
Yes Thats right

/Sigge

15 mars 2020 kl. 00:33 skrev Snaah <notifications@github.com>:

﻿

From DPlay's webpage it seems the first episode of the season is free, the rest not.

**Comment by orfeous1** [comment]
Fails to play any episodes/programs on Dplay.se

[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4553508/retrospect.log)
