### ISSUE TITLE
NPO Start ondertitels ontbreken bij sommige afleveringen

### ISSUE THREAD

**Issue by Phyxion** [retrospect-addon/plugin.video.retrospect#1338]
## Bug report
Bijvoorbeeld deze aflevering geeft geen ondertitels in Retrospect, maar ze staan wel online:
https://www.npostart.nl/keuringsdienst-van-waarde/12-03-2020/KN_1712996

### To Reproduce
1. Open de broodmix aflevering (die van 12-03-2020) in NPO > Keuringsdienst van Waarde. Hier zijn nu geen ondertitels van, zowel op de RPi als op Windows.

### Debuglog
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4332455/retrospect.-.Copy.log)

### Your Environment
 - [X] Raspberry-Pi
 - [X] Windows

Used versions:
- Kodi version: laatste
- Retrospect version: laatste

**Comment by basrieter** [comment]
Heeft bij mij gewoon subtitles. Graag even:

* debug logging in Retrospect aanzetten
* nogmaals afspelen
* log file uploaden met de ingebouwde functionaliteit van Retrospect
* de paste.kodi.tv link hier posten

**Comment by Phyxion** [comment]
Ik had debug logging al aan en ook al meerdere keren opnieuw geprobeerd af te spelen. Zowel op mijn eigen PC als op de RPi zijn er geen ondertitels (behalve de hardcoded rond 14:30). Misschien dat deze subtitle eerst verkeerd online stond en alsnog uit de cache gebruikt wordt door retrospect? Gezien de paar KB van een subtitle, kan deze misschien sowieso gedownload worden bij het starten van de stream? Als dat om een of andere manier niet lukt dan kan die uit de cache gebruikt worden. En als de srt leeg is lijkt mij dat ook een goed idee.

https://paste.kodi.tv/hovesecoco

**Comment by basrieter** [comment]
Hij laadt wel degelijk een subtitle. Ik mis een stukje log. Zou je er nog een kunnen maken?

**Comment by Phyxion** [comment]
Nog een poging:
http://paste.kodi.tv/oxajapupav
Heb het subtitle bestand in de cache folder even bekeken en het is een leeg bestand.

**Comment by basrieter** [comment]
Gooi die file eens weg? Want hij gaat die gewoon daar uit blijven halen.

**Comment by Phyxion** [comment]
Ik heb nu op mijn PC na het verwijderen weer ondertitels 🙂

Dit dan een idee?
> Gezien de paar KB van een subtitle, kan deze misschien sowieso gedownload worden bij het starten van de stream? Als dat om een of andere manier niet lukt dan kan die uit de cache gebruikt worden. En als de srt leeg is lijkt mij dat ook een goed idee.

**Comment by basrieter** [comment]
Ok, dan ga ik nog wat inbouwen om dit te voorkomen. Denk dat het een keer fout is gegaan en hij dus een lege sub heeft opgeslagen.

**Comment by basrieter** [comment]
Kan je deze proberen: https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1338.zip

Het zou dus gewoon moeten blijven werken zoals het hoort. Als er nu een lege subtitle is, dan wordt deze niet gecached.

**Comment by Phyxion** [comment]
Ik heb de verkeerde subtitle even teruggezet maar het werkt nog niet. Hij blijft de bestaande uit de cache gebruiken.

**Comment by basrieter** [comment]
Hij gaat nu lege niet meer opslaan. Dus het probleem zou niet meer moeten ontstaan. Zou je mij die lege file hier kunnen toevoegen? Ik bouw nog wel wat in dat ie op filesize gaat checken.

**Comment by Phyxion** [comment]
Ah, ik dacht dat ie een nieuwe zou downloaden als er een verkeerde subtitle instond. 

[KN_1712996.nl.srt.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/4334020/KN_1712996.nl.srt.txt)

**Comment by basrieter** [comment]
Ik heb even snel gekeken, maar de file is niet helemaal leeg. De aanpassingen gaan er wel voor zorgen dat deze nooit meer gecached gaan worden zodat je niet vast komt te zitten in de situatie waar je nu in zit.

**Comment by Phyxion** [comment]
Super, bedankt 👍
