### ISSUE TITLE
Categories and TV Shows in TV4 Play

### ISSUE THREAD

**Issue by maxruben** [retrospect-addon/plugin.video.retrospect#1340]
### Is your feature request related to a problem? Please describe

Not all categories are present in channel  TV4 Play compared with the  web (tv4play.se). "Samhälle & fakta" is not present in Retrospect. Some of the shows in this category is not present at all under the "TV Shows" menu. For instance "Världens bästa veterinär" and any of the shows "112 - luftens hjältar", "112 - Poliser" and "112 - På liv och död" and more.

They can be found with the Search function. However searching for "veterinär" brings up "Error receiving the list of items.". A a search for "världens bästa" finds "Världens bästa veterinär" but it is kind of a nuisance to do a search every time I want to watch some of these shows.

It also looks like the categories in Retrospect doesn't exactly match the web categories.

The missing tv shows do however appear under the programs for the latest days.

It would also be nice to be able to go from the programs under one of the menus with programs for the latest  latest days or a search to the same program in "TV Shows". 

### Describe the solution you'd like

Match the content in tv4play.se on the web with the content in Retrospect regarding categories and TV Shows.

### Additional context

Not sure if this perhaps should be filed under Bug instead of Enhancement?

**Comment by basrieter** [comment]
Where can I find all the categories for TV4 online?

**Comment by maxruben** [comment]
In the top menu there is a dropdown list:
Here is the link for "Samhälle och fakta": https://www.tv4play.se/kategori/samh%C3%A4lle-och-fakta
All programs are also listed in the "Alla Program from the "Program A-Ö" menu: https://www.tv4play.se/alla-program

![image](https://user-images.githubusercontent.com/12049523/76727353-17a7ad00-6754-11ea-8661-87d950a7a9ec.png)

Thanks / Ruben

**Comment by Snaah** [comment]
The reason for those programs not being found in the regular listings for TV4 is that Retrospect presently does not have a "TV4-gruppen/TV4 Media" channel as for DPlay and Viafree. TV4, Sjuan and TV12 show the listings of programs depending on what channel they are aired on. The "112..." programs are under Sjuan. "Världens bästa veterinär" are nowhere. The search function, however, searches for programs on all the channels. See also the request for a separate channels for all of TV4 Media: https://github.com/retrospect-addon/plugin.video.retrospect/issues/965.

Searching for "veterinär" gives an error here too.

**Comment by basrieter** [comment]
Looking into this, but it seems that Sjuan and TV11  no longer have seperate pages. TV4 is moving over to another API. 

Please test this zip (install from zip): https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1340.zip

TV4 now uses the new API and the same categories as the site. I did not change Sjuan and TV11

**Comment by matsarv** [comment]
I made a quick check and found one error.
If I goto "Kategorier / Serier" in TV4 Play I will not get any program list.

Found this in log file: cachehttpadapter.py  - 60   - Error storing cache for https://.......
Logfile: [retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4363731/retrospect.log)
Bodyfile: [45c4ac1a464638dbc42489d23db67b71.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/4363777/45c4ac1a464638dbc42489d23db67b71.txt)



PS. Thanks for the new speed of lisrting items in Retrospect, good work.

**Comment by basrieter** [comment]
Can you delete the folder `C:\Users\user\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.retrospect\cache\www\` and try again?

**Comment by matsarv** [comment]
No error in logfile but no program list for "Kategorier / Serier"
Logfile: [retrospect2.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4363823/retrospect2.log)

**Comment by Snaah** [comment]
I can confirm all categories but "Serier" work now. Searching for "veterinär" works too and "Världens bästa veterinär" is in the listings.

Well done, @basrieter !

But now TV4 is like that proposed "TV4 Media" channel. Are you saying it won't be possible to sort out which programs are aired on TV4, Sjuan and TV12 in the future? If it still is, then why not make this the new channel "TV4 Media" and a channel TV4 just like it was, with only programs aired on TV4? CC: @Sopor (https://github.com/retrospect-addon/plugin.video.retrospect/issues/965)

Oh, while you're at it with TV4, maybe also do https://github.com/retrospect-addon/plugin.video.retrospect/issues/1317? It's quickly done.

**Comment by maxruben** [comment]
Yes it seems to be working now. Thanks for the great work.

I also have no programs under the category "Serier". Could it be because TV4Play assigns programs to more categories than those existing in the Categories (Kategorier) list? There are for example the categories "Drama", "Deckare", "Mat & bakning", "Livsstil", "Nöje", "Hem & fritid" besides those in the categories list in the main menu and no actual show is listed under the "Serier" category.

Thanks again / Ruben

**Comment by matsarv** [comment]
I had a look at the JSON and maybe it's better to create the Category folder list using the 
category/name from program JSON. This will give 13 categories.
![kategori](https://user-images.githubusercontent.com/46671821/77252798-9cb02c00-6c56-11ea-95fb-4333675d2d95.png)

**Comment by basrieter** [comment]
> I had a look at the JSON and maybe it's better to create the Category folder list using the
> category/name from program JSON. This will give 13 categories.
> ![kategori](https://user-images.githubusercontent.com/46671821/77252798-9cb02c00-6c56-11ea-95fb-4333675d2d95.png)

That won't work, as I need the ID for a category, not the name. 

The problem with the `series` is that the GraphQL response keeps changing. That an issue at their end I think. Let me check a bit more.

**Comment by basrieter** [comment]
Hmmm, seems like they reverted to the older system for series. Weird. Going to wait for a bit here, before they change their mind again and my new code becomes useless again.

**Comment by EnPajk** [comment]
Any updates on this? It would be nice to see all categories and shows. As of now some shows are only found via Search.

**Comment by basrieter** [comment]
> Any updates on this? It would be nice to see all categories and shows. As of now some shows are only found via Search.

Good question. I think they settled on the API for now. The new API now provides the correct categories, but there seems to be a different response for Series compare to the others. Need some more time.

**Comment by basrieter** [comment]
So I checked again. The issues lies with https://www.tv4play.se/kategori/serier which is not a real category and this it won't show up as the TV4 api. If I add it, it does not contain any shows/videos. I think I will remove that category. Agree?

**Comment by EnPajk** [comment]
An empty category is of course not so nice to have. But both on the website and in the app there are Serier with content, so it would be nice to see it. The app also has much more categories than the website, like Hus & hem, Livsstil, Deckare and so on.

**Comment by basrieter** [comment]
Is this the full list of categories?

- Deckare
- Djur
- Dokumentärer
- Drama
- Humor
- Hus & hem
- Livsstil
- Mat & bakning
- Nöje
- Relationer
- Samhälle & fakta
- Serier
- Sport
- Övernaturligt

**Comment by EnPajk** [comment]
Yes, that is the full list in the app.

**Comment by basrieter** [comment]
Ok, then I think I can make it work.

**Comment by basrieter** [comment]
Please download https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1340.zip again and "Install from zip" to test the latest version. I my opinion this the best solution I can find.

**Comment by EnPajk** [comment]
I am happy with this solution. All shows I looked for could be found easy.
Will you remove Sjuan and TV12 now that everything is included under TV4?

**Comment by basrieter** [comment]
> I am happy with this solution. All shows I looked for could be found easy.
> Will you remove Sjuan and TV12 now that everything is included under TV4?

No, I don't think so. I need to filter those that do not belong to TV4.

**Comment by basrieter** [comment]
> > I am happy with this solution. All shows I looked for could be found easy.
> > Will you remove Sjuan and TV12 now that everything is included under TV4?
> 
> No, I don't think so. I need to filter those that do not belong to TV4.

I checked, but I can no longer filter out other items because that info is no longer present in the API

**Comment by EnPajk** [comment]
I am not surprised since both the website and the app shows everything together now.

**Comment by basrieter** [comment]
Should I remove the other two channels then? It's fairly easy.

**Comment by EnPajk** [comment]
Yes, I think those should be removed. They do not provide any additional shows so what is the point of keeping them?

**Comment by matsarv** [comment]
Really nice work!

I agree that the Sjuan and TV12 could be remove now.
You can allways change the description for TV4 Play to inform endusers.

chn_tv4se.json, replace line 6
from:
` "description": "Sändningar från TV4Play.se.",`
to:
`"description": "Sändningar från TV4Play.se\n\nInnehåller kanalerna TV4, Sjuan och TV12",`


**I have a request for change:** 
To get the TV-show name in the thumb images for the TV program folders. This is how the thumbs is shown in latest Release. (also used in other channels)


chn_tv4se.py, replace line 334
from:
`#item.thumb = (result_set.get("images", {}) or {}).get("main16x9")`
to:
`item.thumb = result_set.get("image")`


Before:
![before2](https://user-images.githubusercontent.com/46671821/88102268-8d5ad400-cb9f-11ea-81b0-c6e5592ef487.png)

After:
![after1](https://user-images.githubusercontent.com/46671821/88102497-ef1b3e00-cb9f-11ea-9ebf-bcce918651b0.png)

**Comment by Snaah** [comment]
@basrieter With your zip, I programs of Sjuan, TV12 and TV4 are distinguishable by Retrospect. TV4 show categories and each channel show their program.

I **oppose** not keeping Sjuan and TV12. Instead, go ahead with the solution for https://github.com/retrospect-addon/plugin.video.retrospect/issues/965. Add an extra _[TV4 Media](https://sv.wikipedia.org/wiki/TV4_Media)_ channel, just like you did with DPlay and Viafree. A user can always disable showing Sjuan and TV12.

**Comment by basrieter** [comment]
Let me check. What would the name of that channel, with all TV4 Gruppen channel, be?

**Comment by matsarv** [comment]
My suggestion is to use TV4 Play for the TV4 Group channels (as it is on the web and on the phone app) and then use only TV4, Sjuan and TV12 for the separate channels (if it's possible to separate them).

**Comment by basrieter** [comment]
I think it should be ok now: https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1340.zip

I kept TV4, Sjuan and TV12 like it was before, but they only show the TV Shows and no categories and so. 'TV4 Group' is now added as a new channel that contains the combined data and the special folders such as Categories.

**Comment by matsarv** [comment]
Tested and everything works ok.

As for the name for the new combined channel my suggesting was not so clear, sorry. I was mening that the channel could just be named "TV4 Play". I think that should just be enough as you have the new description. You decide.....

**Comment by basrieter** [comment]
I updated the name and some other minor things: https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1340.zip

This should be all OK now?

**Comment by matsarv** [comment]
Everyting is OK!

Just a small description change in chn_tv4se.json, row 6
from:
`      "description": "Sändningar från TV4Play.se.",`
to:
`      "description": "Sändningar från TV4 (TV4Play.se).",`

**Comment by basrieter** [comment]
You have an eye for details. Changed it to be consistent with Sjuan and TV12.

**Comment by Snaah** [comment]
Great! Working fine here.

I think _TV4 Play for the TV4 Group Channels_ is way too long as a channel name. It looks bad in some views. I agree with @matsarv - just "TV4 Play" works. If you want to have a distinguishing name, maybe "TV4 Play (all channels)"?

**Comment by basrieter** [comment]
If you re-download the latest zip file the name should be changed already.

And the other thing is on purpose: ”TV4 Play” has all the specials. TV4, Sjuan and TV12 just the listing. As with the new API it is no longer possible to filter on channels for the special folders such as the Categories.

**Comment by basrieter** [comment]
Shall I merge this into master like this? @maxruben @Snaah  @matsarv @EnPajk

**Comment by matsarv** [comment]
It's ok to merge from my side

**Comment by maxruben** [comment]
> Shall I merge this into master like this? @maxruben @Snaah @matsarv @EnPajk

Ok for me.
Thanks again for the awesome work!

/Ruben

**Comment by Snaah** [comment]
Sorry, Bas, I missed that part.

A last minute suggestion. Change the description text to:
_Swedish:_
"Innehåller kanalerna TV4, Sjuan och TV12**. Här kan du också söka, lista mest visade avsnitt, se kategorier, livesändningar och  lista program utifrån veckodag.**

_English:_
"Contains the channels TV4, Sjuan and TV12**. Here you can also search, list most viewed episodes, see categories, view live broadcasts and list programs by weekday.** 

Otherwise looking good! Tremendous work as always, @basrieter !

**Comment by basrieter** [comment]
Official zip's are here. It will also be in the next release via the Kodi repository.

Leia: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-leia.zip
Matrix: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-matrix.zip
