### ISSUE TITLE
HTML opmaak filteren AT5 kanaal vervolg

### ISSUE THREAD

**Issue by didamsko** [retrospect-addon/plugin.video.retrospect#1343]
Deze is verwant aan mijn eerdere melding: https://github.com/retrospect-addon/plugin.video.retrospect/issues/1292

Ik heb vandaag een oudere mediaspeler opnieuw geïnstalleerd en bijgewerkt en toen zag ik dat ik een veld over het hoofd had gezien ivm met de HTML opmaak die in beeld komt in de beschrijvingen op het AT5 kanaal. Ik ga normaal altijd meteen via de Favorieten direct naar het item "AT5 Nieuws" maar nu zag ik de volledige lijst van het AT5 kanaal weer eens en daar zit dus nog een beschrijvings-veld in waar de HTML opmaak nog niet uitgefilterd is:  

![IMG_8022](https://user-images.githubusercontent.com/60958082/77123459-7d3fb600-6a40-11ea-8e70-4cb3063cafce.JPG)

![IMG_8027](https://user-images.githubusercontent.com/60958082/77123469-82046a00-6a40-11ea-962a-6d07c0112707.JPG)

Kan je deze ook onder handen nemen?

**Comment by basrieter** [comment]
Fixed it. You can downloaded the lastest master (https://github.com/retrospect-addon/plugin.video.retrospect/archive/master.zip) and use the install from zip in Kodi.

**Comment by didamsko** [comment]
Thanks Bas! Issue fixed indeed!
