### ISSUE TITLE
Play programs from Ketnet doesn't work

### ISSUE THREAD

**Issue by peno64** [retrospect-addon/plugin.video.retrospect#1344]
### Describe the bug

Playing something from Ketnet does not work

## Expected Behavior

It should play

## Actual Behavior

A retrospect error is given: cannot start playback

### To Reproduce

1. Start retrospect
2. Go to National, Ketnet, De smurfen
3. Play one of the episodes there

### Debuglog

The **debug** retrospect.log can be found here: https://paste.kodi.tv/owuxaxupox.kodi

The debug kodi.log can be found here: https://paste.kodi.tv/mafucituhe.kodi

## Additional context or screenshots (if appropriate)

Note that there are episodes in here that are not on vrt.nu (it also has a De smurfen folder but it contains other episodes and these play). Also note that the addon vrt.nu also sees those same episodes from ketnet and it can also play them so there is no issue with the site.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi 4
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.5 and 18.6
- Retrospect version: 5.2.0

**Comment by basrieter** [comment]
Ok, I think I fixed it. Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1344.zip and use the "install from zip" option.

**Comment by peno64** [comment]
Works great. Thanks

**Comment by basrieter** [comment]
Zou je ook VRT Nu even kunnen kijken? Die maken nu gebruik van dezelfde logica.

**Comment by peno64** [comment]
"Zou je ook VRT Nu even kunnen kijken? Die maken nu gebruik van dezelfde logica." Ik ben momenteel het journaal vanuit vrt nu aan het kijken en dat is ok. Is dat voldoende?

**Comment by basrieter** [comment]
Top thanks! Een nieuwe versie kan je hier downloaden: https://github.com/retrospect-addon/plugin.video.retrospect/archive/master.zip

Zal deze week ook een officiële update doen.
