### ISSUE TITLE
NPO Start > Zembla > Retrospect - Error, Error retrieving the list of items.

### ISSUE THREAD

**Issue by didamsko** [retrospect-addon/plugin.video.retrospect#1345]
### Describe the bug

Trying to start the "NPO Start" program "Zembla" results in a "Retropsect - Error, Error retrieving the list of items."

## Expected Behavior

Till not so long ago "Zembla" could be played via Restrospect, it still can be played via NPO Start itself.

## Actual Behavior

 "Retropsect - Error, Error retrieving the list of items."

### To Reproduce

1. open: Retrospect
2. go to: NPO Start > TV Shows (A-Z) > Z
3. start: Zembla

### Debuglog

The **debug** retrospect.log can be found here: https://paste.kodi.tv/kagoyaruxo

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: OSMC running Kodi 18.5
- Retrospect version: 5.2.0

**Comment by basrieter** [comment]
Ok, Zembla had missing titles. Please install this zip via "Install from zip" https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1345.zip and try again.

**Comment by didamsko** [comment]
Thanks Bas! That fixed it, Zembla is working again
