### ISSUE TITLE
vrt nu does not show all episodes

### ISSUE THREAD

**Issue by peno64** [retrospect-addon/plugin.video.retrospect#1351]
### Describe the bug

vrt nu does not show all episodes.

## Expected Behavior

All episodes should be shown

## Actual Behavior

Via retrospect I see less episodes for a given series compared to the addon vrt.nu

### To Reproduce

1.  Go to VRT NU
2. Titles with 'D'
3. "De smurfen"
4. Only the episode "Smurfin de waarzegster" is shown
5. When I do this with the addon vrt nu, I see 7 episodes among the episode "Smurfin de waarzegster". One of the episodes is only 7 more minutes available but the others are all still 2 days there.

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/wufesafaku.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi 4 on libreelec
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.6
- Retrospect version: 5.2.1

**Comment by basrieter** [comment]
Examples please. Shows and missing videos.

**Comment by peno64** [comment]
examples, there are plenty... For example:

- De smurfen (showing 1 from 6)
- Axel Nort (showing 1 from 16)
- De collega's (showing 10 from 12) 
.
.
.

But others are ok. For example:

- Er was eens (showing 6 from 6)
- F.C . De kampioenen (showing 4 from 4)
.
.
.

**Comment by peno64** [comment]
Another example is "De Zoo":

In de addon vrt nu:

![image](https://user-images.githubusercontent.com/32430988/78269131-72d5ef80-7509-11ea-92d9-cbab01a9f212.png)

In retrospect:

![image](https://user-images.githubusercontent.com/32430988/78269093-681b5a80-7509-11ea-8beb-7bd7c6f425cc.png)
