### ISSUE TITLE
Swedish Dplay.se, shows no episodes

### ISSUE THREAD

**Issue by orfeous1** [retrospect-addon/plugin.video.retrospect#1361]
Trying to watch "Peter Forsberg....." on Dplay.se but retrospect does not show any episodes.
Just that there is no.

On dplay.se's website i can get to "Peter Forsberg..." and see the actual episode and play it.
No issues there.

Attaching logfile.
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4527374/retrospect.log)

**Comment by basrieter** [comment]
Please try this version: https://github.com/retrospect-addon/plugin.video.retrospect/archive/266cb4a77758af8e739f47a0f08bec862f85cdc6.zip 

You can install it via the "install from zip" option. **Keep in mind that this version is only for Kodi Leia and NOT Matrix.**

**Comment by orfeous1** [comment]
I guess someone else can try then since im not on Leia.

**Comment by basrieter** [comment]
wait, let me fix that for you

**Comment by basrieter** [comment]
[retrospect-1361.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4531115/retrospect-1361.zip)

**Comment by orfeous1** [comment]
Thank you!
Works really well!

**Comment by basrieter** [comment]
You can download the latest Matrix build here: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-matrix.zip
