### ISSUE TITLE
No subtitle in Swedish Viafree for some TV-shows

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1362]
### Describe the bug

No subtitle in Viafree for some TV-shows.
I have found this in Navy CIS and NCIS: New Orleans so far.

## Expected Behavior

Show subtitle

## Actual Behavior

No subtitle

### To Reproduce

1.  Select Swedish Viafree
2.  Select Navy CIS
3.  Start the tv-show

### Debuglog

The **debug** retrospect.log can be found here:
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4533117/retrospect.log)

## Additional context or screenshots (if appropriate)

In the folder plugin.video.retrospect\cache\www I found a .body file that contains the subtitle:
[b41813499e4411b0a811e17581b4bbc9.body.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/4533127/b41813499e4411b0a811e17581b4bbc9.body.txt) 

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.6
- Retrospect version: 5.2.2

**Comment by basrieter** [comment]
I think the cache is corrupted. Please clear it. I added an option for that in Retrospect: go to `Add-on setttings -> Advanced -> Clean-up cache & Cookies` and try again.

**Comment by matsarv** [comment]
Did not work.
The debug retrospect.log and retrospect.old.log can be found here:
[retrospect-logs.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4534312/retrospect-logs.zip)

**Comment by basrieter** [comment]
Found it. Please try this version: https://github.com/retrospect-addon/plugin.video.retrospect/archive/28391d541480e0e0189191f47a18238c4f913e12.zip

You can "install from zip" this on Kodi Leia.

**Comment by matsarv** [comment]
Thanks!
It's working now.
