### ISSUE TITLE
Unable to add favorites after an empty list of favorites was shown

### ISSUE THREAD

**Issue by Sopor** [retrospect-addon/plugin.video.retrospect#1365]
### Describe the bug

First i select Channel favorites. This will show a error message "no favorites available". If i now select "Add to favorites" it will bring up that check log files.

### To Reproduce

1. Open channel favorites (mine was empty and i believe that is making it fail later).
2. I then open the context menu again but this time i selected add to favorites.
3. Now i get this check log files message

### Debuglog

The **debug** retrospect.log can be found here:
https://pastebin.com/6M7QuQ1H

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.6
- Retrospect version: 5.2.2

**Comment by basrieter** [comment]
Please try this one: https://github.com/retrospect-addon/plugin.video.retrospect/archive/14236c3e3785d69daeb363fd9ba5ed0610468d63.zip

**Comment by Sopor** [comment]
I did some testing and it seems to work now.
