### ISSUE TITLE
Intermittently unable to list "Senaste" in SVT

### ISSUE THREAD

**Issue by walleboom** [retrospect-addon/plugin.video.retrospect#1369]
### Describe the bug

Now and then I just get an error toast informing me that Retrospect is unable to receive the program list.

## Expected Behavior

The list should be loaded.

## Actual Behavior

The list does not load.

## Possible Fix

From my debugging it seems that timestamps from the API-request/some other code, sometimes comes in UTC instead of DateTimeOffsets. The format string to DateTimeHelper.get_datetime_from_string does not account for this.

Maybe just remove Z from expire_date?
chn_svt.py:1036
```
expire_date = expire_date.split("+")[0].replace("T", " ").replace("Z", "")
```

Would probably be more clean to handle both UTC and DateTimeOffsets?

### To Reproduce

1. Open SVT-play
2. Try once in a while for some hours to open "Senaste"
3. Profit

### Debuglog

The **debug** retrospect.log can be found here:
https://pastebin.com/HKDdRHn6

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.6
- Retrospect version: 5.2.2

**Comment by basrieter** [comment]
I see, some timestamps are in UTC, not +02:00. That sucks, I will need to see if I can fix this.

**Comment by walleboom** [comment]
> I see, some timestamps are in UTC, not +02:00. That sucks, I will need to see if I can fix this. You fix will remove the error, but will result in an invalid time.

Ye, it was just quick and dirty.. :) Thus:

> Would probably be more clean to handle both UTC and DateTimeOffsets?

**Comment by basrieter** [comment]
Do you have some examples that fail? The essential stuff to reproduce the issue seems to have been cut from the log.

**Comment by walleboom** [comment]
SVT -> "Mest sedda avsnitt", 2 minutes ago:
https://pastebin.com/wyNQim6Q

**Comment by walleboom** [comment]
Request URL
https://api.svt.se/contento/graphql?ua=svtplaywebb-play-render-prod-client&operationName=GridPage&variables=%7B%22selectionId%22%3A%20%22popular%22%7D&extensions=%7B%22persistedQuery%22%3A%20%7B%22version%22%3A%201%2C%20%22sha256Hash%22%3A%20%22265677a2465d93d39b536545cdc3664d97e3843ce5e34f145b2a45813b85007b%22%7D%7D

Response JSON
https://pastebin.com/j8UFWuDF

Item 25: 
```
"validTo" : "2020-11-05T22:59:59Z"
```

**Comment by basrieter** [comment]
Please try this version: https://github.com/retrospect-addon/plugin.video.retrospect/archive/81356e959738ae507fca50c77fe97d4e6b42a9ba.zip 

It can be installed from zip in Kodi Leia.

**Comment by Snaah** [comment]
I experience the same behavior on Android TV for SVT, but on any listings - the main of programs, of specific programs. Trying a couple of times it works. On Windows it works flawlessly. Just wanted to let you know @basrieter I'm not at home to test the fix now. Will do tomorrow.

**Comment by Snaah** [comment]
Wow! I just updated my ATV installation, and this really did it. Now there's no like the above and the listings are much faster. Thanks a lot @basrieter !
