### ISSUE TITLE
Stievie Premium: aired shows support

### ISSUE THREAD

**Issue by SlevinBE** [retrospect-addon/plugin.video.retrospect#1373]
### Is your feature request related to a problem? Please describe
Since Retrospect v5.1.9 the aired shows of Stievie Premium are not available anymore (ref: https://github.com/retrospect-addon/plugin.video.retrospect/issues/1310). While Stievie Free became VTM GO, Stievie Premium is still available with all previous features.

### Describe the solution you'd like
It would be great if support for aired shows in Stievie Premium could be added again.

### Additional context
<img width="1519" alt="stievie-premium-shows" src="https://user-images.githubusercontent.com/481541/81441570-4e0d1180-9172-11ea-9e31-074cb5fb6355.png">

**Comment by basrieter** [comment]
I would require access to a premium account to create and test such a feature. Logging in is already present. So I would need to verify the rest.

**Comment by SlevinBE** [comment]
Hey Bas, I can provide my access. Let me know how you would like to receive the details.

**Comment by SlevinBE** [comment]
Hey Bas, I donated 15€ via paypal so you can take Stievie Premium for a month at any time you want. Given that they only support one concurrent stream, this is probably the easiest for both you and me. :-)

**Comment by basrieter** [comment]
Thanks! I will look into this.

**Comment by basrieter** [comment]
Apparently I need a Belgium adres for a Premium account and Belgium phone number. The latter is the main issue :(

**Comment by SlevinBE** [comment]
send you an email ;-)

**Comment by SlevinBE** [comment]
Stievie Premium is stopping its operations (ref: https://www.stievie.be), so this feature won't be necessary anymore.
