### ISSUE TITLE
Geen NOS Live (Could not start playback due to missing streams.)

### ISSUE THREAD

**Issue by BrodjagaRatnik** [retrospect-addon/plugin.video.retrospect#1374]
### Describe the bug

Als ik een programma op NOS wil kijken krijg ik "The selected item has no stream" fout melding. Heb retrospect + Widevine handmatig verwijdert en opnieuw geinstaleerd (verschillende keren).

## Expected Behavior

Dat programma dat geselecteerd is ook bekeken kan worden

## Actual Behavior

Krijg fout "The selected item has no stream" melding

### Debuglog

The **debug** retrospect.log can be found here: https://paste.kodi.tv/iboliqiriq.kodi
### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: v18.6 "Leia"
- Retrospect version: v5.2.3
- LibreELEC release: RPi4.arm-9.2.1

**Comment by basrieter** [comment]
Hmm, I see. Will try to fix it.

**Comment by basrieter** [comment]
Please try this version (you can install from zip): https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1374.zip

**Comment by ndoornhn** [comment]
Works again!

**Comment by BrodjagaRatnik** [comment]
Yes works again Ty.

**Comment by basrieter** [comment]
Waiting for it be in Kodi

https://github.com/xbmc/repo-plugins/pull/2904
https://github.com/xbmc/repo-plugins/pull/2905

**Comment by basrieter** [comment]
Just opening to prevent more duplicates 😢

**Comment by basrieter** [comment]
Updates is merged into the Kodi repository. It should be dripping in soon.

**Comment by northlaender** [comment]
Works! thanks @basrieter
