### ISSUE TITLE
No NPO streams: The selected item does not have a stream...

### ISSUE THREAD

**Issue by mvmsoft** [retrospect-addon/plugin.video.retrospect#1375]
### Describe the bug

When I start f.i. NPO 1 RS fails with a message about a non-existant stream (or something like that). This is so for all NPO Start streams it seems. Yesterday I had the same issue, but after a while the streams were running as expected. Maybe it's very busy at NPO??

## Expected Behavior

Play the stream

## Actual Behavior

An error message appears: The selected item does not have a stream...

### To Reproduce

1.  Start Retrospect
2.  Choose NPO Start
3.  Choose one of the provided channels

### Debuglog

The **debug** retrospect.log can be found here:
The name of the log:
qixuzugele
### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [x ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.6
- Retrospect version: 5.2.3

**Comment by JapieJoo** [comment]
Same here!

- Kodi: 18.6
- Retrospect version: 5.2.3
- Windows 10

**Comment by basrieter** [comment]
Search #1374

**Comment by basrieter** [comment]
I will get a fix in soon.

**Comment by mvmsoft** [comment]
Thanx and: sorry. It works now.

**Comment by basrieter** [comment]
Updates is merged into the Kodi repository. It should be seeding the mirrors and arrive at Kodi installations soon.
