### ISSUE TITLE
NPO: no stream found

### ISSUE THREAD

**Issue by dleeuw** [retrospect-addon/plugin.video.retrospect#1376]
Since a couple of day  Restrospect refuses to play anything from NPO websites. It claims there is a missing stream, see log below. If anybody has a clue or a pointer to the problem. It would be much appreciated, because I have no idea where to start.

Thanks in advance,
Dennis Leeuw

[edit]

**Comment by basrieter** [comment]
Don't paste logs. Attach please. And search items: #1375 and #1374 

https://github.com/xbmc/repo-plugins/pull/2904
https://github.com/xbmc/repo-plugins/pull/2905

**Comment by basrieter** [comment]
Updates is merged into the Kodi repository. It should be seeding the mirrors and arrive at Kodi installations soon.
