### ISSUE TITLE
Recent lijst Kijk.nl

### ISSUE THREAD

**Issue by kengithub9** [retrospect-addon/plugin.video.retrospect#1377]
### What Channel would you like to add and why?
Zou de recent lijst weer terug kunnen komen bij Kijk.nl nu hebben we alleen A t/m Z.

### Provide some details for the channel
- Name of the channel in English: Kijk.nl
- Name of the channel in native language: 
- Website for the channel:
- If available link to the Android app for the VOD content of channel:
- Link to the logo of the channel
 
### Check which features should be implemented
- [ ] Video on-demand content
- [ ] TV live streams
- [ ] Use your account for the VOD services from Retrospect
- [ ] Access the premium content if you are eligible

**Comment by basrieter** [comment]
Volgens mij is deze toch aanwezig:

![image](https://user-images.githubusercontent.com/1310443/81809708-127f9800-9522-11ea-8ef5-a308e59dd39e.png)

![image](https://user-images.githubusercontent.com/1310443/81809746-24613b00-9522-11ea-82e2-da114dececfc.png)

Een volledige lijst met alle "recente" items bestaat niet meer. Ook niet op kijk.nl voor zo ver ik heb kunnen vinden.

**Comment by kengithub9** [comment]
Helaas bij mij niet vanaf versie 5.2.2. zie ik dit
![20200513_150029](https://user-images.githubusercontent.com/56362494/81815637-83c34900-952a-11ea-90d5-15a01c44244a.jpg)
Bij versie 5.2.1. is jouw versie van de lijst nog te zien. Ik heb het getest op zowel CoreElec 9.2.2. en via windows 10 Kodi 19.

**Comment by basrieter** [comment]
En als je de groepering uitschakelt? Dan kan via de Retrospect instellingen. Ik denk dat daar iets niet goed zit dan.

**Comment by kengithub9** [comment]
Door de groepering uit te schakelen is het probleem opgelost. Bedankt hiervoor, nu werkt het terugkijken een stuk makkelijker.

**Comment by basrieter** [comment]
Dan ga ik dat nog even fixen.....vergeet wel vaker. Heb namelijk zelf de groepering altijd uit staan.

**Comment by basrieter** [comment]
Bij deze een versie om te testen. Je kunt het via "install from zip" installeren onder **Kodi Leia**. Ze zouden er dan ook weer bij moeten staan als je de groepering aan zet. 

https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1377.zip

Heb je een Kodi Leia om te testen?

**Comment by kengithub9** [comment]
Ik heb Kodi Leia ook, ik ga het testen.

**Comment by kengithub9** [comment]
Je aanpassing werkt met de groepering aan is het nu ook zichtbaar
![20200513_155923](https://user-images.githubusercontent.com/56362494/81821938-cd179680-9532-11ea-8d59-b6bc3cde64a9.jpg)

**Comment by basrieter** [comment]
Mooi zo. Ga ik het mergen.

**Comment by basrieter** [comment]
Zip's zijn beschikbaar:

Leia: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-leia.zip
Matrix: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-matrix.zip
