### ISSUE TITLE
vrt nu doesn't work anymore & the solution

### ISSUE THREAD

**Issue by peno64** [retrospect-addon/plugin.video.retrospect#1379]
Since yesterday, vrt nu doesn't work anymore. This is not a retrospect issue but a change on the vrt site which asks one time to confirm your login information and without doing this it is not possible to play the streams.

So the solution is simply do a login on vrt nu on your computer with your webbrowser and confirm the questions that are asked and after that everything works again.

**Comment by basrieter** [comment]
Ok, so I will add that as a "Start-up message". Just out of curiosity: is an account required now?

**Comment by peno64** [comment]
As far as I know it was already required. Anyway if I empty the login data from vrt nu I cannot play anything. So it is for sure required now

**Comment by peno64** [comment]
Strange...
When I entered my credentials again it also didn't want to play anything until I restarted kodi so then I tried again to remove the credentials and restart kodi and indeed it does play...

**Comment by basrieter** [comment]
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1379.zip

VRT.nu introduced some extra checks

**Comment by basrieter** [comment]
@peno64 did you have a chance to look at the fix?

**Comment by peno64** [comment]
Problem is that I already logged in on the vrt nu site and entered my information so I can't simulate the problem anymore

**Comment by basrieter** [comment]
But there was also an issue in Retrospect itself whenever the session expired. Can you clear the Retrospect cache (from the add-on settings) try playing something.

**Comment by peno64** [comment]
I cleared the cache and played something and that worked.
I also tried again to remove my vrt nu credentials, clear that cache and cookies and tried again to play something from vrt nu and now it can't play. It gives a popup message "Could not log on to the selected channel." So probably my credentials were still in cache/cookies before when I cleared them. So this confirms again that credentials are needed on vrt nu..
Then I entered the credentials again, cleared cache/cookies and tried to play but then I get a retrospect error with a message to check the log which gives: 

20200519 11:53:00 - [CRITICAL] - addon.py             - 73   - Error running plugin
20200519 11:53:00 - [CRITICAL] - addon.py             - 73   - | Traceback (most recent call last):
20200519 11:53:00 - [CRITICAL] - addon.py             - 73   - |   File "C:\Users\mail\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\addon.py", line 63, in run_addon
20200519 11:53:00 - [CRITICAL] - addon.py             - 73   - |     p.run()
20200519 11:53:00 - [CRITICAL] - addon.py             - 73   - |   File "C:\Users\mail\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\plugin.py", line 165, in run
20200519 11:53:00 - [CRITICAL] - addon.py             - 73   - |     addon_action = VideoAction(self, channel_object)
20200519 11:53:00 - [CRITICAL] - addon.py             - 73   - |   File "C:\Users\mail\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\actions\videoaction.py", line 30, in __init__
20200519 11:53:00 - [CRITICAL] - addon.py             - 73   - |     raise ValueError("No MediaItem to play")
20200519 11:53:00 - [CRITICAL] - addon.py             - 73   - + ValueError: No MediaItem to play
20200519 11:53:00 - [INFO    ] - addon.py             - 74   - Retrospect :: Flushing and closing logfile.
20200519 11:53:19 - [INFO    ] - addon.py             - 35   - XOT Logger :: Appending Existing logFile
20200519 11:53:20 - [INFO    ] - addonsettings.py     - 418  - Setting language from None to English
20200519 11:53:20 - [INFO    ] - urihandler.py        - 63   - Initialised: UriHandler [id=1589882000, useCaching=Cache store [C:\Users\mail\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.retrospect\cache\www], ignoreSslErrors=False]
20200519 11:53:20 - [INFO    ] - plugin.py            - 36   - ******** Starting Retrospect add-on version 5.2.4/repo *********
20200519 11:53:21 - [INFO    ] - chn_class.py         - 45   - Initializing channel (__init__): VRT NU (vrtnu) [channel.be.vrtnu.vrtnu=False, be=False, National, F530A9EC-3C0D-49B6-96C2-480273417460] (Order: #be.0011)
20200519 11:53:21 - [INFO    ] - plugin.py            - 117  - Loaded: VRT NU
20200519 11:53:21 - [ERROR   ] - pickler.py           - 246  - Error opening 'C:\Users\mail\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.retrospect\pickles\e2\80\e280e9a79f6b1d783584383f5407e9df885c7f14ef58010580cff1ea60fd216a.store.z'
20200519 11:53:21 - [ERROR   ] - pickler.py           - 246  - | Traceback (most recent call last):
20200519 11:53:21 - [ERROR   ] - pickler.py           - 246  - |   File "C:\Users\mail\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\pickler.py", line 239, in __retrieve_media_item_from_store
20200519 11:53:21 - [ERROR   ] - pickler.py           - 246  - |     with io.open(pickles_path, 'rb') as fp:
20200519 11:53:21 - [ERROR   ] - pickler.py           - 246  - + IOError: [Errno 2] No such file or directory: u'C:\\Users\\mail\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.video.retrospect\\pickles\\e2\\80\\e280e9a79f6b1d783584383f5407e9df885c7f14ef58010580cff1ea60fd216a.store.z'
20200519 11:53:21 - [CRITICAL] - addon.py             - 73   - Error running plugin
20200519 11:53:21 - [CRITICAL] - addon.py             - 73   - | Traceback (most recent call last):
20200519 11:53:21 - [CRITICAL] - addon.py             - 73   - |   File "C:\Users\mail\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\addon.py", line 63, in run_addon
20200519 11:53:21 - [CRITICAL] - addon.py             - 73   - |     p.run()
20200519 11:53:21 - [CRITICAL] - addon.py             - 73   - |   File "C:\Users\mail\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\plugin.py", line 165, in run
20200519 11:53:21 - [CRITICAL] - addon.py             - 73   - |     addon_action = VideoAction(self, channel_object)
20200519 11:53:21 - [CRITICAL] - addon.py             - 73   - |   File "C:\Users\mail\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\actions\videoaction.py", line 30, in __init__
20200519 11:53:21 - [CRITICAL] - addon.py             - 73   - |     raise ValueError("No MediaItem to play")
20200519 11:53:21 - [CRITICAL] - addon.py             - 73   - + ValueError: No MediaItem to play
20200519 11:53:21 - [INFO    ] - addon.py             - 74   - Retrospect :: Flushing and closing logfile.

Then I restarted retrospect (not kodi) and then it played the streams again.

**Comment by basrieter** [comment]
The error is because you deleted the cache. But good to hear this seems to work again.
