### ISSUE TITLE
NPO: "unspecified error retrieving streams" for some items

### ISSUE THREAD

**Issue by H2172** [retrospect-addon/plugin.video.retrospect#1380]
### Describe the bug

On several items, we get the error "unspecified error retrieving streams". They play correctly from the website, e.g. https://www.npostart.nl/the-sommerdahl-murders/23-05-2020/POW_04625397

## Expected Behavior

Video should play

## Actual Behavior

Error: "unspecified error retrieving streams"

### To Reproduce

1. NPO Start
2. Recent
3. Saturday, 23 May
4. 20:30 NPO3 The Sommerdahl Murders

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/uzadoyepip.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.2
LibreELEC release: RPi2.arm-9.0.2
- Retrospect version: 5.2.5

**Comment by H2172** [comment]
P.S., issue #1374 seems gone from Github, so I could not check whether it's the same (but that issue was solved 2 releases ago anyway)

**Comment by basrieter** [comment]
It's a different item. Are you watching from inside NL or outside?

**Comment by H2172** [comment]
from inside NL.

and no problems (geo fencing or otherwise) when watching the same item on npostart.nl

are you unable to replicate for this very item? (note it's not happening to all, just a few ...)

**Comment by H2172** [comment]
after doing the steps to troubleshoot #1381 , this one seems to be fixed as well ...! perhaps the reboot did the trick ...? (I do a reboot regularly, not sure if I had done that since this issue appeared.)

**Comment by H2172** [comment]
tried a few more that didn't work, all back to normal now. thanks for having a look (and thanks for the great Addon!!!)
