### ISSUE TITLE
NPO: Live TV channels are missing

### ISSUE THREAD

**Issue by H2172** [retrospect-addon/plugin.video.retrospect#1381]
### Describe the bug

Live tv channels are missing (NPO 1, NPO 2, NPO Zapp, etc.). Only Live _radio_ webcam channels are still visible.

## Expected Behavior

Live TV section should include tv channels such as NPO 1, NPO 2, etc.

## Actual Behavior

Only live _radio_ webcam channels are visible in Live TV section, i.e. 3FM Live,  Radio 1 Live, etc.

### To Reproduce

1. NPO Start
2. Live TV
3.

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/ofopagirox.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.2
    LibreELEC release: RPi2.arm-9.0.2
- Retrospect version: 5.2.5

**Comment by basrieter** [comment]
Weird, just checked my Raspberry Pi with Retrospect 5.2.5 and they appear as normal. Could you clear all cache via the Retrospect Advanced settings and retry?

**Comment by H2172** [comment]
OK will do and report back

**Comment by H2172** [comment]
that didn't help I'm afraid.
new log = https://paste.kodi.tv/hiyewibimi.kodi
![IMG_20200526_123030](https://user-images.githubusercontent.com/24855951/82890850-21684080-9f4d-11ea-8239-c765e6d59d4d.jpg)

**Comment by basrieter** [comment]
It seems that somehow for you https://npostart.nl/live is redirected to https://npostart.nl/. The the first line (the request url) and the last line (resulting url).

```
20200526 12:17:31 - [INFO    ] - urihandler.py        - 513  - Performing a GET for https://www.npostart.nl/live
20200526 12:17:31 - [DEBUG   ] - cachehttpadapter.py  - 99   - Expired Cache-Hit: https://www.npostart.nl/live
20200526 12:17:31 - [DEBUG   ] - cachehttpadapter.py  - 46   - Retrieving data from: https://www.npostart.nl/live
20200526 12:17:32 - [DEBUG   ] - cachehttpadapter.py  - 138  - Found cache-control and etag data: {'no-cache': True, 'no-store': True, 'private': True}
20200526 12:17:32 - [DEBUG   ] - cachehttpadapter.py  - 99   - Expired Cache-Hit: https://www.npostart.nl
20200526 12:17:32 - [DEBUG   ] - cachehttpadapter.py  - 46   - Retrieving data from: https://www.npostart.nl
20200526 12:17:32 - [DEBUG   ] - cachehttpadapter.py  - 138  - Found cache-control and etag data: {'s-maxage': 600, 'public': True, 'max-age': 0}
20200526 12:17:32 - [DEBUG   ] - cachehttpadapter.py  - 213  - Storing cache for: https://www.npostart.nl
20200526 12:17:32 - [INFO    ] - urihandler.py        - 519  - GET resulted in '200 OK' (0:00:00.516194) for https://www.npostart.nl
```

Could you do this:

- restart Kodi
- without starting Retrospect from the add-on settings clear cache and cookies
- enable TRACE logging in Retrospect
- start Retrospect and got to NPO Start / Live again.

I don't think it will fix it, but it might give more information.

**Comment by H2172** [comment]
@basrieter thanks for the quick support and for maintaining this great Addon. I'll close this issue now if you don't mind.
