### ISSUE TITLE
Stream does not start playing if 'play from here/continuous play' is requested/configured

### ISSUE THREAD

**Issue by nkichukov** [retrospect-addon/plugin.video.retrospect#1384]
### Describe the bug
If you want to have the next video/episode in a roll automatically play, playback does not start at all. This is reproducible via two ways, both perhaps related:
1.) Play from here on an list of items (by right-clicking in the list)
2.) Configuration setting: Settings / Player / Videos : play next video automatically (all selected)

## Expected Behavior
The selected episode should play, when it finishes, the next from the list should start and so on.

## Actual Behavior
Selected episode does not start at all

### To Reproduce

There are two ways to reproduce it:

1. Load retrospect plugin and go to Kids / NickJr
2. Select a series and go into it so the actual episodes are listed
3. When the list of recordings shows up, select one with right click and select option 'Play from here'

Alternatively, in the second scenario:
1.) Go to Settings / Player / Videos : play next video automatically (select all)
2.) Go to retrospect addon and then navigate Kids / NickJr
3.) Select a series and go into it
4.) Start an episode

### Debuglog
https://kichukov.home.xs4all.nl/bug-reports/plugin.video.retrospect/logs/retrospect-play-from-here-failure.log
https://kichukov.home.xs4all.nl/bug-reports/plugin.video.retrospect/logs/retrospect-settings-player-videos-playnextvideoautomatically-all-selected.log

## Additional context or screenshots (if appropriate)
Perhaps related to: #980 , but does not cause any crashes, just no playback.

### Your Environment
Used Operating system: GNU/Gentoo Linux
 - [ ] Android
 - [ ] iOS
 - [ x] Linux
 - [ ] OSX
 - [ x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: Kodi/19.0-ALPHA1 (Linux 5.4.28-v8+; armv8l; http://kodi.tv) Version/19.0-ALPHA1 Git:20200526-d7836a6226-dirty
- Retrospect version: 5.2.5-Matrix , with the patches for NickJrNL included.

**Comment by basrieter** [comment]
the method `getfilename` was removed recently: https://codedocs.xyz/xbmc/xbmc/python_v19.html 

Need to find a replace.

**Comment by basrieter** [comment]
Please try changing the `getfilename` in `videoaction.py` to `getPath` on lines 142 and 159. Restart Kodi and try again.

**Comment by nkichukov** [comment]
Hi Bas,
This patch fixes the problem for both use cases.

Hartelijk bedankt voor de snelle reactie! Groetjes,
-Nikolay

**Comment by basrieter** [comment]
Great!

**Comment by basrieter** [comment]
Official zip's are here. It will also be in the next release via the Kodi repository.

Leia: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-leia.zip
Matrix: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-matrix.zip
