### ISSUE TITLE
Kanal 5

### ISSUE THREAD

**Issue by svalasnubben** [retrospect-addon/plugin.video.retrospect#1387]
Kanal 5 Swe shows asks for password

**Comment by basrieter** [comment]
That is completely correct. You will need a Dplay account for playback. That username/password need to be configured. The password is stored securely in the Retrospect Vault. That vault is protected with a pin: see https://www.rieter.net/content/2017/02/07/storing-passwords-in-the-retrospect-vault/

**Comment by basrieter** [comment]
Added it to the wiki here: https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Storing-Passwords-in-the-Retrospect-Vault

**Comment by Snaah** [comment]
@svalasnubben To clarify: You need to go to dplay.se and create an account. Enter the login information in Retrospect. You can't be logged into the account on the web at the same time as using it in Retrospect. Just create two accounts if needed.

**Comment by cabban** [comment]
I have an account can't still watch anything
