### ISSUE TITLE
NPO 1: Could not start playback due to missing streams. Item:

### ISSUE THREAD

**Issue by BrodjagaRatnik** [retrospect-addon/plugin.video.retrospect#1389]
### Describe the bug

On NPO 1 only I get "Could not start playback due to missing streams. Item:"

Can play streams in resent.

## Expected Behavior

Playing stream

## Actual Behavior

Error: "unspecified error retrieving streams"

### To Reproduce

1. Selected NPO1 to play
2.
3.

### Debuglog

The **debug** retrospect.log can be found here: https://paste.kodi.tv/selofurega.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.6 Git:leia_pi4_18.6-Leia
- LibreELEC release: RPi4.arm-9.2.1
- Retrospect version: 5.2.5

**Comment by basrieter** [comment]
I see, this is cause by the fact that the current Live stream is Geo restricted to The Netherlands. That messes up the stream selection.

Please try: https://github.com/retrospect-addon/plugin.video.retrospect/archive/758f8a7e45b6148754c6ffb44a959182b0a9d437.zip

You can use the "install from zip" option in Kodi

**Comment by BrodjagaRatnik** [comment]
> I see, this is cause by the fact that the current Live stream is Geo restricted to The Netherlands. That messes up the stream selection.
> 
> Please try: https://github.com/retrospect-addon/plugin.video.retrospect/archive/e69dc7d31db3b63d5ec785f3111f039b9593d439.zip
> 
> You can use the "install from zip" option in Kodi

But I am in the Netherlands and issue is only on NPO 1, NPO 12 or NPO 3 are not affected.

**Comment by ndoornhn** [comment]
NPO1 works again with this fix

**Comment by basrieter** [comment]
Great, I will try to push an official release soon.
