### ISSUE TITLE
NPO Lifestream not working

### ISSUE THREAD

**Issue by joopmartens** [retrospect-addon/plugin.video.retrospect#1391]
### Describe the bug

Since a couple of days the NPO lifestreams stopped working. It shows a notification "Unspecified error retrieving streams" and next "The specified item has no streams available."

I'm running version 5.2.5 and Widevine updated a couple of days ago. 

## Expected Behavior

The stream should start without errors

## Actual Behavior

Error messages appear and the stream does not start.

### To Reproduce

1. Start one of the NPO lifestreams
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
20200609 22:54:15 - [INFO    ] - addon.py             - 35   - XOT Logger :: Appending Existing logFile
20200609 22:54:15 - [INFO    ] - urihandler.py        - 65   - Re-using existing UriHandler: UriHandler [id=1591735987, useCaching=Cache store [/storage/.kodi/userdata/addon_data/plugin.video.retrospect/cache/www], ignoreSslErrors=False]
20200609 22:54:15 - [INFO    ] - plugin.py            - 35   - *********** Starting Retrospect add-on version 5.2.5 ***********
20200609 22:54:15 - [INFO    ] - chn_class.py         - 45   - Initializing channel (__init__): NPO Start (uzgjson) [channel.nos.nos2010.uzgjson=False, nl=False, National, ED8FDB9C-3870-11E2-B1C2-192A6288709B] (Order: #_nl.0001)
20200609 22:54:15 - [INFO    ] - chn_nos2010.py       - 1389 - Setting the Cookie-Consent cookie for www.uitzendinggemist.nl
20200609 22:54:15 - [INFO    ] - plugin.py            - 104  - Loaded: NPO Start
20200609 22:54:15 - [INFO    ] - urihandler.py        - 513  - Performing a GET for https://www.npostart.nl/live/npo-1
20200609 22:54:15 - [INFO    ] - urihandler.py        - 519  - GET resulted in '200 OK' (0:00:00.149391) for https://www.npostart.nl/live/npo-1
20200609 22:54:15 - [INFO    ] - addonsettings.py     - 573  - Adaptive Stream add-on 'inputstream.adaptive' with decryption support was found.
20200609 22:54:15 - [INFO    ] - npostream.py         - 57   - Determining MPD streams for VideoId: POW_04675813
20200609 22:54:15 - [INFO    ] - urihandler.py        - 513  - Performing a GET for https://www.npostart.nl/api/token
20200609 22:54:15 - [INFO    ] - urihandler.py        - 519  - GET resulted in '200 OK' (0:00:00.104021) for https://www.npostart.nl/api/token
20200609 22:54:15 - [INFO    ] - urihandler.py        - 505  - Performing a POST with '<No Content-Type>' for https://www.npostart.nl/player/POW_04675813
20200609 22:54:15 - [INFO    ] - urihandler.py        - 519  - POST resulted in '200 OK' (0:00:00.158110) for https://www.npostart.nl/player/POW_04675813
20200609 22:54:15 - [INFO    ] - urihandler.py        - 513  - Performing a GET for https://start-player.npo.nl/video/POW_04675813/streams?profile=dash-widevine&quality=npo&tokenId=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzbWFydHRhZyI6eyJzaXRlSWQiOiI0In0sImhhc1N1YnNjcmlwdGlvbiI6IiIsImhhc1ByZW1pdW1TdWJzY3JpcHRpb24iOiIiLCJlbGVtZW50SWQiOiJwbGF5ZXItUE9XXzA0Njc1ODEzIiwibWVkaWFJZCI6IlBPV18wNDY3NTgxMyIsInRvcHNwaW4iOnsicGFydHlJZCI6IiIsInByb2ZpbGVJZCI6IiJ9LCJoYXNTZXR0aW5ncyI6IjEiLCJoYXNBZENvbnNlbnQiOiIxIiwic2hhcmUiOiIxIiwic3R5bGVWZXJzaW9uIjoiMiIsIm1vcmVCdXR0b24iOiIwIiwiY2hyb21lY2FzdCI6eyJlbmFibGVkIjoiMSJ9LCJzdHlsaW5nIjp7InRpdGxlIjp7ImRpc3BsYXkiOiJub25lIn19LCJwYWdlVXJsIjoiIiwic3RlclJlZmVycmFsVXJsIjoiIiwic3RlclNpdGVJZCI6Im5wb3N0YXJ0Iiwic3R5bGVzaGVldCI6Imh0dHBzOlwvXC93d3cubnBvc3RhcnQubmxcL3N0eWxlc1wvcGxheWVyLmNzcyIsImlhdCI6MTU5MTczNjA1NSwibmJmIjoxNTkxNzM2MDU1LCJleHAiOjE1OTE3NjQ4NTUsImNvbnN1bWVySWQiOm51bGwsImlzUGxheWxpc3QiOmZhbHNlLCJyZWZlcnJlclVybCI6bnVsbCwic2tpcENhdGFsb2ciOjAsIm5vQWRzIjowLCJyZWNvbW1lbmRhdGlvbnMiOjEsImlzcyI6ImV5SnBkaUk2SWs1WWNESkdka1pvV1RKU1VFdGlOMHRKUzI5WFpuYzlQU0lzSW5aaGJIVmxJam9pSzJwM1ltNDFOMEpaZDJoUFVHcDFhMUJ5VGtJemRteHdOMjlVVEc5VlJEbDVTbUYxTWxoNGRFTk5NRUpYWlRoQlNXMWNMMDFNVG1wb1dXdEdlR1JwVGx3dklpd2liV0ZqSWpvaVpEZ3lNek16WTJObE1EVmtNV1ZoTkRJMVlURmlPVFJoTTJJNU0yRmhNR0ZtTmpKaU5UWTBPR014T0RVME1XVTJNbVppT0dRM01UTm1OV0poTUdJM1lTSjkifQ.AFKc_CI5StRauH4IyKJBj5NfaNROHcX2WIerjiuLryM&streamType=broadcast&mobile=0&isChromecast=0
20200609 22:54:15 - [INFO    ] - urihandler.py        - 519  - GET resulted in '200 OK' (0:00:00.159555) for https://start-player.npo.nl/video/POW_04675813/streams?profile=dash-widevine&quality=npo&tokenId=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzbWFydHRhZyI6eyJzaXRlSWQiOiI0In0sImhhc1N1YnNjcmlwdGlvbiI6IiIsImhhc1ByZW1pdW1TdWJzY3JpcHRpb24iOiIiLCJlbGVtZW50SWQiOiJwbGF5ZXItUE9XXzA0Njc1ODEzIiwibWVkaWFJZCI6IlBPV18wNDY3NTgxMyIsInRvcHNwaW4iOnsicGFydHlJZCI6IiIsInByb2ZpbGVJZCI6IiJ9LCJoYXNTZXR0aW5ncyI6IjEiLCJoYXNBZENvbnNlbnQiOiIxIiwic2hhcmUiOiIxIiwic3R5bGVWZXJzaW9uIjoiMiIsIm1vcmVCdXR0b24iOiIwIiwiY2hyb21lY2FzdCI6eyJlbmFibGVkIjoiMSJ9LCJzdHlsaW5nIjp7InRpdGxlIjp7ImRpc3BsYXkiOiJub25lIn19LCJwYWdlVXJsIjoiIiwic3RlclJlZmVycmFsVXJsIjoiIiwic3RlclNpdGVJZCI6Im5wb3N0YXJ0Iiwic3R5bGVzaGVldCI6Imh0dHBzOlwvXC93d3cubnBvc3RhcnQubmxcL3N0eWxlc1wvcGxheWVyLmNzcyIsImlhdCI6MTU5MTczNjA1NSwibmJmIjoxNTkxNzM2MDU1LCJleHAiOjE1OTE3NjQ4NTUsImNvbnN1bWVySWQiOm51bGwsImlzUGxheWxpc3QiOmZhbHNlLCJyZWZlcnJlclVybCI6bnVsbCwic2tpcENhdGFsb2ciOjAsIm5vQWRzIjowLCJyZWNvbW1lbmRhdGlvbnMiOjEsImlzcyI6ImV5SnBkaUk2SWs1WWNESkdka1pvV1RKU1VFdGlOMHRKUzI5WFpuYzlQU0lzSW5aaGJIVmxJam9pSzJwM1ltNDFOMEpaZDJoUFVHcDFhMUJ5VGtJemRteHdOMjlVVEc5VlJEbDVTbUYxTWxoNGRFTk5NRUpYWlRoQlNXMWNMMDFNVG1wb1dXdEdlR1JwVGx3dklpd2liV0ZqSWpvaVpEZ3lNek16WTJObE1EVmtNV1ZoTkRJMVlURmlPVFJoTTJJNU0yRmhNR0ZtTmpKaU5UWTBPR014T0RVME1XVTJNbVppT0dRM01UTm1OV0poTUdJM1lTSjkifQ.AFKc_CI5StRauH4IyKJBj5NfaNROHcX2WIerjiuLryM&streamType=broadcast&mobile=0&isChromecast=0
20200609 22:54:17 - [WARNING ] - videoaction.py       - 53   - process_video_item returned an MediaItem that had MediaItem.complete = False:
20200609 22:54:17 - [WARNING ] - videoaction.py       - 53   - | MediaItem: NPO 1: Op1 [Type=video, Complete=False, IsLive=True, Date=, Geo/DRM=False/False]
20200609 22:54:17 - [WARNING ] - videoaction.py       - 53   - + MediaPart: NPO 1: Op1 [HttpHeaders={}]
20200609 22:54:18 - [WARNING ] - videoaction.py       - 62   - Could not start playback due to missing streams. Item:
20200609 22:54:18 - [WARNING ] - videoaction.py       - 62   - | MediaItem: NPO 1: Op1 [Type=video, Complete=False, IsLive=True, Date=, Geo/DRM=False/False]
20200609 22:54:18 - [WARNING ] - videoaction.py       - 62   - + MediaPart: NPO 1: Op1 [HttpHeaders={}]
20200609 22:54:18 - [INFO    ] - addon.py             - 68   - Retrospect :: Flushing and closing logfile.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.7.1 (LibreELEC 9.2.3)
- Retrospect version: 5.2.5

**Comment by basrieter** [comment]
This was fixed in #1389  and release yesterday. It should be installable via the Kodi repository.
