### ISSUE TITLE
Kan niet meer configureren in Kodi

### ISSUE THREAD

**Issue by Dapee08** [retrospect-addon/plugin.video.retrospect#1395]
Via Kodi Leia 18.6, (Librelec 9.2.1) en versie 5.2.6 van Retrospect kan ik al een tijdje geen configuratie wijzigingen aanbrengen. Als ik de instellingen oproep komt er alleen maar aan de linkerkant een knop met daarin de tekst "Geen categorieën beschikbaar". M.a.w.: ik kan niet meer instellen. Ook geen wachtwoorden voor bijvoorbeeld NPO of VRT.NU. Ik vermoed dat er iets mis is met de installatie. Ik heb al geprobeerd om Retrospect te verwijderen en weer opnieuw te installeren, maar dit helpt niet.
Of kanaalinstellingen. Dit alles is niet meer te bereiken.

**Comment by basrieter** [comment]
Dan is er iets mis gegaan bij het initialiseren.

Als je hem verwijdert (instellingen en zo behouden) en dan weer opnieuw installeert zou het weer moeten werken. Geef hem bij de eerste keer runnen even wat tijd totdat alles klaar is.

Zo niet dan even de retrospect.log van de eerste run na installatie op paste.kodi.tv zetten en hier linken.

**Comment by basrieter** [comment]
Werkt dit nu weer?

**Comment by Dapee08** [comment]
Hallo Bas,

Ik heb het hele systeem (dus ook Kodi) opnieuw, 'fris' geïnstalleerd en nu
werkt het weer.

Alleen krijg ik het VRT.NU nog niet aan de praat, ondanks dat ik een
gebruikersnaam en wachtwoord heb ingesteld. Bij de NPO bijvoorbeeld werkt
het zonder problemen, maar bij de VRT.NU opent hij geen enkele stream. (Met
de 'originele' VRT.NU addon uit de repository, doen de meeste streams het
wel; uiteraard degene die geo-blocked zijn niet, aangezien ik geen Belgisch
telefoonnummer heb. Dat is geen probleem).

Ik zal een dezer dagen nog eens kijken in de LOG's of ik iets kan vinden.

Groeten en nogmaals dank voor het meedenken!

Paul

Op ma 29 jun. 2020 00:44 schreef Bas Rieter <notifications@github.com>:

**Comment by basrieter** [comment]
Goed om te horen. Voor VRT: #1400

**Comment by basrieter** [comment]
Je kunt deze installeren om VRT te fixen:

Leia: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-leia.zip
Matrix: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-matrix.zip

**Comment by Dapee08** [comment]
Hallo Bas,

Top!
Alles werkt!
Thanks.

Op di 30 jun. 2020 21:54 schreef Bas Rieter <notifications@github.com>:

**Comment by basrieter** [comment]
Goed om te horen. Ik hoop binnenkort een nieuwe versie te releasen.
