### ISSUE TITLE
GUI: Missing new line on description with limitations

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1396]
### Describe the bug

A bug or enhancement: 
Missing new line on description with limitations

## Expected Behavior

Add new line before the symbols for DRM, GEO and Paid in description

## Actual Behavior

No new line before the symbols for DRM, GEO and Paid in description

## Possible Fix

`
My QuickFix, make changes in menuitem.py. in:

    def __update_title_and_description_with_limitations(self):

add new def after def __color_text.......

        def __color_text_limits(texts, text_format="\n[COLOR {}]{}[/COLOR]"):
            """

            :param list[tuple[str, str]] texts:     The color and text (in tuple)
            :param str text_format:                 The format used for filling

            :return: A Kodi compatible color coded string.
            :rtype: str

            See https://forum.kodi.tv/showthread.php?tid=210837
            """

            return "".join([text_format.format(clr, text.lstrip()) for clr, text in texts])

change to use __color_text_limits for description:

        if description_prefix:
            description = __color_text_limits(description_prefix)
`

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here: N/A

### Screenshots 

Before QuickFix
![err1](https://user-images.githubusercontent.com/46671821/85229941-2b1a8200-b3ed-11ea-81de-9dd8ead5f679.jpg)
![err2](https://user-images.githubusercontent.com/46671821/85229945-31106300-b3ed-11ea-86ee-1cba53056193.jpg)

After QuickFix
![fix1](https://user-images.githubusercontent.com/46671821/85229949-37064400-b3ed-11ea-832f-93fd4925500e.jpg)
![fix2](https://user-images.githubusercontent.com/46671821/85229951-39689e00-b3ed-11ea-8254-aff7ffd3278b.jpg)

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.7
- Retrospect version: 5.2.6

**Comment by basrieter** [comment]
Already fixed it, but did not get to merging it. See #1397

**Comment by basrieter** [comment]
Official zip's are here. It will also be in the next release via the Kodi repository.

Leia: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-leia.zip
Matrix: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-matrix.zip
