### ISSUE TITLE
VRT NU does't play on a fresh installation of kodi

### ISSUE THREAD

**Issue by peno64** [retrospect-addon/plugin.video.retrospect#1400]
### Describe the bug

I did a fresh installation of kodi 18.7 on a raspberry pi 4 with libreelec and the first and only thing that is done is installing the latest retrospect from the kodi repository. Then I created a vault pin and I installed widevine drm from the retrospect settings menu.
Then I put my password from vrt nu on that channel in the settings and then I try to play the journal (Het journaal).
It just won't play. Retrospect asks me again the pin code, which I already  find strange and then gives the error "cannot start playback". I tried the same with channel Vier and here everything is fine (the pin code is also not asked as I expect). But eacht time I restart kodi and try to play vrt nu, it asks for the retrospect pin code and then it does not play. I am sure that my login credentials are correct because I use the same to login on the site with my web browser and they are accepted.
When I restore the folder plugin.video.retrospect from the userdata/addon_data folder from my previous installation where vrt nu played fine, then this new installation also plays fine. This proofs me that the installation of the program and widevine is correct and that the problem is some sort of login issue in the vrt nu site. This is also shown by the retrospect log. But again, I am 100% sure that I use the correct credentials.

## Expected Behavior

vrt nu should work on a fresh installation

## Actual Behavior

nothing plays fro vrt nu and an error message is shown

### To Reproduce

See description of the bug

### Debuglog

The **debug** retrospect.log can be found here:

https://paste.kodi.tv/fetagetito

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi 4
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.7
- Retrospect version: 5.2.6

**Comment by basrieter** [comment]
I see, something is failing with the log in. Let me see if I can fix that.

**Comment by basrieter** [comment]
Please try this for Kodi 18.x: https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1400.zip

**Comment by peno64** [comment]
Works great with this fix. The retrospect pin is asked once now and then the stream is played. Also after a reboot it looks ok now. Now pin isn't asked anymore also.

Thank you
