### ISSUE TITLE
Ondertiteling bij kijk.nl ?

### ISSUE THREAD

**Issue by meganiekje** [retrospect-addon/plugin.video.retrospect#1402]
### Describe the bug

Hoi Bas, Ik ben enorm blij met je harde werk !!
Wij gebruiken het ELKE dag :) 
Ik heb gezien dat alle Talpa uitzending-gemist items naar Kijk gegaan zijn.
Dat is op zich prima, maar helaas werken bij de meeste uitzendingen de ondertitels niet.
Ik heb al zitten proberen met de ondertitel-instellingen in Retrospect en in Kodi/LibreElec, maar ik krijg het niet aan de praat.
Is hier nog wat aan te doen ?

Alvast bedankt !!!! 

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.7.1
- Retrospect version: 5.2.6

**Comment by basrieter** [comment]
Heb je voorbeelden van afleveringen waarbij de ondertitels niet (goed) werken?

**Comment by meganiekje** [comment]
Hoi Bas,
Dat is een snelle reactie !!!
Bijvoorbeeld bij : Recent, gisteren, Het blok Australie.
Er is een nederlandse voice-over, maar in de normale uitzending is er een ondertiteling voor de engels sprekende deelnemers.
Via kodi is die ondertitel helaas niet aanwezig.
Via de website van kijk.nl is de ondertitel er wel, maar ik moet hem wel aanzetten. Het is een 'overlay' in de speler.

**Comment by basrieter** [comment]
Ze ontbraken nog in de code. Zou je deze zip file eens kunnen installeren via de "install from zip" optie in Kodi:

https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1402.zip

De zip werkt enkel voor Kodi Leia.

**Comment by meganiekje** [comment]
Hey Bas, 
Ik heb je testversie geinstalleerd, en hij werkt perfect !
De ondertitels doen het nu prima !

**Comment by basrieter** [comment]
Gooed om te horen!
