### ISSUE TITLE
SE: UR Play - Show program list in folders is not possible anymore

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1403]
### Describe the bug

Show program list in folders is not possible anymore

## Expected Behavior

Show program list in folders 

## Actual Behavior

Popup's a Retrospect - error message

## Possible Fix

Remove milliseconds from startTime and endTime
chn_urplay.py - change on line 336 (for test):
```
        if "accessiblePlatforms" in result_set and "urplay" in result_set["accessiblePlatforms"]:
            start_date = result_set["accessiblePlatforms"]["urplay"]["startTime"]
            start_date = start_date.replace(".000Z","Z")
            end_date = result_set["accessiblePlatforms"]["urplay"]["endTime"]
            end_date = end_date.replace(".000Z","Z")
```

### To Reproduce

1.  select UR Play
2. select .: Popular :.
3.

### Debuglog

The **debug** retrospect.log can be found here:
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4878274/retrospect.log)

### Screenshots 

N/A

## Additional context or screenshots (if appropriate)

N/A

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.7
- Retrospect version: 5.2.7

**Comment by basrieter** [comment]
I really wish they would make up their mind and stay with one format. Will fix it.

**Comment by basrieter** [comment]
Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1403.zip for Kodi Leia to test. I also fixed the titles in "popular" and "recent" listings. They did not include the show title. Just the episode title.

**Comment by matsarv** [comment]
Everything is looking good. Greate work.
