### ISSUE TITLE
Option to disable pin check

### ISSUE THREAD

**Issue by Damme** [retrospect-addon/plugin.video.retrospect#1405]
### Is your feature request related to a problem? Please describe

I feel it unnecessarily to input pin every time I want to play something that requires login. My use case does not even need a pin. Me and only me have access to the device.

### Describe the solution you'd like

The solution would be that retrospect first tries with for example 000000 as pin, if no success display enter pin dialog. Change to this set pin to disable pin check.

**Comment by basrieter** [comment]
Nope that will not happen. The PIN should only be needed once to create a login in token. In many cases this token is valid for multiple months. If you are requested for a PIN every time, something else is wrong. Please provide a full debug retrospect.log. It can be uploaded from the add-on settings. So:

- Enable debug logging in Kodi
- Then try to playback something that asks the PIN
- Finally upload the log via the add-on settings

Post the link to the log here.

**Comment by Damme** [comment]
You can close this, I really dont know why I had to enter pin every time in the beginning, after fresh install it worked as you said.

**Comment by basrieter** [comment]
Great to hear that @Damme . Enjoy Retrospect
