### ISSUE TITLE
AT5 and RTV Noord-Holland channel lists gone blank

### ISSUE THREAD

**Issue by didamsko** [retrospect-addon/plugin.video.retrospect#1406]
### Describe the bug

Both the AT5 and RTV Noord-Holland channel lists have gone blank. The live-streams on both channels still work.

## Expected Behavior

I mainly watched sub-item AT5 news in the AT5 channel and normally when you opened the AT5 news sub-item you got a list with the daily news episodes. 

## Actual Behavior

Both channel lists are blank besides the live stream. There is no more AT5 news item. 

### To Reproduce

1. Browse to the channels and open them
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.7 (packed with latest OSMC)
- Retrospect version: 5.2.7

**Comment by basrieter** [comment]
I fixed AT5. Could you check by installing this zip using the Install from Zip in Kodi: https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1406.zip

I never had a full listing for _RTV Noord-Holland_ as they changed their mobile API. Don't really know what they use now. I will check it tomorrow.

**Comment by didamsko** [comment]
Thanks for the quick fix Bas! AT5 indeed is working again. First after the fix i still was missing _AT5 Nieuws_ but i see that they rebranded that to _Amsterdam Vandaag_. So i'm happy and can watch my local news again. 

I'm not sure what items were on the _RTV Noord-Holland_ channel but i believe there was more then only the live stream.

**Comment by didamsko** [comment]
Not related to this bug but i just saw a small typo on the plugin.video.retrospect page: 

> ...
> Acknowledgement
> 
> The first idea for Retrospect/XBMC Online TV/XOT-Uzg came from a script **by by** BaKMaN.
> 
> ...

https://github.com/retrospect-addon/plugin.video.retrospect#acknowledgement

**Comment by basrieter** [comment]
If you download https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1406.zip again it should now also have a working RTV Noord Holland

**Comment by didamsko** [comment]
Downloaded and applied and RTV Noord Holland indeed gives a list but only short news items besides the live stream, it has no "main index" similar to AT5 that by example has its daily news show grouped in the _Amsterdam Vandaag_ sub menu in the main listing. Does the RTV Noord Holland channel no longer support that? I believe it did in the past.

**Comment by basrieter** [comment]
RTV Noord Holland no longer has that, not even on their site: https://www.nhnieuws.nl/media

**Comment by basrieter** [comment]
Ik heb wat gevonden: ik gebruik nu de Thema's als folders: https://www.nhnieuws.nl/themas

https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1406.zip bevat nu deze changes.

**Comment by didamsko** [comment]
Downloaded and applied and RTV Noord Holland indeed gives a list but only short news items besides the live stream, it has no "main index" similar to AT5 that by example has its daily news show grouped in the _Amsterdam Vandaag_ sub menu in the main listing. Does the RTV Noord Holland channel no longer support that? I believe it did in the past.

**Comment by basrieter** [comment]
You copy pasted your last comment? Did you try the last version? You need to redownload the zip file and reinstall using the "install from zip"?

**Comment by didamsko** [comment]
LOL i thought i had forgotten to press the comment button... so i indeed repeated my reply and did not notice that you already answered. 

I downloaded and tried your last fix. It indeed looks like i remembered now altough oddly enough i do not see their news show listed there. It seems that online they switched from the static news show to all those short news items instead. But i can watch the news show via the live stream then. 

I consider it fixed. Thanks for your help!

**Comment by basrieter** [comment]
Official zip's are here. It will also be in the next release via the Kodi repository.

Leia: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-leia.zip
Matrix: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-matrix.zip
