### ISSUE TITLE
VTM Nieuws broken

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#1408]
### Describe the bug

VTM Nieuws broke due to a major change in website. It also introduced a cookie-wall. The new URL is: https://www.hln.be/video/series

### Your Environment
Used Operating system:

 - [x] Android
 - [x] iOS
 - [x] Linux
 - [x] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [x] Windows UWP

Used versions:
- Kodi version: **all**
- Retrospect version: _latest_

**Comment by TomHillaert** [comment]
Go go Bas, fix this please :)

**Comment by TomHillaert** [comment]
This thread is also about VTM ? Because I think also VTM is not working. (not only VTM nieuws)

**Comment by bcnx** [comment]
I can confirm this, had also create a bug for this, which got closed down but the problem still seems there.

BC

**Comment by basrieter** [comment]
Closing this with this commit 935dccb5f8533d59a9f989090ec42a57503c0788.

VTM will not be working via Retrospect for now. There is a very nice VTM GO add-on that contains all VTM content. Retrospect will pass through to that one. Also see: #1409 and #1463.
