### ISSUE TITLE
Quick switch for Geo Location

### ISSUE THREAD

**Issue by Arathonk** [retrospect-addon/plugin.video.retrospect#1411]
### Is your feature request related to a problem? Please describe

Geo-Blocked channels

### Describe the solution you'd like

A quick switch option to change Geo Location, or an option to set it to switch automatically when selecting and changing channels.

### Describe alternatives you've considered

Manually going into settings to switch, requires lots of clicks and costs some time.

**Comment by basrieter** [comment]
Could you explain what issue you currently encounter? The Geo location setting usually on gets set once?

**Comment by Arathonk** [comment]
I constantly switch between watching streams from channels like Vier.be, UK channels and Dutch channels, so every time I need to go into settings and change the geo location again because lots of those streams/channels are geo blocked.

**Comment by basrieter** [comment]
So, why don't you set them the GEO location to "Disabled"? That way they will all show and those that are geo locked will have a yellow "o" behind them.

**Comment by Arathonk** [comment]
Because then It won't play the geo locked ones?

**Comment by basrieter** [comment]
> Because then It won't play the geo locked ones?

That setting has absolutely nothing to do with Retrospect making GEO blocked items play. If they are locked to the Netherlands, they won't play outside. The only thing the setting does is allow you to filter out those that won't play outside your GEO region. So if you set it to Netherlands, it will show all items that are not GEO locked and those that are GEO locked to The Netherlands. If you set it to Sweden, Retrospect  will show all items that are not GEO locked and those that are GEO locked to Sweden.
