### ISSUE TITLE
Kids>Nickelodeon broken

### ISSUE THREAD

**Issue by lovecrafthowardphillips** [retrospect-addon/plugin.video.retrospect#1412]
### Describe the bug
Clicking on Nickelodeon produces the error message "No episodes found for the selected item". Playing the videos straight from nickelodeon.nl works perfectly fine. The Kids>Nick Jr. link in Retrospect is still working fine as well.

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.7
- Retrospect version: 5.2.8

**Comment by basrieter** [comment]
Please provide a DEBUG retrospect.log file:

- Enable debug logging withing REtrospect
- Reproduce the problem
- Upload the log file using the built-in functionality of Retrospect (via the add-on settings)
- Provide the link to the log file here.

**Comment by lovecrafthowardphillips** [comment]
Of course: http://paste.kodi.tv/obahumebur

Thank you for looking into this.

**Comment by basrieter** [comment]
Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1412.zip using the "Install from zip" option in Kodi Leia (not Matrix). 

I have to implement the listing of "Seasons" but the main lists should work again.

**Comment by lovecrafthowardphillips** [comment]
It lists the shows again, thanks. Two things I've noticed doing some quick tests, though:

1.  It only shows videos for the first selected season. E.g. for https://www.nickelodeon.nl/shows/76ypv4/spongebob it will only list the one video under Season 11, not the videos for the other seasons. Possibly related to the implementation of Seasons you mentioned?
2.  It only shows videos for a season that are immediately displayed on the page, not the videos that are initially hidden and that you have to first click on "Show more" for them to be displayed. E.g. for https://www.nickelodeon.nl/shows/65kecx/de-legende-van-korra it will only list the videos up to episode A23 because A24-A26 are initially hidden behind the "Show more".

**Comment by basrieter** [comment]
The seasons I will fix, as I mentioned.

The "more" I will need to look into and fix.

**Comment by basrieter** [comment]
I think I fixed the both items. Please re-download the zip https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1412.zip and install using the "Install from zip" option in Kodi Leia (not Matrix).

**Comment by lovecrafthowardphillips** [comment]
Excellent work, both issues seem to have been resolved. Have a great weekend!

**Comment by basrieter** [comment]
Official zip's are here. It will also be in the next release via the Kodi repository.

Leia: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-leia.zip
Matrix: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-matrix.zip

**Comment by basrieter** [comment]
They broke again, but I already fixed it. If you download the zip's again, it will work again.
