### ISSUE TITLE
Sweden: Dplay login broke on Android devices

### ISSUE THREAD

**Issue by Soleros1** [retrospect-addon/plugin.video.retrospect#1413]
Hello!
Thanks for a nice add-on!

I have a problem with some of the Swedish channels from Dplay, Kanal 5, and kanal 9 that will not play on my Android devices (Fire tv stick 4k and on my android phone).
Both have latest Kodi stable installed 18.8 and latest Retrospect 5.29. I have put in username and password for Dplay channel which should work for all these channels.

When I try to play a stream from any of these channels i get "Could not login to selected channel" and from Retrospect "the selected item does not have any streams associated. 
The strange thing is that all channels works perfekt from my computer with Win10 and Kodi, also tried with another computer with only LibreELEC it works there to.
Same login to Dplay used there.

What could be the problem with Android systems that these channels doesn't work there? 

Uploaded log file here: https://paste.kodi.tv/omomiyibis

Regards!

**Comment by basrieter** [comment]
I think I fixed it. Could you install https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1413.zip using the "Install from zip" option and retry?

**Comment by Soleros1** [comment]
Hello!
I have just tested this on my Android phone with Android 10 and it is working very good there, had for some reason to reset pin to get it working, 
Can test this evening with the fire stick 4k, and get back.
Thank you very much!!

**Comment by Soleros1** [comment]
I can now confirm your fix also works on the fire tv stick 4k  👍

**Comment by basrieter** [comment]
Official zip's are here. It will also be in the next release via the Kodi repository.

Leia: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-leia.zip
Matrix: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-matrix.zip
