### ISSUE TITLE
SVTPlay - Single episodes won't play

### ISSUE THREAD

**Issue by Sopor** [retrospect-addon/plugin.video.retrospect#1414]
### Describe the bug

SVTPlay has changed the layout of their site

## Expected Behavior

It should play the programs

## Actual Behavior

Cannot start playback is the error message

### To Reproduce

1. It seems to only be those program you will see in Single episodes
2.
3.

### Debuglog

The **debug** retrospect.log can be found here: https://paste.kodi.tv/iritimepat.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.6
- Retrospect version: 5.2.10

**Comment by basrieter** [comment]
Please try this version (Kodi Leia): https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1414.zip

**Comment by Sopor** [comment]
I have tested several different streams and they all works!

**Comment by basrieter** [comment]
Good to hear that. Will try make a new release as soon as some other issues are fixed.

**Comment by Sopor** [comment]
SVTPlay is broken again: [Debuglog](https://paste.kodi.tv/acijovagiz.kodi)

**Comment by basrieter** [comment]
Please, don't re-use old issues. I already fixed that yesterday: https://github.com/retrospect-addon/plugin.video.retrospect/commit/c5274ba8df78ce5327520e2b9abe287c5b0acb88

Will generate Leia en Matrix zips in a moment.

**Comment by basrieter** [comment]
Official zip's are here. It will also be in the next release via the Kodi repository.

Leia: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-leia.zip
Matrix: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-matrix.zip
