### ISSUE TITLE
VRT.Nu only sound no video ?

### ISSUE THREAD

**Issue by TomHillaert** [retrospect-addon/plugin.video.retrospect#1415]
Yesterday evening I was only able to hear audio and not see video on any stream I watched from VRT.Nu ?
Is this a bug or something with my configuration ?

**Comment by basrieter** [comment]
And how are things now? Where is your debug retrospect.log? Without a log I can't do anything.

**Comment by peno64** [comment]
There were some problems yesterday with vrt nu.
I could for example not look at the vrt news via the vrt nu addon.
2 hours later it was again ok.
So most probably it was a problem on the vrt nu site.

**Comment by TomHillaert** [comment]
It seemed I had more problems on my android tv box. Reinstalled Kodi and the retrospect plugin. Now vrt + vier/vijf/zes are ok again.
VTM + VTM Nieuws are not working but I think you guys already know that. In other words, this thread can be closed. Thx.

**Comment by peno64** [comment]
There is also a VTM GO addon. With this one you can also look at the VTM news and I think also live. VTM news worked there 2 days ago at least.
