### ISSUE TITLE
need a code för kanal 5 seems little bug  

### ISSUE THREAD

**Issue by cabban** [retrospect-addon/plugin.video.retrospect#1417]
### Describe the bug
when i tap a web serie i need a code 

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:
- Retrospect version:

**Comment by basrieter** [comment]
It is not. You need a username and password to play content from the DPlay platform. That password is securely stored in the Retrospect Vault which is encrypted using a PIN. 

If you think otherwise, please attach a full DEBUG retrospect.log and update this issue with information required in the issue template (as you should have already done).

**Comment by cabban** [comment]
@basrieter  where is that pin :) ?

**Comment by basrieter** [comment]
Details can be found here: https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Storing-Passwords-in-the-Retrospect-Vault

You most likely already have it set up if you ever used any password in Retrospect.

**Comment by cabban** [comment]
> Details can be found here: https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Storing-Passwords-in-the-Retrospect-Vault
> 
> You most likely already have it set up if you ever used any password in Retrospect.

i havent but i find user name and passwqord, but how to generate a pin? cheers

**Comment by basrieter** [comment]
If you set the password, the first thing Retrospect will do, if there is no Vault yet, is guide you through setting it up.

**Comment by cabban** [comment]
> If you set the password, the first thing Retrospect will do, if there is no Vault yet, is guide you through setting it up.

where, i see my username in the vault  but then nothing? .:(  how can i watch dplay again , why this pin code must :)(

**Comment by basrieter** [comment]
You won't see a username in the vault! Go to the DPlay channel options:

![image](https://user-images.githubusercontent.com/1310443/92410601-ef1dd000-f144-11ea-9f21-c8456ec3f904.png)

Select password and hit enter. You should get this pop-up for the Retrospect PIN (if you already have one set up, if you don't have it set up, it will ask you so set a new pin. It can be a simple one, as the SCrypt will make it strong):

![image](https://user-images.githubusercontent.com/1310443/92410623-ffce4600-f144-11ea-9b49-8dbff2a897e8.png)

Insert the PIN and select Done. The next dialog will ask you what password to set: 

![image](https://user-images.githubusercontent.com/1310443/92410694-33a96b80-f145-11ea-983a-f1ac191ff1a0.png)

Set the password and select "Done" again to confirm. You will end up in the Add-on settings again. Click "ok" and go back to Retrospect. The next time you want to play Dplay, it will ask for the Retrospect PIN once. It will use it to retrieve the password and then it should start playing.

**Comment by cabban** [comment]
> You won't see a username in the vault! Go to the DPlay channel options:
> 
> ![image](https://user-images.githubusercontent.com/1310443/92410601-ef1dd000-f144-11ea-9f21-c8456ec3f904.png)
> 
> Select password and hit enter. You should get this pop-up for the Retrospect PIN (if you already have one set up, if you don't have it set up, it will ask you so set a new pin. It can be a simple one, as the SCrypt will make it strong):
> 
> ![image](https://user-images.githubusercontent.com/1310443/92410623-ffce4600-f144-11ea-9b49-8dbff2a897e8.png)
> 
> Insert the PIN and select Done. The next dialog will ask you what password to set:
> 
> ![image](https://user-images.githubusercontent.com/1310443/92410694-33a96b80-f145-11ea-983a-f1ac191ff1a0.png)
> 
> Set the password and select "Done" again to confirm. You will end up in the Add-on settings again. Click "ok" and go back to Retrospect. The next time you want to play Dplay, it will ask for the Retrospect PIN once. It will use it to retrieve the password and then it should start playing.

Only get wrong code when I tap password😥 I can't watch

**Comment by basrieter** [comment]
Do you actually specify a code? Please post a debug retrospect.log.

**Comment by cabban** [comment]
> Do you actually specify a code? Please post a debug retrospect.log.

@basrieter  i have an account but wrong code is notification etc cheers

**Comment by basrieter** [comment]
I can't follow what you are doing. So either provide a debug retrospect.log, or write down step by step what you are doing. Or better: record it.

But it seems that you are mixing up the Retrospect PIN and the Dplay password. These are 2 different things. If you are in doubt, just reset the Retrospect Vault from the add-on settings, choose a new PIN (keep it simple) and setup the Dplay password again like I showed above. And read what you need the input in the dialogs. It specifically asks for the PIN or password. Don't mix them up.

**Comment by cabban** [comment]
> I can't follow what you are doing. So either provide a debug retrospect.log, or write down step by step what you are doing. Or better: record it.
> 
> But it seems that you are mixing up the Retrospect PIN and the Dplay password. These are 2 different things. If you are in doubt, just reset the Retrospect Vault from the add-on settings, choose a new PIN (keep it simple) and setup the Dplay password again like I showed above. And read what you need the input in the dialogs. It specifically asks for the PIN or password. Don't mix them up.

As I wrote. I go in settings and username and password so my password is in the vault and that I till type in channel settings correct? Cheers

**Comment by basrieter** [comment]
Write it down, step by step. What you are saying seems incomplete. You go into settings, to the Dplay channel settings, select password, and should then be prompted for the PIN. So that is different then you write. 

I want to help, but I need to know what you are doing. Step by step.

**Comment by cabban** [comment]
> Write it down, step by step. What you are saying seems incomplete. You go into settings, to the Dplay channel settings, select password, and should then be prompted for the PIN. So that is different then you write.
> 
> I want to help, but I need to know what you are doing. Step by step.

But I did not get any questions abbot pin I'm not stupid and I understand but I tried but never get's any questions 😥

**Comment by basrieter** [comment]
so enable debug logging in Retrospect, try again and upload the logfile. Post the link here.

**Comment by basrieter** [comment]
The thing is that if something is wrong, then I can't see what without some data. I just tried and it is all OK for me.

**Comment by cabban** [comment]
> The thing is that if something is wrong, then I can't see what without some data. I just tried and it is all OK for me.

But the password is in the userdata in folder? Can I try that

**Comment by basrieter** [comment]
> > The thing is that if something is wrong, then I can't see what without some data. I just tried and it is all OK for me.
> 
> But the password is in the userdata in folder? Can I try that but also the username what to type in there?

No, the password is set via the Retrospect add-on setting. Configure the username there and the password. So again, in order to help you, please tell me what you are doing. Step by step: 

1. I do this
2. Then I do that

It sounds childish, but I really need to follow your steps.

**Comment by cabban** [comment]
> > > The thing is that if something is wrong, then I can't see what without some data. I just tried and it is all OK for me.
> > 
> > 
> > But the password is in the userdata in folder? Can I try that but also the username what to type in there?
> 
> No, the password is set via the Retrospect add-on settings and is encrypted. Configure the username there and the password. So again, in order to help you, please tell me what you are doing. Step by step:
> 
> 1. I do this
> 2. Then I do that
> 
> It sounds childish, but I really need to follow your steps.

Yes but I enter your addon then settings channel settings dplay 
Then it says username 
I don't find my username 
Password I don't have either so here I'm stuck 
When I try my password from dplay it's says wrong code for retrospect 😥 here I don't know what to do I think nothing is wrong just I don't know what to do. This was the hardest thing to understand since
 I first downloaded kodi regards

**Comment by basrieter** [comment]
Just provide a debug logfile. I think your version is outdated.

**Comment by cabban** [comment]
> Just provide a debug logfile. I think your version is outdated.

now i reset headpassword, but my dplay not viewing same as website ,  how can i see all episodes :)

**Comment by cabban** [comment]
> Just provide a debug logfile. I think your version is outdated.

i reset head påassword, cant still log in though i create a new password and other 
, then i have paid premium account how to get all episodes to watch inside retrospect ?

**Comment by Snaah** [comment]
@cabban I assume you are from Sweden, so maybe I can help you in Swedish?

Kolla först så du har senaste Kodi och Retrospect installerat.

Retrospect har ett krypterat "vault" där lösenord sparas. Första gången du skriver in dina användaruppgifter till DPlay kommer Retrospect be dig att ange en ny PIN-kod till "vault". Ange och bekräfta, sen kan du ange användaruppgifterna till DPlay. Tänk på att du måste vara utloggad från samma konto på dplay.se. Funkar det nu?

**Comment by basrieter** [comment]
Again: just provide a debug Retrospect log file. That is the only way forward now.
