### ISSUE TITLE
Regional channel AT5 made change, item Amsterdam Vandaag missing

### ISSUE THREAD

**Issue by didamsko** [retrospect-addon/plugin.video.retrospect#1418]
### Describe the bug

A recent change by AT5 a couple of days ago made that their news program "Amsterdam Vandaag" (formerly known as AT5 Nieuws) has gone missing from the channel list. 

## Possible Fix

Channel item Amsterdam Vandaag is still available on the website: https://www.at5.nl/artikelen/p123/amsterdam-vandaag so it still exists and i hope it can be included back. 

### To Reproduce

1. open the AT5 channel list and you will see that the Amsterdam Vandaag item is currently missing
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: OSMC's (currently latest) 2020 June update with Kodi v18.7
- Retrospect version: 5.2.11

**Comment by basrieter** [comment]
Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1418.zip via the "install from zip" option under Kodi Leia (not Matrix). "Amsterdam Vandaag" should be there again.

**Comment by didamsko** [comment]
Thanks! Your fix is working. I can watch Amsterdam Vandaag again.

**Comment by basrieter** [comment]
Official zip's are here. It will also be in the next release via the Kodi repository.

Leia: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-leia.zip
Matrix: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-matrix.zip

**Comment by didamsko** [comment]
Thanks for the support Bas.
