### ISSUE TITLE
Retrospect asking to input PIN. Dplay (Sweden)

### ISSUE THREAD

**Issue by Method47** [retrospect-addon/plugin.video.retrospect#1419]
### Describe the bug

Whenever i choose to play an episode on the channel DPLAY (Sverige) retrospect is requesting a pin code. I'm not aware of any pin code to be used in this case.

## Expected Behavior

The episode should play as usual.

## Actual Behavior

It requests PIN code before playing

### To Reproduce

1.  Choose DPLAY sverige
2. Any episode to play.
3. It requests pin.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:
- Retrospect version:

**Comment by basrieter** [comment]
Dplay requires a username and password. You configure this via the Retrospect add-on settings. 

Password are stored in the Retrospect Vault which is protected with a PIN: https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Storing-Passwords-in-the-Retrospect-Vault

**Comment by basrieter** [comment]
I created a short video on how it should work if you never used the Vault before (the Vault will be initialized with a new PIN): 

https://youtu.be/Z5xIkE4Qe70

If the Vault was already initialized it will only ask for a PIN once.
