### ISSUE TITLE
SVT Öppet Arkiv "no stream associated"

### ISSUE THREAD

**Issue by bisonium** [retrospect-addon/plugin.video.retrospect#1421]
### Describe the bug
Many of the programs in Öppet arkiv are not playable due to "item not associated with any stream", propably meaning the path is not correct.

## Expected Behavior

Klicking a program the program should start.

## Actual Behavior

Most of the programs are not associated with any stream and only an error message appears.

## Possible Fix

Uppdating paths to the programs mayby?

### To Reproduce

1.  Öppet Arkiv->Genrer->Humor->Dolda kameran->no one of the listed programs will start. (as well as for many others in Öppet Arkiv. Only some of the programa start actually.
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.7
- Retrospect version:  5.2.11

**Comment by basrieter** [comment]
Please provide a logfile.

**Comment by bisonium** [comment]
[kodi.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/5213288/kodi.log)

**Comment by bisonium** [comment]
Oh, sorry, I hope it is accessible now.

**Comment by basrieter** [comment]
Nope, I need a debug retrospect.log: https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Logging

**Comment by bisonium** [comment]
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/5213654/retrospect.log)

**Comment by bisonium** [comment]
oh, now . Did not know the retrospect uses its own log.  Nice!

**Comment by bisonium** [comment]
The url seems correct. But Retrospect still cannot open the videos.

**Comment by bisonium** [comment]
I accidentally clicked the Close button. Opened it again.

**Comment by basrieter** [comment]
Thanks but the logfile has no debug information. Please enable debug logging in Retrospect and then try playing again. Then upload the new logfile.

**Comment by bisonium** [comment]
I cant get to the page where I alter the log level for retrospect. . The add-on alternatives ->Advanve does not have that setting anywhere

**Comment by basrieter** [comment]
No,  you need to go to the Retrospect add-on settings. Within Retrospect you can find it in the context menu.

**Comment by bisonium** [comment]
I open Retrospect and chose **Add-on Settings**, but I only see the following. m I at the wrong place?

![Skärmklipp1](https://user-images.githubusercontent.com/71192456/93028234-b7b29600-f612-11ea-8cd0-71934497c0f0.JPG)

![Skärmklipp2](https://user-images.githubusercontent.com/71192456/93028238-bed9a400-f612-11ea-81d0-4deddedc8704.JPG)

![Skärmklipp3](https://user-images.githubusercontent.com/71192456/93028243-c26d2b00-f612-11ea-9198-c3959f82600f.JPG)

**Comment by bisonium** [comment]
Oh, it was scrollable too. :D 
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/5215076/retrospect.log)

**Comment by basrieter** [comment]
Please install this zipfile from the "Install from zip" in Kodi Leia and see if it fixes the issue: https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1421.zip

**Comment by bisonium** [comment]
You are the best! Works like a charm!  Am I the only one having this problem, were you able to reproduce it on your machine? 

How come some episoden within Öppet Arkiv worked one time and the next time they just didn't? 

Will the solution be included in an upcoming version release soon, or shall I hold on to the tag you just sent me, for now?

Thanks alot for you work, impressive response!

/Mattias

**Comment by basrieter** [comment]
It was a generic issue, that I was able to reproduce with the help of your log file. So thanks for that. Oppet Arkiv is moving towards the same video back-end as SVT. So some shows are already moved to the new platform, others are not. It might even depend on what server your requests end up on.

I am waiting to finish up some other changes and will then create a new release that will be in the Kodi repository.

**Comment by bisonium** [comment]
OK! Thank you so much for laying time on this, and thanks for the explaination. So funny I did not see any other comments about the issue while googling around. :) 

Looking forward to the upcoming release, using the pre-released tag in the meantime.

Best regards
Mattias

**Comment by basrieter** [comment]
You are welcome. The issue will be closed automagically when I push the changes to the Master branch
