### ISSUE TITLE
 SE: SvtPlay - remove time, title, episode from description in Channels folder items (Kanaler)

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1422]
### Is your feature request related to a problem? Please describe

Remove time, title, episode from description in Channel folder items (Kanaler) to be consistent with other folders.

### Describe the solution you'd like

change in chn_svt.py from row ~917 in  def create_channel_item(self, channel):
from:

        if episode:
            title = "%s: %s - %s (%02d:%02d - %02d:%02d)" \
                    % (channel_title, title, episode,
                       start_time.tm_hour, start_time.tm_min, end_time.tm_hour, end_time.tm_min)
            description = "{:02d}:{:02d} - {:02d}:{:02d}: {} - {}\n\n{}".format(
                start_time.tm_hour, start_time.tm_min, end_time.tm_hour, end_time.tm_min,
                title, episode or "", description)
        else:
            title = "%s: %s (%02d:%02d - %02d:%02d)" \
                    % (channel_title, title,
                       start_time.tm_hour, start_time.tm_min, end_time.tm_hour, end_time.tm_min)
            description = "{:02d}:{:02d} - {:02d}:{:02d}: {}\n\n{}".format(
                start_time.tm_hour, start_time.tm_min, end_time.tm_hour, end_time.tm_min,
                title, description)

to:

        if episode:
            title = "%s: %s - %s (%02d:%02d - %02d:%02d)" \
                    % (channel_title, title, episode,
                       start_time.tm_hour, start_time.tm_min, end_time.tm_hour, end_time.tm_min)
        else:
            title = "%s: %s (%02d:%02d - %02d:%02d)" \
                    % (channel_title, title,
                       start_time.tm_hour, start_time.tm_min, end_time.tm_hour, end_time.tm_min)

### Additional context

Current:
![chn_svt_before](https://user-images.githubusercontent.com/46671821/93078962-a9549080-f68b-11ea-8ab4-868991b8e30b.png)

After:
![chn_svt-after](https://user-images.githubusercontent.com/46671821/93078984-afe30800-f68b-11ea-94e5-1239b0615513.png)

**Comment by basrieter** [comment]
I guess this does make sense. Let me check.

**Comment by basrieter** [comment]
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1422.zip with Kodi Leia.

**Comment by matsarv** [comment]
Great, It looks much better now. 
Ready for release.
