### ISSUE TITLE
Laatste zin ondertiteling NPO wordt afgekapt bij drie zinnen

### ISSUE THREAD

**Issue by PhyxionNL** [retrospect-addon/plugin.video.retrospect#1424]
Op zowel de RPi als op mijn eigen PC heb ik een probleem met de ondertitels van NPO. Wanneer er drie zinnen in beeld komen te staan dan snoept ie tekst van de laatste zin af. Deze staat dan maar gedeeltelijk in beeld (meestal de laatste 5-6 tekens, maar bij kortere zinnen vaak maar 1-2 tekens).
Als voorbeeld: https://www.npostart.nl/hunted/24-10-2016/AT_2064738 op 1:11

Via NPO website:
![image](https://user-images.githubusercontent.com/7643972/93215019-2eac7380-f766-11ea-8be9-61305e62dfa0.png)

Via Kodi:
![image](https://user-images.githubusercontent.com/7643972/93215148-513e8c80-f766-11ea-8682-e81318d97940.png)

Debug log:
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/5225093/retrospect.log)

De ondertitels lijken verkeerd te worden opgeslagen in het SRT bestand, want daar zit de fout ook in:
`19
00:01:11,040 --> 00:01:15,160
Broer en zus Ike en Babette
zijn van de radar verdwenen
.`

Zie ook:
[AT_2064738.nl.srt.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/5225111/AT_2064738.nl.srt.txt)

**Comment by basrieter** [comment]
Dat zal ik even kijken. Denk ik dat het niet zo lastig is om te fixen.

**Comment by basrieter** [comment]
Zou je deze kunnen installeren en kunnen kijken of het dan wel werkt? https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1424.zip

Ook graag even `userdata\addon_data\plugin.video.retrospect\cache\` leeg gooien, anders pakt hij daar de reeds bestaande uit.

**Comment by PhyxionNL** [comment]
![image](https://user-images.githubusercontent.com/7643972/93229954-7091e580-f777-11ea-815a-5c0ec317fd0a.png)

Top, werkt nu 👍

**Comment by basrieter** [comment]
Mooi zo

**Comment by basrieter** [comment]
Ik ga proberen vanavond of morgen een release te doen.
