### ISSUE TITLE
Artifacts bij NPO start

### ISSUE THREAD

**Issue by digitall12** [retrospect-addon/plugin.video.retrospect#1425]
### Describe the bug

In NPO start krijg ik bij het programma: Je had er bij moeten zijn, steeds veel artifacts in beeld. Het beeld bevriest als het ware. Audio loopt wel door. Ik heb dit bijvoorbeeld niet bij een programma  als Mr Frank Visser: Wordt u al geholpen? 

## Expected Behavior

Het beeld is normaal gesproken vloeiend. 

## Actual Behavior

Nu krijg ik constant artifacts. Beeld bevriest. 

### To Reproduce

1. NPO start : Je had er hij moeten zijn 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

https://paste.kodi.tv/memifagara

## Additional context or screenshots (if appropriate)

Ik heb wat geprobeerd om met de instellingen te spelen. Maximum stream bitrate en zo. Maar dat helpt niet. 

### Your Environment
Used Operating system:

 - [x] Android TV 9 
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.8
- Retrospect version: 5.2.12

**Comment by basrieter** [comment]
Graag een debug retrospect.log

**Comment by digitall12** [comment]
Sorry bas, Duurde even voordat ik wist hoe ik een log moest sturen. Als het
goed is heb je 'm binnen op: https:://paste.kodi.tv/inogotedam
Wat ik ook nog wil zeggen: ik ben heel erg blij met je mooie Retrospect
project. Alleen jammer dat er steeds minder te zien valt, maar daar kun jij
niets aan doen.


Mvg Ron Sebregts

Op ma 21 sep. 2020 om 09:03 schreef Bas Rieter <notifications@github.com>:

**Comment by basrieter** [comment]
Er ontbreekt de daadwerkelijke playback.

**Comment by digitall12** [comment]
Ik hoop het nu goed te hebben gedaan:
Https://paste.Kodi.tv/memifagara

Ik heb de stream op de achtergrond laten afspelen. 

Gr. Ron Sebregts. 

Verstuurd van mijn iPhone.

**Comment by basrieter** [comment]
Heb je de hele video lang artifacts?

**Comment by digitall12** [comment]
Telkens na 10 à 15 seconden over de hele video. De ene keer is het erger dan de andere keer.

**Comment by basrieter** [comment]
En is dat bij elke aflevering?

**Comment by digitall12** [comment]
Ja dat is bij alle andere afleveringen ook zo.

**Comment by digitall12** [comment]
![Uploading 4D98121C-5A39-4CAC-8A45-DDB31FDE2D52.png…]()

**Comment by basrieter** [comment]
Lijkt meer op een issue met bandbreedte, waardoor hij terugschakelt naar een hele lage resolutie. Ik heb het hier op 4 systemen bekeken, maar nergens soortgelijke problemen. Heb jij nog meer systemen om het op te testen?

**Comment by digitall12** [comment]
Ik heb net even Kodi op Windows geïnstalleerd. En daarop Kodi 18.8 en Retrospect. 
NPO opgestart en warempel: geen artifacts! 
Zal het aan de netwerkkabel liggen?

**Comment by basrieter** [comment]
Netwerk of wellicht de Android versie? Kodi gebruikt de mediacodec van Android voor het afspelen van Widevine content.

**Comment by digitall12** [comment]
Dit is een nieuwe Sony Bravia waarop ik het afspeel. Met de nieuwste software. 
Ook het netwerk is in orde. 
Ik kan hieruit opmaken dat ik er niets aan kan doen?

**Comment by basrieter** [comment]
Daar lijkt het wel op. Heeft enkel NPO dit? 

Denk dat met meer iets is voor de InputStream Adaptive add-on of Kodi zelf. Heb het forum van Kodi al eens doorzocht?

**Comment by digitall12** [comment]
Ik ga het forum van Kodi doorzoeken. Dank je wel!

**Comment by basrieter** [comment]
Ik hoor het graag hoe het afloopt.

**Comment by digitall12** [comment]
Dat is goed. Zal ik zeker doen.
