### ISSUE TITLE
Dplay (Sverige) Login not working

### ISSUE THREAD

**Issue by appelgran** [retrospect-addon/plugin.video.retrospect#1426]
### Describe the bug

Logging in with a free dplay se account doesn't seem to work. 

## Expected Behavior

The free to watch (with an account) video should play.

## Actual Behavior

I got the failed login message and the video doesn´t play.

## Possible Fix

To me the point of failure seems to be here:
urihandler.py GET 200 OK "https://disco-api.dplay.se/users/me"
urihandler.py POST 200 OK https://...arkoselabs.com
chn_subs.py "Error logging in. Invalid Arkose token."

### To Reproduce

1. Install Kodi 18.8 and Retrospect 5.2.12
2. Provide login credentials for dplayse
3. Try playing free-with-account-to-play video

### Debuglog

The **debug** retrospect.log can be found here:
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/5275184/retrospect.log)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [x] Windows (versions and log is from Windows)
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.8
- Retrospect version: 5.2.12

**Comment by basrieter** [comment]
That is correct. The changed something and it seems rather impossible for me to fix it from The Netherlands. But I am trying.

**Comment by Dis90** [comment]
They started to use ArkoseLabs funcaptcha. I tried to use this https://github.com/davidbaszucki/py-funcaptcha to get my Dplay addon's login to work but no luck so far.

**Comment by Sopor** [comment]
I don't get this captcha if i login from a Swedish IP address.

**Comment by basrieter** [comment]
Please try this version https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1426.zip (Kodi Leia only)

I think it should work for Swedish IP addresses. But not outside of Sweden. If you logon to Dplay.se via the website and you get a Captcha it won't work from Retrospect. Please very this in case it still does not work.

**Comment by appelgran** [comment]
@basrieter That version works for me! :) From a Swedish IP address on Windows. I'll try it out on my pi Libreelec as well and let you know.

I have not had to do any captcha on dplay.se.

**Comment by Sopor** [comment]
Same here, it works!
