### ISSUE TITLE
VRT NU doesn't show all titles

### ISSUE THREAD

**Issue by peno64** [retrospect-addon/plugin.video.retrospect#1427]
### Describe the bug

The A-Z index doesn't show all programs

## Expected Behavior

All programs should be shown

## Actual Behavior

Only a limited list is shown

### To Reproduce

1.  In Retrospect, goto VRT NU
2. Choose Titles with  'U'
3. Only 3 titlles are shown: Uki, Une soer, Universiteit van Vlaanderen

It should show alot more titles. For example Undercover should be there. See https://www.vrt.be/vrtnu/a-z/#letter-u
There you also see Undercover and Undercoder (met audiodescriptie)

### Debuglog

The **debug** retrospect.log can be found here:

https://paste.kodi.tv/umuyugeviz.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.8
- Retrospect version: 5.2.12

**Comment by basrieter** [comment]
Please be more specific on which ones are missing. Give some examples.

**Comment by peno64** [comment]
I looked further and in fact I only find this example at first sight.
Only for the U index there are only Undercover and Undercover (met audiodescriptie) missing.
I initially thaught that there would be much more titles with U but there are no more.
I also thaught it maybe was because of the ( and ) in the description but even that is not the reason because other ones with  ( and ) are shown so I don't see a reason why it is aparantly only for the U that this happens.
Note that the addon VRT NU does show these titles and of course also the vrt nu website is showing them.

**Comment by basrieter** [comment]
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1427.zip and install from zip in Kodi Leia

**Comment by peno64** [comment]
Yes this solved the problem.
Thank you
