### ISSUE TITLE
Kijk.nl alleen nog 720p

### ISSUE THREAD

**Issue by kengithub9** [retrospect-addon/plugin.video.retrospect#1428]
SInds retrospect 5.2.1 kan ik bij Kijk.nl alleen de video's in 720p kijken, mijn internet verbinding is snel gewoon want bij de addon van VTM kan ik alles in 1080p bekijken. Het is niet echt een probleem maar misschien kan het worden aangepast aangezien via kijk.nl website alles 1080p beschikbaar is.

Used versions:
- Kodi version: 18.8
- Retrospect version: 5.2.12

**Comment by basrieter** [comment]
Graag even een **debug** retrospect.log waarin het afspelen van een item staat. Dus debug logging aanzetten, afspelen en dan uploaden

**Comment by kengithub9** [comment]
Hierbij de debug link van retrospect: https://paste.kodi.tv/cujuxayiji

**Comment by basrieter** [comment]
Het lijkt erop dat er enkel 720p wordt aangeboden:

```
#EXTM3U
#EXT-X-VERSION:1
## Created with Unified Streaming Platform (version=1.10.18-20255)

# variants
#EXT-X-STREAM-INF:BANDWIDTH=563000,CODECS="mp4a.40.2,avc1.77.30",RESOLUTION=448x252,FRAME-RATE=25,VIDEO-RANGE=SDR
M02Inq5o4Kp-index-audio=160000-video=370313.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=955000,CODECS="mp4a.40.2,avc1.77.30",RESOLUTION=640x360,FRAME-RATE=25,VIDEO-RANGE=SDR
M02Inq5o4Kp-index-audio=160000-video=740051.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1781000,CODECS="mp4a.40.2,avc1.77.30",RESOLUTION=768x432,FRAME-RATE=25,VIDEO-RANGE=SDR
M02Inq5o4Kp-index-audio=160000-video=1519338.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3392000,CODECS="mp4a.40.2,avc1.77.31",RESOLUTION=1280x720,FRAME-RATE=25,VIDEO-RANGE=SDR
M02Inq5o4Kp-index-audio=160000-video=3039575.m3u8

# variants
#EXT-X-STREAM-INF:BANDWIDTH=170000,CODECS="mp4a.40.2"
M02Inq5o4Kp-index-audio=160000.m3u8
```

**Comment by kengithub9** [comment]
Wel gek dat je met gemistdownloader wel 1080p kunt opslaan, maar geen probleem.

**Comment by basrieter** [comment]
Ik heb het gevonden. Ga het fixen.

**Comment by basrieter** [comment]
Zou je deze zip eens kunnen installeren via de "Install from zip" optie: https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1428.zip. Hij werkt enkel voor Kodi Leia.

Het kan zijn dat Kodi de oude streams onthouden heeft, dus pak even een nieuwe aflevering om te testen.

**Comment by kengithub9** [comment]
Kijk.nl is weer in 1080p beschikbaar, bedankt voor het fixen.

**Comment by basrieter** [comment]
Super! Ga ik het mergen en een release maken.
