### ISSUE TITLE
Missing show(TV3 Play)

### ISSUE THREAD

**Issue by bubbleboyy** [retrospect-addon/plugin.video.retrospect#1430]
### Describe the bug

The show Charterfeber is missing from the program list.

### To Reproduce

1. TV3 Play 
2. Charterfeber is missing from the program list
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 5.2.13
- Retrospect version: 18.8

**Comment by bubbleboyy** [comment]
Do you need a debug log for this problem?

**Comment by basrieter** [comment]
Perhaps. Let me check first.

**Comment by bubbleboyy** [comment]
Viafree videos dont stop when the duration run out. Maybe thats a issue with kodi?

**Comment by bubbleboyy** [comment]
Viafree videos dont stop when the duration have run out. Can you fix that problem or is it a software problem?

**Comment by bubbleboyy** [comment]
Viafree videos dont stop when the duration have run out. Is that a software problem?

**Comment by basrieter** [comment]
Ok, please include a DEBUG retrospect.log because I can't find "Charterfeber" on https://www.viafree.se/program/

**Comment by matsarv** [comment]
@basrieter, you will find it on https://www.viafree.no/programmer/

**Comment by basrieter** [comment]
That would have been nice to now that it was Norwegian.

**Comment by bubbleboyy** [comment]
Sorry, I would have included it.

**Comment by basrieter** [comment]
Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1430.zip using the "Install from ZIP" option in Kodi Leia (not Matrix).

It should fix TV4 Norge and adds a ViaFree.no channel with all it's content

**Comment by Snaah** [comment]
> Viafree videos dont stop when the duration have run out. Is that a software problem?

This happens on Swedish TV3 Play too. I recall it was like this with the news program Aktuellt on SVT Play a couple of years ago.

**Comment by bubbleboyy** [comment]
Thanks, Its working now.





> > Viafree videos dont stop when the duration have run out. Is that a software problem?
> 
> This happens on Swedish TV3 Play too. I recall it was like this with the news program Aktuellt on SVT Play a couple of years ago, but you fixed it, @basrieter .
Is this a issue for inputstream adaptive?

**Comment by basrieter** [comment]
> Thanks, Its working now.
> 
> > > Viafree videos dont stop when the duration have run out. Is that a software problem?
> > 
> > 
> > This happens on Swedish TV3 Play too. I recall it was like this with the news program Aktuellt on SVT Play a couple of years ago, but you fixed it, @basrieter .
> 
> Is this a issue for inputstream adaptive?

Please send me a debug log for playing back such an item.

**Comment by bubbleboyy** [comment]
I have sent the logfiles now. It seems like its something wrong with the audio stream.

**Comment by matsarv** [comment]
> Please send me a debug log for playing back such an item.

Looked the TV-show, time continue after ended, manual stop the TV-show, see [ProgramNeverEnds.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/5392499/ProgramNeverEnds.zip)
I hope this will help you.

**Comment by basrieter** [comment]
Let me check, but let's not try to mix discussions. Perhaps we should create a separate issue for this.
