### ISSUE TITLE
SE: Viafree use wrong subtitle language for some TV-shows

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1431]
### Describe the bug

Viafree use the wrong subtitle language for some TV-shows (e.g. The Good Doctor).
If the TV-show have one or have more than one language in the JSON and (language: sv) is located in (/embedded/subtitles/0/data/language : sv)  then the correct subtitles is used.

The attached files will show that the TV-show will have danish subtitles (/embedded/subtitles/0/data/language : da) since the swedish is located under (/embedded/subtitles/3/data/language : sv)
It seems that the fist (0) in JSON is select for subtitle.

Cache is cleared under Advanced settings before the tests.

## Expected Behavior

Show swedish subtitles

## Actual Behavior

Showing random subtitles

### To Reproduce

1.  Select swedish Viafree
2.  Select The Good Doctor

### Debuglog

The **debug** retrospect.log and cache-folder can be found here:
[TheGoodDocktor.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/5385575/TheGoodDocktor.zip)

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.8
- Retrospect version: 5.2.13

**Comment by basrieter** [comment]
Your logfile does not show any playback?

**Comment by matsarv** [comment]
OK, let's try again:
[retrospect-log.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/5386289/retrospect-log.zip)

**Comment by basrieter** [comment]
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1431.zip using the "Install from zip" option from Kodi Leia (not Matrix).

**Comment by matsarv** [comment]
I've tested 3 different TV shows and now they all have swedish subtitles.
Ready for release. Good work!

**Comment by basrieter** [comment]
Great!
