### ISSUE TITLE
Dplay

### ISSUE THREAD

**Issue by duck7000** [retrospect-addon/plugin.video.retrospect#1432]
Simple question:
Why is there no option for Dplay Netherlands? Can this be added?

I consider to get a abo on Dplay but it would be very nice to have it on kodi through this addon if possible

**Comment by basrieter** [comment]
Because I never knew dplay.nl existed 🤔 I will see what I can do

**Comment by duck7000** [comment]
Ah Jep it does exist.
Thanks for looking in this.
