### ISSUE TITLE
Viafree videos never end automatically

### ISSUE THREAD

**Issue by bubbleboyy** [retrospect-addon/plugin.video.retrospect#1433]
### Describe the bug

Video dont stop when the duration have run out.

### To Reproduce

1. Play any viafree video.
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
Retrospect: https://paste.kodi.tv/ujicamijoy
Kodi: https://paste.kodi.tv/lojixixuso
### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.18
- Retrospect version: 5.2.13

**Comment by orfeous1** [comment]
Still issues, video/episodes does not stop when episode are finished. TV3 Sweden.

**Comment by Snaah** [comment]
@basrieter  Any chance you can look into this?

**Comment by basrieter** [comment]
I would need new logs for Kodi Matrix with the most recent InputStream Adaptive add-on installed.

**Comment by bubbleboyy** [comment]
Here's some new logs for retrospect and kodi matrix with latest inputstream adaptive add-on installed.
Retrospect 5.4.0: https://paste.kodi.tv/mahekeguqa
Kodi 19.1: https://paste.kodi.tv/huvazihosu

**Comment by basrieter** [comment]
Ok, so what happens after the video should stop?

**Comment by Snaah** [comment]
It just continues after the programme is over, with no sound or picture. It doesn't stop and return to Kodi/Retrospect automatically.

**Comment by bubbleboyy** [comment]
When I played #flickstreck episode 1 there was a noise when the video went black. The video picture and the playing time was not in sync. The video is 20:00, but the video in retrospect is 19:52.

**Comment by basrieter** [comment]
As far as I can tell, this is Kodi not stopping or the server not stopping to send data. I can't really fix that from Retrospect.

**Comment by Snaah** [comment]
Okay. That's a bummer. Possible to fix in Kodi?

**Comment by basrieter** [comment]
Possibly. You should create an issue in the InputStream Adaptive add-on github (https://github.com/xbmc/inputstream.adaptive) and provide them with a detailed debug log that contains the InputStream Adaptive and FFMPEG logging at the start of the stream and the end.

**Comment by Sopor** [comment]
It seems that SVTPlay have the same issue. I have to stop it manually or it will continue in infinity.

**Comment by basrieter** [comment]
It turns out to be related to the HLS streams. Asking in the Team Kodi slack whether we can find the source of the issue. For SVT I can force it to use MPD.

**Comment by basrieter** [comment]
Closed with 991bbc4
