### ISSUE TITLE
NPO Start en RTL hebben extreem veel artifacts na 10 seconden spelen.

### ISSUE THREAD

**Issue by meganiekje** [retrospect-addon/plugin.video.retrospect#1434]
Ik heb een Samsung Tab s7+ (fantastische tablet) maar die heeft problemen met alle NPO start en RTL video's. 
Kijk.nl heeft geen last. De tablet heeft Android 10.0.0 API 29 (kernel 4.19.81- 19543082), kodi 18.8.0, Retro 5.2.13.
De ondertilels hebben geen artifacts, het zit in de video's zelf. 
Ik heb nog 3 andere versies van kodi op tablets, PC's en telefoons en daar doen NPO Start en RTL het prima.
De logfile van Retrospect is toegevoegd.
[retrospect log.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/5397562/retrospect.log.zip)

**Comment by basrieter** [comment]
Zodra het begint te spelen, dan is het toch echt een issue met Kodi. Ik heb weinig controle over het decoden. Zeker als het op andere devices wel werkt, dan kan ik er weinig aan doen.

**Comment by meganiekje** [comment]
Hoi Bas,
Dank voor je snelle reactie !
Ik was er al bang voor, dat je er niks aan kan doen. 
Heb je een tip, waar ik wel moet zijn ?
Bedankt voor je fantastische werk, zodat mijn andere apparaten perfect werken !!!

**Comment by basrieter** [comment]
Ik zou het forum van Kodi eens proberen

**Comment by basrieter** [comment]
Heb het even binnen het Kodi Team gevraagd en het is een bekend issue, maar iets waarvan we (Team Kodi) de oorzaak nog niet gevonden hebben.

**Comment by basrieter** [comment]
Ok, wat vraagjes uit het team: als je inde Input Stream Adaptive instellingen aanzet dat je enkel Video wilt (en dus geen audio), heb je dan ook nog artifacts?

**Comment by meganiekje** [comment]
Als ik bij inputstream adaptive instellingen de 'media' van All naar video zet, dan heb ik GEEN artifacts, maar ook geen geluid, natuurlijk.
Kan ik nog meer tests doen om te helpen ?

**Comment by basrieter** [comment]
Dat is in ieder geval even handig om te weten. Ik ga in overleg.

**Comment by basrieter** [comment]
It seems that only the first 150 items are retrieved.....will fix that.

**Comment by basrieter** [comment]
Er komt een test build van Kodi voor je, die wellicht het probleem oplost

**Comment by meganiekje** [comment]
Ik kan niet wachten ;))
Waar kan ik de testbuild vinden ?

Op zo 25 okt. 2020 18:08 schreef Bas Rieter <notifications@github.com>:
