### ISSUE TITLE
 svenska utbildningsradion (ur play) is currently broken

### ISSUE THREAD

**Issue by sopparus** [retrospect-addon/plugin.video.retrospect#1435]
### Describe the bug
svenska utbildningskanalen (UR PLAY) doesnt work anymore.
Tested on both rpi4/libreelec and on my windows desktop.
below is a log snippet from kodi.

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/moxujegaza

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x ] Raspberry-Pi
 - [x ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.8
- Retrospect version: 5.2.13

**Comment by basrieter** [comment]
Please attach (don't copy paste) a full DEBUG Retrospect.log file. Not just a Kodi file.

**Comment by sopparus** [comment]
sorry, here is log https://pastebin.com/8JdheW9C
it seems to happend on every single video so should be easy to reproduce. thanks for your awesome work

**Comment by basrieter** [comment]
> sorry, here is log https://pastebin.com/8JdheW9C
> it seems to happend on every single video so should be easy to reproduce. thanks for your awesome work

This is not a Retrospect DEBUG build. Please enable debug logging in Retrospect, playback and upload a logfile using the build in functionality.

**Comment by sopparus** [comment]
ok, here it goes https://paste.kodi.tv/moxujegaza

**Comment by basrieter** [comment]
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1435.zip with Kodi Leia. Just use the "Install from zip" option.

**Comment by sopparus** [comment]
yes, that fixes it. thanks!

**Comment by Snaah** [comment]
I can confirm it's working, but I just discovered problems with the listings for UR Play. Retrospect doesn't list programs with titles starting with 0-9, G, I, Q, O, W, Å, Ä or Ö.

**Comment by basrieter** [comment]
> I can confirm it's working, but I just discovered problems with the listings for UR Play. Retrospect doesn't list programs with titles starting with 0-9, G, I, Q, O, W, Å, Ä or Ö.

Examples please

**Comment by Snaah** [comment]
> > I can confirm it's working, but I just discovered problems with the listings for UR Play. Retrospect doesn't list programs with titles starting with 0-9, G, I, Q, O, W, Å, Ä or Ö.
> 
> Examples please

[00-talets USA](https://urplay.se/serie/208218-00-talets-usa)
[Gatsmart](https://urplay.se/serie/171736-gatsmart)
[I matindustrins spår](https://urplay.se/serie/208296-i-matindustrins-spar)
[Odens rike - meänkieli](https://urplay.se/serie/152851-odens-rike-meankieli)
[Que pasa](https://urplay.se/serie/214815-que-pasa)

As with similar previous problems, they can be found using the search function.

@matsarv You also found something?

**Comment by matsarv** [comment]
> @matsarv You also found something?

I think that Bas has found the problem.
Up to 150 items will be shown in the folders right now. Lets see what he comes up with.

**Comment by basrieter** [comment]
Please download https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1435.zip again and install. The main list should be around 1500 items now. However, this does take 10 HTTPS calls, so it takes a bit longer.

**Comment by Snaah** [comment]
@matsarv Ok.

A-Ö listings fixed, not all categories. Alla program, Drama, Hälsa & relationer, Natur & resor, Utbildning & media.

**Comment by basrieter** [comment]
If you try https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1435.zip again (redownload), it should now list all categories.

**Comment by matsarv** [comment]
All the categories are now working. Great work!

**Comment by Snaah** [comment]
Yes, just like matsarv said everything is working. As always, fantastic work, @basrieter!
