### ISSUE TITLE
SE: UR Play - No episodes found in some categories

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1436]
### Describe the bug

When select some of the categories in .:Categories:. it returns 0 items.

Affected categories are:

- All program
- Drama
- Hälsa & relationer
- Natur & resor
- Utbildning & media

## Expected Behavior

Show items in selected category 

## Actual Behavior

Retrospect Error - No episodes found ....

### To Reproduce

1. Select UR Play
2. Select Categories
3. Select Drama

### Debuglog

The **debug** retrospect.log can be found here: https://paste.kodi.tv/nulotanaro

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.8
- Retrospect version: 5.2.13 + fix #1435

**Comment by basrieter** [comment]
Please see #1345

**Comment by Snaah** [comment]
#1435

**Comment by basrieter** [comment]
I am
