### ISSUE TITLE
Having issues with inputstream.adaptive, kodi, retrospect

### ISSUE THREAD

**Issue by orfeous1** [retrospect-addon/plugin.video.retrospect#1437]
Having some issues with Kodi and Retrospect. Dont know where it fails.
Got a notice about someting with inputstream.adaptive... version... and something more.
Did not pay attention. Was not logging with debug enabled that time.
When i start Kodi and Retrospect now no error messages are shown as popups like they did last time.

Using Kodi 20201015 and Retrospect 5.2.13-matrix.1

Trying to start latest bonde söker fru from tv4play but got an error.

Attaching logs.
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/5418380/retrospect.log)
[kodi.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/5418381/kodi.log)

**Comment by basrieter** [comment]
```2020-10-21 21:24:48.582 T:5604    ERROR <general>: EXCEPTION: Unknown addon id 'inputstream.adaptive'.
2020-10-21 21:24:48.588 T:5604    FATAL <general>: Traceback (most recent call last):
                                                     File "C:\Users\Anton\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\envcontroller.py", line 128, in widevine_lib
                                                       addon = xbmcaddon.Addon(input_stream_adaptive_id)
                                                   RuntimeError: Unknown addon id 'inputstream.adaptive'.
```
Do you actually have this add-on?

**Comment by orfeous1** [comment]
Yeah, i saw that too.
I have not uninstalled anything. It might have been removed when i update Kodi.
In Retrospect dependencies it tells me that inputstream.adaptive is installed.

Found my old logs with lower loglevel.
I will attach the log from Kodi, There is info about version.
[kodi.old.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/5418708/kodi.old.log)

**Comment by orfeous1** [comment]
Started Kodi, Navigated to My Addons and All addons. There is an X showing that Inputstream.Adaptive is not activated.
When i try to activate it, i got an error about that it is not compatible with this version.
So, its installed but cant be activated with my Kodi version it seems.

**Comment by orfeous1** [comment]
Deleted Kodi.log and started up Kodi again. Selecting My Addons - All, Inputstream.Adaptive, and then Activate.
After that i click Versions. It says that there are no versions.
[kodi.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/5418874/kodi.log)

Attaching Kodi.log.

I can try and uninstall Kodi and install Kodi and Retrospect from scratch again since ive updated Kodi and Retrospect several times. That might solve the problem.

**Comment by orfeous1** [comment]
Problem/issue now solved with Inputstream.Adaptive 2.6.1

**Comment by basrieter** [comment]
Great!
