### ISSUE TITLE
Add TV4Play.se LIVE

### ISSUE THREAD

**Issue by Sopor** [retrospect-addon/plugin.video.retrospect#1439]
[It seems that Com Hem will close TV4 (and some other channels) at 00:00 1/11 2020 if they can't agree on a new agreement.](https://www.aftonbladet.se/nojesbladet/a/pAAr8E/tv4-kan-forsvinna-vid-midnatt-for-comhems-kunder)

It would be nice if [TV4 LIVE](https://www.tv4play.se/program/tv4/12513002) could be added to Retrospect even if it is for a limited time.

**Comment by Sopor** [comment]
[It seems that they have extended the time to 2020-11-02 00:00 to close the agreement and avoid that 2.1 million customers lose TV4.](https://www.svt.se/kultur/tva-miljoner-kunder-kan-forlora-tv4)

**Comment by Snaah** [comment]
Is the TV4 Live link perhaps limited to Comhem IPs? I can't access it with my Ownit IP.

**Comment by Sopor** [comment]
I can watch this https://www.tv4play.se/program/tv4/12513002

**Comment by Snaah** [comment]
Now it's working here too! Let's hope they never close that agreement. 😂 Would be great to have this in Retrospect temporary.

**Comment by Sopor** [comment]
Now they have extended it to 23.59 the third of November

**Comment by Sopor** [comment]
I'm closing this because you should be able to see TV4 in `Currently playing` when they decides to show it.
