### ISSUE TITLE
VRT NU doesn't work anymore

### ISSUE THREAD

**Issue by peno64** [retrospect-addon/plugin.video.retrospect#1440]
### Describe the bug

None of the content of VRT NU plays.
For example, Het journaal, Het journaal 19u from today (02/11)

## Expected Behavior

Programs should play. They do via the website and via the vrt nu addon.

## Actual Behavior

A message appears "Cannot start playback"

## Possible Fix

Note that the retrospect.log shows:

20201102 21:58:24 - [DEBUG   ] - cachehttpadapter.py  - 46   - Retrieving data from: https://www.vrt.be/vrtnu/a-z/het-journaal/2020/het-journaal-het-journaal-19u-20201102.mssecurevideo.json
20201102 21:58:25 - [DEBUG   ] - cachehttpadapter.py  - 138  - Found cache-control and etag data: {'max-age': 604800}
20201102 21:58:25 - [ERROR   ] - urihandler.py        - 542  - GET failed with '410 Gone' (0:00:00.153117) for https://www.vrt.be/vrtnu/a-z/het-journaal/2020/het-journaal-het-journaal-19u-20201102.mssecurevideo.json
20201102 21:58:25 - [DEBUG   ] - jsonhelper.py        - 35   - Removing non-Json wrapper
20201102 21:58:25 - [CRITICAL] - videoaction.py       - 101  - Could not playback the url

### To Reproduce

1.  VRT NU
2. Titles with 'H'
3. Het journaal
4. Het journaal 19u 02/11/2020
### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/uqipucezec.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.8
- Retrospect version: 5.2.14

**Comment by basrieter** [comment]
Just this one, or more?

**Comment by peno64** [comment]
All. All streams have the same issue

**Comment by basrieter** [comment]
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1440.zip

**Comment by peno64** [comment]
All seems to work again. Thx

**Comment by basrieter** [comment]
I also fixed the folders in the last commit. Please redownload and try it.

**Comment by peno64** [comment]
Ah that is great. Folders are there now indeed and the programs all play. Job well done

**Comment by basrieter** [comment]
I will try to get a release out

**Comment by basrieter** [comment]
Closed with b7dec17ac4e2cf748d6352fd68986477439dcb18
