### ISSUE TITLE
Visual Radio for NPO Radio 4 and FunX

### ISSUE THREAD

**Issue by kyl416** [retrospect-addon/plugin.video.retrospect#1441]
You're missing the Visual Radio streams NPO Radio 4 and FunX in NPO Start under Live TV:
https://www.nporadio4.nl/live
https://www.funx.nl/live

Also, you still list the Visual Radio feed for Radio 6 which was discontinued after the rebrand to Soul & Jazz a few years ago

**Comment by basrieter** [comment]
Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1441.zip via the "Install from zip" on Kodi Leia and see if Radio 4 and Fun X now work.

**Comment by kyl416** [comment]
Yes, they work. Thanks.

**Comment by kyl416** [comment]
On a semi-related note, you might want to update the thumb URL for 3FM in chn_nos2010.py.

**Comment by basrieter** [comment]
Ok, let me check the artwork for the NPO channel.

**Comment by basrieter** [comment]
If you re-download https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1441.zip and install it again, it should have new artwork

**Comment by kyl416** [comment]
The updated artwork isn't showing up and the artwork for Radio 1, Radio 2 and Radio 4 no longer appears. Looking at the user_data folder for the images, they appear to be corrupt:
```
~/.kodi/userdata/addon_data/plugin.video.retrospect/textures/channel.nos.nos2010$ file funx.jpg
funx.jpg: HTML document, ASCII text, with very long lines
~/.kodi/userdata/addon_data/plugin.video.retrospect/textures/channel.nos.nos2010$ file radio4image.png
radio4image.png: HTML document, ASCII text, with very long lines
```

**Comment by basrieter** [comment]
where does that come from? That error?

**Comment by basrieter** [comment]
Let me create you a zip in a moment.

**Comment by basrieter** [comment]
[plugin.video.retrospect-issue-1441.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/5505411/plugin.video.retrospect-issue-1441.zip)

**Comment by kyl416** [comment]
Thanks, that works. Although Radio 4 is showing a banner for their Concerten Themakanaal instead of a banner for the main Radio 4 channel.

**Comment by basrieter** [comment]
I will use this one:

![image](https://user-images.githubusercontent.com/1310443/98452109-b1412600-214c-11eb-8aa8-80d6fb3d2c51.png)

**Comment by basrieter** [comment]
If you redownload the zip again, it should work. I updated the CDN

**Comment by basrieter** [comment]
Did you give it a try now @kyl416

**Comment by kyl416** [comment]
Yes, it works, thanks
