### ISSUE TITLE
Kijk -> Lang leve de liefde -> season 2 "error retrieving list of items"

### ISSUE THREAD

**Issue by JaccoR** [retrospect-addon/plugin.video.retrospect#1455]
### Describe the bug

When trying to open Lang de liefde season 2 on kijk, i'll get the error "error retrieving list of items".

## Expected Behavior

See the list of episodes of lang leve de liefde season 2

## Actual Behavior

It doesn't open and i get the error "error retrieving list of items"

## Possible Fix

No idea, maybe the list is missing.

### To Reproduce

1. open national
2. open kijk
3. open the letter L
4. open Lang leve de liefde (the second one)
5. open season 2

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/uxoqoyujix.kodi

### Your Environment
Used Operating system: Windows, but it is also happening on Firestick 4k

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.9
- Retrospect version: newest

**Comment by basrieter** [comment]
Please don't copy paste log files but post them at paste.kodi.org and our the link here. Could you please do that

**Comment by JaccoR** [comment]
> Please don't copy paste log files but post them at https://paste.kodi.tv and our the link here. Could you please do that

Sorry, done!

**Comment by basrieter** [comment]
Please download https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1455.zip and install it from zip within Kodi Leia (not Matrix). Let me know if it works.

**Comment by JaccoR** [comment]
I'm getting the error "The dependency on inputstream.adaptive version 2.0.19 could not be satisfied." when trying to install it from the zip file.

**Comment by basrieter** [comment]
Are you installing it on Kodi Matrix? Of Leia? What platform?

**Comment by JaccoR** [comment]
Leia (18.9), for now on windows, but would also like to add it to my google tv.

**Comment by basrieter** [comment]
That is weird, because that dependency should already be there!

**Comment by JaccoR** [comment]
yes indeed, maybe i accidentally disabled or deleted it or something? I can't find it anywhere. Where can i download it? It's not in kodis repo.

**Comment by JaccoR** [comment]
Just installed it from somewhere else and now it's fixed. Guess I accidentally deleted it. Thanks!

**Comment by basrieter** [comment]
Great, let me close this with a merge then.
