### ISSUE TITLE
NPO Start doesn't play on RPi4 with LibreElec but does play on Windows

### ISSUE THREAD

**Issue by bartmans** [retrospect-addon/plugin.video.retrospect#1457]
I am running latest version of Kodi and Retrospect. As of today (12-12-2020) I am experiencing no playback on NPO Start programs.

I wanted to look at Met het mes op tafel. I got the popup to update Widevine. I did. It ran succesfully. But the programs won't start.

I then checked on a Windows laptop running latest versions of Kodi and Retrospect. The show played.

The log shows errors on loading the widevine library. Log is attached.

[kodi.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/5683794/kodi.log)

**Comment by basrieter** [comment]
Widevine is missing:

![image](https://user-images.githubusercontent.com/1310443/101995897-dbe34900-3ccd-11eb-9ef2-9ca0e52a8d32.png)

Please try to reinstall it.

**Comment by bartmans** [comment]
I did. Tried it from InputHelper, then tried removing the dir /cdm myself via SSH and then reinstalling. When I ssh into the Rpi I see the file at the right location: /storage/.kodi/cdm/libwidevinecdm.so

**Comment by basrieter** [comment]
Did you try a force update: 

![image](https://user-images.githubusercontent.com/1310443/101999989-a4cb6280-3ce2-11eb-880c-e01d5b7e4f15.png)

Or a rollback?

**Comment by bartmans** [comment]
Fixed by using the restore option and choosing the first option.

For reference
It started after an update request for Widevine.
That installed fine, but shows wouldn't play
I then reinstalled using Retrospect option
I then reinstalled using InputstreamHelper
I then removed the /cmd directory and started a show, triggering the install
I then removed and installed using InputstreamHelper
I then restored using InputstreamHelper. This fixed the issue

Shows play again. But I still get errors in the log:
AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!

**Comment by basrieter** [comment]
A new change was pushed to the Input Stream Helper: https://github.com/xbmc/repo-scripts/pull/1780

Perhaps that fixes it. It will take some time to sync through all the mirrors.

**Comment by wanted0** [comment]
I had the same issue. Problem is that the Widevine update chose a wrong architecture of the library:
```
-rwxr--r--    2 root     root       9331116 Dec 12 22:28 libwidevinecdm.so
pi:~/.kodi/cdm # file libwidevinecdm.so
libwidevinecdm.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked,
BuildID[sha1]=7b1ce3ce3c0d0ee6591e1cf2d6cdc61de62c2178, stripped
```

Of course an x86 library won't work on RPi (which is ARM-based).

inputstreamhelper keeps a few backups of the library by default, so it's just a matter of selecting "Restore Widevine CDM library" option and rolling back to one of the older versions.

**Comment by basrieter** [comment]
A new version of the InputStream Helper has already been released.

**Comment by basrieter** [comment]
I assume this can be closed? If not, feel free to comment.
