### ISSUE TITLE
NPO live TV stops after a minute

### ISSUE THREAD

**Issue by Arathonk** [retrospect-addon/plugin.video.retrospect#1458]
NPO live TV stops after a minute,
Is there a way to fix this?

**Comment by basrieter** [comment]
Not without a proper DEBUG retrospect.log and kodi.log.

**Comment by basrieter** [comment]
Seems like it was a thing at NPO? I also experienced it, but now it is working again? Could you double check?

**Comment by Arathonk** [comment]
Yes it's working again!
But a second problem which probably has nothing to do with Restrospect but maybe you have a solution, 
When my girlriends phone connects to the same network as my Raspberry I have the same problems, live TV stops, hangs etc. do you have any clue on why this is happening and if there's a solution?

**Comment by basrieter** [comment]
Perhaps an issue with a router or faulty network?
