### ISSUE TITLE
Cant play episodes of Team bachstad(nrk tv)

### ISSUE THREAD

**Issue by bubbleboyy** [retrospect-addon/plugin.video.retrospect#1459]
### Describe the bug

Cant play epsodes of Team bachstad season 8 episodes 2-4. Only a error message.

## Expected Behavior

Should start the episodes.

## Actual Behavior

Error message about not found any videostream.

### To Reproduce

1. Play team bachstad season 8 episodes 2-4.
2.
3.

### Debuglog

The **debug** retrospect.log can be found here: https://paste.kodi.tv/evegucejew

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.9
- Retrospect version: 5.2.18

**Comment by basrieter** [comment]
Seems to work here. Please clear cache from the Retrospect add-on settings and try again.

**Comment by bubbleboyy** [comment]
I have cleared the cache, but still the same problem. I also reinstalled kodi and retrospect, but the problem remains. Heres the logfiles for retrospect: https://paste.kodi.tv/alihuzumoc and kodi: https://paste.kodi.tv/vojesetaci after the reinstallation.

**Comment by bubbleboyy** [comment]
If it is something wrong with my network it should affect more videostream.

**Comment by basrieter** [comment]
Please try this version: https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1459.zip

Install it in Kodi Leia (Not matrix) via the "Install from zip"

**Comment by bubbleboyy** [comment]
1,2,4 works now, but not 3. Other tv shows and live streams seems to work so far. There is a new subtitle problem with team bachstad. Episode 1 have none available and 2,4 have the same one.

**Comment by bubbleboyy** [comment]
Heres newer logfiles if you need it. Kodi: https://paste.kodi.tv/xoqezaceri Retrospect: https://paste.kodi.tv/igurafoliz

**Comment by bubbleboyy** [comment]
I Just found out that episode 3 dont work on nrks website https://tv.nrk.no/serie/team-bachstad/sesong/8/episode/3

**Comment by bubbleboyy** [comment]
Episode 3 seems to work on nrks website and retrospect now. Only the subtitle problem remains. Also this episode have the same subtitle as 2,4. The subtitle seems to belong to episode 2.

**Comment by basrieter** [comment]
Found the issue with the subtitles. Please redownload https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1459.zip and verify.

**Comment by bubbleboyy** [comment]
There is subtitles in all the episodes now, but they all belongs to episode 2.

**Comment by bubbleboyy** [comment]
Its something weird with the cache. I cleared the cache and now every episode have the subtitle that belong to episode 1.

**Comment by basrieter** [comment]
I see. Fixed it now. Please verify one last time: https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1459.zip

**Comment by bubbleboyy** [comment]
Everything works now. Thanks!
