### ISSUE TITLE
No subtitles in Urplay.se

### ISSUE THREAD

**Issue by hakgle47** [retrospect-addon/plugin.video.retrospect#1460]
### Describe the bug

Urplay.se does not show subtitles anymore. I have subtitles activated in settings. I have also tried to deactivate subtitles and activate them again. It will not help.

## Expected Behavior

Subtitles should be visible on the screen. At least when activated in settings.

## Actual Behavior

No subtitles visible.

## Possible Fix

I have no idea but the name of the textfile containing the subtitles have a very odd name in subtitle settings.

### To Reproduce

1. Start for example Indiens glömda armé (Forgotten Army of India) (https://urplay.se/program/214591-forsta-varldskrigets-asiatiska-soldater-indiens-glomda-arme).
2. Activate subtitles in settings.
3. No subtitles will be diplayed.

### Debuglog

The **debug** retrospect.log can be found here:
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/5719940/retrospect.log)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.9
- Retrospect version: 5.2.18

**Comment by basrieter** [comment]
They moved from WebSRT to TTML. 

Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1460.zip and install it from zip (in Kodi Leia, not Matrxi).

**Comment by hakgle47** [comment]
Thank you for quick response.

Subtitles for Urplay.se is now working again!

Hakgle

**Comment by basrieter** [comment]
Close with e951985c

**Comment by basrieter** [comment]
Will try to do an official release before x-mas.
