### ISSUE TITLE
SE: SVT Play - update of category items.

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1461]
### Is your feature request related to a problem? Please describe

Now that SVT öppet arkiv is merging to SVT Play the "Category" / "Kategorier" has been updated on SVT Play.

### Describe the solution you'd like

See attached file for update.
[category_update.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/5721151/category_update.txt)

**Comment by basrieter** [comment]
Already done: see d6d3abc002e7ad29c4fd8a4eb6e33d3ec71e2004

**Comment by matsarv** [comment]
I think you misunderstood me. This change applies to the manual configuration (attached file) of the category folder for SVT Play in chn_svt.py

The categories should have this content right now (copied from SVT Play):

![category](https://user-images.githubusercontent.com/46671821/102720996-09487c00-42f8-11eb-8444-e8d2909c5e62.png)

If time is running out, you can definitely wait until after Christmas and New Year with this.

**Comment by basrieter** [comment]
Right, I did not get that. I don't see any attached files, just an image. Could you re-attach the file?

**Comment by matsarv** [comment]
Here you go: 
[category_update.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/5721301/category_update.txt)
