### ISSUE TITLE
Kijk.nl Movie folder missing request

### ISSUE THREAD

**Issue by YMaas** [retrospect-addon/plugin.video.retrospect#1462]
I realy enjoy using retrospect but i am missing the movie folder in kijk.nl

Description: When using Retrospect with the channel Kijk.nl there are no movies listed. When you try the search option in kijk.nl and you search for a movie there is no result.

Request: Kijk.nl Movie section as a folder or the posibility to search a movie in this channel

Thank you in advance and for the hard work keeping this addon up to date

KODI LEIA V18.9

**Comment by basrieter** [comment]
I guess that should be no problem. Please download https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1462.zip and install it using the "Install from zip" option? Kijk.nl should then have a Movies (or Films) folder.

**Comment by basrieter** [comment]
I added some more checks for movies not yet available.

**Comment by YMaas** [comment]
I just tried it and it seems to be working ok i can see the movies are listed. I will look at this update later on for a final check on playability but that should be ok.Thank you for the update Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: Bas Rieter <notifications@github.com> Datum: 24-12-2020  00:09  (GMT+01:00) Aan: "retrospect-addon/plugin.video.retrospect" <plugin.video.retrospect@noreply.github.com> Cc: YMaas <yourie.maasland@gmail.com>, Author <author@noreply.github.com> Onderwerp: Re: [retrospect-addon/plugin.video.retrospect] Kijk.nl Movie folder missing request (#1462) 
I added some more checks for movies not yet available.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/retrospect-addon/plugin.video.retrospect/issues/1462#issuecomment-750537431",
"url": "https://github.com/retrospect-addon/plugin.video.retrospect/issues/1462#issuecomment-750537431",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by basrieter** [comment]
You can ignore the past 3 commits, there was a typoo in the commit message.

**Comment by YMaas** [comment]
The addon is working fine all but one moviestreams are working: la vita e bella is not working see picture
![Screenshot_20201225-120225_Kodi](https://user-images.githubusercontent.com/61164604/103133161-2dfe7400-46a9-11eb-8ef2-0b4579ae1d42.jpg)

Only one personal question where in addon script do you check the date if the stream is availible?

Thanks for making the addon better each time

**Comment by basrieter** [comment]
I  think the GraphQL  bugged out on the "La vita e bella". Fixed it so it does not need to fetch new data.

**Comment by basrieter** [comment]
I will add it to the next release. In the mean time zips can be found here:

Kodi Leia: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-leia.zip
Kodi Matrix: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-matrix.zip
