### ISSUE TITLE
Videos not starting

### ISSUE THREAD

**Issue by bcnx** [retrospect-addon/plugin.video.retrospect#1463]
### Describe the bug

Hi, after not having used Kodi for quite some time, I installed a Raspberry Pi with Xbian. 
Retrospect is installed from repo and all the channel settings/accounts have been configured.

## Expected Behavior
Videos should start

## Actual Behavior
They don't. 

### Debuglog
I did not find errors in retrospect.log, but I did find this in kodi.log: 

2020-12-24 18:19:37.551 T:2984254528  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.retrospect/?action=playvideo&pickle=ED031450F0E67B754EA0B9B00CDB4BEE2CFE6DC694BF382A8A11A29156286DE9--4A3758572B7F23BDC38091256FC07119A4153167C6CB836E54DFC16220872A75&channel=channel.be.vier
2020-12-24 18:19:37.552 T:2559553760  NOTICE: Creating InputStream
2020-12-24 18:19:37.554 T:2559553760   ERROR: IAddonInstanceHandler::CreateInstance: inputstream.adaptive returned bad status "Permanent failure" during instance creation
2020-12-24 18:19:37.554 T:2559553760   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.retrospect/?action=playvideo&pickle=ED031450F0E67B754EA0B9B00CDB4BEE2CFE6DC694BF382A8A11A29156286DE9--4A3758572B7F23BDC38091256FC07119A4153167C6CB836E54DFC16220872A75&channel=channel.be.vier]
2020-12-24 18:19:37.554 T:2559553760  NOTICE: CVideoPlayer::OnExit()
2020-12-24 18:19:37.779 T:2984254528  NOTICE: CVideoPlayer::CloseFile()
2020-12-24 18:19:37.784 T:2984254528  NOTICE: VideoPlayer: waiting for threads to exit
2020-12-24 18:19:37.784 T:2984254528  NOTICE: VideoPlayer: finished waiting

### Your Environment
Used Operating system:

Latest Xbian

Used versions:
- Kodi version: 18
- Retrospect version: latest

thanks!

BC

**Comment by basrieter** [comment]
I need a full DEBUG retrospect.log, eventhough it does not contain any errors. Please use the built-in functionality of Retrospect to upload a log and post the resulting log here.

**Comment by bcnx** [comment]
Hi, I can't find this functionality in the General tab of the AddOn. I do see this on one of your pages: This feature is only available if the log level is set to either Debug or Trace. Are you there referring to the Kodi logfile that should be put to Debug?

**Comment by bcnx** [comment]
Hi, OK, found it, should be on https://paste.kodi.tv/eqaduzofuv,

cheers,

BC

**Comment by bcnx** [comment]
I made a second one after browsing VTM.BE, which shows no programs, just VTM life:

https://paste.doki.tv/wogivufupa

**Comment by bcnx** [comment]
I'm not familiar with the code, but this one seems crucial:

 + ConnectionError: HTTPSConnectionPool(host='stream-live.medialaan.io', port=443): Max retries exceeded with url: /stream-live/v1/channels/vtm/broadcasts/current/video/?deviceId=97c30a3445ed11eb8f77b827eb08ebcb (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x97a18e30>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by basrieter** [comment]
Ok, so VTM.be is completely moving to VTM.GO and will be removed from Retrospect soon. As is VTM.be and VTM Nieuws. Please try VRT Nu?

**Comment by bcnx** [comment]
Hi,

VRT NU works. Vier also poses a problem. 
So VTM Go has u future in Retrospect?

Cheers,

BC

**Comment by basrieter** [comment]
Nope, VTM Go does not. But let me push some changes to make the transition to VTM Go easiers. 

Please try: https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1463.zip by installing it via the "Install from zip" option in Kodi. It will then redirect you to a working VTM Go.

**Comment by bcnx** [comment]
OK, I need to figure out how to get the zip file on my Xbox. I tried running Kodi on a rasp pi 3B+ yesterday, but it is way too slow. Maybe I should consider a rasp 4, the Xbox is a very closed up system.

**Comment by basrieter** [comment]
> OK, I need to figure out how to get the zip file on my Xbox. I tried running Kodi on a rasp pi 3B+ yesterday, but it is way too slow. Maybe I should consider a rasp 4, the Xbox is a very closed up system.

I run Kodi on a rPi 3 with LibreElec and that works OK. However, I also have a rPi4 with LibreElec and that works much better.

**Comment by bcnx** [comment]
I use a NFS file share and while updating the library to this one, the Pi 3 goes on its knees and the network connection drops. I like the Xbox for the ability to run DVDs and BluRays, but the OS is very locked down,

BC

**Comment by bcnx** [comment]
Can I use your zipfile as well on my xbox?

**Comment by basrieter** [comment]
It won't work,  because of the fact that Python cannot access the filesystem properly. Please give it a try on rPi. Then I can merge it and put it in the zip for #1225

**Comment by basrieter** [comment]
I updated the Belgium VTM channels to use VTM Go now. Closing this channel with merge 1b713bad

**Comment by bcnx** [comment]
OK, I suppose we just need to o an update to get this rolling now?

**Comment by basrieter** [comment]
I will add it to the next release. In the mean time zips can be found here:

Kodi Leia: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-leia.zip
Kodi Matrix: https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-matrix.zip

**Comment by bcnx** [comment]
Cheers Bas! Is there a known date for the next release? (approx.)

**Comment by basrieter** [comment]
Soon. I need to update the texture resources first, and then after that has been seeded to all Kodi mirrors, I will create a new release. I also need to test some more stuff I added (such as Poster art and proper content types for folders, so Kodi actually sees there are TV Shows or Episodes in a listing and it will show proper posters for it).

**Comment by bcnx** [comment]
I just tested the new release: is it correct that it links to another add-on "VTM GO"? I had this Addon installed before, but only Live TV works on that one, not any other recorded TV shows. Are you the author as well for that one?

**Comment by basrieter** [comment]
That is correct, but I am not a maintainer of that add-on. The add-on is maintained by a group of enthusiastic developers: https://github.com/add-ons/plugin.video.vtm.go 

They have some issues with a specific Kodi component, but that is being resolved.

**Comment by bcnx** [comment]
Yeah, found their Github page in the meantime and indeed a bug for which they have a temp. solution. I will need to install that one first and re-assess

**Comment by michaelarnauts** [comment]
@bcnx You might want to try https://github.com/add-ons/plugin.video.viervijfzes

It's not in the Kodi repository however.

**Comment by bcnx** [comment]
Cheers Michael,
will it be added to the Kodi repo amytime soon?

BC
