### ISSUE TITLE
Vier shows do not play

### ISSUE THREAD

**Issue by bcnx** [retrospect-addon/plugin.video.retrospect#1465]
### Describe the bug
Vier shows do not start. Clips do seem to start.

## Expected Behavior
All shows should play 

## Actual Behavior
Clips do play, shows do not
### To Reproduce
Open Retrospect, go to Vier and open random show

### Debuglog
see https://paste.kodi/tv/imeroleses:

Used Operating system: Xbian

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: Leia
- Retrospect version: the one with the links to the VTM Go Addon

**Comment by bcnx** [comment]
Vijf and Zes seem to be working fine, strangely enough.

BC

**Comment by bcnx** [comment]
I reconfigured the Addon for Vier and now it shows several episodes. I will test the next few days,

BC

**Comment by basrieter** [comment]
> Vijf and Zes seem to be working fine, strangely enough.
> 
> BC

Vijf and Zes are other providers.

**Comment by basrieter** [comment]
Any update?

**Comment by bcnx** [comment]
We have been watching Vier shows for the last couple of days, so that seems all right. We do have a problem with paused VTM shows, but that seems to be another Add-on.

Cheers,

BC

**Comment by basrieter** [comment]
Cheers, enjoy Retrospect and Kodi!
