### ISSUE TITLE
Player: PlayBackEnded triggered while waiting for start

### ISSUE THREAD

**Issue by 1marc1** [retrospect-addon/plugin.video.retrospect#1469]
Hi,

I have something strange happening.

Yesterday, I installed Retrospect for the first time. After manually also installing `kodi-inputstream-adaptive` and getting Widevine to work, Retrospect worked as expected.

I gave the system a reboot and went to sleep. Today, I find that Retrospect no longer works. When selecting something to play, the circles (in the centre of the screen) spin for a bit, I see the title appear in the top right of the screen, the circles spin some more and then they disappear and I am back in the menu to select what I want to watch.

I have tried to uninstall and the install Retrospect, but the result stays the same.

I have enabled debug logging (at 20210108 23:12:34), then navigated to what I want to watch and selected it. After watching the "waiting circles" for a few seconds, the last message in the log is `Player: PlayBackEnded triggered while waiting for start.`.

This can be seen in the debug log at 20210108 23:13:08. Here is the link to the debug log: https://paste.kodi.tv/wujevefuqa

My environment: Raspberry Pi3, Kodi 18.7, Retrospect 5.2.19 installed via the repository inside Kodi.

Below are the logs from `~/.kodi/temp/kodi.log` that coincide with me trying to play the video.

Thank you in advance for having a look into tihs.

Marc.

```
2021-01-08 23:11:25.047 T:1526718688 WARNING: Attempt to use invalid handle 7
2021-01-08 23:12:33.082 T:1900053424   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2021-01-08 23:13:05.939 T:1526718688  NOTICE: [script.module.inputstreamhelper] Widevine update check was made on 2021-01-07 14:27
2021-01-08 23:13:06.188 T:1900053424  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.retrospect/?action=playvideo&pickle=D13C95FBF1D6DA2275CCED2A4B6690AA2AF29695213D12F160150DB4341BA13E--7CF9574B9B6C5C3681F341E57BED09EADFAB10317ED679877121A9F623368A7C&channel=channel.nos.nos2010-uzgjson
2021-01-08 23:13:06.190 T:1535111392  NOTICE: Creating InputStream
2021-01-08 23:13:07.532 T:1535111392  NOTICE: Creating Demuxer
2021-01-08 23:13:07.590 T:1535111392   ERROR: Open - error probing input format, https://nl-ams-p30-am5.cdn.streamgate.nl/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTAxOTQzODUsInVyaSI6Ilwvdm9kXC9ucG9cL3VzcFwvVEVTVFwvbnBvXC9kYXNoX2NlbmNcL0tOXzE3MTY3MjlcL0tOXzE3MTY3MjlfdjE2MDg1ODMwMjUuaXNtIiwiY2xpZW50X2lwIjoiMTE1LjY5LjE1LjE4OCIsInZpZXdlciI6ImJmNDBkZTA0N2EwZjM1MTQ2ZmQzNjcxZjhlMWE3ZDUyYzQ3ZDViOWMiLCJyaWQiOiJjMGYxMTgxIn0.8lw2zEzVEFcxhLlsPUqFNkujLH2LdPC_5soui9xCfAc/vod/npo/usp/TEST/npo/dash_cenc/KN_1716729/KN_1716729_v1608583025.ism/stream.mpd
2021-01-08 23:13:07.590 T:1535111392   ERROR: OpenDemuxStream - Error creating demuxer
2021-01-08 23:13:07.590 T:1535111392  NOTICE: CVideoPlayer::OnExit()
2021-01-08 23:13:07.613 T:1900053424  NOTICE: CVideoPlayer::CloseFile()
2021-01-08 23:13:07.615 T:1900053424  NOTICE: VideoPlayer: waiting for threads to exit
2021-01-08 23:13:07.615 T:1900053424  NOTICE: VideoPlayer: finished waiting
2021-01-08 23:13:08.159 T:1526718688 WARNING: Attempt to use invalid handle 7
```

**Comment by basrieter** [comment]
Well, the Retrospect log looks OK. Could you enable debug logging for Kodi and try again? Then post the kodi.log?

**Comment by 1marc1** [comment]
I enabled debug logging in Kodi and pasted the output here: https://pastebin.com/MXGphFTP

**Comment by basrieter** [comment]
So it seems to be a DNS issue: 

```2021-01-09 00:16:23.950 T:1486876896   ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)```

Could you check?

**Comment by 1marc1** [comment]
I also saw that in the log last night. I tried pinging `nl-ams-p30-am3.cdn.streamgate.nl` and that was successful. Because things are pointing to DNS, I changed my DNS server to Google's to see if that changes anything, but it doesn't.

This is the `nslookup` result from this evening after changing the DNS server.
---
pi@rpi3:~/.kodi/temp $ nslookup nl-ams-p30-am3.cdn.streamgate.nl
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	nl-ams-p30-am3.cdn.streamgate.nl
Address: 176.58.31.170
---

I then tried playing the same show again, but it again failed. I enabled debug logging again in kodi and pasted the results here:
https://pastebin.com/RbyZYSV7

This time there is no mention of an inability to resolve a host name. Any ideas?

**Comment by 1marc1** [comment]
Further investigation.

I ran both Kodi and Retrospect in Debug mode, then tried to watch the same episode again.

The Kodi debug log is here: https://pastebin.com/6Kq5NnBS
The Retrospect debug log is here: https://paste.kodi.tv/pisugofusu

This is where it seems to go wrong:

From the Kodi log:
```
2021-01-09 22:56:22.781 T:1504952544    INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)
```

From the Retrospect log:
```
20210109 22:56:21 - [DEBUG   ] - player.py            - 40   - Player: Waiting for playback
20210109 22:56:23 - [WARNING ] - player.py            - 57   - Player: PlayBackEnded triggered while waiting for start.
```

**Comment by 1marc1** [comment]
I just tried to watch the episodes that I successfully watched after I initially installed Retrospect for the first time (2 days ago).

When attempting to watch those, the same behavior is shown: spinning circles, title appears briefly in the top right of the screen, more spinning circles and then back in the episode selection menu.

**Comment by basrieter** [comment]
The warning in the retrospect.log is just a result of Kodi not starting playback, so that can be ignored. It seems to be an issue with Widevine I think. Could you use the InputStream Adaptive Helper add-on to reinstall Widevine CDM?

**Comment by 1marc1** [comment]
I will try that and let you know what happens.

**Comment by 1marc1** [comment]
I installed it via Retrospect > Settings > General > - Install Widevine using 'InputStream Helper' add-on.

It doesn't make a difference. I then restarted the Raspberry Pi (for good measure),  but it still doesn't change anything.

**Comment by 1marc1** [comment]
For what it is worth: I am able to watch episodes from AT5. I tried some of the other channels (from Belgium, Denmark, Sweden), but they seem to be mostly empty.

**Comment by basrieter** [comment]
> I installed it via Retrospect > Settings > General > - Install Widevine using 'InputStream Helper' add-on.
> 
> It doesn't make a difference. I then restarted the Raspberry Pi (for good measure), but it still doesn't change anything.

No, you need to go to the InputStream Helper add-on and "reinstall" from those settings.

> For what it is worth: I am able to watch episodes from AT5. I tried some of the other channels (from Belgium, Denmark, Sweden), but they seem to be mostly empty.

These don't always use Widevine, so you can't compare.

**Comment by 1marc1** [comment]
I found the InputStream Helper add-on. Inside its settings there was the option to **(Re)install Widevine CDM library...** That is what I did. Unfortunately, it doesn't make a difference.

**Comment by basrieter** [comment]
Do you have an alternative system to double check if you have the same issue there? I verified it here, but the streams starts on all of my Kodi installations.

**Comment by 1marc1** [comment]
I don't have an alternative system, but I did the following:

1. Uninstall Retrospect (an all related data)
2. sudo apt remove kodi-inputstream-adaptive
3. Reboot
4. sudo apt install kodi-inputstream-adaptive
5. Reboot
6. Install Retrospect

Now everything works. Next, I reboot the Raspberry Pi. Now it doesn't work any more.
I did some further testing. Start state: episode playback is not working.

1. sudo apt remove kodi-inputstream-adaptive
2. Reboot
3. sudo apt install kodi-inputstream-adaptive
4. Reboot
5. Enable InputStream Adaptive add-on (via My add-ons, VideoPlayer InputStream, Information, Enable)

Now things work again. Any ideas?

**Comment by basrieter** [comment]
That is weird. Seems like there is an issue with persistence of installations? Could that be?

**Comment by 1marc1** [comment]
I didn't have a chance to look further into this yesterday. Today I found that (after a reboot), if I disable the InputStream Adaptive add-on and then enable it again, things will start to work again.

It certainly looks like something that doesn't like the reboot and that gets reset by disabling/enabling the add-on.

**Comment by basrieter** [comment]
That is really odd. Perhaps check the Linux logfiles?

**Comment by 1marc1** [comment]
I haven't had a chance to further look into this. I am closing this issue as I am convinced it is not a Retrospect thing.
Thank you very much for your assistance with this! Much appreciated.

**Comment by basrieter** [comment]
Ok, good luck figuring this out.
