### ISSUE TITLE
cannot install retrospect in kodi 18.7

### ISSUE THREAD

**Issue by sjrdc** [retrospect-addon/plugin.video.retrospect#1471]
### Describe the bug
when installing retrospect in kodi 18.7 on raspberry pi through the add-on repository, kodi notifies on 'unable to satisfy dependencies'

## Expected Behavior
retrospect installs in kodi 18.7

## Actual Behavior
retrospect cannot be installed, due to unsatisfiable dependencies

## Possible Fix
unknown 

### To Reproduce
trigger installation of the add-on through the add-on repository

### Screenshots 
not available

## Additional context or screenshots (if appropriate)
n/a
### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi/ raspbian buster
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.7 leia
- Retrospect version: as per the add on repo

**Comment by basrieter** [comment]
Please provide a debug kodi.log that contains the attempt to install.

**Comment by sjrdc** [comment]
[kodi.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/5792827/kodi.log)

2021-01-10 16:36:27.857 T:1900262320   DEBUG: CAddonInstaller: installing 'plugin.video.retrospect' version '5.2.19' from repository 'repository.xbmc.org'
2021-01-10 16:36:27.871 T:1755410656   DEBUG: CAddonInstallJob[plugin.video.retrospect]: requires inputstream.adaptive version 2.0.19 which is not available
2021-01-10 16:36:27.872 T:1755410656   ERROR: CAddonInstallJob[plugin.video.retrospect]: The dependency on inputstream.adaptive version 2.0.19 could not be satisfied.

**Comment by basrieter** [comment]
Are you sure it is not already there in Kodi, but disabled? It should have come with the Kodi install.

**Comment by sjrdc** [comment]
you mean retrospect as a media source? or the dependency?

**Comment by basrieter** [comment]
No, the input stream adaptive add-on in Kodi itself.

**Comment by sjrdc** [comment]
You are absolutely right, it was installed as part of the kodi package and apparently disabled (can't remember doing that...)

I may have overlooked this in the installation instructions, in which case I am sorry for the disturbance...
Otherwise, can I help adding this to the installation instructions?

**Comment by basrieter** [comment]
Perhaps I should update it here: https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Installation 

That is where the readme.md points to.

**Comment by sjrdc** [comment]
that would be nice
in any case, keep up the good work and thanks for the help!

**Comment by basrieter** [comment]
I will add this:

> **NOTE**: Retrospect requires the _InputStream Adaptive_ add-on to be installed with Kodi. On some Linux based systems this add-on is installed using `sudo apt-get install kodi-inputstream-adaptive` command. However, after a succesful installation, the add-on still needs to be **enabled** wihtin Kodi. If this add-on is installed, but not enabled, Retrospect **cannot** be installed within KodiD.

**Comment by basrieter** [comment]
Updated. Thanks for the input!
