### ISSUE TITLE
Sweden: UR Play broken

### ISSUE THREAD

**Issue by Snaah** [retrospect-addon/plugin.video.retrospect#1473]
### Describe the bug

Watching programs on UR Play doesn't work. Tested on Windows 10, Android and Android TV. I also tried clearing cache to no avail. Works on the web, for example https://urplay.se/serie/203240-samernas-tid

## Expected Behavior

Programs should play.

## Actual Behavior

Programs don't play.

### To Reproduce

1. Open any program and try to play
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/5820180/retrospect.log)

### Your Environment
Used Operating system:

 - [x] Android
 - [x] Android TV
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.9
- Retrospect version: latest

**Comment by basrieter** [comment]
I already fixed it. See 02124fef35c90dcce87abf9ca1e90ad09da174c5. 

I will push an update tonight. Until then you can download the Leia or Matrix zips and install from zip.

**Comment by Snaah** [comment]
Okay! Sorry, I've missed that fix.
