### ISSUE TITLE
Hoe GraphQL querystring met custom fields vorm te geven?

### ISSUE THREAD

**Issue by Reino17** [retrospect-addon/plugin.video.retrospect#1474]
Hallo Bas,

Ik kon geen e-mailadres van je vinden, dus doe ik het op deze manier.  
Ik heb geen "issue" te melden, maar een vraag die ik wil stellen. Ik hoop dat je dat geen probleem vindt.

Voor kijk.nl heb ik voor het eerst te maken met GraphQL. Door het netwerkverkeer nauwlettend in de gaten te houden zie ik deze url + (decoded) querystring...
```
https://graph.kijk.nl/graphql?operationName=programs&variables={"guid":+"<prid>"}&extensions={"persistedQuery":+{"version":+1,+"sha256Hash":+"<hash>"}}
```
...2x voorbij komen. De ene voor metadata, de andere voor het HLS/DASH manifest (elk met een andere hash).

Echter, in je broncode zie ik...

_https://github.com/retrospect-addon/plugin.video.retrospect/blob/master/channels/channel.sbsnl/kijknl/chn_kijknl.py#L101-L104:_
> ```
> self.__video_fields = \
>     "{items{__typename,title,description,guid,updated,seriesTvSeasons{id}," \
>     "imageMedia{url,label},type,sources{type,drm,file},series{title}," \
>     "seasonNumber,tvSeasonEpisodeNumber,lastPubDate,duration,displayGenre,tracks{type,file}}}"
> ```

...waardoor ik het idee krijg dat je in de querystring precies kunt aangeven welke entries je als antwoord wilt hebben.

Omdat ik niet zo thuis ben in Python heb ik flink op het internet zitten zoeken hoe ik deze custom querystring precies moet vormgeven. Ik heb urls als deze...
```
https://graph.kijk.nl/graphql?query=query+programs(guid:<prid>)+{items{__typename,title,description,guid,updated,seriesTvSeasons{id},imageMedia{url,label},type,sources{type,drm,file},series{title},seasonNumber,tvSeasonEpisodeNumber,lastPubDate,duration,displayGenre,tracks{type,file}}}
```
...geprobeerd + variaties daarop, maar tot nu toe zonder succes.

Kun jij me uitleggen hoe en waar ik die "fields" in de querystring plaats?

**Comment by basrieter** [comment]
Mail mij even op `retrospect [at] rieter [dot] net`. Dan help ik je verder.
