### ISSUE TITLE
Cant logon with Discovery+(sweden)

### ISSUE THREAD

**Issue by bubbleboyy** [retrospect-addon/plugin.video.retrospect#1475]
### Describe the bug

Cant logon with my discovery+ account information.

## Expected Behavior

Start the video without any error message.

## Actual Behavior

Cant log on and play any video.

### To Reproduce

1. Enter your discovery+ account in settings.
2. Start any video
3. Error message cant logon

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/ayizefuzos

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.9
- Retrospect version: 5.2.21

**Comment by basrieter** [comment]
I see they have update their logon process again. I will need to dive into that. From experience this is always rather complex and could take some time.

**Comment by bubbleboyy** [comment]
Ok, I see. They have added some puzzle game when I login on their website. Maybe thats a old thing.

**Comment by basrieter** [comment]
Right. And after logging in on the website, does the log-in in Retrospect starts to work again?

**Comment by bubbleboyy** [comment]
No, still the same problem.

**Comment by bubbleboyy** [comment]
Its not always a puzzle game to solve. Sometimes It jump over that step when I login.

**Comment by basrieter** [comment]
I gave this two full evenings of trying, but I just can't get it to work anymore. They changed someting in the hashing which I cannot resolve. And even when logging into the website, i cannot seem to get it to work.

**Comment by bubbleboyy** [comment]
Ok, Maybe they remove the captcha in the future, but probably not...

**Comment by Method47** [comment]
Hello again,

Not to bother, but, any updates on this issue I am experiencing as well?

Much thanks!

**Comment by basrieter** [comment]
At this moment I am looking into a work around, but it is not easy. But I am currently very busy so it will take some time.

**Comment by cabban** [comment]
> At this moment I am looking into a work around, but it is not easy. But I am currently very busy so it will take some time.

I have a work around I found from discovery+ addon 

If you are experiencing problems with login example "Error logging in. Invalid Arkose token." you can use cookies exported from Chrome to fix login issues. Use Get cookies.txt to export cookies and from addon settings specify location of cookies.txt. This was the issue in this app, so I tried this and now I can watch all free TVshows there. Maybe you also can add this to settings? 
![Screenshot_20210227-135632_Chrome Beta](https://user-images.githubusercontent.com/19514493/109387842-ee037980-7903-11eb-995b-1f8583d638bd.jpg) @basrieter

**Comment by basrieter** [comment]
Yeah, I am in contact with their dev and see if we can fix this. But I will look into this.

**Comment by cabban** [comment]
> Yeah, I am in contact with their dev and see if we can fix this. But I will look into this.

No its was svt play who was not working . Thank u for check it out😀

**Comment by basrieter** [comment]
Ok, so please provide a logfile, because without one, I can't really do anything.

**Comment by nkls2000** [comment]
Hi. Thanks for this great plugin. Im having problems with discovery+ in Sweden as well. Here is a link to my log:
https://paste.kodi.tv/yakoniduyo

**Comment by nkls2000** [comment]
No update on this yet? Just tell me if you need anything else!

**Comment by maxruben** [comment]
Hi, I have the same problem - Can't log in to Discovery+ and Kanal 5 Sweden anymore. As I understand it kanal 5 is part of Discovery+ now and uses the same login. Retrospect says 'can't log in to channel' and 'no streams'.  Since this issue is not closed yet it may not be fixed, right? However I know that it did work ok in the beginning of July since I have watched a lot of Flip or Flop (premium paid) on Discovery+ during my lunch break when working from home during the pandemic. I have also watched Premium paid shows on Kanal 5, Sweden (channel 5). I have a paid account at Discovery + and I can log in to that an watch shows from there on the web. I always make sure to logout after I have logged in on the web.

Could this be a vault or password problem?

Rpi 3
Kodi 18.9
Libreelec 9.2.7
Retrospect 5.4.5

Log here: https://paste.kodi.tv/odayimefip

I have also tried on an Android Samsung tablet with Kodi Matrix and no go there either (however I have not used this when it did work on my RPI).

Thanks for this great app /Ruben

**Comment by basrieter** [comment]
For now this is something I cannot fix. I am still thinking on other options, but it seems to be impossible for the moment.

**Comment by maxruben** [comment]
Too bad :-(

They have something called a "pairing code" for devices, but I am sure you already have looked in to that.

Hope you solve it. If you need any help with testing, let me know.

Thanks /Ruben

**Comment by failure84** [comment]
https://github.com/spaam/svtplay-dl/blob/master/lib/svtplay_dl/service/dplay.py

Maybe this will help @basrieter :)

**Comment by Snaah** [comment]
It still seems to require a cookie from a web browser, doesn't it?

**Comment by basrieter** [comment]
Yep, they used my code but still require a cookie.

**Comment by failure84** [comment]
https://github.com/Dis90/plugin.video.discoveryplus/issues/38

This might help?

**Comment by basrieter** [comment]
Closing this with 2692b286ad5c6c512ceb536157a49265c28d369d as Dplay is no longer an option.
