### ISSUE TITLE
Playing NPO-start streams on more devices simultaneously 

### ISSUE THREAD

**Issue by chakubie** [retrospect-addon/plugin.video.retrospect#1476]
### Describe the bug

It is not possible to play NPO-start streams on more devices simultaneously using Kodi on my raspberry's or Linux-laptop
on the same IP-address 
I can play more RTL or Kijk.nl streams simultaneously using the same IP-adress 
When I use Firefox on Linux-Mint or the NPO-app on Android this issue doesn't occur...
When on one of the devices a VPN is active there is no problem.

## Expected Behavior

Being able to play NPO-start streams on more devices simultaneously using the same IP-adress 

## Actual Behavior

It is not possible to play NPO-start streams on more devices simultaneously using Kodi on my raspberry's or Linux-laptop
on the same IP-address 

### To Reproduce

1. 
2.
3.

### Debuglog

***removed***

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:
Linux OSMC
Linux Mint 

Used versions:
- Kodi version: 18.9
- Retrospect version: 5.2.21

**Comment by basrieter** [comment]
Please provide a link to a full debug retrospect.log not kodi.log.

**Comment by basrieter** [comment]
Question: do you log on to NPO from Retrospect? (that would be info I usually get from the logfile).

**Comment by chakubie** [comment]
> Please provide a link to a full debug retrospect.log not kodi.log: you can juse the built-in fuctionality from Retrospect and just post the link here.

https://paste.kodi.tv/xisuqumiwe

**Comment by chakubie** [comment]
Please provide a link to a full debug retrospect.log not kodi.log: you can juse the built-in fuctionality from Retrospect and just post the link here.

https://paste.kodi.tv/xisuqumiwe

**Comment by basrieter** [comment]
The Retrospect log looks just fine. Can you provide a full debug xbmc.log?

**Comment by chakubie** [comment]
> The Retrospect log looks just fine. Can you provide a full debug xbmc.log?

https://paste.kodi.tv/uwojojiyoy   
https://paste.kodi.tv/xevapozeqo
Thanks again!

**Comment by chakubie** [comment]
This is an osmc-log from the second raspberry after the NPO1-live-stream stopped...: https://paste.osmc.tv/cetejajovu

**Comment by basrieter** [comment]
Did you copy over Retrospect user_data from one machine to the other? If so, try cleaning up the cache and cookies using the Retrospect add-on settings.

**Comment by chakubie** [comment]
No, I didn't, it is a clean install on all machines and l did clean take cache and cookies on all machines too...

**Comment by basrieter** [comment]
It's weird. I tried it here and can play the same stream on two Kodi devices. I tried my LibreElec Kodi and Android Kodi. Np. Is it just your Linux boxes that have this?

**Comment by chakubie** [comment]
Yes, the problem only exists on Linux boxes and only with NPO streams. I can play a second NPO stream at the same time using the NPO-site on Firefox on my Linux computer... When I use Kodi on this same device the second NPO-stream isn't starting...
When I activate the VPN on one Linux device the second stream starts on Kodi and OSMC/Kodi

**Comment by basrieter** [comment]
Hmm, ok. Will need to check that tomorrow.

**Comment by chakubie** [comment]
I'm afraid that the problem will persist and that it can only be solved by the NPO, what is your opinion?

**Comment by basrieter** [comment]
Is this still an issue?

**Comment by chakubie** [comment]
The problem solved itself a few weeks ago.
My provider, KPN, enabled ipv6. I don't know if that is the reason, but now it is possible to play NPO-start streams on two devices simultaneously.

**Comment by basrieter** [comment]
Good to hear it is working now.
