### ISSUE TITLE
Vier/Vijf/Zes.be broke

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#1477]
They moved to https://goplay.be

### Describe the bug

Nothing is working anymore for these three channels.

### Your Environment
Used Operating system:

 - [x] Android
 - [x] iOS
 - [x] Linux
 - [x] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [x] Windows UWP

Used versions:
- Kodi version: 18.x
- Retrospect version: latest

**Comment by michaelarnauts** [comment]
@basrieter I've made a fix here: https://github.com/add-ons/plugin.video.viervijfzes/pull/64

Basically, they just moved some api endpoints around, and use now only one site instead of three.

**Comment by basrieter** [comment]
There is already a fix in Retrospect. Will release it tomorrow.
