### ISSUE TITLE
NPO Start folder icoontjes

### ISSUE THREAD

**Issue by PhyxionNL** [retrospect-addon/plugin.video.retrospect#1479]
## Bug report

NPO Start heeft sinds kort in de lijst van de hoofdmap vrijwel onleesbare icons (die voor Favourites/Genres/etc):

![image](https://user-images.githubusercontent.com/7643972/106312960-c15a3480-6267-11eb-8b52-0f4a42f99171.png)

## Expected Behavior
Zoals alle andere folders lijkt mij de normale map icon hier beter.

**Comment by basrieter** [comment]
Goed gespot! Ga ik fixen.

**Comment by basrieter** [comment]
Je was echt niet op tijd. De PR voor de volgende versie stond al klaar :)

**Comment by didamsko** [comment]
"Je was echt **_net_** op tijd. " ;)

En bedankt voor de fix! Het was mij ook opgevallen maar ik dacht dat het een geplande verandering was. Gelukkig was dat dus niet het geval :)
