### ISSUE TITLE
Vier, Vijf and Zes  not working anymore

### ISSUE THREAD

**Issue by bcnx** [retrospect-addon/plugin.video.retrospect#1480]
Hi,

this is most likely due to the fact that these stations have changed names: Play4, Play5 and Play6.
Can you please update Retrospect to reflect these changes?

Cheers,

BC

**Comment by basrieter** [comment]
Please update to Kodi 5.2.22

**Comment by basrieter** [comment]
https://github.com/retrospect-addon/plugin.video.retrospect/issues/1477
