### ISSUE TITLE
Installing Inputstream Adaptive on installing Retrospect?

### ISSUE THREAD

**Issue by bartmans** [retrospect-addon/plugin.video.retrospect#1482]
### Describe the bug

When installing Retrospect from the repository on a fresh Matrix install, I got an error. I had to install the Inputstream Adaptive addon manually and retry installing Retro.

## Expected Behavior

When I install Retro from the Kodi repo I expect that all dependencies are resolved and installed (if possible).

## Actual Behavior

I had to install manually.

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Raspberry-Pi

Used versions:
- Kodi version:
- Retrospect version:
Kodi: Matrix, LibreElec nightly from 29th january.
Retrospect: most recent in Kodi repo

**Comment by basrieter** [comment]
This is a Kodi thing, not Retrospect. It is there as a dependency, so it should install.
