### ISSUE TITLE
RTV Oost werkt soms niet

### ISSUE THREAD

**Issue by ErikBrown2** [retrospect-addon/plugin.video.retrospect#1483]
### Describe the bug

RTV Oost werkt soms niet . Als het niet werkt, dan gebeurt het volgende. Ik klik op een programma om het af te spelen. De achtergrond wordt dan zwart (zoals normaal) en ik zie 'Working'. Na een paar seconden komt de achtergrond weer te voorschijn en verdwijnt 'Working'. 
Het vreemde is dat het soms werkt nadat ik de raspberry Pi opnieuw opgestart heb. Maar soms werkt het niet. De debug log is van toen het niet werkte.

## Expected Behavior

Als ik op een programma klik om het af te spelen dan wordt normaal gesproken de achtergrond zwart, ik zie 'Working' en na een paar seconden wordt het programma afgespeeld. 

## Actual Behavior

Als ik op een programma klik om het af te spelen dan wordt de achtergrond zwart, ik zie 'Working', zoals gewoon. Maar na een paar seconden zie ik de achtergrond weer en de programma listing. Dus het lijkt er op dat Retrospect probeert de video af te spelen maar daar niet in slaagt. En dan weer de programma lijst laat zien die ook te zien was toen ik het programma probeerde af te spelen.

### To Reproduce

1. Start Kodi - Start Retrospect - Ga naar Regionaal - RTV Oost
2. Probeer een programma af te spelen
3. Als het wel werkt, start dan Kodi opnieuw op. 

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/dezequzasa

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: Libreelec 9.2.6, Kodi is 18.9.0
- Retrospect version: 5.2.22

**Comment by basrieter** [comment]
Raar. De logfile ziet er gewoon netjes uit. Zou je een kodi.log kunnen sturen als het weer een keer niet werkt?

**Comment by ErikBrown2** [comment]
Het Kodi debug log is https://paste.kodi.tv/kefozumogu.kodi

Je schreef dat de Retrospect logfile er normaal uitziet. Maar de regel met de tekst "Player: PlayBackEnded triggered while waiting for start." lijkt er toch op te duiden dat de video niet afgespeeld werd?

20210205 01:37:39 - [INFO    ] - mediaitem.py         - 500  - Playing Stream:  MediaStream: http://tvarchief.rtvoost.nl/hi/571732.mp4 [bitrate=1350]
20210205 01:37:39 - [DEBUG   ] - videoaction.py       - 70   - Continuing playback in plugin.py
20210205 01:37:39 - [DEBUG   ] - videoaction.py       - 135  - Current playlist size and position: 1 @ 0
20210205 01:37:39 - [DEBUG   ] - videoaction.py       - 144  - Adding Main PlayList item
20210205 01:37:39 - [DEBUG   ] - player.py            - 40   - Player: Waiting for playback
20210205 01:37:45 - [WARNING ] - player.py            - 57   - Player: PlayBackEnded triggered while waiting for start.
20210205 01:37:45 - [DEBUG   ] - kodisettings.py      - 70   - Removed Kodi settings-store
20210205 01:37:45 - [DEBUG   ] - localsettings.py     - 84   - Removed Local settings-store
20210205 01:37:45 - [INFO    ] - addon.py             - 65   - Retrospect :: Flushing and closing logfile.

**Comment by ErikBrown2** [comment]
Sorry Bas dat ik dit niet eerder probeerde. Maar als ik met een webbrowser naar de RTVOost website ga heb ik ook problemen met het afspelen van de programma's. Dus het lijkt er op dat het niets met Retrospect te maken heeft. Op de webbrowser krijg ik deze melding:
Er is een fout opgetreden
Tijdens het laden van de pagina is er een fout opgetreden. Probeer het later opnieuw.

Nogmaals sorry dat ik dit niet eerder heb getest.

**Comment by basrieter** [comment]
Ik zie dat ze een http 502 error terug geven:

>2021-02-05 15:17:30.296 T:1547502464   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 502
2021-02-05 15:17:30.296 T:1547502464   ERROR: CCurlFile::Open failed with code 502 for http://tvarchief.rtvoost.nl/hi/571732.mp4:
2021-02-05 15:17:30.296 T:1547502464   ERROR: Open - failed to open source <http://tvarchief.rtvoost.nl/hi/571732.mp4>

Hopelijk kunnen ze het aan hun kant fixen. Mocht je het bij hun melden, meldt dan het de website fouten geeft. Retrospect zegt ze toch niks.
