### ISSUE TITLE
Inputstream.adaptive not available for Kodi Matrix on tvOS

### ISSUE THREAD

**Issue by bjornaelvoet** [retrospect-addon/plugin.video.retrospect#1484]
### Describe the bug

Inputstream.adaptive library is not available for tVOS. Retrospect add-on identifies this library as mandatory. Installation of the retrospect add-on fails with the corresponding message of missing library. See also [here](https://forum.kodi.tv/showthread.php?tid=303609&page=3) for problem description of the library not building on certain platforms.

## Expected Behavior

Proposal to define the inputstream.adaptive library as optional in addon.xml. This will allow for installation and most of the channels will still work as expected.

## Actual Behavior

Retrospect not installing due to missing inputstream.adaptive library on tvOS for Kodi Matrix. I am guessing the problem also happens on all macOS related platforms (iOS, OS X, ...), as I see only successfull builds for the inputstream.adaptive library for linux and Windows.

## Possible Fix

Proposal to define the inputstream.adaptive library as optional in addon.xml. This will allow for installation and most of the channels will still work as expected.

<import addon="inputstream.adaptive" version="2.0.19" **optional="true"** />

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [x] iOS
 - [ ] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP
 - [x] tvOS (Apple TV 4K) 

Used versions:
- Kodi version: Matrix
- Retrospect version: Latest, 5.2.22, official Kodi Matrix repository.

**Comment by basrieter** [comment]
90% of the channels will not work without InputStream Adaptive. So that is not an option. I assume there will be a TVOS version is InputStream Adaptive soon.

**Comment by bjornaelvoet** [comment]
Hi Bas,

  My mistake. I'm using the plugin to watch the Flemish channels and all work without having the inputstream.adaptive library. That's why I assumed most channels don't need it.

  For now; I will manually fix the addon.xml (adding **optional="true"**) with each new release of retrospect to get it working on tvOS. At least reporting this issue will be helpful for other (Dutch/Belgian) people facing same problem.

  I will focus on having an in-depth look why this library is not building on Apple related OS.

  I will close the issue 👍 

  Thanks for the great work!
