### ISSUE TITLE
__init__() got an unexpected keyword argument 'encoding' when using the vault

### ISSUE THREAD

**Issue by henkv1** [retrospect-addon/plugin.video.retrospect#1487]
### Describe the bug
I get the following python error when using the vault. I did some investigation and it seems that the encoding= parameter is deprecated and removed in python 3.9. See: https://docs.python.org/3/whatsnew/3.9.html

20210221 17:24:51 - [ERROR   ] - localsettings.py     - 107  - Error loading JSON settings. Resetting all settings.
20210221 17:24:51 - [ERROR   ] - localsettings.py     - 107  - | Traceback (most recent call last):
20210221 17:24:51 - [ERROR   ] - localsettings.py     - 107  - |   File "/root/.kodi/addons/plugin.video.retrospect/resources/lib/settings/localsettings.py", line 105, in __load_settings
20210221 17:24:51 - [ERROR   ] - localsettings.py     - 107  - |     LocalSettings.__settings = json.loads(content, encoding='utf-8')
20210221 17:24:51 - [ERROR   ] - localsettings.py     - 107  - |   File "/usr/lib/python3.9/json/__init__.py", line 359, in loads
20210221 17:24:51 - [ERROR   ] - localsettings.py     - 107  - |     return cls(**kw).decode(s)
20210221 17:24:51 - [ERROR   ] - localsettings.py     - 107  - + TypeError: __init__() got an unexpected keyword argument 'encoding'
20210221 17:24:51 - [WARNING ] - localsettings.py     - 110  - Creating backup of settings file: /root/.kodi/userdata/addon_data/plugin.video.retrospect/settings.error.json

Removing the encoding= parameter fixes this error.

**Comment by basrieter** [comment]
Hmmm, let me fix that for the next release.

**Comment by basrieter** [comment]
Can you try this version: https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1487.zip

**Comment by basrieter** [comment]
@henkv1  Could you check?
