### ISSUE TITLE
NPO video's don't start

### ISSUE THREAD

**Issue by Hazes75** [retrospect-addon/plugin.video.retrospect#1488]
### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:
- Retrospect version:

**Comment by basrieter** [comment]
Please fill in the requested information? We really need that to answer your question.

**Comment by Hazes75** [comment]
Thank you for your reply  The last 2 weeks the videos didn't start. Today I tried again, now they do start. I don't know what the problem is. I live in Mexico and use Kodi 18.9 with Nord VPN on a Chromecast with Google tv. If it happens again I will include a DEBUG report.

**Comment by basrieter** [comment]
Good to hear it works now. If it happens again. Just re-open this issue and attach a debug log.
