### ISSUE TITLE
KijK Error retrieving list of items

### ISSUE THREAD

**Issue by sluwtje** [retrospect-addon/plugin.video.retrospect#1489]
### Describe the bug

With latest Retrospect version, selecting Kijk after 11 pm NL time.
And selecting "recent" and "today," i get "error retrieving list of items"

## Expected Behavior

Please fix

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:
- Retrospect version:

**Comment by basrieter** [comment]
Ok, do you have a retrospect.log for that? And are you in the NL time zone?

**Comment by sluwtje** [comment]
Hello,

The problem is already a while going on.
I don't know how to get the log file.
I Will try to get it for you if i have time.
Yes i'm in The Netherlands.

If i have the log file, can i send it to this email?

Jan Hiemstra



Op do 25 feb. 2021 20:39 schreef Bas Rieter <notifications@github.com>:

**Comment by basrieter** [comment]
Hi Jan, you can use the built-in log file upload feature of Retrospect:

- Enable debug logging from the Retrospect settings
- Reproduce the problem
- Go back into the Retrospect settings and upload the logfile
- Post the resulting URL here

**Comment by basrieter** [comment]
I just tried, and it all works here for me?

**Comment by sluwtje** [comment]
Hi,

Yes, very strange, yesterday i tried it around 12:12 AM nl Time to get it
in the log.And it Worked also.
It seems to happen at a certain time at night after 12 AM.
When it happens again i create the log for you and send it right away.

Do you live in the Netherlands, can we mail in the dutch? My dutch is
better when typing mails.

Regards,

Jan


Op vr 26 feb. 2021 23:35 schreef Bas Rieter <notifications@github.com>:

**Comment by basrieter** [comment]
Ok, I checked aat 01:50. The "Today" actually retrieves the shows for the date that just started: so for me what was the 28th of februari. However, nothing has been broadcasted yet, so the list is almost empty. Those items do appear in the data, have a missing  "date" field which causes an error. However: even if I fix that, those streams will not play. 

Perhaps it makes more sense to let the "Today" switch at a later time, like 5:00 in the morning. That way, "Today" at 1:00 will not contain the shows in the "future" yet.

**Comment by basrieter** [comment]
You can try https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1489.zip with Kodi Matrx (19.0) to see if it fixes your issues. I now swap "today" at 5:00 and can handle missing time stamps for videos.

**Comment by sluwtje** [comment]
Oké, i understand where you coming from,. But the issue is not selecting
"today" but selecting "yesterday" because it is a new day after 12 AM we
want to see a tvshow from the Day before late at the evening.

We want to see "Hart van Nederland-laat"  that comes on tv 10:30 pm the Day
before thru kijk.

But this morning it happend at  2:37 AM and i got a log for you:

https://paste.kodi.tv/vobamelice

That's what kodi said after use debug mode.

Jan



Op zo 28 feb. 2021 02:08 schreef Bas Rieter <notifications@github.com>:

**Comment by basrieter** [comment]
Please try the zip I posted. That will fix your issue I think.

**Comment by sluwtje** [comment]
Oké, i'll try

Op zo 28 feb. 2021 12:08 schreef Bas Rieter <notifications@github.com>:

**Comment by sluwtje** [comment]
Hey,

Tried to install your Retrospect zip, but i get: xbmc.python version 3.0.0.
could not be satisfied.

I think because i'm still on kodi 18.9 and you made this version for kodi 19
Any solutions?

Jan

Op zo 28 feb. 2021 12:08 schreef Bas Rieter <notifications@github.com>:

**Comment by basrieter** [comment]
The main development is for Kodi Matrix now, so I would suggest to upgrade whenever possible. Leia is still supported, but only via a the Kodi repository or manual download. 

I will just merge and release a new version then. That will reach you via the Kodi repositories.

**Comment by sluwtje** [comment]
Hello,

Oké, that is alright

Thank you.

Op ma 1 mrt. 2021 20:36 schreef Bas Rieter <notifications@github.com>:

**Comment by basrieter** [comment]
Closed with 4eba7eca72ca740009bed0d81838d432d07333a7

**Comment by sluwtje** [comment]
Hey,

Got the update yesterday, and it solved the problem, however i noticed
something else.
After 0:30 AM i had to select kijk/recent/today for the programs from day
before (before 0:00 AM)
That has to be kijk/recent/yesterday or did you do that on purpose?

Jan



Op di 2 mrt. 2021 20:08 schreef Bas Rieter <notifications@github.com>:

**Comment by basrieter** [comment]
Great! I changed it on purpose: at 5:00 the "Today" becomes the new day. It made more sense: if I want to check a show that played that evening and I check it just after midnight it is confusing that I need to select Yesterday.

**Comment by sluwtje** [comment]
Oké, i understand.
Thanks for the help.




Op wo 3 mrt. 2021 11:39 schreef Bas Rieter <notifications@github.com>:

**Comment by sluwtje** [comment]
Hey,

Yesterday i installed Kodi 19 Matrix on my Android box, and Retrospect from
the Kodi Repo.
When i tried to watch Kijk at 02:08 AM central European time/dutch time,
When selecting "Kijk" it said "Error retrieving the list of items" so i
tried RTLXL and it said the same.

Jan Hiemstra




Op wo 3 mrt. 2021 16:57 schreef Jan Hiemstra ***@***.***>:

**Comment by basrieter** [comment]
Please provide a DEBUG retrospect logfile via paste.kodi.tv
