### ISSUE TITLE
Retro addon not working on my Android Tv

### ISSUE THREAD

**Issue by Espancor** [retrospect-addon/plugin.video.retrospect#1490]
Hi!
I´m running kodi on my Android TV and I got a new  update of Kodi (Matrix) and then my Retro addon end to work but still working on my pc. 
It is any one that experiment the same issue?
Thanks!!

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:
- Retrospect version:

**Comment by basrieter** [comment]
I can't do anything without a **DEBUG** kodi.log and/or retrospect.log. Please attach both.

**Comment by Espancor** [comment]
I understand, but I don´t think that I will availible to do that, because the addon does not respond at all. Maybe I should reinstallt it.
Sorry

**Comment by basrieter** [comment]
Please try uninstalling it and reinstalling it via the Kodi Matrix repository. It should work under Matrix. If it does not, install the Kodi logfile uploader add-on from the repository and use it to upload a kodi.log so you can post the link here.

**Comment by Snaah** [comment]
Retrospect is working on my Philips Android TV. Everything updated automatically when Kodi was updated to 19 Matrix.

**Comment by basrieter** [comment]
Let me know if this is still an issue. Closing for now.
