### ISSUE TITLE
Not workin on kodi 19 

### ISSUE THREAD

**Issue by cabban** [retrospect-addon/plugin.video.retrospect#1491]
### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

## Additional context or screenshots (if appropriate)

Tried program and not working loading then nothing 

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:
- Retrospect version:

**Comment by basrieter** [comment]
It should be working on Kodi 19. Please tell me how you installed this?

**Comment by cabban** [comment]
It's windows kodi 
I try and try it only loading than kodi don't answer
Also I can't play discovery plus I try I have correct password and still i can't login it can't login to the selected channel 😥

**Comment by basrieter** [comment]
So you need to be more specific: What is not working? If it is only Discovery+ you most likely have this issue: #1475

**Comment by cabban** [comment]
> So you need to be more specific: What is not working? If it is only Discovery+ you most likely have this issue: #1475

When I choose a program on say svtplay whole kodi freeze maybe sometime it goes and play other time only freezing 😥

**Comment by basrieter** [comment]
Let me know if this is still an issue. Closing for now.
