### ISSUE TITLE
NPO streams not starting

### ISSUE THREAD

**Issue by northlaender** [retrospect-addon/plugin.video.retrospect#1492]
### Describe the bug

NL Livestreams not workin. Displays error message  "the selected item does not have any stream sassociated.
same error shows for NPO1, NPO2, Zapp (NPO3)

## Expected Behavior

stream should start

## Actual Behavior

Error message shown  + playback failed kodi message

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
https://gist.github.com/northlaender/888815aa886814f70aced0803d0b2f9a

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:18.7
- Retrospect version: 5.2.23

**Comment by basrieter** [comment]
Let me see what has changed here.

**Comment by basrieter** [comment]
Please try this version under Kodi Matrix: https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1492.zip

Let me know if it solves your issue, so I can push a new update fast.

**Comment by northlaender** [comment]
hi @basrieter 
The update works!
thanks!

**Comment by basrieter** [comment]
Great. I will create an update then.
