### ISSUE TITLE
Add dolby digital/digital plus to npo

### ISSUE THREAD

**Issue by powermarcel10** [retrospect-addon/plugin.video.retrospect#1494]
Is it possible to add support for dolby digital on the npo start plus movies and series?

Cheers,
Marcel

**Comment by basrieter** [comment]
Do you have examples of streams that have this?

**Comment by basrieter** [comment]
Any update @powermarcel10 ?

**Comment by powermarcel10** [comment]
Well, actually, I was thinking that all streams had it by default, but maybe I'm wrong. On live TV, all programs have dolby, so I thought that they had it also for on demand content as well. Other platforms like Netflix or Videoland support it.

**Comment by basrieter** [comment]
The normal non-plus streams not. As I don't have NPO plus, it would be great if you could share a HAR export of traffic while playing such a stream. See here: https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting

Please mail the result to retrospect [at] rieter [dot] net, as it  might contains sensivitive data.

**Comment by powermarcel10** [comment]
Aaah allright! Thanks. I wil try to sent it to you when I have some time!

**Comment by basrieter** [comment]
Any update here?
