### ISSUE TITLE
Wrong poster image used for Nickelodeon (Sverige)

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1497]
### Describe the bug

Wrong poster image used for Nickelodeon (Sverige)

## Expected Behavior

Correct poster used for Nickelodeon (Sverige)

## Possible Fix

My quickfix:

copy: resource.images.retrospect\resources\channel.nick.nickelodeon\nickposter.png
to:   resource.images.retrospect\resources\channel.nick.nickjr\nickposter.png

add to plugin.video.retrospect\channels\channel.nick\channelpack.json:   "channel.nick.nickjr/nickposter.png": "xxxxx"

change in row 45: plugin.video.retrospect\channels\channel.nick\nickjr\chn_nickjr.json for "Nickelodeon (Sverige)"
from: "poster": "nickjrposter.png",
to:   "poster": "nickposter.png",

### Screenshots 

Before quickfix:
![Image1](https://user-images.githubusercontent.com/46671821/110962048-cd4e1180-8350-11eb-9921-67dc6e2eee1c.png)
After quickfix:
![Image2](https://user-images.githubusercontent.com/46671821/110962095-db9c2d80-8350-11eb-8c5b-42963a864400.png)

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.9, 19.0
- Retrospect version: 5.2.24

**Comment by basrieter** [comment]
That is odd. Let me see where this is going wrong. Please don't copy over these files btw: eventually it will fallback because the original textures will be used again.

**Comment by basrieter** [comment]
Fixed it, but need to wait for a repository update before I can push a new Retrospect version.
