### ISSUE TITLE
Issues with Kodi V20 and latest Retrospect.

### ISSUE THREAD

**Issue by orfeous1** [retrospect-addon/plugin.video.retrospect#1499]
My issue is that it takes forever to open retrospect plugin and then also whatever channel and all other browsing.
The two circles in the middle of the screen just animate for like 20sec and then next page loads.
In the logs it seems that there is problem with Python.

**Comment by basrieter** [comment]
Ok, so where are these logs?

**Comment by orfeous1** [comment]
Nevermind, seems to be fixed now, just got an update when i open Kodi. Must have been released last days.
Issue can be deleted.
