### ISSUE TITLE
VRT no streams

### ISSUE THREAD

**Issue by Arathonk** [retrospect-addon/plugin.video.retrospect#1500]
### Describe the bug

All VRT programs give the no stream notification

## Expected Behavior

To see and play streams

## Actual Behavior

It says no streams

## Possible Fix

-

### To Reproduce

1. Click any VRT program
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/ataniyivah

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.9.0
- Retrospect version: 5.2.25

**Comment by basrieter** [comment]
Please fill out the template and provide a DEBUG Retrospect log.

**Comment by Arathonk** [comment]
> Please fill out the template and provide a DEBUG Retrospect log.

Added the log and info.

**Comment by basrieter** [comment]
Please try this version for Kodi Matrix: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/issue-1500.zip

**Comment by Arathonk** [comment]
> Please try this version for Kodi Matrix: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/issue-1500.zip

That's not an update to the addon?

**Comment by basrieter** [comment]
It is, for Kodi Matrix. You can install it via the "install from zip" option.

**Comment by Arathonk** [comment]
> It is, for Kodi Matrix. You can install it via the "install from zip" option.

But I don't have Matrix yet, still on 18.9. And I thought we should always update using the repository?

**Comment by basrieter** [comment]
I always want to have some feedback from the issue submitter to see if the issue is actually fixed. 

Any chance to install Matrix somewhere and check? The platform (Windows, Linux or Android) does not really matter.

**Comment by Arathonk** [comment]
Unfortunately not.. I can't upgrade to Matrix yet. Waiting for Libreelec to do so. Can you fix it for 18.9?

**Comment by basrieter** [comment]
Try this one.

[plugin.video.retrospect-5.2.25-1500.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/6217671/plugin.video.retrospect-5.2.25-1500.zip)

**Comment by Arathonk** [comment]
That works! What's going to happen now? Are you going to implement it in a new update for Retrospect?

**Comment by basrieter** [comment]
Yes, if it all works, I will release a new version tonight.

**Comment by Arathonk** [comment]
Great! Well with that fix VRT works for me so thanks!
