### ISSUE TITLE
Integratie van Up Next

### ISSUE THREAD

**Issue by kengithub9** [retrospect-addon/plugin.video.retrospect#1501]
Je addon is helemaal top,
maar nu zag ik bij de VTM addon Up Next, een addon die automatisch de volgende aflevering laat afspelen. 
Is het mogelijk om Up Next te verwerken in Retropect?

**Comment by basrieter** [comment]
Thanks voor de complimenten. 

Welke toegevoegde waarde heeft "Up Next" ten opzicht van de "Play from here" icm de juiste sortering binnen Kodi?

**Comment by kengithub9** [comment]
Ik heb geen idee wat je bedoelt, waar kan ik dat vinden?

**Comment by basrieter** [comment]
![image](https://user-images.githubusercontent.com/1310443/114473251-2df09880-9bf4-11eb-9ea8-70d166c31f63.png)

**Comment by kengithub9** [comment]
Ik snap nu wat je bedoelt, werkt dat dan hetzelfde als Up Next?

**Comment by basrieter** [comment]
Je krijgt dan geen mooie GUI zoals in UpNext, maar hij speelt wel gewoon alle afleveringen af.

**Comment by basrieter** [comment]
Ik weet al weer wat het probleem is bij Retrospect: de resultaten zijn niet altijd chronologisch en dus is het lastig te bepalen wat "de volgende" is. Soms is dat gebaseerd op datum, soms op enkel seizoen en aflevering.

**Comment by PhyxionNL** [comment]
> Ik weet al weer wat het probleem is bij Retrospect: de resultaten zijn niet altijd chronologisch en dus is het lastig te bepalen wat "de volgende" is. Soms is dat gebaseerd op datum, soms op enkel seizoen en aflevering.

Ik haak even hierin, want het lijkt gerelateerd. Binnen Kodi heb je de optie om automatisch de eerstvolgende ongekeken TV aflevering te selecteren. Als Retrospect hetzelfde zou doen (afhankelijk van de sortering) dan zou dat handig zijn. Uiteraard zal dat niet voor elke aflevering correct zijn i.v.m. herhalingen, maar voor het merendeel zou het in ieder geval een stap in de juiste richting zijn. Bij sortering op datum, dan zou de eerste boven de laatst gekeken aflevering geselecteerd kunnen worden, bijvoorbeeld:

![image](https://user-images.githubusercontent.com/7643972/114687567-317b4100-9d14-11eb-8327-8784c67af15f.png)

**Comment by basrieter** [comment]
Dat klopt, maar de sortering wordt nu volledig door Kodi gedaan, niet in Retrospect. Maar daar ga ik wel uit komen. Het zal niet perfect zijn, maar voor de meeste NL kanalen, die wel een datum hebben, gaat het werken.

**Comment by PhyxionNL** [comment]
Oké, ik weet niet precies wat er kan binnen Kodi, misschien is zoiets mogelijk?

- Bekijken of Kodi gesorteerd is op datum bij de eerste keer inladen.
- Zo ja, selecteer de eerste nieuwere aflevering (of de huidige aflevering indien nog met één bezig). Nieuwere omdat je twee kanten op kan sorteren.

Dat het niet overal bij werkt is geen probleem lijkt mij, als de benodigde informatie ontbreekt dan is het niet anders 🙂

**Comment by basrieter** [comment]
Ik heb de basics. Deze kan je proberen door https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/issue-1501-upnext.zip te installeren in Kodi Matrix (Sorry geen Leia, die komt als het af is).

**Comment by kengithub9** [comment]
Bedankt en ik ga het uit testen.

**Comment by basrieter** [comment]
> Bedankt en ik ga het uit testen.

Ok! De voortgang van de implementatie staat in deze PR: https://github.com/retrospect-addon/plugin.video.retrospect/pull/1502

**Comment by basrieter** [comment]
A Leia version can be found here: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/kodi-leia.zip
The Matrix version here: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/master.zip

It will be in the next main release.

**Comment by basrieter** [comment]
Zou jij deze nog kunnen testen: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/features-media-content-types.zip?

**Comment by PhyxionNL** [comment]
Ik @basrieter? Ik gebruik nog Leia i.v.m. andere addons die nog niet geüpdatet zijn.

**Comment by basrieter** [comment]
of @kengithub9?

**Comment by PhyxionNL** [comment]
> Je zou ook zelf de `leia` branch kunnen rebasen op de `features-media-content-types` branch. Dat zou ook moeten werken voor Leia.

De merge into leia ging wel goed, maar de installatie niet 😟 Installation failed due to an invalid structure of iets dergelijks. Heb het al even vergeleken met één van de "Release" maar die zip structuur ziet er hetzelfde uit 😕

**Comment by basrieter** [comment]
Kan je de zip hier toevoegen? Dan kijk ik een.

**Comment by PhyxionNL** [comment]
Het is inmiddels gelukt door de zip naar een andere locatie te kopiëren, geen idee waarom het bij die andere locatie niet werkte (daar installeer ik normaal ook zips vanaf).

Ik gebruik Up Next niet, maar hij selecteert nog niet de laatste ongekeken aflevering in de lijst. Zit dat er al in? Of is het alleen nog Up Next integratie?

**Comment by PhyxionNL** [comment]
```txt
20210422 20:02:33 - [DEBUG   ] - folderaction.py      - 56   - Stopwatch :: Lap (Plugin process_folder_list) Class process_folder_list finished: elapsed since start: 206.000089645 ms (delta +206.000089645 ms)
20210422 20:02:33 - [DEBUG   ] - folderaction.py      - 66   - process_folder_list returned 310 items
20210422 20:02:33 - [DEBUG   ] - folderaction.py      - 102  - Stopwatch :: Lap (Plugin process_folder_list) Kodi Items generated: elapsed since start: 233.999967575 ms (delta +27.9998779297 ms)
20210422 20:02:33 - [DEBUG   ] - folderaction.py      - 106  - Stopwatch :: Lap (Plugin process_folder_list) items send to Kodi: elapsed since start: 235.000133514 ms (delta +1.00016593933 ms)
20210422 20:02:33 - [DEBUG   ] - pickler.py           - 184  - PickleStore: Write to 'C:\Users\Kodi\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.retrospect\pickles\da\01\da011f6d4ef589fc5e651666865050266348942ddc0ab33a57b14cded0f8aa8a.store.z'
20210422 20:02:33 - [DEBUG   ] - folderaction.py      - 111  - Stopwatch :: Stop (Plugin process_folder_list): 1619114553.74, time elapsed: 243.000030518 ms (+7.99989700317 ms)
20210422 20:02:33 - [DEBUG   ] - folderaction.py      - 275  - Sorting methods: [3, 1, 24, 40]
20210422 20:02:33 - [DEBUG   ] - folderaction.py      - 325  - Setting content-type to: episodes
20210422 20:02:33 - [DEBUG   ] - kodisettings.py      - 70   - Removed Kodi settings-store`

Dit geeft ie wel weer in de log, maar Kodi selecteert niet de laatste ongekeken aflevering. Ik zal Up Next eens proberen te installeren.

**Comment by basrieter** [comment]
je hebt daar echt UpNext voor nodig. Of "Play from here" selecteren in Kodi zelf. Maar dat is echt minder geadvanceerd.

**Comment by PhyxionNL** [comment]
Hmm, ik heb Up Next nu geïnstalleerd en Kodi opnieuw opgestart, maar hij selecteert de aflevering van 08-04-2021 alsnog niet.
![image](https://user-images.githubusercontent.com/7643972/115765220-c9c59580-a3a6-11eb-89b6-66dbff28a277.png)

Hij blijft maar de vorige folder (..) selecteren. Andere programma's worden ook niet geselecteerd.

**Comment by basrieter** [comment]
Wat zou moeten gebeuren is dat als je die van 08-04 aan het spelen hij daarna een gui moet tonen en dan die van 12-04 gaat spelen.

**Comment by PhyxionNL** [comment]
Dat werkt hier niet in ieder geval. Ik heb het geïnstalleerd, maar in de log staat ook dit:

> 20210423 09:18:41 - [DEBUG   ] - addonsettings.py     - 566  - Up Next: installed=False, use=True

 Maar wat ik eigenlijk bedoelde is dat de aflevering van 08-04 ook geselecteerd wordt bij het openen van de lijst (of 07-04 indien die nog niet uit is). Bij Met het Mes op Tafel is het hier niet zo erg om naar beneden te scrollen, maar als je nog 30 afleveringen moet kijken is het wel een heel lang stuk om naar beneden te gaan.

**Comment by basrieter** [comment]
Apart, want dat is toch iets dat Kodi zelf regelt. Ik ga kijken.

**Comment by basrieter** [comment]
Gisteren is een nieuwe Retrospect gepushed naar zowel Kodi Matrix als Kodi Leia. Daarin zit de Up Next integratie.

**Comment by PhyxionNL** [comment]
Werkt nog steeds niet hier in Leia.
20210502 13:00:18 - [DEBUG   ] - addonsettings.py     - 566  - Up Next: installed=False, use=True

Up Next is wel geïnstalleerd (en werkt ook bij "normale" TV shows).

**Comment by basrieter** [comment]
Juist, Leia! Zie dat ik `System.AddonIsEnabled(service.upnext)')` gebruik, die bestaat niet op Leia! Ff wat checken.

**Comment by basrieter** [comment]
Probeer deze eens op Kodi Leia: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/issue-1501-leia.zip

**Comment by PhyxionNL** [comment]
Die werkt! De preview text is alleen wel wat vreemd.
SNoneENone - Met het Mes op Tafel.
Kan daar niet de datum staan?

Had je hier al naar gekeken trouwens? Dit werkt nog niet in ieder geval.

> Maar wat ik eigenlijk bedoelde is dat de aflevering van 08-04 ook geselecteerd wordt bij het openen van de lijst (of 07-04 indien die nog niet uit is). Bij Met het Mes op Tafel is het hier niet zo erg om naar beneden te scrollen, maar als je nog 30 afleveringen moet kijken is het wel een heel lang stuk om naar beneden te gaan.

**Comment by basrieter** [comment]
Ik ga het fixen dat er geen `None` meer staat. Wat betreft de lijst: dat is echt Kodi. Maar je kunt altijd sorteren op aflopende datum in de lijst?

**Comment by basrieter** [comment]
Kan je de zip nog eens downloaden, installeren en proberen?

**Comment by basrieter** [comment]
Ook net nog even de airdate erbij gezet.

**Comment by PhyxionNL** [comment]
> 
> 
> Ik ga het fixen dat er geen `None` meer staat. Wat betreft de lijst: dat is echt Kodi. Maar je kunt altijd sorteren op aflopende datum in de lijst?

Ja, zo ziet het er goed uit. Ik sorteer al op aflopende datum, maar als je bij sommige programma's met veel afleveringen/seizoenen een stuk achter ligt dan moet je enorm ver naar beneden scrollen. Op de PC met toetsenbord is dat niet zo'n probleem met PageDown, maar op de TV met afstandsbediening via CEC verbonden gaat het erg traag. Bij normale TV shows selecteert Kodi automatisch de eerstvolgende aflevering. Is het niet mogelijk om daarin mee te gaan (als dat aanstaat)?

**Comment by basrieter** [comment]
Ik heb dat gedrag echt nog nooit gezien in Kodi, ook niet bij normale TV Shows? Up Next doet dat in iedergeval niet. Je kunt wel gewoon de "watched" items hiden in Kodi.

**Comment by PhyxionNL** [comment]
Zit er wel in hoor (gebruik dat al jaren zo 🙂):

![image](https://user-images.githubusercontent.com/7643972/116819479-87534400-ab70-11eb-87d3-1ae1b086ca1a.png)

Dat met de scrollbar zal ik eens zien of dat wat werkt @ TV.

**Comment by basrieter** [comment]
Lijkt inderdaad niet te werken voor video plugins? Werkt het bij andere add-ons wel?

**Comment by basrieter** [comment]
Even navraag gedaan: 
![image](https://user-images.githubusercontent.com/1310443/116824279-a0b4ba00-ab89-11eb-8792-91c69af94920.png)

Kan dus niet voor add-ons.

**Comment by PhyxionNL** [comment]
Ah, jammer, nou ja, dan is het niet anders :)

**Comment by basrieter** [comment]
Ik heb de settings in Retrospect wat getweaked voor Up Next. Voor Matrix kunnen jullie dat proberen door https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/master.zip te installeren.
