### ISSUE TITLE
Error retrieving list of items

### ISSUE THREAD

**Issue by sluwtje** [retrospect-addon/plugin.video.retrospect#1504]
Last Night at 02:15 am cet (NL time) when selecting Kijk/recent/today to watch "Hart van Nederland" from 22:30 pm, got "Error retrieving list of items.

Log: https://paste.kodi.tv/idazakoboc

**Comment by basrieter** [comment]
Weird, it's working as expected now. Might have been an issue at their end?

**Comment by sluwtje** [comment]
It only happens at night past 12 AM CET.
Yes it's strange.

Op do 22 apr. 2021 19:18 schreef Bas Rieter ***@***.***>:
