### ISSUE TITLE
no sound in swedish channel other addons works

### ISSUE THREAD

**Issue by cabban** [retrospect-addon/plugin.video.retrospect#1505]
## Bug report
cno sound in retrospect 

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.9
- Retrospect version: .31

@basrieter 
any tips and ideas appreciated

**Comment by basrieter** [comment]
I need much more info to work with. Please provide information such as: 

- What channel
- What show
- What episode

And include a full DEBUG retrospect.log.

**Comment by basrieter** [comment]
Great! Enjoy Kodi and Retrospect.
