### ISSUE TITLE
Nick Jr. International: Error Processing FolderList

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1508]
### Describe the bug

When select Nick Jr. International I get the error 'Error Processing FolderList' and no list of program is displayed.

## Expected Behavior

Show the program list

## Actual Behavior

No program list is displayed

### To Reproduce

1. Start Retrospect
2. Enable Nick Jr. International
3. Start Nick Jr. International

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/piqewuquze.kodi

### Screenshots 

n/a

## Additional context or screenshots (if appropriate)

n/a

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.0
- Retrospect version: 5.3.2

**Comment by basrieter** [comment]
It seems that https://www.nickjr.tv/ is completely empty at the moment?

**Comment by matsarv** [comment]
Sorry, did not check out the site. We'll see when it comes up again.

**Comment by basrieter** [comment]
If it stays empty, I will most likely remove the channel.

**Comment by matsarv** [comment]
Still no live streams. They seem to do some work but right now it only contains a TV Scedulder, the same now applies to nickjr.nl
I think the best thing is to hide nickjr.xx for now.
