### ISSUE TITLE
Error retrieving list of items NPO

### ISSUE THREAD

**Issue by Coenstegeman** [retrospect-addon/plugin.video.retrospect#1511]
### Describe the bug

NPO says 'error retrieving list of items' when selecting a program folder to open, if filter for paid items is set to 'folders & streams'. Does not seem to happen on all programs, though (2 voor 12 and 2Doc do show the error, but 2Doc Kort and 2 Meter Sessies don't, for example). 

In NPO A-Z some folders also disappear with filter set. 

## Expected Behavior

Open folder and show the episodes within. 

## Actual Behavior

Gives error and doesn't open folder (of certain programs, but not all). 

## Possible Fix

Set filter for paid items to 'streams only' and all lists seem to work again (obviously I haven't tested them all). 

### To Reproduce

1. Set paid filter to 'folders & streams' 
2. Select program in NPO to open list of episodes
3. (Not all programs give the error) 

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/aqusiyadab

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.9
- Retrospect version: 5.3.2

**Comment by Coenstegeman** [comment]
Copied your fix into my own chn_class.py (I am still on Leia for now, so Python 2) and it works. Seems to be fixed now!

**Comment by basrieter** [comment]
Great! You can find a dev build for Leia here: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/kodi-leia.zip
