### ISSUE TITLE
Nos.nl speelt geen video's af

### ISSUE THREAD

**Issue by MijnGithubAccount** [retrospect-addon/plugin.video.retrospect#1512]
Hallo,  

De streams van NOS.nl spelen geen video's af.
Je kan wel kiezen maar opent de streams niet.
Ik heb KODI 18.7 Leia met de nieuwe widevine.

Hopelijk valt dit te herstellen.

Gr,

**Comment by basrieter** [comment]
Graag een debug retrospect.log: dus debug logging in Retrospect aanzetten, nogmaals het probleem reproduceren, daarna de logfile uploaden en de link hier posten.

**Comment by basrieter** [comment]
Al gevonden. Je kunt deze zip installeren in Kodi om te kijken of het werkt: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1512.zip

Graag verneem ik of dat het geval is.

**Comment by lagosazules** [comment]
Plugin werkt niet op kodi OSMC <3.0.
OSMC met python 3.0 is er helaas nog niet

**Comment by basrieter** [comment]
Geen Windows/Linux device om op te testen?

**Comment by basrieter** [comment]
Try this one for Leia:

[plugin.video.retrospect-5.3.2-bug-1512-leia.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/6475195/plugin.video.retrospect-5.3.2-bug-1512-leia.zip)

**Comment by MijnGithubAccount** [comment]
Thx it’s working again now 👍👍👍



Verzonden vanuit Mail voor Windows 10

Van: Bas Rieter
Verzonden: donderdag 13 mei 2021 23:32
Aan: retrospect-addon/plugin.video.retrospect
CC: MijnGithubAccount; Author
Onderwerp: Re: [retrospect-addon/plugin.video.retrospect] Nos.nl speelt geenvideo's af (#1512)

Try this one for Leia:
plugin.video.retrospect-5.3.2-bug-1512-leia.zip
