### ISSUE TITLE
Playback issue after Widevine CDM update

### ISSUE THREAD

**Issue by didamsko** [retrospect-addon/plugin.video.retrospect#1515]
### Describe the bug

Recently I had a Widevine CDM update prompt while running Retrospect 5.3.2 on my holiday location Odroid-C2, I applied that update and all worked fine at first but after next boot playback is no longer working on (as far as I saw) all but a few old programs. 

When i reverted back to a backup before the Widevine CDM update playback is working again. And it keeps working as long as I keep pressing cancel on the Widevine CDM update prompt that pops up every time when starting playback of a program. 

I tried if Retrospect 5.4.0 would fix the issue but as soon as I updated the Widevine CDM the same playback problem occurs after reboot or next boot. 

## Expected Behavior

The player starts --> Playback

## Actual Behavior

The player starts but halts --> No playback. 

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

https://paste.kodi.tv/ijiqijubab.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: Running latest LibreELEC for Odroid-C2: "LibreELEC-Odroid_C2.arm-9.0.2" with Kodi v18.2 Leia
- Retrospect version: Retrospect 5.3.2 + Retrospect 5.4.0

**Comment by basrieter** [comment]
Yes, that is a know issue: https://github.com/xbmc/inputstream.adaptive/issues/678

Nothing that I can do. There was an update to the https://github.com/emilsvennesson/script.module.inputstreamhelper add-on that prevents updates for the moment.

**Comment by didamsko** [comment]
Thanks Bas. Will see how it develops and update the script.module.inputstreamhelper manually, somehow it had not yet updated itself. 

https://github.com/emilsvennesson/script.module.inputstreamhelper/releases

**Comment by basrieter** [comment]
Re-opening to make sure people see the issue.

**Comment by basrieter** [comment]
Please read this: https://www.matthuisman.nz/2021/05/widevine-arm-broken.html

It contains steps how to fix it.

**Comment by didamsko** [comment]
Thanks for the pointer Bas. My main Kodi OS is OSMC on a Vero 4K+ and it looks like its going to be a bit of a wait till things get sorted there. Will see if i can get the 9.2.8 version of LibreELEC running on my Raspberry Pi3 that i still should have laying around somewhere.

**Comment by didamsko** [comment]
Up and running again on Raspberry Pi3 with LibreELEC 9.2.8 :-)

**Comment by basrieter** [comment]
You can also use the InputStream Adaptive Helper add-on (Installed with Retrospect) to force update of WideVine instead of 'Slyguy Common'. The reboot your device.

**Comment by basrieter** [comment]
Closing this as it should all be ok now with all the updates in Adaptive InputStream.

**Comment by didamsko** [comment]
Yep. Looks like most boxes should be able to work again with the new Widevine CDM. 

I already had my Raspberry Pi3 working with LibreELEC 9.2.8 and now also got my Vero 4K+ sorted with the 2021.08-1 OSMC release (also nicely plays MVC-3D btw): https://osmc.tv/download/

And Retrospect is also working again on my WeTek Play 2 en ODROID-C2 running the stable CoreELEC Legacy Build 9.2.8: https://coreelec.org/legacy/#download 

The CoreELEC Legacy Build supports a lot of older boxes.
