### ISSUE TITLE
Issue with NPO Start "bullets/icons" in the "TV shows (A-Z)"

### ISSUE THREAD

**Issue by didamsko** [retrospect-addon/plugin.video.retrospect#1516]
### Describe the bug

The NPO Start "TV shows (A-Z)" list shows wrong "bullet/icon" images. See image below. 

Looks like one got overlooked from this issue from the past: https://github.com/retrospect-addon/plugin.video.retrospect/issues/1479

## Expected Behavior

A square grayish folder icon.

## Actual Behavior

A small version of one the Retrospect channel logo or artwork images.

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Screenshots 

![20210516_190710 1](https://user-images.githubusercontent.com/60958082/118408167-9237c980-b684-11eb-925c-3658c771e702.jpg)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: Running latest LibreELEC for Odroid-C2: "LibreELEC-Odroid_C2.arm-9.0.2" with Kodi v18.2 Leia
- Retrospect version: Retrospect 5.3.2 + Retrospect 5.4.0

**Comment by basrieter** [comment]
What skin are you using, an please attach a full debug retrospect.log

**Comment by basrieter** [comment]
Can you try this one: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1516.zip in Kodi Matrix.

**Comment by didamsko** [comment]
The fix does not run on my media player. Its an Odroid-C2 running the latest LibreELEC version available for it: "LibreELEC-Odroid_C2.arm-9.0.2" with Kodi v18.2 Leia.

The skin in use is the default Kodi skin Estuary.

**Comment by basrieter** [comment]
NP, use https://raw.githubusercontent.com/retrospect-addon/plugin.video.retrospect/8533e106c6f71dd745cd0a812b05e1addf87e407/channels/channel.nos/nos2010/chn_nos2010.py as a replacement for your chn_nos2010.py file. Restart Kodi and try again.

**Comment by didamsko** [comment]
Thanks! It worked: 

![20210517_124634](https://user-images.githubusercontent.com/60958082/118477449-fa32f200-b70e-11eb-8f77-42e54d702481.jpg)

**Comment by basrieter** [comment]
Great. I will merge this for the next release.
