### ISSUE TITLE
NPO items won't play (aborted within a second)

### ISSUE THREAD

**Issue by H2172** [retrospect-addon/plugin.video.retrospect#1519]
### Describe the bug

Starting items from NPO channel, the item will appear to launch briefly (Kodi indicator starting the item), but then abort within a second and won't play.

## Expected Behavior

Item should play

## Actual Behavior

Item seems to start but then aborts

### To Reproduce

1. Retrospect
2. Channel NPO
3. Start item for Journaal 20:00, 16 may 2021

### Debuglog

The **debug** retrospect.log can be found here:
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/6495540/retrospect.log)

## Additional context or screenshots (if appropriate)

I can't rule out an issue on my installation. However, I did remove Retrospect and its settings and installed again, with the same result. If it's an issue on my system, could you point me at the issue based on my log?

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.9.0 on LibreELEC 9.2.6
- Retrospect version: 5.3.2

**Comment by H2172** [comment]
The recently released 5.4.0 seems to have the same issue. (Didn't notice this new version until now, but updated now, rebooted, same result.)

**Comment by basrieter** [comment]
This is a Widevine issue. Rollback to an earlier version of WideVine via the Inputstream adaptive. See #1515

**Comment by H2172** [comment]
OK will give that a try, thank you!!

**Comment by H2172** [comment]
Thanks again. I have Rolled back to Inputstream Adaptive version 2.4.5.1, then reinstalled WideVine via Inputstream Helper, and now it's fixed. I'll disable auto-updates for Inputstream Adaptive for now...

**Comment by basrieter** [comment]
Great! We are working on fixing Widevine in Kodi.
