### ISSUE TITLE
npostart and rtl not playing on Leia (Libreelec)

### ISSUE THREAD

**Issue by pschoond** [retrospect-addon/plugin.video.retrospect#1520]
### Describe the bug

npostart and rtl won't play anymore, neither live tv or older items. Not sure when it started, probably after the last update of Retrospect or Widedevine.
All items are there in the list.

## Expected Behavior

Item should play when clicked.

## Actual Behavior

Small glitch of the player starting, and closes immediately.

## Possible Fix

Tried Matrix version on Debian testing (11), works ok.

### To Reproduce

1. Select an item in npostart, click it. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
paste.kodi.tv/onalupucew

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ X] Raspberry-Pi LibreElec
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.9 latest
- Retrospect version: 5.4

**Comment by basrieter** [comment]
Please search previous issues. This is a Widevine issue. Rollback to an earlier version of WideVine via the Inputstream adaptive. See #1515, #1519 and  xbmc/inputstream.adaptive#678
