### ISSUE TITLE
NPO and RTL don't show video anymore (Audio Only)

### ISSUE THREAD

**Issue by adjego** [retrospect-addon/plugin.video.retrospect#1522]
### Describe the bug

When trying to play streams from NPO Start or RTLXL, it only will play the audio when playing this on a Nvidia Shield. Playing a stream from Kijk.nl does work as expected. The problem of only having audio is not happening when playing the same streams on Windows via Kodi.

## Expected Behavior

Video and audio is available when playing stream from NPO Start / RTL XL.

## Actual Behavior

Only audio is available when playing stream from NPO Start / RTL XL.

### To Reproduce

1. From Retrospect, open NPO Start / RTL XL folder on Nvidia Shield.
2. Select recent stream and play.

### Debuglog

The **debug** retrospect.log can be found here: https://paste.kodi.tv/fisakaremo

### Your Environment
Used Operating system:

 - [x] Android -> Nvidia Shield
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.1 (19.1.0) Git: 20210508.85e05228b4
- Retrospect version: 5.4.0+matrix.1
- Android TV Version: Android 9.0.0
- Shield Android TV SW Version: 8.2.2 (32.6.509.0)

**Comment by basrieter** [comment]
Please rollback the update of the InputStream Adaptive add-on.

**Comment by adjego** [comment]
> Please rollback the update of the InputStream Adaptive add-on.

I don't know what i did now, i think i reinstalled latest addon version which is 2.6.16 and it seems to be working again. So i guess this bug can be closed again as "not reproducible".

**Comment by basrieter** [comment]
Great!
