### ISSUE TITLE
Sweden, TV4 Play: Big Brother Sverige doesn't show listings for May episodes

### ISSUE THREAD

**Issue by Snaah** [retrospect-addon/plugin.video.retrospect#1524]
### Describe the bug

Creating this issue on behalf of [user Siddan](https://forum.kodi.tv/showthread.php?tid=25522&pid=3040365#pid3040365).

When listing episodes for "Big Brother Sverige" episodes after 2021-04-28 don't show, although they are on [TV4 Play's website](https://www.tv4play.se/program/big-brother-sverige).

## Expected Behavior

Show all episodes.

## Actual Behavior

Retrospect doesn't show episodes after 2021-04-28.

### To Reproduce

1. Go to TV4 Play.
2. List episodes for "Big Brother Sverige"
3.

### Debuglog

The **debug** retrospect.log can be found here: https://paste.kodi.tv/anifugoyep.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.1 Matrix
- Retrospect version: 5.40+matrix.1

**Comment by basrieter** [comment]
Please try this zip file for Kodi Matrix: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1524.zip

**Comment by Snaah** [comment]
It shows all episodes now, but:

-  the listing for "Big Brother Sverige" also show the listing for the separate program "Big Brother Sverige - Bara huset" (The listing for "Big Brother Sverige - Bara huset" correctly only shows episodes for that program.)
- Episodes after s02e73 2021-04-28 are shown on the second page, even if you sort them by date
- "Sida Flera sidor" means "Page More pages"

**Comment by basrieter** [comment]
Let me fix those:

* [ ] Episodes after s02e73 2021-04-28 are shown on the second page, even if you sort them by date
* [ ] "Sida Flera sidor" means "Page More pages"

**Comment by basrieter** [comment]
Please redownload https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1524.zip and try again.

**Comment by basrieter** [comment]
Is this good to go like this?

**Comment by matsarv** [comment]
FYI.
I updated the changed file chn_tv4se.py for TV4 Play and now all episodes are shown until the end of the season (a total of 137 streams) and the Page More pages is gone. So everything looks good according to what I can see.
