### ISSUE TITLE
New request: cmore swedish channel

### ISSUE THREAD

**Issue by krille30** [retrospect-addon/plugin.video.retrospect#1525]
### What Channel would you like to add and why?

Cmore.se

### Provide some details for the channel
- Name of the channel in English:cmore.se
- Name of the channel in native language: cmore.se
- Website for the channel:cmore.se
- If available link to the Android app for the VOD content of channel:
- https://play.google.com/store/apps/details?id=se.cmore.bonnier
- Link to the logo of the channel
 
### Check which features should be implemented
- [x] Video on-demand content
- [x] TV live streams
- [x] Use your account for the VOD services from Retrospect
- [x] Access the premium content if you are eligible  

### Additional information

This channel require premium login

**Comment by basrieter** [comment]
I would need to see how the log in works. Are there also free accounts?

**Comment by krille30** [comment]
Yes there is also possible to create free account here https://www.cmore.se/login , it is same free account as used for tv4play.se

But it is very limited content in cmore for free account, only some of the livetv is working.
