### ISSUE TITLE
Widevine complains that new version probably doesn't work on LibreElec?

### ISSUE THREAD

**Issue by bartmans** [retrospect-addon/plugin.video.retrospect#1527]
Most recent episodes from 'Freeks Wilde Wereld' complain about older version of Widevine CDM. But when I try to update it suggests that installing latest Widevine might break playback.

I haven't been able to reproduce this on Windows, only on my RPi4 with latest LibreElec en Kodi (19.1).

But the message seems to be coming from Retrospect so maybe you have an explanation / solution?

So far playback works when ignoring the update message.

**Comment by basrieter** [comment]
The message is coming from the inputstream adaptive helper module. The add-on makes sure that Widevine keeps working. There are some challenges on this area at the moment. You can disable the auto updating of Widevine there.
