### ISSUE TITLE
TV Oost live is not working, other programs are fine

### ISSUE THREAD

**Issue by ErikBrown2** [retrospect-addon/plugin.video.retrospect#1529]
### Describe the bug

The live TV of TV Oost (Dutch channel) is not not working. Selecting it from the menu results in "Working" with the moving circle for about two seconds and then the message "Retrospect - Error Error retrieving the list of items". All other programs of TV Oost work fine. On the webbrowser of my laptop, the live TV program works fine.

## Expected Behavior

Selecting the Live TV channel of TV Oost is expected to show the live TV program.

## Actual Behavior

Selecting the Live TV program from the menu results in "Working" with the moving circle for about two seconds and then the message "Retrospect - Error Error retrieving the list of items".

## Possible Fix

You know best.

### To Reproduce
Steps to reproduce the behaviour:

1. Go to Retrospect add on - Regional - RTV Oost - Live TV - TV Oost and press enter
2. Working will be shown for two seconds followed by "Retrospect - Error Error retrieving the list of items".
3.

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/ofijujiquj
Kodi debug log = https://paste.kodi.tv/jehegosapo.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.9.0
- Retrospect version: 5.4.1
- LibreElec : 9.2.7

**Comment by basrieter** [comment]
Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1529.zip in Kodi Matrix to test.

**Comment by ErikBrown2** [comment]
It works now fine on Kodi 19.1 on my laptop. Thank you very much for the fix. 
You specifically mentioned to try it on Kodi Matrix. Can this fix also be used on Kodi 18.9 on a Raspberry Pi 3?

**Comment by basrieter** [comment]
Will do a release soon.
