### ISSUE TITLE
SRF.ch not working

### ISSUE THREAD

**Issue by Magbert1** [retrospect-addon/plugin.video.retrospect#1535]
Thanks for looking into this!

### Describe the bug
Error message 'Error retrieving list of items' when opening SRF.ch

## Expected Behavior
Items should be listed. No error message

## Actual Behavior
When opening SRF.ch there is an error message 'Retrospect error. Error retrieving list of items'

## Possible Fix
Probably SRF.ch changed to API

### To [Reproduce]
1. Open Retrospect
2. Open SRF.ch

### Debuglog

https://drive.google.com/file/d/1Pl8i16mp_cjMOo0Hz_B7a1DucEHA9nQb/view?usp=sharing

### Your Environment
Used Operating system: Libreelec 9.95.5
Raspberry Pie RPi4.arm

Used versions:
- Kodi version: 19.1 Matrix
- Retrospect version: 5.4.3+matrix.1

**Comment by basrieter** [comment]
Op please don't copy paste logiles. Update your bug report and attach the full debug retrospect.log.

**Comment by Magbert1** [comment]
Corrected. Added URL

**Comment by basrieter** [comment]
Please test https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1535.zip on Kodi Matrix (Use the "Install from Zip" option).

**Comment by Magbert1** [comment]
Thanks Bas. You are awesome!
That was the fastest Bugfix I have seen in my life.
Works like a charm.
Many thanks!

**Comment by basrieter** [comment]
Great! I am going to add the live channels tomorrow, but those are geo blocked so it's a bit harder to test for me.

**Comment by basrieter** [comment]
I also added initial support for the Live streams. Download https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1535.zip again in install it.

Due to the Geo and the DRM I need a session trace from Chrome navigating to the SRF live streams and playing one. See https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting.

Could you create one and attach it here?

Also: thanks for the donation, it will be used wisely.

**Comment by Magbert1** [comment]
Sure!
The session trace can be found here: https://drive.google.com/file/d/1NyLs03fPxTZwBCvDtAgJVslOtHY9K7CT/view?usp=sharing

**Comment by basrieter** [comment]
Thanks. Could you give https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1535.zip another try?

**Comment by Magbert1** [comment]
Working fine! But I am unable to find any live channels.

Should they be implemented or are you still working on it?

**Comment by basrieter** [comment]
That should be exactly what I am wondering. Live channels are should be there:

![image](https://user-images.githubusercontent.com/1310443/127070926-0f61a0a7-b1b5-4a03-b574-b8140ad40976.png)

![image](https://user-images.githubusercontent.com/1310443/127070984-f02d65a8-a199-48c0-bb59-c0847af08fc7.png)


If not, please redownload https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1535.zip and reinstall it in Kodi. The restart Kodi and double check.

**Comment by Magbert1** [comment]
There are no live channels for me me. I completely uninstalled Retrospect, installed it again from https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1535.zip and restarted Kodi.

**Comment by basrieter** [comment]
I think I see the issue. Please redownload https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1535.zip and try again. The Live items were grouped by default.

**Comment by Magbert1** [comment]
Success! I see the live channels now and they play just fine!

Well done!

**Comment by basrieter** [comment]
Great news! Let me see if I can get this into an actual Retrospect release. I am a bit busy at the moment, so that might take a bit of time. I also want to see if I can include #1095 in that release.

**Comment by basrieter** [comment]
I will try to get in the next release soon. Just merged it into`master`.

**Comment by Magbert1** [comment]
Perfect! Thanks!
