### ISSUE TITLE
Viafree Error retrieving list of items

### ISSUE THREAD

**Issue by bubbleboyy** [retrospect-addon/plugin.video.retrospect#1544]
### Describe the bug

Viafree gives "Error retrieving list of items" when you try to access it.

## Expected Behavior

Viafree would open without any error message.

## Actual Behavior

Error message Error retrieving list of items when you try to access viafree.

### To Reproduce

1. Open Viafree
2. Error message appears
3.

### Debuglog

The **debug** retrospect.log can be found here:
Retrospect: https://paste.kodi.tv/gikegeyato
Kodi: https://paste.kodi.tv/alotivuqok

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.1
- Retrospect version: 5.4.5

**Comment by bubbleboyy** [comment]
Maybe its the same issue as this https://github.com/spaam/svtplay-dl/commit/52d98a8934fac4e88963d943539abd52b25fcc89

**Comment by basrieter** [comment]
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1544.zip. Just install from zip in Kodi Matrix (not Leia).

**Comment by bubbleboyy** [comment]
Its working now. Thanks!

**Comment by basrieter** [comment]
Will try to do a release soon.
