### ISSUE TITLE
No subtitles for SVT Play with Kodi 18.9 and LibreElec 9.2.7 on rpi 3.

### ISSUE THREAD

**Issue by maxruben** [retrospect-addon/plugin.video.retrospect#1545]
### Describe the bug

SVT play does not show subtitles and when selecting the subtitle menu in the player it shows that there are no subtitles.

## Expected Behavior

At least one subtitle found for the show.

## Actual Behavior

No subtitle shown and no subtitles in sthe subtitle dialog.

### To Reproduce

1. Open SVT Play and start Drottningoffret any of the tree episodes.
2. Select the subtitles dialog
3. There are no subtitles for the episode

### Debuglog

The **debug** retrospect.log can be found here: https://paste.kodi.tv/isahuqoqeb.htm

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi 3 with libreelec v9.2.7 and kodi 18.9.0
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: Leia 18.9.0
- Retrospect version: 5.4.5 (latest)

I also have retrospect on an android tablet running kodi matrix and the same episode shows swedish subtitle there.
I have checked the debug log and I can see that there is a subtitle which is converted from type 'webvtt' to 'srt' and placed in the  cache folder and that this is added to the mediastream. The srt file looks ok (but I am no expert). Could this be a inputstream adaptive problem?
inputstream adaptive v 2.4.8.1 from LibreElec add-ons
Inputstream Helper v 0.5.7.

I have tried to do a fresh install on another sd card but it still isn't working.

Thanks /Ruben

**Comment by basrieter** [comment]
Please delete /storage/.kodi/userdata/addon_data/plugin.video.retrospect/cache/E3FB8AB6059B94E1F03A39B5D3B0550E.srt and try that same video again.

**Comment by maxruben** [comment]
Thanks. Tested to delete the created .srt file in the cache folder but that did unfortunately not help.

**Comment by maxruben** [comment]
I tried to change the timeout directly in the videoaction.py file to 30s and now it works. Thanks a lot.
/Ruben

**Comment by basrieter** [comment]
It's released via the Kodi repository.
