### ISSUE TITLE
NPO Channels not working

### ISSUE THREAD

**Issue by noud61** [retrospect-addon/plugin.video.retrospect#1547]
### Describe the bug

Since two days I can't watch the Dutch NPO channels anymore. All the other channels like Kijk.nl and even NOS channels work.

## Expected Behavior

Click on a programme in the list, and it starts playing.

## Actual Behavior

Clicking on a programma on the list, the show seems to start, but at the end it does not start.

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:
- Retrospect version:

**Comment by noud61** [comment]
By the way, I have 2 RPi's. They have both the same issue.

**Comment by basrieter** [comment]
Please read this: https://www.matthuisman.nz/2021/05/widevine-arm-broken.html

It contains steps how to fix it.

**Comment by noud61** [comment]
Okee, Thanks. I will try that later.

**Comment by noud61** [comment]
Thanks it works again.

**Comment by basrieter** [comment]
Great!

**Comment by diekshouse** [comment]
The same problem here, but has not been solved yet.

Updated LibreELEC to 9.2.8, KODI 18.9. But not able to find "Add-ons > My Add-ons > Services > Slyguy Common" on my system. Removed Widevine to force Retrospect downloading and installing it again. Which worked. But it still seems to be the not supported version.

**Comment by basrieter** [comment]
> The same problem here, but has not been solved yet.
> 
> Updated LibreELEC to 9.2.8, KODI 18.9. But not able to find "Add-ons > My Add-ons > Services > Slyguy Common" on my system. Removed Widevine to force Retrospect downloading and installing it again. Which worked. But it still seems to be the not supported version.

Just use the InputStream Adaptive Helper add-on to force update of WideVine

**Comment by diekshouse** [comment]
Did the job! Thanks.

**Comment by DasBootU96** [comment]
> > The same problem here, but has not been solved yet.
> > Updated LibreELEC to 9.2.8, KODI 18.9. But not able to find "Add-ons > My Add-ons > Services > Slyguy Common" on my system. Removed Widevine to force Retrospect downloading and installing it again. Which worked. But it still seems to be the not supported version.
> 
> Just use the InputStream Adaptive Helper add-on (Installed with Retrospect) to force update of WideVine. The reboot your device.

Did the same: removed InputStream Adaptive Helper add-on and removed widevine CDM. Started retrospect and got a prompt to install widevine CDM. Selected 'no' when asked to install an older version. Still get 'playback failed'  error. Also after rebooting.

Using pi4 libreelec 9.95.1. retrospect version 5.4.6+matrix.1.  input stream helper 0.5.7+matrix.1.

Is there something I missed, or must I install this Slyguy Common repo?

**Comment by basrieter** [comment]
> > > The same problem here, but has not been solved yet.
> > > Updated LibreELEC to 9.2.8, KODI 18.9. But not able to find "Add-ons > My Add-ons > Services > Slyguy Common" on my system. Removed Widevine to force Retrospect downloading and installing it again. Which worked. But it still seems to be the not supported version.
> > 
> > 
> > Just use the InputStream Adaptive Helper add-on (Installed with Retrospect) to force update of WideVine. The reboot your device.
> 
> Did the same: opened InputStream Adaptive Helper add-on and removed widevine CDM. Started retrospect and got a prompt to install widevine CDM. Selected 'no' when asked to install an older version. Still get 'playback failed' error. Also after rebooting.
> 
> Using pi4 libreelec 9.95.1. retrospect version 5.4.6+matrix.1. input stream helper 0.5.7+matrix.1.
> 
> Is there something I missed, or must I install this Slyguy Common repo?

Your version of LibreElec seems weird: latest 9.2.x version is 9.2.8 and after that comes 10.x.x. So make sure your LibreElec is correct. Then *reinstall* WideVine from the `InputStream Helper` add-on settings (You can run that add-on from your program add-ons) : 

![image](https://user-images.githubusercontent.com/1310443/132144101-20eb12e2-1955-407c-90a7-93480de16799.png)

After that reboot your system. 

Then verify the right version is running from the `InputStream Helper` add-on settings `InputStream Helper information`:
![image](https://user-images.githubusercontent.com/1310443/132144277-445cbfda-5c9e-4c59-8c14-7ff24a95b6c4.png)
![image](https://user-images.githubusercontent.com/1310443/132144283-691a95ef-b4ca-4818-a9b0-b4d28db71cb2.png)

**Comment by DasBootU96** [comment]
Went through the whole process again: using input stream helper removed widevine, reboot, install widevine, reboot.

Still playback failed.

Running  Kodi v19.0.  noticed there was a v19.1 released recently. Will try that tomorrow.

![screenshot00003](https://user-images.githubusercontent.com/54699211/132145250-60835d1e-a878-4699-a005-33c344cb3acb.png)

![screenshot00002](https://user-images.githubusercontent.com/54699211/132145254-964f7a8f-3401-45d9-b986-5cb967bf880a.png)

![screenshot00000](https://user-images.githubusercontent.com/54699211/132145258-e810a32a-793b-45f6-bd73-af9c6634bc99.png)

**Comment by DasBootU96** [comment]
Nevermind: I updated from 9.95.1 to 10. It's now working fine.

Thanks for the support and the great addon @basrieter  !

![screenshot00004](https://user-images.githubusercontent.com/54699211/132145706-47895fa6-fa56-4589-82d3-661599817aa3.png)

**Comment by noud61** [comment]
If updating to 9.2.8 don't work, you can try updating to 9.2.7. That worked for one of my Raspberry Pi's.

**Comment by diekshouse** [comment]
In my case (pi 3 b) , soft reboot did not solve the problem. I had to turn off the power.

**Comment by streamgoody** [comment]
I used on my PI4, raspberry OS and a install of Kodi. The problems as above NPO channels.
Then saw the link for solutions. LibreELEC.
Took a new sd card, with Raspberry PI imager installed the PI4 LibreELEC, 10.0.0 then installed Input adaptive and widevine, installed addon retrospect, channnel is working, but I have no sound. Over the analog audio 3,5 plug.

Missing: PI HDMI and analogue audio option in kodi audio.

The next solution is not a good one, too much noise.
Using a 3,5 audio jack LibreELEC is not the solution.
I want to pass that on to you all.

There is some code for the LibreELEC config.txt file
[link](https://forum.libreelec.tv/thread/23651-libreelec10-no-audio-on-3-5mm-jack/?pageNo=2)

> The solution is quite simple, clear the overlay scope with "dtoverlay=" or move the dtparam=audio=on statement up, before the include distroconfig.txt.

`dtoverlay=
dtparam=audio=on
audio_pwm_mode=1`

This give the choice in KODI to choose audio ALSA BCM 2835 headphones, then you have sound over the 3,5 audio jack, lot of noise, bad quality.

A LibreELEC problem, Raspberry PI OS, audio worked fine.

**Comment by basrieter** [comment]
That is not a thing cause by Retrospect, but a LibreElec issue. Please see if they can help you at their forums.

**Comment by streamgoody** [comment]
> That is not a thing cause by Retrospect, but a LibreElec issue. Please see if they can help you at their forums.

My post was just for your information.
PI OS
[DRM, For anyone who just can't wait](https://www.raspberrypi.org/forums/viewtopic.php?p=1910100#p1910100)

I did not test it.

**Comment by streamgoody** [comment]
This evening i did a full-upgrade of the Raspberry OS and all NPO channels are working in Kodi on a Raspberry Pi4.
Inside the retrospect addon I updated the widevine.

**Comment by basrieter** [comment]
Closing this as it should all be ok now with all the updates in Adaptive InputStream.
