### ISSUE TITLE
The Radio538 live video stream is no longer working

### ISSUE THREAD

**Issue by jcjdammers** [retrospect-addon/plugin.video.retrospect#1548]
Hi,
The Radio538 live video stream is no longer working.
I use the latest version of the Retrospect addon with Kodi Matrix 19.1 on LE 10.0.

Regards,
Jeroen

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:
- Retrospect version:

**Comment by basrieter** [comment]
Please check #1515 and see it is not a Widevine issue.

**Comment by jcjdammers** [comment]
I don't think it is a Widevine issue. When I create my own strm-file then the stream plays fine.
See also the attached version information from InputStream Helper.
![InputStream Helper Info](https://user-images.githubusercontent.com/10573570/132416827-a1365c0e-ad5b-4553-bcb4-ed61ad34e493.jpg)

**Comment by basrieter** [comment]
Can you try https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1548.zip using the "Install from zip" from Kodi Matrix?

**Comment by jcjdammers** [comment]
I tried and it works !!
