### ISSUE TITLE
SE: TV4 Play error - No episode found...

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1549]
### Describe the bug

When press Currently playing (Livesändningar) showng "Error - No episode found..."
Log is showing: process_folder_list returned 0 items

## Expected Behavior

Display the upcomming Currently playing (Livesändningar)
Livesändningar still exist on the web site.
https://www.tv4play.se/program/live

## Actual Behavior

See above.

### To Reproduce

1. Select TV4 Play
2. Select Currently playing (Livesändningar)

### Debuglog

The **debug** retrospect.log can be found here: https://paste.kodi.tv/helejeceni.kodi

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.1
- Retrospect version: 5.4.6

**Comment by matsarv** [comment]
After being down for a week, it has started to work again today. I'm closing this now.

**Comment by basrieter** [comment]
Ok, let me know when this occurs again.
