### ISSUE TITLE
UR Play does not list categories

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#1550]
### Describe the bug

UR Play does not list categories

## Expected Behavior

It should list.

### Your Environment
Used Operating system:

 - [x] Android
 - [x] iOS
 - [x] Linux
 - [x] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [x] Windows UWP

Used versions:
- Kodi version:  Matrix
- Retrospect version: 5.4.6

**Comment by basrieter** [comment]
Fixed with 58e70ab8

**Comment by matsarv** [comment]
Sorry, late testing again. 
Downloaded: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1550.zip

Might seems to be something wrong when I using the 'Search'.
I'll get the error: 'Plugin::Error Processing FolderList'

See Retrospect.log: https://paste.kodi.tv/iqikixeguz.kodi

**Comment by basrieter** [comment]
> Sorry, late testing again.
> Downloaded: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1550.zip
> 
> Might seems to be something wrong when I using the 'Search'.
> I'll get the error: 'Plugin::Error Processing FolderList'
> 
> See Retrospect.log: https://paste.kodi.tv/iqikixeguz.kodi

Could you create a new issue for that. They moved the search API, so that is indeed an issue, but not related to this one.
