### ISSUE TITLE
NPO genre titels eindigen met " -"

### ISSUE THREAD

**Issue by PhyxionNL** [retrospect-addon/plugin.video.retrospect#1551]
### Describe the bug
Zie afbeelding:
![image](https://user-images.githubusercontent.com/7643972/133842780-d4c6a63c-3645-4f67-829e-18d8dd65eb26.png)

### To Reproduce

1. NPO Start openen
2. Genres
3. Selecteer een genre

### Debuglog
[kodi.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/7188060/kodi.txt)

### Your Environment
Used Operating system: Windows 10, Kodi Matrix, Retrospect 5.4.6. Maar ook op de RPi.

**Comment by basrieter** [comment]
Please download https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/master.zip and install it from zip in Kodi Matrix. It should fix the issue.

**Comment by PhyxionNL** [comment]
Die zip werkt niet niet, maar die pakt het ook van master af. Ik heb zelf het aangepaste bestand even vervangen en nu werkt het weer goed, bedankt 🎉

**Comment by basrieter** [comment]
Verkeerde URL idd: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1551.zip

Kennelijk een issue van Github, want de download URL van https://github.com/retrospect-addon/plugin.video.retrospect/tree/bug-1551 wijst naar de master branch.
