### ISSUE TITLE
NPO sortering op datum is stuk

### ISSUE THREAD

**Issue by PhyxionNL** [retrospect-addon/plugin.video.retrospect#1552]
### Describe the bug
Gesorteerd op datum descending:
Pagina 1 bovenaan:
![image](https://user-images.githubusercontent.com/7643972/133843190-c607520e-c6f9-4a4c-8974-3fb9b7dd4a57.png)
Pagina 2 onderaan:
![image](https://user-images.githubusercontent.com/7643972/133843264-7b4556a2-2834-4cf9-8ded-84b6b90f5e2c.png)

Pagina 2 bovenaan:
![image](https://user-images.githubusercontent.com/7643972/133843291-9750a9f4-3dda-49fd-8c8c-5c22d276bf23.png)
Pagina 2 onderaan:
![image](https://user-images.githubusercontent.com/7643972/133843316-8a5fc098-903f-4414-96f7-7be7d7ba2b15.png)

Om nu naar de laatste aflevering te gaan (van 16-09) moet je 3 pagina's doorlopen via "More pages".

### To Reproduce
1. Open Keuringsdienst van Waarde in NPO en sorteer op aflopende datum.

### Debuglog
[kodi.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/7188078/kodi.txt)

### Your Environment

Used Operating system: Windows 10, Kodi Matrix, Retrospect 5.4.6. Maar ook op de RPi.

**Comment by basrieter** [comment]
Wat bedoel je met "Boven" en "Onder"?

**Comment by PhyxionNL** [comment]
Aan de bovenkant van de lijst/pagina en aan de onderkant 🙂 Had bovenaan en onderaan moeten zijn 👀

**Comment by basrieter** [comment]
En hoe zit het met andere programma's?

**Comment by PhyxionNL** [comment]
Met het Mes op Tafel heeft hetzelfde probleem.

**Comment by basrieter** [comment]
Gevonden: het aantal items per page is terug gebracht naar 100, waardoor niet meer de hele lijst wordt opgehaald. Ik ga kijken hoe ik dat ga fixen. Heb in de API nog niet gevonden hoe ik kan sorteren zodat de eerste 100 results de meest recente zijn.

**Comment by basrieter** [comment]
Kan je https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1552.zip downloaden en installeren? Wat ik nu doe is tot 500 items ophalen in meerdere calls. Dat duurt wel iets langer, maar lost het wel op. 

Ze worden 10 uur gecached (als je dat aan hebt staan in Retrospect, wat default zou moeten zijn), dus het zou enkel de eerste listing per show impact hebben.  

Let wel even op: Deze code bevat **niet** de fix voor #1551 omdat het een andere branche is.

**Comment by PhyxionNL** [comment]
Ik zal het zo even proberen. Ik zat ook al even op de NPO site rond te kijken maar volgens mij is er inderdaad geen mogelijkheid om te sorteren op datum. Je hebt nu max 5 pagina's zo te zien, maar het totaal aantal items wordt bij het resultaat ook teruggegeven in "total", dus dan zou dat misschien ook gebruikt kunnen worden.

**Comment by basrieter** [comment]
> Ik zal het zo even proberen. Ik zat ook al even op de NPO site rond te kijken maar volgens mij is er inderdaad geen mogelijkheid om te sorteren op datum. Je hebt nu max 5 pagina's zo te zien, maar het totaal aantal items wordt bij het resultaat ook teruggegeven in "total", dus dan zou dat misschien ook gebruikt kunnen worden.

Ik doe het nu anders: ik laad maximaal 5 pages van 100 items (was eerst dus 1 page van 500) en daarna krijg je een "More Pages" item voor de volgende 5x100 pagina's. Er zijn maar zo weinig programma's met 500+ afleveringen, dat nagenoeg alles nu gewoon zo moet laden. Ik zou ook bijv. 10x100 pagina's kunnen doen, maar op tragere systemen is dat wellicht niet zo leuk.

**Comment by PhyxionNL** [comment]
Er zijn inderdaad maar heel weinig boven de 500. KvW zit er wel tegenaan al met zo'n 400 🙂 Ik kan die standaard sortering van NPO ook niet helemaal volgen; het zou handiger zijn dat het gewoon standaard per datum is. Maar bedankt voor de fix 👍
