### ISSUE TITLE
Vier.be (and vijf/zes) are not listing

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#1553]
### Describe the bug

Vier.be (and vijf/zes) are not listing their main listings due to API changes.

## Expected Behavior

The mainlist should show.

### Your Environment
Used Operating system:

 - [x] Android
 - [x] iOS
 - [x] Linux
 - [x] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [x] Windows UWP

Used versions:
- Kodi version: Matrix
- Retrospect version: master

**Comment by mtvw** [comment]
I found a problem with this fix:
https://github.com/retrospect-addon/plugin.video.retrospect/commit/ef024e81bb5c9b21bfeeda75d89c3b20d567182a#r56842199

"vijf" is showing the same listing as "zes" at the moment, probably a copypaste error :)

**Comment by basrieter** [comment]
Lol, most likely! Let me fix that.

**Comment by basrieter** [comment]
Please see if https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1553.zip fixes the issue

**Comment by mtvw** [comment]
Hi Bas,

I can't really find a way to install that zip on my libreELEC (I get an error about an uncompatible version).
As a test I updated the file manually (channels/channel.be/vier/chn_vier.py) and rebooted.

This fixes the issue for me!
Thanks a lot!
