### ISSUE TITLE
TV4 Play is not listing the mainlist

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#1554]
### Your Environment
Used Operating system:

 - [x] Android
 - [x] iOS
 - [x] Linux
 - [x] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [x] Windows UWP

Used versions:
- Kodi version: Matrix
- Retrospect version: master

**Comment by matsarv** [comment]
I tested with the changes you made, and now the TV shows folder is working again, nice!

Found two other errors:
- Folder 'Currently playing' says (process_folder_list returned 0 items)
- Folder 'Upptäck TV4 Play' folder says (process_folder_list returned 0 items) 

If you look at the web site, the 'Upptäck TV4 Play'  it is acctually the same as from the dropdown menu  under the 'Kategorier' and as this content is already under 'Categories' folder perhaps it should not be displayed? Maybe the best is to skip the 'Upptäck TV4 Play' folder in the root folders.

**Comment by basrieter** [comment]
> I tested with the changes you made, and now the TV shows folder is working again, nice!
> 
> Found two other errors:
> 
> * Folder 'Currently playing' says (process_folder_list returned 0 items)
> * Folder 'Upptäck TV4 Play' folder says (process_folder_list returned 0 items)
> 
> If you look at the web site, the 'Upptäck TV4 Play' it is acctually the same as from the dropdown menu under the 'Kategorier' and as this content is already under 'Categories' folder perhaps it should not be displayed? Maybe the best is to skip the 'Upptäck TV4 Play' folder in the root folders.

Thanks for checking. The "Currently Playing" is something that seems to be unstable on their end. Where can I find "Upptäck TV4 Play"?

**Comment by matsarv** [comment]
I missed a change in 'def create_api_videopanel_type):

```
if not item.items:
            return None
```

now it's gone from the root folder. Sorry.

I use 'Currently playing' several times every day, so this I will miss.

**Comment by basrieter** [comment]
> I missed a change in 'def create_api_videopanel_type):
> 
> ```
> if not item.items:
>             return None
> ```
> 
> now it's gone from the root folder. Sorry.
> 
> I use 'Currently playing' several times every day, so this I will miss.

You can always downoad the branch and install it to get the fix: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1554.zip
