### ISSUE TITLE
UR Play search does not list items

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1555]
### Describe the bug

UR Play search does not list items

## Expected Behavior

It should list item

### Debuglog

The **debug** retrospect.log can be found here: https://paste.kodi.tv/iqikixeguz.kodi

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.1
- Retrospect version: 5.4.6

**Comment by basrieter** [comment]
Please try: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1555.zip and install it via Zip from Kodi Matrix.

**Comment by matsarv** [comment]
Now the search is working again. Nice quickfix.

**Comment by basrieter** [comment]
Thanks!
