### ISSUE TITLE
Discovery+, cant retrieve program list

### ISSUE THREAD

**Issue by orfeous1** [retrospect-addon/plugin.video.retrospect#1559]
Attaching logs

[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/7205913/retrospect.log)
[kodi.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/7205914/kodi.log)

Using website until fixed.

**Comment by orfeous1** [comment]
Today it works! So i will close the issue!'
Dont know what fixed it. Maybe something on Discovery+/Kanal5 side.

**Comment by basrieter** [comment]
> Today it works! So i will close the issue!'
> Dont know what fixed it. Maybe something on Discovery+/Kanal5 side.

Yes, perhaps een issue in their API. There was an image missing.

**Comment by Snaah** [comment]
@orfeous1 Are you able to watch anything? Otherwise I'm thinking the listings of programs isn't of any use. :)

**Comment by orfeous1** [comment]
Yes, everything works as it should for now.

**Comment by Snaah** [comment]
So issue [#1475](https://github.com/retrospect-addon/plugin.video.retrospect/issues/1475) is invalid then?

I've tried with several different Kodi installations and can't login at all. Are you logged in on the web page simultaneously? Using a dedicated login for Retrospect?  Premium subscriber?

**Comment by orfeous1** [comment]
It has been working for me for a long time.
Not logged in on the web, not a paying account, only the free.
Might be an issue on your side.. dont know if others have the issue as well.

**Comment by Snaah** [comment]
This is strange. Many people are experiencing they can't login, as evidenced by  RS issue #1475 and the cookie workaround solutions made for the Discovery+ plugin and SVT-d. Seems you're lucky. :) 

@basrieter Do you know why this is?

**Comment by basrieter** [comment]
I have no clue. The only thing I don't feel like doing the cookie thing.
