### ISSUE TITLE
Possible to add videoportal.sf.tv?

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#156]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/156) by Anonymous.**

----------------------------------------

Not an issue, but an enhancement request  
  
----  
Original item http://code.google.com/p/xot-uzg/issues/detail?id=156

**Comment by dagwieers** [comment]
Should this not be labeled "channel"?

**Comment by Snaah** [comment]
Isn't SRF.ch already in Retrospect? Close issue?
