### ISSUE TITLE
Omroep Gelderland catchup-TV problem

### ISSUE THREAD

**Issue by chakubie** [retrospect-addon/plugin.video.retrospect#1561]
### Describe the bug

No recent programs omroep Gelderland (last date: 28-07-2021)

## Expected Behavior

Being able to watch recent programs 

## Actual Behavior

No recent programs omroep Gelderland (last date: 28-07-2021)

### To Reproduce

1. Retrospect
2. Omroep Gelderland
3. GLD Nieuws: last program shown: 28-07-2021  

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x ] Linux
 - [ ] OSX
 - [x ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:19.1
- Retrospect version:5.4.6.matrix

**Comment by basrieter** [comment]
They seemed to have switched from backend.

**Comment by basrieter** [comment]
Please try this version https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1561.zip and install it via "Install from zip"

**Comment by chakubie** [comment]
Thank you sincerely for your fast action!
I installed your zip and the last news broadcast from yesterday(28-09) is playing now.
All the other programs are also listed now, but none of them are playing, including the ones from and before 28-07-2021(they did play with the original zip...)
I'm referring to the news broadcasts (GLD Nieuws). Most other streams seem to be working...

**Comment by basrieter** [comment]
Odd, let me check that.

**Comment by basrieter** [comment]
Ok, please try again. Redownload, reinstall and retry :)

**Comment by chakubie** [comment]
This time everything works, thanks!

Verzonden met ProtonMail Mobile

-------- Oorspronkelijk bericht --------
Aan 29 sep. 2021 21:08, Bas Rieter schreef:
