### ISSUE TITLE
Belgium: vier can't play program 

### ISSUE THREAD

**Issue by Vglith** [retrospect-addon/plugin.video.retrospect#1567]
When I try to login on channel vier and I want to play a program I get an error that it can't be played. 

I've uploaded my log file:
https://paste.kodi.tv/dolahobuto

I have the following hardware: raspberryPi 3 (armv7 rev 4 processor) 
It runs on Osmc kodi matrix

Retrospect log:
https://paste.kodi.tv/eluboromap

**Comment by basrieter** [comment]
Please attach a full debug Retrospect.log, not just the kodi log.

**Comment by Vglith** [comment]
Here we go:

https://paste.kodi.tv/eluboromap

**Comment by basrieter** [comment]
The error from Vier is: "Cannot start authentication challenge: User does not exist." 

Are you  sure your login is oK?

**Comment by Vglith** [comment]
Unfortunately yes. I literally copy paste the login and password out of my password manager. On the website these credentials work.. 😒

**Comment by basrieter** [comment]
Can you check the Retrospect settings: `userdata/addon_data/plugin.video.retrospect/settings.xml` and see what value is in the setting `<setting id="viervijfzes_username">....username......</setting>`

**Comment by Vglith** [comment]
Oh... So I opened the xml file and discovered that my email address was written with a capital letter, while it should not be. I changed it in the xml myself and... It works. So it was my email that blocked everything afterall. A casessensitive error...

Thx for the support and directing me in the correct way!
