### ISSUE TITLE
Cannot install 5.4.9matrix.1 on Kodi 19.3

### ISSUE THREAD

**Issue by Rvhalewyn** [retrospect-addon/plugin.video.retrospect#1573]
### Describe the bug

>Get error when trying to install. Not compatible because of Python 2.26.0

## Expected Behavior
Should install, as it's the latest Matrix version

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.3
- Retrospect version: 5.4.9matrix1

**Comment by basrieter** [comment]
Are you installing it via the Kodi Repository? Because it seems like you are installing the Kodi Leia version in Matrix.

**Comment by Rvhalewyn** [comment]
First I copied everything from my former set (Leia) in order not to lose my settings, afterwards I installed the new matrix version from the repository.
Perhaps this was a mistake. Should I delete the add-on completely and then reinstall and manually set up? 
Per

**Comment by basrieter** [comment]
Just delete the full add-on, but keep the add-on settings. The install from the Kodi repository.

**Comment by Rvhalewyn** [comment]
Thanks, I'll try this tomorrow and let you know.

**Comment by Rvhalewyn** [comment]
It worked, thanks!
NPO working perfectly with my plus account.
Tried BBC iPlayer. With OpenVpn Connect-app on my Nvidia on a British server and IPv4-only tunnel.
Get no play error on every entry, live and VOD.
Would like to send you the Retrospect log, but can't copy it.

**Comment by basrieter** [comment]
> It worked, thanks! NPO working perfectly with my plus account. Tried BBC iPlayer. With OpenVpn Connect-app on my Nvidia on a British server and IPv4-only tunnel. Get no play error on every entry, live and VOD. Would like to send you the Retrospect log, but can't copy it.

Great to hear it installed. You can upload a logfile via the built-in feature of Retrospect. Switch to debug logging, reproduce the error, and then upload it via the Retrospect settings. Then post the link here.

**Comment by Rvhalewyn** [comment]
Logfile https://paste.kodi.tv/gumiliyuna

**Comment by basrieter** [comment]
Are you inside the UK?

**Comment by Rvhalewyn** [comment]
No, but I used a British VPN server.
