### ISSUE TITLE
iTunes Movie Trailers (AMT) don't show any list of trailers

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1575]
### Describe the bug

iTunes Movie Trailers (AMT) don't show any list of trailers

## Expected Behavior

The iTunes Movie Trailers (AMT) to show the list of trailers

## Actual Behavior

Got: Error Processing FolderList

## Possible Fix

Just for my test, remarked the actors data:
```
        #actors_data = result_set["actors"][:]
        #item.set_info_label("cast", actors_data)
```
Now it show the list of trailers and trailers are working

### To Reproduce

1.  Start iTunes Movie Trailers

### Debuglog

The **debug** retrospect.log can be found here: https://paste.kodi.tv/nufaqoquyi.kodi

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.3
- Retrospect version: 5.4.9

**Comment by basrieter** [comment]
Let me check this.

**Comment by basrieter** [comment]
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1575.zip and install from zip in Kodi Matrix.

**Comment by matsarv** [comment]
Problem fixed. Now it's running ok and the Cast is in the trailers info. Good  work.
