### ISSUE TITLE
NPO programma titel ontbreekt

### ISSUE THREAD

**Issue by PhyxionNL** [retrospect-addon/plugin.video.retrospect#1577]
### Describe the bug
In Kodi, wanneer je de aflevering pauzeert, ontbreekt de programma naam; er staat er alleen " (2021)" (inclusief spatie).
Het duidelijkste is een screenshot:
![image](https://user-images.githubusercontent.com/7643972/143718452-4ded7fad-1afc-41bf-b140-128a5e902a18.png)

### To Reproduce
1. Open NPO Start.
2. TV Shows (A-Z).
3. Titles with 'P'.
4. Per Seconde Wijzer.
5. Open de nieuwste aflevering (28-10-2021).

### Debuglog

The **debug** retrospect.log can be found here:
[retrospect debug log.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/7612264/retrospect.debug.log.txt)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18 en 19.
- Retrospect version: laatste.

**Comment by basrieter** [comment]
Can you try https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1577.zip in Kodi Matrix?

**Comment by PhyxionNL** [comment]
Super, werkt prima 👍

**Comment by basrieter** [comment]
Ik ga hem nog wat tweaken n.a.v. #1574
