### ISSUE TITLE
SE SVT Play: Fix item name for series listing due to changes

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1579]
### Describe the bug

Fix item name for series listing due to changes

## Expected Behavior

Only show episode name after new "season"x"episode"

## Actual Behavior

Shows a mix of old and new season/episode

## Possible Fix

Change the following in
    def create_api_episode_type(self, result_set, add_parent_title=False):

Replace from Line 678:
```
                item.set_season_info(episode_info[1], episode_info[4])
                item.name = "s{:02}e{:02} - {}".format(
                    int(episode_info[1]),
                    int(episode_info[4]),
                    result_set.get("nameRaw", item.name) or item.name)
```

With:
```
                item.set_season_info(episode_info[1], episode_info[4])
                item.name = result_set.get("nameRaw", item.name) or item.name
```

Is it possible to get the "tvshow_title" from the function "def fetch_program_api_data(self, data):" that is in the json_data?

With - if tvshow_title:
```
                tv_show_title = ?????????
                item.set_season_info(episode_info[1], episode_info[4], tv_show_title)
                item.name = result_set.get("nameRaw", item.name) or item.name
                item.description = "[B]{}[/B][CR][CR]{}".format(tv_show_title, result_set.get("longDescription"))
```

### To Reproduce

1. SVT Play
2. Categories
3. Serier
4. Atlantic crossing

### Debuglog

The **debug** retrospect.log can be found here:  N/A

### Screenshots 

Before:

Listing
![1a](https://user-images.githubusercontent.com/46671821/143934055-91afd7f0-cfad-43ea-ac65-5736b1ace246.png)

OSD
![2a](https://user-images.githubusercontent.com/46671821/143934089-c035f3fc-8ac5-4960-be87-9df89d0b5824.png)

After:

Listing
![1b](https://user-images.githubusercontent.com/46671821/143934331-b6d8734e-a9dd-4acc-9188-dd43c9a98e68.png)

OSD
![2b](https://user-images.githubusercontent.com/46671821/143934353-ba430ee8-3476-42de-9a93-17b57a92fbf0.png)

OSD if it's possible to get "tvshow_title"
![2c](https://user-images.githubusercontent.com/46671821/143934557-dd231831-2738-4023-b7ca-94d23346771e.png)

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.3
- Retrospect version: 5.4.9 + latest changes

**Comment by basrieter** [comment]
Please create a pull request with these changes.

**Comment by matsarv** [comment]
Never done that. Have to read the github document on this.

**Comment by basrieter** [comment]
Closed with #1580

**Comment by basrieter** [comment]
@matsarv Could you try https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1590.zip and see if it makes sense? 

I changed the default sorting a bit: Kodi will now only default to "sort by episode" if **all** playable items have episodes. That prevents mixed lists of episodes and non-episodes. If all items have season/episode information, it makes sense to sort by them automatically.

**Comment by matsarv** [comment]
Good, I had this on my list. I did some testing. Changed all .EPISODE to .VIDEOS in the chn_svt file except for series with season/episode.

I see a small difference when I tested. I had the title of the top row in the KODI Player OSD. Now you seem to be showing the title in one on the second line (I guess this line is for a subtitle - smaller text)

My change:

![title1](https://user-images.githubusercontent.com/46671821/147132993-1bb82e62-b1fd-46d9-8298-e5229bf2d446.png)

![title2](https://user-images.githubusercontent.com/46671821/147133218-def5d925-ee1f-4c84-bbb9-c6ae4afb7bfc.png)


Your change:

![subtitle1](https://user-images.githubusercontent.com/46671821/147133040-ccefef5f-227c-46c2-8b8f-f5b98729d93c.png)

![subtitle2](https://user-images.githubusercontent.com/46671821/147133235-4f17d569-5356-4f23-81a9-f4ed681676cc.png)


It's a small detail, but I think it looks better to use the first line (as it is for Series).

**Comment by matsarv** [comment]
Second,
I can not select Viewtype for the Categories and Genres/tags folders.

I did the following changes in chn_svt file:


I did the following changes in chn_svt file in:

`    def add_live_items_and_genres(self, data):`


Change Line 216:
from
`        genre_item = FolderItem(genre_tags, genre_url, content_type=contenttype.FILES)`
to
`        genre_item = FolderItem(genre_tags, genre_url, content_type=contenttype.VIDEOS)`


Change Line 294:
from
`        new_item = FolderItem(category_title, "https://www.svtplay.se/genre", content_type=contenttype.FILES)`
to
`        new_item = FolderItem(category_title, "https://www.svtplay.se/genre", content_type=contenttype.VIDEOS)`


### Before:
![View-before](https://user-images.githubusercontent.com/46671821/147134807-f9b969af-f768-46a0-90ac-3b9ae61884a8.png)

### After:
![View-after](https://user-images.githubusercontent.com/46671821/147134813-fbbcc71c-8459-4f99-8d9e-7d26dcf4ad86.png)

**Comment by basrieter** [comment]
> 

You will need to tell me where to find this.

**Comment by basrieter** [comment]
The categorie/tags change is here: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1579.zip

The other thing you will need to point me in how to find those folders/shows you are screenshotted.

**Comment by matsarv** [comment]
When I tested this, I reasoned that all TV shows would use mediatype.VIDEO except for Series that would have mediatype.EPISODE

These are changes I made in chn_svt.py:

Change line 592, 687, 739, 912:
(4 places)

from
`item.media_type = mediatype.EPISODE`
to
`item.media_type = mediatype.VIDEO`



Change line 651:
(just before set_season_info)

from
`item.set_season_info(episode_info[1], episode_info[4])`
to
```
item.media_type = mediatype.EPISODE
item.set_season_info(episode_info[1], episode_info[4])
```

**Comment by basrieter** [comment]
I first want to know WHERE you see the header behaviour? I want to verify myself. The thing is that these are EPISODEs, so I will not change them to VIDEO. But there might be another issue. So please tell me exactly how to get to where you create the screenshot.

**Comment by matsarv** [comment]
Select SVT Play
Select Search
Type blybarnen (this could be seen from the World)

Click with the mouse on the player.
![image](https://user-images.githubusercontent.com/46671821/147158419-632ca02f-5d9f-4a98-b93a-925f198d5b3c.png)

Did it work for you?

**Comment by basrieter** [comment]
Ok, so that is because you search and then you don't have a parent item AND that this items is a "single" item. So let me fix this for the 'Single' items. Those are the ones without any TV show related.

**Comment by basrieter** [comment]
Try https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1579.zip again.

**Comment by matsarv** [comment]
Works OK, some are now changed. The "items" that is going via "def create_api_single_type" is now changed.

I have tested the changes I proposed for some time. Only the TV shows that have the "item.set_season_info(season,episode)" will need to use EPISODE. Even is a episode ends up i Last Chance or Recent a.s.o. then they will show up with original name and then will/could be treated as a VIDEO.

This is not a stopper, you'll have the last say!

**Comment by matsarv** [comment]
Tested a little bit more:
The change to "create_api_single_type" works well.
The only thing that can also be changed is in "create_channel_item" on line 912: Change EPISODE to VIDEO.
Each of the five channel act as a single video stream.

**Comment by matsarv** [comment]
chn_tv4se.py

### First:

remark (or remove) line 470

from:
`        item.media_type = mediatype.EPISODE`
to:
`        #item.media_type = mediatype.EPISODE`



Change line 441-442:

from:
```
        if is_episodic and not is_live:
            item.set_season_info(season, episode)
```
to:
```
        if is_episodic and not is_live:
            item.media_type = mediatype.EPISODE
            item.set_season_info(season, episode)
        else:
            item.media_type = mediatype.VIDEO 
```

### Second:

I can not select Viewtype for the extras folders.

Change line 661:

from:
item = FolderItem(title, url, content_type=contenttype.FILES)
to:
item = FolderItem(title, url, content_type=contenttype.VIDEOS)

**Comment by matsarv** [comment]
chn_viafree.py

change line 294:

from
`        item.media_type = mediatype.EPISODE`
to
`        item.media_type = mediatype.VIDEO`




change line 538-540:

from
```
        item.media_type = mediatype.EPISODE
        if episode > 0 and season > 0:
            item.set_season_info(season, episode)
```
to
```
        if episode > 0 and season > 0:
            item.media_type = mediatype.EPISODE
            item.set_season_info(season, episode)
        else:
            item.media_type = mediatype.VIDEO
```

**Comment by basrieter** [comment]
We should not just change all EPISODEs into VIDOE's. Even though a episode number is missing, it still is an episode of a TV show.  I don't understand what this achieves?

**Comment by matsarv** [comment]
It was for single TV programs without any season/episode (simple items) that I have been able to find, but now I found some that use both lines och kanske finns det vissa med episode info.

Maybe it's better to skip it for now for tv4se and viafree. I do not know which is the best look, both works.

### chn_tv4se.py
Before change:
![image](https://user-images.githubusercontent.com/46671821/147224715-7233011e-9eb9-456d-af48-ceb96376144d.png)

![image](https://user-images.githubusercontent.com/46671821/147227115-75086d4e-cbf5-4942-86d8-5449f308581f.png)

After change:
![image](https://user-images.githubusercontent.com/46671821/147224732-cf258704-e52c-47d6-8e83-dd0b87d5c55c.png)

![image](https://user-images.githubusercontent.com/46671821/147227329-2b62b115-17d4-4755-81af-1d5cc8e67a60.png)

The TV shows work so you can skip these changes, you decide.

**Comment by basrieter** [comment]
I will leave it for now.
