### ISSUE TITLE
cant watch episodes and movies on viafree

### ISSUE THREAD

**Issue by cabban** [retrospect-addon/plugin.video.retrospect#1581]
### Describe the bug
cant retrieve the list i hope you can fix it or make so we can login cheers

## Possible Fix

make login in setttings to viafree 

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.3
- Retrospect version: latest

**Comment by basrieter** [comment]
Please attach a DEBUG retrospect.log.

**Comment by Sopor** [comment]
It could be a Widevine issue. Have you updated it recently?

I'm running Widevine CDM 4.10.2209.0 in Windows and i can watch Viafree. I think the latest version is 4.10.2252.5, though.
