### ISSUE TITLE
SVTplay (sweden) mainpage tips and categories

### ISSUE THREAD

**Issue by datamaskinen** [retrospect-addon/plugin.video.retrospect#1587]
### Is your feature request related to a problem? Please describe

To make the SVTplay in retrospect more usable and more like the play website we should add the categories that the www.svtplay.se has on its main site.

This categories change from time to time so a script that runs when updating the list could as well update the categories.

### Describe the solution you'd like

curl -s "https://www.svtplay.se" --list-only

**Comment by basrieter** [comment]
Doesn't SVT already have categories

![Screenshot_20211215-122352.jpg](https://user-images.githubusercontent.com/1310443/146178002-944972df-a2ba-45cd-acf7-58b5e0717e78.jpg)

**Comment by Snaah** [comment]
Yes, it does. @datamaskinen Are there any categories missing?

**Comment by datamaskinen** [comment]
latest news shows only the latest news ....

**Comment by datamaskinen** [comment]
yea no i know .... i am trying to think of what i mean :)...

But like ... in the start main page of svtplay they show like the last aired movies ant series antd so on .... would be nice if retrospect would have a similar main list .... but the more i think about it the harder it feels to find a good way to do it .... they probably change the listings of videos there often... ähhhh i dont know ....

**Comment by basrieter** [comment]
I had that in the past, but they broke that. Perhaps I can verify if it could be added again. But please describe it a bit better. Now you talk about categories. Name what parts of the site you miss in Retrospect (and perhaps change the title of the issue).

**Comment by datamaskinen** [comment]
You have all the categories there already it is just a bit un user friendly to find the ones that is the popular and last aired ones now...

So in svtplay main page they have the listed ... "Populärt" , "Vinter serier" , "Nytt på play" , "Nyheter"

**Comment by basrieter** [comment]
Ok. "Populärt" => Most watched in Retrospect. The other I can check.

**Comment by basrieter** [comment]
What would be a good generic translation for "Nytt på play"? So one that I can use for more channels?

**Comment by basrieter** [comment]
I could make it "New on [channelname]".

**Comment by matsarv** [comment]
Maybe something like this?

EN: Interesting on Play
SE: Intressant på Play

One of the folders in "Interesting on Play" will probably be "New on Play".

![1](https://user-images.githubusercontent.com/46671821/148700254-c131bdb2-246f-44d0-b7f7-18e47402699e.png)

**Comment by datamaskinen** [comment]
Yeah nice one

**Comment by basrieter** [comment]
Is it "Interesting" or "New"? Google Translate suggests "New"?

**Comment by basrieter** [comment]
You can install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/feature-1587.zip in Kodi Matrix via the "install from zip" and see how it works. You might need to restart Kodi, because I had to add a translation string.

**Comment by matsarv** [comment]
My mistake, I tested above and I see you have added the show listed in "Nytt på Play" from the start page.
Then they should definitely be changed EN: "New on Play" SE: "Nytt på Play"
Sorry for any inconvenience of changing the code back.

---------------------------------

I thought you found a way to get all the new dynamic listings used on the homepage  from the API and not just one.

Below are some of the list used this weekend.

```
Vinterns serier  -  https://www.svtplay.se/lista/vinterns-serier-K1X14YN
Inspiration & livsstil  -  https://www.svtplay.se/lista/inspiration-och-livsstil-jLZRDzy
Nytt på Play  -  https://www.svtplay.se/lista/nytt-pa-play-8vyaD1x
Nyheter  -  https://www.svtplay.se/lista/nyheter-jnD6vny
Filmtips  -  https://www.svtplay.se/lista/filmtips-KyEgXJd
För dig som var ung på 90-talet   -  https://www.svtplay.se/lista/for-dig-som-var-ung-pa-90-talet-e3p1ZpY
För dig som var ung på 80-talet  -  https://www.svtplay.se/lista/for-dig-som-var-ung-pa-80-talet-KM6pGB2
and so on.......
```

I have added a new image above.

I think the initial wish was to get the content in all topics that come from "https: //www.svtplay.se/lista / ......." created as in the pictures I show above. As these different lists are not static, they must be fetched dynamically. 

Anyway, this may not be possible?

**Comment by basrieter** [comment]
Reverted the language change. Are any of those available via the already present Genres/Tags or Categories?

**Comment by matsarv** [comment]
Hi, I do not think so. I can not find anything in either Genre or Categories. They must be generated in some other way.
An example: Yesterday there was a selection "Lördagens livesport": ("Lördagens livesport-KA55JWd" (Saturday's live sports) which is now gone from the homepage.

**Comment by basrieter** [comment]
It won't be possible to get those categories from the website dynamically: I use the SVT Play API and they do not provide such listings as it seems.

**Comment by datamaskinen** [comment]
wow that is perfect .... now it becomes more like using the webpage and it i dont have to first open the web to later search the new stuff in kodi ... thanx a milion

**Comment by datamaskinen** [comment]
The new that you have added (new on play & most viewed) is the ones that was needed so now it is perfect ....

**Comment by basrieter** [comment]
So there are no more items to add?

**Comment by matsarv** [comment]
Not from my side. Everything works well.

**Comment by datamaskinen** [comment]
for me this is great ....
