### ISSUE TITLE
Provide RPC automation (capabilities/documentation)

### ISSUE THREAD

**Issue by joopdo** [retrospect-addon/plugin.video.retrospect#1588]
### Is your feature request related to a problem? Please describe
Thanks for this project, Bas. 
I'm setting up automations of my watching behaviour and found difficulties automating content with JSON-RPC.
Pickler behaviour (not sure what this does yet, but it seems to rotate) invalidates post commands after some time, also it's hard to get started.

For example, right now I'm able to start NPO1 Live steam as follows:
```
curl -X POST -H "content-type:application/json" http://<IP>:8080/jsonrpc -d '{"jsonrpc": "2.0", "method": "Player.Open", "params": {"item": {"file": "plugin://plugin.video.retrospect/?channel=channel.nos.nos2010-uzgjson&action=playvideo&pickle=<longstring>&rnd=36299" }}, "id": 1}'  
```

But in some time, this method will not work any more.

### Describe the solution you'd like
Could you provide pointers or automation documentation on how to programmatically work with Retrospect?

For reference, I found https://github.com/add-ons/plugin.video.vrt.nu/wiki/Automation allows to view a 'latest' show. 

```
{
    "jsonrpc": "2.0",
    "method": "Player.Open",
    "params": {
        "item": {
            "file": "plugin://plugin.video.vrt.nu/play/latest/het-journaal"
        }
    },
    "id": 1
} 
```

Thanks again for creating and maintaining this addon!

**Comment by basrieter** [comment]
That is rather simpel: the GUID are points to index files in the Retrospect user data folder. But those get removed after some time. There is  a work around:  add them to the Kodi Favourites. That should prevent them from being cleaned up.

As for the automation in general: Retrospect support too many channels make them all "automation ready". Very often the url's of streams change over time and even that cannot be solved from Retrospect's point of view. The VRT add-on has a much easier situation: just a single channel.

**Comment by joopdo** [comment]
Thanks for the clear answer and quick reply Bas. Closing issue as my problem is solved with a fixed Pickle with items in Favourites. Much appreciated!

**Comment by basrieter** [comment]
> Thanks for the clear answer and quick reply Bas. Closing issue as my problem is solved with a fixed Pickle with items in Favourites. Much appreciated!

Great!
