### ISSUE TITLE
NPOstart program lists start with the season and episode number

### ISSUE THREAD

**Issue by ErikBrown2** [retrospect-addon/plugin.video.retrospect#1590]
### Describe the bug

NPOstart program lists on their website include a season and episode number. This shows up in Retrospect program lists before the time the program is shown. So for instance a program is shown in the Retrospect program list for today as:
1x01. 00:34 - NPO 2 - De Slapelozen  - Kracht
In my opinion this clutters up very much the list. It would be better if this 1x01 is either not shown or shown after the program name. But not at the start of the line.

## Expected Behavior

The program should be shown as 
00:34 - NPO 2 - De Slapelozen  - Kracht
or as
00:34 - NPO 2 - De Slapelozen  - Kracht 0x01
or maybe better as 
00:34 - NPO 2 - De Slapelozen  - Kracht S01E01

## Actual Behavior

Most programs have now the season and episode number at the start of the program like: 
1x01. 00:34 - NPO 2 - De Slapelozen  - Kracht

## Possible Fix

One of these options:
00:34 - NPO 2 - De Slapelozen  - Kracht
or as
00:34 - NPO 2 - De Slapelozen  - Kracht 0x01
or maybe better as 
00:34 - NPO 2 - De Slapelozen  - Kracht S01E01

### To Reproduce

1. Start Retrospect and select NPOstart
2. Select Recent programs and select for  instance today
3. Notice the shown program list

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/elubifomuc

### Screenshots 

<img width="960" alt="Screenshot 2021-12-21 201818" src="https://user-images.githubusercontent.com/32511867/146988191-2384c872-6267-4437-814b-0ccaa495ff1e.png">

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.3.0
- Retrospect version: 5.4.10+matrix.1

**Comment by basrieter** [comment]
Ok, it is Kodi that shows them in front of the listing, I can't fix that. But I don't think they should be set there. Let me see.

**Comment by basrieter** [comment]
Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1590.zip and see if that fixes it.

**Comment by ErikBrown2** [comment]
The Recent program lists now indeed do not show the season-episode info anymore.

<img width="960" alt="Screenshot 2021-12-22 022241" src="https://user-images.githubusercontent.com/32511867/147019488-4a27e399-3c83-456d-b1bf-aed81ff67a6f.png">

The TV shows (A-Z) and TV shows (Full list) listings still have the season-episode info at the beginning of the line but that is fine since there is no date or time on the line.

<img width="960" alt="Screenshot 2021-12-22 022617" src="https://user-images.githubusercontent.com/32511867/147019799-048173da-f5fd-4d03-b465-f53bfac2b4e0.png">

Thank you very much for the very quick fix!

**Comment by basrieter** [comment]
I changed it a bit: Kodi will now only default to "sort by episode" if all playable items have episodes. That prevents these mixed lists of episodes and non-episodes as you posted in your last screenshot. If all items have season/episode information, it makes sense to sort by them. 

You can retry by downloading https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1590.zip again and reinstalling.

**Comment by ErikBrown2** [comment]
Very nice. Now it behaves indeed as you described. The following screenshot shows the listing of the program with the mix of episodes and non-episodes:

<img width="960" alt="Screenshot 2021-12-22 181640" src="https://user-images.githubusercontent.com/32511867/147132412-f6658b26-9cc7-401a-8dfb-463ae2cdb848.png">

The following shows a listing of a program with only episodes:

<img width="960" alt="Screenshot 2021-12-22 182236" src="https://user-images.githubusercontent.com/32511867/147132443-c1461031-a6d3-42d7-8779-7a36413bfd35.png">

Thanks again.
