### ISSUE TITLE
Export playlist  or constant playlist url

### ISSUE THREAD

**Issue by DJJo14** [retrospect-addon/plugin.video.retrospect#1591]
### Is your feature request related to a problem? Please describe
I want to import NPO or other live streams to my pvr.

### Describe the solution you'd like
With the PVR  Iptvsimple you can import a m3u. I know a lot of people has requested it. With only thing I want is a (simple) url that I'm can import. 

In the documentation of the [pvr.iptvsimple](https://github.com/kodi-pvr/pvr.iptvsimple) says it support the url starting with "plugin://"

I did a test with the current file:
```
#EXTM3U
#EXTINF:20,Channel test
plugin://plugin.video.retrospect/?action=playvideo&pickle=<alotofblablbla>--<morebla>&channel=channel.nos.nos2010-uzgjson&rnd=12400
```
and this is currently working, but I do not know if the url or the <alotofblablbla> change over time? I took the url from the kodi log. I tested a non Widevine url, but that is al I want the moment. 

The thing I want is a URL that is simple and constant like:
`plugin://plugin.video.retrospect/?action=playvideo&channel=channel.nos.nos2010-uzgjson&name=NPO_3fm_webcam`

That way you can just supply one m3u for everyone. Maybe this is already the case, than I do not know how to find it in the documentation.

### Describe alternatives you've considered
A function that can generate a playlist is also a good option.

### Additional context
Do not bother about epg or the tv guide rewind or any thing like that. Start with this you can always expand.

**Comment by basrieter** [comment]
Bookmark the `plugin://plugin.video.retrospect/?action=playvideo&pickle=<alotofblablbla>--<morebla>&channel=channel.nos.nos2010-uzgjson&rnd=12400` url in Kodi and it will not expire. Or bookmark it in Retrospect and fetch the full url config the folder with the favourites.

**Comment by basrieter** [comment]
What I could do is some how provide you with a full link that contains all the information. That url is however, rather long. So how would I show that?

**Comment by basrieter** [comment]
Perhaps this can be combined with #1588? Would it make sense to let users pick a "shortcut" name for an item?

**Comment by basrieter** [comment]
Ok, so I did an attempt: 

- Please download https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/feature-shortcut.zip
- Install it from zip
- On each folder or video item you can go to: 
  - Retrospect Favourites
  - Add Shortcut
  - Provide a [simple name]
-  Then you can use this url to directly play it: plugin://plugin.video.retrospect/?action=openshortcut&shortcut=[simple name]
  - This also works for the API of Kodi

Let me know what you thing @DJJo14 and @joopdo

**Comment by joopdo** [comment]
Hi @basrieter That's an amazing idea - thanks for letting us try this idea! I was able to Add Shortcuts to episodes (livestreams) and give them a name. Then succesfully start them from API. (e.g. 

`curl -X POST -H "content-type:application/json" http://192.168.x.x:8080/jsonrpc -d '{"jsonrpc": "2.0", "method": "Player.Open", "params": {"item": {"file": "plugin://plugin.video.retrospect/?action=openshortcut&shortcut=nosjournaal"}}, "id": 1}'`

That works like a charm! More convenient then the 'copy from favourites' method.

Question, you wrote _'On each **folder** or video item'_ - Does that mean I can also link to folders? I haven't been able to do so yet. (Tried with NPO and Dumpert) - will try more later.

**Comment by basrieter** [comment]
Great to hear that!

> Question, you wrote 'On each folder or video item' - Does that mean I can also link to folders? I haven't been able to do so yet. (Tried with NPO and Dumpert) - will try more later.

Yyes, it should work but not with `Player.Open` but with `Addons.ExecuteAddon`

**Comment by joopdo** [comment]
Confirmed to work with folders with `Addons.ExecuteAddon`

Now I have moved from shell scripts to HomeAssistant. I can now trigger my Retrospect favourites in various ways. E.g.:
```
method: Addons.ExecuteAddon
addonid: plugin.video.retrospect
params:
  action: openshortcut
  shortcut: nosjournaal

```

This triggers a list with the **_folder_** that I saved in my favourites with that name.

You are a legend! Let me know if you want me to test something else. For now: Happy test user having fun.

**Comment by basrieter** [comment]
@DJJo14  do you have any findings or suggestions with this version?

**Comment by DJJo14** [comment]
I can confirm that it is working. I only had to upgrade to matrix. I imported the following playlist to simple iptv. (including the Widevine channels)

```
#EXTM3U
#EXTINF:-1,NPO1
plugin://plugin.video.retrospect/?action=openshortcut&shortcut=npo1
#EXTINF:-1,NPO2
plugin://plugin.video.retrospect/?action=openshortcut&shortcut=npo2
#EXTINF:-1,NPO1extra
plugin://plugin.video.retrospect/?action=openshortcut&shortcut=npo1extra
```

I only have to remember what i have typed in, the live channels does not come in the favourites list.

**Comment by basrieter** [comment]
Ok, it indeed does not show up as part of the favourite or so. You need to remember the shortcut name you use.

**Comment by DJJo14** [comment]
I found a list in the .kodi/userdata/addondata/plugin.video.retrospect/shortcut folder
For anyone who wants the NPO channels in the PVR:

- Download the latest retrospect (i asume this version comes in the main)
- Go to the NPO live tv channels and test if they work
- do for every one channel [contest menu] "Retrospect favorieten >>" "add shortcut"
- and name all the channels "npo1", "npo2", "npo3", "npo1extra", "npo2extra", "npopn" (poltiek en nieuws), "radio1", "radio2", "3fm", "radio4", "funx"
- Download the [iptv_retrospect.m3u.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/7784691/iptv_retrospect.m3u.txt) and name it "iptv_retrospect.m3u"
- add the "PVR IPTV simple client" to kodi (install addon from repo, add repositoryies, pvr clients, pvr iptv simple client)
- configure iptv simple client (mijn addons, pvr clients, pvr iptv simple client) 
- Set location to "local path"
- and select the "iptv_retrospect.m3u"
- press OK
- and the tv channels are imported to kodi's pvr (only tv)


Note:

- The streams are still supplied by retrospect. It is only the tv channels, the radio channels are possible but when you select the npo live radio 2, you get the webcam. (maybe this can change?, so you can only listen to audio for the main radio channels?)
- I had no icons for the NPO extra's
- The TV guide does not work.

**Comment by ErikBrown2** [comment]
> * iptv_retrospect.m3u

Very nice. What about pasting the file here?

**Comment by basrieter** [comment]
> > * iptv_retrospect.m3u
> 
> Very nice. What about pasting the file here?

It's already attached isn't it?

**Comment by basrieter** [comment]
I will update the readme.md and add this:

D
### Automation of Retrospect
Listing of folders or playing of media can be automated for Retrospect. In order for this to work, you will need to create _shortcuts_ for the folders and/or videos you want to automate. This can be done as follows:

- On each folder or video item you can go to:
  - Retrospect Favourites.
  - Add Shortcut.
  - Provide a `[simple name]`.
  - Remember the `simple name` as you need it later.
- Then you can use this url to directly open or play the shortcut: 
  - `plugin://plugin.video.retrospect/?action=openshortcut&shortcut=[simple name]`
  
Listing a folder can be done by caling the Kodi API `Addons.ExecuteAddon` with the given shortcut url. Media can be played using the `Player.Open` API.

If you were to use the JSON API, this might look like: 

```bash 
curl -X POST -H "content-type:application/json" http://<kodi-ip>:8080/jsonrpc -d '{"jsonrpc": "2.0", "method": "Player.Open", "params": {"item": {"file": "plugin://plugin.video.retrospect/?action=openshortcut&shortcut=<shortcut_name>"}}, "id": 1}'
```

Replace `<shortcut_name>` and `<kodi_ip>` with the correct values. 

---------------------

**Comment by joopdo** [comment]
Nice! Sounds like it will be integrated in main. Agreed that documentation is important!

#### Menu Item:
I'm worried that a user will not understand "add shortcut" menu item otherwise. Not sure what to do about this though...

#### .md Text
Suggested edits for your consideration (tried to mark diff with formatting but failed):
---

### Automation of Retrospect

Listing of folders or playing of media can be automated for Retrospect. In order for this to work, you will need to create _shortcuts_ for the folders and/or videos you want to automate. This can be done as follows:

    * On each folder or video item you can go to:
      
      * Retrospect Favourites.
      * Add Shortcut.
      * Provide a `[simple name]`.
      * Remember the `simple name` as you need it later.

    * Then you can use this url to directly open or play the shortcut:
      
      * `plugin://plugin.video.retrospect/?action=openshortcut&shortcut=[simple name]`


Listing a folder can be done by calling the Kodi API `Addons.ExecuteAddon` with the given shortcut URL. Media can be played using the `Player.Open` API.

If you were to use the Kodi JSON-RPC_API (documented [here](https://kodi.wiki/view/JSON-RPC_API))

1. You could link to a video file with `Player.Open`:
>
```shell
curl -X POST -H "content-type:application/json" http://<kodi-ip>:<_kodi_port_>/jsonrpc -d '{"jsonrpc": "2.0", "method": "Player.Open", "params": {"item": {"file": "plugin://plugin.video.retrospect/?action=openshortcut&shortcut=<shortcut_name>"}}, "id": 1}'
```
2. Or open for example trigger a shortcut to a folder with `Addons.ExecuteAddon`:
```shell
curl -X POST -H "content-type:application/json" http://<kodi-ip>:<_kodi_port_>/jsonrpc -d '{"jsonrpc": "2.0", "method": "Addons.ExecuteAddon", "params": {"addonid": "plugin.video.retrospect","params": {"action": "openshortcut","shortcut": "<shortcut_name>" }}, "id": 1}'**
```

Replace `<shortcut_name>`, `<kodi_ip>` and `<kodi_port>` with the correct values.

**Comment by basrieter** [comment]
It will be in the next official release.

**Comment by joopdo** [comment]
Just an update after three months of use:

1. I set this up and it just works. (programmatically starting NPO1 etc)
2. Previously set shortcuts can't be listed, no worries, just setup a new shortcut.

Example on how to call one from HomeAssistant:
````alias: npo1
sequence:
  - service: kodi.call_method
    data:
      method: Player.Open
      item:
        file: plugin://plugin.video.retrospect/?action=openshortcut&shortcut=npo1
      options:
        resume: true
    target:
      entity_id: media_player.kodi_70d415ed00d772188a29aec030bee5a4
mode: single
icon: mdi:television
````
