### ISSUE TITLE
SE TV4 Play: Not possible to select Viewtype

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1593]
### Describe the bug

It's not possible to select Viewtype for the "extras" folders.

## Expected Behavior

Be able to change Viewtype

## Actual Behavior

Viewtype is missing

## Possible Fix

In chn_tv4se.py change line 661:
from:
`item = FolderItem(title, url, content_type=contenttype.FILES)`
to:
`item = FolderItem(title, url, content_type=contenttype.VIDEOS)`

### To Reproduce

1. Select TV4 Play
2. Select Categories, TV shows or Search
3. Check View options

### Debuglog

The **debug** retrospect.log can be found here: N/A

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.3 / Nexus 20.0 alpha
- Retrospect version: 5.4.10 + latest changes

**Comment by basrieter** [comment]
Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1593.zip and try if it works.

**Comment by matsarv** [comment]
Works perfect. Thanks.
