### ISSUE TITLE
NPO entry vandaag empty

### ISSUE THREAD

**Issue by chakubie** [retrospect-addon/plugin.video.retrospect#1594]
### Describe the bug

From 30-12-2021 the entry vandaag under recent from NPO is empty

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x ] Linux
 - [ ] OSX
 - [x ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.3
- Retrospect version:5.5.0

**Comment by basrieter** [comment]
Seems to be an issue on their side. Let's wait a bit and see if they can fix it.

**Comment by ErikBrown2** [comment]
But it works on their own website.

**Comment by basrieter** [comment]
> But it works on their own website.

Don't compare website and Retrospect. I use their API, the website does not in this case.

**Comment by basrieter** [comment]
```json
{"code":500,"message":"Call to a member function isMCRChannel() on null","request_uri":"https://start-api.npo.nl/epg/2021-12-30?type=tv","request_method":"GET","request_ip":"10.0.58.67"}
```

Is the response. Seems like internal to me. Let's see.

**Comment by basrieter** [comment]
Well, seems like al days work now, except for 30 december. Yesterday the future days were also broken, they seems to be OK now. So it seems to be fixed on their end.

**Comment by chakubie** [comment]
You are right: today all programs are visible again! The ones from 30-12 not, which isn't a big problem: they all can be found in a different way. Thanks again 👍

**Comment by basrieter** [comment]
NP, enjoy Retrospect.
