### ISSUE TITLE
VRT NU doesn't work anymore

### ISSUE THREAD

**Issue by peno64** [retrospect-addon/plugin.video.retrospect#1595]
### Describe the bug

VRT NU doesn't work anymore. For example 'Het  journaal'

## Expected Behavior

When choosing an episode of 'Het journaal' it should play.

## Actual Behavior

It doesn't play but gives a message 'Cannot start playback'

### To Reproduce

1. Retrospect, National, VRT NU, Titles with 'H', Het journaal
2. Choose a recent one ( for example from the day before)
3. The episode doesn't play but gives a message 'Cannot start playback'

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/ehafozirod.kodi

## Additional context or screenshots (if appropriate)

I know that the VRT NU content can also play via the addon VRT NU, but I like to have a backup way in case that addon would not work.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi 4 (LibreElec 10.0.1)
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.3
- Retrospect version: 5.5.0+matrix.1

In fact everything is the latest version and this is a fresh installation of kodi with only the addon Retrospect installed. Also Widevine is installed and login credentials are set correctly. 
It was detected on a save version with also other addons installed where everything else works fine.

**Comment by basrieter** [comment]
Those are GEO locked and can only be viewed from Belgium. So the question is: are you in Belgium?

**Comment by peno64** [comment]
Yes I am from Belgium.

**Comment by basrieter** [comment]
And did you verify your VRT account to be Belgium? This happens if you try to play something from the site?

**Comment by peno64** [comment]
Yes my account is correct. Note that everything is ok with the VRT NU addon with this same account so it must be a retrospect issue.

**Comment by peno64** [comment]
The same episode of "Het journaal" plays without a problem from my browser, with the same account.

**Comment by basrieter** [comment]
So I can verify this a bit later, as I will need to somehow verify my account with a Belgium mobile number

**Comment by basrieter** [comment]
Could you try clearing your cache and cookies via the add-on settings. You can best do this from the main channel listing of Retrospect? 

![image](https://user-images.githubusercontent.com/1310443/148644678-40b9315d-4ac6-4bfa-84e9-cec8e7602d4d.png)

Then see if it works again?

**Comment by peno64** [comment]
I will try it. But I had it also on a complete new installation of kodi and retrospect so it would surprise me.

**Comment by peno64** [comment]
It's the same.
It first asked me to enter the retrospect pin (I guess this was because of a successful clear) and then again the same error.

**Comment by basrieter** [comment]
Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1595.zip and try again.

**Comment by peno64** [comment]
Works great!
Tried it with at least  10 different programs and all work now.
Nive work.
Thank you.
