### ISSUE TITLE
SVTplay links lead to wrong programs

### ISSUE THREAD

**Issue by dobbelina** [retrospect-addon/plugin.video.retrospect#1596]
### Describe the bug

Below two links from my favorites that lead to other programs than in the title.
The documentary about Patrick Swayze leads to a documentary on Tom Cruise.
The link to the movie "Heja Roland!" leads to a movie called "Flickorna"
This is just 2 examples, many other links has the same issue.
```
<favourite name="I am Patrick Swayze - Brittisk dokumentär från 2019 [COLOR aqua]º[/COLOR]" thumb="https://www.svtstatic.se/image/wide/720/30620428/1616567673?quality=70">PlayMedia(&quot;plugin://plugin.video.retrospect/?action=playvideo&amp;pickle=B2125411AFF8FCD138784BE767523A80EF9632A9F8497EC0AA3B2F60F1A62F29--1E0FAEDF18FF0D81D350BB931EC509710876EFC36EFB6596A6257373A1A5673E&amp;channel=channel.se.svt-svt&quot;)</favourite>
    <favourite name="Heja Roland! - Svensk långfilm från 1966 [COLOR aqua]º[/COLOR]" thumb="https://www.svtstatic.se/image/wide/720/33686570/1640260627?quality=70">PlayMedia(&quot;plugin://plugin.video.retrospect/?action=playvideo&amp;pickle=B2125411AFF8FCD138784BE767523A80EF9632A9F8497EC0AA3B2F60F1A62F29--CA63A7D15DD8B1068BC1FCB8F56EB0B80DDB19094A9C2D74079EC6768516655D&amp;channel=channel.se.svt-svt&quot;)</favourite>
```
Correct url for the Patrick Swayze documentary:
https://ed9.cdn.svt.se/d0/se/20211231/ca61fed9-0ad6-4c28-9713-f1aaa7667404/hls-ts-avc.m3u8
Correct url for the "Heja Roland!" movie:
https://ed4.cdn.svt.se/d0/se/20211230/b7ab973a-bbcf-486d-9df2-b95a1da72fdb/hls-ts-avc.m3u8

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.9
- Retrospect version: 5.5.0

**Comment by basrieter** [comment]
Well spotted. This fails because of some changes on the SVT side. Let me fix it.

**Comment by basrieter** [comment]
Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1596.zip for Kodi Matrix and see if this fixes your issue.

**Comment by dobbelina** [comment]
It fixes the issue, thank you for the quick response.
