### ISSUE TITLE
Inloggen+Favorieten NPOPlus werkt niet meer 

### ISSUE THREAD

**Issue by jcjdammers** [retrospect-addon/plugin.video.retrospect#1597]
Ik heb een NPOPlus account, en heb mijn userID+wachtwoord opgegeven in de kanaalinstellingen.
Als ik naar Favorieten ga dan krijg ik een foutmelding en is de lijst leeg.
Ik weet zeker dat dit vorige week nog werkte.
Het lijkt erop dat het inloggen bij NPO niet goed meer gaat.
Op andere devices/apps werkt het wel.

**Comment by basrieter** [comment]
Graag een DEBUG retrospect.log toevoegen zoals de template aangaf.

**Comment by jcjdammers** [comment]
Log-file is verstuurd naar ==> https://paste.kodi.tv/ohaxiwubot

Bedankt voor je hulp.

**Comment by basrieter** [comment]
Zou je https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1597.zip kunnen installeren onder Kodi Matrix en kunnen kijken of het weer werkt? Zo niet, dan graag weer een logje.

**Comment by jcjdammers** [comment]
Ik heb de zip geïnstalleerd en ja nu werkt het weer.
Bedankt.

**Comment by basrieter** [comment]
Ik zal een nieuwe officiële release maken.

**Comment by PhyxionNL** [comment]
> Ik zal een nieuwe officiële release maken.

Super, ik zou dit net ook melden 🎉

**Comment by basrieter** [comment]
For those still experiencing issues after the update or new Retrospect version: clear the cookies and cache via the Retrospect add-on settings.

**Comment by lauris-nl** [comment]
I removed cash and cookies.
I'm on 5.5.12
NPO stil don't work.

**Comment by basrieter** [comment]
See #1672
