### ISSUE TITLE
NPO account problem

### ISSUE THREAD

**Issue by chakubie** [retrospect-addon/plugin.video.retrospect#1599]
### Describe the bug

While being logged in (NPO) behaviour is like being logged out: low resolution and NPO favourites empty, so not able to see programs that need a subscription. On Android app everything functions..
About same issue as bug 1597.., I installed bug-1597.zip which didn't help..
Debug log made after installing this zip..

### To Reproduce

1. 
2.
3.

### Debuglog
 
https://paste.kodi.tv/heditusogu

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.3
- Retrospect version: 5.5.1

**Comment by basrieter** [comment]
Please search existing issues before posting new ones. Issue #1597 was even pinned at the top of the issue list. It was fixed yesterday and released this evening.

**Comment by chakubie** [comment]
You're right I saw this to late.., still on my device the problem is not sol after installing the zip 1597

**Comment by basrieter** [comment]
You log does not even show logging you in. Please try clearing the cache and cookies from the main Retrospect channel listing using the add-on settings:

![image](https://user-images.githubusercontent.com/1310443/149237774-8e814ba7-f070-4da9-8a3a-127502c0cbf7.png)

that will force a re-login.

**Comment by chakubie** [comment]
Now it works (after clearing the cache), sorry for the inconvenience! Next time I will look better!

Charles

-------- Oorspronkelijk bericht --------
Aan 13 jan. 2022 00:12, Bas Rieter schreef:

**Comment by basrieter** [comment]
Great!
