### ISSUE TITLE
The channels on npo start and rtl are not getting sufficient bandwidth

### ISSUE THREAD

**Issue by diekshouse** [retrospect-addon/plugin.video.retrospect#1601]
### Describe the bug

The channnels on NPO start and RTL are playing, but only interrupted.

## Expected Behavior

Continious playing video.

## Actual Behavior

A video stream plays for a few seconds and stops. A percentage counter is displayed for some 10 seconds. The video plays again for a few seconds etc. It looks like for some reason the bandwith is limited. Other channels work OK.

## Possible Fix

Maybe this is the case after update 5.5.2, I am not sure.

### To Reproduce

1. Start retrospect
2. Go to National - NPO start
3. Start a channel

### Debuglog

The **debug** retrospect.log can be found here:  https://paste.kodi.tv/evikoxixut

### Your Environment
Used Operating system: 

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.9
- Retrospect version:  5.5.2

**Comment by basrieter** [comment]
This is not an Retrospect issue but an issue with InputStream Adaptive: https://github.com/xbmc/inputstream.adaptive/issues/877

**Comment by diekshouse** [comment]
Hi,
I can confirm, installing widevine 4.10.2252.5 solved the problem.
Thanks very much.

**Comment by CharlieTemplar** [comment]
> 4.10.2252.5

Where did you find this?  Do you  have a url for raspi3/arm?

**Comment by Derkades** [comment]
> > 4.10.2252.5
> 
> Where did you find this? Do you have a url for raspi3/arm?

The instructions in https://github.com/xbmc/inputstream.adaptive/issues/877#issuecomment-1021585184 worked for me
