### ISSUE TITLE
Taalfoutje in het infoscherm

### ISSUE THREAD

**Issue by meiphoo7-Mae** [retrospect-addon/plugin.video.retrospect#1603]
### Describe the bug

Dit is eigenlijk totaal niet ernstig maar meer een schoonheidsfoutje.
Als je kijkt in het infoschermpje van Retrospect dan wordt er gesproken over 'Noorweegse' kanalen. Het moet zijn 'Noorse'. Dat wist je natuurlijk ook wel maar heb je waarschijnlijk gewoon over het hoofd gezien. Het staat er al gedurende wat langere tijd dus voor de volledigheid meld ik het maar een keertje.

### To Reproduce

1. Open het contextmenu van Retrospect
2. Open het informatie item.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:
- Retrospect version:

**Comment by basrieter** [comment]
Thanks. Ik heb het gefixed in de vertalingen: https://github.com/retrospect-addon/plugin.video.retrospect/pull/1598/files#diff-83528db5dacfb8c431d4f559d472fd790a8de3f67333425f3d3c01b6ac10e9d7
