### ISSUE TITLE
UR Play wont work 

### ISSUE THREAD

**Issue by wellzel** [retrospect-addon/plugin.video.retrospect#1604]
### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

## Additional context or screenshots (if appropriate)

Cant open UR Play in Sweden

Log http://paste.kodi.tv/cogelequxu

### Your Environment
Used Operating system: Xbian (Debian)

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.3 Matrix
- Retrospect version: 5.5.2+matrix.1

**Comment by basrieter** [comment]
Yeah, I noticed that. They were migrating their API. Need some changes for that. Main issue is the maximum of 25 items per API call.

**Comment by basrieter** [comment]
I checked: the paging has a max size of 20 per call. So I need to do 94 call to get the main list :(

**Comment by basrieter** [comment]
Could you download and "install from zip" this zip file: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1604.zip

And see if the user experience is acceptable? I now retrieve the 400 most recent shows (not all 1700+)

**Comment by wellzel** [comment]
I appreciate your help.  
I can now select the first 20 alternatives and the same within the alternatives: Last Chance, Most recent episodes, Popular but only with 20 posts starting with the oldest so I will never see the latest :-) 

"Categories" Search" and "Tirles with A-V" won't work at all. If only "Search" would have been in place with 20 posts I would be happy. I guess the 400 latest could be a start as well but then ordered by the latest first
Last log
http://paste.kodi.tv/wutahuvuvi

**Comment by basrieter** [comment]
I only worked on the listing of the mainlist so for. None of the others. If you re-download and install, the new version will force a 24 hour cache of the main listing, so  you only need to wait for the list once a day . Furthermore you can configure how many API pages you want to load via the channel options of UR Play. 

I will now continue to fix the rest.

**Comment by wellzel** [comment]
https://raw.githubusercontent.com/osund/urget/master/urget.py

**Comment by basrieter** [comment]
This is just the video stream, not the listing. Just give me some time to fix it.

**Comment by basrieter** [comment]
As far as I can see, it should be OK again. Please redownload and double check.

**Comment by wellzel** [comment]
Sorry I just realized that

**Comment by matsarv** [comment]
### Bug: 
The Episode item don't end up in Season folder. The last Season Episodes ends up in Show folder and selecting any other Season folders the Episodes ends up in Show folder.

See the TV shows: "Småsagor" (Season) and "Mediesnacket" (Year)

### Request: 
If it not to much work it would be nice to have the main list in a seperate "TV show" folder and then remove the dotts on the other folders.

**Comment by wellzel** [comment]
Well done!
**Categories**
If you select All Programs in Categories you will only be able to select the first 20. I don't mind, as the other selections which contains all programs though in categories actually works.
http://paste.kodi.tv/wukizocuca

**Last Chance**
You get 20 posts to select from and they are all working

**Most Recent episodes**
You get 20 posts to select from and they are all working Perhaps you should list them in a descending order by date earliest first

**Popular**
You get 20 posts to select and they are all working

**Search**
You get 20 posts to select from and they are all working

**Titles with A-V**
Are all working but after V comes X, Z, Å, Å, Ö (Ä should not come after A) in the very same order from which I'm missing X, Z and Å.

Thank you for the help!!

**Comment by basrieter** [comment]
>Titles with A-V
>Are all working but after V comes X, Z, Å, Å, Ö (Ä should not come after A) in the very same order from which I'm missing X, Z and Å.

That is something that is related to Kodi and its sorting.

>You get 20 posts to select from and they are all working Perhaps you should list them in a descending order by date earliest first

I tell Kodi to sort by date, but can't tell Kodi to sort ascending or descending.

> If it not to much work it would be nice to have the main list in a seperate "TV show" folder and then remove the dotts on the other folders.

Done!

Other stuff should have changed now. Please redownload and check.

**Comment by matsarv** [comment]
I'm getting some errors under Categories.

In "UR Play / Categories / Drama" the single items here are getting error messages when I'm trying to play them.

### Bug1:
The show "Kolsvart" getting error: 
GET failed with '404 Not Found' (0:00:00.215588) for https://urplay.se/program/206225-kolsvart

URL using the web-browser: https://urplay.se/serie/206225-kolsvart
Retrospect logfile: https://paste.kodi.tv/inavezayoz.kodi

### Bug2:

The show "Lilla L" getting error:  
GET failed with '500 Internal Server Error' (0:00:00.383172) for https://urplay.se/api/v1/series?id=204054

URL using the web-browser: https://urplay.se/program/204054-lilla-l
Retrospect logfile: https://paste.kodi.tv/yigowusupu.kodi

**Comment by basrieter** [comment]
Ok, let me check those last 2 things tonight.

**Comment by basrieter** [comment]
Category parsing was wrong. Fixed that. Please try again.

**Comment by matsarv** [comment]
Excellent, all the programs I have tested is working OK now.

FYI. Found a difference from other channels, the Season folder icon uses the Item icon. Not any issue.

A final question:
Is there an easy way to get season number to be used in the "create_video_item_json" function? Will be needed for some testing for Episode to use 1x01, 2x01 as implemented in other channels.

**Comment by basrieter** [comment]
>Is there an easy way to get season number to be used in the "create_video_item_json" function? Will be needed for some testing for Episode to use 1x01, 2x01 as implemented in other channels.

That is not possible, as they do not provide season numbers: seasons can even have labels.

**Comment by basrieter** [comment]
Season icon fixed.

**Comment by matsarv** [comment]
Now the old problem are back.






> ### Bug:
> The Episode item don't end up in Season folder. The last Season Episodes ends up in Show folder and selecting any other Season folders the Episodes ends up in Show folder.
> 
> See the TV shows: "Småsagor" (Season) and "Mediesnacket" (Year)

**Comment by basrieter** [comment]
I just fixed that. Please recheck.

**Comment by matsarv** [comment]
Excellent, all is working OK now.

**Comment by basrieter** [comment]
Can somebody translate these: 

![image](https://user-images.githubusercontent.com/1310443/151075591-b77b727d-8a3e-46f3-84ac-f3c78fc3bd06.png)

**Comment by matsarv** [comment]
I think this will be ok.


msgctxt "#30511"
msgid "Add shortcut"
msgstr "Lägg till genväg"

msgctxt "#30512"
msgid "Please provide a name for the shortcut."
msgstr "Ange ett namn för genvägen."

msgctxt "#30584"
msgid "Fetching a long list of items using multiple API calls."
msgstr "Flera hämtningar för en lång programlista."

msgctxt "#30585"
msgid "Page {} of {}"
msgstr "Sida {} av {}"

msgctxt "#30586"
msgid "Number of pages to load for the main listing"
msgstr "Antal sidor som skall laddas ner för programlistan"

**Comment by wellzel** [comment]
I would prefer this translation for  "#30584"
Hämtar en lång lista med objekt med flera API-anrop

msgctxt "#30584"
msgid "Fetching a long list of items using multiple API calls."
msgstr "_Flera hämtningar för en lång programlista_."

I would prefer this translation for "#30586"
Antal sidor som skall laddas ner för huvudlistan

msgctxt "#30586"
msgid "Number of pages to load for the main listing"
msgstr "Antal sidor som skall laddas ner för programlistan"

**Comment by basrieter** [comment]
I just merged the changes, but if both of you can agree, I will update the translations again.

**Comment by matsarv** [comment]
Object and API sounded a bit to much technical but the suggested changes is OK for me. Go ahead and do the changes.

**Comment by basrieter** [comment]
See #1610

**Comment by matsarv** [comment]
Checked.
You seems to have change the wrong text:

msgctxt "#30584" change is OK,

msgctxt "#30586" should change to:  

```
msgctxt "#30586"
msgid "Number of pages to load for the main listing"
msgstr "Antal sidor som skall laddas ner för huvudlistan"

```



msgctxt "#30041" should not be changed. Change back to:

```
msgctxt "#30041"
msgid "Show \"All Favourites\" in main Channel listing"
msgstr "Visa \"Alla favoriter\" i kanallistan"
```

**Comment by basrieter** [comment]
Perhaps it makes more sense to directly report this here: https://kodi.weblate.cloud/projects/kodi-add-ons-video/plugin-video-retrospect/sv_se/

**Comment by matsarv** [comment]
There are now "2 strings with suggestions - 16 words" in Kodi Weblate

**Comment by basrieter** [comment]
See #1610

**Comment by matsarv** [comment]
Sorry, entered the escape character before " in translation, ended up with 2 extra \\

I did a new suggestion, I really hope it's correct now.

**Comment by basrieter** [comment]
I updated the translation.
