### ISSUE TITLE
discovery+ sweden, not listing latest programs and episodes.

### ISSUE THREAD

**Issue by orfeous1** [retrospect-addon/plugin.video.retrospect#1615]
discovery+ does not list latest programs and episodes.
no error messages.
works fine browsing the site in chrome, episodes shows up as "free"

For example "Vägens Hjältar" or "Wahlgrens Värld"

I guess they changed something?

**Comment by basrieter** [comment]
Attach a debug retrospect.log please.

**Comment by orfeous1** [comment]
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/8149358/retrospect.log)
[kodi.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/8149359/kodi.log)

Here you have.
Opened Wahlgrens Värld and Vägens Hjältar and then exit/quit Kodi

**Comment by orfeous1** [comment]
Any updates on the issue?

**Comment by orfeous1** [comment]
> Attach a debug retrospect.log please.

any updates?

**Comment by basrieter** [comment]
I had to get past some Covid stuff. I checked, but those items are listed as "Premium" items on the API. So they are labelled as such. If you filter those items, you will end up with an empty list.

**Comment by orfeous1** [comment]
I see!
No, theyre Free to watch with a free account.
There something wrong with retrospect here. Since i can watch on discoveryplus.se website free.
Also new seasons are displayed which they arent in retrospect.

So i cant use retrospect anymore for discoveryplus.

**Comment by basrieter** [comment]
Well, currently, logging in does not work at all and it seems that this will take time.

**Comment by basrieter** [comment]
But if you disable the filters, the items will show. Can you play them?

**Comment by orfeous1** [comment]
No, Discoveryplus and Kanal 5 are gone from channel list now.
It has been working great for me for some of the programs/shows.

**Comment by basrieter** [comment]
See 2692b286. These channels have been removed for now.

**Comment by orfeous1** [comment]
I found an unofficial plugin for kodi that works for discoveryplus and the related sbs channels.
You link your device and enter a pin. And woila it syncs to the linked device cookies.
Works great. Maybe you have a solution there.

**Comment by basrieter** [comment]
Interesting option, the linking with PIN. Let me check that.

**Comment by rytmisk** [comment]
Hi
Has there been any news regarding this? Would be awesome!!
