### ISSUE TITLE
NPO streams (NPO1, NPO2, NPO3) not working anymore

### ISSUE THREAD

**Issue by Piscator74** [retrospect-addon/plugin.video.retrospect#1616]
### Describe the bug

Since a couple of days, the NPO1, NPO2 and NPO3 live streams are not working anymore (checked it on various installations).

### Debuglog

The log file reports the following error:
_cut_: no full logs as pastes: use attachments

The **debug** retrospect.log can be found here:
_cut_: no full logs as pastes: use attachments

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.3
- Retrospect version: 5.5.3

**Comment by basrieter** [comment]
Please post a full DEBUG retrospect.log as a file attachment here.

**Comment by Piscator74** [comment]
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/8156440/retrospect.log)

**Comment by basrieter** [comment]
Could please enable debug logging in Retrospect, try playback again, and then upload that new logfile? This one is normal info log.

**Comment by Piscator74** [comment]
I was sort of assuming that the links for the streams are broken (since a few days) as it gives the error: No MediaItem to play. So I thought this would be sufficient. I'll send a DEBUG log later.

**Comment by basrieter** [comment]
It's all working for me 100% here. So that is why I need some more info.

**Comment by henkv1** [comment]
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/8163724/retrospect.log)
Same issue here. I've added the debug log.

**Comment by basrieter** [comment]
I think it has to do with expiring sessions. Older cookies are causing that. If you want to fix it quickly: remove cache and cookies via the Retrospect settings.

**Comment by Piscator74** [comment]
Removing cache and cookies did resolve the problem, thanks!
