### ISSUE TITLE
Kijk playback fails

### ISSUE THREAD

**Issue by Derkades** [retrospect-addon/plugin.video.retrospect#1617]
### To Reproduce

1. Select a video from kijk.nl for playback

### Debuglog

The **debug** retrospect.log can be found here:
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/8164636/retrospect.log)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

To fix an unrelated issue, ` libwidevinecdm.so` was replaced according to instructions in https://github.com/xbmc/inputstream.adaptive/issues/877#issuecomment-1021585184

Clearing cookies/cache didn't help.

Used versions:
- Kodi version: LibreELEC 10.0.1, Kodi 19.3
- Retrospect version: 5.5.3

**Comment by basrieter** [comment]
Which item are you trying to play?

**Comment by basrieter** [comment]
It is all playing just fine here. I guess your Widevine replacement is causing the issue.

**Comment by Derkades** [comment]
Hm ok thanks, I'll try reinstalling the latest version, maybe the stuttering bug has been fixed by now

**Comment by Derkades** [comment]
Still doesn't work after using the "(Re)install widevine" option in inputstream. I looked into the debug log and it looks like for this specific program, Kijk returns an unencrypted stream. I can download the manifest using youtube-dl and play it back without needing to decrypt it first. Does retrospect handle this case, or does it always try to use widevine?

**Comment by basrieter** [comment]
Did you restart Kodi after the reinstall?

**Comment by Derkades** [comment]
I did not, now that I did it works! NPO buffering issue also seems to be solved with the new widevine version.
