### ISSUE TITLE
RTL XL premium paid sinds deze week

### ISSUE THREAD

**Issue by Meneerleblanc** [retrospect-addon/plugin.video.retrospect#1619]
### Describe the bug

Als voorbeeld, 2 weken geleden afleveringen kunnen kijken van married at first....
Vandaag de melding dat het een premium/paid stream is.

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:
- Retrospect version:

**Comment by basrieter** [comment]
En hoe is dat op de website van RTL XL zelf?

**Comment by basrieter** [comment]
Any update on my question?
