### ISSUE TITLE
There are duplicate menu item to show information for an item

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1620]
### Describe the bug

There are duplicate menu item to show information for an item.
Now when the Kodi Team has added "Information" to the context menu popup the "Show info" is not needed to be added by Retrospect any more.

## Expected Behavior

Only show "Information"

## Actual Behavior

Shows both "Show info" and "Information"

## Possible Fix

Made changes to "addonaction.py" in "def _get_context_menu_items..."

	Removed the below and associated code.

```
        if item.has_info():
            info_action = LanguageHelper.get_localized_string(LanguageHelper.ItemInfo)
            context_menu_items.append((info_action, 'Action(info)'))
```

### Screenshots 

![showinfo](https://user-images.githubusercontent.com/46671821/158617629-a40cab1c-4af3-4c8e-918a-61eb4b56dbeb.jpg)

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.4  (tested in Nexus Alpha1)
- Retrospect version: 5.5.3+matrix.1

**Comment by basrieter** [comment]
Thanks! Closed with 9240aa84
