### ISSUE TITLE
SE SVT Play: "New on SVT Play" is not working.

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1621]
### Describe the bug

"New on SVT Play" is not working.

## Expected Behavior

List newly added shows.

## Actual Behavior

Error: No episodes found......

## Fix

1. In chn_svt.py search for "KM6mbZ4"
2. Replace "selectionId" value to "8DMWMyQ"

![Image](https://user-images.githubusercontent.com/46671821/159176594-70332b40-4d6f-4c53-9fab-740d27a1f8b1.png)

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.4
- Retrospect version: 5.5.3+matrix.1

**Comment by basrieter** [comment]
Please install and try https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1621.zip

**Comment by matsarv** [comment]
Working. Thanks.

**Comment by basrieter** [comment]
Will try to do a release soon.
