### ISSUE TITLE
SVTPlay sub issue

### ISSUE THREAD

**Issue by Anth70** [retrospect-addon/plugin.video.retrospect#1625]
Since a week ago SVTPLAY has put in some code in the end of each subline. It makes it hard to read. So the Retrospect works super and i just ask for a fix to solve this:). I run it on a RPi4B Libreelec 10.0.2 and Matrix 19.4. Best regards Thore from Sweden...

**Comment by basrieter** [comment]
Do you have a full **debug** retrospect.log that you can link or attach here?

**Comment by Anth70** [comment]
Sorry, missed the picture...
-------- Originalmeddelande --------Från: Bas Rieter ***@***.***> Datum: 2022-03-27  21:13  (GMT+01:00) Till: "retrospect-addon/plugin.video.retrospect" ***@***.***> Kopia: Anth70 ***@***.***>, Author ***@***.***> Ämne: Re: [retrospect-addon/plugin.video.retrospect] SVTPlay sub issue
  (Issue #1625) 
Do you have a full debug retrospect.log that you can link or attach here?

**Comment by basrieter** [comment]
Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/issue-1625.zip and a new show. Keep in mind that existing subs are cached and will stay defect until the Retrospect cache is cleared.

**Comment by matsarv** [comment]
I have tested above change and the fix works.

**Comment by Anth70** [comment]
Wow, that was a fast fix... I am so impressed of the work that was done... THANKS😁😁
-------- Originalmeddelande --------Från: Mats Arvidsson ***@***.***> Datum: 2022-03-30  21:30  (GMT+01:00) Till: "retrospect-addon/plugin.video.retrospect" ***@***.***> Kopia: Anth70 ***@***.***>, Author ***@***.***> Ämne: Re: [retrospect-addon/plugin.video.retrospect] SVTPlay sub issue
  (Issue #1625) 
I have tested above change and the fix works.

**Comment by basrieter** [comment]
I will try to push an update soon.

**Comment by Anth70** [comment]
Sounds great💪💪and thanks again for a great addon
-------- Originalmeddelande --------Från: Bas Rieter ***@***.***> Datum: 2022-03-30  22:00  (GMT+01:00) Till: "retrospect-addon/plugin.video.retrospect" ***@***.***> Kopia: Anth70 ***@***.***>, Author ***@***.***> Ämne: Re: [retrospect-addon/plugin.video.retrospect] SVTPlay sub issue
  (Issue #1625) 
I will try to push an update soon.

**Comment by Anth70** [comment]
Hello and thanks for the fast respond. I attache a picture there you can see what i mean. There is lines after each sub. Thanks and best regards Thore
-------- Originalmeddelande --------Från: Bas Rieter ***@***.***> Datum: 2022-03-27  21:13  (GMT+01:00) Till: "retrospect-addon/plugin.video.retrospect" ***@***.***> Kopia: Anth70 ***@***.***>, Author ***@***.***> Ämne: Re: [retrospect-addon/plugin.video.retrospect] SVTPlay sub issue
  (Issue #1625) 
Do you have a full debug retrospect.log that you can link or attach here?

**Comment by Anth70** [comment]
Hello again and thanks for the great fix you make. Now i cannot find my local news channel after the latest update. Is it possible to fix that? Tha channel i miss is "Nyheter Lokalt öst". Best regards Thore from Sweden 
-------- Originalmeddelande --------Från: Bas Rieter ***@***.***> Datum: 2022-03-30  22:36  (GMT+01:00) Till: "retrospect-addon/plugin.video.retrospect" ***@***.***> Kopia: Anth70 ***@***.***>, Author ***@***.***> Ämne: Re: [retrospect-addon/plugin.video.retrospect] SVTPlay sub issue
  (Issue #1625) 
Closed #1625 via 3f2fc7f.

**Comment by basrieter** [comment]
Please create a new issue for this and don't reuse unrelated (and closed) issues.
