### ISSUE TITLE
24 Classics failed with '404 Not Found' and Error Processing FolderList

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1626]
### Describe the bug

24 Classics failed with '404 Not Found' and Error Processing FolderList

## Expected Behavior

Show FolderLists

## Actual Behavior

Error Processing FolderList

### Debuglog

The **debug** retrospect.log can be found here: https://paste.kodi.tv/ofecisaxak.kodi

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.4
- Retrospect version: 5.5.3

**Comment by basrieter** [comment]
Seems like they did a a large update and a lot moved to Spotify. Can you tell me which parts of the site you expected to see? So the URL's for the site.

**Comment by matsarv** [comment]
I have looked around the site and things have moved to Youtube and Spotify. I decided to skip this channel for now because I can not find anything useful anymore. You may want to delete this channel. It is better to concentrate on the TV channels.

In my opinion, you can close this issue.

**Comment by basrieter** [comment]
Yes, that was my impression to. But thanks for mentioning.
