### ISSUE TITLE
SVTPlay - No year or season number

### ISSUE THREAD

**Issue by Sopor** [retrospect-addon/plugin.video.retrospect#1629]
### Describe the bug

`Marika Carlsson är nyfiken döv` will not show any year or season, but it seems to be the same on [svtplay](https://www.svtplay.se/marika-carlsson-ar-nyfiken-dov)

## Possible Fix

I don't know if there are more like this, but maybe you could add some dummy text when this happens?

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here: https://paste.kodi.tv/yudetujifu.kodi

### Screenshots 

![image](https://user-images.githubusercontent.com/5789283/161829819-e140cf2f-ca50-4618-98a9-3018cd86a4b9.png)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.4
- Retrospect version: 5.5.4+bug-1628

**Comment by basrieter** [comment]
See #1628
