### ISSUE TITLE
SVT Play -No episodes found for the selected item-

### ISSUE THREAD

**Issue by dobbelina** [retrospect-addon/plugin.video.retrospect#1630]
### Describe the bug

The following links display *-No episodes found for the selected item-*
**Currently playing**
**Last Chance**
**Most viewed episodes**
**Recent**

### Debuglog

https://paste.kodi.tv/gozizulofu.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.9
- Retrospect version: 5.5.4

**Comment by basrieter** [comment]
See #1628
