### ISSUE TITLE
Geen nieuwe programma's KIJK.nl

### ISSUE THREAD

**Issue by noud61** [retrospect-addon/plugin.video.retrospect#1631]
Sinds de update van een paar dagen geleden worden er geen nieuwe programma's meer toegevoegd bij Kijk.nl .
Op een andere mediaspeler waar ik versie 5.3.3. van retrospect heb geinstalleerd wekt Kijk.nl wel goed.
Is het mogelijk om dit probleem op te lossen, of terug te gaan van  versie 5.3.4 naar versie 5.3.3?

**Comment by basrieter** [comment]
De laatste update heeft echt niks gedaan met Kijk.nl. Je zal iets meer informatie moeten geven: voorbeelden van wat ontbreekt en een debug Retrospect logfile

**Comment by noud61** [comment]
Dank je voor je snelle reactie.
Ik heb gemerkt dat sinds een paar dagen alleen de programma's van sbs niet meer worden opgehaald.
Heb nu ook een logfile toegevoegd.
Ik hoop dat je een oplossing voor me hebt.
Bij voorbaat dank.
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/8456590/retrospect.log)

**Comment by basrieter** [comment]
Thanks voor het beetje extra info, maar jammer genoeg is de log file geen debug log, maar een normale. Je kan het log niveau in Retrospect aanpassen en dan nogmaals naar de tv programma's navigeren die niet updaten. Dan kan ik wat meer zien.

**Comment by noud61** [comment]
Hoi Bas,
Nadat ik het logniveau heb aangepast en ook de cookies en cache heb opgeschoond werkt alles weer naar behoren.
Bedankt voor je snelle reactie en het meedenken.

**Comment by basrieter** [comment]
Ok, dat klinkt goed dan! Veel plezier er mee.
