### ISSUE TITLE
SVT Play thumbnail issue

### ISSUE THREAD

**Issue by dobbelina** [retrospect-addon/plugin.video.retrospect#1632]
# Problem description
Thumbnails only show on some items(Films), but not on others with "Media info" view on my Confluence skin.
I know SVT Play addon author fixed it by duplicating the episode thumbnail into the fanart.
If it could be fixed it would be great, screenshot below.
Thanks for this great addon!

# System information
Kodi version: 
Kodi 18.9 & 19.4
Platform: 
Windows
Plugin version: 
5.5.4
# Screenshot
<img width="444" alt="screenshot000" src="https://user-images.githubusercontent.com/46063764/162680962-c88e49c8-1415-4d6e-92ea-64291c4c58f7.png">
Film

<img width="444" alt="screenshot001" src="https://user-images.githubusercontent.com/46063764/162681038-355f9aeb-60ab-47c7-b44b-8487c4be9c89.png">

**Comment by basrieter** [comment]
Could you please try the latest master version? I recently update SVT a lot: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/master.zip

**Comment by dobbelina** [comment]
@basrieter 
Installed it on Kodi 19.4 but issue still persists.
Most items don't show, only films.

**Comment by basrieter** [comment]
And do you have this setting enabled: 

![image](https://user-images.githubusercontent.com/1310443/162686993-ebe44ef2-8270-47af-83e6-6d4f2fc14be9.png)

`Show thumbnail as fanart if no fanart is available`?

**Comment by dobbelina** [comment]
That setting did it, thank you.
<img width="444" alt="screenshot000" src="https://user-images.githubusercontent.com/46063764/162692472-66cea600-4b47-4103-af28-6b3d63d0c93b.png">

**Comment by basrieter** [comment]
Great! Should it be enabled by default?

**Comment by matsarv** [comment]
I think it be enabled by default!
