### ISSUE TITLE
No Retrospect items will play. 

### ISSUE THREAD

**Issue by Arathonk** [retrospect-addon/plugin.video.retrospect#1633]
### Describe the bug

No Retrospect items will play, updated Widevide. 

## Expected Behavior

Play items and show lists. 

## Actual Behavior

Cannot start playback

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
Https://paste.kodi.tv/hibepunaca

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.4
- Retrospect version: 5.5.@+matrix.1

**Comment by basrieter** [comment]
Please clear the Retrospect cache via the add-on settings.

**Comment by basrieter** [comment]
![image](https://user-images.githubusercontent.com/1310443/162812648-e35c9ea0-fbe0-40b5-90fc-786b0da34a40.png)

**Comment by Arathonk** [comment]
Cleared the cache but I didn't help unfortunately..

**Comment by basrieter** [comment]
So then you will need to provide a proper debug Retrospect log.

**Comment by Arathonk** [comment]
Https://paste.kodi.tv/qocirofuce

After clearing cache and restarting, it asks me to update widevine. Is I decline it will play items somewhat normal, if I update it won't says can't play, I tried updating and reinstalling widevine using Retrospect settings and using the Slyguy Common.

**Comment by basrieter** [comment]
From the log file I can see that Retrospect is sending the right stuff to Kodi now.

**Comment by Arathonk** [comment]
So what's up with the widevine update then? Retrospect keeps asking me to update, when I do it won't play.

**Comment by basrieter** [comment]
https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/511

**Comment by Arathonk** [comment]
> [emilsvennesson/script.module.inputstreamhelper#511](https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/511)

Do I need to manually install those test builds of widevine?

**Comment by basrieter** [comment]
Install the test build of the input stream helper and reinstall WideVine, then reboot

**Comment by Arathonk** [comment]
That worked! Thanks.

I now have the following happening, when I start to play an item I get a bar on the top of the screen showing seconds and saying seeking, do you have any idea what this is and how to get rid of it?
