### ISSUE TITLE
SVT Play sort order Recent programs don't reflect website

### ISSUE THREAD

**Issue by dobbelina** [retrospect-addon/plugin.video.retrospect#1634]
## Bug report
Sort order of **Recent** programs don't reflect the website:https://www.svtplay.se/senaste
Sorting options as in the screenshot below don't correct the issue,
regardless what you change it to.

**Used versions:**
- Kodi version: 18.9 & 19.4
- Retrospect version: 5.5.4
## Screenshot
<img width="444" alt="screenshot001" src="https://user-images.githubusercontent.com/46063764/162815522-f5eb51e0-9668-4edb-8b4b-c5673c9921a3.png">

**Comment by basrieter** [comment]
Sorry, that is just how kodi sorts. There is not date information on most of the items. Can't help that.

**Comment by dobbelina** [comment]
For some odd reason it corrected itself after the live broadcast of "Aktuellt" was finished?
If you look at my screenshot of the programs under the yellow "Live" link they have now disappeared?

**Comment by basrieter** [comment]
If you sort by "Default" and refresh the changes, the list will be as they appear in the API.
