### ISSUE TITLE
Items disappears after being played

### ISSUE THREAD

**Issue by wolgast** [retrospect-addon/plugin.video.retrospect#1637]
Hello,

Only uses Swedish channels, but whenever I play a show it disappears. For example if the list shows 10 episodes if paw patrol, after playing episode 1 it is no longer listed, the other 9 is still there though, and so on.

thanks for a great addon!

**Comment by basrieter** [comment]
That is a feature of Kodi to hide watched videos. You can change that in settings of Kodi: 

![image](https://user-images.githubusercontent.com/1310443/167266023-25252d39-fde1-45bf-a485-e5391ecc26bf.png)

![image](https://user-images.githubusercontent.com/1310443/167266027-6249d42d-fca0-4454-88ac-5c736270bb6f.png)

**Comment by wolgast** [comment]
Been using xbmc/kodi for +15 years, can’t believe I missed that. Thanks!

**Comment by basrieter** [comment]
Glad I could help!
