### ISSUE TITLE
Viafree channels? 

### ISSUE THREAD

**Issue by nickot1** [retrospect-addon/plugin.video.retrospect#1640]
### Provide some details for the channel
- Name of the channel in English:
- Name of the channel in native language: 
- Website for the channel:
- If available link to the Android app for the VOD content of channel:
- Link to the logo of the channel
 
### Check which features should be implemented
- [ ] Video on-demand content
- [ ] TV live streams
- [ ] Use your account for the VOD services from Retrospect
- [ ] Access the premium content if you are eligible  

### Provide some details for the channel
- Name of the channel in English:
- Name of the channel in native language: 
- Website for the channel:
- If available link to the Android app for the VOD content of channel:
- Link to the logo of the channel
 
### Check which features should be implemented
- [ ] Video on-demand content
- [ ] TV live streams
- [ ] Use your account for the VOD services from Retrospect
- [ ] Access the premium content if you are eligible  

### Additional information

->

**Comment by nickot1** [comment]
It is any chance to get back viafree channels back on retrospect?

**Comment by basrieter** [comment]
They moved to Pluto.tv, which is not available in The Netherlands, so for the moment, I won't be re-adding them.
