### ISSUE TITLE
Error running plugin, cookiejar.dat

### ISSUE THREAD

**Issue by jimrobertson19** [retrospect-addon/plugin.video.retrospect#1643]
Hi,
I can't run Retrospect atm on my firestick 2 and I'm getting this error in my log file:

20220703 11:34:07 - [CRITICAL] - addon.py             - 70   - Error running plugin
20220703 11:34:07 - [CRITICAL] - addon.py             - 70   - | Traceback (most recent call last):
20220703 11:34:07 - [CRITICAL] - addon.py             - 70   - |   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.retrospect/resources/lib/addon.py", line 50, in run_addon
20220703 11:34:07 - [CRITICAL] - addon.py             - 70   - |     UriHandler.create_uri_handler(cache_dir=cache_dir,
20220703 11:34:07 - [CRITICAL] - addon.py             - 70   - |   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.retrospect/resources/lib/urihandler.py", line 57, in create_uri_handler
20220703 11:34:07 - [CRITICAL] - addon.py             - 70   - |     handler = _RequestsHandler(
20220703 11:34:07 - [CRITICAL] - addon.py             - 70   - |   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.retrospect/resources/lib/urihandler.py", line 320, in __init__
20220703 11:34:07 - [CRITICAL] - addon.py             - 70   - |     self.cookieJar.load()
20220703 11:34:07 - [CRITICAL] - addon.py             - 70   - |   File "/data/data/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/http/cookiejar.py", line 1799, in load
20220703 11:34:07 - [CRITICAL] - addon.py             - 70   - |     self._really_load(f, filename, ignore_discard, ignore_expires)
20220703 11:34:07 - [CRITICAL] - addon.py             - 70   - |   File "/data/data/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/http/cookiejar.py", line 2020, in _really_load
20220703 11:34:07 - [CRITICAL] - addon.py             - 70   - |     raise LoadError(
20220703 11:34:07 - [CRITICAL] - addon.py             - 70   - + http.cookiejar.LoadError: '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.retrospect/cookiejar.dat' does not look like a Netscape format cookies file
20220703 11:34:07 - [INFO    ] - addon.py             - 71   - Retrospect :: Flushing and closing logfile.

I tried uninstalling the addon and reinstalling it, but to no avail. If I try to pull the cookiejar.dat file with my adblink app on macos I get an error.

Please help! :)

**Comment by basrieter** [comment]
Seems like your cookie file got corrupted. Please reset that using the add-on settings:

![image](https://user-images.githubusercontent.com/1310443/177035811-0a2c9c94-339e-43ba-8bdb-621e5309a206.png)

`Clean-up cache and cookies`

**Comment by jimrobertson19** [comment]
> Seems like your cookie file got corrupted. Please reset that using the add-on settings:
> 
> ![image](https://user-images.githubusercontent.com/1310443/177035811-0a2c9c94-339e-43ba-8bdb-621e5309a206.png)
> 
> `Clean-up cache and cookies`

Thanks for the quick reply!
When I clicked "clean-up cache and cookies", I actually got the same error.

I proceeded to go into adblink and delete the cookiejar.dat file and that seems to have fixed the problem! So fixed for now :)

**Comment by basrieter** [comment]
I was afraid of that. But good to hear it worked out.
