### ISSUE TITLE
NPO Start oude afleveringen hebben geen ondertitels

### ISSUE THREAD

**Issue by PhyxionNL** [retrospect-addon/plugin.video.retrospect#1644]
### Describe the bug
Oude NPO afleveringen hebben geen ondertitels, bijvoorbeeld deze:
https://www.npostart.nl/de-streken-van-van-boven/08-02-2021/AT_300000600

## Expected Behavior
Ondertitels aanwezig. Op NPO zijn ze wel aanwezig:
![image](https://user-images.githubusercontent.com/7643972/177857475-6185aea0-5488-4bca-81c6-e2f01d6c2100.png)
De subs zijn hier beschikbaar:
https://rs.poms.omroep.nl/v1/api/subtitles/AT_300000600/nl_NL/CAPTION.vtt

Retrospect probeert deze URL binnen te halen:
https://assetscdn.npostart.nl/subtitles/original/nl/AT_300000600.vtt
Deze geeft een 403 error, dus misschien kan er in dat geval een fallback naar bovenstaande URL gedaan worden.

## Actual Behavior
Geen ondertitels.

### To Reproduce

1. Ga in NPO naar De streken van Van Boven.
2. Open 1x02 Achterhoek.
3. Zie dat er geen ondertitels zijn.

### Debuglog
[debuglog.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/9066833/debuglog.txt)

**Comment by basrieter** [comment]
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1644.zip from Kodi Matrix.

**Comment by PhyxionNL** [comment]
Thanks, dat werkt nu voor de oude afleveringen 🙂 Alleen werkt deze sub URL niet voor nieuwe afleveringen, ik denk dat eerst de nieuwe URL (assetscdn.npostart.nl) geprobeerd moet worden en bij geen geldige subs daarna de oude URL (rs.poms.omroep.nl).

**Comment by PhyxionNL** [comment]
Klopt, super, bedankt 🎉👍
