### ISSUE TITLE
NPO ondertitels is stuk voor nieuwe afleveringen

### ISSUE THREAD

**Issue by PhyxionNL** [retrospect-addon/plugin.video.retrospect#1646]
### Describe the bug
Ergens is in de laatste versie een fout geslopen die niet aanwezig was in de laatste test versie. Er wordt namelijk alleen nog maar de pomps URL aangeroepen:
https://github.com/retrospect-addon/plugin.video.retrospect/blob/master/channels/channel.nos/nos2010/chn_nos2010.py#L1369

Deze URL werkt niet met nieuwe afleveringen. Zo te zien is deze commit overgeslagen met het mergen:
https://github.com/retrospect-addon/plugin.video.retrospect/commit/380e5b0fc5b0082c500c2d02ffe6cb94b8221bdc

### Debuglog
[retro.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/9126471/retro.txt)

**Comment by basrieter** [comment]
Welke aflevering gaat er nu fout?

**Comment by PhyxionNL** [comment]
Bijvoorbeeld deze:
https://www.npostart.nl/mindfck/27-11-2021/AT_300000965
Oude afleveringen gebruiken die poms URL, nieuwere afleveringen (sinds ergens 2021 volgens mij) hebben die assetscdn URL nodig zoals in die commit ook was :)

**Comment by basrieter** [comment]
Er mist een commit. Waarschijnlijk op twee pc's gewerkt en een `git pull` vergeten.

Ga het fixen.

**Comment by basrieter** [comment]
Fixed in https://github.com/retrospect-addon/plugin.video.retrospect/releases/tag/v5.5.8. 

Inmiddels ook in de repo.

**Comment by PhyxionNL** [comment]
Super, bedankt @basrieter 👍
