### ISSUE TITLE
Retrospect won't open

### ISSUE THREAD

**Issue by Arathonk** [retrospect-addon/plugin.video.retrospect#1648]
### Describe the bug

Retrospect won't open 

## Expected Behavior

Opening addon

## Actual Behavior

Error upon opening

## Possible Fix

-

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
Https://paste.kodi.tv/wapavowaku

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.4
- Retrospect version: 5.5.8+matrix.1

**Comment by basrieter** [comment]
Delete `/storage/.kodi/userdata/addon_data/plugin.video.retrospect/cookiejar.dat`. Seems it was corrupted.

**Comment by Arathonk** [comment]
That worked!

**Comment by basrieter** [comment]
Great. It very rarely happens on pi's.
