### ISSUE TITLE
TV Shows (Full list) not showing entries on Kodi Leia

### ISSUE THREAD

**Issue by Coenstegeman** [retrospect-addon/plugin.video.retrospect#1650]
### Describe the bug

When choosing 'TV Shows (Full list)' from NPO Start menu, Retrospect returns a 'no episodes could be found for this item' message.

## Expected Behavior

It should show an alphabetical list of NPO programs

## Actual Behavior

Retrospect returns a 'no episodes could be found for this item' message.

### To Reproduce

1. Open Retrospect through addon browser
2. Select 'National -> NPO Start -> TV Shows (full list)'

### Debuglog

The **debug** retrospect.log can be found here:
http://paste.kodi.tv/adavexisuv

### Screenshots 

https://i.imgur.com/2kisWvA.png

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.9
- Retrospect version: 5.5.8

**Comment by basrieter** [comment]
I apparently already fixed this in the `master` branch before my holiday: 7edc34e0. So you can always use that in combination with Kodi Matrix. 

If you want it right now on Leia, the change is very minor and you can fix it in the `chn_nos2010.py`: 

![image](https://user-images.githubusercontent.com/1310443/185712463-453d4a28-027c-4f33-ad4f-ea7ce0956330.png)

**Comment by Coenstegeman** [comment]
Confirmed working, thanks for the fix!

**Comment by basrieter** [comment]
Should be fixed in https://github.com/retrospect-addon/plugin.video.retrospect/releases/tag/v5.5.9 which can be found in the Kodi repos.
