### ISSUE TITLE
NPO Live Channels not working when opening them from favorites. 

### ISSUE THREAD

**Issue by Arathonk** [retrospect-addon/plugin.video.retrospect#1652]
I've added the NPO Live Channels to Kodi's favorites, when just added they work fine, but after a little while they won't open anymore and give me an error.
When going trough Retrospect's menu's I can open them just fine.

Log: https://paste.kodi.tv/tifojedeqe

**Comment by Arathonk** [comment]
> Couple of questions:
> 
> * How old are these favourites?
1 day in this instance 
> * Did you try removing them and re-adding them again?
Yes

Everytime they stop working I do that, then it works for a day or so and then it stops working.

**Comment by basrieter** [comment]
Can you please switch to TRACE logging, and create another log in which it fails?

**Comment by basrieter** [comment]
I found it! And I need to think about how to fix it. The thing is that the favourite is pointing towards a local file with meta data. The identifier (filename) is based on the url that was opened. 

Now the LIVE url of NPO does not change, but the content that is retrieve is. So each time you open the live listing, it will fetch new content and overwrite old content.

**Comment by Arathonk** [comment]
> I found it! And I need to think about how to fix it. The thing is that the favourite is pointing towards a local file with meta data. The identifier (filename) is based on the url that was opened.
> 
> Now the LIVE url of NPO does not change, but the content that is retrieve is. So each time you open the live listing, it will fetch new content and overwrite old content.

Yes I thought it was something like that! Do you think you can fix it or find a workaround?

**Comment by basrieter** [comment]
I need to do some thinking and see how to fix this smart.

**Comment by basrieter** [comment]
Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/issue-1652.zip in Kodi Matrix. Then: 

- Delete the older favorites
- Navigate from the main Retrospect page to the NPO live streams
- Re-add them to the favorites

Then check if it does not break.

**Comment by Arathonk** [comment]
> Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/issue-1652.zip in Kodi Matrix. Then:
> 
> * Delete the older favorites
> * Navigate from the main Retrospect page to the NPO live streams
> * Re-add them to the favorites
> 
> Then check if it does not break.

Done! I'll check periodically over the next few days and I will let you know how it goes. Thanks!

**Comment by basrieter** [comment]
Is it working?

**Comment by Arathonk** [comment]
> Is it working?

Untill now it's still working perfectly yes!
Are you going to release it in a new Retrospect update?

**Comment by basrieter** [comment]
I will push an update soon.

**Comment by basrieter** [comment]
Update was released: https://github.com/xbmc/repo-plugins/pull/4141 and https://github.com/xbmc/repo-plugins/pull/4142
