### ISSUE TITLE
(Sweden) TV4 play needs login

### ISSUE THREAD

**Issue by frownlayer** [retrospect-addon/plugin.video.retrospect#1657]
### Describe the bug

Log in account is now required.

## Expected Behavior

It should be playing the selected episode. 

## Actual Behavior

Error message on everything I tried. 

## Possible Fix

A login system need to be added to the channel.

### To Reproduce

1. Start any movie on tv4 play
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: latest
- Retrospect version: 5.5.10

**Comment by basrieter** [comment]
Please fill out all the required fields!

**Comment by huey-smart** [comment]
Same issue on Android. Started today. Other channels play fine and watching via tv4play requires login.

**Comment by user119999** [comment]
> ## Bug report
> ### Describe the bug
> I can't read logs that well, but @frownlayer says: Log in account is now required.
> 
> ## Expected Behavior
> It should be playing the selected episode.
> 
> ## Actual Behavior
> Error message on every single episode I tried.
I have randomly tested some episodes in different tv-shows and I can't start playback of any of those episodes.
The folders of those tv-shows i tested is showing all episodes, but as said, can't start playback of any episodes.
The folder 'Live events/Live broadcasts' ("Livesändningar" in swedish)  -  not showing any episodes.
> 
> ## Possible Fix
> @frownlayer says: A login system need to be added to the channel.
> 
> ### To Reproduce
> Steps to reproduce the behavior:
> 
> 1. Start any episode on TV4 Play
> 
> ### Debuglog
> The **debug** retrospect.log can be found here:
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/10006712/retrospect.log)
[kodi.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/10006716/kodi.log)

> 
> ### Screenshots
> ## Additional context or screenshots (if appropriate)
> ### Your Environment
> Used Operating system:
> 
> * [ ]  Android
> * [ ]  iOS
> * [x]  Linux
> * [ ]  OSX
> * [ ]  Raspberry-Pi
> * [ ]  Windows
> * [ ]  Windows UWP
> 
> Used versions:
> 
> * Kodi version: 19.4
> * Retrospect version: 5.5.10

**Comment by basrieter** [comment]
I will need to see how that works. Give me some time.

**Comment by basrieter** [comment]
Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1657.zip using the `install from zip` in Kodi Matrix. 

You need to:

* Run Retrospect once after installation
* Then go into the channel settings 
* Add username for TV4
* Add a password (Requires a Retrospect Vault to be set up: https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Storing-Passwords-in-the-Retrospect-Vault).
* Try to play a video.

Due to Geo restrictions it is hard for me to test it.

**Comment by huey-smart** [comment]
This fix works for me! Thanks for awesome support!

**Comment by user119999** [comment]
@huey-smart  -  I have no time to test the fixed zip-file yet...Does the folder 'Live broadcasts' ("Livesändningar") show content?

**Comment by huey-smart** [comment]
@user119999 - I tested now and in the folder "Currently playing" I see only "- No episodes found for the selected item -".

**Comment by user119999** [comment]
@huey-smart  -  ok, thanks - Yes, I meant the folder 'Currently playing'.....I also only saw "- No episodes found for the selected item -" yesterday, with Retrospect 5.5.10.

@basrieter  -  I've added som lines in my previous 'Bug report' above here...
Or do you want a 'New issue' opened for that bug?

Thanks in advance.

**Comment by basrieter** [comment]
Let me check those too.

**Comment by frownlayer** [comment]
Tested the .ZIP, now I can watch episodes from TV4 again.

**Comment by EnPajk** [comment]
@basrieter, you hard coded your own credentials in the code. I got it working with "dummy" as username and password.

**Comment by basrieter** [comment]
.....Never code when you are tired. Let me fix that.....password reset btw. Thanks @EnPajk

**Comment by basrieter** [comment]
Can somebody double check? You will most likely have to log on again....with your own credentials :)

**Comment by frownlayer** [comment]
Do I need to install e new ZIP?
I've changed my password to blabla, rebooted, and I can still watch episodes.

**Comment by huey-smart** [comment]
How to verify? I downloaded the zip again so please tell me if I should do it differently. Still works for me after installing the zip but "Currently playing" is still empty.

**Comment by basrieter** [comment]
I only changed the hardcoded stuff. But let me double check. Because it should have prompted you with a username/password. Did it do that?

**Comment by basrieter** [comment]
Latest version should fix the proper log-in. I will check the empty folders later.

**Comment by basrieter** [comment]
Live shows fixed (as far as I can check).

**Comment by lineslim** [comment]
Thanks for the fast response to this issue! Apologies if this is a basic question, but what is the best way to update Kodi/Retrospect on Chromecast with google TV? It seems diffucult to use a .zip file. Can I use the "update from repository" button? Does the Retrospect vault mentioned any additional installs in Kodi on Google TV?

**Comment by basrieter** [comment]
> Thanks for the fast response to this issue! Apologies if this is a basic question, but what is the best way to update Kodi/Retrospect on Chromecast with google TV? It seems diffucult to use a .zip file. Can I use the "update from repository" button? Does the Retrospect vault mentioned require any additional installs in Kodi on Google TV?

You can't update it via the repository yet, as this version is not yet in there. You could put them on a network share and install from there?

**Comment by huey-smart** [comment]
Something broke for me with the latest fix but I suspect I'm doing something wrong. I can now see live content. But I get login failed. What does "specify value for password" mean? I get that input field after entering my password.

**Comment by huey-smart** [comment]
But it's not asking me for a pin, it's asking me to specify a value for the password. And the input field is in plain text.

**Comment by huey-smart** [comment]
After testing some more I figure the password should go into that field. Problem is now I can't playback anymore. Anyone else experiencing this with the latest fix?

**Comment by basrieter** [comment]
Input is plain text, storage is fully encrypted. Please post a debug retrospect.log that contains a playback attempt.

**Comment by basrieter** [comment]
It is a TV4 issue: We get a Server 500 error back.

**Comment by basrieter** [comment]
I also found another issue that would prevent playback. Sorry :( But not being able to test from NL makes it hard.

**Comment by huey-smart** [comment]
SVT Play works via Retrospect. Streaming directly from TV4 Play (not via Retrospect) works. Is this happening only for me?

**Comment by huey-smart** [comment]
Oh sorry, missed your latest comment. Will test.

**Comment by dobbelina** [comment]
Downloaded the fix https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1657.zip 
Then created an account on tv4
There is no user name, you register with email address and a password.
Cleared the vault, created a new pin and added email as user name and password.
Doesn't play.
Kodi debug log
https://paste.kodi.tv/ojacolozir.kodi


Retrospect log
https://paste.kodi.tv/akidedeneg.kodi

**Comment by basrieter** [comment]
It won't work for all streams. That was the initial issue.

**Comment by basrieter** [comment]
> Downloaded the fix https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1657.zip Then created an account on tv4 There is no user name, you register with email address and a password. Cleared the vault, created a new pin and added email as user name and password. Doesn't play. Kodi debug log https://paste.kodi.tv/ojacolozir.kodi
> 
> Retrospect log https://paste.kodi.tv/akidedeneg.kodi

Are you in Sweden? Or outside?

**Comment by lineslim** [comment]
For me it works! Downloaded the zip to Chromecast Google TV using open browser & installed from Kodi. Setup vault pin and input tv4 credentials. Tested several streams, NP. Thanks for the fast fix!

**Comment by s0rk** [comment]
Maybe a noob question: This fix is Matrix only, yes? Any chance on getting one for Leia as well? Still on RPi3 and Leia here unfortunately.

**Comment by basrieter** [comment]
> Maybe a noob question: This fix is Matrix only, yes? Any chance on getting one for Leia as well? Still on RPi3 and Leia here unfortunately.

When I push it to the Kodi repo, the Leia version will also be there.

**Comment by s0rk** [comment]
> > Maybe a noob question: This fix is Matrix only, yes? Any chance on getting one for Leia as well? Still on RPi3 and Leia here unfortunately.
> 
> When I push it to the Kodi repo, the Leia version will also be there.

Oh, that will be awesome indeed. You are the Boss, thanks alot!

**Comment by dobbelina** [comment]
> > Downloaded the fix https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1657.zip Then created an account on tv4 There is no user name, you register with email address and a password. Cleared the vault, created a new pin and added email as user name and password. Doesn't play. Kodi debug log https://paste.kodi.tv/ojacolozir.kodi
> > Retrospect log https://paste.kodi.tv/akidedeneg.kodi
> 
> Are you in Sweden? Or outside?

Yes, I'm in Sweden

**Comment by frownlayer** [comment]
I've noticed that the movie doesn't close after watching. Disappears when pressing stop, but never Disappear by it self. Never been a problem before bugfix 1657.

**Comment by basrieter** [comment]
> I've noticed that the movie doesn't close after watching. Disappears when pressing stop, but never Disappear by it self. Never been a problem before bugfix 1657.
Check, I reverted one small thing. Could you verify that the stream now stops?

**Comment by krka** [comment]
Thanks, installing [bug-1657.zip](https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1657.zip) helped for me!

**Comment by dobbelina** [comment]
> Thanks, installing [bug-1657.zip](https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1657.zip) helped for me!
Re-downloaded fix above and now it works for me to. 👍

**Comment by kaisto** [comment]
Thanx a bunch for fixing this again mr Rieter. Works like a charm again. 🙏

**Comment by basrieter** [comment]
A new release is available in the Kodi repository.

**Comment by s0rk** [comment]
> A new release is available in the Kodi repository.

Marvellous! All working now. Once again, thank you so much for your efforts!

**Comment by hjerning** [comment]
> It won't work for all streams. That was the initial issue.

@basrieter is that verified or just based on the initial report?
https://github.com/spaam/svtplay-dl/issues/1509 came to another conclusion.

**Comment by basrieter** [comment]
You don't need a login for all streams, for **some**! As I cannot see that beforehand, you just need to login once (every year) and it works from that point on.

**Comment by rgainza** [comment]
I think their new api is just buggy. But to be honest their website always demands a login so it might be good that you've made this change. Maybe they will enforce it for everything soon.

**Comment by basrieter** [comment]
I had to tweak the clips (See #16662). Can somebody verify https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1662.zip to see if this (#1657) issue did not return?
