### ISSUE TITLE
RtlXL doesn't want to play

### ISSUE THREAD

**Issue by Arathonk** [retrospect-addon/plugin.video.retrospect#1658]
### Describe the bug

RtlXL doesn't want to play, mainly Expeditie Robinson(yesterday's episode for example) 

## Expected Behavior

Play the episode

## Actual Behavior

Doesn't play

### To Reproduce

1. Navigate to Expeditie Robinson
2. Play latest episode
3.

### Debuglog

The **debug** retrospect.log can be found here:
Https://paste.kodi.tv/xahawupoyu

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.4
- Retrospect version: Latest

**Comment by Arathonk** [comment]
> You will need to provide a username/password in the add-on settings for RTL XL.

Done that..

**Comment by basrieter** [comment]
Then I need a debug kodi.log

**Comment by Arathonk** [comment]
Apparently I had to login to RTLXL on my laptop, after that it miraculously worked on Retrospect. 🤷🏻‍♂️

**Comment by basrieter** [comment]
Great!
