### ISSUE TITLE
Kodi Music items lost after install of retrospect

### ISSUE THREAD

**Issue by joomlahenk** [retrospect-addon/plugin.video.retrospect#1661]
### Describe the bug

After install of retrospect and all setting voor NPO plus I indeed have it working. BUT! now all menu items of my music screen have disappeared, als after uninstalling of retrospect.
Also quality of NPO start plus is not as good as app on LG-TV, so I don't use retrospect but now I have an issue getting my music items back. Thank you retrospect!

## Expected Behavior

After install of retrospect all other menu items on Kodi do not change

## Actual Behavior

Menu items on music disappeared.

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:
- Retrospect version: 5.5.11
- Libreelec 10,0,3 on Rpi4

**Comment by basrieter** [comment]
Add-ons have 100% nothing to do with the main Kodi screen/listings. They are not even allowed to write/read data outside their own data folder. So the source of your problem lies somewhere else.

**Comment by joomlahenk** [comment]
Sure you can  ignore the issue. The cause of my issue is Retrospect weather you like it or not. I tried several times.
I just informed you about it.

**Comment by basrieter** [comment]
I am not ignoring, just telling you that no Kodi add-on will remove/change other parts of Kodi. That is just not allowed. So I really see no way that Retrospect broke your Kodi. 

So please do tell me how you installed, uninstalled and what is missing now. Inlcude a kodi.log that contains the install/uninstall and some screenshots of what is missing.
