### ISSUE TITLE
Subtitles not rendered correctly if text formatting is used

### ISSUE THREAD

**Issue by hermids** [retrospect-addon/plugin.video.retrospect#1663]
### Describe the bug
I have noticed that subtitles to shows from UR Play (Swedish) does not always render correctly. The problem seems to be when a narrator is speaking they use <i>italic</i> font to distinguish it from regular dialogue. I do not know for sure if this is a Retrospect problem or Kodi but I have only seen it on shows from UR Play with Retrospect.
The extra formatting is not handled correctly and the result is that only the first row of two are shown on screen, the other is lost. This problem have existed a long time.
I guess this problem can affect other channels also but I have only seen the use of text formatting on shows from UR Play.

One example is the show https://urplay.se/program/223428-naturskona-tagresor-i-varlden-destination-skye-i-skottland
SRT: https://undertexter.ur.se/223000-223999/223428-12.tt

For example these text rows:
SRT code:
```
<p begin="00:00:02.44" duration="00:00:05.16" end="00:00:07.60" style="default.left" tts:direction="ltr">
<i>
Följ med på en legendarisk resa
<br/>
genom det västra skotska höglandet-
</i>
</p>
```

### Expected Behavior
All rows of the subtitles should be displayed and rendered correctly regardless of any extra font formatting.
Expected text:
> <i>
> Följ med på en legendarisk resa
> <br/>
> genom det västra skotska höglandet-
> </i>

### Actual Behavior
If the subtitle text is using any extra formatting only the first text row will be displayed.
Actual text rendered by Retrospect/Kodi:
> <i>
> Följ med på en legendarisk resa
> </i>

### To Reproduce

Play any show with a narrator and enable subtitles. One example is: https://urplay.se/program/223428-naturskona-tagresor-i-varlden-destination-skye-i-skottland

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux, Coreelec 19.5 (latest as of 2022-12-11)
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.4.0
- Retrospect version: 5.5.11

**Comment by basrieter** [comment]
I think I fixed it. Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1663.zip

But keep in mind that subtitles are **cached** locally. So previously downloaded ones will still be broken. You can remove the cache in the Retrospect profile folder in the `userdata/addon_data/plugin.video.retrospect/cache`.

**Comment by matsarv** [comment]
The UR Play is now showing both rows in the subtitle.

I now saw 6 digits in the subtitle of a program in TV4 Play. Please change len(line) > 6 to len(line) > 5 in subtitlehelper.

**Comment by basrieter** [comment]
Changed it to >4 just to be sure.

**Comment by hermids** [comment]
Thanks @basrieter! I have tested it now and can also confirm it is working as expected, including TV4 Play.
