### ISSUE TITLE
Retrospect on Kodi v20 on Android runs fine 'once' and then gives a 'Retrospect error'

### ISSUE THREAD

**Issue by DrCheeks** [retrospect-addon/plugin.video.retrospect#1666]
Since Kodi v20 'Nexus' I have to reinstall Retrospect every day (or thereabouts).
It runs fine for a little while (about a day) and then it gives a 'Retrospect error'.
Removing Retrospect and reinstalling resolves the issue. Until it happens again the next day.

This happens on Kodi v20 running on Android (Nvidia Shield TV).
This happens in Kodi v20 beta-1 and RC1. (I just updated to RC2, so cannot comment on that yet.)
I did not have this issue in the same setup on previous Kodi versions.

Pls. find attached the retrospect.log
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/10267321/retrospect.log)

Many thanks, just grateful for all you hard work!

**Comment by basrieter** [comment]
Can you check the cookie file and see if it is actually corrupted? I never encountered this on Windows/Linux. Retrospect uses the `requests` library for all HTTPs stuff, so that "should" just work.

**Comment by DrCheeks** [comment]
As far as I can judge, the cookiejar.dat file is not corrupted. Not in a filesystem-kind-of-way, I mean. By that I mean I can open it and read its contents.

I don't know what the contents should be like, so don't know if it contains anything wrong. Only strange thing (to my eyes) it has a last line containing '3D%3D' (without the quotes).

To be sure: I checked this file file on the Nvidia Shield: '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.retrospect/cookiejar.dat'

Here is the file itself, maybe you see something strange.
NOTE: I myself removed (<snip>) the 2 tokens. Not sure if that matters, let me know. It seemed prudent.
[cookiejar.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/10268627/cookiejar.zip)

Thanks again!

**Comment by powermarcel10** [comment]
I'm having the same Issue with Kodi 20 rc1 using an Nvidia shield.

**Comment by basrieter** [comment]
Do the `3D%3D` in the cookiejar.dat belong to the previous line, or are they perhaps corrupting it?

**Comment by DrCheeks** [comment]
> Do the `3D%3D` in the cookiejar.dat belong to the previous line, or are they perhaps corrupting it?

The `3D%3D` really is on it own line, at least as per Notepad++
![image](https://user-images.githubusercontent.com/18447759/208727168-f80ad3c5-cd18-4fee-8cd7-e3a5dd9c6ba9.png)


> And can you tell me what you do to reproduce this? So step for step.

1. The cycle starts with a working Retrospect and for a while it works. It keeps working fine, also if I do some other Kodi stuff like wathcing a move, or  if switch to e.g. another app on Android (e.g. Youtube) and back to Kodi. (Note I do not really 'close' Kodi, I just leave it up to Android to manage running apps)
2. After about a day (perhaps Android quite Kodi in the background?) I will get the "Retrospect error" when staring the add-on. It is 'out of the blue'.
3. Then I uninstall Retrospect and then re-install Restrospect (all without quitting Kodi, or restarting Android or anything like that) and then it works again. Back to step 1.

I'm sorry I don't have anything more specific.

**Comment by basrieter** [comment]
What streams do you watch mostly? What channels?

**Comment by DrCheeks** [comment]
> What streams do you watch mostly? What channels?

The only channel we watch is "NPO Start".
(And then most often the recent episode of "Het Klokhuis", with the kids, but also other NPO programs.)

**Comment by basrieter** [comment]
It's just weird. I am going to look into it.

**Comment by DrCheeks** [comment]
Thanks Bas!

(As extra thanks I just made a donation. Even if this doesn't get resolved, I'm just grateful for all the time and effort you've put into Retrospect!)

**Comment by basrieter** [comment]
I created a small workaround that will just ignore the load error of the cookiejar file and save all cookies that had been loaded so far. Please try: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/issue-1666.zip

Use the "install from zip" option from Kodi Matrix.

**Comment by DrCheeks** [comment]
I've installed the workaround version, thanks! I will let you know if it 'misbehaves'...

And pls. let me know if there's anything more I can do. Try stuff out. Do some tests. Etc.

**Comment by basrieter** [comment]
> I've installed the workaround version, thanks! I will let you know if it 'misbehaves'...
> 
> And pls. let me know if there's anything more I can do. Try stuff out. Do some tests. Etc.

Just see if the problem is solved now. The fixed I added is just basically ignoring the error and saving those cookies that were not corrupted.

**Comment by DrCheeks** [comment]
Just writing to let you know all is good so far.
It's just 1 day of use, so it's nothing final. I did try some extra stuff ( hard-closing Kodi, restarting Android, etc.), but so far no more errors. Nice!
I'm on holiday for a week, so will not report back until next year :)

**Comment by basrieter** [comment]
Great! I am going to wait be bit and push a new Retrospect version soon.
