### ISSUE TITLE
Channel 9 is not streaming anymore.

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1667]
### Describe the bug

Channel 9 is not streaming anymore.

## Expected Behavior

Channel 9 is streaming items.

## Actual Behavior

Give an error to check the log files.

### To Reproduce

1.  Try any episode.
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
Retrospect log: https://paste.kodi.tv/pirinukaxu.kodi
Kodi log: https://paste.kodi.tv/owijizuduq.kodi

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:  19. 4 and 20 rc2
- Retrospect version: 5.5.11 and  bug-1663.zip

**Comment by basrieter** [comment]
I see. Let me fix that.

**Comment by basrieter** [comment]
Please try: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1667.zip

**Comment by matsarv** [comment]
The fix is working. Great work as always! Merry Christmas and Happy New Year.

**Comment by basrieter** [comment]
Thank you. I will push a new release soon.
