### ISSUE TITLE
NPOStart forward and backward issue with Kodi 20

### ISSUE THREAD

**Issue by ErikBrown2** [retrospect-addon/plugin.video.retrospect#1670]
### Describe the bug

After upgrading Kodi to version 20, NPOstart has an issue with forward and backward. I mean jumping forward and backward using the left and right arrow keys on the keyboard of my PC.  When I press the left arrow key (jump back) then the program will jump back a few seconds, as expected. The sound of the program will be heard immediately as usual. But the video will only be shown after several seconds. When the video is also shown, then the audio and video are correctly in sync. 

When I press the right arrow key (jump forwards) then the video jumps forward a few seconds as expected. The video is immediately shown as expected. But no audio is being heard. This behaviour is not 100% consistent but most of the time it happens this way. When I press again forward, then the the video freezes for a few seconds but the audio will be heard. After a few seconds both audio and video will be correct.
This behaviour is only seen with NPOstart programs, not with other channels.
EDIT: This behaviour is also seen on BVN.

## Expected Behavior

When I press forward or backward (using the arrow keys) then I expect that the program jump to the new position and within a very short time will play both audio and video.

## Actual Behavior

When I press forward or backward (using the arrow keys) then the program jumps correctly to the new position. When I jump backwards then the audio plays in a very short time as expected. But the video takes several seconds to appear. When it appears, it is in sync with the audio.
When I press forward, then the the program jumps correctly to the new position, plays the video as expected but the audio is not heard.

### To Reproduce

1. Upgrade Kodi to version 20
2. Start Retrospect - National - NPOstart - Recent - Yesterday - select any program
3. Wait for the program to start playing. Press forward (right arrow key)
4. Note that the video plays correctly but without sound.
5. Stop playing the program, start it again and press after a bit of time backward (left arrow key). Note that the video will take time
to appear while the audio is heard almost instantly.

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/ludotuzeyo

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 20
- Retrospect version: 5.5.12+matrix.1

**Comment by basrieter** [comment]
This is most likely cause by the new ffmpeg version. Not something I can fix. I merely call Kodi api's for playback.

**Comment by ErikBrown2** [comment]
Sorry that I have bothered you while it is not a Retrospect bug. To get it fixed, will you report this with the Kodi developers or shall I do that? In case you want me to do that, can you then please let me know in one or two sentences what the problem is?

**Comment by basrieter** [comment]
NP. You can always report it here: https://github.com/xbmc/inputstream.adaptive/issues or https://github.com/xbmc/xbmc/issues. I would suggest the first one.
