### ISSUE TITLE
NPO freezes after 2 minutes

### ISSUE THREAD

**Issue by rwynands** [retrospect-addon/plugin.video.retrospect#1675]
### Describe the bug

Version 5.5.13 works with NPO for only 2 minutes on Fire TV. After that it freezes.

## Expected Behavior

it should continue running

## Actual Behavior

stops after 2 minutes

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP
- [x] fire TV
Used versions:
- Kodi version: kodi matrix
- Retrospect version: 5.5.13

**Comment by basrieter** [comment]
In need a full DEBUG retrospect.log and kodi.log. Please attach the files, don't copy paste content.

**Comment by rwynands** [comment]
Sorry. I am just an amateur. Where do I find those files on a Firestick and how do I mobilize them for sending.

**Comment by basrieter** [comment]
https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Logging

**Comment by rwynands** [comment]
Ik heb de android kodi data folder op firestick gevonden, maar er zitten geen files in. Sent from my phoneOn Feb 7, 2023, at 00:53, Bas Rieter ***@***.***> wrote:﻿
https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Logging

**Comment by basrieter** [comment]
Je kunt het gewoon direct vanuit Retrospect zelf doen: even goed lezen:

![image](https://user-images.githubusercontent.com/1310443/217498749-2c3e1359-6a45-4c9a-8648-b00924a77366.png)

**Comment by ErikBrown2** [comment]
For a new user, to find how to send the log might take a bit of searching. The following is how you can do it:

Goto the configuration menu of Retrospect. You can do that from the Kodi add-on menu or from within Retrospect. 
To do it from within Retrospect, do the following (this assumes that you have connected a keyboard to the device on which you run Kodi. And my interface is in English,
you might have a different language set. Note that pressing C is not accepted in every state in the Retrospect menu. So if there is no reponse after pressing C, 
then try going up one level in the Retrospect menu and try again.):

Startup Retrospect - Press C on the keyboard - Select "Retrospect settings" - Select "Add-on Settings"

On the top of the screen shown here you see the tabs General, Channels, Channel settings and Advanced. Select Advanced.
Go down till you see in blue "Logging & Diagnostics". Under this you set LogLevel to Debug by using the up and down arrows next to it.

I am not sure if you have to restart Retrospect that this stage but you better do it to be sure. Now debug logging is enabled and you should perform
the steps that cause the problem that you want to report. After you did that, you go back into the settings menu of Retrospect:

Press C on the keyboard - Select "Retrospect settings" - Select "Add-on Settings"

On the top you see the tabs General, Channels, Channel settings, Advanced. Select Advanced.
Go down till you see in blue "Logging & Diagnostics". Under this you find the option "Send retrospect.log>>"
Select this option and the Retrospect log will be uploaded automatically to the Kodi server (assuming that your device is connected to the internet). You will then see a message like:

Logfile posted to: https://paste.kodi.tv/abcdefghij

Note down this full URL and mention it in a message here. Finally change the loglevel back to "Info". Below are some screenshots.


 
![image](https://user-images.githubusercontent.com/32511867/217592116-b64655ac-cab9-4a5e-b69f-85e0bd41432e.png)

![image](https://user-images.githubusercontent.com/32511867/217592388-9678e070-bd5f-4558-97d8-b3bc52c6af0c.png)

![image](https://user-images.githubusercontent.com/32511867/217593014-ff41ad34-abc7-4540-9594-621c9093d1da.png)

**Comment by rwynands** [comment]
Thank you. Is there a way without a keyboard, or is there a way to connect
a keyboard to a firestick?

**Comment by ErikBrown2** [comment]
I am not sure how to go to the settings menu within Retrospect without a keyboard. So I suggest that you go to the Retrospect settings menu from the Kodi menu. I use the Confluence skin on Kodi so it might be slightly different for you. 

Go to the Kodi menu option Add-ons  and then select:  My add-ons - Video add-ons - Retrospect - Configure

**Comment by rwynands** [comment]
Apologies for my ignorance, I figured it out now.
The url is: https://paste.kodi.tv/bunidoduwu
Thanks for your help.

**Comment by rwynands** [comment]
Do you have the information you need?

**Comment by basrieter** [comment]
I checked, but the log looks just fine. Also tried playback, which worked just fine here.

Can you provide  a kodi.log with debugging enabled? There is an addon that does that for you.

**Comment by rwynands** [comment]
https://paste.kodi.tv/azaqiguyuh

**Comment by basrieter** [comment]
![image](https://user-images.githubusercontent.com/1310443/218300282-1bf178c0-ac33-4f02-ba1c-2c7859734874.png)
Seems to be a network/stream thing, Are using the most recent Input Stream Adaptive add-on?

**Comment by rwynands** [comment]
input stream helper information:
Kodi version 19.4 is running on a Android system with arm architecture
InputStream Helper is at version 0.5.10+matrix1
InputStream Adaptive is at version 19.0.7

**Comment by rwynands** [comment]
I noticed that the issue does not occur when I do not use vpn. Using vpn was never an issue in earlier versions of Retrospect though.

**Comment by rwynands** [comment]
Even without VPN it eventually freezes though. It just takes longer before it occurs.

**Comment by basrieter** [comment]
It's a bandwidth issue. Limit that in Retrospect.

**Comment by rwynands** [comment]
When I go to the InputStream adaptive settings in Retrospect minimum and maximum bandwidth both show up as zero. What do I set them at instead?

**Comment by basrieter** [comment]
Start by limiting Retrospect (not input stream adaptive) to 2000 kbps. Retrospect will take care of the rest.

You can even just limit the NPO channel.

**Comment by rwynands** [comment]
I did as you said and put the max bitrate at 2000 in retrospect, but that did not help

**Comment by rwynands** [comment]
even 500, with a pretty awful resolution did not do the trick

**Comment by rwynands** [comment]
It must be something in combination with VPN (=Nord VPN), although I never had this issue before. I have a tv show running without VPN for half an hour now at bitrate setting 0 like before with no issue.

**Comment by basrieter** [comment]
so that is something I can't fix then.

**Comment by rwynands** [comment]
Yes, too bad. Hopefully I can find something to solve this, because combining Retrospect with VPN is important to me.

**Comment by basrieter** [comment]
I hope you can find a solution (other vpn?).

**Comment by rwynands** [comment]
Hallo Bas,
Mocht dit ooit terugkomen, de oplossing is bij NordVPN het connection
protocol op TCP te zetten ipv auto of NordLynx.
Nogmaals bedankt voor je hulp.
Robert
