### ISSUE TITLE
Sommige programma's van NPO start ontbreken in de lijst maar staan wel op de website van NPO start.

### ISSUE THREAD

**Issue by meiphoo7-Mae** [retrospect-addon/plugin.video.retrospect#1676]
### Describe the bug

Sinds enkele dagen missen er programma's in de NPOstart addon. Bijvoorbeeld dit programma: https://www.npostart.nl/zoeken?term=checkpoint+basecamp staat dus wel op NPO Start, maar ontbreekt ineens in de lijst van de addon.
Als je zoekt naar: https://www.npostart.nl/zoeken?term=cupcakecup, dan staat dat wel op NPO Start maar mist dat programma ook in de lijst van de addon.
Als je vervolgens in de zoekmachine in de zijbalk gaat zoeken dan weet Retrospect wel een lijstje met treffers te produceren.

## Expected Behavior

Een complete lijst  ;-)

## Actual Behavior

Een incomplete lijst zoals ik hierboven al beschreef.

### To Reproduce

Er zijn geen speciale handelingen nodig. Gewoon de genoemde programma's proberen te vinden in de lijst en het lijkt weg te zijn.

### Debuglog

The **debug** retrospect.log can be found here:

Ik heb niet de indruk dat er iets mis is dat tot een debug log kan leiden want de meeste programma's zijn er gewoon. Er gaat kennelijk iets mis met het samenstellen van de lijst.
### Screenshots 

Wel Checkpoint, geen Checkpoint Basecamp.

![screenshot00142](https://user-images.githubusercontent.com/95827976/218281735-9238f064-a3e7-4b9b-88b6-f21381e7969d.png)

Geen CupCakeCup in de lijst.

![screenshot00144](https://user-images.githubusercontent.com/95827976/218281939-78f2408e-264c-4caa-ada8-9383e8a869e5.png)

De zoekmachine in de zijbalk komt wel met resultaten.

![screenshot00143](https://user-images.githubusercontent.com/95827976/218282023-044173cf-30b3-470d-b28a-6d750e8e46be.png)

## Additional context or screenshots (if appropriate)

Ik heb twee voorbeelden gegeven die beide ontbreken in de 'C-lijst', maar dat is een kwestie van toeval. Ook sommige programma's die beginnen met andere letters ontbreken.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 20.0
- Retrospect version: 5.5.13+matrix.1

Dit is een nog verse installatie van Kodi van nog geen week oud.

**Comment by basrieter** [comment]
Het probleem is dat ze ook niet hier staan: https://www.npostart.nl/programmas?az=C

**Comment by meiphoo7-Mae** [comment]
Bedankt voor je antwoord. Ik heb er in elk geval weer iets van geleerd want ik wist niet dat die lijsten bestonden en dacht dat ze door Retrospect zelf werden gemaakt.
Ik moet toch eens naar de broncode van Retrospect gaan kijken...

Deze issue ga ik nu sluiten want NPO heeft de lijsten weer aangepast en de 'verdwenen' programma's staan er weer in.
