### ISSUE TITLE
KIJK.nl speelt (DRM protected) in browser maar...

### ISSUE THREAD

**Issue by BrodjagaRatnik** [retrospect-addon/plugin.video.retrospect#1677]
### Describe the bug

KIJK.nl speelt (DRM protected) afleveringen in browser (pc) maar niet als ik ze in retrospect wil afspelen.

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
http://paste.kodi.tv/yupayurasu

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 -  Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.5 (19.5.0) Git:19.5-Matrix
- Retrospect version: 5.5.13

**Comment by basrieter** [comment]
Did you install the correct and latest Widevine libraries?

**Comment by BrodjagaRatnik** [comment]
Yes, latest is from this week

**Comment by basrieter** [comment]
Can you provide a full bedug Kodi.log?

**Comment by BrodjagaRatnik** [comment]
https://paste.kodi.tv/miraroruwa.kodi

**Comment by BrodjagaRatnik** [comment]
Believe it's all Talpa that will not play since a couple of days.

**Comment by basrieter** [comment]
What episode are you trying to watch?

**Comment by BrodjagaRatnik** [comment]
"Vandaag Inside" I can see movies (not DRM protected) for the rest all episodes of programs the majority of kijk.nl are DRM protected and do not play

**Comment by basrieter** [comment]
They all work here. On Windows, Linux and RPi.

Please try to reinstall WideVine using the InputStream Adaptive helper add-on. It will download a ChromeOS image and extract WideVine from it on RPI. Or just find the most recent version for other Oases.

**Comment by BrodjagaRatnik** [comment]
Removed WideVine using the InputStream Adaptive helper add-on and installed WideVine using the InputStream Adaptive helper add-on this did not work.
Removed WideVine manually downloaded it from Google and copied to cdm directory this also did not work
Renoved again installed and reboted now DRM protected is running.

Ty

**Comment by basrieter** [comment]
The reboot was essential. Great that it works again.
