### ISSUE TITLE
NPO live and replay not playing (01-03)

### ISSUE THREAD

**Issue by chakubie** [retrospect-addon/plugin.video.retrospect#1679]
### Describe the bug

Exactly the same issue as 31-01: NPO livestreams and replay streams do not start..

### To Reproduce

1. 
2.
3.

### Debuglog

https://paste.kodi.tv/lifoparevu

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi-OSMC
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.5
- Retrospect version: 5.5.13

**Comment by VDK** [comment]
Retreaving the stream data at [line 94](https://github.com/retrospect-addon/plugin.video.retrospect/blob/master/resources/lib/streams/npostream.py#L94) needs to become a POST request instead of a GET. I dug through the NPO player javascript earlier today because my own code stopped working.

**Comment by ErjeMeij** [comment]
Hi, i am new here. Tryed to download #1679. Is not working. Where can i download this fie?

**Comment by basrieter** [comment]
it's already merged. Just download https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/master.zip and install it in Kodi Matrix or Nexus.

**Comment by Coenstegeman** [comment]
Hi Bas, is there still a fix possible for Leia, or is that no longer supported by now? Thanks in advance.

**Comment by basrieter** [comment]
For that you will have to wait for the official release. But I am waiting for #1680 and #1674 before creating one. BUT: that will be the last Leia version. I have a -1 version / +1 version support policy: We are at Kodi Nexus now. So only Matrix and Omega will be supported. 

I really suggest everyone to at least move to Matrix soon.

**Comment by Andrew-462** [comment]
The master.zip is working on Kodi Matrix, on my Windows 10 Desktop PC.

**Comment by udERAziEL7ib** [comment]
This master.zip has again fixed the npo start/plus problem.
Thanks again Bas for your quick response.!

**Comment by basrieter** [comment]
There should also be an official update in the Kodi repo now.

**Comment by ndoornhn** [comment]
For MACOS these files are working: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1851/1/artifacts/
