### ISSUE TITLE
Can't play Radio 538 video channel(s) but audio channels work fine

### ISSUE THREAD

**Issue by pquesinb** [retrospect-addon/plugin.video.retrospect#1685]
### Describe the bug

Audio content will play but video content will not.  Can't play 538 video stream or party stream.

## Expected Behavior

Video streams should play... they used to.

## Actual Behavior

Stream fails with no stream avaiilable / not found

## Possible Fix

Trying to watch from USA.  Are the video streams now GeoBlocked?  Log says no.

### To Reproduce

1.  Launch Retrospect
2.  Try to play Radio 538 video stream
3.  Experience disappointment when it fails

### Debuglog

The **debug** retrospect.log can be found here:
https://pastebin.com/70XZaMuw

## Additional context or screenshots (if appropriate)

Watch a 538 video stream

### Your Environment
Used Operating system:

CoreELEC v20 on ODroid-N2 - Retrospect v5.5.13
 - [ ] Android
 - [ ] iOS
 - [ x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 20.0 (20.0.0) Git:5c67bb4e24920ebf3a5d45a084d5b78f8cc97f3c. Platform: Linux ARM 32-bit
- Retrospect version: 5.5.13

**Comment by basrieter** [comment]
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1685.zip on Kodi Matrix/Nexus.

**Comment by pquesinb** [comment]
FIXED... works like a charm.  Thanks for the quick fix!
