### ISSUE TITLE
kodi 11 - NPO subtitles are accumulating

### ISSUE THREAD

**Issue by joopdo** [retrospect-addon/plugin.video.retrospect#1690]
### Describe the bug

I'm curious if others also have this issue with subtitles that stay on screen.

## Expected Behavior

This happened after upgrade. On the previous kodi version, the subtitles disappeared.

## Actual Behavior

Subtitles stay on screen.

### To Reproduce

1.  Open retrospect
2. Open a live stream (on demand works fine)
3. Subtitles appear, color red and keep piling (no removal)

### Screenshots 

![PXL_20230315_214642723](https://user-images.githubusercontent.com/1182449/225451405-a4081c55-9f90-4509-9d08-7c9ba21d4e84.jpg)

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 20.0
- Retrospect version: 5.5.14
- libreelec 11

![PXL_20230315_214642723](https://user-images.githubusercontent.com/1182449/225451405

**Comment by basrieter** [comment]
Ik heb het inderdaad ook al gezien. De subtitles worden helemaal gedaan via de InputStream Adaptive add-on (https://github.com/xbmc/inputstream.adaptive). Daar gaat er dus iets mis. Je zou het hun kunnen aangeven dat ze er eens naar kijken. Ik kan er vanuit Retrospect weinig mee. 

Je kunt natuurlijk altijd de ondertiteling uitzetten via de Kodi OSD.

**Comment by joopdo** [comment]
Hi @basrieter dank je wel voor je uitleg! Ga ik doen.
