### ISSUE TITLE
http.client.HTTPException: got more than 100 headers

### ISSUE THREAD

**Issue by maxruben** [retrospect-addon/plugin.video.retrospect#1695]
### Describe the bug

Most of the episodes in the Swedish TV4 TV-Show Robinson season 12 results in error when starting the episode.

## Expected Behavior

The episodes playing ok.

## Actual Behavior

Error instead of playing the episode.
Looking in the retrospect.log file I can see that http.client throws an exception with the message 'got more than 100 headers' when parsing the headers when opening the URL for the stream.

## Possible Fix

Allow more headers.

### To Reproduce

1. Go to season 12 of the Swedish TV-Show Robinson and play episode 1

### Debuglog

The **debug** retrospect.log can be found here: https://paste.kodi.tv/usipihotuk.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: LibreELEC 10.0.4 same on Windows 10
- Retrospect version: 5.5.14+matrix.1

**Comment by basrieter** [comment]
I need a complete debug logfile. Please enable debug logging in Retrospect. Then try playing the item again. Please post a link to the full logfile here. Don't modify or cut stuff out of it.

**Comment by maxruben** [comment]
Thanks, here is a log to a complete debug logfile from starting the rbpi to playing the episode that fails: https://paste.kodi.tv/qecunosine.kodi

**Comment by basrieter** [comment]
The server returned 100+ headers and Python does not like that. I bumped the limit. Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1695.zip via the Kodi "Install from zip" option in Kodi Matrix/Nexus.

**Comment by maxruben** [comment]
Wow, that was fast! It works!
Thanks a lot.

/Ruben

**Comment by basrieter** [comment]
Great! I will try to push an official update this week.
