### ISSUE TITLE
Kijk.nl werkt niet meer

### ISSUE THREAD

**Issue by ErikBrown2** [retrospect-addon/plugin.video.retrospect#1697]
### Describe the bug

The programs of Kijk.nl result in "One or more items failed to play. Check the log for more information about this message."

## Expected Behavior

That the programs play.

## Actual Behavior

The programs of Kijk.nl result in "One or more items failed to play. Check the log for more information about this message." And the program is not played.

### To Reproduce

1. Start up Retrospect, go to National - Kijk.nl - Recent - Yesterday 
2. Select any program and try to play it.
3.

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/miyiyaripi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 20.1 and 19.5
- Retrospect version: 5.5.14+matrix.1

**Comment by basrieter** [comment]
Laatste Widevine geprobeerd?

**Comment by ErikBrown2** [comment]
I re-installed Widevine using Inputstream Helper but this did not make a difference. The programs still do not play.

**Comment by basrieter** [comment]
I see where the issue lies. I will try to fix it.

**Comment by ErikBrown2** [comment]
That indeed fixed it. Thank you very much.

**Comment by basrieter** [comment]
I will do an official update soon.
