### ISSUE TITLE
TV4play doesn't play any content.

### ISSUE THREAD

**Issue by Geoplegatill** [retrospect-addon/plugin.video.retrospect#1699]
### Describe the bug

TV4play doesn't play any content.
It says that everything is Geo-Blocked, and every stream says it expired at the same time I enter the folder, and no stream can be played, says that there is no stream available for that object.
My IP is located in Sweden.

SVTplay and UR play works great, I actually prefer SVTplay in Retrospect instead of the Kodi version as you are able to rewind live content which Kodi SVTPlay can't.

But my issue is with TV4Play, that was the reason to start using Retrospect, to be able to play TV4 content.

No difference with TV4play account setup.

## Expected Behavior

Play TV4Play content

## Actual Behavior

See above

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: Latest (Matrix)
- Retrospect version: Latest

**Comment by basrieter** [comment]
Could you please attach a full DEBUG retrospect.log? Because I live outside Sweden, it's hard for me to verify the problem and a log could really help.

**Comment by Geoplegatill** [comment]
Yes, here's the debug.log
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/11110971/retrospect.log)

Row 565 and 1042:
`20230330 13:26:56 - [ERROR   ] - urihandler.py        - 555  - GET failed with '403 Forbidden' (0:00:00.270315) for https://playback2.a2d.tv/play/....`


Why does not the other SE channels get loaded?:
`20230330 13:26:40 - [WARNING ] - channelimporter.py   - 188  - Not loading: Kanal 5 (tv5json) [channel.se.sbs.tv5json=False, se=False, National, C72D24F6-5FAE-11E0-9935-5F41E0D72085] (Order: #se.0005) -> ignored in the channel set`

`20230330 13:26:40 - [WARNING ] - channelimporter.py   - 188  - Not loading: Kanal 9 (tv9json) [channel.se.sbs.tv9json=False, se=False, National, 32B4A9AB-583C-4F78-A057-6D79C797B45C] (Order: #se.0009) -> ignored in the channel set`

`20230330 13:26:40 - [WARNING ] - channelimporter.py   - 188  - Not loading: Kanal 11 (tv11json) [channel.se.sbs.tv11json=False, se=False, National, 64E1CA5E-BC3C-4763-9A63-02BE76754BD3] (Order: #se.0011) -> ignored in the channel set`

`20230330 13:26:40 - [WARNING ] - channelimporter.py   - 188  - Not loading: discovery+ (dplayse) [channel.se.sbs.dplayse=False, se=False, National, 230A2F56-572B-470B-AD53-AFD20A768D54] (Order: #se.0007) -> ignored in the channel set`

`20230330 13:26:40 - [WARNING ] - channelimporter.py   - 188  - Not loading: TV4 (tv4se) [channel.se.tv4se.tv4se=False, se=False, National, 98506F58-CD6F-11DE-99BA-187F55D89593] (Order: #se.0004) -> ignored in the channel set`

`20230330 13:26:40 - [WARNING ] - channelimporter.py   - 188  - Not loading: Sjuan (tv7se) [channel.se.tv4se.tv7se=False, se=False, National, 66174057-D5E3-4102-AF46-B2D8E800E0D9] (Order: #se.0007) -> ignored in the channel set`

`20230330 13:26:40 - [WARNING ] - channelimporter.py   - 188  - Not loading: TV12 (tv12se) [channel.se.tv4se.tv12se=False, se=False, National, F2D31759-71BD-4DD1-A1FB-FF8FD99CE03E] (Order: #se.0012) -> ignored in the channel set`

**Comment by basrieter** [comment]
Thanks, I will have a look.

The other Swedish channels either don't exist anymore (some merged in to a single channel) and some just broken or do no longer exist.

**Comment by Geoplegatill** [comment]
I guess you can stop looking, I was behind a VPN/Proxy and TV4play didn't like that. Without VPN it works.
All streams still says Geo-Blocked thou, but as long as they work it doesn't matter.

**Comment by basrieter** [comment]
Great! `Geo-blocked` means that they can only be viewed in the geografical region it was intended for.
