### ISSUE TITLE
NPO: bij sommige series ontbreken de laatste afleveringen

### ISSUE THREAD

**Issue by PhyxionNL** [retrospect-addon/plugin.video.retrospect#1701]
### Describe the bug
Bij NPO ontbreken bij sommige series de laatste afleveringen in de lijst. 
Als voorbeeld: https://www.npostart.nl/met-het-mes-op-tafel/POW_03108559/overview
In Retrospect ontbreken alle afleveringen na 02-03-23.

### To Reproduce

1. Open NPO.
2. A-Z lijst > M > Met het mes op tafel.
3. De laatste aflevering is nu 20x16.
4. Op de site (https://www.npostart.nl/met-het-mes-op-tafel/POW_03108559/overview) is al 20x24 te zien.

### Debuglog
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/11289769/retrospect.log)

### Screenshots 

![image](https://user-images.githubusercontent.com/7643972/233469632-e1806ad9-33e5-4988-b5af-0118732921cd.png)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 20.0 en 20.1.
- Retrospect version: 5.6.0.

**Comment by basrieter** [comment]
Is it just this show, or more shows?

**Comment by PhyxionNL** [comment]
Volgens mij was nog één die het had, dat was ook bij een serie met (heel) veel afleveringen.

**Comment by basrieter** [comment]
Probleem ligt bij NPO: De API geeft het verkeerde seizoensnummer mee in de API (19 ipv 20): 

![image](https://user-images.githubusercontent.com/1310443/233808526-d98907e4-cf9c-4f0f-b17e-7b9923ac5210.png)

![image](https://user-images.githubusercontent.com/1310443/233808544-4c5e11ec-a0f8-4fc9-bc7a-76b7003c41ae.png)

![image](https://user-images.githubusercontent.com/1310443/233808515-b6a5dfd6-8130-4cd4-a519-f04d481494e2.png)

Dat zou eigenlijk seizoen 20 moeten zijn: 

![image](https://user-images.githubusercontent.com/1310443/233808600-65230b2d-7bd2-487a-9a1c-5ee97f324477.png)

Verwarrend, maar niet iets dat ik kan fixen dus. NPO moet dat goed doorgeven. Probleem daarbij is dat ze waarschijnlijk er waarschijnlijk geen boodschap aan hebben dat het via Kodi verkeerd wordt getoond. Sterker nog: wellicht vinden ze het kijken via Kodi helemaal niet leuk?

**Comment by PhyxionNL** [comment]
Hmm, ik zie het ja, ze staan er wel in veel verder naar beneden in de lijst, was mij niet opgevallen met zoveel afleveringen. Vreemd dat ze op de site dit wel bij het juiste seizoen hebben staan (2023). Ze gebruiken op de site deze URL voor de afleveringen per seizoen (per seasonId: https://www.npostart.nl/media/series/POW_03108559/episodes?seasonId=POW_05515817&tileType=asset&tileMapping=dedicated&useJson=true&pageSize=25). Hier staan ze dan wel correct in, maar dat zal wel een andere API zijn die Retrospect gebruikt denk ik?
Ik had het nog even opgezocht en tussen kunst en kitsch heeft er ook last van. Op datum sorteren werkt wel goed.

**Comment by basrieter** [comment]
NPO baseert het seizoen op de POW-id van dat seizoen, niet het nummer. Kennelijk gaat dat dus soms fout. 

> https://www.npostart.nl/media/series/POW_03108559/episodes?seasonId=POW_05515817&tileType=asset&tileMapping=dedicated&useJson=true&pageSize=25

Dit end-point is echt een website end-point: er komt gewoon HTML terug in de JSON. Ik gebruik de mobile API. Daarin komt alles gewoon netjes terug, maar gaat er dus soms wat fout met o.a. het seizoen.

**Comment by PhyxionNL** [comment]
Het is wel apart dat daar verschil in zit. Ik heb net even de app geïnstalleerd (gebruik ik normaal nooit) en daar gaat het ook goed; ze staan daar ook keurig onder seizoen 2023 🤔

![image](https://user-images.githubusercontent.com/7643972/233841491-463457f9-5f0a-4f13-9a15-9b6924218431.png)

Het is niet zo erg omdat op datum sorteren wel werkt, ik dacht eerst dat ze helemaal ontbraken 😄

**Comment by basrieter** [comment]
Zelfs verhaal: daar laten ze de seizoensnummers ook niet zien. Enkel de namen. Vandaar dat het daar ook gewoon goed gaat. Wat je in Retrospect ziet is ook gewoon 1 seizoen. Maar daar zit dus gewoon een probleem met de nummering in de api.

**Comment by PhyxionNL** [comment]
Ah, zo 🙂 Dan sorteren we gewoon op datum 👍
