### ISSUE TITLE
RTV-Drenthe streams are not playing voor some weeks

### ISSUE THREAD

**Issue by PA0RWE** [retrospect-addon/plugin.video.retrospect#1702]
### Describe the bug

For some weeks RTV-Drenthe is not playing streams. Error message: Playback cannot be started

## Expected Behavior

Stream should be played

## Actual Behavior

When I select a stream, I have got an error: Playback cannot be started

## Possible Fix

Up to you...

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
https://www.dropbox.com/s/q745ggvn9hzp8oc/retrospect.log?dl=0

### Screenshots 

![afbeelding](https://user-images.githubusercontent.com/130929248/235139585-858e0eb5-7f2d-4f66-9283-351ec3368fc5.png)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ x ] Linux
 - [ ] OSX
 - [x ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 20.1.0
- Retrospect version:  5.5.14+matrix.1

**Comment by basrieter** [comment]
That is correct. I recently fixed that, see https://github.com/retrospect-addon/plugin.video.retrospect/commit/d159baf387ff4d9b74aa9ccd090396d82be3bfa2

I just did not get into releasing a new version.

You can always manually install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/master.zip in Kodi Matrix or newer.

Let me know is that solved your issue. I will try to release a new version soon.
