### ISSUE TITLE
RTL XL navigation not working properly since update 5.6.0 to 5.6.2

### ISSUE THREAD

**Issue by didamsko** [retrospect-addon/plugin.video.retrospect#1708]
### Describe the bug

Navigation RTL XL mixed up since  update 5.6.0 to 5.6.2. Since update the "Recent" option is no longer functioning properly and the "opening screen" is changed; all "Titles with ..." are gone. Also starting to play a RTL XL item on 5.6.2 generates a "Login Failed" message but when clicking OK the item does start to play.

This happens to me while using Kodi Nexus 20.1 on CoreELEC ODROID and Kodi for Windows portable. See debug log and screenshots below.

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

https://paste.kodi.tv/sogewedudu.kodi

### Screenshots 

screenshots Retrospect 5.6.0, usual "opening screen" and opened recent listing:

![rtlxl-5 6 0-1](https://github.com/retrospect-addon/plugin.video.retrospect/assets/60958082/0ea417a4-e099-4b0b-8502-6f600cc4efbf)
![rtlxl-5 6 0-2](https://github.com/retrospect-addon/plugin.video.retrospect/assets/60958082/0729c286-448c-48ef-aeee-10e8a80ada3b)

screenshots Retrospect 5.6.2, "opening screen" without the "Titles with ..." and attempt to access recent listing resulting in error, and a "Login Failed" error message:

![rtlxl-5 6 2-1](https://github.com/retrospect-addon/plugin.video.retrospect/assets/60958082/420edb0f-9ccf-4eb6-a8cd-d09d445d707c)
![rtlxl-5 6 2-2](https://github.com/retrospect-addon/plugin.video.retrospect/assets/60958082/e136f588-b8fe-4bee-94a6-54b4312c6a48)
![rtlxl-5 6 2-3](https://github.com/retrospect-addon/plugin.video.retrospect/assets/60958082/7906c621-2a40-46bd-8f78-636b97f12ba8)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 20.1
- Retrospect version: 5.6.2

**Comment by basrieter** [comment]
- The title listing is just a Retrospect setting  to Group them if they exceed a certain number. The RTL XL list is so short due to the retiring of RTL XL soon. So it won't be grouped.
- I guess I can re-add the broadcast time.
- The listing error for "eergisteren" I can fix.

Regarding the log-in error. If you configure your RTL XL account it will all be OK. But I don't know if it is required at all to log in.

**Comment by basrieter** [comment]
RTL XL really limited their API. But please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1708.zip using the "Install from zip"  and see if it fixes your finding?

**Comment by laurensV** [comment]
Regarding the retirement of RTL XL: Will there be a possibility to use the new feature through videoland called "TV gemist", where people can still watch content up to 7 days with ads for free? https://help.rtlxl.nl/hc/nl/articles/11171036914450-Wat-is-TV-Gemist-

**Comment by basrieter** [comment]
> Regarding the retirement of RTL XL: Will there be a possibility to use the new feature through videoland called "TV gemist", where people can still watch content up to 7 days with ads for free? https://help.rtlxl.nl/hc/nl/articles/11171036914450-Wat-is-TV-Gemist-

Of course, I will be looking into that :)

**Comment by didamsko** [comment]
> RTL XL really limited their API. But please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1708.zip using the "Install from zip" and see if it fixes your finding?

Thanks!, the "Recent" listing is working again as before and also thanks for re-adding the broadcast times. Would this also be possible on the "KIJK" "Recent" listings? 

The log-in error also is gone. I never used the RTL XL account. Still miss the "Titles with ..." index that still works when using 5.6.0 but no use investing time on that when RTL XL is going to stop. 

I second the wish for adding TV Gemist to still be able to access the RTL content up to 7 days :)

**Comment by basrieter** [comment]
> The log-in error also is gone. I never used the RTL XL account. Still miss the "Titles with ..." index that still works when using 5.6.0 but no use investing time on that when RTL XL is going to stop.

You need to configure it in the add-on settings: 

![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/1310443/fdd00bce-82db-415b-b334-7979cfe8ffa3)

The `Group list if exceeds....` option.

**Comment by didamsko** [comment]
Thanks! Had it set on 200. Now set to 10 and the "Titles with ..." index is back.

**Comment by didamsko** [comment]
Some noticeable differences between how the "Titles with ..." index functions between versions 5.6.0 and 5.6.2. 

5.6.0 shows more programs, seasons and also lists free and paid episodes with episode specific description: 

![5 6 0-1-programs](https://github.com/retrospect-addon/plugin.video.retrospect/assets/60958082/a595792b-a567-4c74-adab-28d56338f922)
![5 6 0-2-seasons](https://github.com/retrospect-addon/plugin.video.retrospect/assets/60958082/c7b5c675-b985-47f3-a0be-a52298f4b340)
![5 6 0-3-episodes](https://github.com/retrospect-addon/plugin.video.retrospect/assets/60958082/c813c3b8-c816-4fee-91d9-e7b8dc476ad3)

5.6.2 shows less programs but has several double listings and only shows free episodes (with Retrospect set to show paid items), and also the episodes do not have a episode specific description anymore: 

![5 6 2-1 programs](https://github.com/retrospect-addon/plugin.video.retrospect/assets/60958082/97a04a9c-f2d4-475a-9aac-0fdfbf49224d)
![5 6 2-2-episodes](https://github.com/retrospect-addon/plugin.video.retrospect/assets/60958082/be81c831-ffff-45b3-a4c1-eb88d831200e)

**Comment by basrieter** [comment]
- The paid items were all moved to Videoland, and just don't appear in the RTL XL API anymore (check the lists from the RTL XL site). 
- Well spotted regarding the duplicate items. I fixed the duplication (it was present in all channels). 
- The descriptions is just how it comes from the API. Look at GTST, there they are correct. So that I can't fix.

**Comment by didamsko** [comment]
Thanks for the continuing support!, the doubles are gone: 

![plugin video retrospect-5 6 2-bug-1708-FIXED](https://github.com/retrospect-addon/plugin.video.retrospect/assets/60958082/576bdc6f-b0d6-49f0-8dd2-3bdb32d0e3e2)

Issue can be closed then i think. Curious to go see when RTL XL will stop.

**Comment by basrieter** [comment]
Great! I will push an update to the Kodi repo soon.
