### ISSUE TITLE
RTLZ programs give Api content error  or no time frame on content. 

### ISSUE THREAD

**Issue by Gjaltz** [retrospect-addon/plugin.video.retrospect#1710]
### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:
- Retrospect version:

**Comment by basrieter** [comment]
Please provide a  full debug retrospect.log as attachement (enable debugging in retrospect, reproduce). Then either fetch the logfile, or upload it and post the link: https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Logging

**Comment by Gjaltz** [comment]
2023-06-14 21:28:50.417 T:5288     info <general>: Retrospect :: Additional logging can be found in 'C:\Users\gzwaagstra\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.retrospect\retrospect.log'
2023-06-14 21:28:50.490 T:5288    error <general>: C:\Users\gzwaagstra\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.rtl.nl'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
                                                     warnings.warn(
                                                   
2023-06-14 21:28:50.519 T:11732   error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.retrospect/?channel=channel.rtlnl.rtl&action=playvideo&pickle=A8E7BFDBCC8A5AD517290C0ACAEEF893B789669994C61C0A4FB77BACFC2F56CB--0EE476E7626EEBBC57D12A3AC9002668EBF6AE6591B9EB47D7FF304EA13FFEA0]
2023-06-14 21:28:50.519 T:25272    info <general>: CActiveAESink::OpenSink - initialize sink

**Comment by Gjaltz** [comment]
oorlog in de keuken

**Comment by basrieter** [comment]
> 2023-06-14 21:28:50.417 T:5288 info : Retrospect :: Additional logging can be found in 'C:\Users\gzwaagstra\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.retrospect\retrospect.log' 2023-06-14 21:28:50.490 T:5288 error : C:\Users\gzwaagstra\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.rtl.nl'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings warnings.warn(
> 
> 2023-06-14 21:28:50.519 T:11732 error : Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.retrospect/?channel=channel.rtlnl.rtl&action=playvideo&pickle=A8E7BFDBCC8A5AD517290C0ACAEEF893B789669994C61C0A4FB77BACFC2F56CB--0EE476E7626EEBBC57D12A3AC9002668EBF6AE6591B9EB47D7FF304EA13FFEA0] 2023-06-14 21:28:50.519 T:25272 info : CActiveAESink::OpenSink - initialize sink

Please, upload a full debug log. I really, really need all the information in it.

**Comment by Gjaltz** [comment]
[kodi.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/11749933/kodi.log)

**Comment by Gjaltz** [comment]
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/11750310/retrospect.log)

**Comment by Gjaltz** [comment]
[retrospect.old.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/11750321/retrospect.old.log)

**Comment by Gjaltz** [comment]
[retrospect.old.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/11750322/retrospect.old.log)

**Comment by basrieter** [comment]
Thanks! But these contain no debug level info. Please follow the wiki: 

![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/1310443/e164de18-3088-4cf8-b410-4ad9ac9fdaee)

**Comment by Gjaltz** [comment]
Problem is on all Kodi systems RTLZ seems to be blocked.

**Comment by basrieter** [comment]
But I still need the debug info I asked for.

**Comment by Gjaltz** [comment]
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/12346736/retrospect.log)
de debug log

**Comment by Gjaltz** [comment]
There is a free watchback service but you must login for that. Is now redirected to videoland

**Comment by basrieter** [comment]
I looked, but can't find a free service for Videoland.

**Comment by Gjaltz** [comment]
only 7 days are free https://v2.videoland.com/rtl-weer-p_3273/rtl-weer-19-55-14-08-23-c_50281

**Comment by basrieter** [comment]
Videoland was implemented. See #1724
