### ISSUE TITLE
NPO start live streams get unspecified error

### ISSUE THREAD

**Issue by rmellema** [retrospect-addon/plugin.video.retrospect#1713]
### Describe the bug

I’m trying to play the NPO live streams from within Sweden. If I remember correctly this worked fine in the past (used it for the top 2000 in 2020), but now it gives and unspecified error retrieving streams. The stream will then also not play.

## Expected Behavior

I expect when I select one of the live streams that it would play. Or if that’s no longer allowed due to geolocation, a more specific error.

## Actual Behavior

Restrospect throws an error “unspecified error retrieving streams”

### To Reproduce

1. Be in Sweden
2. Select the NPO live streams
3.

### Debuglog

The **debug** retrospect.log can be found here:
HTTPS://paste.kodi.tv/ihajehodiy

## Additional context or screenshots (if appropriate)

The Radio live streams all seem to work, but the TV live streams don’t.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi, LibreELEC 11.0.1
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 20.1.0
- Retrospect version: 5.6.4

**Comment by basrieter** [comment]
It has to do with the current sport events (Tour de France, etc) for which NPO only has rights in The Netherlands. That is why you cannot watch live streams abroad at the moment. 

So I cannot fix it. I did fix the error handling and it should now show a proper message again. You can manually install it via https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1713.zip. As this is not a high prio fix, it will be include in the next future update.
