### ISSUE TITLE
No EPG data from Retrospect

### ISSUE THREAD

**Issue by Ctheman** [retrospect-addon/plugin.video.retrospect#1717]
### Describe the bug

Error on retrieving EPG data

## Expected Behavior

When an request for EPG data is send, no data is received.

## Actual Behavior

Retrospect gives a error

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here: https://paste.kodi.tv/ewigokolez

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] CoreElec
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:
- Retrospect version:

**Comment by basrieter** [comment]
I see the issue. Let me fix it.

**Comment by basrieter** [comment]
Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1717.zip via the "Install from zip", reboot Kodi and see if it works.

**Comment by Ctheman** [comment]
Works, info is coming in, thanks.
