### ISSUE TITLE
SVT Play no listing

### ISSUE THREAD

**Issue by dobbelina** [retrospect-addon/plugin.video.retrospect#1718]
## Bug report
Since this morning SVT Play no listing regardless of link used, debug log made.
### To Reproduce

1. 
2.
3.

### Debuglog

https://paste.kodi.tv/koramaqaqi.kodi

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 20.2
- Retrospect version: 5.6.4

**Comment by basrieter** [comment]
The api was updated.

**Comment by basrieter** [comment]
Please try this version via the "install from zip" option: 

https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1718.zip

Most stuff should be working, except tags/genres and perhaps the search.

**Comment by dobbelina** [comment]
@basrieter 
Fix works, thank you.

**Comment by matsarv** [comment]
In the initial fix I found a few things that didn't work:
- Categories
- Genres\tags (mentioned above)
- Live TV (This is working in version 5.6.4)
- Öppet arkiv
- Search (mentioned above)

- 'Currently playing' needs the time before title so we don't trying to play a program in the future. Right now there is 13 'Rapport' in the list. I think it used to be like this:  '18:00 - Rapport'

**Comment by basrieter** [comment]
> In the initial fix I found a few things that didn't work:
> 
> * Categories
> * Genres\tags (mentioned above)
> * Live TV (This is working in version 5.6.4)
> * Öppet arkiv
> * Search (mentioned above)
> * 'Currently playing' needs the time before title so we don't trying to play a program in the future. Right now there is 13 'Rapport' in the list. I think it used to be like this:  '18:00 - Rapport'

Those are more or less the ones I mentioned in my post.

**Comment by basrieter** [comment]
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1718.zip again. I think it is all working again: 2 notes:

1. The "All Genres/Tags" was removed from their API (can't find it) so the listing is not as long as it was.
2. The "Currently playing" thing with the time won't work with the time in front, as it might also be that time day after. 

Only thing left is the "Live streams".

**Comment by basrieter** [comment]
Live streams fixed: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1718.zip

Please verify, as I can't really from the Netherlands.

**Comment by matsarv** [comment]
I have tested all first level folders and some Categories folders and eveything is working.

---------------------------------------------------------------------

I have found a couple of things that could be enhanced.
I think Categories is rather important for the look and feel.

---------------------------------------------------------------------

<details><summary>Categories</summary>
<p>

If you goto Categories and select Drama, 
all Singels and TVSeries are missing the image and fanart.

![categories-images](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46671821/70ce1afa-761d-4d72-b6a0-e2d6479da42c)


On the next level in TVSeries the image and fanart are shown for the folders (Klipp, Sasong x and Upptäck mer) 


![categories-images2](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46671821/f642034d-0856-4bb6-8ddd-0bfbd02dc9ad)


The info for this seems to be extracted from the API.
I guess this could also be applied for Genres/tags

```
Single:

20230911 11:46:55 - [TRACE   ] - chn_svt.py           - 418  - Single: {'id': '1403983-001', 'name': 'At the Window', '__typename': 'Single', 'urls': {'svtplay': '/video/KZm7rmd/at-the-window', '__typename': 'Urls'}, 'oppetArkiv': False, 'restrictions': {'onlyAvailableInSweden': False, 'onlyAvailableInSwedenFormatted': 'Kan ses i hela världen', '__typename': 'Restrictions'}, 'svtId': 'KZm7rmd', 'videoSvtId': 'jpAdZzp', 'images': {'cleanWide': {'changed': 1686741501, 'description': 'At the Window - En flicka står vid fönstret och blickar ut över den snötäckta trädgården utanför. Bakom henne ligger hennes sjuka mamma i sin säng. När en otäck varelse dyker upp i trädgården suddas gränsen mellan dröm och verklighet ut.', 'id': '50073851', 'keyart': False, '__typename': 'Image'}, 'logotype': None, 'cleanPortrait': {'description': 'At the Window - En flicka står vid fönstret och blickar ut över den snötäckta trädgården utanför. Bakom henne ligger hennes sjuka mamma i sin säng. När en otäck varelse dyker upp i trädgården suddas gränsen mellan dröm och verklighet ut.', 'changed': 1686741501, 'id': '50073855', 'keyart': False, '__typename': 'Image'}, '__typename': 'Images'}, 'parent': {'id': '1403983-001', 'name': 'At the Window', 'svtId': 'KZm7rmd', 'images': {'wide': {'changed': 1686741500, 'id': '50073843', 'description': 'At the Window - En flicka står vid fönstret och blickar ut över den snötäckta trädgården utanför. Bakom henne ligger hennes sjuka mamma i sin säng. När en otäck varelse dyker upp i trädgården suddas gränsen mellan dröm och verklighet ut.', '__typename': 'Image'}, 'cleanWide': {'changed': 1686741501, 'description': 'At the Window - En flicka står vid fönstret och blickar ut över den snötäckta trädgården utanför. Bakom henne ligger hennes sjuka mamma i sin säng. När en otäck varelse dyker upp i trädgården suddas gränsen mellan dröm och verklighet ut.', 'id': '50073851', 'keyart': False, '__typename': 'Image'}, 'logotype': None, 'cleanPortrait': {'description': 'At the Window - En flicka står vid fönstret och blickar ut över den snötäckta trädgården utanför. Bakom henne ligger hennes sjuka mamma i sin säng. När en otäck varelse dyker upp i trädgården suddas gränsen mellan dröm och verklighet ut.', 'changed': 1686741501, 'id': '50073855', 'keyart': False, '__typename': 'Image'}, '__typename': 'Images'}, 'urls': {'svtplay': '/video/KZm7rmd/at-the-window', '__typename': 'Urls'}, '__typename': 'Single'}, 'validFrom': '2023-06-30T02:00:00+02:00', 'validFromFormatted': 'Fre 30 jun 02:00', 'duration': 461, 'variants': [{'accessibility': 'Default', 'urls': {'svtplay': '/video/jpAdZzp/at-the-window', '__typename': 'Urls'}, '__typename': 'Variant'}], 'accessibilities': []}

```


```
TVSeries:

20230911 11:46:55 - [TRACE   ] - chn_svt.py           - 418  - TvSeries: {'id': 'eopv56n', 'name': 'Atlantic crossing', '__typename': 'TvSeries', 'urls': {'svtplay': '/atlantic-crossing', '__typename': 'Urls'}, 'oppetArkiv': False, 'restrictions': {'onlyAvailableInSweden': True, 'onlyAvailableInSwedenFormatted': 'Kan bara ses i Sverige', '__typename': 'Restrictions'}, 'svtId': 'eopv56n', 'videoSvtId': 'jnDJZE6', 'images': {'cleanWide': {'changed': 1686136164, 'description': 'Kronprins Olav (Tobias Santelmann), kronprinsesse Märtha (Siofia Helin) och president Franklin D. Roosevelt. - Atlantic crossing', 'id': '29701314', 'keyart': True, '__typename': 'Image'}, 'logotype': None, 'cleanPortrait': {'description': 'Kronprins Olav (Tobias Santelmann), kronprinsesse Märtha (Siofia Helin) och president Franklin D. Roosevelt. - Atlantic crossing', 'changed': 1686136159, 'id': '29756634', 'keyart': True, '__typename': 'Image'}, '__typename': 'Images'}, 'parent': {'id': 'eopv56n', 'name': 'Atlantic crossing', 'svtId': 'eopv56n', 'images': {'wide': {'changed': 1686136164, 'id': '29701314', 'description': 'Kronprins Olav (Tobias Santelmann), kronprinsesse Märtha (Siofia Helin) och president Franklin D. Roosevelt. - Atlantic crossing', '__typename': 'Image'}, 'cleanWide': {'changed': 1686136164, 'description': 'Kronprins Olav (Tobias Santelmann), kronprinsesse Märtha (Siofia Helin) och president Franklin D. Roosevelt. - Atlantic crossing', 'id': '29701314', 'keyart': True, '__typename': 'Image'}, 'logotype': None, 'cleanPortrait': {'description': 'Kronprins Olav (Tobias Santelmann), kronprinsesse Märtha (Siofia Helin) och president Franklin D. Roosevelt. - Atlantic crossing', 'changed': 1686136159, 'id': '29756634', 'keyart': True, '__typename': 'Image'}, '__typename': 'Images'}, 'urls': {'svtplay': '/atlantic-crossing', '__typename': 'Urls'}, '__typename': 'TvSeries'}, 'accessibilities': []}

```

</p>
</details>

<details><summary>Currently playing </summary>
<p>

Currently playing looks like this 

![CurrPlay1](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46671821/7b914e30-2cba-4395-8d2e-c38e508c6b98)


In the def create_api_teaser_type(self, result_set):
remark the following:

```
Row 579

from:
            if self.parentItem.metaData.get(self.__filter_subheading, True) and (
                    "Idag" in sub_heading
                    or "Ikväll" in sub_heading
                    or "Igår" in sub_heading
                    or sub_heading.endswith(" sek")
                    or sub_heading.endswith(" min")
                    or sub_heading.endswith(" tim")):
                Logger.trace("Ignoring subheading: %s", sub_heading)
                new_result_set["name"] = title
to:
            # if self.parentItem.metaData.get(self.__filter_subheading, True) and (
                    # "Idag" in sub_heading
                    # or "Ikväll" in sub_heading
                    # or "Igår" in sub_heading
                    # or sub_heading.endswith(" sek")
                    # or sub_heading.endswith(" min")
                    # or sub_heading.endswith(" tim")):
                # Logger.trace("Ignoring subheading: %s", sub_heading)
                # new_result_set["name"] = title
```

Now Currently playing looks like this, with info when the show is available.


![Currplay2](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46671821/08077af0-5d45-4055-9355-fd9f345ef680)


</p>
</details>


</p>
</details>

<details><summary>Live TV </summary>
<p>


Live TV looks like this 

![LiveTV1](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46671821/62420076-e0f6-44f6-94a6-4013c85159c9)


Live TV in version 5.6.4 still works and it looks like this.

![LiveTV2](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46671821/6831be1e-3fef-4b15-85be-db58dae1ffe5)

In the above all images is fetched from the API even when no show is playing. 

Maybe you could add the end time to the latest working and it is fixed.

</p>
</details>

---------------------------------------------------------------------

All is working and this is just enhancement if you got the time.
Greate work! Thanks for all the hard work fixing this to us.

**Comment by basrieter** [comment]
Thanks for your feedback: 

* Currently Playing: Fixed (forgot something)
* Live TV: End times are no longer present in the API. But I managed to get one by reading the next item in the list.
* Live TV: Thumbs are not always present. But most have them.

I will have a look at the artwork in general.

**Comment by basrieter** [comment]
Please redownload https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1718.zip and see if it is better now?

**Comment by matsarv** [comment]
This is the image from Categories and Drama using Viewtype: Wall

![Drama_1](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46671821/8ffe7f66-1444-489a-ae76-5dcb68be9a44)

The poster images only seems to work on Movies,
As for Series, text don't fit, text is missing, so you don't allways see the name.

![Drama2](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46671821/33c1590c-3acd-4ff9-9b2e-95cad952be6d)

Before you used the format image and there was the name of the shows allways  visible.
I guess the image used in TVSeries show folder is the best option.

My guess is that the posters are not ready to use everyware yet.

**Comment by basrieter** [comment]
The thumbs/poster are generated using their own API and the JSON data they send. They apparently cut of text: 

https://www.svtstatic.se/image/portrait/1080/36820195/1686132923

**Comment by matsarv** [comment]
For the thumbs: use image/custom instead of image/portrait

https://www.svtstatic.se/image/custom/430/36820195/1686132923
https://www.svtstatic.se/image/custom/720/36820195/1686132923
https://www.svtstatic.se/image/custom/1080/36820195/1686132923

**Comment by basrieter** [comment]
> For the thumbs: use image/custom instead of image/portrait
> 
> https://www.svtstatic.se/image/custom/430/36820195/1686132923 https://www.svtstatic.se/image/custom/720/36820195/1686132923 https://www.svtstatic.se/image/custom/1080/36820195/1686132923

But then they won't be "portrait" format and Kodi will "squeeze" them:
![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/1310443/ee0e6619-d2ea-4179-a232-fc4132b9daaa)

**Comment by basrieter** [comment]
This is what a poster should be: 

![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/1310443/de26187f-bba7-489c-81ca-c793241574a0)

**Comment by matsarv** [comment]
When listing all the Category / Series on the website it uses the custom image
https://www.svtplay.se/kategori/serier?tab=all

When listing the TVshow, the foldes Säsong, Klipp and Upptäck mer uses the custom image
https://www.svtplay.se/atlantic-crossing
 
If I remember correctly, posters (portraits) in previously Retrospect were never used in SVT Play.
If possible, custom images should be used and maybe the media type needs to be changed where the custom images are squeezed.

I've been trying to figure out where to make these changes to the code to test this but haven't yet found where. Can you share the code used for the above picture and where to change the thumb images (squeezed) just for testing?

Any image in better the no image so don't let this be a stopper for the upcoming release.

**Comment by matsarv** [comment]
I have gone back and dowloaded the version up to the fix:
Changed: SVT Live and Currently Playing tweaks.

I have tested this version and everything is working as before the API changes.
It looks perfect except for one thing as mentioned.


- Open 'Categories' and goto 'Drama'.

![Categories](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46671821/d728ec0f-a28e-431c-b1d7-a844b6b05b69)

- See the images used for the folder 'Drama'
- Open 'Drama' folder


![CategoriesDrama](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46671821/f8773a27-d9af-4533-8ab8-b012662337c7)

Both Singles items and TVSeries Folders is using the parent info from 'Drama'.
The foldes below this is working OK.

![CategoriesDramaAtlantic](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46671821/92afc831-06d7-4a6e-b75c-e07715d033cb)


The only thing needs to be fixed is that Singels and TVSeries  should be using Singles items image and TVSeries Folders image and not use the parent 'Drama' images,


If not possibe to fix this I think this is far better to released this and not the changes with using Posters.

**Comment by basrieter** [comment]
So basically: no posters, just thumbs?

**Comment by basrieter** [comment]
Please try: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1718.zip again.

**Comment by matsarv** [comment]
Great work. Everyting looks fanatastic with the images now!

I did find that the Search gives an error.
Retrospect-log: https://paste.kodi.tv/dolafipero.kodi

**Comment by basrieter** [comment]
> Great work. Everyting looks fanatastic with the images now!
> 
> I did find that the Search gives an error. Retrospect-log: https://paste.kodi.tv/dolafipero.kodi

What did you search for?

**Comment by matsarv** [comment]
chn_class.py         - 502  - Searching for 'abba'

**Comment by matsarv** [comment]
I guess it has to do with 'onlyAvailableInSweden'

See the above log:
folderaction.py      - 133  - + KeyError: 'restrictions'

**Comment by dobbelina** [comment]
When i click "Recent" the description is missing, seems it's using the heading instead?
See 3 screenshots below that illustrates what i mean:
![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46063764/1ac30a58-63d5-498e-bd99-b1a3ab2bc395)
And
![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46063764/cf7f4614-a6bc-48cf-b4bc-1ba9d6e5fa58)
And
![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46063764/7986245d-9633-4065-b599-ec012c03c103)
