### ISSUE TITLE
SVTPlay missing description on Recent

### ISSUE THREAD

**Issue by dobbelina** [retrospect-addon/plugin.video.retrospect#1719]
### Describe the bug

On "Recent" the description is missing as can be seen in the 2 screenshots below.
I miss that from the old api point.
Going thru Categories=>Filmer is the same, and also if doing a search, description is not there.

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Screenshots 

![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46063764/767783ec-c36a-4c52-89c4-8a7a55a1c8b4)
And
![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46063764/88482117-842a-468d-bfa5-3737eac07d08)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:20.2
- Retrospect version:5.6.5

**Comment by dobbelina** [comment]
Thanks for the quick response.
Description has returned to items under Categories, however not on Recent
which is the main gateway for me using the addon.
It worked on the old api.

**Comment by basrieter** [comment]
I have descriptions, but they are the same as the title.....but that is what the API gives me. So can't fix that:
![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/1310443/65385db1-9071-4961-bffe-7f3c5a88e97b)

**Comment by dobbelina** [comment]
Thanks for trying.
Getting the description for Categories was a big improvement anyway, thanks.

**Comment by basrieter** [comment]
I will create an update soon.

**Comment by matsarv** [comment]
The changes you made did the work. Now it picks up the wide thumbs and fanart with the text same as in the old API. Thanks for that.


I have looked into missing of the description and some more things like LIVE in Currently playing a.s.o.
Here is some test code I came up with. Both must be addend to get the result as in below pictures.

<details><summary>Add (LIVE) to title to Currently playing.</summary>
<p>

In the def create_api_episode_type(self, result_set, add_parent_title=False):

```
Row 657 After:
            self.__set_expire_time(valid_to, item)

Insert:
        live_just_now = result_set.get('longDescription')
        if 'Live just nu' in live_just_now:
            item.name = "{} [COLOR gold](LIVE)[/COLOR]".format(item.name)
```

</p>
</details>

</p>
</details>

<details><summary>Add Badge and Description to Teaser.</summary>
<p>


In the def create_api_teaser_type(self, result_set):

```
Row 583 Replace:
        if "longDescription" not in new_result_set:
            new_result_set["longDescription"] = result_set.get("description")

With:
        if "longDescription" not in new_result_set:
            badge = result_set.get("badge")
            if badge is None:
                new_result_set["longDescription"] = result_set['images']['wide']['description']
            else:
                new_result_set["longDescription"] = "[COLOR gold]{}[/COLOR][CR][CR]{}".format(result_set.get("badge", {}).get("altText", None),result_set['images']['wide']['description'])

```

The description is stored in the diffrent images type so maybe result_set['images']['wide']['description'] should be fetched as the images is doing now.

</p>
</details>


</p>
</details>

---------------------------------------------

Currently playing:

![Currently playing](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46671821/69e6e484-77c2-46e0-ae57-eb7bbb5e8f24)

Last chance:

![Last chance](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46671821/a6df3916-558d-4e16-a41e-9c7d02ce9ecb)

Recent:

![Recent](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46671821/8b15d232-9a03-4c82-9637-2355448519e3)

Series:

![Series](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46671821/1652d4ee-7a97-4649-9f38-d18951c493a0)

**Comment by basrieter** [comment]
I added the badge and descriptions (not yet live stuff). Please check: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1719.zip

**Comment by dobbelina** [comment]
Awesome, thanks @matsarv & @basrieter for the description!

**Comment by matsarv** [comment]
The description works perfectly now!

**Comment by basrieter** [comment]
Great! Let me add the `live` stuff too.

**Comment by dobbelina** [comment]
I am very happy with the description added to Recent/Senaste but there seems to be 2 different descriptions, one short and one long.
Example below shows the same movie accessed from Recent followed by Categories=>Filmer, see the 3 screenshots below that illustrates the difference.
If it can be fixed great, if not then that's fine to and thanks for the effort fixing it in the first place 👍 
![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46063764/db7dbe23-85a5-40d4-a8e7-1726fb0df3f3)
And
![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46063764/66af4364-c7c9-4e5e-82cf-c639ccd990f1)
And
![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46063764/afb5243c-c489-41de-b06d-ecd28975741d)

**Comment by basrieter** [comment]
I understand the issue, however: that full description is just not present in the `recent` API! Sorry!

**Comment by basrieter** [comment]
I added the live indicator: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1719.zip

**Comment by matsarv** [comment]
Working! (live) is shown as before.

**Comment by basrieter** [comment]
Great! I will create a release tomorrow.

**Comment by matsarv** [comment]
I see you haven't merge this issue into the master yet.
After used it for some time I've noticed that 'Currently playing' have duplicated info in the description so I removed it. I've also added the play time into the program title.

Before:

![before-current](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46671821/81a2a94a-9423-46e9-ac32-375b35bb3626)



After:

![after-current](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46671821/5779ca9c-e3f6-477c-95ea-c49cf6ce2e15)



If you got the time, consider make theese changes. If not, it's not essential for the functions.

---------------------------------------------------------------------

<details><summary>Testcode for 'Currently playing'</summary>
<p>

Changes in     def create_api_teaser_type(self, result_set):

```
Row 563
from:
        new_result_set = result_set["item"]
to:
        new_result_set = result_set["item"]
        duration_formatted = result_set.get("durationFormatted")
```


```
Row 569
from:
            new_result_set["name"] = "{} - {}".format(title, sub_heading)
to:
            if ("Idag" in sub_heading 
                or "Ikväll" in sub_heading 
                or "Imorgon" in sub_heading):
                sub_heading_time = sub_heading.split(" ")[1]
                sub_heading_day = sub_heading.split(" ")[0]
                new_result_set["name"] = "{} - {} - {} {}".format(sub_heading_time,title,sub_heading_day,duration_formatted)
            else:
                new_result_set["name"] = "{} - {}".format(title,sub_heading)

Remarked ( not in use anymore? )

            # See if we need to filter out some of the headings? Defaults to True
            # if self.parentItem.metaData.get(self.__filter_subheading, True) and (
            #         "Idag" in sub_heading
            #         or "Ikväll" in sub_heading
            #         or "Igår" in sub_heading
            #         or sub_heading.endswith(" sek")
            #         or sub_heading.endswith(" min")
            #         or sub_heading.endswith(" tim")):
            #     Logger.trace("Ignoring subheading: %s", sub_heading)
            #     new_result_set["name"] = title
```

```
Row 597:
from:
            new_result_set["longDescription"] = description

to:
            new_result_set["longDescription"] = description

        if bool(sub_heading):
            if badge:
                new_result_set["longDescription"] = f"[COLOR gold]{badge}[/COLOR]"
```

</p>
</details>

**Comment by matsarv** [comment]
> I see you haven't merge this issue into the master yet. After used it for some time I've noticed that 'Currently playing' have duplicated info in the description so I removed it. I've also added the play time into the program title.
> 
> Before:
> 
> [image]
> 
> After:
> 
> [image]
> 
> If you got the time, consider make theese changes. If not, it's not essential for the functions.
> 
> Testcode for 'Currently playing'

Skipp this proposal. It seems to have affects in other areas.
