### ISSUE TITLE
RTL XL is gestopt. Uitzendingen staan nu op Videoland.

### ISSUE THREAD

**Issue by henkv1** [retrospect-addon/plugin.video.retrospect#1724]
RTL XL is gestopt. Uitzendingen zijn nu te zien op Videoland. Is het mogelijk om Videoland toe te voegen aan deze addon?

**Comment by basrieter** [comment]
Nope, weinig kans. Videoland = 100% betaald en dan wordt het debuggen en zo heel erg lastig. Dat moet dan echt met persoonlijke accounts die dan eventueel weer gebanned kunnen worden.

**Comment by henkv1** [comment]
Jammer. De meeste RTL programma's zijn wel gratis te bekijken, maar daar is wel een login voor nodig.
Als RTL XL definitef stopt moeten we daarheen voor de uitzendingen. Laat maar weten of ik kan helpen met debuggen of zoiets.

**Comment by basrieter** [comment]
Dat laatste (gratis kijken) is nieuw! Dan ga ik er toch een poging toe doen in de herfstvakantie.

**Comment by henkv1** [comment]
Misschien overbodige info: RTL XL werkt nu nog wel in Retrospect, maar de website is wel gesloten.

**Comment by Reino17** [comment]
Dat komt omdat retrospect gebruik maakt van een api van RTL:
https://github.com/retrospect-addon/plugin.video.retrospect/blob/025af0f98f17998652ebda5d4977c223b76b71ad/channels/channel.rtlnl/rtl/chn_rtl.py#L137

Ondanks dat rtlxl.nl verledentijd is, wordt deze api ongetwijfeld ook door Videoland op de achtergrond gebruikt.

Wat ik wel heb ondervonden is dat vreemd genoeg de "serie_id"-url niet meer werkt:
https://github.com/retrospect-addon/plugin.video.retrospect/blob/025af0f98f17998652ebda5d4977c223b76b71ad/channels/channel.rtlnl/rtl/chn_rtl.py#L190

Heb je enig idee hoe deze is veranderd, Bas?

**Comment by basrieter** [comment]
De oude API is nog online, maar bevat steeds minder content. Ik ga hem omschrijven naar Videoland, maar dat kost wat tijd.

**Comment by Reino17** [comment]
Is dat zo? Sinds dat rtlxl is gestopt gebruik ik deze (blijkbaar oude) API om een lijst van programma's te genereren die ik interessant vind om terug te kijken. Natuurlijk bevat het geen Videoland-content, maar volgens mij mis ik niks van wat anders in het overzicht op de rtlxl-website gestaan zou hebben.

Voor het half8 nieuws moet ik echter altijd de hier boven genoemde "related"-api-url gebruiken (https://api.rtl.nl/rtlxl/related/api/related/132237 om precies te zijn), omdat het bij rtlxl jaren zo is geweest dat deze **niet** in het dag-overzicht is terug te vinden. Totdat het late nieuws is uitgezonden was het half8 nieuws **wel** terug te vinden in het dag-verzicht, maar daarna vreemd genoeg niet meer. Dat geldt ook voor de "missed"-api-url hier boven.

Ik heb nog wel andere manieren om achter de uuid van het half8 nieuws te komen, maar daarom dus mijn vraag of jij weet hoe die "related"-api-url is veranderd, omdat die vreemd genoeg niet meer werkt.

**Comment by Reino17** [comment]
Hoewel `https://api.rtl.nl/watch/play/api/play/xl/` nog wel werkt, werkt, bij mij in ieder geval, `https://api.rtl.nl/rtlxl/missed/api/missed` al 2 weken niet meer. Of ben ik de enige?

**Comment by peerk72** [comment]
I'm curious if there is any news / progress about a new videoland channel.
Is it possible to add a short update?
Thanks for the great work!

**Comment by basrieter** [comment]
I am looking into Videoland, but am currently very busy. NPO renewed their complete app and did take a lot of my time. So it is in the works.

**Comment by basrieter** [comment]
First version of VideoLand channel is here: 

https://codeload.github.com/retrospect-addon/plugin.video.retrospect/zip/refs/heads/kill-rtl-xl

Be aware: it is a work in progress, and currently only these work:

![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/1310443/36a67778-deff-46d1-b1df-b3cb9b6bea75)

Furthermore:
- No HD-quality streams yet. 
- Login in required (see https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Storing-Passwords-in-the-Retrospect-Vault)
- Many streams are paid (indicated by the yellow 'a' behind them)

**Comment by peerk72** [comment]
I installed kill-rtl-xl.zip and added a valid videoland username and password and tested if I get the same results as shown in your screenshot

But I get message 'Retrospect Fout,  Geen afleveringen gevonden voor het geselecteerde item'

see log https://paste.kodi.tv/hizejihove.kodi

**Comment by basrieter** [comment]
Er gaat iets mis met de profiel selectie: 

```
20240102 19:15:58 - [ERROR   ] - urihandler.py        - 555  - GET failed with '498 Unknown' (0:00:00.148715) for https://users.videoland.bedrock.tech/v2/platforms/m6group_web/users/ac6a19c647974c858e0c30e1105ff3b6/profiles
```

Heb je meerdere profielen bij Videoland aangemaakt?

**Comment by peerk72** [comment]
dat klopt tbv deze test met kodi heb ik een extra account aangemaakt

**Comment by basrieter** [comment]
Ik heb het gevonden en gefixed. Wel moet even de log-in gereset worden: verander even de username in iets anders (streepje erachter of zo). Dan een keer Videoland openen. Dat geeft een fout. Dan weer de username terug zetten en dan zou het moeten werken.

**Comment by peerk72** [comment]
Nu zie ik wel de diverse zenders. En de daaronder getoonde programma's (zonder gele 'a') kunnen ook worden afgespeeld. Top!

Misschien kun je om de 'betaalde content' al dan niet weg te filteren een optie toevoegen bij de kanaalinstellingen (het scherm waarin je ook gebruikersnaam en wachtwoord opgeeft). En een zoek functie om programma's te zoeken zou uiteindelijk ook handig zijn. Uiteraard logisch dat dit in een eerste versie er nog niet in zit.

Ik ga er wat mee testen en als ik tegen vreemde dingen aanloop meld ik me weer.
Ziet er in ieder geval goed uit! Thanks!

**Comment by basrieter** [comment]
> Nu zie ik wel de diverse zenders. En de daaronder getoonde programma's (zonder gele 'a') kunnen ook worden afgespeeld. Top!
> 
> Misschien kun je om de 'betaalde content' al dan niet weg te filteren een optie toevoegen bij de kanaalinstellingen (het scherm waarin je ook gebruikersnaam en wachtwoord opgeeft). En een zoek functie om programma's te zoeken zou uiteindelijk ook handig zijn. Uiteraard logisch dat dit in een eerste versie er nog niet in zit.
> 
> Ik ga er wat mee testen en als ik tegen vreemde dingen aanloop meld ik me weer. Ziet er in ieder geval goed uit! Thanks!

Top! De betaalde "Premium" items kan je al wegfilteren vanuit de Retrospect settings.

**Comment by peerk72** [comment]
Met de huidige optie om premium items worden toch alle premium items weggefilterd voor alle kanalen?

Maar wat gebeurd er dan als je een betaalde account voor NPO hebt en een gratis account voor Videoland. Dan mag je alleen de premium items van NPO afspelen en niet die van Videoland. Die optie zou volgens mij dus ook / beter bij de kanaalopties thuishoren zodat je dat per kanaal kunt regelen. 

Dit heeft uiteraard geen prioriteit maar lijkt me wel beter.

**Comment by ErikBrown2** [comment]
Dank je wel, Bas. Het werkt perfect.

**Comment by basrieter** [comment]
> Met de huidige optie om premium items worden toch alle premium items weggefilterd voor alle kanalen?
> 
> Maar wat gebeurd er dan als je een betaalde account voor NPO hebt en een gratis account voor Videoland. Dan mag je alleen de premium items van NPO afspelen en niet die van Videoland. Die optie zou volgens mij dus ook / beter bij de kanaalopties thuishoren zodat je dat per kanaal kunt regelen.
> 
> Dit heeft uiteraard geen prioriteit maar lijkt me wel beter.

Zodra ik kan zien dat iemand premium heeft, dan zal ik deze items niet meer als premium markeren. Echter: Ik weet nog niet hoe ik dat kan zien. Daarvoor heb ik van iemand die wel premium heeft de output nodig van deze url: 

https://gigya-merge.videoland.com/accounts.getAccountInfo

Bij mij ziet ie er in Chrome zo uit:

![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/1310443/a1b35291-5ed4-463d-a5ca-f3e562d4608e)

**Comment by basrieter** [comment]
Inmiddels zouden alle getoonde folders moeten werken. Even opnieuw installeren: https://codeload.github.com/retrospect-addon/plugin.video.retrospect/zip/refs/heads/kill-rtl-xl

Verder zit ik een beetje met het tonen van "alle" content. Dat zijn meer dan 2500 objecten:
```json
{"@":24,"a":174,"b":233,"c":137,"d":269,"e":79,"f":65,"g":59,"h":130,"i":75,"j":49,"k":67,"l":119,"m":160,"n":38,"o":66,"p":96,"q":0,"r":87,"s":180,"t":276,"u":13,"v":55,"w":76,"x":0,"y":12,"z":26}
```
In het totaal zouden het dan heel veel pages ophalen zijn. Vervelender is echter dat ik vanuit de listing die hieronder hangt niet kan opmaken of het premium content is of niet. Dus ik kan dat van te voren niet laten zien.

**Comment by henkv1** [comment]
Helaas lukt het ophalen van de lijst met uitzendingen bij mij niet. Ik krijg de lijst met categorieën, maar als ik daar op klik krijg ik een foutmelding, zie log files.
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/13819548/retrospect.log)
[kodi.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/13819549/kodi.log)

**Comment by basrieter** [comment]
Op welk system doe je dit? Lijkt een issue te zijn binnen de Python `cryptography` module namelijk:

https://github.com/pyca/cryptography/issues/9016

**Comment by henkv1** [comment]
Dit is Arch Linux ARM 64 bit op een raspberry pi 4. De versie van python-cryptography is: python-cryptography-41.0.7-1
Downgraden naar python-cryptography-38.0.1-1 lost het probleem inderdaad op. Dank je

**Comment by peerk72** [comment]
> Zodra ik kan zien dat iemand premium heeft, dan zal ik deze items niet meer als premium markeren. Echter: Ik weet nog niet hoe ik dat kan zien. Daarvoor heb ik van iemand die wel premium heeft de output nodig van deze url:

> https://gigya-merge.videoland.com/accounts.getAccountInfo

Als je uit de accountinfo kunt halen of iemand een premium account heeft is dat nog een betere oplossing inderdaad.
Ik kan je helaas niet aan die informatie helpen aangezien ik een gratis account heb

> Verder zit ik een beetje met het tonen van "alle" content. Dat zijn meer dan 2500 objecten:

Is het een idee om de lijst op te delen per letter van het alfabet zodat de omvang per letter beperkt blijft?

**Comment by basrieter** [comment]
> > Zodra ik kan zien dat iemand premium heeft, dan zal ik deze items niet meer als premium markeren. Echter: Ik weet nog niet hoe ik dat kan zien. Daarvoor heb ik van iemand die wel premium heeft de output nodig van deze url:
> 
> > https://gigya-merge.videoland.com/accounts.getAccountInfo
> 
> Als je uit de accountinfo kunt halen of iemand een premium account heeft is dat nog een betere oplossing inderdaad. Ik kan je helaas niet aan die informatie helpen aangezien ik een gratis account heb
> 
> > Verder zit ik een beetje met het tonen van "alle" content. Dat zijn meer dan 2500 objecten:
> 
> Is het een idee om de lijst op te delen per letter van het alfabet zodat de omvang per letter beperkt blijft?

Ja, daar zat ik ook ana te denken om het alfabetisch te doen. Maar ik ben ook wel benieuwd naar de profile info van iemand met een betaald account? Dus wie wilt dat delen? Mag ook prive via de mail.

**Comment by basrieter** [comment]
Thanks @WebDLLover! Toch nog een vraag: zie jij op dit moment bij "Populair -> Bureau Hofstad -> " bijv. hier de premium indicator `a`

![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/1310443/e6dc27b4-5610-4d1d-8bc5-e6497234fb43)

**Comment by peerk72** [comment]
ik weet niet of je het probleem om het abonnementstype te bepalen hebt
opgelost maar mocht dat nog niet zo zijn. via
https://stores.videoland.bedrock.tech/premium/v4/customers/rtlnl/platforms/m6group_web/users
*/#userid#*/subscriptions
krijg ik een json object terug waaruit je volgens mij af zou kunnen leiden
welke abonnementtype je hebt

{
    "passed": [],
    "current": [
        {
            "uid": "*#userid#*",
            "offer": {
                "code": "catchup-tier",
                "public": false,
                "title": "TV Gemist",
                "features": [
                    {
                        "code": "1 scherm tegelijk"
                    },
                    {
                        "code": "TV programma\u0027s 7 dagen terugkijken"
                    },
                    {
                        "code": "Met reclame"
                    }
                ],
                "variants": [],
                "image": null,
                "offers_link": null
            },
            "current_contract": {
                "contract_id": "#contractid",
                "store_code": "videoland_pg",
                "variant_id": "Free",
                "start_date": 1697649067,
                "due_date": null,
                "end_date": null,
                "payment_method": {
                    "type": "Free"
                },
                "next_billing_date": null,
                "next_billing_price": 0,
                "recurring": true,
                "active": true,
                "variant": {
                    "id": "videoland_pg|catchup-tier|Free",
                    "store_code": "videoland_pg",
                    "recurring": true,
                     etc...............

Op do 4 jan 2024 om 23:16 schreef Bas Rieter ***@***.***>:

**Comment by basrieter** [comment]
Thanks! Die gebruik ik nu. @peerk72 Kan jij deze vraag beantwoorden voor mij? https://github.com/retrospect-addon/plugin.video.retrospect/issues/1724#issuecomment-1877834116

**Comment by peerk72** [comment]
ik zie dit (op basis van de zip-file die ik zojuist heb
gedownload/geinstalleerd) dit
[image: image.png]



Op za 6 jan 2024 om 14:07 schreef Bas Rieter ***@***.***>:

**Comment by basrieter** [comment]
Plaatjes werken niet als je via de mail reageert. Dat kan enkel via de website.

**Comment by peerk72** [comment]
ik zag het ...
als het goed is heb ik dat al aangepast zie 
https://github.com/retrospect-addon/plugin.video.retrospect/assets/51530412/89f5223f-7a38-4026-bb72-107f6c7060b1

**Comment by basrieter** [comment]
Top! En @peerk72 jij hebt dus geen premium account?

**Comment by peerk72** [comment]
Klopt ik heb inderdaad geen premium account.

Op za 6 jan 2024 om 14:48 schreef Bas Rieter ***@***.***>

**Comment by henkv1** [comment]
Het werkt nu vrij goed. Ik loop alleen tegen het probleem aan dat bij het opstarten soms de lijst met zenders wordt getoond, maar soms ook een lijst met categorieën.  Dit lijkt vrij willekeurig op te treden.

**Comment by basrieter** [comment]
> Het werkt nu vrij goed. Ik loop alleen tegen het probleem aan dat bij het opstarten soms de lijst met zenders wordt getoond, maar soms ook een lijst met categorieën. Dit lijkt vrij willekeurig op te treden.

Yes, dat heb ik ook gezien. Hun URL geeft soms een andere output. Dat heb ik zelfs soms in mijn browser. Ik ga er nog eens  naar kijken. @henkv1 heb jij een premium account?

**Comment by peerk72** [comment]
Ik had dat ook soms dat de verkeerde lijst werd getoond. Via het context
menu de lijst verversen loste dat soms op.

Op za 6 jan 2024 om 20:11 schreef Bas Rieter ***@***.***>

**Comment by basrieter** [comment]
> Ik had dat ook soms dat de verkeerde lijst werd getoond. Via het context menu de lijst verversen loste dat soms op. Op za 6 jan 2024 om 20:11 schreef Bas Rieter ***@***.***>
> […](#)
> Het werkt nu vrij goed. Ik loop alleen tegen het probleem aan dat bij het opstarten soms de lijst met zenders wordt getoond, maar soms ook een lijst met categorieën. Dit lijkt vrij willekeurig op te treden. Yes, dat heb ik ook gezien. Hun URL geeft soms een andere output. Dat heb ik zelfs soms in mijn browser. Ik ga er nog eens naar kijken. @henkv1 
Met de laatste update zou dit opgelost moeten zijn. Ook heb ik `recente programma's` items toegevoegd.

**Comment by henkv1** [comment]
> > Het werkt nu vrij goed. Ik loop alleen tegen het probleem aan dat bij het opstarten soms de lijst met zenders wordt getoond, maar soms ook een lijst met categorieën. Dit lijkt vrij willekeurig op te treden.
> 
> Yes, dat heb ik ook gezien. Hun URL geeft soms een andere output. Dat heb ik zelfs soms in mijn browser. Ik ga er nog eens naar kijken. @henkv1 heb jij een premium account?

Ziet er goed uit. Dank je.
Helaas heb ik geen premium account om verder te testen.

**Comment by peerk72** [comment]
Het afspelen van de beschikbare afleveringen werkt prima. Top.

Ook nog wat bevindingen ...
De inhoud van het startmenu is nog met regelmaat afwijkend (zie schermafdruk)
![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/51530412/fd1712fc-eeff-4923-b057-53ee527e4d63)
Verder mis ik vooral het kunnen navigeren of zoeken op basis van de naam van een programma. Het is nu (zeker met het afwijkende startmenu) erg lastig cq bijna onmogelijk om een specifiek programma te vinden. Eerder gaf je aan de volledige lijst programma's evt per letter van het alfabet onder te verdelen. Dat zou ook een goede innvulling hiervoor zijn denk ik.

**Comment by basrieter** [comment]
Die andere layout die heb ik ook zelfs op de normale site soms! Dus dat is lastig om te voorkomen. Ik had al "Recente" items toegevoegd, waardoor de meeste belangrijke shows al te vinden zijn. 

Het zoeken zal ik nog wel bouwen, maar dat gaat via een andere API van Videoland en is dus wat lastiger. En normale navigatie is er op de site ook niet echt. Dus zoeken is echt de enige optie.

**Comment by basrieter** [comment]
"Zoeken" heb ik toegevoegd: https://codeload.github.com/retrospect-addon/plugin.video.retrospect/zip/refs/heads/kill-rtl-xl (install from ZIP)

**Comment by peerk72** [comment]
Nice! Ga ik vanavond meteen testen. Thanks!

**Comment by peerk72** [comment]
Zoeken werkt. Top. 

De zoekresultaten in response in de Videoland webpagina zijn gesorteerd op op mate van matching.
Maar in Kodi worden de resultaten gewoon op de normale manier gesorteerd (alfabetische sortering van de programmanaam) 
Logisch dat het zo werkt.

Er wordt bij een zoek-actie in Videoland echter niet alleen gezocht op de naam maar ook in de beschrijving van programma's
Als ik als voorbeeld zoek op Eigen Huis wordt Eigen Huis en Tuin wel als eerste geretourneerd in de json response.
Maar er worden ook nog tientallen andere programma's teruggegeven die ergens in de beschrijving iets van 'eigen huis' hebben. Zou de sortering in de response op een of andere manier gebruikt kunnen worden om de resultaten te sorteren. 

In de resultaten zitten ook nog de premium-programma's waarvoor mijn free-account geen rechten heeft. Die worden allemaal netjes met een A gemarkeerd dus dat werkt ook prima. Als de zoekresultaten ontdaan zouden kunnen worden van de premium programma's die toch niet bekeken kunnen worden is de sortering waarschijnlijk niet meer van belang voor een free-account. Misschien nog beter om bij een free-accounttype in alle overzichten de premium-programma's weg te laten?

Ik weet dat je voor alle zenders de premium-programma's uit kunt zetten via de instellingen. Voor NPO wil ik wel premium programma's zien en voor Videoland momenteel niet. Dus die instelling werkt voor mij niet. Eigenlijk zou die instelling beter per kanaal ingesteld moeten kunnen worden.

**Comment by basrieter** [comment]
> De zoekresultaten in response in de Videoland webpagina zijn gesorteerd op op mate van matching. Maar in Kodi worden de resultaten gewoon op de normale manier gesorteerd (alfabetische sortering van de programmanaam) Logisch dat het zo werkt.
> 
> Er wordt bij een zoek-actie in Videoland echter niet alleen gezocht op de naam maar ook in de beschrijving van programma's Als ik als voorbeeld zoek op Eigen Huis wordt Eigen Huis en Tuin wel als eerste geretourneerd in de json response. Maar er worden ook nog tientallen andere programma's teruggegeven die ergens in de beschrijving iets van 'eigen huis' hebben. Zou de sortering in de response op een of andere manier gebruikt kunnen worden om de resultaten te sorteren.

Je kunt de sorteervolgorde op "Default/Standaard" zetten:

![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/1310443/6c6aac59-365c-41da-af5b-e09991e19f4e)

> In de resultaten zitten ook nog de premium-programma's waarvoor mijn free-account geen rechten heeft. Die worden allemaal netjes met een A gemarkeerd dus dat werkt ook prima. Als de zoekresultaten ontdaan zouden kunnen worden van de premium programma's die toch niet bekeken kunnen worden is de sortering waarschijnlijk niet meer van belang voor een free-account. Misschien nog beter om bij een free-accounttype in alle overzichten de premium-programma's weg te laten?
> Ik weet dat je voor alle zenders de premium-programma's uit kunt zetten via de instellingen. Voor NPO wil ik wel premium programma's zien en voor Videoland momenteel niet. Dus die instelling werkt voor mij niet. Eigenlijk zou die instelling beter per kanaal ingesteld moeten kunnen worden.

Wel een aardig punt. Zal ik erin verwerken voor zowel NPO als Videoland.

**Comment by peerk72** [comment]
met de standaard sortering worden de zoekresultaten inderdaad op de juiste volgorde getoond, dat zou kunnen werken.
deze standaard sortering springt echter steeds terug naar sortering op datum oplopend als je kodi opnieuw start
doe ik dan iets fout?

fijn dat je de extra instelling voor npo en videoland toe wil gaanvoegen

**Comment by basrieter** [comment]
> met de standaard sortering worden de zoekresultaten inderdaad op de juiste volgorde getoond, dat zou kunnen werken. deze standaard sortering springt echter steeds terug naar sortering op datum oplopend als je kodi opnieuw start doe ik dan iets fout?

Denk dat ik dat gesloopt het een tijdje geleden. Heb het nu teruggedraaid. Zou je het nog eens kunnen downloaden, installeren en proberen? Nu zou het weer onthouden moeten worden na instellen.

**Comment by peerk72** [comment]
het lijkt erop dat de sortering nu wel wordt bewaard voor het menu dat wordt geopend als je videoland in het hoofdmenu kiest.
maar niet van de zoekresultaten, die sortering moet ik nog steeds opnieuw instellen als ik kodi herstart en weer ga zoeken

**Comment by basrieter** [comment]
Bij mij blijft hij de sortering gewoon onthouden! Ik zet hem, na zoeken, eenmalig op "Default". Als ik dan terug ga en opnieuw ga zoeken, dan blijft hij hetzelfde.

**Comment by peerk72** [comment]
Dat doet ie bij mij ook zo lang ik Kodi niet herstart. Maar nadat Kodi
opnieuw is opgestart is de sortering weer datum, oplopend.

Op zo 14 jan 2024 om 21:56 schreef Bas Rieter ***@***.***>

**Comment by basrieter** [comment]
Inderdaad. Zie het nu. Het komt omdat het anders niet mogelijk is om zoek resultaten te bookmarken in Kodi en/of Retrospect. Daarvoor moet welke zoek URL anders zijn. En daarom denk Kodi dat het steeds het ene of het andere is. Maar ik kijk even nog naar andere oplossingen.

**Comment by basrieter** [comment]
Gefixed nu. Even opnieuw download en installeren. Hij default nu voor zoek resultaten altijd naar "unsorted/default". Is wel het meest logische.

**Comment by peerk72** [comment]
lijkt me een prima oplossing
en zojuist even getest en sortering blijft nu bewaard

als dan nog de premium content grotendeels weggefilterd wordt (via de kanaalinstellingen) als je daar geen geschikt account voor hebt denk ik dat het een perfecte oplossing is  

lekker bezig!

**Comment by basrieter** [comment]
Closed with 33362dcafbb0d364a60bd58ced5de6dcbb738fad

Released via Kodi repo.

**Comment by basrieter** [comment]
Geen idee. Je moet dan een nieuw issue aanmaken en daarbij dan een goede logfile bij aanleveren
