### ISSUE TITLE
Retrospect onder versie Kodi19.5 kan ik niet laden vanuit repository

### ISSUE THREAD

**Issue by TinivanB** [retrospect-addon/plugin.video.retrospect#1725]
Ik tracht Retrospect 5.6.6. te laden vanuit de officiele Kodi repository van Kodi 19.5. Bij de Installeren geeft hij een foutmelding dat de "Inputstream. Adaptive" versie 20.3.1 moet zijn. Echter deze versie is ontwikkeld voor Kodi Nexus. Bij de te laden Retrospect 5.6.6. zit wel een versie van Inputstream Adaptive nl. 19.0.7. Dit is echter de laatst uitgebrachte versie onder Kodi 19 .
Ik kan dus Retrospect niet laden vanuit de officiele Kodi repository.
Used versions:
- Kodi version: 19.5
- Retrospect version: 5.6.6

**Comment by basrieter** [comment]
I don't required that at all. It should run fine on Matrix and up:

![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/1310443/986b6c32-70e3-4762-b15c-97fb58249ffe)

However, I have seen cases where the InputStream Adaptive add-on was installed, but disabled. Check that. Otherwise, please enable debug logging in Kodi, try installing Retrospect again and then attach (don't copy paste) the full log here.

**Comment by TinivanB** [comment]
Dag Bas,
Bij het installeren van Retrospect wordt de foutboodschap vermeld:

"De afhankelijkheid op inputstream.adaptive versie 20.3.1 kan niet worden
voldaan". Dat klopt van de versie is 19.0.7.

Mijn technisch vermogen is niet zo groot, dus ik tracht om de log boven
water t krijgen.

Met dank alvast,
Tini

Op zo 22 okt 2023 om 14:07 schreef Bas Rieter ***@***.***>:

**Comment by TinivanB** [comment]
Inputstream was "geaktiveerd".

Op zo 22 okt 2023 om 14:35 schreef Tini van Bussel <
***@***.***>:

**Comment by basrieter** [comment]
Ik heb het net op een kale Kodi Matrix geprobeerd: installeert gewoon. De versie van `inputstream.adaptive` staat bewust super laag (2.0.19), om overal compatibel mee te zijn. Ik ben wel benieuwd naar de logfile van Kodi.

**Comment by TinivanB** [comment]
Dag Bas,

Mijn technisch vermogen is te beperkt. Ik de logfile  (visueel) lezen, waar
de installatie van Retrospect op staat. Echter Kodi staat op een
Androidbox. Ik zou dan de logfile moeten toesturen. Echter deze mail staat
op mijn Windowslaptop, dus hoe ik dit moet uitvoeren, is me op dit moment
nog onbekend.
Ik kan wel foto's maken van de log op dat moment van installatie
Reprospect.

Groetjes en bedankt voor de snelle reply's,
Tini




Op zo 22 okt 2023 om 18:42 schreef Bas Rieter ***@***.***>:

**Comment by basrieter** [comment]
Je kunt deze add-on gebruiken: https://kodi.wiki/view/Add-on:Kodi_Logfile_Uploader

**Comment by TinivanB** [comment]
Hoi Bas,

Ik heb zonet de (old)log geupload via het programma Kodi Logfile uploader.
Ik hoop dat je er aan kunt.

Bedankt voor je snelle hulp. Ik hoop dat je er wat aan hebt.

Op de een of andere wijze moet mijn Kodi 19 vervuild zijn en zal ik opnieuw
moeten installeren.

Groetjes,
Tini

Op zo 22 okt 2023 om 19:54 schreef Bas Rieter ***@***.***>:

**Comment by basrieter** [comment]
Hoi Tini,

ik heb dan wel de URL nodig waarop de logfile te vinden is

**Comment by TinivanB** [comment]
Bas,

Heb je hier iets aan?
Bijgaand enkele foto's met QR-kode en pad.

Groetjes,
Tini

Op ma 23 okt 2023 om 14:56 schreef Bas Rieter ***@***.***>:

**Comment by basrieter** [comment]
De attachment kan ik niet zien. Makkelijker om dat even via https://github.com/retrospect-addon/plugin.video.retrospect/issues/1725 te doen, ipv via een mail reply.

**Comment by TinivanB** [comment]
Hierbij de foto's
![IMG_20231023_150412-1](https://github.com/retrospect-addon/plugin.video.retrospect/assets/148690262/2ffd7429-8bad-4f73-a91b-a211cf06610f)
![IMG_20231023_150416-1](https://github.com/retrospect-addon/plugin.video.retrospect/assets/148690262/9d8495f6-091c-4e48-b720-b94360fbbe5c)
![IMG_20231023_150432-1](https://github.com/retrospect-addon/plugin.video.retrospect/assets/148690262/753c5363-98fc-43a4-8baa-36664e3de469)
###

**Comment by basrieter** [comment]
```
2023-10-22 15:04:44.926 T:17986   DEBUG <general>: CAddonInstaller: installing 'plugin.video.retrospect' version '5.6.6' from repository 'repository.xbmc.org'
2023-10-22 15:04:44.946 T:20931   DEBUG <general>: CAddonInstallJob[plugin.video.youtube]: requires inputstream.adaptive version 20.3.1 which is not available
2023-10-22 15:04:44.947 T:20931   ERROR <general>: CAddonInstallJob[plugin.video.retrospect]: De afhankelijkheid op inputstream.adaptive versie 20.3.1 kan niet worden voldaan.
```

Bron zit hem in `plugin.video.youtube`, deze wordt NIET uit de officiele Kodi repository gedownload, maar uit `repository.umbrella`. En daar wordt geen rekening gehouden met Kodi versies en in de YT add-on die daar staat is niet compatible met Kodi Matrix. 

Maar: `repository.umbrella` host illegale streaming content die wij **niet** ondersteunen. En dat betekent dus dat we ook geen verdere support kunnen leveren. Sorry.

**Comment by TinivanB** [comment]
Bas,

Bedankt voor de moeite.

Het is voor mij nu compleet duidelijk. Ik had deze Android-box (2 maanden
oud) van iemand overgenomen. De download is dus niet gedaan vanaf de off.
Kodi-directory.

Nogmaals dank,
Tini van Bussel


Op ma 23 okt 2023 om 21:01 schreef Bas Rieter ***@***.***>:
