### ISSUE TITLE
Een vernieuwd NPOStart

### ISSUE THREAD

**Issue by ggieling** [retrospect-addon/plugin.video.retrospect#1726]
## Feature Request
Wat betekent de verandering voor het kijken naar NPO programma's in Retrospect?

### Is your feature request related to a problem? Please describe

NPO geeft aan dat NPO start vernieuwd wordt, zie [Een vernieuwd NPO start](https://nieuwestart.npo.nl/stap-voor-stap).

### Describe the solution you'd like

Ik weet niet of dit invloed gaat hebben op de samenwerking van de retrospect plugin en NPOstart/plus. Ik weet ook niet of relevante informatie hiervoor beschikbaar is, maar indien het invloed heeft en de informatie beschikbaar is, dan zou het prettig zijn om retrospect klaar te hebben voor deze verandering op het moment dat deze verandering ingaat.

**Comment by basrieter** [comment]
Dat hangt vooral af van wat ze gaan veranderen. Als de API niet veranderd, dan is de impact laag. Maar er zal zeker wat werk uit voort komen.

**Comment by basrieter** [comment]
Closing with #1730
