### ISSUE TITLE
tv4play premium with sports

### ISSUE THREAD

**Issue by stiffes** [retrospect-addon/plugin.video.retrospect#1727]
### Is your feature request related to a problem? Please describe

CMore has been integrated into tv4play. The current version of retrospect does not list live events or sports. 

### Describe the solution you'd like
When using the tv4play-plugin there could be a catergory with "sport" with sub categories for "hockeyallsvenskan", "SHL". A listing of current live events in "sport". Or just a listing of live sports directly when starting the plugin.

### Describe alternatives you've considered

Using chromecast.

**Comment by basrieter** [comment]
Please discuss this in #1714 which is 100% about TV4.
