### ISSUE TITLE
all channels gone?

### ISSUE THREAD

**Issue by Joolks** [retrospect-addon/plugin.video.retrospect#1728]
### Describe the bug

After the options in the main menu there are no choices anymore. So selecting [national] -> empty. This is for all main menu options.

## Expected Behavior

I expected channels to be filled

### To Reproduce

1. Start Retrospect
2. Select any main menu item
3. Nothing...

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/enawubabos

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:19.4
- Retrospect version: 5.6.6
Using raspbian 11

**Comment by basrieter** [comment]
Should all be fine from the log: 

```
20231101 21:08:09 - [INFO    ] - channelimporter.py   - 213  - Fetch a total of 57 channels of which 57 are visible.
20231101 21:08:09 - [DEBUG   ] - channelimporter.py   - 217  - Stopwatch :: Stop (ChannelIndex.get_channels Importer): 1698869289.8111804, time elapsed: 48.13504219055176 ms (+48.13504219055176 ms)
20231101 21:08:09 - [DEBUG   ] - channelimporter.py   - 237  - Found these categories: Sport, Regional, Tech, Video, Radio, National
```

Can you check you Kodi log?

**Comment by Joolks** [comment]
So I tried it again just now with the same results:

> 20231102 21:22:12 - [INFO    ] - channelimporter.py   - 213  - Fetch a total of 57 channels of which 57 are visible.
>20231102 21:22:12 - [DEBUG   ] - channelimporter.py   - 217  - Stopwatch :: Stop (ChannelIndex.get_channels Importer): 1698956532.828077, time elapsed: 121.32525444030762 ms (+121.32525444030762 ms)
>20231102 21:22:12 - [DEBUG   ] - channelimporter.py   - 237  - Found these categories: Video, Tech, Regional, Radio, National, Sport

But still only see those categories and no channels under them.
Also checked the kodi log but all mentions to retrospect show script succesfully run.

**Comment by basrieter** [comment]
Can you try to reinstall Retrospect: uninstall (but keep config files), then reinstall.

**Comment by Joolks** [comment]
Yeah already tried that. Didn't make any difference. I didn't try **with** removing the config files however.

**Comment by Joolks** [comment]
So I tried reinstalling including removing the settings, but the error stays.
Also found this in the log for today: 
>20231103 20:27:05 - [DEBUG   ] - channellistaction.py - 72   - Skipping NPO Start (National) due to category filter
>20231103 20:27:05 - [DEBUG   ] - channellistaction.py - 72   - Skipping RTL XL (RTL 4,5,7 &amp; 8) (National) due to category filter
>20231103 20:27:05 - [DEBUG   ] - channellistaction.py - 72   - Skipping Kijk.nl (National) due to category filter
>20231103 20:27:05 - [DEBUG   ] - channellistaction.py - 72   - Skipping MTV.nl (Video) due to category filter
>20231103 20:27:05 - [DEBUG   ] - channellistaction.py - 72   - Skipping Pathé Nederland (Video) due to category filter
>20231103 20:27:05 - [DEBUG   ] - channellistaction.py - 72   - Skipping AT5 (Regional) due to category filter
Could this explain why nog channels are shown?

**Comment by basrieter** [comment]
So, please tell me what you are doing in more steps, or actually: step by step, without leaving out any steps. 

>20231103 20:27:05 - [DEBUG ] - channellistaction.py - 72 - Skipping NPO Start (National) due to category filter
20231103 20:27:05 - [DEBUG ] - channellistaction.py - 72 - Skipping RTL XL (RTL 4,5,7 & 8) (National) due to category filter
20231103 20:27:05 - [DEBUG ] - channellistaction.py - 72 - Skipping Kijk.nl (National) due to category filter
20231103 20:27:05 - [DEBUG ] - channellistaction.py - 72 - Skipping MTV.nl (Video) due to category filter
20231103 20:27:05 - [DEBUG ] - channellistaction.py - 72 - Skipping Pathé Nederland (Video) due to category filter
20231103 20:27:05 - [DEBUG ] - channellistaction.py - 72 - Skipping AT5 (Regional) due to category filter

This warning is not weird if you select a different category.

**Comment by Joolks** [comment]
-Boot up Pi
-login
-start kodi from raspbian os
-go to add ons
-start Retrospect
-go to national
-goes to folder TV shows/Retrospect: watched. Nothing is there apart from 2 dots folder to go back.

**Comment by basrieter** [comment]
Can you change the: "Hide Watched" option in Kodi?

**Comment by Joolks** [comment]
Yeah! that fixed it. Sorry for the troubles! Didn't know that was even an option. Kids must have gotten a hold of the remote and changed some settings..

**Comment by basrieter** [comment]
> Yeah! that fixed it. Sorry for the troubles! Didn't know that was even an option. Kids must have gotten a hold of the remote and changed some settings..

It is weird how they got marked as "read". As they are folders.

**Comment by Joolks** [comment]
Yeah kinda. For normal imported series in kodi the folder gets checked as watched when all episodes are watched. But I doubt I have seen everything in each folder in Retrospect;)

**Comment by basrieter** [comment]
Just added a quick thing to the code that prevents this in the future.
