### ISSUE TITLE
Youtube add-on dependency

### ISSUE THREAD

**Issue by duck7000** [retrospect-addon/plugin.video.retrospect#1738]
A very simple question.
What is the reason that retrospect needs you tube add-on to be installed?

i never use you tube so i tried to uninstall but that is not possible due to dependency of retrospect

Might it be possible to make you tube add-on optional dependency?

It is of course not really a issue but I'm wondering.

Edit: Sorry i choose the wrong category, it is not a bug obviously

**Comment by basrieter** [comment]
it is a dependency for some channels. They use YouTube streams for replay

**Comment by duck7000** [comment]
Okay i understand, thanks for explaining.
