### ISSUE TITLE
Retrospect 5.72 not working

### ISSUE THREAD

**Issue by markrutte10** [retrospect-addon/plugin.video.retrospect#1740]
### Is your feature request related to a problem? Please describe

I have downloaded retrospect 5.72 but it is not working for me 
NPO Start is when I put it on the channels get stuck
The sound cintinues
But when I put on for instance NOS the channels are working
can you help me

**Comment by basrieter** [comment]
If it starts playing it's working. Try updating Widevine: https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Troubleshooting

**Comment by markrutte10** [comment]
Thank you for your answereBut in NPO Start is not playingAlso Kijk is not playingPicture is not playingSound goes onI tryed kodi to recetEverthing of and a brand new installationNot workingWhen you say it must be working whatI doing wrongThanksVerzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Bas Rieter ***@***.***> Datum: 28-11-2023  21:09  (GMT+01:00) Aan: "retrospect-addon/plugin.video.retrospect" ***@***.***> Cc: markrutte10 ***@***.***>, Author ***@***.***> Onderwerp: Re: [retrospect-addon/plugin.video.retrospect] Retrospect 5.72 not working (Issue #1740) 
If it starts playing it's working. Try updating Widevine: https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Troubleshooting

**Comment by markrutte10** [comment]
Not rebooted
Doing it now

Op di 28 nov. 2023 22:35 schreef Bas Rieter ***@***.***>:

**Comment by markrutte10** [comment]
Yes  but when I start retrospect 5.72Start NPO then laatste nieuws zegtfout bij het laden van de itemsVerzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Bas Rieter ***@***.***> Datum: 28-11-2023  22:35  (GMT+01:00) Aan: "retrospect-addon/plugin.video.retrospect" ***@***.***> Cc: markrutte10 ***@***.***>, Author ***@***.***> Onderwerp: Re: [retrospect-addon/plugin.video.retrospect] Retrospect 5.72 not working (Issue #1740) 
Did you use the InputStream Helper add-on for that AND rebooted Kodi afterward?

**Comment by basrieter** [comment]
They you need to provide a full DEBUG Retrospect log. See at the bottom of this page how to do that: 

https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Logging

**Comment by basrieter** [comment]
But please first install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/npo-future.zip as it contains some minor NPO fixes.

**Comment by basrieter** [comment]
Update on this?

**Comment by cosmic-sko** [comment]
Several hours later...
Running Kodi Leia and Libreelec 9.2.8 on Raspberry 3. Retrospect 5.5.14 is installed and have not updated for a long time. It has worked Ok until a few days ago - now Swedish TV4play can't be reached at all any longer. But neither Automatic or Manual update of Retrospect is working. I've cleared the cache, uninstalled Retrospect. The only version found in repository to install is 5.5.14. I downloaded 5.7.2 on a USB stick but receive message "...omdb dependance 3.0 cannot be satisfied" or something similar. Totally frustrated by now. HOW on earth do I update??

**Comment by basrieter** [comment]
You can't on Kodi Leia......that version is no longer supported. It used Python 2 and now everything is Python 3. So you will need to upgrade your Kodi instance (and you should as Leia is way to old) and then you can upgrade Retrospect and all other add-ons.

**Comment by basrieter** [comment]
You cannot upgrade it, but you reinstall it: https://libreelec.tv/downloads/raspberry/

**Comment by cosmic-sko** [comment]
Question is, as, reportedly Libreelec 9.2.8 should not/can't be upgraded to higher versions with RP 3
since support for HEVC decoding is broken, which version to install:
RPi 2 [LibreELEC-RPi2.arm-11.0.3.img.gz](https://releases.libreelec.tv/LibreELEC-RPi2.arm-11.0.3.img.gz)
OR
RPi 3 LibreELEC-RPi2.arm-9.2.8.img.gz

If I reinstall 9.2.8, will that resolve my problem? Does the current 9.2.8 run with Python 3?

Or, should I switch to another OS (which...?)? Or must I actually scrap my RP3 and buy an RP4??

**Comment by basrieter** [comment]
> Question is, as, reportedly Libreelec 9.2.8 should not/can't be upgraded to higher versions with RP 3 since support for HEVC decoding is broken, which version to install: RPi 2 [LibreELEC-RPi2.arm-11.0.3.img.gz](https://releases.libreelec.tv/LibreELEC-RPi2.arm-11.0.3.img.gz) OR RPi 3 LibreELEC-RPi2.arm-9.2.8.img.gz
> 
> If I reinstall 9.2.8, will that resolve my problem? Does the current 9.2.8 run with Python 3?
> 
> Or, should I switch to another OS (which...?)? Or must I actually scrap my RP3 and buy an RP4??

HVEC is perhaps broken, but everything else runs just fine. I have Kodi Nexus op LibreElec on a Rpi2. Runs just fine. So you need https://releases.libreelec.tv/LibreELEC-RPi2.arm-11.0.3.img.gz on a Rpi3. Only Kodi Matrix and newer support Python 3. Regardless of OS.

**Comment by cosmic-sko** [comment]
OK, so now I've made a clean install of [LibreELEC-RPi2.arm-11.0.3.img.gz] on my Pi 3. It worked pretty well so now I run Kodi Nexus and Retrospect 5.7.2. And thanks to the info "Refresh token" for Swedish TV4Play on https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Storing-Passwords-in-the-Retrospect-Vault, I can finally access TV4 material again. (Really, without that info it would have been impossible to figure out how to do it.)

The only issue is that I can't get rid of the 3 lines in upper left of screen, displaying LOG, MEM and CPU info. Quite annoying. How on earth can these be hidden?

**Comment by cosmic-sko** [comment]
PS  Also, Sveriges Radio add-on dosesn't want to install. A temporary glitch, or a known issue?

**Comment by cosmic-sko** [comment]
More questions... Regarding the refresh token for Swedish TV4Play (first time I've encountered this - in LE 9 you entered username and password in Channel settings):
Must this process be repeated now and then, or how does it work?

**Comment by basrieter** [comment]
> More questions... Regarding the refresh token for Swedish TV4Play (first time I've encountered this - in LE 9 you entered username and password in Channel settings): Must this process be repeated now and then, or how does it work?

The refresh token is valid for 1 year. So it should not happen too often.

**Comment by cosmic-sko** [comment]
Bas or anyone else:  Any clues regarding the 3 always visible lines in upper left of screen, displaying LOG, MEM and CPU info, and that Sveriges Radio add-on dosesn't want to install?

**Comment by basrieter** [comment]
I think you have debug mode enabled in Kodi. You should try disabling it.

**Comment by cosmic-sko** [comment]
Just on spot, Bas. Info lines gone now. And SR add-on installed just fine. Thanks for good help.

One small thing: It's not possible to decrease the size of Favourites icons I add on the home screen? They are rather huge.  My TV screen is 65", 1920x1080p.

**Comment by basrieter** [comment]
> Just on spot, Bas. Info lines gone now. And SR add-on installed just fine. Thanks for good help.
> 
> One small thing: It's not possible to decrease the size of Favourites icons I add on the home screen? They are rather huge. My TV screen is 65", 1920x1080p.

Great to hear. Regarding the icon size: that is a Kodi skin thing. I can't help you with that.

**Comment by cosmic-sko** [comment]
Sure, I appreciate that Kodi skin is not your area. I'll try to find some info in the Kodi Forum.
