### ISSUE TITLE
Letters met een umlaut incorrect in de NPO start ondertiteling

### ISSUE THREAD

**Issue by ErikBrown2** [retrospect-addon/plugin.video.retrospect#1743]
### Describe the bug

De letters met een umlaut van de woorden schön en jüdische in de ondertiteling
van het programma Rundfunk, episode Schnurrbart zijn vervangen door een verkeerd teken. 
Ik neem aan dat dit te maken heeft met de character coding van de undertitel file. 
Dit is hetzelfde met Kodi onder Windows en Kodi onder Libreelec.

## Expected Behavior

Dat de de woorden schön en jüdische in de ondertiteling juist worden geschreven

## Actual Behavior

Zie de foute letters in de screenshots

## Possible Fix

Ik neem aan de character encoding voor de ondertitel file veranderen

### To Reproduce

1. Start Kodi, Retrospect, National, NPO start, Search en enter Rundfunk
2. Selecteer de episode Schnurrbart, speel het af en zet de ondertiteling aan.
3. Op 15 minuten en 9 seconden vind je het woord schön en op 15 minuten en 17 seconden vind je het woord jüdische.

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/icequvofuj

### Screenshots 

![file1](https://github.com/retrospect-addon/plugin.video.retrospect/assets/32511867/286be55e-99c3-4caa-b972-119d7ce2c082)

![file 2](https://github.com/retrospect-addon/plugin.video.retrospect/assets/32511867/fda9f414-faff-4246-ad48-b0c4599a6ab1)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 20.1 en 19.5
- Retrospect version: De laatste test versie die jij online hebt gezet.

**Comment by ErikBrown2** [comment]
Ik was nog vergeten te vermelden dat ik niet kon zien of dezelfde fout te zien was op de NPO start website. Ik kon niet vinden hoe je op de NPO start website de ondertiteling aan zet.

**Comment by basrieter** [comment]
Ik zie het, maarrrrr: 

![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/1310443/2954a726-a5b5-4d8d-9a36-f4f7813c5a3e)

Het zit gewoon zo in de data die van NPO afkomt. Niet iets dat ik kan fixen. Als je het op NPO.nl zelf kan reproduceren dan zou ik het bij hun melden. Anders is het even afwachten.
