### ISSUE TITLE
RTL XL all listing is gone

### ISSUE THREAD

**Issue by BrodjagaRatnik** [retrospect-addon/plugin.video.retrospect#1744]
### Describe the bug

RTL XL all listing is gone only search and recent is shown, but both give "No episode found..."

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here: https://paste.kodi.tv/ibiqinoxac.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:
- Retrospect version:

**Comment by basrieter** [comment]
Please search before posting: #1724
