### ISSUE TITLE
lijst in "recent" voor "vandaag" in NPO is niet compleet

### ISSUE THREAD

**Issue by rwynands** [retrospect-addon/plugin.video.retrospect#1745]
### Describe the bug

Bij het openen van "recent" en dan "today" zie je een chronologische lijst van alle programma's van vandaag op NPO 1, 2 en 3. Vanaf een uur of 5 's middags vallen er gaten en zijn een hoop programma's niet zichtbaar

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [x] Android (Firestick)
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: nexus
- Retrospect version: 5.7.2

**Comment by rwynands** [comment]
Het varieert per dag en een dag later is alles weer in beeld. Omdat de npo app volledig op zijn gat ligt voor apple tv, is het lastig om een gids in beeld te krijgen, maar ik zal op andere platforms kijken om een duidelijker beeld te krijgen van wat er weg is gevallen. Sent from my phoneOn Dec 9, 2023, at 08:18, Bas Rieter ***@***.***> wrote:﻿
Je zult concreter moeten zijn: welke afleveringen/programma's mis je op welk kanaal en om welke tijd?

**Comment by rwynands** [comment]
Het is 9 december 9:00 plaatselijke tijd en dus 18:00 in NL:
NPO1 geen programma's te zien tussen 18:00 en 00:52
NPO2 geen programma's te zien tussen 17:00 en 23:59
NPO3 geen programma's te zien tussen tussen 18:30 en 20:23 en tussen 22:00
en 23:36

**Comment by Heleen-Heleen** [comment]
Het klopt dat het varieert per dag, maar dan is nog niet alles in beeld 

![Screenshot_20231210-103347](https://github.com/retrospect-addon/plugin.video.retrospect/assets/151458718/57ca2ffd-0449-47c6-a396-738b10530803)
![Screenshot_20231211-192638](https://github.com/retrospect-addon/plugin.video.retrospect/assets/151458718/faab9d66-87b6-4958-b152-5639b7e77106)
 
Deze zijn van gisteren

**Comment by Heleen-Heleen** [comment]
![Screenshot_20231204-115357](https://github.com/retrospect-addon/plugin.video.retrospect/assets/151458718/f1a961d1-bcbe-425e-9ca3-1b41943d2d35)
![Screenshot_20231204-152549](https://github.com/retrospect-addon/plugin.video.retrospect/assets/151458718/5831752a-dc6c-4e97-a83a-730a6f1c7fe0)
![Screenshot_20231205-104945](https://github.com/retrospect-addon/plugin.video.retrospect/assets/151458718/727983a7-fd83-4392-9f5e-14b023b7c8dd)

4 december
Maar het is al langer zo

**Comment by basrieter** [comment]
Ik kan nog steeds niet veel met deze info. Plaats nog eens een screenshot en vertel me dan WAT er ontbreekt? Desnoods met nog een screenshot van de https://npo.nl/start/live site? Hou er rekening mee dat niet alles wat op de site staat, ook terug te kijken is uit de live listing. Die toon ik dus niet in Retrospect.

**Comment by rwynands** [comment]
Heel vaak zoek in "recent" naar het 8 uur journaal en nieuwsuur, die
volgens mij terug te kijken zijn, maar niet verschijnen. Wel via andere weg
nl "search" of "series>nieuws en actualiteiten". Ook later in de
avond/nacht of de volgende dag in "recent". Ik ben de komende twee weken
van huis en kan geen screenshots maken.
Heleen, jij weet precies wat ik bedoel. Kun jij me hiermee helpen?

**Comment by Heleen-Heleen** [comment]
rwijnands, ik weet wat je bedoelt, ga er morgen naar kijken

**Comment by ErikBrown2** [comment]
> Heel vaak zoek in "recent" naar het 8 uur journaal en nieuwsuur, die volgens mij terug te kijken zijn, maar niet verschijnen. Wel via andere weg nl "search" of "series>nieuws en actualiteiten". Ook later in de avond/nacht of de volgende dag in "recent" 

Het is blijkbaar niet voor iedereen zo. Ik kijk ook elke morgen naar het acht uur journaal van de vorige dag in Recent. Ik heb het probleem niet en vind het daar elke dag.

**Comment by basrieter** [comment]
Wat belangrijk is, is om Retrospect te vergelijken met de https://npo.nl/start/live site op dat moment. Wat daar zichtbaar EN afspeelbaar is, zou in Retrospect ook moeten staan.

**Comment by Heleen-Heleen** [comment]
H
[live tv en terugkijken 15-12-23.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/13686744/live.tv.en.terugkijken.15-12-23.zip)
 
Vooralsnog doe ik het nu even middels teletekst en Retrospect  omdat veel overzichtelijker is dan de Npo, maar heb wel 16 screenshots voorhanden.

Het Journaal laadt in de avond niet meer, evenals Nieuwsuur. EenVandaag doet het wel dezelfde dag, maar veel later.
Verscheidene kinderprogramma's laden pas een paar uur later.

Films zijn in recent sinds *17 november of eerdr al helemaal niet meer te zien. Ook bij de sectie Films an sich worden in Retrospect maar 32 geladen, terwijl alleen al bij NPO op de eerste rij 72 telt.  *Sonny Boy en Sorry we missed you.

Zou het niet mogelijk zijn om, net zo als vroeger, alles in een keer te laden?

**Comment by Heleen-Heleen** [comment]
![journaal](https://github.com/retrospect-addon/plugin.video.retrospect/assets/151458718/29827286-7a5a-4f18-8846-402fac3c44e3)
![Nieuwsuur](https://github.com/retrospect-addon/plugin.video.retrospect/assets/151458718/2ed2dd8f-fcad-457b-af07-56e37db457e7)
![film](https://github.com/retrospect-addon/plugin.video.retrospect/assets/151458718/849eb7e8-72b3-450b-8548-d8d67381304e)

**Comment by Heleen-Heleen** [comment]
veel screenshots van 14 december
[live tv en terugkijken 14-12-23.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/13687105/live.tv.en.terugkijken.14-12-23.zip)

**Comment by basrieter** [comment]
Dit is wat ik zie op jouw screenshots:

![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/1310443/23d8c38d-84a7-4dce-a11b-00787f742c6a)
Dit klopt allemaal. Alles met een pijltje is grijs op de NPO site en heeft geen stream! En kan dus ook niet afgespeeld worden. Zowel op de site, als in Retrospect. 

Dus ik kan nog steeds niet helemaal plaatsen wat het probleem is. Zo ver ik kan zien staat alles in Retrospect wat ook speelbaar is op de site? 

Wellicht dat ik het over het hoofd zie, maar dan heb ik echt het volgende nodig: 

- Een screenshot van Retrospect, ongefilterd, met de tijdspanne van een missend element. 
- Een screenshot van NPO waarin exact dezelfde tijdspanne staat, met echt een uitgebreide timeline, zoals: ![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/1310443/bf19400a-6962-4a03-bacc-3f5ffc05e018)

**Comment by rwynands** [comment]
Also ik het 8 uur journaal en nieuwsuur als voorbeelden mag nemen, hoewel ze op een bepaald moment nog niet zichtbaar zijn in “recent”, zijn ze wel te zien en speelbaar na een search ernaar. Overigens doet retrospect het bij sinds donderdag niet goed meer. De streams worden niet meer gevonden als ik een programma aanclick (firestick). Sent from my phoneOn Dec 15, 2023, at 07:35, Bas Rieter ***@***.***> wrote:﻿
Dit is wat ik zie op jouw screenshots:
image.png (view on web)
Dit klopt allemaal. Alles met een pijltje is grijs op de NPO site en heeft geen stream! En kan dus ook niet afgespeeld worden. Zowel op de site, als in Retrospect.
Dus ik kan nog steeds niet helemaal plaatsen wat het probleem is. Zo ver ik kan zien staat alles in Retrospect wat ook speelbaar is op de site?
Wellicht dat ik het over het hoofd zie, maar dan heb ik echt het volgende nodig:

Een screenshot van Retrospect, ongefilterd, met de tijdspanne van een missend element.
Een screenshot van NPO waarin exact dezelfde tijdspanne staat, met echt een uitgebreide timeline, zoals: image.png (view on web)

**Comment by Heleen-Heleen** [comment]
Dank, Bas, voor de snelle reactie

**Comment by basrieter** [comment]
> Also ik het 8 uur journaal en nieuwsuur als voorbeelden mag nemen, hoewel ze op een bepaald moment nog niet zichtbaar zijn in “recent”, zijn ze wel te zien en speelbaar na een search ernaar. 

Ik snap dat het met zoeken wellicht gevonden wordt, maar in de EPG api van NOS staan ze dan nog als niet beschikbaar en dan houdt het op. 

> Overigens doet retrospect het bij sinds donderdag niet goed meer. De streams worden niet meer gevonden als ik een programma aanclick (firestick).

Is mij nog niet opgevallen. Voorbeelden graag! Ik kan echt niet raden wat er wel of niet werkt.

**Comment by rwynands** [comment]
﻿Geen enkele stream wordt gevonden. Er komt een foutboodschap om de log file te bekijken. Kun je me helpen herinneren waar ik de link naar de logfile kan vinden, zodat ik die posten?Sent from my phoneOn Dec 15, 2023, at 10:09, Bas Rieter ***@***.***> wrote:﻿

Also ik het 8 uur journaal en nieuwsuur als voorbeelden mag nemen, hoewel ze op een bepaald moment nog niet zichtbaar zijn in “recent”, zijn ze wel te zien en speelbaar na een search ernaar. 

Ik snap dat het met zoeken wellicht gevonden wordt, maar in de EPG api van NOS staan ze dan nog als niet beschikbaar en dan houdt het op.

Overigens doet retrospect het bij sinds donderdag niet goed meer. De streams worden niet meer gevonden als ik een programma aanclick (firestick).

Is mij nog niet opgevallen. Voorbeelden graag! Ik kan echt niet raden wat er wel of niet werkt.

**Comment by basrieter** [comment]
See here: https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Logging at the bottom.

**Comment by rwynands** [comment]
Log file is hereHttps://paste.kodi.tv/iferideqovBedanktRobert Sent from my phoneOn Dec 15, 2023, at 12:57, Bas Rieter ***@***.***> wrote:﻿
See here: https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Logging at the bottom.

**Comment by basrieter** [comment]
De cookie file is bij jouw corrupt: `http.cookiejar.LoadError: invalid Netscape format cookies file '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.retrospect/cookiejar.dat': 't_4ZIis0LH1Ul_Um-Z8Mp'`. Je kunt de cookies wissen via de instellingen van Retrospect

**Comment by lagosazules** [comment]
"Overigens doet retrospect het bij sinds donderdag niet goed meer. De streams worden niet meer gevonden als ik een programma aanclick (firestick)"

Zelfde ervaring sinds donderdag op kodi raspberry, geen enkele NPO stream recent, live etc kijk, NOS etc werken wel, ik gebruik vpn via Amsterdam om ook normaal gesproken de live programmas te zien. 

Via mijn Firestick vanaf Spaanse IP werkt alles wel maar uiteraard niet de NPO live streams die een NL IP vereisen.

Ook via Android npostart app werkt geen enkele stream

**Comment by basrieter** [comment]
> "Overigens doet retrospect het bij sinds donderdag niet goed meer. De streams worden niet meer gevonden als ik een programma aanclick (firestick)"
> 
> Zelfde ervaring sinds donderdag op kodi raspberry, geen enkele NPO stream recent, live etc kijk, NOS etc werken wel, ik gebruik vpn via Amsterdam om ook normaal gesproken de live programmas te zien.
> 
> Via mijn Firestick vanaf Spaanse IP werkt alles wel maar uiteraard niet de NPO live streams die een NL IP vereisen.
> 
> Ook via Android npostart app werkt geen enkele stream

VPN's werken niet meer. Die heeft NPO geblokkeerd. Maar laten we vooral stoppen met dit issue over **recente** items te vervuilen met andere problemen.

**Comment by rwynands** [comment]
﻿Dank je. Cookies verwijderen werkt, zolang ik zonder vpn werk. Zodra ik vpn inschakel komt het probleem terug en moet ik opnieuw cookies verwijderen om zonder vpn weer te kunnen kijken.  Jammer, maar zoals je al zei, dit ligt aan NPO en niet aan retrospectExcuses voor het vervuilen van de recent discussie. Ik had een nieuw gesprek moeten starten. Sent from my phoneOn Dec 16, 2023, at 00:57, Bas Rieter ***@***.***> wrote:﻿
De cookie file is bij jouw corrupt: http.cookiejar.LoadError: invalid Netscape format cookies file '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.retrospect/cookiejar.dat': 't_4ZIis0LH1Ul_Um-Z8Mp'. Je kunt de cookies wissen via de instellingen van Retrospect

**Comment by Heleen-Heleen** [comment]
Het heeft momenteel niet zoveel zin om screenshots van Retrospect te plaatsen. 
De NPO er n.l.  vandaag een complete janboel van de timeline gemaakt.

vreemd genoeg waren het Journaal en Nieuwsuur gisteren wel zichtbaar in Retrospect 

![Screenshot_20231216-232004](https://github.com/retrospect-addon/plugin.video.retrospect/assets/151458718/b09dd1a0-297a-436f-b2b1-caf55a2ba762)
[17-12-23.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/13696802/17-12-23.zip)

**Comment by Heleen-Heleen** [comment]
timeline NPO
![timeline](https://github.com/retrospect-addon/plugin.video.retrospect/assets/151458718/9755f1b9-f4ff-4f54-a6bc-58ffe1c85b7d)

**Comment by Heleen-Heleen** [comment]
> Opvallend is dat er dat er hiaten zijn van ruim 5 uur, zie teletekst 

Dit kwam waarschijnlijk door "vandaag" op de bladwijzers te hebben geplaatst

**Comment by Heleen-Heleen** [comment]
ik heb ontdekt dat er heel veel foute afspeelden zijn waardoor er veel gapen tussen de programma's zitten


![Screenshot_20231218-223400](https://github.com/retrospect-addon/plugin.video.retrospect/assets/151458718/26b18340-66d6-4570-be9c-7b927d2fd02a)

![Screenshot_20231218-223428](https://github.com/retrospect-addon/plugin.video.retrospect/assets/151458718/d9d4156c-5c64-47be-b841-8c8462907930)
![Screenshot_20231219-071535](https://github.com/retrospect-addon/plugin.video.retrospect/assets/151458718/67ea3629-761d-467c-9383-383fed81106f)
![Screenshot_20231219-075232](https://github.com/retrospect-addon/plugin.video.retrospect/assets/151458718/4bb06f64-efa3-4042-8b4c-17a47218780a)
![Screenshot_20231219-075308](https://github.com/retrospect-addon/plugin.video.retrospect/assets/151458718/0ec81b7a-c04c-45fb-ab37-ecaf771d3dfb)
![Screenshot_20231219-085905](https://github.com/retrospect-addon/plugin.video.retrospect/assets/151458718/371a8fb5-4954-4d31-b4c5-653a4fd0c54e)
![Screenshot_20231219-085947](https://github.com/retrospect-addon/plugin.video.retrospect/assets/151458718/b8ad0d94-befc-4b8a-81d0-c663aae997af)

**Comment by Heleen-Heleen** [comment]
[17-12 verkeerde afspeelduur.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/13713246/17-12.verkeerde.afspeelduur.zip)
[19-12 1.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/13713255/19-12.1.zip)

**Comment by basrieter** [comment]
Ik kan heel weinig met al deze screenshots omdat ik echt niet zie wat er niet klopt. Het zou beter zijn om gewoon een enkele screenshot te plaatsen, samen met een screenshot van de NPO site en dan aangeven wat er niet klopt?

En nogmaals ter verduidelijking:

- Retrospect toont enkele de programma's in Recent die af te spelen zijn
- De items zijn op chronologische gesorteerd maar zeker niet aansluitend met elkaar.
- De tijdslijn is dus niet compleet en er is dus ook geen enkele vorm van tijdsduur zichtbaar in de lijst.

**Comment by chakubie** [comment]
Sinds vandaag lijkt  NPO recent niet meer te functioneren: "Fout bij het ophalen van de items"

**Comment by Heleen-Heleen** [comment]
> Ik kan heel weinig met al deze screenshots omdat ik echt niet zie wat er niet klopt. Het zou beter zijn om gewoon een enkele screenshot te plaatsen, samen met een screenshot van de NPO site en dan aangeven wat er niet klopt?
> 
> En nogmaals ter verduidelijking:
> 
> * Retrospect toont enkele de programma's in Recent die af te spelen zijn
> * De items zijn op chronologische gesorteerd maar zeker niet aansluitend met elkaar.
> * De tijdslijn is dus niet compleet en er is dus ook geen enkele vorm van tijdsduur zichtbaar in de lijst.

Sorry, ik heb het niet gecheckt bij de NPO,  maar die gaten zitten alweer daar.

Overigens werkt 'recent' niet meer

![18-12 BUITENHOF](https://github.com/retrospect-addon/plugin.video.retrospect/assets/151458718/fef8a27a-72d7-47a2-8ed3-7180cf9ba76b)

![19-12 JOURNAAL](https://github.com/retrospect-addon/plugin.video.retrospect/assets/151458718/2471b860-cf0b-40bf-a742-5b398c7bc834)

**Comment by basrieter** [comment]
Ik zie het. De URL is aangepast. Ga ik fixen.

**Comment by Heleen-Heleen** [comment]
Er is nog een nieuw item bijgekomen

![Screenshot_20231219-195008](https://github.com/retrospect-addon/plugin.video.retrospect/assets/151458718/e128e18e-60d9-435c-92d9-c2378f2424dc)

**Comment by basrieter** [comment]
We gaan specifiek over `recente` items hier verder: https://github.com/retrospect-addon/plugin.video.retrospect/pull/1750
