### ISSUE TITLE
afspelen programma stopt niet

### ISSUE THREAD

**Issue by rwynands** [retrospect-addon/plugin.video.retrospect#1746]
### Describe the bug

Programma op NPO blijft doorspelen als je eruit stapt om naar iets anders te gaan en stopt pas als je een neuwe aan klikt

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ x] Android (firestick TV)
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: Nexus
- Retrospect version: 5.7.2

**Comment by basrieter** [comment]
Dat is iets met de Kodi opties. Niks met Retrospect te maken.

**Comment by rwynands** [comment]
Duidelijk. Dankjewel Sent from my phoneOn Dec 9, 2023, at 08:17, Bas Rieter ***@***.***> wrote:﻿
Dat is iets met de Kodi opties. Niks met Retrospect te maken.
