### ISSUE TITLE
NPO Start streams do not play anymore

### ISSUE THREAD

**Issue by mark0100** [retrospect-addon/plugin.video.retrospect#1752]
The NPO Start streams do not play anymore.
I get the message that the item cannot be started.

In the kodi log file i see:

> 2024-01-01 11:03:22.000 T:1991    error <general>: CCurlFile::CReadState::FillBuffer - (0x521a5280) Failed: HTTP returned code 403
> 2024-01-01 11:03:22.000 T:1991    error <general>: CCurlFile::Open - <http://thetvdb.com/banners/posters/73244-7.jpg> Failed with code 403:
>                                                    
> 2024-01-01 11:03:22.041 T:1990    error <general>: CCurlFile::Stat - <https://mediadb.omroep.nl/assets/002/346/810.jpg> Failed: Couldn't resolve host name(6)
> 2024-01-01 11:03:22.082 T:1990    error <general>: CCurlFile::Stat - <https://mediadb.omroep.nl/assets/003/602/298.jpg> Failed: Couldn't resolve host name(6)
> 2024-01-01 11:03:22.123 T:2017    error <general>: CCurlFile::Stat - <http://mediadb.omroep.nl/assets/003/600/617.jpg> Failed: Couldn't resolve host name(6)
> 2024-01-01 11:03:22.169 T:2017    error <general>: CCurlFile::Stat - <https://mediadb.omroep.nl/assets/003/532/217.jpg> Failed: Couldn't resolve host name(6)
> 2024-01-01 11:03:22.208 T:2017    error <general>: CCurlFile::Stat - <https://mediadb.omroep.nl/assets/003/213/883.jpg> Failed: Couldn't resolve host name(6)
> 2024-01-01 11:03:23.430 T:2017    error <general>: CCurlFile::CReadState::FillBuffer - (0x5a9e7048) Failed: HTTP returned code 403
> 2024-01-01 11:03:23.431 T:2017    error <general>: CCurlFile::Open - <http://thetvdb.com/banners/seasons/5cf494719ac64.jpg> Failed with code 403:
>  

I run Retrospect 5.7.4 on Kodi 20.2.0 on OSMC 2023.12.1 on a Pi 3b+

**Comment by basrieter** [comment]
Are you trying to play from within the Netherlands or outside? Any VPNs?

**Comment by mark0100** [comment]
From within the Netherlands and no VPN.
It worked fine a week ago or so.

**Comment by mark0100** [comment]
If i try to browse to the urls in the logfile from a different system they also cannot be resolved.
So it looks like something has changed on the NPO site?

**Comment by basrieter** [comment]
Ok, please post a full DEBUG retrospect.log. So enable debug logging in Retrospect, then try playback and then upload the log using the built-in functionality of Retrospect. Then post the link to the log here.

**Comment by mark0100** [comment]
Strange: I rebooted my Pi and now the streams do play again!
It must have been a local issue on my Pi.
Sorry to bother you.

**Comment by basrieter** [comment]
Great to hear! Enjoy Retrospect.
