### ISSUE TITLE
Missing ip in the url in the web dialog for TV4 Play

### ISSUE THREAD

**Issue by huey-smart** [retrospect-addon/plugin.video.retrospect#1760]
### Describe the bug

When I try to access an item in the TV4 Play folders I get the Retrospect Web Dialog and it tells me to navigate to "http://:3145". It's missing the full url. I've tried reinstalling Retrospect with no difference. I've tried in various local networks without success.

## Expected Behavior

The web dialog should include the full url.

## Actual Behavior

The web dialog only includes "http://:3145".

### To Reproduce

1. Navigate to a folder in TV4 Play that includes playable items and enter it
2. Web dialog is displayed

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/quxifidodi

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 20.3.2
- Retrospect version: 5.7.5

**Comment by basrieter** [comment]
It should contain the IP of your device on which you are running Kodi. I retrieve it using `xbmc.getInfoLabel("network.ipaddress")`. Can you check what Kodi is showing in the network info page?

**Comment by huey-smart** [comment]
Hmm. The IP address according to Kodi is empty. So root cause is elsewhere...

**Comment by basrieter** [comment]
Apparently :(  If you know the IP, you can still navigate to it on http port 3145

**Comment by huey-smart** [comment]
Since you made me understand the issue was with Kodi I tried restarting the device and then the ip was there again. And now it works as expected. I'll close the ticket. Thanks for the quick response and guidance!

**Comment by basrieter** [comment]
Good to hear that!
