### ISSUE TITLE
NPO not working

### ISSUE THREAD

**Issue by BrodjagaRatnik** [retrospect-addon/plugin.video.retrospect#1762]
### Describe the bug

NPO does not work for live and recent other kijk and videoland work as normal

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here: https://paste.kodi.tv/qefemiyisa.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.5.0
- Retrospect version: 5.7.5

**Comment by PhyxionNL** [comment]
Heb hetzelfde probleem, via de NPO app werkt het wel.
Het lijkt hier niet helemaal goed te gaan:
```
20240213 18:43:39 - [ERROR   ] - urihandler.py        - 555  - POST failed with '400 Bad Request' (0:00:00.139991) for https://npo.nl/start/api/domain/player-token
```

**Comment by basrieter** [comment]
I noticed that today. Fix is already in the works

**Comment by basrieter** [comment]
Please try: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1762.zip

**Comment by ErikBrown2** [comment]
Dank je wel Bas, het werkt weer prima.

**Comment by BrodjagaRatnik** [comment]
Perfect werkt dank voor de snelle fix

**Comment by oliv3r** [comment]
Confirmed, works again

**Comment by basrieter** [comment]
Release a new version via the Kodi repo.

**Comment by ErjeMeij** [comment]
> Please try: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1762.zip
Hallo Bas, het lukt mij niet om deze file te downloaden. Ik heb twee raspberry's. Een ervan is automatisch geüpdatet en werkt weer de andere krijg ik niet aan de praat, ook niet als ik alles opnieuw installeer. Groet, RJ.

**Comment by oliv3r** [comment]
> > Please try: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1762.zip

> Hallo Bas, het lukt mij niet om deze file te downloaden. Ik heb twee raspberry's. Een ervan is automatisch geüpdatet en werkt weer de andere krijg ik niet aan de praat, ook niet als ik alles opnieuw installeer. Groet, RJ.

Als je wacht voor de kodi release, krijg je gewoon een update in kodi, zal niet heel lang duren.

**Comment by ErjeMeij** [comment]
Hello,

This is not working, my computer says " 404: not found"

Met vriendelijke groet,
RJ Meijers.

Op wo 14 feb 2024 13:27 schreef Olliver Schinagl ***@***.***>:

**Comment by basrieter** [comment]
Indeed, as there was an official update pushed to the Kodi repository. No need for this test build anymore.
