### ISSUE TITLE
POST failed with '401 Unauthorized'

### ISSUE THREAD

**Issue by AthanasiusPernath** [retrospect-addon/plugin.video.retrospect#1764]
### Describe the bug

Hi, longtime and happy Retrospect user here - truly appreciate this brilliant Kodi add-on!

As of today (14th Feb), NPO content no longer plays on my RPi4 running LibreELEC. No user changes were made on this system - NPO streams played fine last night. Identical setup on RPi3+/LibreELEC is still playing NPO streams w/o probs.

Tried several cold reboots, clearing the Retrospect vault and re-entering NPO logon details ...all to no avail.

## Expected Behavior

Play NPO streams on my RPi4.

## Actual Behavior

All NPO streams fail to play, erratically with and without an on-screen  notification.

## Possible Fix

A quick look at the DEBUG error log shows that each attempt to play a NPO stream results in the following error:

POST failed with '401 Unauthorized' (0:00:00.130280) for https://prod.npoplayer.nl/stream-link

See pasted log for details.

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/yozecodexe

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux 6.1.74 #1 SMP Sat Jan 27 03:38:15 UTC 2024 aarch64 GNU/Linux
 - [ ] OSX
 - [X] Raspberry-Pi 4 / LibreELEC (official): 11.0.6 (RPi4.arm)
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:  20.3
- Retrospect version: 5.7.5

**Comment by basrieter** [comment]
Please search in open and closed issues: #1762 

So basically: update Retrospect via Kodi to get the fix.

**Comment by AthanasiusPernath** [comment]
Thanks - and stupid me. I should've checked Retrospect versions before submitting a bug report - Pi3 had already auto-updated to 5.7.6, Pi4 was somehow still running 5.7.5.
