### ISSUE TITLE
TV4 Play News error (TV4 Nyheterna)

### ISSUE THREAD

**Issue by dobbelina** [retrospect-addon/plugin.video.retrospect#1766]
### Describe the bug
Can not play **TV4 Nyheterna**, get the "Error retrieving the list of items." message.
Log & screendump attached.

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/lohequfoje.kodi

### Screenshots 

<img width="450" alt="debug" src="https://github.com/retrospect-addon/plugin.video.retrospect/assets/46063764/7217d97b-a240-413c-9d2c-475f5705b61c">

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 20.2
- Retrospect version: 5.7.7

**Comment by basrieter** [comment]
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1766.zip using the "Install from Zip" option in Kodi.

**Comment by dobbelina** [comment]
It works perfect!

Thanks basrieter 👍

**Comment by basrieter** [comment]
Great! I will need to release a new version then.
