### ISSUE TITLE
NPO recent werkt niet meer

### ISSUE THREAD

**Issue by ErikBrown2** [retrospect-addon/plugin.video.retrospect#1771]
### Describe the bug

NPO start Recent werkt niet meer. Al het andere van NPO start werkt wel. De foutmelding is: "Retrospect - Error, Error retrieving the list of items". Ik heb niet kunnen testen of het op de NPO website werkt of niet omdat ik tot nu toe de Recent optie niet heb kunnen vinden op de NPO website.

## Expected Behavior

Dat het de lijst met programma's voor de geselecteerde dag laat zien.

## Actual Behavior

Het selecteren van Recent en dan een dag geeft de foutmelding "Retrospect - Error, Error retrieving the list of items"

### To Reproduce

1. Start Retrospect, selecteer National - NPO start - Recent - Yesterday (of een andere dag)
2.
3.

### Debuglog

The **debug** retrospect.log can be found here: https://paste.kodi.tv/uxonepuzoy

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 20.5
- Retrospect version: 5.7.7

**Comment by ErikBrown2** [comment]
Ik weet niet of dit relevant is of alleen maar cosmetisch maar volgens het Retrospect log is de versie van mijn Retrospect add-on   versie 5.7.5 maar volgens Kodi - Add-ons - My add-ons - My add-ons - Video add-ons - Retrospect versie 5.7.7

**Comment by basrieter** [comment]
Zou je deze kunnen installeren https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1771.zip en kunnen kijken of het weer werkt?

**Comment by ErikBrown2** [comment]
Het werkt inderdaad weer. Hartelijk dank voor de snelle fix.

**Comment by basrieter** [comment]
Ik ga een release doen vanavond.

**Comment by Heleen-Heleen** [comment]
bedankt, Bas de gids werkt ook meteen weer

**Comment by basrieter** [comment]
Update is eruit
