### ISSUE TITLE
TV4 Play: Shows item image for both items and folders when listing

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1774]
### Describe the bug

Shows item image for both items and folders when listing

## Expected Behavior

Show folder image when item is a folder and item image för item streams

## Actual Behavior

All items is showing item image

## Possible Fix

See below

### To Reproduce

1.  Select TV4 Play
2. Select Latest

### Screenshots 

Now:
![1](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46671821/3fab8dd3-9474-446b-b847-52fae661c6d1)

Fix; 
chn_tv4se.py
def create_api_series(self, result_set: dict) -> Optional[MediaItem]:
Line 409

```
from:
        item = FolderItem(title, url, content_type=contenttype.EPISODES, media_type=mediatype.TVSHOW)
to:
        item = FolderItem(title, url, content_type=contenttype.EPISODES, media_type=mediatype.FOLDER)
```

After:
![2](https://github.com/retrospect-addon/plugin.video.retrospect/assets/46671821/9388ef02-399c-4ac6-9528-06d781b9d888)

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 20.5
- Retrospect version: 5.7.8

**Comment by basrieter** [comment]
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1774.zip

**Comment by matsarv** [comment]
Now it works OK.
Nothing is broken so no need to rush out a new version.
