### ISSUE TITLE
In plaats van de live stream voor RTV Noord-Holland wordt AT5 getoond.

### ISSUE THREAD

**Issue by Johpin1** [retrospect-addon/plugin.video.retrospect#1782]
### Describe the bug

Regional -> RTV Noord-Holland -> Live Stream geeft ATV5, maar geen RTV Noord-Holland.

## Expected Behavior

Het zou de live stream van RTV Noord-Holland moeten afspelen.

## Actual Behavior

Je ziet de live stream van ATV5

## Possible Fix

Aanpassen van de URL?
 Onder VLC werkt de volgende (uit mijn zelf samengestelde m3u8 bestand):
`#EXTINF:12,NH Niews (1080p)
#EXTVLCOPT:network-caching=1000
https://takeoff.jetstre.am/?account=nhnieuws&file=live&output=playlist.m3u8&protocol=https&service=wowza&type=live`

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 20.3
- Retrospect version: 5.7.9

**Comment by basrieter** [comment]
Please try this zip via the "Install from zip" option: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1782.zip

**Comment by Johpin1** [comment]
The following message appeared:
 Afspelen mislukt. Een of meer items kunnen niet worden afgespeeld. Controleer het log voor meer informatie.

The file retrospect.log can be found at
[https://paste.kodi.tv/kogizebide.kodi](url)

I checked Omroep Flevoland => fine. Omroep Brabant gives "error retrieving list of items". VLC with RTV NH still works.

**Comment by basrieter** [comment]
Should be fixed now. Please download the zip again and install the new version.

**Comment by Johpin1** [comment]
The stream is correct. The picture next to Live-stream is still from AT5. Also the thumbnail in Favorites shows AT5.

**Comment by Johpin1** [comment]
I have downloaded the zip file => the live stream and the artwork have been fixed. Thanks!

**Comment by basrieter** [comment]
Great! I will see when I can do a new release.
