### ISSUE TITLE
GoPlay regio locked afleveringen kunnen geen streams vinden

### ISSUE THREAD

**Issue by PhyxionNL** [retrospect-addon/plugin.video.retrospect#1788]
### Describe the bug
Ik heb een GoPlay account die geactiveerd is met een Belgisch telefoonnummer en kan daarmee via de website en app van GoPlay alle streams bekijken die normaal alleen in België te bekijken zijn. Helaas werken deze streams niet in Retrospect, er komt een melding te staan dat er geen streams gevonden zijn.

### To Reproduce

1. GoPlay account inloggen.
2. Open bijvoorbeeld Bake Off Vlaanderen: https://www.goplay.be/video/bake-off-vlaanderen/bake-off-vlaanderen-s5/bake-off-vlaanderen-s5-aflevering-1#autoplay
3. Indien je een "normaal" account hebt zal GoPlay nu vragen om je locatie te bevestigen (eenmalig BE telefoonnummer nodig, werkt dan gewoon permanent).
4. Via webbrowser en app werkt het hierna perfect, maar via Retrospect niet.

Ik heb al meerdere keren de cache leeggehaald in Retrospect maar dit deed ook niks.

### Debuglog

The **debug** retrospect.log can be found here: [log.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/15083403/log.txt)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 21
- Retrospect version: laatste

**Comment by PhyxionNL** [comment]
Het zit in de Bearer token die aangemaakt wordt, ik heb de token van Retrospect even geprint en als ik daarmee de request uitvoer dan krijg ik ook de locked error.

**Comment by basrieter** [comment]
Ok, dan moet ik login eens herzien. Dat is altijd wel lastig. Maar zal een poging doen.

**Comment by basrieter** [comment]
> Het zit in de Bearer token die aangemaakt wordt, ik heb de token van Retrospect even geprint en als ik daarmee de request uitvoer dan krijg ik ook de locked error.

Heb jij een verschil de bearer kunnen zien?

**Comment by PhyxionNL** [comment]
> > Het zit in de Bearer token die aangemaakt wordt, ik heb de token van Retrospect even geprint en als ik daarmee de request uitvoer dan krijg ik ook de locked error.
> 
> Heb jij een verschil de bearer kunnen zien?

Het eerste stuk is hetzelfde (tot de eerste punt). De twee andere stukken (tot en vanaf de volgende punt) zijn verschillend.
Het tweede stuk is in de browser ook minder lang (951 chars vs 1039 in Retrospect), het eerste en laatste stuk zijn wel even lang.

**Comment by basrieter** [comment]
Ik ga deze wel fixen met #1809
