### ISSUE TITLE
Retrospect pincode for Videoland is not being stored on Android TV

### ISSUE THREAD

**Issue by Johpin1** [retrospect-addon/plugin.video.retrospect#1791]
### Describe the bug

On Android TV 11 you have to fill in the Retrospect pincode for Videoland everytime after starting Kodi. During a Kodi session it will be remembered. It seems to be the pincode has not been stored. For Linux and Android 13 tablet it will be stored on disk.

## Expected Behavior

After starting Kodi not every time asking for Retrospect pincode on Android TV when you choose Videoland. 

## Actual Behavior

You have to fill in the Retrospect pincode everytime you use Videoland after starting Kodi.

## Possible Fix

Remove Retrospect pincode from Videoland or store the pincode on disk.

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 20.5
- Retrospect version: 5.7.10

**Comment by basrieter** [comment]
Soo, I really need a debug log for that. Please provide one: https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Logging

**Comment by Johpin1** [comment]
The log file can be found in [https://paste.kodi.tv/patiwisozi.kodi](url). After switching Retrospect debug on, I started Videoland, entered the pin. After this a list has been shown.

**Comment by basrieter** [comment]
```
20240502 19:00:23 - [ERROR   ] - folderaction.py      - 134  - Plugin::Error Processing FolderList
20240502 19:00:23 - [ERROR   ] - folderaction.py      - 134  - | Traceback (most recent call last):
20240502 19:00:23 - [ERROR   ] - folderaction.py      - 134  - |   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.retrospect/resources/lib/actions/folderaction.py", line 55, in execute
20240502 19:00:23 - [ERROR   ] - folderaction.py      - 134  - |     media_items = self.__channel.process_folder_list(selected_item)
20240502 19:00:23 - [ERROR   ] - folderaction.py      - 134  - |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
20240502 19:00:23 - [ERROR   ] - folderaction.py      - 134  - |   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.retrospect/resources/lib/chn_class.py", line 191, in process_folder_list
20240502 19:00:23 - [ERROR   ] - folderaction.py      - 134  - |     self.loggedOn = self.log_on()
20240502 19:00:23 - [ERROR   ] - folderaction.py      - 134  - |                     ^^^^^^^^^^^^^
20240502 19:00:23 - [ERROR   ] - folderaction.py      - 134  - |   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.retrospect/channels/channel.videoland/videolandnl/chn_videolandnl.py", line 427, in log_on
20240502 19:00:23 - [ERROR   ] - folderaction.py      - 134  - |     result = self.__authenticator.log_on(username=username, channel_guid=self.guid,
20240502 19:00:23 - [ERROR   ] - folderaction.py      - 134  - |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
20240502 19:00:23 - [ERROR   ] - folderaction.py      - 134  - |   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.retrospect/resources/lib/authentication/authenticator.py", line 61, in log_on
20240502 19:00:23 - [ERROR   ] - folderaction.py      - 134  - |     v = Vault()
20240502 19:00:23 - [ERROR   ] - folderaction.py      - 134  - |         ^^^^^^^
20240502 19:00:23 - [ERROR   ] - folderaction.py      - 134  - |   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.retrospect/resources/lib/vault.py", line 32, in __init__
20240502 19:00:23 - [ERROR   ] - folderaction.py      - 134  - |     key = self.__get_application_key()  # type: bytes
20240502 19:00:23 - [ERROR   ] - folderaction.py      - 134  - |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
20240502 19:00:23 - [ERROR   ] - folderaction.py      - 134  - |   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.retrospect/resources/lib/vault.py", line 264, in __get_application_key
20240502 19:00:23 - [ERROR   ] - folderaction.py      - 134  - |     raise RuntimeError("Incorrect Retrospect PIN specified")
20240502 19:00:23 - [ERROR   ] - folderaction.py      - 134  - + RuntimeError: Incorrect Retrospect PIN specified
```

You are not specifying the correct Retrospect Vault Pin (which is not your videoload password).

**Comment by Johpin1** [comment]
I removed the previous retrospect.log and made  a new one.  In the old one at the time stamp 21:55 should have been looked at. I am surprised old information in this file is found.

The new retrospect.log does not contain the word "pin ". I opened Videoland, entered the pin code, saw a list appear and closed it.
[https://paste.kodi.tv/yareyelaxa.kodi](url)

**Comment by basrieter** [comment]
Can you try clearing the cache and cookies in Retrospect (via the add-on settings of Retrospect)?

**Comment by Johpin1** [comment]
Via the addon settings of Retrospect I have removed its cache and cookies. After entering Videoland with a pin code I closed Kodi. Still I have to reenter the pin code to open Videoland.

**Comment by basrieter** [comment]
Weird:

```
Existing but different authenticated user (t*w*c*l*6*@*e*s*a*s*c*m) found. Logging of first.
```

Seems like the JWT info differs from your actual login e-mail? Could that be?

**Comment by Johpin1** [comment]
Where could I find the JWT info? I assume it isn't in settings.json.

**Comment by basrieter** [comment]
During login there is a call to `https://gigya-merge.videoland.com/accounts.getAccountInfo`, the data it returns contains `profile` information with a `email`. This also happens on the site itself. Could you check with your browser and the Developer tools within the browser to see what the content is of your `https://gigya-merge.videoland.com/accounts.getAccountInfo` and if the `email` matches the value configured in Retrospect?

**Comment by Johpin1** [comment]
I logged into videoland.com, looked in Developer tools. It is unclear to me what the next step is.
I entered the URL https://gigya-merge.videoland.com/accounts.getAccountInfo and got the message I don't have the required permission to call. 

Could you describe the steps in more detail?

My issue does not happen when using Android 13 or Raspberry Pi OS, only for Android TV 11.

**Comment by basrieter** [comment]
With the developer tools open, and `perserve log` enabled, log into videoland.nl. In the list the `https://gigya-merge.videoland.com/accounts.getAccountInfo` will appear. 

![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/1310443/61f8ac5a-8555-43c8-bc8d-79f178dc6f64)

Click it and check it's response data.

**Comment by Johpin1** [comment]
In the profile of the response date the e-mail address is correct: it is the same as I entered in Retrospect for Videoland.

**Comment by basrieter** [comment]
Can you please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1791.zip. Set the logging to TRACE and check Videoland again. It won't be fixed but I added some extra logging. 

`Logger.trace(f"Account comparison: '{logged_on_user}' vs '{username}'")`

Please check the log and see what the line says.

**Comment by basrieter** [comment]
Great! So let me fix that by doing a capital-insensitive comparison.
