### ISSUE TITLE
Bladwijzer voor Nationaal -> NPO Start -> Live TV verwijst naar Nationaal -> NPO Start

### ISSUE THREAD

**Issue by Johpin1** [retrospect-addon/plugin.video.retrospect#1794]
### Describe the bug

Bladwijzer voor Nationaal -> NPO Start -> Live TV verwijst naar Nationaal -> NPO Start.

## Expected Behavior

Bladwijzer voor Nationaal -> NPO Start -> Live TV zou naar  Nationaal -> NPO Start -> Live TV moeten verwijzen.

## Actual Behavior

Als je Kodi opent en naar bladwijzers gaat, dan verwijst Nationaal -> NPO Start -> Live TV naar Nationaal -> NPO Start. Een bladwijzer voor "Recent" werkt wel goed.

### To Reproduce

1. Maak bladwijzer voor Nationaal -> NPO Start -> Live TV aan
2. Sluit en open Kodi
3. Ga naar bladwijzer voor Live TV en zie dat het naar Nationaal -> NPO Start verwijst

### Debuglog

The **debug** retrospect.log can be found here: De favourites.xml staat hieronder
```
<favourites>
    <favourite name="NPO Start" thumb="resource://resource.images.retrospect/channels/n/npolarge.png">ActivateWindow(10025,&quot;plugin://plugin.video.retrospect/?action=listfolder&amp;channel=channel.nos.nos2010-uzgjson&quot;,return)</favourite>
    <favourite name="Live TV" thumb="resource://resource.images.retrospect/channels/n/nosimage.png">ActivateWindow(10025,&quot;plugin://plugin.video.retrospect/?action=listfolder&amp;channel=channel.nos.nos2010-uzgjson&amp;pickle=ED8FDB9C-3870-11E2-B1C2-192A6288709B--92BF426D57BCBDF4C5559E5B7DD18902A0E86CC68D75E427C26BBA74D29729B2B06E2AFE&quot;,return)</favourite>
    <favourite name="Recent" thumb="resource://resource.images.retrospect/channels/n/nosimage.png">ActivateWindow(10025,&quot;plugin://plugin.video.retrospect/?action=listfolder&amp;channel=channel.nos.nos2010-uzgjson&amp;pickle=ED8FDB9C-3870-11E2-B1C2-192A6288709B--DAE52B80711EE1029C7006F95018D300A0E86CC68D75E427C26BBA74D29729B2&quot;,return)</favourite>
</favourites>
```

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 20.5
- Retrospect version: 5.7.10

**Comment by basrieter** [comment]
Ik heb een vaag vermoeden dat je je favourites.xml hebt overgezet van een ander systeem, of wellicht de user data van Retrospect zelf hebt opgeschoond?

**Comment by Johpin1** [comment]
De favourites.xml is niet overgezet van een ander systeem en ik heb deze niet zelf veranderd. Ik heb het volgende gedaan:
1. mv .kodi .kodi_werkend
2. Inputstream.adaptive en Retrospect geinstalleerd
3. Bladwijzers voor NPO Start, Live TV en recent aangemaakt.

Het is sinds ik Retrospect gebruik en het is bij verschillende besturingssystemen. De bladwijzer voor Live Radio heeft wel het juiste pad.

**Comment by Heleen-Heleen** [comment]
Bij werkt het ook al een hele tijd niet meer

**Comment by basrieter** [comment]
Hier werkt het gewoon. 

Dan heb ik echt een debug log nodig van Retrospect. Dus in Retrospect de logging op debug zetten, dan via de bladwijzers naar Live TV gaan en dan de log uploaden via de ingebouwde functie. De link dan hier posten

**Comment by Heleen-Heleen** [comment]
M

> Hier werkt het gewoon.
> 
> Dan heb ik echt een debug log nodig van Retrospect. Dus in Retrospect de logging op debug zetten, dan via de bladwijzers naar Live TV gaan en dan de log uploaden via de ingebouwde functie. De link dan hier posten

Klopt, maar na een paar uur niet meer

**Comment by Johpin1** [comment]
De snelkoppeling van retrospect.log: [paste.kodi.tv/jevibebive](url).

**Comment by basrieter** [comment]
De URL werkt niet. Klopt ie wel?

**Comment by basrieter** [comment]
Ik heb het niet ook nog een keer op een versie Android install gedaan, maar hier werkt het gewoon.

**Comment by Johpin1** [comment]
[https://paste.kodi.tv/jevibebive](url)

**Comment by Heleen-Heleen** [comment]
Https://kodi.tv/uzunekiluk

**Comment by basrieter** [comment]
Zouden jullie eens kunnen kijken of het volgende klopt:

In jullie `userdata/addon_data/plugin.video.retrospect/pickles` staan allemaal folders. Deze bestaan uit 2 karakters en dan weer twee karakters. Deze eerste 4 karakters komen overeen met die in de url van je bladwijzer:

Dus: 

`plugin://plugin.video.retrospect/?action=listfolder&amp;channel=channel.nos.nos2010-uzgjson&amp;pickle=ED8FDB9C-3870-11E2-B1C2-192A6288709B--92BF426D57BCBDF4C5559E5B7DD18902A0E86CC68D75E427C26BBA74D29729B2B06E2AFE` 

betekent dat er een folder is:

`userdata/addon_data/plugin.video.retrospect/pickles/ed/8f/` met daar ineen file: `ed8fdb9c-3870-11e2-b1c2-192a6288709b.store.z`

Klopt dat?

**Comment by Johpin1** [comment]
`~/.kodi/userdata/addon_data/plugin.video.retrospect/pickles/ed/8f $ ls`

`ed8fdb9c-3870-11e2-b1c2-192a6288709b.store.z`

Dit bestand is aanwezig.

**Comment by basrieter** [comment]
Gevonden. Zouden jullie deze eens kunnen installeren via de "Install from zip" optie: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1794.zip

Je zult de bladwijzers opnieuwe moeten aanmaken, maar daarna zouden ze moeten blijven werken.

**Comment by Johpin1** [comment]
Het werkt! Bedankt! Nu verwijst de bladwijzer voor Nationaal -> NPO Start -> Live TV naar Nationaal -> NPO Start -> LIve TV.

**Comment by basrieter** [comment]
Top! Ik ga het dan zo release ergens dit weekend.

**Comment by Heleen-Heleen** [comment]
Bedankt Bas, 

Om 9 uur vanochtend heb ik het geüpdatet, NPO Live TV geplaatst in de bladwijzers en het werkt nog steeds.
Normaliter verwijst deze dan naar NPO start

**Comment by basrieter** [comment]
See #1797

**Comment by Johpin1** [comment]
Bij het openen van Retrospect krijg ik nu een lijstje bestaande uit: bestanden, afspeellijsten en video add-ons. Retrosprect werkt helemaal niet meer.

**Comment by basrieter** [comment]
> Bij het openen van Retrospect krijg ik nu een lijstje bestaande uit: bestanden, afspeellijsten en video add-ons. Retrosprect werkt helemaal niet meer.

Ja, ergens gaat wat fout: https://github.com/retrospect-addon/plugin.video.retrospect/issues/1797#issuecomment-2132405697

**Comment by basrieter** [comment]
Misschien ook even Trace logging aanzetten, proberen en dan een logfile aanleveren.

**Comment by basrieter** [comment]
Heb wellicht iets gefixed: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1797.zip

**Comment by Johpin1** [comment]
Bij mij werkt het weer.

**Comment by basrieter** [comment]
Released in v5.7.12
