### ISSUE TITLE
Viewtype not saved after last update

### ISSUE THREAD

**Issue by BrodjagaRatnik** [retrospect-addon/plugin.video.retrospect#1797]
### Describe the bug

When I select a Viewtype it is not saved this is happening after the latest update.

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here: https://paste.kodi.tv/noguzorela.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.5.0
- Retrospect version: 5.7.11

**Comment by basrieter** [comment]
That is the result of the fix for #1794. I really don't know if both are possible.

**Comment by basrieter** [comment]
Could tell me "where" the viewtypes are not saved. Tell me exactly how you navigate and where it is not saved (or retrieved properly).

**Comment by BrodjagaRatnik** [comment]
TV Shows/Retrospect/NPO Start/Latest news **viewtypes are not saved**
TV Shows/Retrospect/NPO Start/Live Radio **viewtypes is saved**
TV Shows/Retrospect/NPO Start/Live TV **viewtypes is saved**
TV Shows/Retrospect/NPO Start/Popular **viewtypes are not saved**
TV Shows/Retrospect/NPO Start/Trending **viewtypes are not saved**
TV Shows/Retrospect/NPO Start/TV Shows **viewtypes are not saved**

**Comment by basrieter** [comment]
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1797.zip and see if that fixes it.

**Comment by BrodjagaRatnik** [comment]
I got error(s) https://paste.kodi.tv/eqogiwaseb.kodi

**Comment by basrieter** [comment]
Please enable TRACE logging, try again. Then provide the new logfile.

**Comment by basrieter** [comment]
Might have fixed it: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1797.zip

**Comment by BrodjagaRatnik** [comment]
This one fixed it Ty.

**Comment by basrieter** [comment]
Released in v5.7.12
