### ISSUE TITLE
TV4 play does not work

### ISSUE THREAD

**Issue by krille30** [retrospect-addon/plugin.video.retrospect#1800]
![Uploading Screenshot_20240614-140023_Kodi.jpg…]()

Hi

TV4play does not work no program is working at the moment. When pressing to refresh token under settings url referred to does not work. Would you know what could have happen?
Thanks for your great work with this fantastic addon.

Br
Kristian

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:
- Retrospect version:

**Comment by basrieter** [comment]
I need a full Retrospect DEBUG log. Enable debug logging in Retrospect, reproduce the problem and then upload the log via the built-in funcationality. Paste the resulting link (not content) here.

**Comment by krille30** [comment]
Sure link is https://paste.kodi.tv/uwifoleguc

**Comment by basrieter** [comment]
So, did you set a proper refresh token for TV4? 

- Open TV4 Play settings in Retrospect and select `set refresh token`.
- Follow the instructions to input the refresh token via a webgui:

![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/1310443/79e7aad8-79bf-4e04-ba77-b7356f99854c)

![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/1310443/75184f45-e112-46d5-8b95-c0ce549c5fe3)

Then try again.

**Comment by skogl** [comment]
I can confirm I have the same issue as @krille30 and it doesn't help to change refresh token, I've tried many times.

**Comment by krille30** [comment]
For me there is issue using refresh token because I get url http://busy:3145 which does not work so not an ip adress as expected. Earlier I have been able to use refresh token and also TV4 play. But last days TV4play has stopped working and now when trying to refresh token  I get above issue.

**Comment by matsarv** [comment]
I have no problem with the refresh token.
Maybe what I found has to do with this problem?

Got an error: "Error Processing FolderList".
Looked in the log file: https://paste.kodi.tv/afubaruzop.kodi and saw that millisecond was removed from isoString.
Changed two time_stamp formats to "%Y-%m-%dT%H:%M:%SZ" in chn_tv4se.py and everything was back as before.

**Comment by skogl** [comment]
Good find! So are there instructions how to "build" this addon somewhere or should I look in general Kodi addon bulding specs?

**Comment by basrieter** [comment]
OK OK, please all hold your horses here. The error about the date time issue is completely new, and was not present in the other logs. I will have a look at that. 

Besides that: `http://busy:3145/` means that Kodi returns `busy` as your hostname. I can't really help that. Use the the device's IP adres: http://xxx.xxx.xxx.xxx:3145 to make it work. To be clear: you **need to have a valid refreshtoken** to make TV4 work.

**Comment by basrieter** [comment]
Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1800.zip and try again. the date issue should be fixed.

**Comment by skogl** [comment]
Yes, it's working - Thank you!

**Comment by krille30** [comment]
Yes it works thanks so much for fantastic work and support as always.

**Comment by basrieter** [comment]
Released

**Comment by lennartzmta** [comment]
Thanks to all of you. Finally I managed to add  the refresh token to my android-tv. So now I'm happy again. 
Thanks basrieter for your amazing work.
