### ISSUE TITLE
SE: SVT Play Live TV and some newly added series are not playing.

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1801]
### Describe the bug

Playback failed
One or more items failed to play. Check the log for more information about this message.

## Expected Behavior

SVT Play Live TV and some newly added series will play.

## Actual Behavior

SVT Play Live TV and some newly added series are not playing.

### To Reproduce

1. 
2.
3.

### Debuglog

Live TV:
The **debug** retrospect.log can be found here: https://paste.kodi.tv/utizolirag.kodi
The Kodi.log can be found here: https://paste.kodi.tv/tahahequpa.kodi

Nautilus - kapten Nemos äventyr:
The **debug** retrospect.log can be found here: https://paste.kodi.tv/mubifapaye.kodi
The Kodi.log can be found here: https://paste.kodi.tv/cigitusowo.kodi

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 21.0
- Retrospect version: 5.7.12

**Comment by basrieter** [comment]
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1801.zip and see if it works again. Also verify that streams stop at the end....there was #1433 that complicated things.

**Comment by matsarv** [comment]
Live TV and Nautilus works again and tested some series, movies and others (quick jump to the last minute) and all stops OK.  Thanks!

**Comment by basrieter** [comment]
Great. Then I will create a new release this weekend.

**Comment by basrieter** [comment]
Released
