### ISSUE TITLE
Add 'Mark as seen' to mark all episode in a season as seen.

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1802]
### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

Add 'Mark as seen' to mark all episode in a season as seen to Context Menu when select a season folder

### Additional context

In folderaction.py

row 103:

```
from:
                # Get the context menu items
                context_menu_items = self._get_context_menu_items(self.__channel, item=media_item, store_id=parent_guid)
                kodi_item.addContextMenuItems(context_menu_items)
to:
                # Get the context menu items
                context_menu_items = self._get_context_menu_items(self.__channel, item=media_item, store_id=parent_guid)
                if folder:
                    mark_folder = LanguageHelper.get_localized_string(LanguageHelper.MarkAsSeen)
                    context_menu_items.append((mark_folder, 'Action(ToggleWatched)'))
                kodi_item.addContextMenuItems(context_menu_items)

```

**Comment by basrieter** [comment]
This can be tricky, as Kodi does not yet know what "child" items are present underneath. And that could lead  to a lot of loading of URL's due to the nesting of items. E.g. Doing this at a top level items, could result in 100+ API calls.

**Comment by matsarv** [comment]
OK, Just close this request.

**Comment by matsarv** [comment]
Is it possible to do this on the Season X folder level?

**Comment by basrieter** [comment]
> Is it possible to do this on the Season X folder level?

No, because I don't know how many levels are below it.

**Comment by matsarv** [comment]
OK
