### ISSUE TITLE
Videoland Live TV channels are not playing

### ISSUE THREAD

**Issue by jcjdammers** [retrospect-addon/plugin.video.retrospect#1804]
### Describe the bug

The Videoland Live TV channels are not playing.

## Expected Behavior

Channel(s) to play

## Actual Behavior

All Live TV channels from Videoland are not playing

### To Reproduce

1.  Nationaal --> Videoland --> Live TV
2. Choose one of the channels
3.

### Debuglog

The **debug** retrospect.log can be found here:

https://paste.kodi.tv/erepiyulir
https://paste.kodi.tv/vimaditite

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: Kodi (Omega) v21.0 using LibreELEC 12.0
- Retrospect version: 5.7.13

**Comment by basrieter** [comment]
These are paid options for Videoland.nl. Do you have a paid account at videoland.nl?

**Comment by jcjdammers** [comment]
Yes I have a paid account. The regular Videoland series and films are playing fine in the plugin.

**Comment by basrieter** [comment]
Could you provide a debug Retrospect log? The one you attached is a Kodi log.

**Comment by jcjdammers** [comment]
The debug log --> https://paste.kodi.tv/vimaditite

**Comment by jcjdammers** [comment]
An the "/storage/.kodi/userdata/addon_data/plugin.video.retrospect/retrospect.log" attached.
[retrospect.log](https://github.com/user-attachments/files/15846703/retrospect.log)

**Comment by basrieter** [comment]
Ok, so I need to know what the content of the `https://layout.videoland.bedrock.tech/front/v1/rtlnl/m6group_web/main/token-web-4/video/videoland_telekids/layout?nbPages=2` url is. Could you try live TV in the browser and check if this URL, or a similar one depending on stream, is present? 

If so, please attach the response here. Double check that there are no personal data in the response.

**Comment by jcjdammers** [comment]
When I type this URL in the brwoser:
https://layout.videoland.bedrock.tech/front/v1/rtlnl/m6group_web/main/token-web-4/video/videoland_rtl7/layout?nbPages=2

then it returns:
{
    "error": 498,
    "message": "Token expired/invalid"
}

**Comment by jcjdammers** [comment]
When I watch Live TV in the browser then I only see URLs like:
https://v2.videoland.com/rtl4/live
https://v2.videoland.com/event-6/live

**Comment by basrieter** [comment]
They `layout` url should be visible in the `network`-tab of the developer tools in Chrome.

**Comment by jcjdammers** [comment]
I have attached the response for URL:
https://layout.videoland.bedrock.tech/front/v1/rtlnl/m6group_web/main/token-web-4/live/rtl7/layout?nbPages=2

[response.json](https://github.com/user-attachments/files/15849424/response.json)

Hope this helps.

**Comment by basrieter** [comment]
That helps a bit. Another question: if you browse Videoland and go to "Live TV" you should see an url like this pass by: 

https://layout.videoland.bedrock.tech/front/v1/rtlnl/m6group_web/main/token-web-4/service/videoland_root/block/page_666ea375dd8356.25094621--7ed33394-c795-4219-a862-08cbc49515e3?nbPages=10

The content looks like this:

![image](https://github.com/retrospect-addon/plugin.video.retrospect/assets/1310443/f68c75ba-be4b-4aee-9b40-333ac1ab8d8f)

And it should contain the live channels under `content -> items`. Can you also send me that response?

**Comment by jcjdammers** [comment]
Strange but I do not see that URL.
I see only:
https://layout.videoland.bedrock.tech/front/v1/rtlnl/m6group_web/main/token-web-4/folder/206/layout?nbPages=2

With following response:
[response2.json](https://github.com/user-attachments/files/15857978/response2.json)

**Comment by basrieter** [comment]
Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1804.zip, try the live streams again and attach a DEBUG retruspect.log here. 

The streams still won't work, but I added some logging.

**Comment by jcjdammers** [comment]
I have installed the zip and run it as you requested (with debug log-level).
Kodi log-file --> https://paste.kodi.tv/uhecunizuw
retrospect.log file --> 
[retrospect.log](https://github.com/user-attachments/files/16129142/retrospect.log)

Hope this helps, thanks a lot.

**Comment by basrieter** [comment]
Ik zie waar het fout gaat, maar zonder betaalde account is het lastig fixen. Ik moet even gaan kijken hoe ik dat ga doen.

**Comment by jcjdammers** [comment]
Je kan volgens mij een gratis 14-dagen proef account aanmaken. Of anders wil ik mijn account wel tijdelijk delen.

**Comment by basrieter** [comment]
Fixed in #1813
