### ISSUE TITLE
Re-use the previous search result when the viewed program that was found using the search option is finished or stopped

### ISSUE THREAD

**Issue by ErikBrown2** [retrospect-addon/plugin.video.retrospect#1805]
### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

When you want to watch a few episodes of a program on NPOstart that are older than a week, then you need to use the search option. But after viewing each episode, the search option pops up again without any search text. So you have to enter the program name again. This becomes specifically a bit inconvenient when you do not know which episode of the found program episodes you want to watch. So you will play a short part of each episode till you find the episode that you are looking for. After trying one, you need to search again, etc etc.

I would like to suggest the following change for how to continue when the currently viewed program was found using the search option and playing of it stopped either because the program was finished or because the user stopped playing it:

When the program is finished or stopped, then automatically the same search result will be shown again allowing the user to select another episode from the search result. So no new search has to be performed since the search result of the initial search will be re-used.

### Describe alternatives you've considered

Alternative change 1:

If this is not possible, then when the currently viewed program is finished or stopped, then automatically a new search will be performed with the same search text as what the user entered before. So the user will still see the same program list as the list that resulted from the previous search but there will be some delay since the search has to be performed again. 

Alternative change 2:

If this is also not possible, is it then possible to enter the previously used search text as the new default search text and highlight Done? The user can then directly press Enter to perform the search using the default search text or modify the default search text to search for something different.

**Comment by basrieter** [comment]
I understand your pain. Let me think about the options. Howerver, I am currently swamped in work and stuff, so it might take bit of time.

**Comment by basrieter** [comment]
I figured out how to do this. Hope to find some time this week. And I think the solution fixes your pain.

**Comment by ErikBrown2** [comment]
Very nice!

**Comment by basrieter** [comment]
Can you test this version: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/feature-1805.zip

It should have new search for NPO, Videoland and Kijk. All others are broken. 

Kodi does behave weird and inconsistent when going back, which is annoying. Looking into that.

**Comment by ErikBrown2** [comment]
I have tested it quickly for now and it appears to work great! Only one note. The list of searches is maintained even after a restart of Kodi. If I highlight one of these searches and I press the C key, then I get a list of options that can be performed. But there is no "Remove from list" option here. There is a "Hide item" option but that causes a "Retrospect error" message to be shown. I think that it would be very nice if there could be a way to remove searches that are not required anymore in the future from the list. 

But the search works really nice now. No need anymore to search again for the next episode. Also it is very nice that the previously played episode is still highlighted after it is stopped. That makes it easy to determine which episode to select next.

**Comment by basrieter** [comment]
Good to hear this. It will only show the last 10 search actions, but I will look into it.

**Comment by basrieter** [comment]
I fixed the issue with the hiding of items (and some others). Can you live with the past 10 search actions, or does it really require a delete of items?

**Comment by ErikBrown2** [comment]
10 searches in the list is fine. I was afraid that all searches that were ever performed would stay in the list.

**Comment by basrieter** [comment]
Could you do a final check on the functionality? I added highlighting and fixed the search in all channels.

**Comment by ErikBrown2** [comment]
Still checking but for now I found a small issue. When you do a new search and play one of the programs from the search result, then go back to the top of the search result, then a search entry screen is shown. I do not think that this search entry screen should be here. When you press on Done without entering any text, then you come correctly to the list of searches. This issue does not happen when you use an old, existing search.

To check this, do the following:

- Do a new search on NPOstart
- Play a found episode and stop it
- Go to the top of the result list
- Here the not required search entry screen pops up
- Select done without search text to go back to the list with searches

**Comment by basrieter** [comment]
> Still checking but for now I found a small issue. When you do a new search and play one of the programs from the search result, then go back to the top of the search result, then a search entry screen is shown. I do not think that this search entry screen should be here. When you press on Done without entering any text, then you come correctly to the list of searches. This issue does not happen when you use an old, existing search.
> 
> To check this, do the following:
> 
> * Do a new search on NPOstart
> * Play a found episode and stop it
> * Go to the top of the result list
> * Here the not required search entry screen pops up
> * Select done without search text to go back to the list with searches

That is correct and I have not found a way to fix this. The problem is that going back on a new search will automatically bring you on the page that asked you for input via the keyboard. As Kodi does navigation, I have not yet found a way of doing this. 
With older search results, the step with the keyboard input is skipped and this makes going back work.

I will ask my Kodi team members if there are any ideas on this.

**Comment by ErikBrown2** [comment]
There appears to be no filtering of the search text. The following characters cause a "Retrospect error" message:

?\*+[()
{}%]$; give also Retrospect error but with - No episodes found for the selected item -

**Comment by ErikBrown2** [comment]
\ also gives an error

**Comment by ErikBrown2** [comment]
A search on Kijk.nl that does not result in a found episode gives the following error message: Retrospect - Error No episode found for the selected item 
To test it, search for instance for hhh

**Comment by ErikBrown2** [comment]
That is the same for Videoland. No search result also gives the error.

**Comment by basrieter** [comment]
I see, it is the highlighter that is causing the issue.

**Comment by basrieter** [comment]
Fixed the special chars issue.

**Comment by ErikBrown2** [comment]
Yes, indeed. It is fixed. This new search is really nice. It makes it much easier to watch old episodes.
