### ISSUE TITLE
SE: SVT play could not playback some url's

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1808]
### Describe the bug

SVT play could not playback some url's

## Expected Behavior

Play url's.

## Actual Behavior

Could not playback the url
IndexError: list index out of range

### To Reproduce

1.  Play any items from Filmer
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/eyufofahez.kodi

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 21.0
- Retrospect version: 5.7.13

**Comment by basrieter** [comment]
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1808.zip

**Comment by matsarv** [comment]
Tested some steams in 'Movies' and some streams in 'New on SVT Play' and now it's working again.
Greate work!

**Comment by basrieter** [comment]
Will release an update soon.
