### ISSUE TITLE
GoPlay werkt niet meer

### ISSUE THREAD

**Issue by PhyxionNL** [retrospect-addon/plugin.video.retrospect#1809]
### Describe the bug
Sinds vandaag werkt GoPlay niet meer.
De api lijkt aangepast te zijn en zit grotendeels onder een nieuwe URL (https://api.goplay.be/web/v1/). Sommige URLs gaan via goplay zelf (https://www.goplay.be/programmas?type=series en https://www.goplay.be/programmas?type=movie).

### To Reproduce

1. Open Vier.
2. Zie een lege lijst.

### Debuglog

```
20240704 21:50:50 - [DEBUG   ] - chn_class.py         - 1086 - Found 1 DataParsers for 'https://www.goplay.be/api/programs/popular/vier'
20240704 21:50:50 - [INFO    ] - urihandler.py        - 547  - Performing a GET for https://www.goplay.be/api/programs/popular/vier
20240704 21:50:50 - [ERROR   ] - urihandler.py        - 555  - GET failed with '404 Not Found' (0:00:00.081712) for https://www.goplay.be/api/programs/popular/vier
```

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: laatste
- Retrospect version: laatste

**Comment by basrieter** [comment]
Ik heb echt een volledige debug logfile nodig als attachement.

**Comment by PhyxionNL** [comment]
> Ik heb echt een volledige debug logfile nodig als attachement.

Bij deze:
[log.txt](https://github.com/user-attachments/files/16102576/log.txt)

**Comment by basrieter** [comment]
Jammer genoeg, vereist dit een complete rewrite van het kanaal. Ik ga kijken hoe ver ik kom.

**Comment by basrieter** [comment]
Please check https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1809.zip for an initial attempt.

**Comment by PhyxionNL** [comment]
Het werkt goed @basrieter. Ook de afleveringen die eerst niet werkten zijn nu te zien 😎

**Comment by basrieter** [comment]
Top! Moet alleen even kijken dat de films ook gaan werken.

**Comment by basrieter** [comment]
I think most of the videos should play now. I need to add a GoPlay channel as they are having content that belongs to none of the other channels.

**Comment by PhyxionNL** [comment]
Volgens mij is er ook geen apart Vier/Vijf/Zes e.d. meer, in de app is gewoon alles GoPlay. Kunnen ze niet gewoon samengevoegd worden tot één kanaal?

**Comment by basrieter** [comment]
Dat kan zeker.  Het ene sluit het andere niet uit.

**Comment by basrieter** [comment]
GoPlay zit er in. De andere kan je, als je dat wilt, verbergen via het context menu.

**Comment by basrieter** [comment]
Ik heb nog wat aangepast aan GoPlay. Iets overzichtelijker zo. Verder zijn er een aantal DRM beschermde streams die het gewoon niet lijken te doen. Hun DRM License server accepteert de input niet van Kodi.

**Comment by PhyxionNL** [comment]
Welke streams werken niet bij je? Bijvoorbeeld Bake Off Vlaanderen werkt hier nu prima.
Wat nog handig zou zijn is een toevoeging van een seizoensfolder zoals bijvoorbeeld ook bij de NPO. 

Ik had maar even een hele reeks geprobeerd, en het viel mij op dat deze geen items in wil laden: https://www.goplay.be/de-slimste-mens-het-leukste-van
Deze lijkt ook anders te zijn dan de overige series, hier zit geen normaal seizoen bij.

[kodilog.txt](https://github.com/user-attachments/files/16321717/kodilog.txt)

**Comment by basrieter** [comment]
Bijvoorbeeld de afleveringen van Cops down het niet omdat ze een verified widevine app nodig hebben. En dat is Kodi niet. Behalve onder Android omdat we dan via de Android speler afspelen

**Comment by PhyxionNL** [comment]
Ah, ik zie het inderdaad. Ik had alleen afleveringen van Vier geprobeerd en die lijken het allemaal te doen verder.

**Comment by basrieter** [comment]
Zal nog maar de seizoenen kijken.

**Comment by basrieter** [comment]
Seizoenen gefixed: hij toont nu folders, tenzij er maar 1 is, dan toont hij die items.
