### ISSUE TITLE
URplay episode listings don't work

### ISSUE THREAD

**Issue by ChrisIse** [retrospect-addon/plugin.video.retrospect#1812]
### Describe the bug

When clicking on a series name you get an error that retrospect cannot retrieve the list.
Single episodes play as intended.

## Expected Behavior

The episodes should be listed.

## Actual Behavior

Error message

### To Reproduce

1. Choose URplay -> Tv shows -> Algoritmen
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/jotebujoti

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 20.5
- Retrospect version: 5.7.13

**Comment by basrieter** [comment]
Will look into it.

**Comment by basrieter** [comment]
Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1812.zip via the "Install from zip" option in Kodi and let me know if this fixes things?

**Comment by ChrisIse** [comment]
Yep, it's working. However, I had saved series as favourites, and those
links don't work anymore ("No episodes found..."). But that's a very minor
issue, I can just create them again.
Thanks.

Den sön 21 juli 2024 kl 00:39 skrev Bas Rieter ***@***.***>:

**Comment by basrieter** [comment]
That is good to hear. The old favourites are those  with broken URL's so you will have to recreate those.
