### ISSUE TITLE
Videoland only plays 960x540

### ISSUE THREAD

**Issue by powermarcel10** [retrospect-addon/plugin.video.retrospect#1813]
Hi,

I am wondering, is 960x540 the max resolution to play for Videoland in Restrospect? Or could it be a setting..

I tried to play with the settings in inputStream Adaptive but the resolution will not go any higher.

**Comment by basrieter** [comment]
Voor zover ik weet is dit de maximale resolutie. Wellicht dat betaalde videoland-accounts een hogere resolutie hebben.

**Comment by powermarcel10** [comment]
Hoi Bas, dank vikr je reactie. Ik ben ingelogd met een betaald account. Zou mooi zijn als er een mogelijkheid bestaat om het in een hogere resolutie te kunnen bekijken. Om die reden kijk ik het nu niet via Kodi. NPO plus werkt wel gewoon netjes in FullHD.

**Comment by basrieter** [comment]
Dan zal ik met een betaalde account wat moet gaan uitzoeken. Deze heb ik zelf niet en ik ben al door mijn gratis dagen heen.

**Comment by powermarcel10** [comment]
Hoi Bas,

Ik gebruik een account van een vriendin, dus die geef ik liever niet weg. Maar ik heb zelf even een proefaccount aangemaakt die je mag gebruiken als je wilt.

Gebruikersnaam: marcel.visser.groningen@hotmail.com
Wachtwoord: ZrJ#@6pYFRePsy

**Comment by basrieter** [comment]
Thanks! Ik ga kijken.

**Comment by basrieter** [comment]
Ik heb het bekeken en het is als volgt: Voor HD streams een extra DRM nodig, echter, in de browser (en dus ook in Kodi) krijgen we enkel een DRM key terug voor SD content:

![image](https://github.com/user-attachments/assets/cf002856-08ac-440e-945e-baf40fd5d11c)

Ik zal de code wat aanpassen zodat HD content zonder extra DRM, wel geselecteerd wordt. Maar ik gok dat dit dus niet gaat voorkomen.

**Comment by basrieter** [comment]
Zou je https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1813.zip eens kunne installeren en kunnen kijken of Videoland nog werkt? Ik check nu of er een HD stream is zonder DRM. Als dat zo is, dan speelt Kodi die. 

Heb er nog geen kunnen vinden trouwens. Dus als je er eentje vindt, dan hoor ik het graag.

**Comment by powermarcel10** [comment]
Hoi Bas,

Dank voor de testversie. De addon werkt na installatie van deze versie nog steeds. Nog wel steeds dezelfde resolutie. Volgens mij is praktisch alle content op Videoland HD. Maar middels de addon ook nog geen content kunnen vinden dat daadwerkelijk in HD wordt afgespeeld. Live tv werkt trouwens niet. Maar ik weet niet of dat met een vorige versie wel zo was.

**Comment by basrieter** [comment]
Ok, ik zal nog naar de live TV kijken dan.

**Comment by basrieter** [comment]
Als het goed is doen de live kanalen het nu weer, net als de films.

**Comment by powermarcel10** [comment]
Thanks! Live TV werkt inderdaad weer. Well 1 opmerking; In de map met live TV worden de programma namen weergegeven van de programma's die op dat moment spelen. Mijn voorkeur zou zijn dat de kanaalnaam (ook) wordt vermeld.

Voor wat betreft de resolutie.. Is hier denk je nog een mouw aan te passen? Of gaat het hem echt niet worden..

**Comment by basrieter** [comment]
> Thanks! Live TV werkt inderdaad weer. Well 1 opmerking; In de map met live TV worden de programma namen weergegeven van de programma's die op dat moment spelen. Mijn voorkeur zou zijn dat de kanaalnaam (ook) wordt vermeld.
> 
> Voor wat betreft de resolutie.. Is hier denk je nog een mouw aan te passen? Of gaat het hem echt niet worden..

Ik kan kijken naar de naam, maar weet niet of dat in de API zit. 
De resolutie gaat hem echt niet worden: Dat kan enkel op ondersteunde hardware, en daarop draait Kodi eigenlijk nooit (behalve Android).

**Comment by basrieter** [comment]
I added channel names: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1813.zip

**Comment by basrieter** [comment]
Closed with 25d09bc9

**Comment by powermarcel10** [comment]
> > Thanks! Live TV werkt inderdaad weer. Well 1 opmerking; In de map met live TV worden de programma namen weergegeven van de programma's die op dat moment spelen. Mijn voorkeur zou zijn dat de kanaalnaam (ook) wordt vermeld.
> > Voor wat betreft de resolutie.. Is hier denk je nog een mouw aan te passen? Of gaat het hem echt niet worden..
> 
> Ik kan kijken naar de naam, maar weet niet of dat in de API zit. De resolutie gaat hem echt niet worden: Dat kan enkel op ondersteunde hardware, en daarop draait Kodi eigenlijk nooit (behalve Android).


Oké, duidelijk. Echter.. Ik gebruik Android TV op een nvidia shield en ik denk dat er best veel mensen zijn die deze setup draaien. Zou het daarop wel aan de praat te krijgen moeten zijn?

**Comment by powermarcel10** [comment]
> I added channel names: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1813.zip

Top! Ik ga het proberen. Dankjewel!

**Comment by basrieter** [comment]
Inmiddels ook al officieel gereleased
