### ISSUE TITLE
NPO zoek resultaat geeft geen datum voor de gevonden episodes.

### ISSUE THREAD

**Issue by ErikBrown2** [retrospect-addon/plugin.video.retrospect#1817]
### Is your feature request related to a problem? Please describe

Zoeken met Retrospect op NPOstart resulteert in een lijst met episode namen maar zonder datum. Als je dezelfde zoek opdracht intypt op de NPOstart site dan wordt er voor elke gevonden episode wel een datum getoond. Zou het mogelijk zijn om de datum weer te geven voor elke gevonden episode, net zoals gedaan wordt op de NPOstart website? Zie als voorbeeld de onderstaande screen captures.

### Describe the solution you'd like

Dat de datum/tijd die op de NPOstart website bij elke gevonden episode staat, ook door Retrospect getoond wordt.

### Additional context

![Zoeken NPO Start](https://github.com/user-attachments/assets/42859729-f166-4c52-8860-99ba1316cefc)

![Zoeken met Retrospect](https://github.com/user-attachments/assets/923ba13d-e0c0-4a40-a259-f09cc3546d80)

**Comment by Heleen-Heleen** [comment]
![Screenshot_20240725-201329](https://github.com/user-attachments/assets/7d8db98b-4420-4dd1-8668-1e0258c0ea54)

**Comment by ErikBrown2** [comment]
Hi Heleen, dank je wel voor jouw antwoord. Ik heb heb de sortering zoals in jouw screenshot zichtbaar is op datum gezet en nu zie ik inderdaad ook de datum. Het lijkt mij een beetje vreemd dat de datum alleen dan zichtbaar wordt. Maar mijn probleem is in ieder geval opgelost. Dank je wel.

**Comment by basrieter** [comment]
Er is niet echt een probleem volgens mij. Enkel dat ik er voor gekozen heb om de resultaten in de volgorde te laten staan zoals de NPO deze teruggeeft. Er vanuitgaande dat de eerste het beste resultaat is. 

Jammer genoeg, bepaald Kodi dan zelf dat bij een "Unsorted" view, de datum niet het tweede info veld is dat wordt getoond.
