### ISSUE TITLE
Nieuwe zoek highlight wordt toegepast op favorieten

### ISSUE THREAD

**Issue by PhyxionNL** [retrospect-addon/plugin.video.retrospect#1818]
### Describe the bug
1. Open NPO Start.
2. Zoeken
3. Zoek bijvoorbeeld op: 2Doc
4. Nu wordt alle "2Doc" geel gemaakt.
5. Alleen wanneer je deze nu toevoegd als favoriet (de standaard Kodi variant - Add to favorites) wordt (een gedeelte van) de naam daarvan ook geel.

## Expected Behavior
Geen (gedeeltelijk) gele titel.

## Actual Behavior
Een gele titel.

### To Reproduce
Zie bug report.

### Debuglog

The **debug** retrospect.log can be found here:
[debug.log](https://github.com/user-attachments/files/16401299/debug.log)

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: laatste
- Retrospect version: laatste

**Comment by basrieter** [comment]
Denk je nog eens iets leuks te doen voor het zoeken. Dan zal ik het highlighten uit moeten zetten ben ik bang.

**Comment by basrieter** [comment]
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1818.zip

**Comment by PhyxionNL** [comment]
Top, werkt weer goed 👍🏻
