### ISSUE TITLE
Retrospect crashes kodi on clean Ubntu 24.04 install

### ISSUE THREAD

**Issue by wavemaking** [retrospect-addon/plugin.video.retrospect#1819]
## Bug report
I made a new install on Ubuntu 24.04 with kodi 2.20 being the latest release from ubuntu channels. I populated the music database and installed retrospect. On Retrospect installing kodi already crashed. But when re-opening kodi Retrospect does seem to be installed. Nevertheless, when starting Retrospect, kodi freezes for a moment and then crashes. I can reproduce this every time I start kodi and retrospect. I have attached a kodi log (with debugging enabled).

## Expected Behavior
Kodi should install and run without crashing.

## Actual Behavior
Kodi crashes on installing and running Retrospect.

### To Reproduce
1. Install Ubuntu 24.04
2. Install kodi
3. Install retrospect ( <- already crashing )
4. Restart kodi and then retrospect ( <- crash )

### Debuglog
Retrospect did no yet generate a log file. The plugin.video.retrospect folder exists, but is empty. I did however attach a general kodi log file (with debugging):
[kodi.log](https://github.com/user-attachments/files/16446674/kodi.log)
 
## Additional context or screenshots (if appropriate)
I was trying to install and run Retrospect. The GUI didn't show any special information.

### Your Environment
- Ubuntu 24.04 on a x86 64 bit machine
- Kodi version: 2.20
- Retrospect version: 5.7.14

**Comment by basrieter** [comment]
Is there also a crash dump present? Retrospect itself can't crash Kodi. It merely uses the local Python install and Kodi ABI. So perhaps see if your local Python is up to date?

**Comment by wavemaking** [comment]
If with a crash dump you mean the one produced by kodi, here it is. 
[kodi_crashlog-20240731_221312.log](https://github.com/user-attachments/files/16447675/kodi_crashlog-20240731_221312.log)

Python is at version 3.12.3-0ubuntu1. After installing I did upgrade the system, so this is the latest that's offered by Ubuntu. 

When you say Retrospect can't crash kodi, I'm surprised. Because a crash really happens exactly when I start Retrospect in the addon menu. But I must, say I hardly did anything else, so I realise now that I cannot completely ascertain that simply opening an addon triggers something in kodi which would also happen with another addon. I will experiment a bit more to see if I can make kodi crash in some other way. I did listen a bit too music for some time (just local files). Kodi was stable with that.

**Comment by neo1973** [comment]
Kodi 20.5 doesn't work on systems using Python 3.12, see https://github.com/xbmc/xbmc/issues/24069 and  https://bugs.launchpad.net/ubuntu/+source/kodi/+bug/2063358

**Comment by wavemaking** [comment]
neo1973, well that explains it indeed. I tried with some other addons. Indeed they also crash kodi. So this is not Retrospect bug, but a kodi-ubuntu bug. Please close.

**Comment by basrieter** [comment]
Hope you find a solution.
