### ISSUE TITLE
Videoland Issue Retrospect 5.7.15

### ISSUE THREAD

**Issue by didamsko** [retrospect-addon/plugin.video.retrospect#1824]
### Describe the bug

Werkt nog in Retrospect 5.7.14 maar niet meer in Retrospect 5.7.15: ik heb een RTL 4 programma, dat ik paar dagen kan terugkijken via Videoland, toegevoegd aan Favorieten en normaal open ik dat in Favorieten en krijg ik de lijst met seizoenen/afleveringen maar dat werkt niet meer in Retrospect 5.7.15, dan krijg ik een 'Error retrieving list of items', als ik terug ga naar Retrospect 5.7.14 werkt het weer. 

## Expected Behavior

Open de Favoriet en krijg lijst met seizoenen/afleveringen

## Actual Behavior

Open de Favoriet en krijg 'Error retrieving list of items'.

### To Reproduce

1. Open Retrospect (versie 5.7.15)
2. Ga naar Videoland
3. Open 'Best bekeken programma's'
4. Open bijvoorbeeld 'B&B Vol Liefde'

### Debuglog

The **debug** retrospect.log can be found here:
[retrospect.debug.log](https://github.com/user-attachments/files/16537471/retrospect.debug.log)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: CoreELEC 21.0-Omega
- Retrospect version: 5.7.15

**Comment by basrieter** [comment]
Inderdaad, daar zat iets fout. In deze versie zou het weer moeten werken: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1824.zip

Installeren van via de "Install from  zip" optie in Kodi. Ik zal vanavond een patch de deur uit doen.

**Comment by didamsko** [comment]
Sorry voor de late feedback, was hele dag in de weer. Maar bovenstaande fix net geprobeerd en alles werkt inderdaad weer als vanouds! Dank voor de doorlopende en vlotte ondersteuning!

**Comment by basrieter** [comment]
Toppie! De release is net de deur uit! Veel plezier met Kodi en Retrospect.

**Comment by didamsko** [comment]
Dank! ik zag het en heb versie 5.7.16 er inmiddels op staan :)
