### ISSUE TITLE
URPlay bookmarks constantly unlinks 

### ISSUE THREAD

**Issue by ChrisIse** [retrospect-addon/plugin.video.retrospect#1827]
### Describe the bug

I have a handful of bookmarks for UrPlay shows, but lately they have been broken multiple times, and I have to recreate them each time. This is rather annoying. Perhaps it's due to UR changing the links? If this behavior is avoidable in Retrospect it would be really nice.

## Expected Behavior

Bookmarks for URPlay works continuously.

## Actual Behavior

Bookmarks break.

### To Reproduce

1.  Create a bookmark
2. Wait a few days
3. Try to access the bookmarked show

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/xapupikeku

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 20.5
- Retrospect version: 5.7.16

**Comment by basrieter** [comment]
From what I can tell from the logs, it is the URL that changes at the UR Play side. I will see if they have something like a perma-link.

**Comment by basrieter** [comment]
I see the problem and I can fix it!

**Comment by basrieter** [comment]
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1827.zip via the "Install from zip" option in Kodi.

**Comment by ChrisIse** [comment]
Thank you very much for such a quick solution! I will try it tonight.
Good work 🙂

Den ons 14 aug. 2024 13:28Bas Rieter ***@***.***> skrev:

**Comment by ChrisIse** [comment]
I assume it works. I can verify it after some time of use.

**Comment by basrieter** [comment]
Great! I will include it in the next official release.
