### ISSUE TITLE
Add support for NPO Plus "Volgen/Volgend" functionality

### ISSUE THREAD

**Issue by jcjdammers** [retrospect-addon/plugin.video.retrospect#1828]
NPO Plus heeft weer de functionaliteit teruggebracht om programma's te volgen.
Zou dit ook weer ondersteund kunnen worden door Retrospect (eerder was er een "Favorieten" functie)?
Dank je.

**Comment by basrieter** [comment]
Vast wel, maar ik was vooral aan het afwachten hoe NPO het weer zou terug brengen na hun nieuwe app.

**Comment by basrieter** [comment]
Ik heb een eerste poging gedaan. Zou je deze eens kunnen installeren in Kodi en kunnen proberen: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/feature-1828.zip

De namen van folders zijn nog niet OK, maar het zou wel moeten werken.

**Comment by jcjdammers** [comment]
Het werkt inderdaad, top !
Zoals je zegt de foldernamen (het sub-nivo na het profiel) bevatten wat aparte teksten ("v0, v1, anonymous") maar zijn verder wel te begrijpen.
Dank je.

**Comment by basrieter** [comment]
Inmiddels zouden de namen ook weer ok te zijn. Als je de zip opnieuw download en installeert, dan zou dat ook moeten werken.

**Comment by jcjdammers** [comment]
Ik heb de zip opnieuw gedownload, maar de installatie mislukt nu (meerdere keren geprobeerd).
Zie mijn Kodi-log:
https://paste.kodi.tv/ineyugixij

Installatie vanuit de Kodi repo gaat gewoon nog goed.
Ik had eerst een de-install gedaan (maar dat hat ik de eerste keer ook).

**Comment by basrieter** [comment]
Ik zie een aantal fouten rondom het download en installeren van afhankelijkheden en een error over het niet kunnen uitpakken van de zip. Ik zou de zip nog eens opnieuw downloaden en opnieuw proberen te installeren.

**Comment by basrieter** [comment]
Het enige wat dus niet gebeurd is dat als je in Kodi afspeelt en middenin stopt, dat hij dat dan weer aangeeft bij NPO. Weet niet of dat mogelijk is namelijk.

**Comment by jcjdammers** [comment]
dat lijkt niet te werken inderdaad, maar is voor mij minder belangrijk. Alle programma's die ik volg kan ik nu tenminste snel terugvinden.

**Comment by basrieter** [comment]
I also fixed the search.

**Comment by basrieter** [comment]
CLosed with 1e784aa4
