### ISSUE TITLE
Kijk.nl no longer works (timeout occurred waiting for playback)

### ISSUE THREAD

**Issue by BrodjagaRatnik** [retrospect-addon/plugin.video.retrospect#1829]
### Describe the bug

The programs of Kijk.nl result in "One or more items failed to play. Check the log for more information about this message."

## Actual Behavior

I get  "One or more items failed to play. Check the log for more information about this message."

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/livexofasu.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 21.0.0 Git:21.0-Omega
- Retrospect version: 5.7.16

**Comment by basrieter** [comment]
It plays without any issues here? Could you retry?

**Comment by BrodjagaRatnik** [comment]
Still the timeout only with Kijk.nl others are streaming good it is not my connection (KPN leased line)

**Comment by basrieter** [comment]
So try updating WideVine, this can be done via de Retrospect Settings:
![image](https://github.com/user-attachments/assets/66c3db77-846a-40d4-b77a-ffb7593231fa)

**Comment by basrieter** [comment]
That is good to hear! Enjoy Kodi and Retrospect.
