### ISSUE TITLE
TV4 Some episodes don't work

### ISSUE THREAD

**Issue by rytmisk** [retrospect-addon/plugin.video.retrospect#1831]
### Describe the bug

I just wanted to finish watching the Swedish series Gåsmamman yesterday and realized that only some episodes work. In season 6 (last season), only episodes 2 and 5 are playable. The rest either say that an error occurred or it just spins and then nothing. Tested again today.
Even tested the series Hamilton and see that the behaviour is the same.  In season 2 Episodes 6 and 8 do not work while the others do. In the series "Ondskan" no episodes work.

## Expected Behavior

I would love all episodes to work :-)

## Actual Behavior

Some episodes and series do not play.

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 21.1
- Retrospect version: 5.7.16

**Comment by basrieter** [comment]
I need a full debug log file: enable debug logging in Retrospect, try playing an item that fails, then upload the logfile using the built-in functionality: post the LINK (don't copy paste) here.

**Comment by rytmisk** [comment]
Ah - sorry about that:
Here it is: [https://paste.kodi.tv/ubedetebik](https://paste.kodi.tv/ubedetebik)

All the best!
Ketil

**Comment by matsarv** [comment]
All above mentioned Series and Episodes can now be played.

Time to close this?
