### ISSUE TITLE
Cannot play anything from Videoland

### ISSUE THREAD

**Issue by 1marc1** [retrospect-addon/plugin.video.retrospect#1834]
### Describe the issue

First of all, I am not sure if this is a bug or if I am doing something wrong.

I created a free account on videoland.com. I added the account details in Retrospect (version 5.7.17). When I want to play anything, a message in Kodi pops up saying that something went wrong. Nothing is played back.

While preparing to log this issue here, I enabled debug logging so I could recreate the problem and capture the log. After enabling debug logging, I found that playback was working. I added a TV series to a Retrospect favourite.

I then disabled debug logging (back to INFO) and I found that I could no longer open the Videoland section.
I enabled debug logging again, but again I could not open Videoland (let alone find something to watch).

## Expected Behavior

1. Videoland opens and shows the contents
2. Upon selection, the selected video is played back.

## Actual Behavior

1. In first instance, the selected video was not played back.
2. In second instance, Videoland would not open at all.

### To Reproduce

1. I tried random episodes from different channels like RTL4, RTL5, RTL7 and RTL8
3. None would playback.
4. The CRITICAL messages in the log are always the same.

### Debuglog

The retrospect.log showing the CRITICAL messages can be found here: https://pastebin.com/evVJNv3M
The **debug** retrospect.log can be found here: https://pastebin.com/h6WTdtkq

## Additional context or screenshots (if appropriate)

It looks like the problem occurs when I try to add something from Videoland to my Retrospect favourites.
Doing so will cause an error and following that error, I am no longer able to use anything in the Videoland section, including opening Videoland itself.

Following this, I tried to disable/enable Retrospect but this doesn't help. I have to reboot the Raspberry-Pi in order to make it work again.

Further testing shows that I can add something to the Kodi favourites.

Unsure where this leaves this report. When I started writing it, I was unable to playback anything from Videoland. By the time I have created and uploaded the logs, I can playback from Videoland, as long as I don't attempt to add anything to Retrospect favourites.

I am wondering if any of this has to do with the fact that I am working on this in the evening and I have a faint idea that things started working after midnight. I created the Videoland account before midnight. See date/time stamps in the two log files. It could be coincidence.

Happy for you to close this.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 21
- Retrospect version: 5.7.17

**Comment by basrieter** [comment]
This is caused by your Python environment on your Linux system: 

`ImportError: PyO3 modules may only be initialized once per interpreter process`

I would suggest try downgrading `cryptography` and see if that solves your issues.

**Comment by 1marc1** [comment]
I had a look around the internet and found the `cryptography` downgrading advise to seemingly apply to people who were using version 40 or 41. The advise seems to be to downgrade to version 38. For example [here](https://github.com/retrospect-addon/plugin.video.retrospect/issues/1724). In my case, I am using version 38; at least that's what it looks like.

```
$ pip list | grep cryptography
cryptography                       38.0.4
types-cryptography                 3.3
```

FWIW, I am running Kodi 21 on a fresh install of Raspberry Pi OS 12 (64 bit).

**Comment by basrieter** [comment]
And what Python version are you running?

**Comment by 1marc1** [comment]
Python version is 3.11.2. This is a fresh install of "Raspberry Pi OS with Desktop 64-bit" on an 8 GB Raspberry Pi 5.

**Comment by basrieter** [comment]
Ok, so I would suggest running LibreElec instead of Rasbperry Pi OS. LE is much more optimized and it will have less issues with Python conflicts like you are having.

**Comment by basrieter** [comment]
Please create a debug log for that. Enable debug logging in Retrospect, try playback again and then upload a new log file.

**Comment by 1marc1** [comment]
I created the debug log. Here is the one for Kodi: https://pastebin.com/5uFdvPAD

Whenever I upload the one for Retrospect, pastebin keeps telling me: "This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff."

The log is about 260 KB; FAQ tells me the limit is 512 KB. Not sure why it isn't working. I will look for an alternative.

**Comment by 1marc1** [comment]
Ok, this should be the retrospect.log with debugging enabled: https://privatebin.net/?d326b51b11319a33#BByoxZ3w4eunrQqwhntuFkfRdP4sZiuVPaqLcCxFGS5T

**Comment by basrieter** [comment]
Can you install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1834.zip, and try again. It won't fix anything, but logs a bit more. Then upload the log debug `retrospect.log` again. 

I checked the upload feature, and it works as expected, so please check that you are not mistaking  a zero for an "o" or something.

**Comment by 1marc1** [comment]
Thank you for looking into this. I have installed the ZIP file and tried again. The debug logs for retrospect are here: https://privatebin.net/?7d1b8d2265fcab0e#6TqtQJbsJ5peG7dF8evDxZF9qkzU3r2k75o3PEGLEQrM

After creating the debug log, I tried watching a couple of other programs as well as a trailer for something, but nothing could be played back.

**Comment by basrieter** [comment]
Seems like the link expired?

**Comment by 1marc1** [comment]
Try this link: https://hastebin.com/share/asemakugiy.bash

**Comment by basrieter** [comment]
From where are you trying to play? The error I see is: 

> "reason": "geoBlocked"

**Comment by 1marc1** [comment]
I am connecting using a VPN terminating in The Netherlands. I will see if my VPN provider has a different end-point in The Netherlands. I will report back.

**Comment by 1marc1** [comment]
I have setup a different profile for the VPN, which uses a different endpoint IP address. However, playback does not work and when looking through the debug log, I still see "geoBlocked" coming up. I know this is out of your hands, but would it be possible to update Retrospect to say that the video could not be played back due to being geoBlocked? At the moment it just says "Cannot start playback".

**Comment by basrieter** [comment]
> I have setup a different profile for the VPN, which uses a different endpoint IP address. However, playback does not work and when looking through the debug log, I still see "geoBlocked" coming up. I know this is out of your hands, but would it be possible to update Retrospect to say that the video could not be played back due to being geoBlocked? At the moment it just says "Cannot start playback".

Yes, I can use your log to see how to extract that message.

**Comment by basrieter** [comment]
If you re-download and install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1834.zip it should now show a better message.

**Comment by 1marc1** [comment]
Since the last posts on this issue, I have learned that Videoland is not only geoblocking, but also blocking known endpoints of at least some VPN providers. I am not sure which ones, but it certainly looks like this is the problem I am running into.
