### ISSUE TITLE
Can we get rid of this "Could not log on for: NPO Start"

### ISSUE THREAD

**Issue by BrodjagaRatnik** [retrospect-addon/plugin.video.retrospect#1835]
### Is your feature request related to a problem? Please describe

Can get rid of the popup msg "Could not log on for: NPO Start"? Have no account, so rather annoying.

**Comment by basrieter** [comment]
The log in is there because it is required to play the live stream abroad. Would it be an option to create a free NPO account and set it up in Retrospect?

**Comment by basrieter** [comment]
Great, enjoy Retrospect.
