### ISSUE TITLE
Can't get TV4 to work

### ISSUE THREAD

**Issue by Anth70** [retrospect-addon/plugin.video.retrospect#1836]
### Describe the bug

When I want to start a video on the channel TV4, I get a message in Swedish "Öppna en Webbläsare och navigera till http://Upptagen:3145" ("Open a Web browser and navigate to http://Busy:3145"). Never seen this before, and I've tried accessing that link with my mobile when I'm on the same network as Kodi with no luck. 

## Expected Behavior

I have previously only entered a "token" then everything has worked.

## Actual Behavior

As I described under "Describe the bug"

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/ibajeyugiv.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:21.0.0
- Retrospect version: 5.7.17

**Comment by Anth70** [comment]
> You need to navigate to: `http://<ip-of-kodi-device>:3145/`

Ahaaa, will test it when I get home. Thank you so much.

**Comment by Anth70** [comment]
Solved it today, but the addon still crash and reboot when backstep and quit...

**Comment by basrieter** [comment]
What do you mean with 'crash and reboot'?

**Comment by Anth70** [comment]
As i tried to explain, when i want ro leave your addon it starts to hung and show the cursor. Then it reboots...
-------- Originalmeddelande --------Från: Bas Rieter ***@***.***> Datum: 2024-09-17  20:42  (GMT+01:00) Till: "retrospect-addon/plugin.video.retrospect" ***@***.***> Kopia: Anth70 ***@***.***>, Author ***@***.***> Ämne: Re: [retrospect-addon/plugin.video.retrospect] Can't get TV4 to work
  (Issue #1836) 
What do you mean with 'crash and reboot'?

**Comment by basrieter** [comment]
Well, my add-on cannot reboot, Kodi can. So I need some clarification.

In any case I need a full Retrospect debug logfile. So enable debug logging in Retrospect and then reproduce your issue. The use the built-in feature in Retrospect to upload the logfile and then post a link to the generated log here.

**Comment by nalle077** [comment]
I have also problems with TV4.
I have added the token according to your guide, and everything happened as it should when following your guide. but when I click on anything it "found no episodes for the selected object." (translated from swedish :))

**Comment by dat97dbo** [comment]
I have the same problem as @nalle077 

https://paste.kodi.tv/pucitogizi

**Comment by basrieter** [comment]
You have a completely different problem but with the same symptoms :)  

You are experiencing an issue related to #1844. But your logfile does not contain debug logging: You enabled it and only uploaded the log. Please reproduce the issue and then provide another log. Preferably in #1844, not here.

**Comment by Anth70** [comment]
> I have also problems with TV4. I have added the token according to your guide, and everything happened as it should when following your guide. but when I click on anything it "found no episodes for the selected object." (translated from swedish :))

Jag hade exakt samma problem, men jag hittade en lösning till slut då guiden inte stämde exakt med min dator. Jag tror att du hämtar fel token som jag gjorde innan jag förstod vad den ville ha. Jag har gjort en liten enkel guide för min egen skull du kan titta på, i nederdelen på bilden så ser du hur token ser ut. Kopiera från "eyJ" och till och med där du kan se texten igen som inte är "blurrad". Mvh Thore
Bildlänk: https://ibb.co/Vm2rQth

**Comment by basrieter** [comment]
> > I have also problems with TV4. I have added the token according to your guide, and everything happened as it should when following your guide. but when I click on anything it "found no episodes for the selected object." (translated from swedish :))
> 
> Jag hade exakt samma problem, men jag hittade en lösning till slut då guiden inte stämde exakt med min dator. Jag tror att du hämtar fel token som jag gjorde innan jag förstod vad den ville ha. Jag har gjort en liten enkel guide för min egen skull du kan titta på, i nederdelen på bilden så ser du hur token ser ut. Kopiera från "eyJ" och till och med där du kan se texten igen som inte är "blurrad". Mvh Thore Bildlänk: https://ibb.co/Vm2rQth

No, he really has a different issue! And for that, I need a logfile! in #1844

**Comment by nalle077** [comment]
> > I have also problems with TV4. I have added the token according to your guide, and everything happened as it should when following your guide. but when I click on anything it "found no episodes for the selected object." (translated from swedish :))
> 
> Jag hade exakt samma problem, men jag hittade en lösning till slut då guiden inte stämde exakt med min dator. Jag tror att du hämtar fel token som jag gjorde innan jag förstod vad den ville ha. Jag har gjort en liten enkel guide för min egen skull du kan titta på, i nederdelen på bilden så ser du hur token ser ut. Kopiera från "eyJ" och till och med där du kan se texten igen som inte är "blurrad". Mvh Thore Bildlänk: https://ibb.co/Vm2rQth

Exactly as Basrieter wrote my problem was something with the plugin.
I installed the updated .zip and everything is as it should :)

**Comment by Anth70** [comment]
> > > I have also problems with TV4. I have added the token according to your guide, and everything happened as it should when following your guide. but when I click on anything it "found no episodes for the selected object." (translated from swedish :))
> > 
> > 
> > Jag hade exakt samma problem, men jag hittade en lösning till slut då guiden inte stämde exakt med min dator. Jag tror att du hämtar fel token som jag gjorde innan jag förstod vad den ville ha. Jag har gjort en liten enkel guide för min egen skull du kan titta på, i nederdelen på bilden så ser du hur token ser ut. Kopiera från "eyJ" och till och med där du kan se texten igen som inte är "blurrad". Mvh Thore Bildlänk: https://ibb.co/Vm2rQth
> 
> No, he really has a different issue! And for that, I need a logfile! in #1844

Ahaa, thanks my friend. Close this thread as solved i think. Take care and THANKS for all work:o)

**Comment by Anth70** [comment]
> > > I have also problems with TV4. I have added the token according to your guide, and everything happened as it should when following your guide. but when I click on anything it "found no episodes for the selected object." (translated from swedish :))
> > 
> > 
> > Jag hade exakt samma problem, men jag hittade en lösning till slut då guiden inte stämde exakt med min dator. Jag tror att du hämtar fel token som jag gjorde innan jag förstod vad den ville ha. Jag har gjort en liten enkel guide för min egen skull du kan titta på, i nederdelen på bilden så ser du hur token ser ut. Kopiera från "eyJ" och till och med där du kan se texten igen som inte är "blurrad". Mvh Thore Bildlänk: https://ibb.co/Vm2rQth
> 
> Exactly as Basrieter wrote my problem was something with the plugin. I installed the updated .zip and everything is as it should :)

Ok, great that it work now:o)
