### ISSUE TITLE
NPO recent werkt niet meer

### ISSUE THREAD

**Issue by ErikBrown2** [retrospect-addon/plugin.video.retrospect#1838]
### Describe the bug

NPO Recent werkt niet meer. Je kunt nog wel een dag kiezen maar als je dat doet dan krijg je de volgende fout melding: "Retrospect - Error Error retrieving the list of items."
Alle andere functies van Retrospect voor NPO werken nog wel.

### To Reproduce

1. Start Retrospect
2. Selecteer NPO Start
3. Selecteer Recent
4. Selecteer een willekeurige dag
5. Zie de fout melding

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/fijofafumo

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 21.0.0
- Retrospect version: 5.7.17

**Comment by basrieter** [comment]
Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1838.zip and see if that fixes the problem.

**Comment by ErikBrown2** [comment]
Dank je wel Bas voor de snelle fix. Het werkt inderdaad weer.

**Comment by basrieter** [comment]
Zal een release proberen te doen morgen.,
