### ISSUE TITLE
SVT Live stream can't play

### ISSUE THREAD

**Issue by crockyler** [retrospect-addon/plugin.video.retrospect#1839]
### Describe the bug

Trying to play a live stream for SVT Play just hangs for a while and then returns to the menu. Been like this since the last update, I think.

## Expected Behavior

Playing the live stream.

## Actual Behavior

The live stream does not play.

### To Reproduce

1. Navigate to a live stream, e.g. a news program (Aktuellt, Rapport)
2. Press play

### Debuglog

The **debug** retrospect.log can be found here:
https://pastebin.com/gr7Ch5ha

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 21.1
- Retrospect version: 5.7.16

**Comment by crockyler** [comment]
Just realized there's a newer release, 5.7.17, will try that.

**Comment by crockyler** [comment]
Tried with 5.7.17 and the same problem.
But it depends on how you navigate to the live stream. If you go via Tv Shows -> G -> Go' Kväll -> 2024 ->... (in this case, I've updated the link to new log) you get the described behaviour.

**Comment by basrieter** [comment]
Could you also attach a debug kodi.log?

**Comment by crockyler** [comment]
Yes, here it is
https://pastebin.com/9r8X9CmP

**Comment by matsarv** [comment]
I saw that the live stream can't play (checked Rapport 19:30) and I did  installed the SVT Play addon to check the live stream in this other addon, and it's working.

Checked the code and saw that another query_hash is used for live stream (and others).

See: [kodi-svtplay](https://github.com/kodi-svtplay/xbmc-svtplay/blob/krypton/resources/lib/api/graphql.py#L89)

Mybee this could be to some help?

**Comment by crockyler** [comment]
> I saw that the live stream can't play (checked Rapport 19:30) and I did installed the SVT Play addon to check the live stream in this other addon, and it's working.
> 
> Checked the code and saw that another query_hash is used for live stream (and others).
> 
> See: [kodi-svtplay](https://github.com/kodi-svtplay/xbmc-svtplay/blob/krypton/resources/lib/api/graphql.py#L89)
> 
> Mybee this could be to some help?

Just checked, and the difference is that in Retrospect you could actually rewind during the live stream, which you can't in SVT Play addon. So if you started to watch in the middle of the stream you could rewind to the beginning, and that's a huge advantage.

**Comment by matsarv** [comment]
> 
> So if you started to watch in the middle of the stream you could rewind to the beginning, and that's a huge advantage.

OK, have never checked that I you could have rewind to the beginning of the stream.

**Comment by matsarv** [comment]
I'm guessing this is fixed in "Issue 1843". See https://github.com/retrospect-addon/plugin.video.retrospect/issues/1843#issuecomment-2414475658

Time to close this one?
