### ISSUE TITLE
NPO EPG not working properly (related to NPO recent werkt niet meer #1838 )

### ISSUE THREAD

**Issue by didamsko** [retrospect-addon/plugin.video.retrospect#1840]
### Describe the bug

Wanted to watch some TV and noticed that the EPG was not loading anymore, all channels (i only use the NPO channels) stayed blank. So i checked online to see if problem was known and if there might be a fix. No issue was reported with the EPG but i spotted the "NPO recent werkt niet meer #1838" topic and tried the "[bug-1838.zip](https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1838.zip)" fix. That fix also partially solved the EPG not getting loaded: the time-slots and thumbnails load but the program-titles are still missing. See screenshot below.

## Expected Behavior

Read above

## Actual Behavior

Read above

### To Reproduce

1. Open Guide in Kodi

### Debuglog

The **debug** retrospect.log can be found here:
[retrospect.log](https://github.com/user-attachments/files/17053089/retrospect.log)
[retrospect.debug.log](https://github.com/user-attachments/files/17053176/retrospect.debug.log)

### Screenshots 

![IMG_20240919_045504](https://github.com/user-attachments/assets/c3ca9439-c03c-45a2-b4ed-3bde00fc5037)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: CoreELEC 21.1.1-Omega
- Retrospect version:  v5.7.17

**Comment by basrieter** [comment]
Can  you redownload https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1838.zip and try again? It might need a refresh of the EPG data.

**Comment by didamsko** [comment]
Thanks it worked now! Yesterday i already tried reinstalling, refreshing the EPG and rebooting a couple times without succes but this time a reinstall and refreshing the EPG did the trick.

**Comment by basrieter** [comment]
Great to hear that. I will release this weekend. Just need to look into #1839.

**Comment by didamsko** [comment]
As a plus the EPG seems to be working better then before now. On my side there always used to be a lot of blanks without a title  in the NPO2 Extra listings, now those programs also all show up :)

**Comment by basrieter** [comment]
That is good to hear!

**Comment by SolosoftNL** [comment]
Question, where is that screenshot coming from? I don't see this in the Kodi menu. What type of program do you use?

**Comment by BrodjagaRatnik** [comment]
> Question, where is that screenshot coming from? I don't see this in the Kodi menu. What type of program do you use?

That is from "IPTV EPG"
