### ISSUE TITLE
NPOstart login failed 

### ISSUE THREAD

**Issue by lagosazules** [retrospect-addon/plugin.video.retrospect#1842]
Selecting NPOstart live TV, any channel gives a error message Retrospect Login Failed: 'Could not log on the selected channel'
 
Selecting 'OK' will opening the channel anyway 

### To Reproduce

1.  Open Retrospect
2.  Select National, NPOstart, Live TV, Any channel 
3.  Select 'OK' to open the channel anyway 

### Debuglog

The **debug** retrospect.log can be found here:

![IMG_20241002_134305_240](https://github.com/user-attachments/assets/500962a3-bdbe-4c50-bcd6-42deaf9b5bd4) 

### Your Environment
Used Operating system:

 - X Firestick 
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 21.0   20240406
- Retrospect version: 5.7.18

**Comment by basrieter** [comment]
I need a debug retrospect.log.

**Comment by lagosazules** [comment]
[kodi.log.zip](https://github.com/user-attachments/files/17229503/kodi.log.zip)
](url)

**Comment by lagosazules** [comment]
Sorry here the debug log
[1kodi-debug.log.zip](https://github.com/user-attachments/files/17229570/1kodi-debug.log.zip)

**Comment by basrieter** [comment]
This is a kodi.log. Please provide a debug `retrospect.log` by changing the logging inside Retrospect to `debug`,  then reproduce the issue, and use the built-in functionality to upload the logfile. Post the **link** (check the link works) here. Not the logfile.

**Comment by lagosazules** [comment]
Ok, thanks 

https://paste.kodi.tv./gufibixoma

**Comment by basrieter** [comment]
Did you configure a NPO account within Retrospect?

**Comment by lagosazules** [comment]
No, I never needed that, it worked fine for years without, 
I did it now and the problem is gone
Thanks and sorry for the trouble

**Comment by basrieter** [comment]
NP. I am still in doubt how to handle this. For users abroad it is required, for users in NL not always. I will leave this issue open as a reminder to think on a solution. But good to hear it is working now.

**Comment by lagosazules** [comment]
I'm outside of NL but to see the Live channels sinds a couple of months I use a dedicated VPN to a private server and IP in the house of family in NL, before I used a normal VPN service but I had never this problem till I noticed it some weeks ago

**Comment by duck7000** [comment]
well i created a npo account, configured it in retrospect and still get the error could not log in?

It used to work to just ignore this error but since yesterday (21-10-2024) none of the npo channnels will play

**Comment by basrieter** [comment]
I need a debug log for that. Double check you are not mixing up the Retrospect pin and NPO password.

**Comment by FRvanderVeen** [comment]
I also do have the issue that NPO says that log-in is required, but nonetheless it is working. I'm located in NL.
Here is my log: https://paste.kodi.tv/eduvugalim

**Comment by basrieter** [comment]
I know, so please create a login in, and configure it in Retrospect to resolve the issue.

**Comment by spacie2136** [comment]
Same issue here.

Maybe a good solution to change the XbmcWrapper.show_dialog function for a Toast style. That way it will not require any user input but the user will still recieve a warning.

        if data_parser.LogOnRequired:
            Logger.info("One or more dataparsers require logging in.")
            self.loggedOn = self.log_on()
            if not self.loggedOn:
                Logger.warning("Could not log on for: %s", self)
                title = LanguageHelper.get_localized_string(LanguageHelper.LoginErrorTitle)
                text = LanguageHelper.get_localized_string(LanguageHelper.LoginErrorText)
                XbmcWrapper.show_dialog(title, text)

**Comment by joopdo** [comment]
@spacie2136 Thanks for that, changing as follows removed the message for me.

`        if data_parser.LogOnRequired:
            Logger.info("One or more dataparsers require logging in.")
            self.loggedOn = self.log_on()
            if not self.loggedOn:
                Logger.warning("Could not log on for: %s", self)
                #title = LanguageHelper.get_localized_string(LanguageHelper.LoginErrorTitle)
                #text = LanguageHelper.get_localized_string(LanguageHelper.LoginErrorText)
                #XbmcWrapper.show_dialog(title, text)

        Logger.debug("Processing Updater from %s", data_parser)
        return data_parser.Updater(item)
`

**Comment by basrieter** [comment]
I could change that.

**Comment by basrieter** [comment]
> @spacie2136 Thanks for that, changing as follows removed the message for me.
> 
> ```
>         if data_parser.LogOnRequired:
>             Logger.info("One or more dataparsers require logging in.")
>             self.loggedOn = self.log_on()
>             if not self.loggedOn:
>                 Logger.warning("Could not log on for: %s", self)
>                 #title = LanguageHelper.get_localized_string(LanguageHelper.LoginErrorTitle)
>                 #text = LanguageHelper.get_localized_string(LanguageHelper.LoginErrorText)
>                 #XbmcWrapper.show_dialog(title, text)
> 
>         Logger.debug("Processing Updater from %s", data_parser)
>         return data_parser.Updater(item)
> ```

Please don't do this, as it will impact all channels and will cause issues. I will change the pop-up into a notification. 

BUT: Just create an NPO login and configure it. NPO requires accounts for some streams and always require accounts when watching from abroad.

**Comment by basrieter** [comment]
Please try this: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/1842-npostart-login-failed.zip

Or just create an NPO account.

**Comment by Johpin1** [comment]
Thanks for the fix: the notification is better than a dialog box. However,
commenting out title, text and XbmcWrapper.show_dialog did not introduce any
issues to me.

According to https://npo.nl/start/aanmelden it seems not required to
register for watching tv livestreams or watching episodes later on.
I don't need the additional features like profiles or personal 
recommendations based on my history of watching.

PS In het bestand channels/channel.nos/nos2010/chn_nos2010.json is
https://www.npostart.nl/npo-id-gebruiksvoorwaarden te vinden, maar deze
internetpagina blijkt niet meer te bestaan.

**Comment by basrieter** [comment]
Please check: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/1842-npostart-login-failed.zip 

I now only use a login if you configured one.

**Comment by Johpin1** [comment]
It works like a charm!

**Comment by basrieter** [comment]
Will push an official release soon.

**Comment by duck7000** [comment]
> I now only use a login if you configured one.

This is the best approach i guess.
If you add account credentials this issue is traded in for a pin request (for every channel) which i don't use or want to use.

Thanks!

**Comment by basrieter** [comment]
> > I now only use a login if you configured one.
> 
> This is the best approach i guess. If you add account credentials this issue is traded in for a pin request (for every channel) which i don't use or want to use.
> 
> Thanks!

Great! The PIN you only need once every couple of months. It is just to keep your log-in secure.

**Comment by duck7000** [comment]
I meant the retrospect pin vault

**Comment by basrieter** [comment]
> I meant the retrospect pin vault

I know: but you only need it to get a session token for NPO, and then not for a long time.

**Comment by duck7000** [comment]
mm that is not my experience, pin is asked after every boot of libreelec for every channel and channel change
That is why i didn't like your solution to create a account in the first place to get rid of the not logged in warning.

So your solution to only use a configured login is for me the best approach, no account, no pin vault and no warning, great!

**Comment by basrieter** [comment]
> mm that is not my experience, pin is asked after every boot of libreelec for every channel and channel change That is why i didn't like your solution to create a account in the first place to get rid of the not logged in warning.
> 
> So your solution to only use a configured login is for me the best approach, no account, no pin vault and no warning, great!

That should not be, unless you manually delete stuff in the profile folder. But hey, if you are happy now.
