### ISSUE TITLE
SE: SVT Play don't display Categories folder content

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1843]
### Describe the bug

SVT Play don't display Categories folder content.

```
Plugin::Error Processing FolderList
.............
.............
IndexError: list index out of range
```

## Expected Behavior

Open Category folders

## Actual Behavior

Error when press a Coategory folder e.g. Serier

### To Reproduce

1.  Select SVT Play
2.  Select Categories
3.  Select a Category e.g. Serier

### Debuglog

The **debug** retrospect.log can be found here: https://paste.kodi.tv/eyoxuzinig.kodi

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 21.1
- Retrospect version: 5.7.18

**Comment by basrieter** [comment]
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1843.zip and let me know.

**Comment by matsarv** [comment]
Now the categories is working again.
Very good!

--------
Currently playing (Live TV) no longer works for me.

Retrospect log: https://paste.kodi.tv/ofeqizuzab.kodi
Kodi log: https://paste.kodi.tv/nazuluracu.kodi

**Comment by matsarv** [comment]
Updated: Live TV is working OK.

**Comment by matsarv** [comment]
I have checked Retrostect.log in #1839 and found the following:

`
MediaItem: Pumpasoppa och arkitektur [COLOR gold](live)[/COLOR]
`

[COLOR gold](live)[/COLOR] is added to the TV program title when the program is broadcast and this is used in the Currently playing folder.

So I'm guessing that the problem in #1839 concerns the Currently playing folder.

See also my Retrospect log and Kodi log above for the issue in Currently playing (Livesändingar).

**Comment by crockyler** [comment]
Tried the bug fix and live plays now, but rewinding to the start makes it hang.
[Retrospect log](https://pastebin.com/TkMuHACx).

**Comment by basrieter** [comment]
> art makes it hang.

That is something related to Kodi then. If it starts playing, Retrospect is done.

**Comment by basrieter** [comment]
> > That is something related to Kodi then. If it starts playing, Retrospect is done.
> 
> It works for TV4 though.

That could very well be, but you should not compare SVT and TV4. Their stream providers are different.

**Comment by crockyler** [comment]
Ok, then I get it.
But, yesterday I had problems playing live again. It just hang for a while and then "returned" to the menu.
[Retrospect.log](https://pastebin.com/ER0SUiWJ).

**Comment by matsarv** [comment]
I will try to explane the problem with playing (live) items:

1. In / Currently playing / 


![live_1](https://github.com/user-attachments/assets/97406f55-7716-44d9-af51-4e9314430ff9)


2. In / Categories / Nyheter / Rapport - Senaste Nytt - dagens mest aktuella nyheter / Huvudsändnngar - 19:30 - 25 min /

![live_2](https://github.com/user-attachments/assets/55ec34b3-3f50-4e05-907d-d945888cf303)


When select a (live) item it just freeze and show the following at top of the screen.

![live_3](https://github.com/user-attachments/assets/5fc49321-b427-46cf-b4df-1c7dfab71e7e)


After about 30 seconds it returns to the item list again.
See the [above](https://github.com/retrospect-addon/plugin.video.retrospect/issues/1843#issuecomment-2405528547) Retrospect.log

Every show item with the (live) in the title is not working.

**Comment by basrieter** [comment]
So I need a debug retrospect.log (the one you added is just one with `info` level. And a debug kodi.log.

**Comment by matsarv** [comment]
Here are the logs for:

![live_4](https://github.com/user-attachments/assets/45182021-b5cb-44f6-946f-8cf19136d55b)

Retrospect log: https://paste.kodi.tv/ugapolanul.kodi
KODI log: https://paste.kodi.tv/ihacesuyeg.kodi

**Comment by basrieter** [comment]
I will have a look, but it is usually difficult with live content from outside Sweden.

**Comment by matsarv** [comment]
I installed the SVT Play addon to check the live stream, and it works.
If you look in the [code](https://github.com/kodi-svtplay/xbmc-svtplay/blob/krypton/resources/lib/api/graphql.py#L89), a different query_hash is used for live stream ("live_start").

Maybe of some help?

**Comment by basrieter** [comment]
Ok, please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1843.zip and see if that works?

**Comment by matsarv** [comment]
I have now tested "live_start" with new hash. Unfortunately, it didn't work. Same result as before. Strange that it works in the SVT Play addon, I don't understand anything!

Just to test, I switched to this new hash for "latest_start", "lastchance_start" and "popular_start" and they played the stream perfectly with this new hash.

Don't let it be a show stopper, "live_start" has stopped working in the past.


Great work, now everything is back and working as before in Retrospect, SVT Play's Categories and TV4 Play's TV shows and Categories.

**Comment by basrieter** [comment]
Could you check whether the SVT add-on uses MPD or M3U8 streams?

**Comment by matsarv** [comment]
It seems to be m3u8, see the log file.
KODI log: https://paste.kodi.tv/orugemaqes.kodi

**Comment by basrieter** [comment]
So I changed it to favor HLS over Dash, please try: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1843.zip.

When testing please also verify that #1433 does not return. That issue cause SVT and ViaFree to not stop streams at the end. So please verify all stream (live, catchup and non-live).

**Comment by matsarv** [comment]
Tested alot of streams during the day and all seems to work without any problem.
Great work. SVT Play is now ready for release.

**Comment by matsarv** [comment]
> Tested alot of streams during the day and all seems to work without any problem. Great work. SVT Play is now ready for release.

Not ready to release!
Sorry, just installed and tested it on a Android tablet. Only Live TV and Currently playing are working.
Need to do more testing.

**Comment by crockyler** [comment]
> So I changed it to favor HLS over Dash, please try: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1843.zip.

Works for me now. Even jumping back and forward works.
Great work!

**Comment by matsarv** [comment]
I have now tested different platforms with the latest change from this fix.

- Windows 10 and Windows 11 KODI 21.1: Everything is playing  OK.

- RPi3 LibreELEC 12.0.1: Everything is playing  OK.

- Android Samsung / Lenovo KODI 21.1: "Currently playing", "Live TV" and some others old videos is playing but the most videos just freezes and never starts.

I made the following change i KODI for Android:

- In "System settings / Player / Videos" under "Processing" i disabled the two "Allow hardware acceleration ...." and after that change everything is now playing OK.

**Comment by basrieter** [comment]
> I have now tested different platforms with the latest change from this fix.
> 
> * Windows 10 and Windows 11 KODI 21.1: Everything is playing  OK.
> * RPi3 LibreELEC 12.0.1: Everything is playing  OK.
> * Android Samsung / Lenovo KODI 21.1: "Currently playing", "Live TV" and some others old videos is playing but the most videos just freezes and never starts.
> 
> I made the following change i KODI for Android:
> 
> * In "System settings / Player / Videos" under "Processing" i disabled the two "Allow hardware acceleration ...." and after that change everything is now playing OK.

Ok, so the HLS streams are not perfect, but do the job?

**Comment by matsarv** [comment]
Yes, what I've checked, everything in SVT Play is working OK now.
Great work!

**Comment by basrieter** [comment]
Fixed in https://github.com/retrospect-addon/plugin.video.retrospect/releases/tag/v5.7.19: Kodi will update the add-on as soon as mirrors have synced.
