### ISSUE TITLE
kijk. nl recent gives error 

### ISSUE THREAD

**Issue by SolosoftNL** [retrospect-addon/plugin.video.retrospect#1845]
### Describe the bug

Error when playing kijk.nl programma

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:
- Retrospect version:

**Comment by basrieter** [comment]
Please don't delete and ignore the issue template. Fill out the request information and provide a debug retrospect.log.

**Comment by Heleen-Heleen** [comment]
KIJK doet het bij mij wel

**Comment by Heleen-Heleen** [comment]
KIJK doet het bij mij wel. Heb wat afleveringen kunnen zien

**Comment by SolosoftNL** [comment]
Sorry. After installing the latest, it works flawlessly, My bad 😞

**Comment by basrieter** [comment]
NP. Enjoy Kodi & Retrospect.

**Comment by basrieter** [comment]
Fixed in https://github.com/retrospect-addon/plugin.video.retrospect/releases/tag/v5.7.19: Kodi will update the add-on as soon as mirrors have synced.
