### ISSUE TITLE
SE: UR Play is not listing Categories or TV shows

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1847]
### Describe the bug

Not listing Categories or TV shows

## Expected Behavior

List Categories and TV shows

## Actual Behavior

Error list Categories and TV shows

### To Reproduce

1.  Select UR Play
2. Select Categories or TV shows
3.

### Debuglog

Categories 
Error: No episodes found
The **debug** retrospect.log can be found here: https://paste.kodi.tv/ifarolirom.kodi

TV shows
Error retreiving the list of item
The **debug** retrospect.log can be found here: https://paste.kodi.tv/wijiqimika.kodi

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 21.1
- Retrospect version: 5.7.18 + fixes

**Comment by basrieter** [comment]
Please try: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/1847-se-ur-play-is-not-listing-categories-or-tv-shows.zip

**Comment by matsarv** [comment]
It's working OK again. 
Thanks.

**Comment by basrieter** [comment]
Fixed in https://github.com/retrospect-addon/plugin.video.retrospect/releases/tag/v5.7.19: Kodi will update the add-on as soon as mirrors have synced.
