### ISSUE TITLE
Some regional stations are not working, e.g. RTV Drenthe

### ISSUE THREAD

**Issue by PA0RWE** [retrospect-addon/plugin.video.retrospect#1850]
### Describe the bug

When I select Drenthe Nu in the Regional-RTV Drenthe section I have got the Retrospect error Error when retreiving Items

## Expected Behavior

There should be a list of streams

## Actual Behavior

There coms a Restrospect error

## Possible Fix

It seems that it is not possible to show a list of available streams

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
https://www.dropbox.com/scl/fi/kf6hwzer3z12ddvxds1sy/retrospect.log?rlkey=dv2kvydbv5xmbzzo9u6605ctd&dl=0

### Screenshots 

https://www.dropbox.com/scl/fi/y4s7fuidtn8jyfaov9gul/Schermafdruk-van-2024-10-19-12-35-03.png?rlkey=9fs8v9hh3kc8747exialb9vj4&dl=0

### Your Environment
Used Operating system:

 - [x ] Android TV
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.4.0
- Retrospect version: 5.7.17

**Comment by PA0RWE** [comment]
Since a couple of weeks some regional stations are given an error when started: 
_**Retrospect Error
Error retrieving the item.**_
This error does not occur with every station and not always with LiveTV

**Comment by basrieter** [comment]
I need a full debug retrospect.log.

**Comment by PA0RWE** [comment]
I have updated the Bug report

**Comment by basrieter** [comment]
Thanks, but those are not debug logs: Enable debug logging in Retrospect and reproduce the issue. You can use the built-in functionality to upload the logs to paste.kodi.tv and then just paste the resulting link here.

**Comment by PA0RWE** [comment]
I hope you mean this...
https://paste.kodi.tv/uhevatafej

**Comment by basrieter** [comment]
You are 2 version of Retrospect behind. Please make sure you run version 5.7.19.

**Comment by PA0RWE** [comment]
Hi Bas,

 

That solved the problem.
KODI said that 5.7.17 was the latest version…  But I installed the zip file of 5.7.19 and that solves the problem.

 

Thanks
Rob

 

 

Van: Bas Rieter ***@***.***> 
Verzonden: zaterdag 19 oktober 2024 20:24
Aan: retrospect-addon/plugin.video.retrospect ***@***.***>
CC: Rob ***@***.***>; State change ***@***.***>
Onderwerp: Re: [retrospect-addon/plugin.video.retrospect] Some regional stations are not working, e.g. RTV Drenthe (Issue #1850)

 

You are 2 version of Retrospect behind. Please make sure you run version 5.7.19.

**Comment by basrieter** [comment]
Weird, it is in the Kodi repo. But good to hear it is working again.

**Comment by PA0RWE** [comment]
Hi Bas,

 

On my Linux laptop the Kodi version was 19.4.0 and the highest version of Retrospect in the repo was 5.17.17 so I missed the latest Retrospect version 😉

Next time I encounter a problem, I'll check GitHub for the latest Retrospect version first….

 

Regards,

Rob

 

Van: Bas Rieter ***@***.***> 
Verzonden: zaterdag 19 oktober 2024 22:39
Aan: retrospect-addon/plugin.video.retrospect ***@***.***>
CC: Rob ***@***.***>; State change ***@***.***>
Onderwerp: Re: [retrospect-addon/plugin.video.retrospect] Some regional stations are not working, e.g. RTV Drenthe (Issue #1850)

 

Weird, it is in the Kodi repo. But good to hear it is working again.

**Comment by basrieter** [comment]
It should update under Kodi Matrix. Anyways: do update Kodi as I will drop Matrix support soon.

**Comment by PA0RWE** [comment]
OK Bas, I will do!  Thanks for help.

 

 

Van: Bas Rieter ***@***.***> 
Verzonden: zondag 20 oktober 2024 10:36
Aan: retrospect-addon/plugin.video.retrospect ***@***.***>
CC: Rob ***@***.***>; State change ***@***.***>
Onderwerp: Re: [retrospect-addon/plugin.video.retrospect] Some regional stations are not working, e.g. RTV Drenthe (Issue #1850)

 

It should update under Kodi Matrix. Anyways: do update Kodi as I will drop Matrix support soon.
