### ISSUE TITLE
Videoland werkt niet meer- List of lives

### ISSUE THREAD

**Issue by kengithub9** [retrospect-addon/plugin.video.retrospect#1852]
Videoland gedeelte doet het niet meer.
Krijg alleen te zien : List of lives. 
Via Windows 11 in de browser kan ik wel naar videoland en daar doet alles het wel.

Used Operating system:
Beelink GT King Kodi 21.1

Used versions:
- Kodi version: 21.1
- Retrospect version: 5.7.19

**Comment by basrieter** [comment]
Waarom wis je nu de hele issue template? Die staat er echt niet voor niks! Graag invullen op zijn minst voor zien van een geuploade DEBUG retrospect.log.

**Comment by kengithub9** [comment]
Klein foutje en heb inderdaad de template gewist.
Hierbij de debug log: https://paste.kodi.tv/yubufebeza

**Comment by basrieter** [comment]
Thanks voor de log. Je hebt alleen niet na het aanpassen van het loglevel nog een keer Videoland proberen te openen. Zou je dat nog kunnen doen en daarna nog een logfile kunnen posten?

**Comment by kengithub9** [comment]
Hopelijk heb ik het nu wel goed gedaan. hierbij een nieuw log
https://paste.kodi.tv/yipacehowa.

**Comment by basrieter** [comment]
Beter. Ik kan het alleen niet reproduceren. Zou je de Retrospect cache kunnen legen: 

![image](https://github.com/user-attachments/assets/b9f9ea62-423a-41e7-9e06-f81c58250838)

**Comment by kengithub9** [comment]
Ga ik doen, zal morgen even laten weten of dat geholpen heeft.

**Comment by kengithub9** [comment]
Na de clean-up van de cache en cookies, werkt het helaas nog steeds niet.
Heb ook de inloggegevens even verwijderd opnieuw ingesteld maar ook dat veranderd niks.

**Comment by basrieter** [comment]
Krijg je "List of Lives" ook al ipv de eerst lijst die je normaal onder Videoland kreeg te zien?

**Comment by kengithub9** [comment]
Die melding krijg je meteen als je Videoland opent.
Ook kun je zoeken, hij geeft wel zoekresultaten maar klik je daarop krijg je dezelfde melding.

**Comment by basrieter** [comment]
Ik heb nog een keer gekeken, maar kan er echt niks van maken zo. Kan je eens stapsgewijs aangeven wat je moet doen voordat dat het fout gaat: Dus elke actie in Kodi (inclusief starten van Retrospect) graag even puntsgewijs beschrijven.

**Comment by kengithub9** [comment]
Na het starten van Kodi 21.1 ga ik naar addons, Retrospect , dan national en vervolgens klik ik videoland aan.
Daarna krijg ik de melding zoals ik eerder heb gemeld.

**Comment by basrieter** [comment]
Bij mij werkt dat echt gewoon. Zou je het eens op een ander device kunnen proberen? Of anders je user_data kunnen backup-en en het zo met een kale install kunnen proberen.

**Comment by kengithub9** [comment]
Ga ik proberen dit weekend

**Comment by basrieter** [comment]
Kan je ook de HTTPS caching binnen Retrospect uitzetten? Kijken of dat uitmaakt?

**Comment by kengithub9** [comment]
Het uitzetten van HTTPS caching heeft het probleem niet verholpen. De andere actie ga ik later vandaag proberen.

**Comment by kengithub9** [comment]
Na verwijdering van Retrospect en herinstalleren werkt het weer.
Is er overigens ook een probleem live kijken van NPO via IP manager/ IP Simple want dat doet het na de herstel niet meer. Is niet erg via het menu in  retrospect werkt het wel.

**Comment by basrieter** [comment]
Welke fout krijg je daarbij? Bij IP Manager?

**Comment by kengithub9** [comment]
hierbij het log voor meer info van de foutmelding:
https://paste.kodi.tv/godikemahu

**Comment by kengithub9** [comment]
Het probleem is sinds vandaag ineens verdwenen. Geen problemen meer.

**Comment by basrieter** [comment]
Dat is fijn! Hopelijk blijft het zo, anders hoor ik het graag.

**Comment by basrieter** [comment]
Ok, ik had nu exact hetzelfde en dit had ik nooit vanuit een log kunnen fixen! Maar ik ben er nu uit: Het komt omdat je device vanuit de Videoland.nl website is revoked. Daarna kan Retrospect niet meer inloggen. Ik ga het fixen.

**Comment by basrieter** [comment]
![image](https://github.com/user-attachments/assets/0b86ad6f-3ade-4d12-8c45-0cc89fb32cc2)

De "Re-Authenticate" lost het probleem nu op.

**Comment by basrieter** [comment]
https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/master.zip Voor als je ongeduldig bent en het al wilt proberen.
