### ISSUE TITLE
Certain shows won't play (TV4)

### ISSUE THREAD

**Issue by huey-smart** [retrospect-addon/plugin.video.retrospect#1853]
### Describe the bug

Can play many shows without issues but get error message on some.

### To Reproduce

1. Go to the show Robinson, regular episodes will play but "Gränslandet" fails.
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
Https://paste.kodi.tv/gufadikata

### Your Environment
Used Operating system:

 - [ x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:
- Retrospect version:

**Comment by basrieter** [comment]
I can't play this stream outside Sweden. . Could you play the video in a browser and see if you can find the response of this URL in the browser's developer tools: 

https://playback2.a2d.tv/play/11fdbeb7b5dcc5debdac?service=tv4play&device=browser&browser=GoogleChrome&protocol=dash&drm=widevine&capabilities=live-drm-adstitch-2%2Cexpired_assets

**Comment by huey-smart** [comment]
Absolutely, where in the dev tools should I look?

When I go to that URL I get this in the browser:
{"errorCode":"LOGIN_REQUIRED","message":"The asset is not accessible for non-authenticated users"}

In dev tools/Network/Console I get:
403 (Forbidden)

**Comment by huey-smart** [comment]
There used to be login details in the channel settings for TV4 Play, didn't it?

**Comment by basrieter** [comment]
> There used to be login details in the channel settings for TV4 Play, didn't it?

Ah, right. You need to set a refresh token. This is a bit different than username and password and requires you to copy paste the refresh token to Retrospect: https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Storing-Passwords-in-the-Retrospect-Vault#refresh-tokens

**Comment by huey-smart** [comment]
Yes, I've done that and if I don't no shows won't even be listed. So to clarify, in the same folder some videos can be played and stone can't.

**Comment by basrieter** [comment]
> I can't play this stream outside Sweden. . Could you play the video in a browser and see if you can find the response of this URL in the browser's developer tools:
> 
> https://playback2.a2d.tv/play/11fdbeb7b5dcc5debdac?service=tv4play&device=browser&browser=GoogleChrome&protocol=dash&drm=widevine&capabilities=live-drm-adstitch-2%2Cexpired_assets

So, I guess you just opened this URL in the browser? That was not what I meant: Just play the video in the browser and go look for a URL similar to that one and find its content.

**Comment by huey-smart** [comment]
Ok, I've tried looking around dev tools to find an url of this type without success. Could you give me some more clues where I should look?

**Comment by mangebest** [comment]
Hello
I have the same problem. In the same folder as "Robinson" is "Gränslandet". Robinson plays but not Gränslandet. Both have the little blue ring after the  episode name and not the little yellow "a".
Robinson plays bot not Gränslandet. Gränslandet plays on Tv4play on my chrome browser. Log: uguvejitah

**Comment by Espancor** [comment]
Hi, I have the same problem too as the others.

**Comment by ainatar1977** [comment]
Same here with Robinson and Gränslandet.

**Comment by huey-smart** [comment]
@basrieter, anything we can help you with to get progress in this issue?

**Comment by basrieter** [comment]
I need a 26 hour day, or an 8 hour week :) But I am looking into it now.

**Comment by basrieter** [comment]
Please try this version: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/1853-certain-shows-wont-play-tv4.zip

**Comment by EdvinNilsson** [comment]
Your fix didn't work, but I found a solution.

You just need to change the key from `token` to `castlabsAssetId`.
```diff
- license_key_token = license_info["token"]
+ license_key_token = license_info["castlabsAssetId"]
```

**Comment by mangebest** [comment]
The fix worked for me. all Gränslandet plays. Also Bachelor sweden plays good (did not work before)I downloaded Widevine CDM according to the update.
all good here.

**Comment by basrieter** [comment]
> Your fix didn't work, but I found a solution.
> 
> You just need to change the key from `token` to `castlabsAssetId`.
> 
> ```diff
> - license_key_token = license_info["token"]
> + license_key_token = license_info["castlabsAssetId"]
> ```

I don't think this is correct! Please use my updated ZIP file. That solves the issue.

**Comment by EdvinNilsson** [comment]
> > Your fix didn't work, but I found a solution.
> > You just need to change the key from `token` to `castlabsAssetId`.
> > ```diff
> > - license_key_token = license_info["token"]
> > + license_key_token = license_info["castlabsAssetId"]
> > ```
> 
> I don't think this is correct, because that line does no longer exist in my ZIP-ed version! Please use my updated ZIP file. That solves the issue.

I retested your zip and it is working now! Sorry for the confusion.
