### ISSUE TITLE
NPO is kapot

### ISSUE THREAD

**Issue by PhyxionNL** [retrospect-addon/plugin.video.retrospect#1854]
### Describe the bug
Hij kan geen enkele aflevering meer opstarten, het geeft meteen een foutmelding.

Het lijkt hierop verkeerd te gaan:
```
20241021 15:32:13 - [INFO    ] - urihandler.py        - 543  - Performing a json POST with '<No Content-Type>' for https://prod.npoplayer.nl/stream-link
20241021 15:32:13 - [ERROR   ] - urihandler.py        - 555  - POST failed with '401 Unauthorized' (0:00:00.059968) for https://prod.npoplayer.nl/stream-link
```

Via de app en npostart.nl werken de afleveringen nog wel.

### To Reproduce

1. Probeer willekeurige aflevering van NPO te openen.

### Debuglog

The **debug** retrospect.log can be found here:
[retrospect.debug.log](https://github.com/user-attachments/files/17461687/retrospect.debug.log)

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 21.1
- Retrospect version: laatste

**Comment by BrodjagaRatnik** [comment]
Have the same since today, can log in with NPO account on laptop with same login details.

**Comment by basrieter** [comment]
> Have the same since today, can log in with NPO account on laptop with same login details.

I will have a look at that.

**Comment by PhyxionNL** [comment]
https://github.com/retrospect-addon/plugin.video.retrospect/blob/master/resources/lib/streams/npostream.py#L71
Is nu:
```
        token_value = token_json.get_value("jwt")
```

Daarmee werkt het weer.

**Comment by basrieter** [comment]
Yes, the fix is very simple. Will update asap.

**Comment by basrieter** [comment]
I pushed an update to the Kodi repo!
