### ISSUE TITLE
NPO livestream not working

### ISSUE THREAD

**Issue by ceisma** [retrospect-addon/plugin.video.retrospect#1857]
### Describe the bug

All NPO livestreams simply won't play, regardless of whether I'm logged in with or without an NPO Start account.

### To Reproduce
1. Live TV -> NPO (all channels)
2.
3.

### Debuglog
The **debug** retrospect.log can be found here: 
https://pastebin.com/JF0SCPuB

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:
- Retrospect version: 5.7.19

**Comment by ceisma** [comment]
> Installeer versie 5.7.20 dan werkt het wel

Dank! Is die al gepushed naar Kodi dan? Of moet ik 5.7.20 eerst handmatig installeren?

**Comment by basrieter** [comment]
Is al gepushed gisteren. Maar check het even

**Comment by basrieter** [comment]
Voor zover ik kan zien, werkt NPO gewoon.

**Comment by ceisma** [comment]
Het werkt inderdaad met 5.7.20. Ik heb 'm zojuist handmatig binnengehaald. Kodi bleef zelf hangen op 5.7.19, maar dat komt misschien door OSMC. In ieder geval bedankt, deze kan dicht. :)
