### ISSUE TITLE
empty folders in NPO-plus items

### ISSUE THREAD

**Issue by keiem** [retrospect-addon/plugin.video.retrospect#1862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When browsing to the NPO-plus items, there is nothing to watch in the folder.  I have an account an my credentials, user and password, are in the retrospect settings.  Similar to issue #1858 although I didn't test it on android and
I'm watching from Belgium.
Bug started after the API fix with commit f935930 "Merge branch '1854-npo-is-kapot'"
Maybe worth to mention.  I'm watching from a pine-h64 running libreelec 13 nightly.  Why the nightly because there are streaming issues with LE12 on the allwinner H6 soc.  The streaming issue is fixed in LE13 (still in testing fase).

### Steps to Reproduce

1. Fill in your NPO plus credentials in the retrospect settings
2. Open retrospect addon
3. In my case, search for ben fogle and check the seasons "where the wild men are"
4. Folders should have several episode, but only one is listed (I think a teaser episode)

### Expected Behavior

See all the episodes from the season.

### Debuglog

https://paste.kodi.tv/jetibifabe
kodi log attached:
[01_KODI.log](https://github.com/user-attachments/files/17524412/01_KODI.log)

### Your Environment

- [ ] Android
- [ ] iOS
- [X] Linux
- [ ] OSX
- [ ] Raspberry-Pi
- [ ] Windows
- [ ] Windows UWP

### Kodi version

kodi 22.0-alpha1

### Retrospect version

5.7.20

**Comment by basrieter** [comment]
Ok, so in a browser, please open the DEV tools and browse [npostart](https://npo.nl/start). In the devtools check for the url: `https://npo.nl/start/api/auth/session`

Check the response for that url, strip all the personal data and post the result here. It should look like:

```json
{
    "user": {
        "name": "------",
        "email": "",
        "image": ""
    },
    "expires": "2024-11-24T19:17:14.916Z",
    "accountGuid": "------",
    "hasSubscription": false,
    "npoEmployee": false,
    "npoId": "------",
    "profile": {
        "color": "bg-catalina-blue",
        "guid": "------",
        "name": "------"
    },
    "tokenExpiresAt": 1729887435
}
```

**Comment by keiem** [comment]
This is what I received:

{
"user":{
"name":"",
"email":"",
"image":""
},
"expires":"2024-11-24T20:56:22.192Z",
"accountGuid":"",
"hasSubscription":true,
"isEmployee":false,
"npoEmployee":false,
"npoId":"",
"tokenExpiresAt":1729893306
}

**Comment by basrieter** [comment]
Found it.

**Comment by basrieter** [comment]
Can you please try: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/1862-empty-folders-in-npo-plus-items.zip
