### ISSUE TITLE
BVN images not laoding

### ISSUE THREAD

**Issue by tcplomp** [retrospect-addon/plugin.video.retrospect#1864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Browsing the BVN channel, the thumbnails for individual items don't load.
From the kodi.log
`error <general>: CCurlFile::Open - <https://www.bvn.tvhttps://images.poms.omroep.nl/image/s300/c288x192/1003605> Failed with code 404:
`
At first I thought it was a trailing / issue in chn_bvntv.py, but then the error became:
`error <general>: CCurlFile::Open - <https://www.bvn.tv/https://images.poms.omroep.nl/image/s300/c288x192/1003605> Failed with code 404:
`
The actual image is at https://images.poms.omroep.nl/image/s300/c288x192/1003605

### Steps to Reproduce

Open Kodi - Addons - Video Addons - Retrospect - National - BVN

No images shown.

### Expected Behavior

Thumbnail image shown

### Possible Fix

I tried adding a trailing '/' to the baseURL token in chn_bvntv.py
Had look at the episode regex on the mainlistURI, but that does parse them properly as thumburl.

### Debuglog

20241118 20:11:32 - [INFO    ] - addon.py             - 32   - XOT Logger :: Appending Existing logFile
20241118 20:11:32 - [INFO    ] - urihandler.py        - 61   - Re-using existing UriHandler: UriHandler [id=1731913204, useCaching=Cache store [/home/XBMC-tv/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.video.retrospect/cache/www], ignoreSslErrors=False]
20241118 20:11:32 - [INFO    ] - plugin.py            - 34   - *********** Starting Retrospect add-on version 5.7.20 ***********
20241118 20:11:32 - [INFO    ] - chn_class.py         - 41   - Initializing channel (__init__): BVN (bvntv) [channel.nos.bvntv.bvntv=True, nl=True, National, D6527D8C-F08C-4E43-AE9A-E25F90EC03EA] (Order: #_nl.0101)
20241118 20:11:32 - [INFO    ] - plugin.py            - 103  - Loaded: BVN
20241118 20:11:32 - [INFO    ] - folderaction.py      - 44   - Plugin::process_folder_list Doing process_folder_list
20241118 20:11:32 - [INFO    ] - chn_class.py         - 187  - process_folder_list :: No item was specified. Assuming it was the main channel list
20241118 20:11:32 - [INFO    ] - urihandler.py        - 547  - Performing a GET for https://www.bvn.tv/programmas/
20241118 20:11:33 - [INFO    ] - urihandler.py        - 552  - GET resulted in '200 OK' (0:00:00.574045) for https://www.bvn.tv/programmas/
20241118 20:11:33 - [INFO    ] - chn_bvntv.py         - 82   - Performing Pre-Processing
20241118 20:11:33 - [INFO    ] - addon.py             - 65   - Retrospect :: Flushing and closing logfile.
20241118 20:11:36 - [INFO    ] - addon.py             - 32   - XOT Logger :: Appending Existing logFile
20241118 20:11:36 - [INFO    ] - urihandler.py        - 61   - Re-using existing UriHandler: UriHandler [id=1731913204, useCaching=Cache store [/home/XBMC-tv/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.video.retrospect/cache/www], ignoreSslErrors=False]
20241118 20:11:36 - [INFO    ] - plugin.py            - 34   - *********** Starting Retrospect add-on version 5.7.20 ***********
20241118 20:11:36 - [INFO    ] - chn_class.py         - 41   - Initializing channel (__init__): BVN (bvntv) [channel.nos.bvntv.bvntv=True, nl=True, National, D6527D8C-F08C-4E43-AE9A-E25F90EC03EA] (Order: #_nl.0101)
20241118 20:11:36 - [INFO    ] - plugin.py            - 103  - Loaded: BVN
20241118 20:11:36 - [INFO    ] - folderaction.py      - 44   - Plugin::process_folder_list Doing process_folder_list
20241118 20:11:36 - [INFO    ] - urihandler.py        - 547  - Performing a GET for https://www.bvn.tv/programma/blauw-bloed/
20241118 20:11:37 - [INFO    ] - urihandler.py        - 552  - GET resulted in '200 OK' (0:00:01.259359) for https://www.bvn.tv/programma/blauw-bloed/
20241118 20:11:37 - [INFO    ] - chn_bvntv.py         - 63   - Performing Pre-Processing
20241118 20:11:37 - [INFO    ] - addon.py             - 65   - Retrospect :: Flushing and closing logfile.
20241118 20:11:38 - [INFO    ] - addon.py             - 32   - XOT Logger :: Appending Existing logFile
20241118 20:11:38 - [INFO    ] - urihandler.py        - 61   - Re-using existing UriHandler: UriHandler [id=1731913204, useCaching=Cache store [/home/XBMC-tv/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.video.retrospect/cache/www], ignoreSslErrors=False]
20241118 20:11:38 - [INFO    ] - plugin.py            - 34   - *********** Starting Retrospect add-on version 5.7.20 ***********
20241118 20:11:38 - [INFO    ] - chn_class.py         - 41   - Initializing channel (__init__): BVN (bvntv) [channel.nos.bvntv.bvntv=True, nl=True, National, D6527D8C-F08C-4E43-AE9A-E25F90EC03EA] (Order: #_nl.0101)
20241118 20:11:38 - [INFO    ] - plugin.py            - 103  - Loaded: BVN
20241118 20:11:38 - [INFO    ] - npostream.py         - 59   - Determining MPD streams for VideoId: VPWON_1356033
20241118 20:11:38 - [INFO    ] - urihandler.py        - 543  - Performing a json POST with '<No Content-Type>' for https://npo.nl/start/api/domain/player-token
20241118 20:11:40 - [ERROR   ] - urihandler.py        - 555  - POST failed with '400 Bad Request' (0:00:01.132268) for https://npo.nl/start/api/domain/player-token
20241118 20:11:40 - [INFO    ] - urihandler.py        - 543  - Performing a json POST with '<No Content-Type>' for https://prod.npoplayer.nl/stream-link
20241118 20:11:41 - [ERROR   ] - urihandler.py        - 555  - POST failed with '401 Unauthorized' (0:00:01.114389) for https://prod.npoplayer.nl/stream-link
20241118 20:11:41 - [INFO    ] - npostream.py         - 96   - Using non-encrypted Dash for NPO
20241118 20:11:41 - [INFO    ] - mediaitem.py         - 565  - Creating a Kodi ListItem for Bitrate: 500 kbps
20241118 20:11:41 - [INFO    ] - mediaitem.py         - 565  - | MediaItem: Blauw Bloed [Type=episode, Complete=True, IsLive=False, Date=, Geo/DRM=False/False]
20241118 20:11:41 - [INFO    ] - mediaitem.py         - 565  - | MediaStream: None [bitrate=0]
20241118 20:11:41 - [INFO    ] - mediaitem.py         - 565  - |     + Property: inputstream=inputstream.adaptive
20241118 20:11:41 - [INFO    ] - mediaitem.py         - 565  - |     + Property: inputstream.adaptive.manifest_type=mpd
20241118 20:11:41 - [INFO    ] - mediaitem.py         - 565  - |     + Property: inputstream.adaptive.license_type=com.widevine.alpha
20241118 20:11:41 - [INFO    ] - mediaitem.py         - 565  - + MediaType: episode
20241118 20:11:41 - [INFO    ] - mediaitem.py         - 612  - Playing Stream: MediaStream: None [bitrate=0]
20241118 20:11:41 - [INFO    ] - mediaitem.py         - 612  - |     + Property: inputstream=inputstream.adaptive
20241118 20:11:41 - [INFO    ] - mediaitem.py         - 612  - |     + Property: inputstream.adaptive.manifest_type=mpd
20241118 20:11:41 - [INFO    ] - mediaitem.py         - 612  - |     + Property: inputstream.adaptive.license_type=com.widevine.alpha
20241118 20:11:41 - [INFO    ] - mediaitem.py         - 612  - +     + Property: inputstream.adaptive.max_bandwidth=500000
20241118 20:12:11 - [WARNING ] - player.py            - 63   - Player: time-out occurred waiting for playback (30)
20241118 20:12:11 - [INFO    ] - addon.py             - 65   - Retrospect :: Flushing and closing logfile.

### Your Environment

- [ ] Android
- [ ] iOS
- [X] Linux
- [ ] OSX
- [ ] Raspberry-Pi
- [ ] Windows
- [ ] Windows UWP

### Kodi version

21.1

### Retrospect version

5.7.20

**Comment by basrieter** [comment]
I see, I will have a look at that.

**Comment by tcplomp** [comment]
Yes photo's are loading.

**Comment by basrieter** [comment]
I will push a new release soon.
