### ISSUE TITLE
Filter out HEVC

### ISSUE THREAD

**Issue by Frasknas** [retrospect-addon/plugin.video.retrospect#1865]
### Is your feature request related to a problem? Please describe

Hi. I am using Retrospect to stream from the swedish channels SVTplay and TV4play.

TV4play uses AVC streams.
SVTplay offers both AVC and HEVC streams.

My Raspberry (3B) renders AVC streams in 1920x1080 without any issues but totally chokes when I try to view a HEVC stream in the same resolution.

I have therefore been trying to get Retrospect to filter out the HEVC streams but have not found a way to do so.

If I disable the Adaptive Streams option I get an error message that it needs to be active if I open a TV4 stream. When it is active SVT play finds only HEVC streams.

I had a look in the log file. This is an extract from when I tried to play a stream from SVT:

```20241117 22:03:51 - [DEBUG   ] - addonsettings.py     - 724  - Using the Retrospect Default Bitrate: 0
20241117 22:03:51 - [INFO    ] - mediaitem.py         - 565  - Creating a Kodi ListItem for Bitrate: 0 kbps
20241117 22:03:51 - [INFO    ] - mediaitem.py         - 565  - | MediaItem: Avsnitt 1 [Type=episode, Complete=True, IsLive=False, Date=2024-11-02 02:00, Geo/DRM=True/False]
20241117 22:03:51 - [INFO    ] - mediaitem.py         - 565  - | MediaStream: https://svt-vod-3a.akamaized.net/d0/se/20241031/f65b0fea-3071-4d50-9f9e-242d0037d011/hls-ts-avc.m3u8 [bitrate=10]
20241117 22:03:51 - [INFO    ] - mediaitem.py         - 565  - |     + Property: inputstream=inputstream.adaptive
20241117 22:03:51 - [INFO    ] - mediaitem.py         - 565  - |     + Property: inputstream.adaptive.manifest_type=hls
20241117 22:03:51 - [INFO    ] - mediaitem.py         - 565  - | MediaStream: https://svt-vod-3a.akamaized.net/d0/se/20241031/f65b0fea-3071-4d50-9f9e-242d0037d011/dash-avc.mpd [bitrate=3]
20241117 22:03:51 - [INFO    ] - mediaitem.py         - 565  - |     + Property: inputstream=inputstream.adaptive
20241117 22:03:51 - [INFO    ] - mediaitem.py         - 565  - |     + Property: inputstream.adaptive.manifest_type=mpd
20241117 22:03:51 - [INFO    ] - mediaitem.py         - 565  - |     + Property: inputstream.adaptive.license_type=com.widevine.alpha
20241117 22:03:51 - [INFO    ] - mediaitem.py         - 565  - | MediaStream: https://svt-vod-3a.akamaized.net/d0/se/20241031/f65b0fea-3071-4d50-9f9e-242d0037d011/dash-hbbtv-avc.mpd [bitrate=4]
20241117 22:03:51 - [INFO    ] - mediaitem.py         - 565  - |     + Property: inputstream=inputstream.adaptive
20241117 22:03:51 - [INFO    ] - mediaitem.py         - 565  - |     + Property: inputstream.adaptive.manifest_type=mpd
20241117 22:03:51 - [INFO    ] - mediaitem.py         - 565  - |     + Property: inputstream.adaptive.license_type=com.widevine.alpha
20241117 22:03:51 - [INFO    ] - mediaitem.py         - 565  - | MediaStream: https://svt-vod-3a.akamaized.net/d0/se/20241031/f65b0fea-3071-4d50-9f9e-242d0037d011/hls-cmaf-full.m3u8 [bitrate=13]
20241117 22:03:51 - [INFO    ] - mediaitem.py         - 565  - |     + Property: inputstream=inputstream.adaptive
20241117 22:03:51 - [INFO    ] - mediaitem.py         - 565  - |     + Property: inputstream.adaptive.manifest_type=hls
20241117 22:03:51 - [INFO    ] - mediaitem.py         - 565  - | MediaStream: https://svt-vod-3a.akamaized.net/d0/se/20241031/f65b0fea-3071-4d50-9f9e-242d0037d011/hls-ts-full.m3u8 [bitrate=12]
20241117 22:03:51 - [INFO    ] - mediaitem.py         - 565  - |     + Property: inputstream=inputstream.adaptive
20241117 22:03:51 - [INFO    ] - mediaitem.py         - 565  - |     + Property: inputstream.adaptive.manifest_type=hls
20241117 22:03:51 - [INFO    ] - mediaitem.py         - 565  - |  + Subtitle: /home/osmc/.kodi/userdata/addon_data/plugin.video.retrospect/cache/106FE311F96C41D2C7552D62C84FE7A2.srt
20241117 22:03:51 - [INFO    ] - mediaitem.py         - 565  - + MediaType: episode
20241117 22:03:51 - [DEBUG   ] - mediaitem.py         - 645  - Returning the higest bitrate stream
20241117 22:03:51 - [INFO    ] - mediaitem.py         - 612  - Playing Stream: MediaStream: https://svt-vod-3a.akamaized.net/d0/se/20241031/f65b0fea-3071-4d50-9f9e-242d0037d011/hls-cmaf-full.m3u8 [bitrate=13]
20241117 22:03:51 - [INFO    ] - mediaitem.py         - 612  - |     + Property: inputstream=inputstream.adaptive
20241117 22:03:51 - [INFO    ] - mediaitem.py         - 612  - +     + Property: inputstream.adaptive.manifest_type=hls
```

I checked the m3u8 files. The one marked bitrate=10 contains only avc streams. The one marked bitrate=13 contains only hevc streams and the one marked bitrate=12 contains both avc and hevc.
I modified the settings xml and added 10 as a valid value for maximum bitrate. I was then allowed to set that value for the maxium bitrate setting and when I opened the stream it selected that m3u8 file and played the stream without any issues.

I assume bitrate is not really a good filtering mechanism. My understanding of the difference between avc and hevc is that the bitrate is the same, it is mainly the level of compression that differs. 

So, my question is, is is currently possible to prevent Retrospect from selecting hevc streams if there are avc streams available? If not, would it be hard to implement such a setting?

### Describe the solution/feature you'd like to see.

I would like a boolean setting that either allows or disallows hevc streams to be returned as valid options. If the setting is true it works just as today. If it is false the framework will only register m3u8 files that contains avc streams and filter out any hevc streams when deciding which stream to pick in the m3u8 file

**Comment by basrieter** [comment]
Please try: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/1865-filter-out-hevc.zip

**Comment by basrieter** [comment]
@Frasknas Can you verify if this solution works for you?

**Comment by Frasknas** [comment]
With your updated version everything works as it should again. Thanks!
