### ISSUE TITLE
Is the setting for how many hours after midnight the next day will be considered today removed?

### ISSUE THREAD

**Issue by ErikBrown2** [retrospect-addon/plugin.video.retrospect#1868]
### Is your feature request related to a problem? Please describe

Until two years ago or so it used to be that only at about 4 am the new day would become today in the listings. But you changed this so that the change over would happen at midnight.  And if I remember well you made a setting so that the user could define if the change to the next day should happen at midnight or later in the early morning.

The change at midnight kept on bothering me for quite some time and I wanted to use the setting to make the change over happen again at 4 am or so. The reason is that late in the evening you always have to look at the clock first before choosing yesterday or today which is a bit annoying.

But I am unable to find the setting. Is it indeed removed? If so, would it be possible to bring it back? Or if that is not possible, maybe you can consider setting the change over again at 4 am. If my memory serves me well, it was just one person asking to make the change over at midnight. But I think that for most users the change over at a time after they go to bed would make most sense.

**Comment by basrieter** [comment]
It was there, however: NPO change their API and I can no longer request a custom time range. So It can no longer be done!
