### ISSUE TITLE
Retrospect gets stuck on trying to fetch NPO Recent / guide listings

### ISSUE THREAD

**Issue by didamsko** [retrospect-addon/plugin.video.retrospect#1869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Retrospect gets hung up on trying to get NPO data. Maybe temporary error or something got changed. See log attached. 

### Steps to Reproduce

1. try to refresh Retrospect guide or fetch the Recent listings

### Debuglog

[retrospect.log](https://github.com/user-attachments/files/17988150/retrospect.log)

### Your Environment

- [ ] Android
- [ ] iOS
- [X] Linux
- [ ] OSX
- [ ] Raspberry-Pi
- [ ] Windows
- [ ] Windows UWP

### Kodi version

CoreELEC 21.1.1-Omega

### Retrospect version

Retrospect 5.7.21

**Comment by didamsko** [comment]
I think this bug report can be ignored. fetching the Recent listing and guide is working again. Seems that it was a temporary error.

**Comment by didamsko** [comment]
Closing it myself as it no longer needs attention.

**Comment by RichardPasmans** [comment]
yes, I confirm. It works again.
