### ISSUE TITLE
AT5 Nieuws items not showing up

### ISSUE THREAD

**Issue by didamsko** [retrospect-addon/plugin.video.retrospect#1870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Something not working with AT5 listings. Normally when i open the AT5 channel i have several items and among those 'AT5 Nieuws', when i choose that one i normally get a listing of the recent AT5 Nieuws episodes but now only the message '- No episodes found for the selected item -'.  Hope the functionality can be restored. 

### Steps to Reproduce

Open AT5 > AT5 Nieuws > - No episodes found for the selected item -

### Debuglog

[retrospect.debug.log](https://github.com/user-attachments/files/17991637/retrospect.debug.log)

### Your Environment

- [ ] Android
- [ ] iOS
- [X] Linux
- [ ] OSX
- [ ] Raspberry-Pi
- [ ] Windows
- [ ] Windows UWP

### Kodi version

CoreELEC 21.1.1-Omega

### Retrospect version

Retrospect 5.7.21

**Comment by basrieter** [comment]
Seems to work again? 

![image](https://github.com/user-attachments/assets/35e4455c-f160-4d55-93cd-abe2fc474fe5)

**Comment by didamsko** [comment]
Correct. And it seems that it continued to work. They apparently made changes to the website ([announced yesterday](https://www.at5.nl/artikelen/229833/de-website-van-at5-is-vernieuwd)) and that seems to have wiped all old AT5 Nieuws episodes. Normally there was a list going back multiple weeks. Maybe that will be building back up again. I hope it will :)
