### ISSUE TITLE
Het NPO 20:00 uur journaal werkt niet meer

### ISSUE THREAD

**Issue by ErikBrown2** [retrospect-addon/plugin.video.retrospect#1871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Het 20:00 uur journaal werkt niet meer via Recent. Het is wel te zien op de NPO website.

### Steps to Reproduce

- Ga naar NPO, Recent en selecteer 4-12 2024 (of een eerdere datum)
- Selecteer 20:00 - NPO1 - NOS Journaal
- Zie de foutmeldingen: Retrospect Error Cannot start playback  en  One or more items failed to play. Check the log for more information about this message. 

### Debuglog

https://paste.kodi.tv/udijifewav

### Your Environment

- [ ] Android
- [ ] iOS
- [X] Linux
- [ ] OSX
- [ ] Raspberry-Pi
- [ ] Windows
- [ ] Windows UWP

### Kodi version

21.1.0

### Retrospect version

5.7.21

**Comment by Heleen-Heleen** [comment]
![Screenshot_20241205-091447](https://github.com/user-attachments/assets/bc5da075-f356-4dd9-bb0b-8bb5623b5def)

Via NPO start werkt het wel

**Comment by basrieter** [comment]
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/1871-het-npo-2000-uur-journaal-werkt-niet-meer.zip and double check the right episodes start playing. This impact ALL EPG streams.

**Comment by ErikBrown2** [comment]
Hartelijk dank Bas, het werkt inderdaad weer.

**Comment by ErikBrown2** [comment]
Alle andere programma's van 5-12-2024 spelen wel af of geven een andere foutmelding. De programma's die niet afspelen zijn:

05:40 - NPO3 - Maya de bij - Dit programma is alleen te zien met een NPO Plus account
06:44 - NPO - Kiwi & Strit - Dit programma is alleen te zien met een NPO Plus account
11:13 - NPO3 - Peppa Pig - Dit programma is alleen te zien met een NPO Plus account
13:50 - NPO3 - Molmans - Dit programma is alleen te zien met een NPO Plus account
14:35 - NPO3 - Barnkidz - Dit programma is alleen te zien met een NPO Plus account
15:35 - NPO3 - Peperbollen - Dit programma is alleen te zien met een NPO Plus account
16:50 - NPO3 - A kind of spark - Dit programma mag nog niet of niet meer bekeken worden.

En dit programma speelt af in 1080p ondanks dat ik geen plus account heb:
21:40 - NPO1 - De toeslagenaffaire

**Comment by basrieter** [comment]
Ok, geen probleem. Ik ga er nog even naar kijken vanavond.

**Comment by basrieter** [comment]
Kan je https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/1871-het-npo-2000-uur-journaal-werkt-niet-meer.zip  nog eens proberen?

**Comment by ErikBrown2** [comment]
Ja, nu werken alle journaal episodes inderdaad weer. Dank je wel Bas.

**Comment by basrieter** [comment]
Ik ga kijken wanneer ik een release kan doen.
