### ISSUE TITLE
Tweede kamer debat direct heeft geen audio

### ISSUE THREAD

**Issue by ErikBrown2** [retrospect-addon/plugin.video.retrospect#1872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Ten eerste, hartelijk dank dat je deze streams hebt toegevoegd aan Retrospect. Het zal een fijne manier zijn om de debatten te kunnen volgen op de TV.

De debatten in Debatten terugkijken hebben geen audio. Er zijn nu geen uitzendingen op de live streams dus ik weet niet zeker of daar wel audio is maar het lijkt er op dat dat niet zo is want als ik op 'O' op mijn toetsenbord druk dan zie ik daar ook (net als bij de Debatten terugkijken) voor audio:

Audio process information
Decoder: unknown, 0bit, 0Hz
Channels: unknown 

Op de website is er wel audio voor dezelfde debatten.

### Steps to Reproduce

- Ga naar Video, Tweede Kamer Debat Direct, Debatten terugkijken
- Selecteer 2024-12-04 - Wednesday (17 debatten)
- Selecteer 10:00 - Stikstof, NPLG en natuur (of een ander debat)
- Merk dat er wel video is maar geen audio.
 

### Debuglog

https://paste.kodi.tv/yijejuwipe

### Screenshots

![screenshot02109](https://github.com/user-attachments/assets/fe88e6a1-51fb-4858-b4a3-18c3adcae611)

### Your Environment

- [ ] Android
- [ ] iOS
- [X] Linux
- [ ] OSX
- [ ] Raspberry-Pi
- [ ] Windows
- [ ] Windows UWP

### Kodi version

21.1.0

### Retrospect version

5.7.21

**Comment by basrieter** [comment]
Please check https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/1871-het-npo-2000-uur-journaal-werkt-niet-meer.zip it should include a fix.

**Comment by ErikBrown2** [comment]
Dank je wel Bas, nu werkt het audio inderdaad.

**Comment by basrieter** [comment]
Ik ga kijken wanneer ik een release kan doen.
