### ISSUE TITLE
Wissen van zoektermen

### ISSUE THREAD

**Issue by Johpin1** [retrospect-addon/plugin.video.retrospect#1874]
### Is your feature request related to a problem? Please describe

In het contextmenu bij zoeken is de optie verwijderen of hernoemen niet aanwezig .

### Describe the solution/feature you'd like to see.

Wissen of hernoemen van zoektermen mogelijk maken

### Describe alternatives you've considered.

Zoiets contextmenu had ik verwacht:
![screen_3](https://github.com/user-attachments/assets/cc88699a-9ef1-4a8b-91bc-4a7ab50b522f)
### Additional context
in plaats van
![screen_1](https://github.com/user-attachments/assets/1b21e4d3-793d-4da3-ad4b-eaba0b756d98)

**Comment by basrieter** [comment]
Dat klopt inderdaad, het is niet bedoeld als een statisch lijst of een lijst die je kunt beheren. 

Het opschonen van de lijst gebeurt automatisch. Als het goed is onthoudt Retrospect de laatste 10 zoekopdrachten. De oudste worden steeds verwijderd. 

Wel is het mogelijk een zoek opdracht als Kodi favoriet toe te voegen en deze zijn dan volgens mij daar te hernoemen.

**Comment by basrieter** [comment]
Het wissen zou wellicht kunnen, maar beheren of hernoemen gaat er niet in komen. "ververs lijst" is gewoon een generiek context menu item, dus die laat ik ook voor wat het is.

**Comment by Johpin1** [comment]
"Wissen" en "Opschonen zoekhistorie (alles wissen)" zou al mooi zijn.

**Comment by basrieter** [comment]
Ik ga kijken

**Comment by basrieter** [comment]
Kan je deze proberen: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/1874-wissen-van-zoektermen.zip

Je zult Kodi moeten herstarten om het context menu opnieuw te initialiseren. 

![image](https://github.com/user-attachments/assets/2d2b65be-6a5a-44ff-9c95-ccbb135d36a0)

**Comment by Johpin1** [comment]
Het werkt prima. Alleen de Nederlandse vertaling ontbreekt nog. Bedankt in ieder geval!

**Comment by basrieter** [comment]
> Het werkt prima. Alleen de Nederlandse vertaling ontbreekt nog. Bedankt in ieder geval!

Top. De Nederlandse vertaling ga ik uiteraard ook toevoegen. Dit is stapje 1!

**Comment by basrieter** [comment]
```
msgctxt "#30377"
msgid "Zoekhistorie wissen"
msgstr ""

msgctxt "#30378"
msgid "Verwijder zoek-item"
msgstr ""
```

Klinken deze logisch?

**Comment by Johpin1** [comment]
"Zoekhistorie wissen" lijkt mij prima.

 "verwijder zoek-item"  zou denk ik kunnen worden verkort tot "Verwijder", net zoals bij de Youtube addon.

**Comment by basrieter** [comment]
Vertaling zou er nu in moeten zitten: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/1874-wissen-van-zoektermen.zip

**Comment by Johpin1** [comment]
Het blijft in de Engelse taal.

Aanpassen van de syntax naar:

```
msgctxt "#30377"
msgid "Clear Search History"
msgstr "Zoekhistorie wissen"

msgctxt "#30378"
msgid "Remove Search Item"
msgstr "Verwijder"
```
Daarmee wordt "Zoekhistorie wissen" zichtbaar, maar "Remove Search Item" blijft onveranderd.

**Comment by Johpin1** [comment]
Het contextmenu is nu volledig in het Nederlands. Nu  kan ik de lijst met zoektermen opschonen en wissen. Bedankt hiervoor. 

Dit kan nu worden afgesloten.

**Comment by basrieter** [comment]
Will push an official release soon.
