### ISSUE TITLE
Add www.itvonline.nl to XOT for KPN subscribers

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#378]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/378) by Anonymous.**

----------------------------------------

In the Netherlands we have a handfull of cable companies they all provide televison online now.  
  
I see (and try to help out)the addon for UPC is in the making(i'm a UPC user)  
  
The majority of the people in the Netherland uses UPC (www.horizon.tv) or KPN (www.itvonline.nl)  
Is it an idea to also make a plugin for KPN (www.itvonline.nl)to??  
  
I'm not a KPN user so i cannot help out with any files.  
Just puttin it out there.  
  
----  
Original item http://code.google.com/p/xot-uzg/issues/detail?id=378

**Comment by dagwieers** [comment]
Should this not be labeled "channel"?
cc @brjhaverkamp
