### ISSUE TITLE
Add Disney channel

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#534]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/534) by Sopor (Bitbucket: [Sopor](https://bitbucket.org/Sopor), GitHub: [Sopor](https://github.com/Sopor)).**

----------------------------------------

----
Will you add Disney Channel?
----
In Sweden it's this url: http://www.disney.se/disney-channel/program
but I think that will change depending on where you live?
http://play.disney.se/disney-channel seems to be down but you can access all there programs from this page http://www.disney.se/disney-channel/play#/videoId/violetta-avsnitt-78-del-1

**Comment by dagwieers** [comment]
Should this not be labeled "channel"?
cc @Sopor
