### ISSUE TITLE
Please add Kanal 10 Sweden

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#585]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/585) by Henrik Nyberg (Bitbucket: [extasy](https://bitbucket.org/extasy), GitHub: [extasy](https://github.com/extasy)).**

----------------------------------------

Please add this Kanal 10 Sweden to your excellent app. Streem can be found at:
http://kanal10.se/webbtv

Kind regards
Henrik

**Comment by dagwieers** [comment]
Should this not be labeled "channel"?
cc @extasy

**Comment by Snaah** [comment]
Think this could be closed. It's been almost 5 years and no catchup content yet. @extasy
