### ISSUE TITLE
Channel request: Tweede kamer debatten

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#617]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/617) by Meram annoniem (Bitbucket: [Meram](https://bitbucket.org/Meram), GitHub: [Meram](https://github.com/Meram)).**

----------------------------------------

Dear Bas,

Could you integrate the Tweede kamer debatten gemist  in to TV Online? 
http://debatgemist.tweedekamer.nl/debatten/

Regards

Graaf Tel (Aram)

**Comment by dagwieers** [comment]
Should this not be labeled "channel"?
cc @Meram
