### ISSUE TITLE
Slam FM not working

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#667]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/667) by Kodi_Vincent (Bitbucket: [Kodi_Vincent](https://bitbucket.org/Kodi_Vincent), ).**

----------------------------------------

There seems to be a bit of HTML code when opening the stream?
For example (see log): http://www.slamfm.nl/slamplayer/<!DOCTYPE html>
This is not working.
A working stream is: http://edge2-icecast.538.lw.triple-it.nl/SLAMFM_MP3
Could you replace this in Retrospect, please?

Windows 10 & Kodi 15.1
Slam FM! 
Netherlands

**Comment by finnie2006** [comment]
Will Slam (fm) every get back?
