### ISSUE TITLE
Channel request: KZOOM

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#761]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/761) by lovecrafthp (Bitbucket: [lovecrafthp](https://bitbucket.org/lovecrafthp), GitHub: [lovecrafthp](https://github.com/lovecrafthp)).**

----------------------------------------

Flemish TV channel with lots of free content. You need to log in in order to view the content (cf. Vier).

Website: http://www.kzoom.be

Android store: https://play.google.com/store/apps/details?id=be.medialaan.vtmkzoom

Thanks for looking into it!

**Comment by dagwieers** [comment]
The KZOOM content (now VTM Kids) is available from the new VTM GO plugin at: https://github.com/michaelarnauts/plugin.video.vtm.go

Beware that this plugin still has issues with most content, but the Kids content works perfect (and even at 1080p !)

**Comment by dagwieers** [comment]
Moet dit niet label "channel" krijgen?

**Comment by dagwieers** [comment]
cc @lovecrafthp

**Comment by michaelarnauts** [comment]
I think this could be marked as a duplicate of #1141

**Comment by basrieter** [comment]
This is indeed a duplicate of #1141 as it is included in VTM GO

**Comment by basrieter** [comment]
Duplicate of #1141
