### ISSUE TITLE
Add Chanel http://tv-ekkergem.be/

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#814]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/814) by Geert (Bitbucket: [slashbot28](https://bitbucket.org/slashbot28), ).**

----------------------------------------

Request to add http://tv-ekkergem.be/
Is a website with video's made from people from Gent Belgium And already up for a few years. No idea if u want to add it to retrospect but it would-be nice.

**Comment by dagwieers** [comment]
Either we should close this, or add YouTube channel support to Retrospect and add this ;-)

**Comment by basrieter** [comment]
I will close it then, as it makes no sense to add a Youtube channel here. There are other add-ons for that.
