### ISSUE TITLE
Complimenten (lof)

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#895]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/895) by P.A. Blok (Bitbucket: [kubus1953](https://bitbucket.org/kubus1953), ).**

----------------------------------------

Ik had het grote genoegen gisterenavond op mijn oude raspberry B met Kodi en Retrospect naar de live uitzending van de VPRO te kijken. Zonder gestotter etc die het leven van televisiekijken op de pc tot een hel maken. Dat noemt zich publieke omroep.

U heer Rieter, of beste Bas, verdient alle lof voor hetgeen u mogelijk maakt. Dank, dank. 

Met vriendelijke groet

**Comment by dagwieers** [comment]
cc @blowk @lovecrafthp @peno64 @robbinwehl @Phyxion @ErikBrown

**Comment by TomHillaert** [comment]
Yes, dikke duim voor Bas en de anderen die hier dagelijks aan werken
