### ISSUE TITLE
SVT's new sorting of folders

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#909]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/909) by Snah (Bitbucket: [Snaah](https://bitbucket.org/Snaah), GitHub: [Snaah](https://github.com/Snaah)).**

----------------------------------------

SVT has started sorting episodes in folders by year. This is good for some programmes, like Grotesco (folders 2007, 2010 and 2017, corresponds to S01, S02 and S03), but for programmes that only have episodes in 2017 available it is just a pointless extra click. Example: Aktuellt and Rapport (both news programmes), and Veckans brott (weekly true crime). Possible to have Retrospect check if there's only episodes in one folder (2017) available and make them show in the root directory of the programme? Instead of "SVT/Aktuellt/2017/[episode], it would be "SVT/Aktuellt/[episode]".

(I don't add a log as I assume it is not necessary. Will do if you need it.)

**Comment by dagwieers** [comment]
cc @snaah @sopo @SteXen

**Comment by Snaah** [comment]
SVT has once again started putting an unnecessary "Avsnitt" folder. Would be great to have this fixed when you have the time, @basrieter.

I've already discussed this with @Sopor and we agree.

This post is lenghty. There's no rush. Just ask if I need to clarify something.

_Summary of the suggestion below_
- folders named "Senaste" or "Senaste sänt" are removed
- empty folders are removed
- folders matching exactly "Avsnitt" are removed

- if user wants to, either all [year] folders or only [present year] folders are removed
- if user wants to, all content of single "Avsnitt" folders removed and the content is shown in the root

**Revised suggestion:**

_Options_
1. Don't show [year] folders when there's only one? (option 1a)
Only remove [present year] folders? (Option 1b) 
2. Don't show season folders when there's only one? (option 2)

If none of the options are selected, Retrospect shows listings as it does now but with 1-3 below.

_Retrospect_

1-3 are run regardless of options.

1. Is there a folder named "Senaste sänt" or "Senaste"? If yes, remove it.
2. Are there empty folders? If yes, remove them.
3. Is there a single folder named exactly "Avsnitt"? Show it's content in the root. (Important: This mustn't catch "Avsnitt [year]" folders.)

Optional:
4. If user has selected to remove year folders:
Is there only one remaining folder (besides possibly "Klipp") and its name matches a year? If yes, check if user wants to remove only [present year] (option 1b).
4.a option 1.a selected: Remove the year folder and show its content in the root.
4.b option 1.b selected: Does the remaining folder match [present year]? If yes, show its content in the root.
5. option 2 selected: Does the remaining folder match "Säsong [X]"? If yes, show the content in the root.

_Examples_

Year folder [NOT present year]:
https://www.svtplay.se/brasa

"Klipp" and [Present year]:
https://www.svtplay.se/aktuellt
https://www.svtplay.se/rapport
https://www.svtplay.se/babel
https://www.svtplay.se/allt-for-sverige

"Klipp", [Present year] and one more folder:
https://www.svtplay.se/agenda

Empty "Klipp" folder:
https://www.svtplay.se/allt-jag-inte-minns

Only one "Säsong" folder:
https://www.svtplay.se/allt-jag-inte-minns

Only one "Säsong" folder and one more folder:
https://www.svtplay.se/vi-overlevde-r-kelly

More than one "Säsong" folder:
https://www.svtplay.se/andra-aket
https://www.svtplay.se/alex-hittar-hobbyn
https://www.svtplay.se/alfons-aberg

"Avsnitt":
https://www.svtplay.se/militarligan

"Avsnitt [year]":
https://www.svtplay.se/allsang-pa-skansen

More than one [year] folder:
https://www.svtplay.se/100-vaken
https://www.svtplay.se/abel-och-fant
https://www.svtplay.se/albert-och-herbert

Couldn't find any "Senaste sänt" or "Senaste", but I've seen them and better safe than sorry.

(Sole folders content are currently shown in the root, which is good.) 

If this will be implemented, it can be adjusted to match other channels too (from other countries as well). I can do the strings needed in Swedish and English.

**Comment by basrieter** [comment]
Good that you both agree. I need some time for this. Which is currently very sparse. Next week I can check. However, I don't think I can prevent 'empty' folders as I can't know beforehand if a folder will be empty.

**Comment by Snaah** [comment]
I think so too! Your workload is totally understandable. Take your time, this is not crucial at all.

Ok on the empty folders.
