### ISSUE TITLE
SVTPlay - undertext och uppläst text

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#946]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/946) by Sopor (Bitbucket: [Sopor](https://bitbucket.org/Sopor), GitHub: [Sopor](https://github.com/Sopor)).**

----------------------------------------

On SVTPlay "Kanaler" it is now possible to remove subtitles and even let a voice read it for you if you have trouble to see it.
To get a voice to read it there need to be a second soundtrack but i can't find that in Kodi. I can only find one soundtrack and the subtitle can't be turned off as it is now.
Could this be added to Retrospect?

**Comment by dagwieers** [comment]
cc @sopor

**Comment by Sopor** [comment]
SVT also have sign language interpretation that would be nice to add.

**Comment by basrieter** [comment]
Is this still valid @Sopor?

**Comment by Sopor** [comment]
You can close it!
