### ISSUE TITLE
Merge TV4, Sjuan and TV12 in to one channel

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#965]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/965) by Sopor (Bitbucket: [Sopor](https://bitbucket.org/Sopor), GitHub: [Sopor](https://github.com/Sopor)).**

----------------------------------------

Now when you have merged Viafree and Dplay, could you do the same for TV4, Sjuan and TV12? The name for them could be [TV4-gruppen](https://sv.wikipedia.org/wiki/TV4-gruppen). You should also remove (TV7) you have added after "Sjuan" because it is not the same channel.

**Comment by dagwieers** [comment]
cc @sopor

**Comment by peakdeveploer** [comment]
Why merge?

**Comment by Sopor** [comment]
@peakdeveploer Why not? Viafree and Dplay have one so why not TV4? TV12 have only a few channels, so instead of trying to find the program i want by searching on TV4, Sjuan and TV12 i do it in one common channel. Same thing if i want to browse though the programs. Now i need to open TV4, Sjuan and TV12... Really annoying...

**Comment by basrieter** [comment]
If I merge them, I will also keep the original channels. Just like Dplay. Users can hide the separate channels if they prefer.

**Comment by orfeous1** [comment]
I dont want the merging either.
Good as it is for me.

**Comment by Snaah** [comment]
@orfeous1 @peakdeveploer I believe both of you don't get this suggestion.

Right now there's both Dplay and Viafree as separate channels, containing all programs of all the channels of each network. All of Viafree's and Dplay's channels are also available as separate channels. You can hide or show channels as you like, including the channels Dplay and Viafree.

A separate channel for TV4-gruppen, containing all of the networks programs, will work the same. You can hide it if you like. The separate channels for TV4, Sjuan etc. will still be there. 

The benefit for users who want to have TV4-gruppen as a separate channel is obviously the same as for having Dplay or Viafree. Why is this not good?

**Comment by basrieter** [comment]
Exactly what @snaah says! I will perhaps add a new combined channel. But not remove the others.

**Comment by basrieter** [comment]
Fixing this with #1340
